### ISSUE TITLE
（汗）他发不出语音

### ISSUE THREAD

**Issue by Adsicmes** [HibiKier/zhenxun_bot#10]
![image](https://user-images.githubusercontent.com/79645438/125967975-48d1b8ab-0c6e-46a1-9e70-933c8d4929a4.png)

**Comment by HibiKier** [comment]
安装ffmpeg

**Comment by Adsicmes** [comment]
谢谢，我尝试去换一下linux

**Comment by Adsicmes** [comment]
您的运行环境是？

**Comment by HibiKier** [comment]
centos7
