### ISSUE TITLE
安装成功后 使用python bot.py 运行出现错误

### ISSUE THREAD

**Issue by xianyongjian080402** [HibiKier/zhenxun_bot#1002]
### 错误截图

![截屏2022-08-18 09 47 50](https://user-images.githubusercontent.com/70191815/185274227-7fcf60c9-7aa8-4982-a100-09de3933458c.png)

### 日志截图

无日志（日志为空）

### 错误说明

我一个朋友在两天前发起了 https://github.com/HibiKier/zhenxun_bot/issues/999 我使用了虚拟环境后解决了这个问题 但是在使用python bot.py运行后 出现 `ModuleNotFoundError: No module named 'configs.config'`错误 我使用pip确认了这个库在虚拟环境中是安装了的（我试过卸载重装 依然没用）

我也试过不使用虚拟环境 但是会出现 https://github.com/HibiKier/zhenxun_bot/issues/999 所以我只好使用虚拟环境 (这样 在使用poetry install安装时不会报错)

python版本：3.9.13

**Comment by SEVEN-6174** [comment]
运行是在虚拟环境里面的吗（如poetry shell
python bot.py
或poetry run bot.py）
这个configs不是pip的库，是真寻根目录下configs里面的
如果是在虚拟环境里面的，可以试试进环境卸载configs库再运行

**Comment by HibiKier** [comment]
你项目文件没下全

**Comment by xianyongjian080402** [comment]
> 你的项目文件没下全

哈？好的 我跟我朋友说下（他下载的）

**Comment by xianyongjian080402** [comment]
> 你项目文件没下全

我朋友是他克隆下来的
