### ISSUE TITLE
b站主播订阅使用短号时添加订阅失败

### ISSUE THREAD

**Issue by q56535** [HibiKier/zhenxun_bot#1003]
### 错误截图

![image](https://user-images.githubusercontent.com/26663837/185433833-1bc96c14-fcdf-4e5d-9df1-4dc4bf0ad502.png)
![image](https://user-images.githubusercontent.com/26663837/185433937-378a2b7f-93b4-4d04-b474-13e061e913b3.png)

### 日志截图

![image](https://user-images.githubusercontent.com/26663837/185433557-ab90750e-9ca6-47cc-a3be-7d130bd8b38b.png)

### 错误说明

使用b站订阅直播时，必须使用原直播间号，不能识别短号

**Comment by HibiKier** [comment]
1a17e88142a880044b4cdd7f63fc68ef375947ac
