### ISSUE TITLE
b站转发解析无法解析av号

### ISSUE THREAD

**Issue by q56535** [HibiKier/zhenxun_bot#1004]
### 错误截图

![image](https://user-images.githubusercontent.com/26663837/185437591-81f46138-8462-4105-ae23-c3aa2e6c93b6.png)
![image](https://user-images.githubusercontent.com/26663837/185437668-5bec5e1a-bb83-408f-9e3e-c5a2737ec985.png)

### 日志截图

![image](https://user-images.githubusercontent.com/26663837/185436759-e1be5937-ed68-46b7-9fe0-e41432b987ea.png)
![image](https://user-images.githubusercontent.com/26663837/185436994-c92a3ea4-5600-4b91-ace8-b24dae3e18a6.png)

### 错误说明

转发解析识别长的av号之后返回为无效av号或bv号，短的av号则无反应，只能识别bv号

**Comment by HibiKier** [comment]
f3b6b0ee3b0b9f0f9754366c10cb5d9771375eb4
