### ISSUE TITLE
管理员关闭B站转发解析后bot仍能响应BV号

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#1006]
### 系统版本：
![image](https://user-images.githubusercontent.com/105090141/185763152-29a90ac9-c619-4216-8d41-45b83dc535c7.png)

### 真寻版本：
https://github.com/HibiKier/zhenxun_bot/commit/ca78e32d97b6fccedd8692a7a30d910a91e9d169

### 错误截图
![image](https://user-images.githubusercontent.com/105090141/185763054-aa2301fb-f36c-473e-8be2-b0b929d5cb1b.png)

### 日志截图
![image](https://user-images.githubusercontent.com/105090141/185763089-2eeea0c3-b281-4e6c-9877-e766761e60fb.png)

### 错误说明
管理员关闭该功能后，普通群员发送BV号仍能被解析

**Comment by HibiKier** [comment]
b站转发解析
