### ISSUE TITLE
插件过多后 生成简单帮助图片重叠

### ISSUE THREAD

**Issue by ChenPiTang-Hui** [HibiKier/zhenxun_bot#1007]
### 错误截图
![_W%8@M{EC)1)% M8WKHY C8](https://user-images.githubusercontent.com/69108232/185780311-6bd845ea-aaf5-4892-b552-58ae758f9f2d.PNG)

### 错误说明

帮助重叠

**Comment by HibiKier** [comment]
49e38862afadeae779534bacc32f78be0fd5775f
