### ISSUE TITLE
词库问答匹配问题

### ISSUE THREAD

**Issue by LambdaYH** [HibiKier/zhenxun_bot#1009]
### 真寻版本：最新

1. https://github.com/HibiKier/zhenxun_bot/blob/708e91206958aa8683b5fde2ae452e2069caf1b1/plugins/word_bank/_data_source.py#L201 
这一行加入了`_[OK`为非法正则表达式，然后运行下面这个语句时候就会出错
https://github.com/HibiKier/zhenxun_bot/blob/708e91206958aa8683b5fde2ae452e2069caf1b1/plugins/word_bank/_model.py#L240
看了下执行计划，出错的原因是先进行了正则匹配再进行`word_type`判断
~~可能是被优化了~~
```
explain SELECT * FROM public.word_bank2 where 1 = 1 and (word_type = 2 and group_id = xxxxxxx or word_scope = 0) and 'test_msg' ~ problem;
                                                       QUERY PLAN                                                        
-------------------------------------------------------------------------------------------------------------------------
 Seq Scan on word_bank2  (cost=0.00..18.20 rows=1 width=169)
   Filter: (('test_msg'::text ~ (problem)::text) AND (((word_type = 2) AND (group_id = xxxxxx)) OR (word_scope = 0)))
(2 rows)
```
> 另外为什么模糊匹配也是用正则不用like
~~似乎添加正则时候也需要检测一下正则语法~~

**Comment by HibiKier** [comment]
like会快些，后面再改，报错已经提供了额外限制条件了

**Comment by HibiKier** [comment]
2051e8183c74f0e7d6361a1e2d82125813366fcd
