### ISSUE TITLE
关于CSGO开箱和金币的关联建议

### ISSUE THREAD

**Issue by VoplsX** [HibiKier/zhenxun_bot#101]
不知道能不能将每日签到的金币用来买CSGO开箱的次数，目前金币的功能性确实比较少，如果能将金币用于购买CSGO开箱，比如每天可以免费开10次，然后每20金币开一次，开出金色能返多少金币。这样或许能提高获得金币的积极性:)

**Comment by HibiKier** [comment]
给plugin_settings中提供了cost_gold的配置项，不过查看等数据也会扣钱，等重构至beat1后应该有办法对单独的matcher进行限制

**Comment by VoplsX** [comment]
十分感谢 加油！
