### ISSUE TITLE
更新0.1.6.3后basic_plugins配置文件出错

### ISSUE THREAD

**Issue by ayakasuki** [HibiKier/zhenxun_bot#1015]
### 错误截图
![({42VK4$8MEV5 X}`2 373S](https://user-images.githubusercontent.com/20859971/185813019-e5ef5e4d-b27f-4b7e-be77-d11f0e51b901.png)

[img]

### 日志截图

[img]

### 错误说明
![)UN{)J14EXIPTA~P ~ZBCGP](https://user-images.githubusercontent.com/20859971/185813025-9e718094-d9e1-471e-8f49-aa8f824ef1bf.png)

好像是这地方改动引起无法配置模块文件

**Comment by ayakasuki** [comment]
![%)3GJPIS8Z48GUU5VVVS(MS](https://user-images.githubusercontent.com/20859971/185813377-2876e2b2-26e1-4fdb-87c1-804afca40a7b.png)
这个pull出错 替换回更新前的backup备份的就能运行

**Comment by ayakasuki** [comment]
检查后是nonebot更新到了beta4没事了 关了

**Comment by Pumpkin-N** [comment]
请问这个应该这么解决啊

**Comment by ayakasuki** [comment]
更新nonebot



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月22日 19:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 更新0.1.6.3后basic_plugins配置文件出错 (Issue #1015) |

请问这个应该这么解决啊
