### ISSUE TITLE
relation "word_bank" does not exist

### ISSUE THREAD

**Issue by tkgs0** [HibiKier/zhenxun_bot#1018]
### 错误截图

![Screenshot_20220822_082857_com termux](https://user-images.githubusercontent.com/107618388/185818870-03252768-358f-4668-801e-31b706c34f16.jpg)

### 错误说明

初次使用真寻，报错：relation "word_bank" does not exist  
无法运行  
  
删除plugins里的word_bank插件后能够正常运行

**Comment by HibiKier** [comment]
再启动一次还有报错吗，还是不行就把word_bank里的old_model删了

**Comment by tkgs0** [comment]
> 再启动一次还有报错吗，还是不行就把word_bank里的old_model删了

重启真寻后报错依旧，删除old_model后再次重启后能够正常运行了。非常感谢您的解答
