### ISSUE TITLE
0.1.63版本运行异常

### ISSUE THREAD

**Issue by lw1583003217** [HibiKier/zhenxun_bot#1019]
### 错误截图
![123qwe](https://user-images.githubusercontent.com/26614997/185844332-838bede4-6edd-4932-a8d4-b89a7edcd47f.png)

### 错误说明
更新之后，启动失败

**Comment by arare18** [comment]
我也这样

**Comment by Loukyuu1120** [comment]
一样的问题

**Comment by HibiKier** [comment]
更新nonebot

**Comment by ChocolateSerein** [comment]
SyntaxError: Non-ASCII character '\xe4' in file bot.py on line 11, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
我显示了这玩意

**Comment by lw1583003217** [comment]
> 更新nonebot

![image](https://user-images.githubusercontent.com/26614997/185877701-3640c87e-a567-4186-8fd1-6c7458097e90.png)
升级了，还是一样

**Comment by ChocolateSerein** [comment]
我现在0.16.2也出问题了，读完条之后直接退出了
![QQ图片20220822184735](https://user-images.githubusercontent.com/108963981/185903698-01a3270e-fb81-4678-a343-b90a60e011e6.png)

**Comment by flower-knight** [comment]
> 我现在0.16.2也出问题了，读完条之后直接退出了 ![QQ图片20220822184735](https://user-images.githubusercontent.com/108963981/185903698-01a3270e-fb81-4678-a343-b90a60e011e6.png)

你这个报的错不是说地址已经被使用了吗，你看看是不是有程序占用了8080端口

**Comment by HibiKier** [comment]
> > 更新nonebot
> 
> ![image](https://user-images.githubusercontent.com/26614997/185877701-3640c87e-a567-4186-8fd1-6c7458097e90.png) 升级了，还是一样

在对应虚拟环境重启了？

**Comment by lw1583003217** [comment]
> 

ok，跑起来了

**Comment by Pumpkin-N** [comment]
> > 
> 
> ok，跑起来了

怎么搞的呀兄弟，我也是更新nonebot之后也还是这样

**Comment by lw1583003217** [comment]
> 

升级nonebot版本

**Comment by lw1583003217** [comment]
> > > 
> > 
> > 
> > ok，跑起来了
> 
> 怎么搞的呀兄弟，我也是更新nonebot之后也还是这样

升级nonebot版本

**Comment by Pumpkin-N** [comment]
> > > > 
> > > 
> > > 
> > > ok，跑起来了
> > 
> > 
> > 怎么搞的呀兄弟，我也是更新nonebot之后也还是这样
> 
> 升级nonebot版本
兄弟你的版本现在是多少

**Comment by lw1583003217** [comment]
> > > > > 
> > > > 
> > > > 
> > > > ok，跑起来了
> > > 
> > > 
> > > 怎么搞的呀兄弟，我也是更新nonebot之后也还是这样
> > 
> > 
> > 升级nonebot版本
> > 兄弟你的版本现在是多少

nonebot最新版 2.0.0b5

**Comment by Pumpkin-N** [comment]
> 

好的谢谢
