### ISSUE TITLE
cos功能还是报错

### ISSUE THREAD

**Issue by modeilan** [HibiKier/zhenxun_bot#1020]
### 错误截图

[img]

### 日志截图

[img]
![image](https://user-images.githubusercontent.com/106938600/185846991-798a3693-8f4a-4065-9234-e7ac72826741.png)

### 错误说明

发生了xx错误...

**Comment by xiayingLIULI** [comment]
看看gocq，有可能是被风控了

**Comment by modeilan** [comment]
> 看看gocq，有可能是被风控了

gocq显示消息为空发送失败，其他的色图啥的都正常

**Comment by xiayingLIULI** [comment]
也有可能是COS的API访问不了了，自己找一个换上。

**Comment by q56535** [comment]
这个解决方法很简单，再gocq的配置加上代理

**Comment by q56535** [comment]
具体位置在`config.yml`里面的`proxy-rewrite`

**Comment by modeilan** [comment]
> 具体位置在`config.yml`里面的`proxy-rewrite`

gocq的代理么，支持http不

**Comment by q56535** [comment]
> > 具体位置在`config.yml`里面的`proxy-rewrite`
> 
> gocq的代理么，支持http不

支持

**Comment by q56535** [comment]
记得加上英文单引号

**Comment by modeilan** [comment]
> > > 具体位置在`config.yml`里面的`proxy-rewrite`
> > 
> > 
> > gocq的代理么，支持http不
> 
> 支持

好的大佬我试试
