### ISSUE TITLE
请问B站订阅无法删除其他群友的订阅吗

### ISSUE THREAD

**Issue by TonokoTakatsuki** [HibiKier/zhenxun_bot#1023]
如题，只能删除自己订阅的，删除其他群友订阅的就会显示“删除订阅id：****** 失败...”

**Comment by qq351959684** [comment]
确实，楼主解决了吗

**Comment by TonokoTakatsuki** [comment]
> 
还没有。。。
我暂且把模块关了，但貌似已订阅的还是会不断推送（悲

**Comment by TonokoTakatsuki** [comment]
> 确实，楼主解决了吗

还没有。。。
我暂且把模块关了，但貌似已订阅的还是会不断推送（悲

**Comment by HibiKier** [comment]
1138a115cef0251b4a79f0654379436b907a7509
