### ISSUE TITLE
get_config函数错误

### ISSUE THREAD

**Issue by wse320** [HibiKier/zhenxun_bot#1025]
### 错误截图
![image](https://user-images.githubusercontent.com/27719438/185926121-38add31a-64e9-479c-a08e-a06270b5f3df.png)

### 日志截图

![image](https://user-images.githubusercontent.com/27719438/185926756-8f2d7758-4861-4cd4-963f-9157f963a4d2.png)

### 错误说明
0.1.6.3版本中凡是调用到config里__init__.py的get_config函数的模块必定出问题，替换回上一版的该函数后所有功能恢复正常

**Comment by HibiKier** [comment]
6c9376983870a27a0322f738ae6f95590368d44b
