### ISSUE TITLE
模糊匹配用contains似乎逻辑有点问题

### ISSUE THREAD

**Issue by LambdaYH** [HibiKier/zhenxun_bot#1026]
https://github.com/HibiKier/zhenxun_bot/blob/82fe59e46900e6ec78ab7625826cc0cdd8c0217c/plugins/word_bank/_model.py#L243
这句意思应该是**数据库problem属性**包含**输入的problem字符串**时返回true
而模糊匹配本意应当是**输入的problem字符串**包含**数据库problem属性**时才返回true
这里似乎相反逻辑了

大概可能得
`select * from word_bank2 where ...... and '字符串' like concat('%', problem, '%');`

**Comment by HibiKier** [comment]
恩，我搞反了
