### ISSUE TITLE
upload_image和send_image错误（上传和发送图片错误？

### ISSUE THREAD

**Issue by 1324470558** [HibiKier/zhenxun_bot#1027]
### 错误截图
![image](https://user-images.githubusercontent.com/74173985/185961111-f6795f0e-4c23-466f-b527-3986335fb21a.png)

### 错误说明

上传和发送图片错误...求大佬帮帮忙

**Comment by HibiKier** [comment]
更新

**Comment by 1324470558** [comment]
已解决，感谢！
