### ISSUE TITLE
依赖未及时更新导致metadata报错

### ISSUE THREAD

**Issue by DeparturesNeko** [HibiKier/zhenxun_bot#1029]
### 错误截图

真寻由0.1.6.2自动更新至0.1.6.3后发生错误
_plugin has no attribute "metadata"
后真寻无法正常启动

### 错误说明

在重新执行poetry install后更新了部分的依赖版本，再次执行python bot.py后恢复正常
建议在自动更新脚本中加入poetry install

注：
**不可**手动更新所有pip包至最新版本，会出现依赖版本过高导致机器人无法启动的问题

**Comment by JiJiang233** [comment]
> ### 系统版本：Ubuntu 20.04
> ### 真寻版本：0.1.6.3
> ### 错误截图
> 真寻由0.1.6.2自动更新至0.1.6.3后发生错误 _plugin has no attribute "metadata" 后真寻无法正常启动
> 
> ### 错误说明
> 在重新执行poetry install后更新了部分的依赖版本，再次执行python bot.py后恢复正常 建议在自动更新脚本中加入poetry install
> 
> 注： **不可**手动更新所有pip包至最新版本，会出现依赖版本过高导致机器人无法启动的问题

感谢老哥指路

**Comment by Einck0** [comment]
感谢老哥指路

**Comment by RShock** [comment]
用一键脚本安装的（没有poetry）的应该如何修复呢

**Comment by DeparturesNeko** [comment]
> 用一键脚本安装的（没有poetry）的应该如何修复呢

出现这个问题的本质是运行环境的依赖与所需求的版本对不上导致函数块缺失，可以参考一键部署脚本中的安装依赖部分
`
Installation_dependency() {
    if [[ ${release} == "centos" ]]; then
        yum -y update
        yum install -y git fontconfig mkfontscale epel-release wget vim curl zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gcc make libffi-devel
        if  ! which python3.8 && ! which python3.9; then
            wget https://mirrors.huaweicloud.com/python/3.9.10/Python-3.9.10.tgz -O ${TMP_DIR}/Python-3.9.10.tgz && \
                tar -zxf ${TMP_DIR}/Python-3.9.10.tgz -C ${TMP_DIR}/ &&\
                cd ${TMP_DIR}/Python-3.9.10 --with-ensurepip=install && \
                ./configure && \
                make -j $(cat /proc/cpuinfo |grep "processor"|wc -l) && \
                make altinstall
            python_v="python3.9"
        fi
        ${python_v} <(curl -s -L https://bootstrap.pypa.io/get-pip.py) || echo -e "${Tip} pip 安装出错..."
        rpm -v --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
        rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
        yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        yum install -y postgresql13-server ffmpeg ffmpeg-devel atk at-spi2-atk cups-libs libxkbcommon libXcomposite libXdamage libXrandr mesa-libgbm gtk3
        /usr/pgsql-13/bin/postgresql-13-setup initdb
        systemctl enable postgresql-13
        systemctl start postgresql-13
        cat > /tmp/sql.sql <<-EOF
CREATE USER zhenxun WITH PASSWORD 'zxpassword';
CREATE DATABASE zhenxun OWNER zhenxun;
EOF
        su postgres -c "psql -f /tmp//sql.sql"
    elif [[ ${release} == "debian" ]]; then
        apt-get update
        apt-get install -y wget ttf-wqy-zenhei xfonts-intl-chinese wqy* build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev
        if  ! which python3.8 && ! which python3.9;then
            wget https://mirrors.huaweicloud.com/python/3.9.10/Python-3.9.10.tgz -O ${TMP_DIR}/Python-3.9.10.tgz && \
                tar -zxf ${TMP_DIR}/Python-3.9.10.tgz -C ${TMP_DIR}/ &&\
                cd ${TMP_DIR}/Python-3.9.10 && \
                ./configure --with-ensurepip=install && \
                make -j $(cat /proc/cpuinfo |grep "processor"|wc -l) && \
                make altinstall
            python_v="python3.9"
        fi
        apt-get install -y \
            vim \
            wget \
            git \
            ffmpeg \
            postgresql \
            postgresql-contrib \
            libgl1 \
            libglib2.0-0 \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            libasound2
        ${python_v} <(curl -s -L https://bootstrap.pypa.io/get-pip.py) || echo -e "${Tip} pip 安装出错..."
        /etc/init.d/postgresql start
        cat > /tmp/sql.sql <<-EOF
CREATE USER zhenxun WITH PASSWORD 'zxpassword';
CREATE DATABASE zhenxun OWNER zhenxun;
EOF
        su postgres -c "psql -f /tmp/sql.sql"
    elif [[ ${release} == "ubuntu" ]]; then
        apt-get update
        apt-get install -y software-properties-common ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-uming
        fc-cache -f -v
        echo -e "\n" | add-apt-repository ppa:deadsnakes/ppa
        if  ! which python3.8 && ! which python3.9;then
            apt-get install -y python3.9-full
            python_v="python3.9"
        fi
        apt-get install -y \
            vim \
            wget \
            git \
            ffmpeg \
            postgresql \
            postgresql-contrib \
            libgl1 \
            libglib2.0-0 \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            libasound2
        ${python_v} <(curl -s -L https://bootstrap.pypa.io/get-pip.py) || echo -e "${Tip} pip 安装出错..."
        /etc/init.d/postgresql start
        cat > /tmp//sql.sql <<-EOF
CREATE USER zhenxun WITH PASSWORD 'zxpassword';
CREATE DATABASE zhenxun OWNER zhenxun;
EOF
        su postgres -c "psql -f /tmp/sql.sql"
    elif [[ ${release} == "archlinux" ]]; then
        pacman -Sy python python-pip unzip --noconfirm
    fi
    [[ ! -e /usr/bin/python3 ]] && ln -s /usr/bin/${python_v} /usr/bin/python3
}
`
去除其中安装python与postgresql的步骤，将该部分独立为python文件并手动运行，可能因为缺失前置变量或函数出现部分报错，需自行调整，操作难度较高。

或备份config、resources、env等配置文件后，彻底卸载真寻bot重新部署，将对应文件拷贝回原目录，有损失数据的风险。

也可以考虑手动使用pip install XXX=version更新对应包到指定版本，但如果包很多就很麻烦。

这些建议仅作为解决方案的思路，实际方案需要等待开发者。
