### ISSUE TITLE
问答插件添加词条报错

### ISSUE THREAD

**Issue by xh22805** [HibiKier/zhenxun_bot#1030]
### 错误截图
![图片](https://user-images.githubusercontent.com/104178374/186059148-0cd793c6-1740-4c11-82ac-4d626bef1860.png)

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/186072713-5fb51172-15b3-478c-b45e-639549e3d94d.png)
看一下是哪个插件的问题再发issues

**Comment by xh22805** [comment]
看错了，添加词条后出现的报错，以为是问答插件的问题，实际是另一个插件的问题，解决了，不好意思😅
