### ISSUE TITLE
运行报错，求大佬解答！

### ISSUE THREAD

**Issue by NekoraNyaRu** [HibiKier/zhenxun_bot#1034]
### 真寻版本：0.1.6.3

![%5@FHNAR`}XI$NLSJD8MZ{T](https://user-images.githubusercontent.com/109634568/186080638-7787072b-e94a-4ede-b6a4-a9049c6586cf.png)

[img]

08-23 13:35:07 [ERROR] nonebot | Running matcher <Matcher from plugins.sign_in, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):

  File "C:\zhenxun_bot-0.1.6.3\zhenxun_bot-0.1.6.3\bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x00000191FB8043A0>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-KkTJaTqE-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KkTJaTqE-py3.9\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x00000191F8C32820>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KkTJaTqE-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
    │       └ <function run at 0x00000191FCBE2670>
    └ <module 'uvicorn' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-KkTJaTqE-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KkTJaTqE-py3.9\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x00000191FCBE2820>
    └ <uvicorn.server.Server object at 0x000001918B335340>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KkTJaTqE-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x00000191FCBE28B0>
           │       │   └ <uvicorn.server.Server object at 0x000001918B335340>
           │       └ <function run at 0x00000191FB1179D0>
           └ <module 'asyncio' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x000001918B30FD40>
           │    └ <function BaseEventLoop.run_until_complete at 0x00000191FB25BA60>
           └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000191FB2ADC10>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000191FB25F550>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000191FB2065E0>
    └ <Handle <TaskWakeupMethWrapper object at 0x000001918F41B9D0>(<Future finished result=None>)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x000001918F41B9D0>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x000001918F41B9D0>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x000001918F41B9D0>(<Future finished result=None>)>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KkTJaTqE-py3.9\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x00000191FB837CA0>: <Task finished name='Task-1380' coro=<_command() done, defined at C:\Users\Admini...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x000001918BC0A7C0>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '签到', '_matched_g...
          │            │        │    └ GroupMessageEvent(time=1661232907, self_id=1218067699, post_type='message', sub_type='normal', user_id=3163610561, message_ty...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x000001918B4F2580>
          │            └ <Matcher from plugins.sign_in, type=message, priority=5, temp=False>
          └ <function _run_matcher at 0x00000191FB9B9D30>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KkTJaTqE-py3.9\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x00000191FB837CA0>: <Task finished name='Task-1380' coro=<_command() done, defined at C:\Users\Admini...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x000001918BC0A7C0>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '签到', '_matched_g...
          │       │   │    └ GroupMessageEvent(time=1661232907, self_id=1218067699, post_type='message', sub_type='normal', user_id=3163610561, message_ty...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x000001918B4F2580>
          │       └ <function Matcher.run at 0x00000191FB837820>
          └ <Matcher from plugins.sign_in, type=message, priority=5, temp=False>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KkTJaTqE-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x00000191FB837CA0>: <Task finished name='Task-1380' coro=<_command() done, defined at C:\Users\Admini...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x000001918BC0A7C0>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '签到', '_matched_g...
          │    │          │    └ GroupMessageEvent(time=1661232907, self_id=1218067699, post_type='message', sub_type='normal', user_id=3163610561, message_ty...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x000001918B4F2580>
          │    └ <function Matcher.simple_run at 0x00000191FB837790>
          └ <Matcher from plugins.sign_in, type=message, priority=5, temp=False>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KkTJaTqE-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x0000019189E5B790>, params=[ModelField(name='event', type=GroupMessageEvent, required=True), ...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KkTJaTqE-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'event': GroupMessageEvent(time=1661232907, self_id=1218067699, post_type='message', sub_type='normal', user_id=3163610561, ...
                 │    └ <function _ at 0x0000019189E5B790>
                 └ <Dependent call=<function _ at 0x0000019189E5B790>, params=[ModelField(name='event', type=GroupMessageEvent, required=True), ...

  File "C:\zhenxun_bot-0.1.6.3\zhenxun_bot-0.1.6.3\plugins\sign_in\__init__.py", line 93, in _
    await group_user_check_in(nickname, event.user_id, event.group_id),
          │                   │         │     │        │     └ 543166451
          │                   │         │     │        └ GroupMessageEvent(time=1661232907, self_id=1218067699, post_type='message', sub_type='normal', user_id=3163610561, message_ty...
          │                   │         │     └ 3163610561
          │                   │         └ GroupMessageEvent(time=1661232907, self_id=1218067699, post_type='message', sub_type='normal', user_id=3163610561, message_ty...
          │                   └ '大萝卜鸡！'
          └ <function group_user_check_in at 0x0000019189E505E0>

  File "C:\zhenxun_bot-0.1.6.3\zhenxun_bot-0.1.6.3\plugins\sign_in\group_user_checkin.py", line 39, in group_user_check_in
    return await _handle_check_in(nickname, user_qq, group, present)  # ok
                 │                │         │        │      └ datetime.datetime(2022, 8, 23, 13, 35, 7, 172292)
                 │                │         │        └ 543166451
                 │                │         └ 3163610561
                 │                └ '大萝卜鸡！'
                 └ <function _handle_check_in at 0x0000019189E50D30>

  File "C:\zhenxun_bot-0.1.6.3\zhenxun_bot-0.1.6.3\plugins\sign_in\group_user_checkin.py", line 76, in _handle_check_in
    gift, gift_type = random_event(user.impression)
                      │            │    └ <gino.declarative.ColumnAttribute object at 0x00000191839A8FA0>
                      │            └ <models.sign_group_user.SignGroupUser object at 0x000001918B5EE9D0>
                      └ <function random_event at 0x0000019189E50C10>

  File "C:\zhenxun_bot-0.1.6.3\zhenxun_bot-0.1.6.3\plugins\sign_in\random_event.py", line 23, in random_event
    if rand <= prob:
       │       └ None
       └ 0.3207071985207938

TypeError: '<=' not supported between instances of 'float' and 'NoneType'

[img]

### 错误说明

貌似每收到一条消息就会报一次这样的错，不知道是怎么回事，求大佬解答！

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/186172512-d7137c91-408f-49d5-b559-4f51a1ef9293.png)
你把这三个删了？
