### ISSUE TITLE
“来点**涩图”命令出现连接错误

### ISSUE THREAD

**Issue by ChthollyWn** [HibiKier/zhenxun_bot#1036]
### 错误截图

![image](https://user-images.githubusercontent.com/85938618/186286917-467205c8-4be7-4890-b9a4-f96f58aefc4c.png)

### 日志截图

![9$XZ(XG87J9~ U2ZP4%B$Y0](https://user-images.githubusercontent.com/85938618/186286939-4f414e16-f294-49e0-b36e-96a58f01f797.png)

### 错误说明

其他命令目前没有发现问题，只有这个命令会返回网络连接失败...

**Comment by HibiKier** [comment]
我可以

**Comment by ChthollyWn** [comment]
> 我可以

我的这个问题现在是偶尔会出现，这应该属于是网络问题吧
