### ISSUE TITLE
更新bot后出现词库bug

### ISSUE THREAD

**Issue by 534019023** [HibiKier/zhenxun_bot#1038]
![image](https://user-images.githubusercontent.com/95991937/186330846-365c1832-f65a-4ca1-a2ba-4d41260ae832.png)
昨天更新后每次有新消息后都会出现这一段报错，但是词库功能能正常运行，请问这是什么原因，是否是因为词库大改前数据库里有先前的词条数据造成的

**Comment by HibiKier** [comment]
更新到最新的

**Comment by 534019023** [comment]
抱歉刚看到您的回复
刚刚我更新到了最新的文件但是还是会出现这个问题，报错代码也一样

**Comment by 534019023** [comment]
解决了，是原先词库的数据里回复是图片的词条造成的
但是现在发送图片为答案的回复时会变成这样
![image](https://user-images.githubusercontent.com/95991937/187340267-0abad8dd-8a3d-46fc-842f-a893b796bfa0.png)

**Comment by HibiKier** [comment]
4e551bec0d1dd672c402dfd64aed7f66a68a5991

**Comment by 534019023** [comment]
解决了，非常感谢
