### ISSUE TITLE
能让小真寻对话能优先使用anime的内容嘛

### ISSUE THREAD

**Issue by ID114514** [HibiKier/zhenxun_bot#104]
现在是ai跟词库的两边随机，有时候就答非所问了

**Comment by HibiKier** [comment]
呃，倒是可以对好感度更高的用户提供更高概率的anime概率

**Comment by ID114514** [comment]
> 呃，倒是可以对好感度更高的用户提供更高概率的anime概率

emm好感度获取途径是不是有点少了些

**Comment by HibiKier** [comment]
后期可以加点道具呃
