### ISSUE TITLE
关于1.6.3新版本的词条，群管理添加词条提示权限不足捏，已经添加了对应群友是BOT的管理员

### ISSUE THREAD

**Issue by saferabbit** [HibiKier/zhenxun_bot#1042]
### 错误截图

![image](https://user-images.githubusercontent.com/44218328/186805419-16d22ca6-dabb-4134-a6ca-00774922398b.png)
![@2IX60HNT%K`6M24AXE}HYJ](https://user-images.githubusercontent.com/44218328/186805468-50ac657c-7cf3-42e0-a247-f6f4d8a7ea94.png)

### 日志截图

日志没报错

### 错误说明

已经是bot的管理员添加词条会触发这个不是超级管理员，请问1.6.3版本的bot管理员添加词条的正确指令是什么？求指个方向

**Comment by HibiKier** [comment]
0756d39ac542854bd9cb6db41aaf09c0cdd456d2
