### ISSUE TITLE
添加词条的时候，回答中没有去掉“答”字

### ISSUE THREAD

**Issue by Renouer** [HibiKier/zhenxun_bot#1043]
### 错误截图

![image](https://user-images.githubusercontent.com/95909116/186859891-d566585c-97fd-4353-84a0-23e2d86149de.png)

### 日志截图

无报错

### 错误说明

添加词条的时候，回答中没有去掉“答”字

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/186893179-cf3adebb-1b37-4260-9a97-259e4021f37f.png)
这个空格去掉试试

**Comment by HibiKier** [comment]
e42521f0a3e53b707fa60eae00fef9e17874b73c
