### ISSUE TITLE
未知kill

### ISSUE THREAD

**Issue by h265642327** [HibiKier/zhenxun_bot#1046]
### 错误截图

08-27 14:08:48 [信息] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> 运行完成
08-27 14:08:48 [调试] nonebot | 正在检查优先级 4 中的匹配器...
08-27 14:08:48 [调试] nonebot | 正在检查优先级 5 中的匹配器...
08-27 14:08:48 [调试] nonebot | 事件类型 <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> 与注解 PrivateMessageEvent 不匹配，已忽略
08-27 15:12:40 [信息] nonebot | 事件将由 <Matcher from basic_plugins.nickname, type=message, priority=5, temp=False> 处理
被杀

### 日志截图

08-27 14:08:48 [信息] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> 运行完成
08-27 14:08:48 [调试] nonebot | 正在检查优先级 4 中的匹配器...
08-27 14:08:48 [调试] nonebot | 正在检查优先级 5 中的匹配器...
08-27 14:08:48 [调试] nonebot | 事件类型 <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> 与注解 PrivateMessageEvent 不匹配，已忽略
08-27 15:12:40 [信息] nonebot | 事件将由 <Matcher from basic_plugins.nickname, type=message, priority=5, temp=False> 处理
被杀

### 错误说明

莫名奇怪的kill

**Comment by HibiKier** [comment]
看不出来
