### ISSUE TITLE
本地数据转移云服务器

### ISSUE THREAD

**Issue by BlueLolikon** [HibiKier/zhenxun_bot#1048]
把本地电脑真寻的好感度，金币那些，移到云服务器上面，怎么弄？
我试了换pgAdmin 4   的data文件，结果数据库出错（
又试了在数据库里面备份然后导出，结果还是不行，弹个这弹窗
![GYC7@VBP~5V@}7MQ(~S)AGG](https://user-images.githubusercontent.com/108455133/187069532-72cd5f6f-0c1f-49d1-9196-38766b9ee2fc.png)
搞了一两天了，人还是懵的。
求求哪位大佬有空出个转移数据教程吧  （呜呜呜

**Comment by q56535** [comment]
首先配置好这个
![image](https://user-images.githubusercontent.com/26663837/187069643-389dbc03-4d54-4340-89c5-a84344539ffd.png)
然后直接备份库和还原库就行

**Comment by BlueLolikon** [comment]
！谢谢大佬，这就去逝逝

**Comment by BlueLolikon** [comment]
然而没找到这个窗口.....(;´༎ຶД༎ຶ`)
大佬救救（萌新太难了）

**Comment by q56535** [comment]
![image](https://user-images.githubusercontent.com/26663837/187070019-81a4cc42-8972-4284-8205-986d06f5e23e.png)
![image](https://user-images.githubusercontent.com/26663837/187070055-a08c0464-9864-4be3-bad7-feaf7deba6b0.png)
![image](https://user-images.githubusercontent.com/26663837/187070065-cd1ef1d5-ffbc-49b4-bfa6-d3b758bd978d.png)

**Comment by BlueLolikon** [comment]
大佬我真的爱死你了😍

**Comment by q56535** [comment]
就差不多这么个流程
然后直接备份表就行

**Comment by MisakaMikoto2333** [comment]
其实可以直接把PG拷贝过去（
我因为不会备份直接拷贝过去了

**Comment by q56535** [comment]
> 其实可以直接把PG拷贝过去（ 我因为不会备份直接拷贝过去了

同系统可以，但是不同系统就不行了

**Comment by MisakaMikoto2333** [comment]
> > 其实可以直接把PG拷贝过去（ 我因为不会备份直接拷贝过去了
> 
> 同系统可以，但是不同系统就不行了

这样啊，我之前重装服务器的时候是恢复当初的镜像，原来是这样啊，我还以为可以直接拷贝（
