### ISSUE TITLE
关于每日签到和开箱的数据问题

### ISSUE THREAD

**Issue by VoplsX** [HibiKier/zhenxun_bot#105]
因为之前的vps配置太低经查卡，换了个新的VPS，配置完各种之后，只是替换了额ID_DATA.db，可是发现开箱和每日签到的数据都找不到了，请问大佬该如何解决这个问题，是存在了postgresql的数据库里了么？这个该如何转移呢？

**Comment by HibiKier** [comment]
最简单的是用pgadmin连接到数据库然后右键备份，再连接到新服务器后右键还原

**Comment by VoplsX** [comment]
了解，这就立马去试试 谢谢大佬
