### ISSUE TITLE
关于bilibili转发解析插件, 假如短时间以不同形式出现的同一个视频, 可不可以加个判断让它只解析一次

### ISSUE THREAD

**Issue by KudouShinnyan** [HibiKier/zhenxun_bot#1050]
如图, 有人分享了个视频, 莪的另一个看板娘(Bot)会解析成链接, 然后真寻好像是把原分享和看板娘的都解析发送一遍所以发了两遍, 要是能只发一遍就好了
![Screenshot_20220829-113502_QQ](https://user-images.githubusercontent.com/68854981/187119328-a091220b-bcd2-47d2-b747-65e3071838a1.png)

**Comment by HibiKier** [comment]
相同url是有cd限制的，可能是另一个也是机器人发的很快导致的？你试试自己单独发2次？
