### ISSUE TITLE
色图模块MAX_ONCE_NUM2FORWARD 选项启用后报错

### ISSUE THREAD

**Issue by linzqGit** [HibiKier/zhenxun_bot#1051]
### 日志
08-30 09:49:47 [ERROR] nonebot | Running matcher <Matcher from plugins.send_setu_.send_setu, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):

  File "bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7fce7e2a9700>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7fce7fadae50>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
    │       └ <function run at 0x7fce7ca7bdc0>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fce7ca7bf70>
    └ <uvicorn.server.Server object at 0x7fce602635e0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fce7ca8b040>
           │       │   └ <uvicorn.server.Server object at 0x7fce602635e0>
           │       └ <function run at 0x7fce7f3a14c0>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fce6014a740>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fce7e26a0d0>: <Task finished name='Task-3453424' coro=<_command() done, defined at /root/.cache/pyp...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fce5f65c220>
          │            │        │    │      └ {'_prefix': {'command': ('色图',), 'raw_command': '色图', 'command_arg': [], 'command_start': ''}}
          │            │        │    └ PrivateMessageEvent(time=1661824185, self_id=2587948132, post_type='message', sub_type='friend', user_id=277937402, message_t...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fce6017f5e0>
          │            └ <Matcher from plugins.send_setu_.send_setu, type=message, priority=5, temp=False>
          └ <function _run_matcher at 0x7fce7e0e89d0>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fce7e26a0d0>: <Task finished name='Task-3453424' coro=<_command() done, defined at /root/.cache/pyp...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fce5f65c220>
          │       │   │    │      └ {'_prefix': {'command': ('色图',), 'raw_command': '色图', 'command_arg': [], 'command_start': ''}}
          │       │   │    └ PrivateMessageEvent(time=1661824185, self_id=2587948132, post_type='message', sub_type='friend', user_id=277937402, message_t...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fce6017f5e0>
          │       └ <function Matcher.run at 0x7fce7e261c10>
          └ <Matcher from plugins.send_setu_.send_setu, type=message, priority=5, temp=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fce7e26a0d0>: <Task finished name='Task-3453424' coro=<_command() done, defined at /root/.cache/pyp...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fce5f65c220>
          │    │          │    │      └ {'_prefix': {'command': ('色图',), 'raw_command': '色图', 'command_arg': [], 'command_start': ''}}
          │    │          │    └ PrivateMessageEvent(time=1661824185, self_id=2587948132, post_type='message', sub_type='friend', user_id=277937402, message_t...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fce6017f5e0>
          │    └ <function Matcher.simple_run at 0x7fce7e261b80>
          └ <Matcher from plugins.send_setu_.send_setu, type=message, priority=5, temp=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7fce6583c940>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xuyT1vc2-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fce6017f5e0>, 'event': PrivateMessageEvent(time=1661824185, self_id...
                 │    └ <function _ at 0x7fce6583c940>
                 └ <Dependent call=<function _ at 0x7fce6583c940>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='eve...

  File "/root/QQBOT/zhenxun_bot/zhenxun_bot-main/plugins/send_setu_/send_setu/__init__.py", line 187, in _
    await send_setu_handle(bot, setu, event, cmd[0], msg, num, r18)
          │                │    │     │      │       │    │    └ 0
          │                │    │     │      │       │    └ 1
          │                │    │     │      │       └ ''
          │                │    │     │      └ ('色图',)
          │                │    │     └ PrivateMessageEvent(time=1661824185, self_id=2587948132, post_type='message', sub_type='friend', user_id=277937402, message_t...
          │                │    └ <Matcher from plugins.send_setu_.send_setu, type=message, priority=5, temp=False>
          │                └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fce6017f5e0>
          └ <function send_setu_handle at 0x7fce6583c9d0>

  File "/root/QQBOT/zhenxun_bot/zhenxun_bot-main/plugins/send_setu_/send_setu/__init__.py", line 359, in send_setu_handle
    and num >= Config.get_config("send_setu", "MAX_ONCE_NUM2FORWARD")
        │      │      └ <function ConfigsManager.get_config at 0x7fce7cfab3a0>
        │      └ <configs.utils.ConfigsManager object at 0x7fce7d2ff700>
        └ 1

TypeError: '>=' not supported between instances of 'int' and 'str'

### 错误说明
Config.getConfig获取选项值后，类型未转换就于数值进行比较而产生的错误

**Comment by HibiKier** [comment]
用webui改的？

**Comment by linzqGit** [comment]
是的，webui上面改的

**Comment by HibiKier** [comment]
自己先在配置文件里改吧，没有默认值的配置不好判断需要的是int还是str

**Comment by linzqGit** [comment]
好
