### ISSUE TITLE
真寻更新后启动报错

### ISSUE THREAD

**Issue by hhjoknvddgjkm** [HibiKier/zhenxun_bot#1054]
### 错误截图
![20220831225618](https://user-images.githubusercontent.com/85065657/187710395-ee8db810-1d6e-4988-a077-d3f42e99097a.png)

[img]

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by S2005230102** [comment]
+1

**Comment by Heartcoolman** [comment]
+1

**Comment by HibiKier** [comment]
更新sript.py文件

**Comment by HibiKier** [comment]
basic_plugin/script.py
