### ISSUE TITLE
原神资源查询只能看到图片的一部分

### ISSUE THREAD

**Issue by SecretLoved** [HibiKier/zhenxun_bot#1056]
### 错误截图
![image](https://user-images.githubusercontent.com/73172198/188197034-c47b81a9-ccca-4b65-a106-8e734eaecece.png)
![image](https://user-images.githubusercontent.com/73172198/188197077-e879e404-71f1-469f-9140-971bcfa3aad4.png)

[img]

### 日志截图

[img]

### 错误说明

原神资源查询只能看到图片的一部分

**Comment by HibiKier** [comment]
3cbd899daafee95ca1f8e4c742d8734cf15b20cb
