### ISSUE TITLE
插件太多导致图片帮助重叠

### ISSUE THREAD

**Issue by SEVEN-6174** [HibiKier/zhenxun_bot#1057]
![451998830](https://user-images.githubusercontent.com/107546075/188257379-982c5bf0-3e66-4b21-9472-857499e821e0.png)
如图
但是我又不想删插件

**Comment by SEVEN-6174** [comment]
![image](https://user-images.githubusercontent.com/107546075/188263763-c2a98395-de38-4e7b-be2d-1c6f94d164ee.png)
150个，别骂（

**Comment by HibiKier** [comment]
49e38862afadeae779534bacc32f78be0fd5775f
