### ISSUE TITLE
按照教程来运行不了真寻

### ISSUE THREAD

**Issue by AyasakiAtre** [HibiKier/zhenxun_bot#1058]
### 错误截图
![QQ截图20220903142659](https://user-images.githubusercontent.com/83602783/188258980-9bf04516-f495-491a-9cf2-085d6be3856d.png)

**Comment by SEVEN-6174** [comment]
都让你填数据库配置了
配置文件是
机器人根目录/configs/config.py

**Comment by AyasakiAtre** [comment]
> 

我还以为我数据库填好了草..  谢谢大佬
