### ISSUE TITLE
原神抽卡武器池有误

### ISSUE THREAD

**Issue by SanaeMio** [HibiKier/zhenxun_bot#1060]
### 错误截图

![QQ截图20220904183154.jpg](https://s2.loli.net/2022/09/04/OV8CLNFzGikMYHq.jpg)

### 日志截图

![QQ截图20220904182858.jpg](https://s2.loli.net/2022/09/04/OqMnAFlX1JBpoW3.jpg)

### 错误说明
根据biligame原神wiki获取卡池数据[https://wiki.biligame.com/ys/%E7%A5%88%E6%84%BF](https://wiki.biligame.com/ys/%E7%A5%88%E6%84%BF)
目前角色祈愿刚好有两个角色up池「巡御蘙荟」 & 「陵薮市朝」，根据genshin_handle.py代码来看，程序把第二个角色up池作为武器池使用了，实际的武器池没有获取并生效

**Comment by HibiKier** [comment]
b25b9ca928597e38d4aabd6f5227991a80caf0d0
