### ISSUE TITLE
1.6.2更新到1.6.3启动报错

### ISSUE THREAD

**Issue by AlanABCDE** [HibiKier/zhenxun_bot#1062]
### 错误截图
![image](https://user-images.githubusercontent.com/65140019/188417698-8d7ea77e-7efa-43c6-b1f6-36d4065f90a5.png)

![image](https://user-images.githubusercontent.com/65140019/188417755-4a7e9bb9-dcbe-435b-9d42-b2bc9d5a824f.png)

### 日志截图

同上

### 错误说明

更新到1.6.3 重启，加载完插件后，获取basic plugins的metadata报错

**Comment by HibiKier** [comment]
更新nb

**Comment by AlanABCDE** [comment]
done
