### ISSUE TITLE
加载的时候send_image 和 load_image 模块报错是为什么啊，和那个nonetype又什么关系吗

### ISSUE THREAD

**Issue by wtekh** [HibiKier/zhenxun_bot#1063]
### 错误截图
![QQ截图20220906124052](https://user-images.githubusercontent.com/112922267/188548671-f3b93964-6373-4ae7-8bf6-4e51b0342e83.png)

[img]

### 日志截图
![QQ截图20220906124635](https://user-images.githubusercontent.com/112922267/188549025-e0c761a4-5892-430b-a48c-814296de60b5.png)

[img]

### 错误说明

发生了xx错误...

**Comment by HibiKier** [comment]
更新代码
