### ISSUE TITLE
自定义入群消息失败

### ISSUE THREAD

**Issue by gaogaowenwen** [HibiKier/zhenxun_bot#1064]
### 真寻版本：0.1.5.3

![image](https://user-images.githubusercontent.com/112854252/188597972-aa14ac26-010a-4877-ae8c-2e34caf11cf1.png)

**Comment by HibiKier** [comment]
艹

**Comment by HibiKier** [comment]
775140cf79abb907f85de59b7e13a18d6cc888b9
