### ISSUE TITLE
关于米游社签到找到同nb框架下更多功能的同款插件的替代建议

### ISSUE THREAD

**Issue by ayakasuki** [HibiKier/zhenxun_bot#1065]
### 真寻版本：0.1.6.3

[Ljzd-PRO](https://github.com/Ljzd-PRO)
/
[nonebot-plugin-mystool](https://github.com/Ljzd-PRO/nonebot-plugin-mystool)
同是nonebot的原神插件，这个支持商店兑换和任务，提个建议可以参考下里面的源码进行替换一下，确实有丢丢先进。
此条仅为建议，无bug反馈

**Comment by xANoyU** [comment]
这个插件看着是不错的，希望真寻的原神绑定cookie也能改成这个插件的绑定方式，更方便一点

**Comment by ayakasuki** [comment]
已自行适配移植插件[真寻版米游社小助手](https://github.com/ayakasuki/nonebot-plugin-mystool)

**Comment by q56535** [comment]
兄啊，你都没有按照真寻插件规范写法来适配啊

**Comment by ayakasuki** [comment]
@q56535  兄啊，你去看看真寻官方文档，它是支持pluginmeta的啊
