### ISSUE TITLE
私聊戳一戳没回应

### ISSUE THREAD

**Issue by AlanABCDE** [HibiKier/zhenxun_bot#1068]
### 错误截图

![image](https://user-images.githubusercontent.com/65140019/189013511-6b9a406e-24c9-47c2-ba83-50a57df88e48.png)

![image](https://user-images.githubusercontent.com/65140019/189013551-5ded864e-f94d-48c5-96e3-602a734ee977.png)

![image](https://user-images.githubusercontent.com/65140019/189013783-f109a686-20b6-44e8-ba26-994e8d18d360.png)

### 日志截图

同上

### 错误说明
私聊戳一戳没有回应，群聊功能正常

**Comment by HibiKier** [comment]
无法复现
