### ISSUE TITLE
完全跑步起来，不知道为啥

### ISSUE THREAD

**Issue by MaoSource** [HibiKier/zhenxun_bot#107]
![image](https://user-images.githubusercontent.com/56857029/150670301-2083adfb-b9b5-443d-9ac7-dc9708998a9c.png)

**Comment by HibiKier** [comment]
日志给全

**Comment by MaoSource** [comment]
> 日志给全

太多了，感觉最少有个几百行

**Comment by MaoSource** [comment]
> 日志给全

![image](https://user-images.githubusercontent.com/56857029/150670381-3658596a-ee2f-493b-9953-2dcbc6d4bf4c.png)
这是最后的几行

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/150670704-9208cb3f-16c9-418b-a8ec-6b91fa31754c.png)
缺环境

**Comment by MaoSource** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/150670704-9208cb3f-16c9-418b-a8ec-6b91fa31754c.png) 缺环境

解决不了

**Comment by HibiKier** [comment]
你python输入后显示什么版本

**Comment by MaoSource** [comment]
> 你python输入后显示什么版本

没有，装的python3.9

**Comment by HibiKier** [comment]
输入python3.9后显示的版本后面带a吗

**Comment by MaoSource** [comment]
> 输入python3.9后显示的版本后面带a吗

带

**Comment by HibiKier** [comment]
你装了ALPHA版，换到正式版

**Comment by MaoSource** [comment]
> 换到正式版

好的

**Comment by MaoSource** [comment]
现在好像部署好了，但是好像没有任何反应
![image](https://user-images.githubusercontent.com/56857029/150707211-82240c9e-e9a7-441f-9209-460470748c34.png)
