### ISSUE TITLE
'NoneType' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by VanLewis2003** [HibiKier/zhenxun_bot#1070]
### 错误截图

![image](https://user-images.githubusercontent.com/93692468/189057872-4380f70e-dd37-48ed-b190-096a268cac4e.png)

### 日志截图

![image](https://user-images.githubusercontent.com/93692468/189057988-3fcc6dbe-13c5-4fc5-a65e-98f11cef2267.png)

### 错误说明

重启服务器后运行bot发生的问题，未在其他issue里找到有效解决方法，参考更新了nonebot2,弹出相同报错。

**Comment by HibiKier** [comment]
6a8a796add54015ce12db1145dcb99e86919d053 感觉是你有插件加载失败了？

**Comment by MobiusT** [comment]
［bot］真寻 12:13:56
检测真寻已更新，当前版本：v0.1.5.6，最新版本：v0.1.6.3
开始更新.....

［bot］真寻 12:16:16
真寻更新完成，版本：v0.1.5.6 -> v0.1.6.3
更新日期：2022-08-21T10:43:58Z
更新日志：
![1755769831-1385136531-3E45DBF38BCD777FC97EF1EF71C54934](https://user-images.githubusercontent.com/62053271/189142676-0d1f1b5c-057b-4882-88df-72794cb734b8.png)

我遇到和他相同的问题，使用docker镜像重装的真寻1.5.6真寻重启均正常，使用【检查更新真寻】更新后重启就报以下错误：
 /usr/local/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
zhenxun_bot  |   return tzinfo.localize(dt)
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：dialogue 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：query_resource_points 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：material_remind 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：black_word 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：open_cases 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：pix_show_info 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：search_buff_skin_price 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：my_props 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：buy 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：gold 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：use 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：shop_handle 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：chat_message_handle 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：update_info 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：about 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：pixiv_rank_search 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：group_welcome_msg 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：word_clouds 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：poetry 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：jitang 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：comments_163 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：cover 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：quotations 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：yiqing 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：statistics_handle 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：what_anime 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：send_setu 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：fake_msg 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：bt 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：music 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：roll 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：wbtop 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：translate 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：nbnhhsh 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：genshin_sign 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：query_memo 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：resin_remind 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：bind 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：query_role 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：send_dinggong_voice 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：weather 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：luxun 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：coser 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：epic 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：search_anime 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：sign_in 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：white2black_image 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：bilibili_sub 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：russian 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：pid_search 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：poke 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：pix 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：update_picture 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：search_image 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：send_image 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：gold_redbag 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：one_friend 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：almanac 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：ai 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：draw_card 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：nickname 获取 plugin_name 失败...'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：24_point 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：luckyball 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：wordle 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：r6s 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
zhenxun_bot  | 09-08 22:00:21 [WARNING] basic_plugins | 配置文件 模块：zhenxun_plugin_petpet 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
zhenxun_bot  | 09-08 22:00:21 [ERROR] uvicorn | Traceback (most recent call last):
zhenxun_bot  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
zhenxun_bot  |     async with self.lifespan_context(app):
zhenxun_bot  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
zhenxun_bot  |     await self._router.startup()
zhenxun_bot  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup
zhenxun_bot  |     await handler()
zhenxun_bot  |   File "/bot/basic_plugins/init_plugin_config/__init__.py", line 39, in _
zhenxun_bot  |     init_plugins_settings(DATA_PATH)
zhenxun_bot  |   File "/bot/basic_plugins/init_plugin_config/init_plugins_settings.py", line 39, in init_plugins_settings
zhenxun_bot  |     metadata = _plugin.metadata
zhenxun_bot  | AttributeError: 'Plugin' object has no attribute 'metadata'
zhenxun_bot  | 
zhenxun_bot  | 09-08 22:00:21 [ERROR] uvicorn | Application startup failed. Exiting.


使用的image: hibikier/zhenxun_bot:latest镜像没有额外加插件，就安装了一些字体之类的

**Comment by VanLewis2003** [comment]
> [6a8a796](https://github.com/HibiKier/zhenxun_bot/commit/6a8a796add54015ce12db1145dcb99e86919d053)感觉是你有插件加载失败了？

应该是，看到回复后把extensive_plugin里的额外插件都删了，再次运行成功了。尽管没有找到问题的原因，不过能正常运行也就够了😂。
