### ISSUE TITLE
启动不了真寻,咋解决

### ISSUE THREAD

**Issue by fanyue0** [HibiKier/zhenxun_bot#1074]
### 错误截图

![y12](https://user-images.githubusercontent.com/109929206/189335890-aaa4b29b-77a5-490c-bea3-912c998a32c0.png)

### 日志截图

![y12](https://user-images.githubusercontent.com/109929206/189335897-d6c28f40-4186-4bd9-a1a5-785ef8174745.png)

### 错误说明

poetry run python bot.py 启动然后就报错中断了其他都好好的

**Comment by HibiKier** [comment]
你在某个插件里的setting里写了cd？

**Comment by fanyue0** [comment]
> 

没有, 然后我把在线运行代码的插件给删了就能正常运行....
