### ISSUE TITLE
真寻突然寄了，重启报错

### ISSUE THREAD

**Issue by Erlla** [HibiKier/zhenxun_bot#1077]
### 错误截图

 
![00402AAF-8C49-4D6A-A04F-8E1AE04AD1D5](https://user-images.githubusercontent.com/49445907/189493017-7259fff1-a61f-47f5-ab33-e5827993d230.jpeg)

### 日志截图

[img]

### 错误说明
机器人突然寄了，打开服务器发现图中报错，重新运行后仍然报错

**Comment by Erlla** [comment]
![IMG_3182](https://user-images.githubusercontent.com/49445907/189493887-921e4a2c-5e35-4e8d-bf19-25ff8a221634.jpeg)

**Comment by HibiKier** [comment]
更新nb

**Comment by Erlla** [comment]
> 

感谢回复，问题已解决
