### ISSUE TITLE
重装之后报错，然后启动后一段内能发消息，之后就报错发不了了

### ISSUE THREAD

**Issue by weltck** [HibiKier/zhenxun_bot#1079]
### 错误截图

[img]

### 日志截图
![I5T))F9@CI~6RU K 3V_NN](https://user-images.githubusercontent.com/106135805/189523992-4d479385-4bb9-4be0-bd7f-99dcc3f29d59.png)
![image](https://user-images.githubusercontent.com/106135805/189524010-81a26e0b-d6a1-4c46-a28c-12590dbddbbb.png)

[img]

### 错误说明

发生了xx错误...

**Comment by HibiKier** [comment]
更新到最新代码

**Comment by HibiKier** [comment]
更新到最新代码
