### ISSUE TITLE
安装成功无法使用

### ISSUE THREAD

**Issue by MaoSource** [HibiKier/zhenxun_bot#108]
![image](https://user-images.githubusercontent.com/56857029/150729293-efe64ac4-bb0d-400a-b734-515aec9a90f2.png)
安装成功了但是好像发啥都没有反应

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/150770256-65dbd79e-104c-4703-9572-6fc2ea72e4b4.png)
请保证所有插件加载上
