### ISSUE TITLE
执行持久化时报错：

### ISSUE THREAD

**Issue by WuoLun** [HibiKier/zhenxun_bot#1081]
### 错误截图
![Screenshot_20220912_221532](https://user-images.githubusercontent.com/108870114/189677443-3ff09523-080d-41f3-83c7-c405fccbed03.jpg)

[img]

### 日志截图
![Screenshot_20220912_221532](https://user-images.githubusercontent.com/108870114/189677478-f26ce51e-4067-46a6-9457-6db93f467b0c.jpg)

[img]

### 错误说明
在执行Linux持久化操作时，出现以上错误。所有依赖都已经安装完毕
显示ModuleNotFoundError

**Comment by HibiKier** [comment]
遇事不决再poetry install

**Comment by WuoLun** [comment]
解决了👌🏻
