### ISSUE TITLE
群聊发【识图】就会报错

### ISSUE THREAD

**Issue by CallTrane** [HibiKier/zhenxun_bot#1082]
### 错误截图
![image](https://user-images.githubusercontent.com/57559093/189695692-b3a4347b-f19e-4bdc-992d-3c235f19795e.png)

### 日志截图

![image](https://user-images.githubusercontent.com/57559093/189695757-86d93993-0049-4c23-af58-4fc16ca7c197.png)

### 错误说明

群聊发【识图】就会报错

**Comment by HibiKier** [comment]
和识图没关系，
![图片](https://user-images.githubusercontent.com/45528451/190556633-97a7eb35-d4a3-4897-af9f-37c5c1a4ecc3.png)
这俩在配置文件里别为空
