### ISSUE TITLE
日志功能问题

### ISSUE THREAD

**Issue by SEVEN-6174** [HibiKier/zhenxun_bot#1083]
系统：win 10 专业工作站版
bot版本 ： v0.1.6.3
开机时加载没问题，没任何报错，可是过一段时间log文件当天的日志不再增加而是停止
![image](https://user-images.githubusercontent.com/107546075/189874624-88eddef3-15ae-41dd-a2f3-e3dd57098fca.png)
![image](https://user-images.githubusercontent.com/107546075/189875060-e53082b9-dc5f-4185-b2a6-8e2614e3de84.png)
如图日志最下面一行比当前最新早
而且重启又只会有开头
并且最后一行每次不一样，不是同一个插件

**Comment by SEVEN-6174** [comment]
(无视第一张截图的画质问题)

**Comment by HibiKier** [comment]
日志是直接使用nb2的
