### ISSUE TITLE
可以启动但是几乎所有模块都找不到  导致真寻机器人处于瘫痪状态 

### ISSUE THREAD

**Issue by 1103859909** [HibiKier/zhenxun_bot#1084]
![image](https://user-images.githubusercontent.com/107859647/190109550-2ae98d7d-2916-4bdc-90ea-554590619d9f.png)
![Screenshot_2022-09-14-16-59-38-808_com tencent mo](https://user-images.githubusercontent.com/107859647/190110256-79863ba1-fca3-4abf-8625-a4070cd5e8b9.jpg)

**Comment by yajiwa** [comment]
[[#373](url)](https://github.com/HibiKier/zhenxun_bot/issues/373#issuecomment-1131638639)

**Comment by yajiwa** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/373#issuecomment-1131638639

**Comment by 1103859909** [comment]
解决了 
![{K)3BDSI TM$C](https://user-images.githubusercontent.com/107859647/190367583-08676e6b-92b9-4e7c-9d97-8798d1b1dc5b.jpg)
 但这次又是啥问题

**Comment by yajiwa** [comment]
> 解决了 ![{K)3BDSI TM$C](https://user-images.githubusercontent.com/107859647/190367583-08676e6b-92b9-4e7c-9d97-8798d1b1dc5b.jpg) 但这次又是啥问题
尝试更新到最新代码

**Comment by yajiwa** [comment]
尝试更新到最新代码

**Comment by HibiKier** [comment]
先试试最新代码

**Comment by 1103859909** [comment]
谢谢  解决了
