### ISSUE TITLE
刚更新到版本就崩溃

### ISSUE THREAD

**Issue by cangla** [HibiKier/zhenxun_bot#1085]
### 错误截图
![image](https://user-images.githubusercontent.com/113469720/189986834-e0475bbb-6789-4c2d-aad3-60e833806b33.png)

### 错误说明
已经尝试过更新nb 现在nb是最新版本

**Comment by yajiwa** [comment]
如果是虚拟环境下运行真寻输入`poetry install`试试

**Comment by cangla** [comment]
ok了 整个重装了一边 现在好了 之前不知道是什么情况 总之谢谢了
