### ISSUE TITLE
碧蓝航线，fgo抽卡出错

### ISSUE THREAD

**Issue by K0nashi** [HibiKier/zhenxun_bot#1086]
### 错误截图

![image](https://user-images.githubusercontent.com/58796627/190048804-f9b97d27-44ff-4193-b14c-b0250c0f55aa.png)
![image](https://user-images.githubusercontent.com/58796627/190049315-110af9b7-5102-4154-a62c-e63bc3e7409f.png)
![image](https://user-images.githubusercontent.com/58796627/190049817-2aacd284-efb3-4461-aa2f-15123991e7b9.png)

![image](https://user-images.githubusercontent.com/58796627/190050238-61b47579-4bb7-4bb3-961f-0f623e673198.png)

尝试更新信息
![image](https://user-images.githubusercontent.com/58796627/190051479-ba5d43ba-e619-4e63-a2a8-7eb801073f69.png)
![image](https://user-images.githubusercontent.com/58796627/190051450-8e03a912-2e29-4dcb-8f84-ed1f1366a979.png)

### 日志截图

![image](https://user-images.githubusercontent.com/58796627/190051644-a5638606-85a0-4014-8c71-dfbc497e0009.png)
![image](https://user-images.githubusercontent.com/58796627/190051677-6bffad64-3bab-4575-86f7-40af0e086274.png)

### 错误说明

第一次开启抽卡功能后，没有等下载完把screen kill了，下次打开以后就一直是这样的报错，不知道如何重载碧蓝航线，fgo的卡池

**Comment by DDS-DS** [comment]
重载XX卡池
用这个命令试试

**Comment by NumberSir** [comment]
> ### 系统版本：Ubuntu 20.04
> ### 真寻版本：0.1.6.3
> ### 错误截图
> ![image](https://user-images.githubusercontent.com/58796627/190048804-f9b97d27-44ff-4193-b14c-b0250c0f55aa.png) ![image](https://user-images.githubusercontent.com/58796627/190049315-110af9b7-5102-4154-a62c-e63bc3e7409f.png) ![image](https://user-images.githubusercontent.com/58796627/190049817-2aacd284-efb3-4461-aa2f-15123991e7b9.png)
> 
> ![image](https://user-images.githubusercontent.com/58796627/190050238-61b47579-4bb7-4bb3-961f-0f623e673198.png)
> 
> 尝试更新信息 ![image](https://user-images.githubusercontent.com/58796627/190051479-ba5d43ba-e619-4e63-a2a8-7eb801073f69.png) ![image](https://user-images.githubusercontent.com/58796627/190051450-8e03a912-2e29-4dcb-8f84-ed1f1366a979.png)
> 
> ### 日志截图
> ![image](https://user-images.githubusercontent.com/58796627/190051644-a5638606-85a0-4014-8c71-dfbc497e0009.png) ![image](https://user-images.githubusercontent.com/58796627/190051677-6bffad64-3bab-4575-86f7-40af0e086274.png)
> 
> ### 错误说明
> 第一次开启抽卡功能后，没有等下载完把screen kill了，下次打开以后就一直是这样的报错，不知道如何重载碧蓝航线，fgo的卡池

碧蓝航线抽卡问题源于bwiki结构修改，修复: #1090
