### ISSUE TITLE
B站视频解析错误

### ISSUE THREAD

**Issue by Yql66** [HibiKier/zhenxun_bot#1087]
### 错误截图
![IOA3Q5{}@IKUS6$5)URZ57H](https://user-images.githubusercontent.com/111969738/190337795-dcc96fcf-0cd3-47b7-ba1a-4d8abc660e0c.png)

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by HibiKier** [comment]
https://github.com/SK-415/bilireq/issues 建议在这问？

**Comment by Yql66** [comment]
> https://github.com/SK-415/bilireq/issues建议在这问？

好的
