### ISSUE TITLE
真寻的AI插件没了

### ISSUE THREAD

**Issue by fanyue0** [HibiKier/zhenxun_bot#1089]
##
![121](https://user-images.githubusercontent.com/109929206/190381448-7ce4a6d4-0d92-4218-8ff6-bc76373aa350.png)
![QQ截图20220915181927](https://user-images.githubusercontent.com/109929206/190381474-e9d07947-0b0d-419a-89f3-3720cf98775c.png)
![QQ截图20220915181934](https://user-images.githubusercontent.com/109929206/190381483-7fe07a3f-2637-4692-b914-1bf2eef57df7.png)

### 错误说明

AI插件没了  也没有报错, 运行真寻也可以看到加载成功ai插件

**Comment by HibiKier** [comment]
先别把你自己加的插件加载进来再是
