### ISSUE TITLE
重复报错

### ISSUE THREAD

**Issue by WuoLun** [HibiKier/zhenxun_bot#1091]
### 错误截图
![Screenshot_20220916_131828](https://user-images.githubusercontent.com/108870114/190562182-3625a7a6-71b3-4434-8953-2baf7c13c144.jpg)

### 日志截图
![Screenshot_20220916_131828](https://user-images.githubusercontent.com/108870114/190562204-e94feda6-e3ad-4374-bbf2-95ef42c4156c.jpg)

### 错误说明

重复报错，直到连接断开(┳Д┳)是不是gocq的问题(┳Д┳)

**Comment by HibiKier** [comment]
发全一点

**Comment by WuoLun** [comment]
> 发全一点
全是这个报错，没有其他的

**Comment by HibiKier** [comment]
试试更新nonebot2
