### ISSUE TITLE
B站订阅推送错误

### ISSUE THREAD

**Issue by nicewsc** [HibiKier/zhenxun_bot#1092]
### 错误截图

![4A%0LS)XUU`L_KL}K~L 1FX](https://user-images.githubusercontent.com/59506907/190583780-0552f28e-3243-4c25-8064-6eb8dd5ea16f.png)

### 日志截图

没有日志报错

### 错误说明

发生了B站订阅推送错误

**Comment by fuyang0811** [comment]
我这边也出现了

**Comment by meng-luo** [comment]
+1

**Comment by xANoyU** [comment]
+1

**Comment by noahzark** [comment]
等阿咪merge，或者手动改吧
参考
https://github.com/HibiKier/zhenxun_bot/pull/1090/commits/6a7405385362da90c305742cafcb9f5dd8e80d79

**Comment by q56535** [comment]
此问题出现是因为
![image](https://user-images.githubusercontent.com/26663837/190625532-05729ae4-f5a2-4291-a328-c84f28c20745.png)
![image](https://user-images.githubusercontent.com/26663837/190625590-6740d8c3-06f6-4be1-b020-00e51b4857c5.png)

**Comment by MengChenJack** [comment]
+1，我的也出错了，在日志里疯狂报错
