### ISSUE TITLE
A issue

### ISSUE THREAD

**Issue by Adsicmes** [HibiKier/zhenxun_bot#11]
我换上了ubuntu装了宝塔  在里边的应用程序管理器运行
python bot.py
出现这个
![image](https://user-images.githubusercontent.com/79645438/126156254-6076369c-b120-48a0-b146-0e597c1b507e.png)
但我所用的环境已经安装过了
nb-cli和requirements.txt

**Comment by HibiKier** [comment]
是用了虚拟环境吗？

**Comment by Adsicmes** [comment]
是的  但环境应该已经安装过了
![image](https://user-images.githubusercontent.com/79645438/126156661-89bcfe53-4a3b-4b28-a577-abdadfa05b99.png)
这是使用的环境
![image](https://user-images.githubusercontent.com/79645438/126156824-cbd8db24-ad10-4fb0-954b-565598fbf5a6.png)
这是该环境的位置
![image](https://user-images.githubusercontent.com/79645438/126156945-038b232f-a974-48b3-a44c-d398d2962a2a.png)
nb-cli满足
![image](https://user-images.githubusercontent.com/79645438/126157067-b5c54790-8c3c-4fd0-a440-ec67c8274a88.png)
同样满足

**Comment by Adsicmes** [comment]
您是如何运行的，通过screen吗

**Comment by HibiKier** [comment]
虽然是通过screen，但是我感觉是虚拟环境的问题？软链接里是有区分python和python3吗，试试python3 bot.py或者/user/bin/python3 bot.py

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126158744-e3e4d9e1-69a9-4a32-b78c-05c0e2034258.png)

**Comment by HibiKier** [comment]
....你进一下/home/adsicmes/.local，你看看里面是不是有个虚拟环境。。

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126159395-7d411b1b-bfcf-466c-9eea-1ba04e676820.png)
这算吗（

**Comment by HibiKier** [comment]
你安装的包都在lib目录下，这个文件夹里没有python文件吗

**Comment by Adsicmes** [comment]
![Uploading image.png…]()
有的

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126159681-be021756-8d63-44e1-a161-d6e61e9bb138.png)
you有的

**Comment by HibiKier** [comment]
.local下有可python这种脚本吗？直接python3 bot.py也无效吗？

**Comment by Adsicmes** [comment]
无效
![image](https://user-images.githubusercontent.com/79645438/126160886-cf43821c-cf9d-4a62-8079-883eba1448fc.png)

**Comment by HibiKier** [comment]
不要用sudo

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126161000-b6a58eef-4d4c-49ff-a8bc-c7fc4b523a82.png)

**Comment by HibiKier** [comment]
权限问题？ 文件你是直接拖进去的吗还是git 下载的？

**Comment by Adsicmes** [comment]
拖进去解压的，git的话我连不上github

**Comment by HibiKier** [comment]
chown -R adsicmes /home/adsicmes/ ，试试这个

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126161340-8a467379-c4d2-4a83-a5af-3aa6715eb9be.png)
诸如此类

**Comment by HibiKier** [comment]
用 root执行此命令

**Comment by Adsicmes** [comment]
我不知道root的密码  我在安装ubuntu的时候只设置了这个用户

**Comment by HibiKier** [comment]
sudo chown -R adsicmes /home/adsicmes/，试试这个

**Comment by Adsicmes** [comment]
确定了  是ubuntu的原因（

我明天换一下Centos（（.

感谢，大晚上还帮忙解决问题

**Comment by HibiKier** [comment]
没事，我刚好在扩充图库

**Comment by Raysamatoken** [comment]
ubuntu是有问题的，建议CentOS
pip3 install -r requirement.txt 依赖装完后直接yum install chromium一把梭就完全没问题了

**Comment by Adsicmes** [comment]
非常感谢😊

**Comment by Adsicmes** [comment]
非常感谢😊

**Comment by Adsicmes** [comment]
我换了centos7  他还是提示没有nonebot这个模块

**Comment by Raysamatoken** [comment]
> 我换了centos7 他还是提示没有nonebot这个模块

yum -y install epel-release
yum install python3.9

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126315685-5b340af1-042f-4c54-816e-30e7a2da31ed.png)

**Comment by Raysamatoken** [comment]
进到目录 pip3 install -r requirement.txt

**Comment by Adsicmes** [comment]
可以要一下联系方式吗（

**Comment by Adsicmes** [comment]
[ZhenXunQQbot.log](https://github.com/HibiKier/zhenxun_bot/files/6847977/ZhenXunQQbot.log)
已经确定所有依赖都安装了
这是日志

**Comment by Adsicmes** [comment]
[ZhenXunQQbot.log](https://github.com/HibiKier/zhenxun_bot/files/6847990/ZhenXunQQbot.log)
修正后的（（

**Comment by HibiKier** [comment]
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

Exception: 数据库连接错误.... e: role "adsicmes" does not exist

少依赖libGL.so.1，数据库的adsicmes不存在

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126319615-d5fc68ec-cbb5-4431-be10-ba573b8496a3.png)
那个依赖我谷歌过了但不知道是什么（

**Comment by HibiKier** [comment]
yum install mesa-libGL 试试
你数据库bind咋写的？（密码用xxxx代替，我康康

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126320515-aab0da8e-c4f6-4686-856c-9a43282e8f57.png)
这个没事主机在我家  外网进不来

**Comment by Adsicmes** [comment]
http://frzz.fun/down/yzZvEpnt2ezh
这是新的日志
我暂时开了映射

**Comment by Adsicmes** [comment]
是可以导入了但数据库仍然无法连接

**Comment by HibiKier** [comment]
bind是正确的，看着是postgresql的用户没创建？可以进去命令行界面吗？

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126322409-efeba9f4-4bb3-4d6b-a600-600a3f7b93c3.png)
可以的

**Comment by HibiKier** [comment]
create user adsicmes with password '123123';

这样可以创建成功嘛？

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126322977-6ea1410a-3e53-4861-9f18-70b37b1facdd.png)

**Comment by HibiKier** [comment]
好家伙，合着之前就没创建用户

create database qqbot owner adsicmes;   创建数据库

**Comment by Adsicmes** [comment]
怪  结果是控制台有问题？
![image](https://user-images.githubusercontent.com/79645438/126323475-cab161d8-9970-4ee8-9b27-7abef32895e6.png)

**Comment by HibiKier** [comment]
可以运行了吗？

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126324317-aa0ffd39-a3d4-4c98-8cb9-01a843824ed6.png)
我认为他好了 但是我没有证据（😀）

**Comment by HibiKier** [comment]
确实是好了，这是在下载抽卡资源

**Comment by Adsicmes** [comment]
好的  感谢！
大晚上又让您帮忙了

**Comment by Adsicmes** [comment]
代理怎么写（
格式是怎样的，那两行代理我愣是没看懂

**Comment by HibiKier** [comment]
示例：system_proxy: Optional[str] = 'http://127.0.0.1:7890'

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126772600-7b323e06-4e5d-497c-a209-828a0bd3c834.png)

**Comment by HibiKier** [comment]
不影响运行的话问题不大

**Comment by Adsicmes** [comment]
没反应

**Comment by Adsicmes** [comment]
ffmpeg是在zhenxunbot启动的过程中安装完毕的

**Comment by HibiKier** [comment]
ffmpeg安装完毕后重启gocq

**Comment by Adsicmes** [comment]
> 示例：system_proxy: Optional[str] = 'http://127.0.0.1:7890'

![image](https://user-images.githubusercontent.com/79645438/126796119-f635f109-c4e2-4710-89b7-984e77175c09.png)

**Comment by HibiKier** [comment]
system_proxy: Union[str, None] = 'http://127.0.0.1:7890'

**Comment by Adsicmes** [comment]
下边的buff proxy是什么

**Comment by HibiKier** [comment]
BUFF代理，有一些云服务器的IP被BUFF给BAN掉了，无法访问

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126799263-10fe3753-3a70-4d93-b28c-9484cecf9a0b.png)
![image](https://user-images.githubusercontent.com/79645438/126799282-b1390637-3f65-4a8e-8ed7-98455f16d02c.png)
![image](https://user-images.githubusercontent.com/79645438/126799450-880cbf2a-1879-410a-9713-ce822e56a999.png)
![image](https://user-images.githubusercontent.com/79645438/126799479-86cecc42-3149-4c68-b910-1af76e35902e.png)

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126799263-10fe3753-3a70-4d93-b28c-9484cecf9a0b.png)
![image](https://user-images.githubusercontent.com/79645438/126799282-b1390637-3f65-4a8e-8ed7-98455f16d02c.png)
![image](https://user-images.githubusercontent.com/79645438/126799450-880cbf2a-1879-410a-9713-ce822e56a999.png)
![image](https://user-images.githubusercontent.com/79645438/126799479-86cecc42-3149-4c68-b910-1af76e35902e.png)

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/126799675-5ec1a7d7-1703-427c-9335-d03966d39276.png)
我设置的应该是没有问题才对，但是还是代理不上的样子
我在电脑上使用的同样的节点，没有任何问题

**Comment by HibiKier** [comment]
呃，在服务器上试试curl www.google.com，而且p搜是不需要代理的，是网的问题？

**Comment by Adsicmes** [comment]
您是用的什么代理呢
还是说您服务器在国外？

**Comment by HibiKier** [comment]
阿里云服务器，使用的clash代理

**Comment by Adsicmes** [comment]
数据是全部存在数据库里的吗
如果我重新下载替换一遍会发生什么
给群友玩坏了
![Screenshot_20210729-214520_JuiceSSH.png](https://user-images.githubusercontent.com/79645438/127505307-93d0860f-4f49-43f5-903c-c19abd6d44ff.png)
![Screenshot_20210729-215910_JuiceSSH.png](https://user-images.githubusercontent.com/79645438/127505351-3b797983-dfee-4fa7-8a4b-d9ae0125ee4d.png)

**Comment by Adsicmes** [comment]
![630efbf13ff7f9f8.jpg](https://user-images.githubusercontent.com/79645438/127506388-b9997463-25e3-4699-bbd2-99fd7c9de58e.jpg)
化学式这狗屁玩意塞了十万位数字

**Comment by Adsicmes** [comment]
何时修复（大概）

**Comment by HibiKier** [comment]
你可以先更新一下plugins/draw_card/announcement.py文件，虽然无法正确更新赛马娘UP池，但是可以正常启动，迟点再把正常更新更上去

**Comment by Adsicmes** [comment]
好

**Comment by HibiKier** [comment]
已修，还是替换announcement.py

**Comment by Adsicmes** [comment]
色图的好感度限制能关掉吗（

还有语录，如何添加（

群友太为难我了😢

（不行我得找时间研究研究）

**Comment by HibiKier** [comment]
configs/config.py把INITIAL_SETU_PROBABILITY改成1，语录是在线获取，没有添加

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/127737184-e74a2024-5f92-4e26-9425-c249a756190e.png)

**Comment by Adsicmes** [comment]
这两个是干嘛的
