### ISSUE TITLE
问题反馈: 抽卡，今日素材 ， 模块等 出现报错

### ISSUE THREAD

**Issue by Sayyiku** [HibiKier/zhenxun_bot#110]
1. 服务器版本：CentOS 7.9
2. python版本：3.8.1
3. postgresql  :  12.9

pip下载时无报错

![1FY6S UA5GQ3SHQ}BN4}R}9](https://user-images.githubusercontent.com/77047823/151009741-235079a5-a22d-45c2-8039-96724834ff68.png)

![0BJ`OAZYSK$N9QR6)80`_`7](https://user-images.githubusercontent.com/77047823/151009804-97bd3e93-11e9-487c-bca3-ba9b2faf7591.png)

![O9KVLMGUL5PLCEGUS%U3GCI](https://user-images.githubusercontent.com/77047823/151009837-28d5b97d-9aeb-4604-87a9-aa4a3a4ac85a.png)

请问是服务器版本不支持原因吗？
如何解决，还望解答

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/151293003-d17d011d-a412-4d41-8c3d-7b330ad72f79.png)
缺环境，第二个大概率疯狂，第三个你原神json文件里有数据吗？

**Comment by Sayyiku** [comment]
好的，感谢解答
