### ISSUE TITLE
B站推送报错无法运行

### ISSUE THREAD

**Issue by garfieldwlx** [HibiKier/zhenxun_bot#1100]
### 错误截图
![微信截图_20220918122606](https://user-images.githubusercontent.com/97733781/190885821-9f4dae16-06fe-47a4-9f2c-e900480bb0dc.png)
### 日志截图
![QQ截图20220918122854](https://user-images.githubusercontent.com/97733781/190885828-87002dff-2827-430b-a12c-f6a1a8f342da.png)
### 错误说明
QQ订阅不在发送 “获取信息失败...请检查订阅Id是否存在或稍后再试...的内容，但是系统后台报错且不发送动态信息
09-18 12:19:41 [WARNING] utils | 图片 resources/image/bilibili_sub/dynamic/22454326_1663388757.jpg 缺失...
09-18 12:20:35 [ERROR] plugins | Id：22454326 获取信息失败...请检查订阅Id是否存在或稍后再试...
09-18 12:21:05 [ERROR] plugins | Id：22454326 获取信息失败...请检查订阅Id是否存在或稍后再试...
09-18 12:21:35 [ERROR] plugins | Id：22454326 获取信息失败...请检查订阅Id是否存在或稍后再试...
09-18 12:22:35 [WARNING] apscheduler | Execution of job "_ (trigger: interval[0:00:30], next run at: 2022-09-18 12:22:35 CST)" skipped: maximum number of running instances reached (1)
09-18 12:22:41 [ERROR] plugins | B站订阅：获取用户动态 发送错误 <class 'playwright._impl._api_types.TimeoutError'>：Timeout 30000ms exceeded.

**Comment by modeilan** [comment]
更新后出现了，离谱的是删除订阅shell还是疯狂弹这段话

**Comment by 1294266616** [comment]
> 更新后出现了，离谱的是删除订阅shell还是疯狂弹这段话

确实后台疯狂报错

**Comment by HibiKier** [comment]
更新
