### ISSUE TITLE
启动时提示没有nonebot模块

### ISSUE THREAD

**Issue by 1103859909** [HibiKier/zhenxun_bot#1102]
![20220918145030](https://user-images.githubusercontent.com/107859647/190889599-76141211-5484-418b-9bcc-d9b331795e7f.png)

**Comment by 1103859909** [comment]
解决了

**Comment by white-empty** [comment]
请问一下是怎么解决的可以吗
我也遇到了相同的问题

**Comment by yunmu789** [comment]
请问一下是怎么解决的可以吗
我也遇到了相同的问题
