### ISSUE TITLE
添加词条失败

### ISSUE THREAD

**Issue by Yql66** [HibiKier/zhenxun_bot#1103]
### 错误截图
![image](https://user-images.githubusercontent.com/111969738/190900403-d3482fe6-e630-4896-878e-3c76e36ecce8.png)

![8DBS`G_1Z~UW}PSME7P0$2M](https://user-images.githubusercontent.com/111969738/190900284-05cad284-057a-4608-8c70-9b9666c33dbf.png)
### 日志截图

[img]

###错误说明
机器人显示添加成功，但是无法回复且出现报错

**Comment by HibiKier** [comment]
这段报错时nonebot的，建议提交到nonebot2的issues
