### ISSUE TITLE
有没有大大知道system watcher windows tool是个什么程序？

### ISSUE THREAD

**Issue by akua0z** [HibiKier/zhenxun_bot#1105]
### 错误截图

![S61@T1~@`AKTIVOEM9F I7Q](https://user-images.githubusercontent.com/113225788/191025906-57cb589a-662d-4bff-a2e5-0f5600cfb751.png)

### 错误说明
真寻bot运行一段时间后（一两天）就会因为出现CPU满载停用，打开远程会话一看，system watcher windows tool把CPU全吃满了，结束这个进程一切恢复正常，谷歌了半天也没找到有相关的资料，在服务项里也没找到这玩意儿，这到底干嘛用的，以及为啥会满载  *（目前用的是腾讯云） 求解答

**Comment by ouzaizak** [comment]
你好，我也遇到了一样的问题，把它删除过后一段时间会自己下回来，请问你是怎么解决的？

**Comment by akua0z** [comment]
> 你好，我也遇到了一样的问题，把它删除过后一段时间会自己下回来，请问你是怎么解决的？

后来查清原因了，我是pg端口被扫了，服务器被别人盗用去挖矿了。我改了强密码，换了端口号就解决了。

**Comment by ouzaizak** [comment]
好的，谢谢你
