### ISSUE TITLE
启动真寻的时候出现了错误

### ISSUE THREAD

**Issue by white-empty** [HibiKier/zhenxun_bot#1106]
### 错误截图

![image](https://user-images.githubusercontent.com/64899541/191243611-88f4c90a-31d7-4dde-921c-918fd5dd7d09.png)

### 日志截图

同错误截图 因为没有启动起来所以找不到哪里有日志。。。（非常抱歉）

### 错误说明

安装了go-cp和pgadmin 已经按照步骤配置 最后用Python bot.py启动可爱的真寻bot时弹出错误 错误如图 没有找到nonebot
已尝试的解决方法：
1.更新Python版本到9.10
2.安装了nonebot2和clip脚手架
3.尝试在后台挂起nonebot的情况下开启真寻bot

真心求助 纯萌新没有思路了

**Comment by white-empty** [comment]
附上我的配置截图
**pgAdmin数据库配置截图**
![image](https://user-images.githubusercontent.com/64899541/191244954-8d50c743-ad8d-4d01-a8db-f5d4f5980d2f.png)
**cmd窗口截图**
![image](https://user-images.githubusercontent.com/64899541/191244981-4021250e-e0b1-4deb-9c25-df0dca001135.png)
**go-cp config.yml文件配置截图**
![image](https://user-images.githubusercontent.com/64899541/191245026-a8fa0b2b-8f2e-4132-a7d2-d01683093888.png)
**可爱真寻bot \configs\config.py 配置截图**
![image](https://user-images.githubusercontent.com/64899541/191245341-f3c7ac6e-5ef5-4a68-bfa6-bb3f25e86479.png)

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/194573491-f07846a2-294f-49c0-be3c-4df09e069d47.png)
