### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by acodegod** [HibiKier/zhenxun_bot#111]
![](https://inews.gtimg.com/newsapp_ls/0/14494491412/0)

**Comment by HibiKier** [comment]
先尝试把plugins/genshin/query_point_xxxx那个插件删了吧

**Comment by BalconyJH** [comment]
zhenxun版本：0.0.9.0

运行环境：Windows 11 pro / python3.8

go-cqhttp 版本：
PS C:\cq> .\go-cqhttp_windows_amd64.exe
[2022-02-05 04:04:47] [INFO]: 当前版本:v1.0.0-beta8-fix2
Bug 描述

描述你遇到的问题：插件加载失败

报错日志
![image](https://user-images.githubusercontent.com/73932916/152787785-c67a356f-2eb1-4908-aeac-283b04a4ee53.png)

运行日志
![image](https://user-images.githubusercontent.com/73932916/152788401-5fdc11e7-30c9-4546-a778-558ed6d131fc.png)
![image](https://user-images.githubusercontent.com/73932916/152787939-05d1b059-7cd2-4989-95f3-869d9c0e1fde.png)
![image](https://user-images.githubusercontent.com/73932916/152788035-d23c5724-df86-42f1-b1d3-fca510399d90.png)

**Comment by HibiKier** [comment]
help插件加载的报错呢？

**Comment by HibiKier** [comment]
你发的那个报错日志也只是apscheduler的警告

**Comment by BalconyJH** [comment]
![carbon](https://user-images.githubusercontent.com/73932916/152808482-1f7c23b8-4a44-4338-bb00-25f103d21e70.png)

**Comment by BalconyJH** [comment]
ai和genshin被我单独删掉了

**Comment by HibiKier** [comment]
可能被其他功能阻断了，试试 详细帮助 能不能用

**Comment by BalconyJH** [comment]
> 可能被其他功能阻断了，试试 详细帮助 能不能用

![屏幕截图 2022-02-08 134108.png](https://user-images.githubusercontent.com/73932916/152926036-11dc5368-0202-402d-8b3f-0c61a8a76ce5.png)

**Comment by BalconyJH** [comment]
破案了，我的.env失踪了，我真无语🤣
