### ISSUE TITLE
B站转发解析 和 b站转发解析 能合并吗

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#1110]
![image](https://user-images.githubusercontent.com/105090141/191430675-8cdf3bff-581d-428c-a66a-607770a7d05f.png)

发送“关闭B站转发解析”后，帮助图片中该功能已变红，但发送BV号时该功能仍能做出响应
实际能生效的指令是“关闭b站转发解析”，但只发这个帮助图片中该功能又不会变红......

**Comment by HibiKier** [comment]
43cddb3580bd5bf32c03cd8f8f805c8177a1ceba
