### ISSUE TITLE
B站订阅动态超时

### ISSUE THREAD

**Issue by a042979** [HibiKier/zhenxun_bot#1111]
### 错误截图

![image](https://user-images.githubusercontent.com/114063925/191462157-6ace8fff-afdb-45b8-b520-e16631bc109e.png)

### 日志截图

![image](https://user-images.githubusercontent.com/114063925/191462186-aade754f-fce9-4cad-86cd-c8e7dda3b484.png)

### 错误说明

发生了获取动态超时的错误
尝试过删除订阅但仍无法解决问题

**Comment by HibiKier** [comment]
933523ae6d4e9f9cd3ab49c1a0ae286c21ad28aa
