### ISSUE TITLE
b23.tv链接解析错误

### ISSUE THREAD

**Issue by webjoin111** [HibiKier/zhenxun_bot#1115]
### 错误截图

![YT~162GKL00HOXN 2 { ~}O](https://user-images.githubusercontent.com/32546670/192145922-b8aa7a11-e527-4c54-b976-387e3771ccf0.png)

### 错误说明

b23.tv格式的链接，真寻无法成功解析，显示的错误是ValueError(f"{video_id} 不是一个有效的 AV 或 BV 号").
比如链接：https://b23.tv/WkY32qI，https://b23.tv/8Buu4Nu

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/194560196-74c0f3d4-8f2a-412f-9ec9-6f12d784dfd3.png)
先尝试更新吧
