### ISSUE TITLE
b站私人订阅出现的问题

### ISSUE THREAD

**Issue by 46516044** [HibiKier/zhenxun_bot#1116]
### 错误截图
![6O 3E9OA~8LJ) KJ3K_QELU](https://user-images.githubusercontent.com/48992430/192208997-a2f026ce-2b29-4db6-82dd-32befa0ca2f3.png)

### 日志截图
![image](https://user-images.githubusercontent.com/48992430/192209048-adfdeace-2614-4252-b098-82d09aab2c77.png)

### 错误说明
删除失败，并且会继续报错
发生了xx错误...

**Comment by ayakasuki** [comment]
![image](https://user-images.githubusercontent.com/20859971/193437462-baa5d99b-c566-4606-80e2-4d7c8c1ff6e4.png)
一样

**Comment by ayakasuki** [comment]
B站订阅陆陆续续出现了不少问题来着 希望能够修复

**Comment by HibiKier** [comment]
3ee9ae5fb867f2b1d05ade441dbe23bec16089b4
