### ISSUE TITLE
古早版本的bot如何进行更新

### ISSUE THREAD

**Issue by zzzcola** [HibiKier/zhenxun_bot#112]
很久之前下载的版本，版本是0.05，现在想再保留之前的用户数据的基础上进行更新，但是发现替换文件夹行不通，会出现报错，请问应该如何更新
![image](https://user-images.githubusercontent.com/74588637/153377843-82800f3f-c32a-49b5-a5ec-fc1d86722710.png)

**Comment by HibiKier** [comment]
你确定你config文件夹替换了？我的建议是保留data和resources文件夹，config的配置也可以备份一下（免得自己配置忘了），其他全删重新clone，另外建议每个版本0.0.x.0的script.py都替换后运行一下，里面都是数据库的一些sql结构变更，或者你可以手动改。

**Comment by HibiKier** [comment]
script.py是替换文件后启动bot，且要按版本顺序

**Comment by zzzcola** [comment]
请问替换了config之后开始运行会发现每个库都会报错
![image](https://user-images.githubusercontent.com/74588637/153388846-8fc5907b-a56c-43ea-a187-c453c9e38c72.png)
想知道什么原因呜呜

**Comment by zzzcola** [comment]
有可能是安装依赖的retrying缺失
![image](https://user-images.githubusercontent.com/74588637/153392813-e4814976-cac9-4e3d-9b57-52e578033600.png)

**Comment by HibiKier** [comment]
报错不是写的很清楚了吗

**Comment by zzzcola** [comment]
关闭代理之后就能够正常安装了，解决了，谢谢
