### ISSUE TITLE
怎么删除色图库的图片

### ISSUE THREAD

**Issue by 1776304537** [HibiKier/zhenxun_bot#1121]
色图占用太多空间了，想完全删掉，该怎么删呢？

**Comment by HibiKier** [comment]
resources/image/_setu和_r18文件夹

**Comment by 1776304537** [comment]
数据库里是不是还是在的呢？

**Comment by DDS-DS** [comment]
数据库里面只是简单得记录一些信息，并不会占用过多的内存

**Comment by 1776304537** [comment]
以后如果要发的话是不是就会继续发存数据库里的这几张id呢？

**Comment by DDS-DS** [comment]
> 以后如果要发的话是不是就会继续发存数据库里的这几张id呢？

我没怎么用过这个插件，你可以尝试一下，应该可以吧~

**Comment by HibiKier** [comment]
FAQ有

**Comment by 1776304537** [comment]
看了下真寻文档的FAQ 
救命！最爱的色图数量只在100不会增加
看多少存多少，例如发送：色图原神 便会增加至多100张图片，色图越看越多，或者在配置中暂时关闭本地存储，全部采用网络请求
只有关于本地的说明

**Comment by 1776304537** [comment]
我是想以后再发色图的话  不要出现之前的那几张

**Comment by HibiKier** [comment]
不是写了吗，增加至多100张

**Comment by 1776304537** [comment]
谢谢 我自己试试吧
