### ISSUE TITLE
新手向

### ISSUE THREAD

**Issue by BlueLolikon** [HibiKier/zhenxun_bot#1126]
为什么添加词条过后在群里面还是不能触发，是我添加有错误吗还是方法错误？
想在群里面发特定的消息，真寻发特定的图片，这个应该是添加词条吧
ಥ_ಥ

**Comment by HibiKier** [comment]
日志

**Comment by BlueLolikon** [comment]
> 日志

?大佬救救(;´༎ຶД༎ຶ`)
