### ISSUE TITLE
本地色图不会自动撤回

### ISSUE THREAD

**Issue by 1776304537** [HibiKier/zhenxun_bot#1127]
网上搜索的色图可以，本地的有日志但就是不撤回

**Comment by 1776304537** [comment]
配置里是纯数字 没有单引号

**Comment by 1776304537** [comment]
![QQ截图20221010104400](https://user-images.githubusercontent.com/24807330/194792725-536251eb-822a-4403-9403-6a11f60e7017.jpg)
这个应该是撤回日志

**Comment by 1776304537** [comment]
我又测试了一下，电脑上的qq看到是撤回的，手机里却还在。换了个别的qq发现也被撤回了，但是我自己手机qq里看是没有被撤回的

**Comment by HibiKier** [comment]
= =这，其他端看到已经撤回了不就是已经撤回生效了吗

**Comment by 1776304537** [comment]
后来发现可能确实是我设备问题吧 抱歉
