### ISSUE TITLE
根据教程安装完后很多功能无法使用

### ISSUE THREAD

**Issue by lihaojie87** [HibiKier/zhenxun_bot#113]
> 02-11 13:38:23 [INFO] nonebot | NoneBot is initializing...
02-11 13:38:23 [INFO] nonebot | Current Env: dev
02-11 13:38:23 [INFO] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
02-11 13:38:23 [INFO] nonebot | Succeeded to import "use"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "shop_handle"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "buy"
/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
02-11 13:38:25 [INFO] nonebot | Succeeded to import "reset_today_gold"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "gold"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "my_props"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "shop"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "hooks"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "rule"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "update_group_member_info"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "data_source"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "custom_welcome_message"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "timing_task"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "admin_config"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "switch_rule"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "admin_bot_manage"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "clear_data"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "super_task_switch"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "manager_group"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "reload_setting"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "exec_sql"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "set_admin_permissions"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "bot_friend_group"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "update_friend_group_info"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "super_cmd"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "super_help"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "apscheduler"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "help"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "group_handle"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "broadcast"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "ban"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "init_plugin_config"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "update_info"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "invite_manager"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "admin_help"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "scripts"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "nickname"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "upload_image"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "send_image"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "delete_image"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "move_image"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "image_management"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "c_song"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "check"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "nbnhhsh"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "my_info"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "send_setu"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "model"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "update_setu"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "send_setu_"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "statistics_handle"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "statistics_hook"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "statistics"
02-11 13:38:25 [INFO] nonebot | Succeeded to import "gold_redbag"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "weather"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "withdraw"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "pix_pass_del_keyword"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "pix_update"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "pix"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "pix_add_keyword"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "pix_show_info"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "pix_gallery"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "parse_bilibili_json"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "draw_card"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "group_last_chat"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "update_gocqhttp"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "bilibili_sub"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "open_cases"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "pid_search"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "update_picture"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "coser"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "fake_msg"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "send_dinggong_voice"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "comments_163"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "cover"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "wbtop"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "poetry"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "jitang"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "alapi"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "epic"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "bt"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "check_zhenxun_update"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "dialogue"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "search_buff_skin_price"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "roll"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "mute"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "yiqing"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "russian"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "white2black_image"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "poke"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "group_welcome_msg"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "fudu"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "pixiv_rank_search"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "server_ip"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "about"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "word_hanlde"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "message_handle"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "word_bank"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "one_friend"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "aconfig"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "translate"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "almanac"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "material_remind"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "query_resource_points"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "utils"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "bind"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "query_memo"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "reset_today_query_user_data"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "query_role"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "genshin_sign"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "resin_remind"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "models"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "query_user"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "genshin"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "luxun"
02-11 13:38:26 [INFO] nonebot | Succeeded to import "what_anime"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "search_anime"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "nonebot_plugin_picsearcher"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "ai"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "quotations"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "sign_in"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "auth_hook"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "other_hook"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "chkdsk_hook"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "withdraw_message_hook"
02-11 13:38:27 [INFO] nonebot | Succeeded to import "ban_hook"
02-11 13:38:27 [INFO] nonebot | Running NoneBot...
02-11 13:38:27 [INFO] uvicorn | Started server process [2781]
02-11 13:38:27 [INFO] uvicorn | Waiting for application startup.
02-11 13:38:27 [INFO] services | Database loaded successfully!
/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/apscheduler/triggers/cron/__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/apscheduler/triggers/cron/__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/apscheduler/triggers/interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)
02-11 13:38:27 [INFO] nonebot_plugin_apscheduler | Scheduler Started
02-11 13:38:27 [INFO] nonebot | register_use 成功注册商品：好感度双倍加持卡Ⅰ 的使用函数
02-11 13:38:27 [INFO] nonebot | register_use 成功注册商品：好感度双倍加持卡Ⅱ 的使用函数
02-11 13:38:27 [INFO] nonebot | register_use 成功注册商品：好感度双倍加持卡Ⅲ 的使用函数
02-11 13:38:27 [INFO] utils | 正在检查 Chromium 更新
02-11 13:38:28 [INFO] nonebot | 已成功加载 57 个非限制插件.
02-11 13:38:28 [INFO] utils | 已成功加载 5 个Cd限制.
02-11 13:38:28 [INFO] utils | 已成功加载 12 个Block限制.
02-11 13:38:28 [INFO] utils | 已成功加载 1 个Count限制.
02-11 13:38:28 [INFO] nonebot | 初始化数据完成...
02-11 13:38:34 [INFO] nonebot | 成功获取赛马娘当前up信息...当前up池:  &
02-11 13:38:39 [INFO] nonebot | 成功获取明日方舟当前up信息...当前up池:
02-11 13:38:42 [INFO] nonebot | 成功获取原神当前up信息...当前up池: 「陵薮市朝」 & 「神铸赋形」
02-11 13:38:46 [INFO] nonebot | 成功获取坎公骑冠剑当前up信息...当前up池: 2月3日UP卡池 & 2月3日UP卡池
02-11 13:38:54 [INFO] nonebot | 更新原神资源类型成功...
02-11 13:38:54 [INFO] uvicorn | Application startup complete.
02-11 13:38:54 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:55555 (Press CTRL+C to quit)
02-11 13:38:54 [INFO] uvicorn | ('127.0.0.1', 59868) - "WebSocket /cqhttp/ws" [accepted]
02-11 13:38:54 [INFO] nonebot | WebSocket Connection from CQHTTP Bot 1683304950 Accepted!
02-11 13:38:55 [INFO] nonebot | 已成功加载 10 个被动技能.
02-11 13:38:56 [INFO] nonebot | 已成功加载 27 条超级用户命令

**Comment by lihaojie87** [comment]
有类似的报错

> 02-11 13:42:47 [INFO] nonebot | CQHTTP 1683304950 | [message.group.normal]: Message -2043655929 from 874*****8@[群:724***40] "我的开箱"
02-11 13:42:47 [INFO] nonebot | Event will be handled by <Matcher from mute, type=message, priority=1, temp=False>
02-11 13:42:47 [INFO] nonebot | Event will be handled by <Matcher from parse_bilibili_json, type=message, priority=1, temp=False>
02-11 13:42:47 [INFO] nonebot | Event will be handled by <Matcher from group_last_chat, type=message, priority=1, temp=False>
02-11 13:42:47 [INFO] nonebot | Matcher <Matcher from group_last_chat, type=message, priority=1, temp=False> running complete
02-11 13:42:47 [INFO] nonebot | Matcher <Matcher from mute, type=message, priority=1, temp=False> running complete
02-11 13:42:47 [INFO] nonebot | Matcher <Matcher from parse_bilibili_json, type=message, priority=1, temp=False> running complete
02-11 13:42:47 [INFO] nonebot | Event will be handled by <Matcher from ai, type=message, priority=8, temp=False>
Task was destroyed but it is pending!
task: <Task pending name='Task-11909' coro=<Bot.handle_message() running at /root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py:328> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7efda6ab4be0>()]>>
02-11 13:42:54 [INFO] nonebot | Matcher <Matcher from ai, type=message, priority=8, temp=False> running complete
02-11 13:42:54 [ERROR] nonebot | Running matcher <Matcher from ai, type=message, priority=8, temp=False> failed.
Traceback (most recent call last):
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/matcher.py", line 544, in run
    await handler(self, bot, event, state_)
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/zhenxun_bot/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 328, in handle_message
    await handle_event(self, event)
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/message.py", line 237, in handle_event
    results = await asyncio.gather(*pending_tasks, return_exceptions=True)
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/asyncio/tasks.py", line 827, in gather
    fut = ensure_future(arg, loop=loop)
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/asyncio/tasks.py", line 668, in ensure_future
    task = loop.create_task(coro_or_future)
> File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/matcher.py", line 601, in run
    current_bot.reset(b_t)
ValueError: <Token var=<ContextVar name='current_bot' at 0x7efdc591eae0> at 0x7efda6adbe40> was created in a different Context
Exception ignored in: <coroutine object _check_matcher at 0x7efda6b97cc0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
RuntimeError: coroutine ignored GeneratorExit

**Comment by HibiKier** [comment]
你这啥啊，“我的开箱”怎么会运行到ai插件，截图报错日志看看

**Comment by lihaojie87** [comment]
![image](https://user-images.githubusercontent.com/50283726/153575099-7c95b6cc-5cde-4b91-919e-0d924ebea90e.png)
这个文件吗？error_2022-02-11.log
最后一个报错是这个
`ValueError: <Token var=<ContextVar name='current_bot' at 0x7ff18521fa40> at 0x7ff1661382c0> was created in a different Context
"error_2022-02-11.log" 3794L, 278327C                                                                 3794,1        Bot
    │       │   │      └ <nonebot.drivers.fastapi.Driver object at 0x7ff1851bca00>
    │       │   └ None
    │       └ <function run at 0x7ff183d63040>
    └ <module 'uvicorn' from '/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/uvicorn/__init__.py'>
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7ff183d5baf0>
    └ <uvicorn.server.Server object at 0x7ff167365d00>
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7ff183d5bb80>
    │    │                  └ <uvicorn.server.Server object at 0x7ff167365d00>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 328, in handle_message
    await handle_event(self, event)
          │            │     └ HeartbeatMetaEvent(time=1644574568, self_id=1683304950, post_type='meta_event', meta_event_type='heartbeat', status=Status(on...
          │            └ <nonebot.adapters.cqhttp.bot.Bot object at 0x7ff1655379a0>
          └ <function handle_event at 0x7ff184d87820>
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/message.py", line 237, in handle_event
    results = await asyncio.gather(*pending_tasks, return_exceptions=True)
                    │       │       └ [<coroutine object _check_matcher at 0x7ff16553f5c0>, <coroutine object _check_matcher at 0x7ff16553fb40>, <coroutine object ...
                    │       └ <function gather at 0x7ff185b90c10>
                    └ <module 'asyncio' from '/root/anaconda3/envs/zhenxun/lib/python3.9/asyncio/__init__.py'>
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/asyncio/tasks.py", line 827, in gather
    fut = ensure_future(arg, loop=loop)
          │             │         └ <uvloop.Loop running=True closed=False debug=False>
          │             └ <coroutine object _check_matcher at 0x7ff1659c51c0>
          └ <function ensure_future at 0x7ff185b90af0>
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/asyncio/tasks.py", line 668, in ensure_future
    task = loop.create_task(coro_or_future)
           │    │           └ <coroutine object _check_matcher at 0x7ff1659c51c0>
           │    └ <method 'create_task' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
          │       │   │    │      └ {'_prefix': {'raw_command': '签到', 'command': ('签到',)}, '_suffix': {'raw_command': None, 'command': None}}
          │       │   │    └ PrivateMessageEvent(time=1644565250, self_id=1683304950, post_type='message', sub_type='friend', user_id=874766848, message_t...
          │       │   └ <nonebot.adapters.cqhttp.bot.Bot object at 0x7ff1655379a0>
          │       └ <function Matcher.run at 0x7ff1851aa1f0>
          └ <Matcher from ai, type=message, priority=8, temp=False>
  File "/root/anaconda3/envs/zhenxun/lib/python3.9/site-packages/nonebot/matcher.py", line 601, in run
    current_bot.reset(b_t)
    │           │     └ <Token var=<ContextVar name='current_bot' at 0x7ff18521fa40> at 0x7ff1661382c0>
    │           └ <method 'reset' of 'ContextVar' objects>
    └ <ContextVar name='current_bot' at 0x7ff18521fa40>

ValueError: <Token var=<ContextVar name='current_bot' at 0x7ff18521fa40> at 0x7ff1661382c0> was created in a different Context`

**Comment by lihaojie87** [comment]
我试了一下，在群里里可以用这个指令，私聊不行

**Comment by HibiKier** [comment]
本来就是群里用的，私聊又开不了箱

**Comment by lihaojie87** [comment]
了解了解，感谢
