### ISSUE TITLE
关于扣除货币 hook 的一些疑问

### ISSUE THREAD

**Issue by Jerry-FaGe** [HibiKier/zhenxun_bot#1130]
### 错误截图

![image](https://user-images.githubusercontent.com/40235071/195068025-133930ac-ee91-4d4b-81b5-29c32770bff1.png)

### 日志截图

![image](https://user-images.githubusercontent.com/40235071/195068381-243ba768-8693-4dc9-85e5-0f7e25beb326.png)

### 错误说明

您好，我看了下您扣除货币 hook 部分的代码有一些疑问。

- 如果直接在运行预处理 `run_preprocessor` 中执行扣除货币的代码似乎没法保证如图这种有 got 的插件能正确扣除，如果第一次运行 matcher 没有带上参数钩子会扣除一次金币，第二次传参还会走一次这个 matcher 并被 hook 到然后扣除第二次。

- 另外如果是全局接收消息并只对特定消息有回复的 matcher（类似于 `on_message(regex)` ？）有货币消耗项是否会导致用户发送的每一条消息都会扣除货币？

- 还有一种情况是插件匹配消息开头，例如“我今天XXXX”，但是在内部判断如果不是“我今天吃了XX”就直接从内部 return 。如果用户发送了“我今天在写代码”之类的话这种插件应该也会触发 hook 但是并没有做事，是否也会导致货币扣除不合理呢

请问真寻是否会出现这种情况，没出现的话又是怎么解决的呢。

**Comment by HibiKier** [comment]
在hook中的是运行前检测，无法判断是否运行结果如何，你可以使用更加细致的

**Comment by HibiKier** [comment]
在hook中的是运行前检测，无法判断是否运行结果如何，你可以使用更加细致的
```python

from utils.depends import cost_gold

# 30为金币数量

@xx.handle(parameterless=[cost_gold(30)])

@xx.got(parameterless=[cost_gold(30)])
```

**Comment by Jerry-FaGe** [comment]
> 在hook中的是运行前检测，无法判断是否运行结果如何，你可以使用更加细致的
> 
> ```python
> from utils.depends import cost_gold
> 
> # 30为金币数量
> 
> @xx.handle(parameterless=[cost_gold(30)])
> 
> @xx.got(parameterless=[cost_gold(30)])
> ```

那真是太遗憾了，我想开发一个只读取 PluginMetadata 的非侵入式货币消耗功能，但是研究了好久目前还没有什么解决我以上问题的思路 QAQ
