### ISSUE TITLE
B站订阅部分情况无法正常删除

### ISSUE THREAD

**Issue by CherryGS** [HibiKier/zhenxun_bot#1131]
### 错误截图

![4WPM SQ~O8AWJ`~%O O6F@I](https://user-images.githubusercontent.com/61844819/195295846-d68645e7-678f-4608-b9e0-63d1d4fc4e46.png)

### 日志截图
日志正常

### 错误说明
期望正常删除。
经实验，当用户名中含有某些字符时会出问题。推测是字符编码原因。
仅含有中文英文时正常，当出现日文时出错。

**Comment by HibiKier** [comment]
删除操作并没有涉及名称的东西吧，
![图片](https://user-images.githubusercontent.com/45528451/195987585-941f39c1-ac86-4842-8678-5583b1a913bd.png)
似乎也无法复现？
