### ISSUE TITLE
新手想问下在哪里可以改签到的好感度？是存在数据库里吗?我没找到

### ISSUE THREAD

**Issue by LaffeyLa** [HibiKier/zhenxun_bot#1135]

**Comment by Evilshadowruin** [comment]
私聊真寻发送下面的命令
好感度：
exec UPDATE "sign_group_users" SET impression=(好感度) WHERE user_qq=(qq号) AND group_id=(群号)
金币:
exec UPDATE "bag_users" SET gold=(金币) WHERE user_qq=(qq号) AND group_id=(群号)

**Comment by LaffeyLa** [comment]
> 私聊真寻发送下面的命令 好感度： exec UPDATE "sign_group_users" SET impression=(好感度) WHERE user_qq=(qq号) AND group_id=(群号) 金币: exec UPDATE "bag_users" SET gold=(金币) WHERE user_qq=(qq号) AND group_id=(群号)

感谢，原来可以用数据库语句修改
