### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by NovNoah** [HibiKier/zhenxun_bot#1136]
### 错误截图
#
![无标题](https://user-images.githubusercontent.com/62124595/195888170-3163768c-bae1-4a4b-940f-69e1b6c62651.png)

[img]

### 日志截图

[img]

### 错误说明

启动时报错，先前在为remake写插件标准

**Comment by HibiKier** [comment]
有个插件的version用了字符串吧，标准使用的int或float

**Comment by NovNoah** [comment]
> 有个插件的version用了字符串吧，标准使用的int或float

解决了，感谢
