### ISSUE TITLE
图片上传失败：image type error: application/octet-stream

### ISSUE THREAD

**Issue by TDuckQWQ** [HibiKier/zhenxun_bot#1138]
### 错误截图
go-cqhttp的日志如下:
![image](https://user-images.githubusercontent.com/62102282/195965778-89945e16-fb3e-4e30-8db1-6d2c2d887052.png)
![image](https://user-images.githubusercontent.com/62102282/195965851-5413cf5b-a3e7-4f5e-9ee0-ef7d6fdbe400.png)

### 日志截图

![image](https://user-images.githubusercontent.com/62102282/195965804-d6627195-68d2-4d06-930f-4ee38a8486cc.png)

### 错误说明

图片上传失败，色图及pix无法发出

**Comment by eachbol2333** [comment]
同，昨天开始就发不了色图了

**Comment by qingba** [comment]
更改镜像源试试

**Comment by HibiKier** [comment]
反代是用的re吗

**Comment by SanaeMio** [comment]
P站的反代临时换用i.pixiv.cat可以解决，这个没寄，可能需要搭配梯子
