### ISSUE TITLE
增加摸头功能

### ISSUE THREAD

**Issue by RocksonLee** [HibiKier/zhenxun_bot#114]
增加摸头功能，在适配了nonebot商店多次后，失败
使用<https://github.com/MeetWq/nonebot-plugin-petpet>
![image](https://user-images.githubusercontent.com/57697347/153604597-51ad5d23-9f95-4fa7-9f74-3175b9827d31.png)
![image](https://user-images.githubusercontent.com/57697347/153604673-fd15841a-c759-4839-bb8e-29bcb1628be8.png)

**Comment by HibiKier** [comment]
等真寻更新至b2

**Comment by HibiKier** [comment]
已更新至beta2
