### ISSUE TITLE
今天看到真寻版本更新，看到色图插件反响代理更新了，更新之后使用色图插件显示下载成功，但是上传失败，我去本地文件夹看了一下下载的图片，都是13字节大小左右的jpg文件，打不开，在浏览器打开下载的链接是空白的，请问该如何解决呢？

### ISSUE THREAD

**Issue by LaffeyLa** [HibiKier/zhenxun_bot#1142]
### 错误截图
![2022-10-17 17-09-48 的屏幕截图](https://user-images.githubusercontent.com/75292949/196149257-30a20617-5c25-44f6-acb6-50d31c5d1536.png)

### 日志截图
![2022-10-17 17-09-28 的屏幕截图](https://user-images.githubusercontent.com/75292949/196149354-bdc15f50-a845-4f76-bfab-3e85be4d85e7.png)

### 错误说明
![2022-10-17 17-08-46 的屏幕截图](https://user-images.githubusercontent.com/75292949/196149385-381d8cfc-35e3-4c84-8ba2-33fc56f058af.png)

发生了xx错误...

**Comment by yanluoli** [comment]
比如不用私聊上传图片，直接把图片放进文件夹里

**Comment by HibiKier** [comment]
反代re寄了

**Comment by LaffeyLa** [comment]
> 

欧克，我换了个反代，用自己梯子的全局代理解决了
