### ISSUE TITLE
 Uvicorn running on

### ISSUE THREAD

**Issue by NovNoah** [HibiKier/zhenxun_bot#1144]
### 错误截图

[img]
![9ZY$F)Y}GC_I74UH5N7Q$S6](https://user-images.githubusercontent.com/62124595/196647227-deb281de-f722-4863-a1ed-7cd7569feb02.png)

### 日志截图

[img]

### 错误说明
在这之后就卡住了

**Comment by HibiKier** [comment]
开gocq

**Comment by NovNoah** [comment]
> 开gocq

好的谢谢，请问可以使用带网页端的那版gocq吗

**Comment by HibiKier** [comment]
可以
