### ISSUE TITLE
如何修改真寻保存的所有资源的路径？

### ISSUE THREAD

**Issue by zhong946555** [HibiKier/zhenxun_bot#1148]
请问一下各位大佬，要如何修改真寻保存的所有资源的路径？

**Comment by HibiKier** [comment]
configs/path_config

**Comment by zhong946555** [comment]
![image](https://user-images.githubusercontent.com/61000018/197344522-094d12ae-a5fa-4355-9a60-5cfb3c2fb2e9.png)
我想存放在/data/zx_data这个文件夹中，这个需要怎么写，直接改有报错
