### ISSUE TITLE
pix更换反代后已挂代理但下载超时

### ISSUE THREAD

**Issue by gaosumaodan** [HibiKier/zhenxun_bot#1149]
**go-cqhttp版本：v1.0.0-rc3

真寻版本：0.1.6.4

日志截图**
![image](https://user-images.githubusercontent.com/105725248/196860083-7182ab9f-63e7-4e2e-8043-c76cbba0f36f.png)
![image](https://user-images.githubusercontent.com/105725248/196860098-cfeaf71c-92f9-4aa8-bd74-bfdfc4745918.png)

**Comment by GHSSeBi** [comment]
挂了代理直连就行了，不用反代

**Comment by LaffeyLa** [comment]
要在配置里修改本地全局代理

**Comment by gaosumaodan** [comment]
> 

是加速器里的配置吗，如果是的话我是已经改过的了

**Comment by gaosumaodan** [comment]
> 要在配置里修改本地全局代理

是加速器里的配置吗，如果是的话我已经修改过了

**Comment by LaffeyLa** [comment]
![2022-10-21 16-09-26 的屏幕截图](https://user-images.githubusercontent.com/75292949/197146371-2bbb2a15-e054-430c-ab12-432df8461338.png)
configs/config.py
该了之后要执行pip install httpx[socks]，然后重启机器人

**Comment by gaosumaodan** [comment]
> ![2022-10-21 16-09-26 的屏幕截图](https://user-images.githubusercontent.com/75292949/197146371-2bbb2a15-e054-430c-ab12-432df8461338.png) configs/config.py 改了之后要执行pip install httpx[socks]，然后重启机器人

哦哦，谢谢老哥，我去试试
