### ISSUE TITLE
[功能要望]github url信息缩略图中的项目简介的unicode表情支持

### ISSUE THREAD

**Issue by steve02081504** [HibiKier/zhenxun_bot#1150]
![图片](https://user-images.githubusercontent.com/31927825/197002499-3d5ad1cd-3afe-491f-91b4-ba6d4015418b.png)

**Comment by qingba** [comment]
这个是第三方插件吧，你去那边提个issues吧

**Comment by steve02081504** [comment]
> 这个是第三方插件吧，你去那边提个issues吧

大佬能指个路吗不是咱的bot咱不知道是哪个repo

**Comment by steve02081504** [comment]
> > 这个是第三方插件吧，你去那边提个issues吧
> 
> 大佬能指个路吗不是咱的bot咱不知道是哪个repo

当我没说，谢谢佬
