### ISSUE TITLE
B站订阅up和订阅主播id混淆

### ISSUE THREAD

**Issue by PrayerT** [HibiKier/zhenxun_bot#1158]
### 错误截图
![image](https://user-images.githubusercontent.com/63850261/198543901-50c53212-1e72-48ea-b12f-ec292e6773c1.png)
![image](https://user-images.githubusercontent.com/63850261/198544006-d9623700-8947-4b5b-80db-56b7adb27f96.png)

### 错误说明

如图，添加订阅主播的直播间号为226919，反馈的订阅name为用户id是226919的名称，并且查阅订阅之后显示的是订阅up的结果，导致226919的直播间开播没有播报

**Comment by HibiKier** [comment]
最新的代码？

**Comment by PrayerT** [comment]
> 最新的代码？

是的
![image](https://user-images.githubusercontent.com/63850261/198871807-42cc189a-ed28-4dce-aedb-01d937dda443.png)

**Comment by PrayerT** [comment]
> 没有推送的问题，大概率是因为B站的下播状态有两种，分别对应 0 2，可以尝试一下把 plugins/bilibili_sub/data_source.py 文件中的 233 行改一下试试 ![image](https://user-images.githubusercontent.com/75608102/198930011-a6e1b4f8-80ca-4181-bc23-f72ad6360b4d.png)

不只是没有推送，添加订阅主播之后查看订阅的直播间，列表里都没有出现该直播间

**Comment by DDS-DS** [comment]
> > 因为没有的下一下的，大是模特播播状态有B站问题，分别是0 2，行改把plugin/bili_sub/data_source/bili233![图片](https://user-images.githubusercontent.com/75608102/198930011-a6e1b4f8-80ca-4181-bc23-f72ad6360b4d.png)
> 
> 不只是没有里，都添加了主播之后订阅的直播间，列表中没有出现该直播间 并且列表中位主播的直播间提醒是正常可用的

删除后，重新订阅也还是一样吗？

**Comment by PrayerT** [comment]
> > > 因为没有的下一下的，大是模特播播状态有B站问题，分别是0 2，行改把plugin/bili_sub/data_source/bili233![图片](https://user-images.githubusercontent.com/75608102/198930011-a6e1b4f8-80ca-4181-bc23-f72ad6360b4d.png)
> > 
> > 
> > 不只是没有里，都添加了主播之后订阅的直播间，列表中没有出现该直播间 并且列表中位主播的直播间提醒是正常可用的
> 
> 删除后，重新订阅也还是一样吗？

是的，尝试过不止一次了，226919这个id可以复现

**Comment by DDS-DS** [comment]
> > > > 因为没有的下一下的，大是模特播播状态有B站问题，分别是0 2，行改把plugin/bili_sub/data_source/bili233![图片](https://user-images.githubusercontent.com/75608102/198930011-a6e1b4f8-80ca-4181-bc23-f72ad6360b4d.png)
> > > 
> > > 
> > > 不只是没有里，都添加了主播之后订阅的直播间，列表中没有出现该直播间 并且列表中位主播的直播间提醒是正常可用的
> > 
> > 
> > 删除后，重新订阅也还是一样吗？
> 
> 是的，尝试过不止一次了，226919这个直播间id可以复现

应该知道什么问题了，我这边看下怎么处理

**Comment by PrayerT** [comment]
最新patch合入之后问题解决，感谢
