### ISSUE TITLE
提示无权限

### ISSUE THREAD

**Issue by Plutoeat** [HibiKier/zhenxun_bot#1159]
就是我群里，有人用色图功能，来1张色图，但是他提示我无权限，虽然我也没法用，但是那只是出问题了，但是现在群员直接没权限，我授予9级权限也不行请问要怎么做才能让群员也有使用权限

**Comment by HibiKier** [comment]
修改群权限

**Comment by Plutoeat** [comment]
ok，谢谢了，已解决！！！
