### ISSUE TITLE
插件加入过多导致的真寻帮助图片错误

### ISSUE THREAD

**Issue by Glospred** [HibiKier/zhenxun_bot#1161]
### 错误截图

![5d8afd17bb6a1292](https://user-images.githubusercontent.com/103896688/198873985-a3320678-fea9-41cc-a839-c7b57003afe8.png)

### 错误说明

插件加入太多出现问题如图，群内小游戏栏压在了马娘工具箱栏上面

**Comment by HibiKier** [comment]
在修了在修了

**Comment by HibiKier** [comment]
49e38862afadeae779534bacc32f78be0fd5775f
