### ISSUE TITLE
获取信息失败...错误码: -401, 信息: 非法访问

### ISSUE THREAD

**Issue by lr616731587** [HibiKier/zhenxun_bot#1164]
### 错误截图

11-03 18:23:38 [INFO] plugins | Id：34086425 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:24:08 [INFO] plugins | Id：25139730 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:25:38 [INFO] plugins | Id：34086425 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:26:08 [INFO] plugins | Id：5311503 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:28:38 [INFO] plugins | Id：20621262 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:29:08 [INFO] plugins | Id：5311503 获取信息失败...错误码: -401, 信息: 非法访问

### 日志截图

11-03 18:23:38 [INFO] plugins | Id：34086425 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:24:08 [INFO] plugins | Id：25139730 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:25:38 [INFO] plugins | Id：34086425 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:26:08 [INFO] plugins | Id：5311503 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:28:38 [INFO] plugins | Id：20621262 获取信息失败...错误码: -401, 信息: 非法访问
11-03 18:29:08 [INFO] plugins | Id：5311503 获取信息失败...错误码: -401, 信息: 非法访问

### 错误说明

不知道什么原因，之前用的好好的，突然出现这个错误

**Comment by yanluoli** [comment]
升级bilireq 到v0.2.3+看看
