### ISSUE TITLE
功能期望：金币系统可调节

### ISSUE THREAD

**Issue by Plutoeat** [HibiKier/zhenxun_bot#1165]
成员之间交易非常不方便，都是通过塞红包，别人一不小心就给开了，请问可以增加个群员之间相互转账或者管理员直接调节金币吗

**Comment by 1411484730** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/1135#issuecomment-1279101603

**Comment by chuzouX** [comment]
金币调节可以直接修改数据库，应该能使用SQL语法和指令直接修改

**Comment by chuzouX** [comment]
我是用的postgresql远程数据库，直接用工具就可以直接修改数据

**Comment by SanaeMio** [comment]
我用的zhenxun_plugins_TZseries里的TZbank模块，外挂了一个银行系统，感觉还不错。

**Comment by Plutoeat** [comment]
谢谢大家了，我也是整了个银行插件，不过劫财和银行手续费总感觉金币跑得太快了
