### ISSUE TITLE
无法拉群

### ISSUE THREAD

**Issue by Nthing734** [HibiKier/zhenxun_bot#1166]
### 错误截图

![IMG_20221106_205453](https://user-images.githubusercontent.com/109641391/200171973-a2bf7c19-f372-4bb5-80cb-c56041ccad88.jpg)

### 日志截图

11-06 20:40:33 [SUCCESS] nonebot | ONEBOT V11 2627602709 | [message.private.friend]: Message -1584589807 from 3217962725 "[CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="128" templateID="12345" action="native" brief="&#91;链接&#93;邀请你加入群聊" sourceMsgId="0" url=""><item layout="2"><picture cover=""/><title>邀请你加入群聊</title><summary /></item><data groupcode="1012602785" groupname="脑瘫二次元" msgseq="1667738433818652" msgtype="2"/></msg>,resid=]"

11-06 20:40:33 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>

11-06 20:40:33 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
11-06 20:40:33 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
11-06 20:40:33 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
11-06 20:40:33 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
11-06 20:40:33 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
11-06 20:40:33 [INFO] nonebot | Event will be handled by <Matcher from plugins.ai, type=message, priority=998, temp=False>
11-06 20:40:33 [INFO] nonebot | Matcher <Matcher from plugins.ai, type=message, priority=998, temp=False> running complete
11-06 20:40:34 [INFO] nonebot | Matcher <Matcher from basic_plugins.invite_manager, type=request, priority=5, temp=False> running complete

更新后无法拉群

**Comment by A-Whisper** [comment]
是否已经添加了群认证，如果没有要加一下，使用群认证的方法在文档里面有

**Comment by Nthing734** [comment]
> 是否已经添加了群认证，如果没有要加一下，使用群认证的方法在文档里面有

添加了，但是没有用

**Comment by HibiKier** [comment]
群认证是防止小群的无需同意直接拉的，也不会直接拒绝的，而是进入后再退出
