### ISSUE TITLE
功能咨询

### ISSUE THREAD

**Issue by Plutoeat** [HibiKier/zhenxun_bot#1169]
朋友有个QQ频道，希望能将机器人拉进频道，go-cqhttp 我记得已经适配了频道，请问真寻支持吗？

**Comment by Plutoeat** [comment]
我还想问下他的好感度有什么实质性的作用吗，比方说词库相对温和，和你交流更和气

**Comment by HibiKier** [comment]
频道要nb补丁的吧，好感度目前就开箱和色图有用到吧

**Comment by Plutoeat** [comment]
我了解了，谢谢
