### ISSUE TITLE
csgo开箱不能更新价格信息

### ISSUE THREAD

**Issue by lihaojie87** [HibiKier/zhenxun_bot#117]
尝试添加了cookie中session里的参数
但是发生报错
![image](https://user-images.githubusercontent.com/50283726/154036392-e3b0fa03-d4c8-4ebb-be54-34e970fae67a.png)
应该是cookie的设置问题，cookie应该怎么填写呢？

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/154485855-af7d5af1-118b-4325-a617-c753af832d45.png)
session后面的值
