### ISSUE TITLE
额外出现sql日志

### ISSUE THREAD

**Issue by MobiusT** [HibiKier/zhenxun_bot#1172]
### 错误截图
无
### 日志截图
![image](https://user-images.githubusercontent.com/62053271/201348967-8af5e60c-759c-42d4-ac27-52c8f7b71ef5.png)
### 错误说明
日志中出现两种日志格式，上方的红框是之前常见的日志，属于正常
下面一个多了个日期的日志看着像是数据库的sql日志，以前没出现过，在某次重启时突然出现

**Comment by HibiKier** [comment]
日志是查询某人是否被ban，不过应该没有打印sql的地方吧

**Comment by MobiusT** [comment]
![image](https://user-images.githubusercontent.com/62053271/201486356-bb2eb141-db5b-4789-9ccc-18d525a62de1.png)
不只是日志被ban 目前看是所有的sql都会被日志输出（有自己加的github订阅，也有原本自带的b站订阅，但是我只动过另外一个日志路径nonebot.load_plugins("zhenxun_extensive_plugin_mobius")，没有对除bot.py外的代码做变更），但是找不到是从哪里输出出来的 从日志格式看也不是nb的格式，就想不通怎么出来的 而且刷的太多了

**Comment by MobiusT** [comment]
[mobius@mobius nonebot_plugin_petpet]$ shell
root@mobius:/app# pip list
Package                    Version
-------------------------- -----------
aiofiles                   0.8.0
aiohttp                    3.7.4.post0
anyio                      3.6.1
appdirs                    1.4.4
APScheduler                3.9.1
arrow                      1.2.3
async-timeout              3.0.1
asyncpg                    0.26.0
attrs                      22.1.0
audioread                  3.0.0
bbcode                     1.1.0
beautifulsoup4             4.9.3
bilireq                    0.2.3.post0
binaryornot                0.4.4
black                      22.10.0
certifi                    2022.9.24
cffi                       1.15.1
chardet                    4.0.0
charset-normalizer         2.1.1
click                      8.1.3
cn2an                      0.5.17
colorama                   0.4.6
commonmark                 0.9.1
contourpy                  1.0.5
cookiecutter               1.7.3
cycler                     0.11.0
dateparser                 1.1.1
decorator                  5.1.1
ecdsa                      0.18.0
emoji                      1.7.0
expandvars                 0.9.0
fastapi                    0.79.1
feedparser                 6.0.10
ffmpeg                     1.4
fonttools                  4.37.4
genshinhelper              2.1.3
gino                       1.0.1
greenlet                   1.1.3
grpcio                     1.49.1
h11                        0.12.0
httpcore                   0.15.0
httptools                  0.5.0
httpx                      0.23.0
idna                       3.4
ImageHash                  4.3.1
imageio                    2.22.3
importlib-metadata         5.0.0
inflect                    5.6.2
jaraco.context             4.1.2
jieba                      0.42.1
Jinja2                     3.1.2
jinja2-time                0.2.0
joblib                     1.2.0
kiwisolver                 1.4.4
langid                     1.1.6
librosa                    0.9.2
llvmlite                   0.38.1
loguru                     0.6.0
lxml                       4.6.5
Markdown                   3.4.1
MarkupSafe                 2.1.1
matplotlib                 3.6.1
mockingbirdforuse          0.2.3
more-itertools             9.0.0
msgpack                    1.0.4
multidict                  6.0.2
mypy-extensions            0.4.3
nb-cli                     0.6.7
nonebot-adapter-onebot     2.1.4
nonebot-plugin-apscheduler 0.2.0
nonebot-plugin-htmlrender  0.2.0.1
nonebot-plugin-imageutils  0.1.13.2
nonebot2                   2.0.0b5
numba                      0.55.2
numpy                      1.22.4
nvidia-cublas-cu11         11.10.3.66
nvidia-cuda-nvrtc-cu11     11.7.99
nvidia-cuda-runtime-cu11   11.7.99
nvidia-cudnn-cu11          8.5.0.96
opencv-python              4.6.0.66
opencv-python-headless     4.6.0.66
packaging                  21.3
pathspec                   0.10.1
Pillow                     9.1.1
pip                        22.3.1
platformdirs               2.5.2
playwright                 1.27.1
pooch                      1.6.0
poyo                       0.5.0
proces                     0.1.2
prompt-toolkit             3.0.32
protobuf                   4.21.7
psutil                     5.9.2
pyasn1                     0.4.8
pycparser                  2.21
pydantic                   1.9.2
pydub                      0.25.1
pyee                       8.1.0
pyfiglet                   0.8.post1
Pygments                   2.13.0
pygtrie                    2.5.0
pymdown-extensions         9.7
pyparsing                  3.0.9
pypinyin                   0.46.0
python-dateutil            2.8.2
python-dotenv              0.21.0
python-jose                3.3.0
python-markdown-math       0.8
python-multipart           0.0.5
python-slugify             6.1.2
pytz                       2022.4
pytz-deprecation-shim      0.1.0.post0
PyWavelets                 1.4.1
PyYAML                     5.4.1
regex                      2022.3.2
requests                   2.28.1
resampy                    0.4.2
retrying                   1.3.3
rfc3986                    1.5.0
rich                       12.6.0
rsa                        4.9
ruamel.yaml                0.17.21
ruamel.yaml.clib           0.2.6
scikit-learn               1.1.3
scipy                      1.9.2
setuptools                 65.5.0
setuptools-scm             7.0.5
sgmllib3k                  1.0.0
six                        1.16.0
sniffio                    1.3.0
soundfile                  0.11.0
soupsieve                  2.3.2.post1
SQLAlchemy                 1.3.24
sqlitedict                 2.0.0
starlette                  0.19.1
tencentcloud-sdk-python    3.0.770
text-unidecode             1.3
threadpoolctl              3.1.0
tomli                      2.0.1
tomlkit                    0.10.2
torch                      1.13.0
typing_extensions          4.4.0
tzdata                     2022.5
tzlocal                    4.2
ujson                      5.5.0
Unidecode                  1.3.6
urllib3                    1.26.12
uvicorn                    0.18.3
uvloop                     0.17.0
watchfiles                 0.17.0
wcwidth                    0.2.5
webrtcvad                  2.0.10
websockets                 10.3
wheel                      0.37.1
wolframalpha               5.0.0
wordcloud                  1.8.2.2
xmltodict                  0.13.0
yarl                       1.8.1
zhconv                     1.4.3
zipp                       3.10.0

**Comment by MobiusT** [comment]
![image](https://user-images.githubusercontent.com/62053271/201655024-fa95bd09-d30b-4817-afba-5e19d9412a7c.png)
看了日志第一次出现的地方，本来推测和uvicorn有关，尝试了

**Comment by HibiKier** [comment]
感觉是sqlalchemy提示的

**Comment by MobiusT** [comment]
> 感觉是sqlalchemy提示的

根据提示，尝试在bot.py中添加了以下内容

```
#关闭sql日志
logging.basicConfig()
logger = logging.getLogger('sqlalchemy')
logger.setLevel(logging.ERROR) 
```

经测试验证，确认sql日志不再输出，虽然全局搜索项目未发现打出日志的原因，过既然能关闭输出就没问题了！谢谢！
![mmexport1670317471100.png](https://user-images.githubusercontent.com/62053271/205868208-5b0733f8-1e49-4aae-bc15-b1e2b4cec27e.png)
