### ISSUE TITLE
请问如何修改好感度 金币之类的呢 

### ISSUE THREAD

**Issue by 1103859909** [HibiKier/zhenxun_bot#1174]

**Comment by HibiKier** [comment]
私聊真寻发送下面的命令
好感度：
exec UPDATE "sign_group_users" SET impression=(好感度) WHERE user_qq=(qq号) AND group_id=(群号)
金币:
exec UPDATE "bag_users" SET gold=(金币) WHERE user_qq=(qq号) AND group_id=(群号)

**Comment by 1103859909** [comment]
好的谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月13日(周日) 凌晨1:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HibiKier/zhenxun_bot] 请问如何修改好感度 金币之类的呢  (Issue #1174)




 
私聊真寻发送下面的命令
 好感度：
 exec UPDATE "sign_group_users" SET impression=(好感度) WHERE user_qq=(qq号) AND group_id=(群号)
 金币:
 exec UPDATE "bag_users" SET gold=(金币) WHERE user_qq=(qq号) AND group_id=(群号)
