### ISSUE TITLE
翻译除了英文其他好像都报错？

### ISSUE THREAD

**Issue by MandarinDuck231** [HibiKier/zhenxun_bot#1181]
### 错误截图
![image](https://user-images.githubusercontent.com/108500604/202895708-da065800-dae8-436c-87de-a6d43ada9fb3.png)

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by shinianj** [comment]
日志给一给哦

**Comment by HibiKier** [comment]
应该是api的问题

**Comment by NathanSummer** [comment]
> 日志给一给哦

![image](https://user-images.githubusercontent.com/88868171/213985486-e9e378de-0931-4fb9-bb64-a03ded071f4d.png)
日志是这样的，不过机器人没有给失败提示 （v0.1.6.6）

**Comment by HibiKier** [comment]
bdfdbbcaebc10cde2c3980a1227de6568c1e9187
