### ISSUE TITLE
更新0.1.6.5后安装依赖失败

### ISSUE THREAD

**Issue by yozorachan** [HibiKier/zhenxun_bot#1186]
### 错误截图

![image](https://user-images.githubusercontent.com/105808870/203469984-dbdf74d7-4950-433d-856b-17395ebcd13b.png)

### 错误说明

自动更新到0.1.6.5后想要重启更新一下pip和依赖，但是依赖安装失败

**Comment by RShock** [comment]
我update一下就没这个问题（但是之后所有插件全炸
