### ISSUE TITLE
Web UI获取数据失败

### ISSUE THREAD

**Issue by Apricot-feiya** [HibiKier/zhenxun_bot#1187]
### Web UI版本：0.1.0.4

错误代码
WEB_UI GET /webui/plugins model：nickname 发生错误 <class 'TypeError'>：'Plugin' object does not support item assignment

错误截图
![qq_pic_merged_1669179287256](https://user-images.githubusercontent.com/58616907/203471670-d2a91680-0851-4dad-b5b6-9fb4a9374da9.jpg)
![V51E5OKXIWU_H9QHIVA36)D](https://user-images.githubusercontent.com/58616907/203471788-d49670e8-522a-4e00-a43b-a20afebe7a85.png)

**Comment by HibiKier** [comment]
d97542a3fdde13d5478778fd6ba446c54f0915cb
