### ISSUE TITLE
纯小白，请问一下这是什么情况

### ISSUE THREAD

**Issue by xiancen** [HibiKier/zhenxun_bot#1189]
### 错误截图
[img]
![Screenshot_20221123_164157](https://user-images.githubusercontent.com/118879324/203509750-8ecdfc1a-94aa-4500-81ab-5a93d813761e.jpg)

### 日志截图

[img]

![K$2VR16K}9HV EHX17RWT M](https://user-images.githubusercontent.com/118879324/203510545-124c988b-e71a-41e9-87d2-1d7ea29b5889.png)
![FFB@YR4~~JR_DDZ{YG~49GR](https://user-images.githubusercontent.com/118879324/203510551-1ec58547-313d-4630-b713-01154052134e.png)

### 错误说明

帮助指令错误

**Comment by molanp** [comment]
检查ai插件，尝试重新克隆并覆盖ai插件（路径plugins/ai）

**Comment by yajiwa** [comment]
试试在群发醒来
