### ISSUE TITLE
好感度总排行获取失败

### ISSUE THREAD

**Issue by molanp** [HibiKier/zhenxun_bot#1190]
### 日志截图

![Screenshot_2022_1124_073857](https://user-images.githubusercontent.com/104612722/203664666-24e4940e-bb4c-41ba-ae5c-28ab8096f1b4.png)
![Screenshot_2022_1124_073913](https://user-images.githubusercontent.com/104612722/203664717-5c006eb6-25f2-41bb-8ecc-01e90b357bcb.png)

### 错误截图

![6543dc874537e7b1](https://user-images.githubusercontent.com/104612722/203664817-b4fb2a72-08f9-40fa-90f6-304b42c9b5c5.jpg)

### 错误说明

好感度总排行无法获取，无应答无反馈

**Comment by HibiKier** [comment]
QQ头像下载失败了，检查网络
