### ISSUE TITLE
管理员命令无法使用？

### ISSUE THREAD

**Issue by DeadBoy2537** [HibiKier/zhenxun_bot#1191]
### 错误截图

![-7cccb79df668538b](https://user-images.githubusercontent.com/87133530/203665431-ac20dc28-57e2-4328-a5c0-d52b710fd5b2.png)

### 日志截图

![Screenshot_20221124-075059](https://user-images.githubusercontent.com/87133530/203665466-be8f363d-5c45-4fb0-bc71-482ab4f8eab6.png)

### 错误说明

（已设置超级用户但没有管理员功能权限）
发送“超级用户帮助”有反应，但管理员指令没有（在群里也是）

**Comment by HibiKier** [comment]
？管理员是群管理员和超级用户才能触发，遇事不决前面加at
