### ISSUE TITLE
小白提问:功能调用统计无法使用

### ISSUE THREAD

**Issue by bubble-w8** [HibiKier/zhenxun_bot#1192]
### 错误截图

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/107778611/203676814-f7347e06-1c8c-49f1-8df1-8826478a2677.png">

尝试过重启与重载配置，私聊仍可触发“请在群聊使用”的回复

**Comment by HibiKier** [comment]
把data/configs/plugin2setting删了重启试试

**Comment by HibiKier** [comment]
更新代码试试
