### ISSUE TITLE
关于刷屏禁言

### ISSUE THREAD

**Issue by Plutoeat** [HibiKier/zhenxun_bot#1193]
真寻刷屏禁言似乎会与复读功能冲突，复读打断一下他就没法识别了，还有刷屏时换一个图像他就无法识别，禁言也无法禁言管理，他目前是群主，权限应该说是够的

**Comment by Plutoeat** [comment]
更新能禁言管理，这个是我的问题

**Comment by HibiKier** [comment]
提高撤回权限

**Comment by Plutoeat** [comment]
我是用的一键部署，他会给我返回一长串插件加载失败，但是插件又都能使用，但webui又无法获取，我试着重启真寻，但是重启后他使用的是其他端口而非8080，我在配置文件中寻找可以固定端口的配置却没有找到，我又得调整go-cqhttp的配置和服务器端口开放，我想问下哪里可以固定8080端口

**Comment by HibiKier** [comment]
更新代码

**Comment by Plutoeat** [comment]
> 我是用的一键部署，他会给我返回一长串插件加载失败，但是插件又都能使用，但webui又无法获取，我试着重启真寻，但是重启后他使用的是其他端口而非8080，我在配置文件中寻找可以固定端口的配置却没有找到，我又得调整go-cqhttp的配置和服务器端口开放，我想问下哪里可以固定8080端口

我所描述的和#1184一样的状况，功能照常使用，他给我发消息插件加载失败倒也没啥，关键没用用webui调整配置

**Comment by Plutoeat** [comment]
> 提高撤回权限

关于撤回权限，我在web-ui中没找到快捷设置，在data/configs和configs文件夹中的配置文件也翻了，是否需要修改源码才能提高撤回权限

**Comment by HibiKier** [comment]
好吧，撤回的权限没有开放在config.yaml里，你可以在plugins/withdraw.py中修改
