### ISSUE TITLE
b站订阅功能出错httpx.ConnectTimeout及ValueError: 'www.bilibili.com' does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by MobiusT** [HibiKier/zhenxun_bot#1194]
### 日志截图

![image](https://user-images.githubusercontent.com/62053271/203788370-04d6556a-a062-4663-98fe-4116d50e921d.png)
![image](https://user-images.githubusercontent.com/62053271/203788422-44795d25-40f8-422d-9287-633e2fb0acf1.png)
![image](https://user-images.githubusercontent.com/62053271/203788451-af0dbd89-5254-44da-ba9e-968458f37dbf.png)
![image](https://user-images.githubusercontent.com/62053271/203788478-1c4b9bc0-29b2-4bbd-8d8e-164806fdbf24.png)

### 错误说明
本来升级到0.1.5.6是正常的，后面服务器进行了一次重启，重启完就一直会报这个错，但是看dns解析是正常的，尝试过升级bilireq，仍然无效，其他功能均正常
![image](https://user-images.githubusercontent.com/62053271/203788741-1958dc10-372b-4acd-8acb-6b74e0abd6d7.png)
![image](https://user-images.githubusercontent.com/62053271/203788910-a075fc26-bb6e-407c-a636-b63f97596ad4.png)

**Comment by HibiKier** [comment]
网络问题吧？

**Comment by MobiusT** [comment]
现在还一直在报，但是前几天开始突然又能推送了，现在一边报错一边推送....感觉挺莫名其妙的 只能先这样了 不知道有没有类似调整超时时间之类的方法
