### ISSUE TITLE
读取到notice.essence类型群精华消息时无法正确处理

### ISSUE THREAD

**Issue by wse320** [HibiKier/zhenxun_bot#1197]
### 错误截图

[img]

### 日志截图

[img]

### 错误说明
在精选群消息时发现日志报错如下
![image](https://user-images.githubusercontent.com/27719438/204011405-f3bae9ef-9a21-4a0b-8a6d-34010fabe449.png)
后根据错误提示注释了
/basic_plugins/hooks/_utils.py文件中第456行的语句，但是依然提示/basic_plugins/hooks/ban_hook.py文件中有错误
![IG N9{@@8CSFXX2IUO5RVMD](https://user-images.githubusercontent.com/27719438/204010576-7c2630ce-bd91-4413-8b52-81a9a6587e5f.png)
不影响整体运行，但是会导致本条消息没有被记入数据库中

**Comment by HibiKier** [comment]
994484f3b0ad5ca302b8b3d9a0c47c48b15549d3
