### ISSUE TITLE
安装第三方插件后，帮助图片显示不全

### ISSUE THREAD

**Issue by DeadBoy2537** [HibiKier/zhenxun_bot#1198]
### 错误截图

![-6fbc5ef5a651ed4c](https://user-images.githubusercontent.com/87133530/204070405-27386839-05dc-4aa7-982a-227f4d4c429b.png)

### 日志截图

![IMG20221126111841](https://user-images.githubusercontent.com/87133530/204070527-32e7040a-85cd-4687-8086-e66fa092d908.jpg)

### 错误说明

安装第三方插件后，帮助图片部分内容显示不全
已安装插件:
![Screenshot_20221126-112605](https://user-images.githubusercontent.com/87133530/204070746-d1938d3f-5989-442a-981f-89a39c20d056.png)

**Comment by HibiKier** [comment]
f496ce48617e0ca69c25f938b0069d873222eecb 不好复现，试试新的
