### ISSUE TITLE
关于安装自定义插件运行时提示No module named 'requests'

### ISSUE THREAD

**Issue by PPPPParas** [HibiKier/zhenxun_bot#1199]
### 错误截图

![image](https://user-images.githubusercontent.com/91717560/204105224-6e51de79-6527-4bad-82fb-e2dd286a031d.png)

### 错误说明

安装已适配真寻的
[[吃什么]](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/tree/master/what2eat)
[[60s读世界]](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/tree/master/read_60s)
时，启动bot遇到了图示的问题。

尝试使用pip命令安装requests却提示Requirement already satisfied
![image](https://user-images.githubusercontent.com/91717560/204105555-102d18f6-33ba-47c8-8d7c-41ba2d7e7cc7.png)
如图。

请各位大佬帮忙看看...纯小白一枚 先感谢各位大佬了orz

**Comment by OVOU4** [comment]
你需要另外安装requests模块，此外你先运行python -m pip install --upgrade pip升级pip版本才能安装

**Comment by PPPPParas** [comment]
> 你需要另外安装requests模块，此外你先运行python -m pip install --upgrade pip升级pip版本才能安装

感谢大佬回复
用命令升级pip版本后尝试卸载了reauests模块 重新安装
![image](https://user-images.githubusercontent.com/91717560/204780935-02b2b548-30a4-4588-acdb-6b299dedcee0.png)
![image](https://user-images.githubusercontent.com/91717560/204781152-8efd1462-1cf5-4977-8a80-89567c50b2ed.png)
![image](https://user-images.githubusercontent.com/91717560/204781294-530a0b64-adf3-490d-934d-61a5eaf75e21.png)
之后依然遇到了相同的问题
![image](https://user-images.githubusercontent.com/91717560/204781614-3631d161-25ea-4feb-8f35-b0004b1ba241.png)

根据红字错误描述我卸载并尝试安装了requests-toolbelt0.9.1之后重新安装requests
![image](https://user-images.githubusercontent.com/91717560/204784238-cc25d085-b5a2-456a-8b2d-019d8c2346d1.png)
然而重启bot问题依然存在
![image](https://user-images.githubusercontent.com/91717560/204784313-26a3fced-58ca-46c1-aa92-137a7bc0ef2a.png)

请问另外安装requests模块是指其他的安装方法吗

**Comment by OVOU4** [comment]
你先输入poetry shell进入虚拟环境，再执行pip install requests，直接执行这个命令只是在实体安装这个模块，并没有在虚拟环境中安装

**Comment by OVOU4** [comment]
可以的话你在原项目开一个issue，要求把所有使用requests换成httpx模块，httpx这个是在真寻的依赖里本身就安装有的

**Comment by PPPPParas** [comment]
> 你先输入poetry shell进入虚拟环境，再执行pip install requests，直接执行这个命令只是在实体安装这个模块，并没有在虚拟环境中安装

感谢大佬！问题解决了
我搜索了好多关于这个问题的解答都没有提到虚拟环境这个问题 可能是太基础了......

另外用到requests模块的插件意外的多，这也算一下解决了一大堆问题....

感谢
