### ISSUE TITLE
管理权限读取失败

### ISSUE THREAD

**Issue by nymanyim** [HibiKier/zhenxun_bot#12]
正常配置后我的权限显示为0，群主管理员也是0

**Comment by HibiKier** [comment]
对的，nonebot不会检测bot本身进群事件，下个版本添加权限更新的定时任务，目前等待半夜自动更新 或 者手动命令 @bot添加权限@自己 [权限等级](最高9)，给自己权限，然后使用命令 ‘更新群组成员信息’

**Comment by nymanyim** [comment]
好嘞
