### ISSUE TITLE
二次元词库分享

### ISSUE THREAD

**Issue by amemi212** [HibiKier/zhenxun_bot#1201]
https://wwp.lanzoum.com/b041h44vc
密码:fdla

**Comment by DeadBoy2537** [comment]
话说可以导入进数据库吗)

**Comment by amemi212** [comment]
可以啊，自己处理一下

**Comment by amemi212** [comment]
很简单，把文件后缀改成txt，就知道数据是什么格式存储的了，然后切分就行了

**Comment by OVOU4** [comment]
这个语料挺有意思，有点想训练一个GPT-2模型出来

**Comment by amemi212** [comment]
已更新词库版本

**Comment by Huang1932539** [comment]
这个词库放到哪里啊

**Comment by Huang1932539** [comment]
> https://wwp.lanzoum.com/b041h44vc 密码:fdla

这个放到哪里啊
