### ISSUE TITLE
 docker安装显示下载原神数据错误

### ISSUE THREAD

**Issue by abigmiu** [HibiKier/zhenxun_bot#1202]
### 错误截图
![image](https://user-images.githubusercontent.com/43983920/204773540-70fc80f8-d318-4ed6-8113-f241f2a87d7d.png)

[img]

### 日志截图

[img]

### 错误说明

docker安装显示下载原神数据错误

**Comment by HibiKier** [comment]
？你这一点日志都没有是吗

**Comment by HibiKier** [comment]
艹，是我图片没加载出来，你这是单纯的超时了

**Comment by abigmiu** [comment]
> 艹，是我图片没加载出来，你这是单纯的超时了

下载源是哪里。 国内还是国外。 我的服务器是成都的腾讯云。如果下载源是国内的话应当不会超时

**Comment by HibiKier** [comment]
国内，基本是bwiki

**Comment by HibiKier** [comment]
和米游社
