### ISSUE TITLE
全局词库无法删除词条

### ISSUE THREAD

**Issue by DeadBoy2537** [HibiKier/zhenxun_bot#1203]
### 错误截图

![7d7652fc7aa8960a](https://user-images.githubusercontent.com/87133530/204789080-7c8961ff-021e-46dc-b4d5-cd9aa9a7c7c1.png)

### 日志截图

全局词库（删除）
![IMG20221130194628](https://user-images.githubusercontent.com/87133530/204789156-86ce3b7e-ed9b-4e99-88e4-fd9cfd965554.jpg)
私聊词库（添加）
![IMG20221130195406](https://user-images.githubusercontent.com/87133530/204789729-becdd4c9-725d-4366-a3e0-d11fd4ddebc5.jpg)

### 错误说明

全局词库无法删除词条，必须到数据库里面删除
私聊词库可以添加/删除但会报错（影响不大）

另外有一个疑问，如何建立一个必须叫了机器人名字或者at机器人才会回答的词条（比如说现在有一个词条叫b，只有发“真寻b”或者“@真寻 b”才会回答这个词条的内容）

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/206859533-7a35c198-3ca4-4387-98af-a7b0b6d8a8e2.png)

**Comment by HibiKier** [comment]
b59699dabe5b98b5ff10752fb8a57823a77caa05
