### ISSUE TITLE
webui报错

### ISSUE THREAD

**Issue by ayakasuki** [HibiKier/zhenxun_bot#1204]
### 错误截图
![image](https://user-images.githubusercontent.com/20859971/205682446-0d7ad65b-0194-4ed4-a025-6ecdd08b2416.png)

[img]

### 日志截图
![image](https://user-images.githubusercontent.com/20859971/205682481-4d66d652-d7ac-4b98-826e-e5b7bdb3a4eb.png)

[img]

### 错误说明

webui一打开 就如图所示，主要是关闭网页以后，日志一样刷屏这个错误，导致ai也失效，重启后不打开webui才不会触发

**Comment by HibiKier** [comment]
更新代码
