### ISSUE TITLE
能否加入可以接入ChatGPT的功能，目前非常需要

### ISSUE THREAD

**Issue by Yumemi8** [HibiKier/zhenxun_bot#1205]
我尝试加入第三方作者的ChatGPT插件，但是似乎并不兼容，并且本人学识尚浅没有python开发经验（我使用的插件github链接：https://github.com/A-kirami/nonebot-plugin-chatgpt     ），只能盼望真寻bot的作者们更新功能了。
![image](https://user-images.githubusercontent.com/71859504/206354052-2538c479-49e1-48aa-bcec-2bcc87fa8250.png)

**Comment by SanaeMio** [comment]
缺少依赖，所以需要额外安装一下依赖
如果是在虚拟环境里可以尝试：poetry add OpenAIAuth
如果不基于虚拟环境：pip3 install OpenAIAuth

**Comment by Yumemi8** [comment]
> 缺少依赖，所以需要额外安装一下依赖 如果是在虚拟环境里可以尝试：poetry add OpenAIAuth 如果不基于虚拟环境：pip3 install OpenAIAuth

感谢回复。我已经成功载入了此插件，ChatGpt插件说明是 .env 文件中写入配置参数就行，但我不知道什么原因，配置参数它似乎并不起作用，依然无法触发ChatGpt的功能，

**Comment by SanaeMio** [comment]
> > 缺少依赖，所以需要额外安装一下依赖 如果是在虚拟环境里可以尝试：poetry add OpenAIAuth 如果不基于虚拟环境：pip3 install OpenAIAuth
> 
> 感谢回复。我已经成功载入了此插件，ChatGpt插件说明是 .env 文件中写入配置参数就行，但我不知道什么原因，配置参数它似乎并不起作用，依然无法触发ChatGpt的功能，

你可以在这个插件的config里配置CHATGPT_COMMAND作为自定义触发命令，比如“提问”，然后在群里发“提问 我是谁”等等，应该就会相应了，注意CHATGPT_TO_ME的默认值是True，需要at真寻

**Comment by Yumemi8** [comment]
> 

插件可以看到是载入成功了的 
![image](https://user-images.githubusercontent.com/71859504/206658888-ff19a3d3-38c5-4a6a-994d-ddc1a9fc7d82.png)

我在config里配置了参数：
<img width="277" alt="图片1" src="https://user-images.githubusercontent.com/71859504/206659516-8ffad344-0ee5-4079-9ae4-de61e3640bcc.png">
但我无论说什么bot都是调用ALAPI来回答我，加上“提问”关键词也不行，我没有头绪是哪里不对
并且我看到作者是有判断token是否为空，但是在我初次导入没有配置参数的时候它也没有提醒我token为空，我在怀疑插件到底有没有在运行
![image](https://user-images.githubusercontent.com/71859504/206661941-bac4c4af-bf0a-4f79-81b8-bc6901c41f98.png)
我感觉插件没在运行，而且我也不知道原因

**Comment by SanaeMio** [comment]
emmm 我个人是按照真寻插件规范加上了一些属性到这个里面（比如插件名之类的），另外我在插件的config里设置了代理，目前使用正常。（可以看看真寻的日志，有没有打印这条消息会被chartGPT处理之类的来判断有没有运行起来）

**Comment by Yumemi8** [comment]
> emmm 我个人是按照真寻插件规范加上了一些属性到这个里面（比如插件名之类的），另外我在插件的config里设置了代理，目前使用正常。（可以看看真寻的日志，有没有打印这条消息会被chartGPT处理之类的来判断有没有运行起来）

算了 我放弃了，折腾一个星期了，累了，不过还是感谢大佬解答

**Comment by EightEggs** [comment]
可以看一看这个 https://github.com/acheong08/EdgeGPT

**Comment by Huang1932539** [comment]
> 可以看一看这个 https://github.com/acheong08/EdgeGPT

这个按照他的帮助页面一步一步操作下来就行了吗？
