### ISSUE TITLE
HTML帮助中的浅色字和横线字似乎反了

### ISSUE THREAD

**Issue by LambdaYH** [HibiKier/zhenxun_bot#1206]
### 错误截图

[img]

### 日志截图

[img]

### 错误说明
在
https://github.com/HibiKier/zhenxun_bot/blob/ab8e87899c08dbaa5af610b551370f04bc0eed10/basic_plugins/help/_utils.py#L183-L189
中被群管理禁用为`sta=1`，被超级用户关闭为`sta=2`
对应到如下几行中为**被群管理禁用的是`横线字`，被超级用户关闭的是`浅色字`**
https://github.com/HibiKier/zhenxun_bot/blob/ab8e87899c08dbaa5af610b551370f04bc0eed10/resources/template/menu/zhenxun_menu.html#L35-L49
与https://github.com/HibiKier/zhenxun_bot/blob/ab8e87899c08dbaa5af610b551370f04bc0eed10/resources/template/menu/zhenxun_menu.html#L17
矛盾

**Comment by HibiKier** [comment]
b3871d550c0ecec9bdb2c76e012249f909427e49

**Comment by LambdaYH** [comment]
好像...没变化

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/207369312-1c89a46a-76dc-4dff-874c-c7927f1fea50.png)
文字改了

**Comment by LambdaYH** [comment]
https://github.com/HibiKier/zhenxun_bot/commit/b9d08855d013cdaaa006d968115421acc0d57f7d
这个commit里面新旧两行好像是一样的
![image](https://user-images.githubusercontent.com/13503375/207371126-dab4d49c-e5f5-4b3a-838d-cde08fc12089.png)
![image](https://user-images.githubusercontent.com/13503375/207371181-3207104e-27fe-443a-aaec-085685c3edac.png)
