### ISSUE TITLE
碧蓝航线抽卡报错（下面是报错）

### ISSUE THREAD

**Issue by TKINGNAMe** [HibiKier/zhenxun_bot#1213]
12-14 18:27:53 [WARNING] draw_card | Traceback (most recent call last):
  File "/data/zhenxun_bot-main/plugins/draw_card/__init__.py", line 172, in handler
    res = await game.handle.draw(num, pool_name=pool_name, user_id=event.user_id)
  File "/data/zhenxun_bot-main/plugins/draw_card/handles/azur_handle.py", line 95, in draw
    up_list = [x.name for x in self.UP_EVENT.up_char] if self.UP_EVENT.up_char else []
AttributeError: 'NoneType' object has no attribute 'up_char'

不是很懂python 但是大概应该是 没有引用到定义的那个class里面的变量

**Comment by HibiKier** [comment]
b25b9ca928597e38d4aabd6f5227991a80caf0d0 更新试试？

**Comment by TKINGNAMe** [comment]
这次更新完把抽卡功能砍了！？？

还是我搞错了什么地方


***@***.***
 
发件人： HibiKier
发送时间： 2022-12-24 00:20
收件人： HibiKier/zhenxun_bot
抄送： TKINGNAMe; Author
主题： Re: [HibiKier/zhenxun_bot] 碧蓝航线抽卡报错（下面是报错） (Issue #1213)
b25b9ca 更新试试？

**Comment by TKINGNAMe** [comment]
看了后台的日志，指令都被 ai 模块取走了，但是奇怪的是 真寻帮助里面的图片  也没有了抽卡这个功能




***@***.***
 
发件人： ***@***.***
发送时间： 2022-12-24 17:12
收件人： HibiKier/zhenxun_bot; HibiKier/zhenxun_bot
抄送： 1490783711; Author
主题： Re: Re: [HibiKier/zhenxun_bot] 碧蓝航线抽卡报错（下面是报错） (Issue #1213)

这次更新完把抽卡功能砍了！？？

还是我搞错了什么地方


***@***.***
 
发件人： HibiKier
发送时间： 2022-12-24 00:20
收件人： HibiKier/zhenxun_bot
抄送： TKINGNAMe; Author
主题： Re: [HibiKier/zhenxun_bot] 碧蓝航线抽卡报错（下面是报错） (Issue #1213)
b25b9ca 更新试试？

**Comment by HibiKier** [comment]
加载了，帮助中没显示出来
802f4df2ce8669b578218d977bbc60e757b7b481 已优化

**Comment by TKINGNAMe** [comment]
好像并不奏效，可能是因为我改动了一些地方（签到？改动了经验的获得数值） 还有关于bt种子那边的搜索网站，你代码中的网址失效了"http://www.eclzz.guru" 现在是这个，
关于鲁迅说也有有些报错，
我明天重新部署一个新的再试试

  File "/data/bot/zhenxun_bot/plugins/luxun/__init__.py", line 46, in handle_event
    content = state["content"].strip()
              └ {'_prefix': {'command': ('鲁迅说',), 'raw_command': '鲁迅说', 'command_arg': [MessageSegment(type='text', data={'text': '我是
你爹'})], ...

AttributeError: 'Message' object has no attribute 'strip'


关于抽卡的报错，我看到了缺少模块

  File "/data/bot/zhenxun_bot/plugins/draw_card/count_manager.py", line 3, in <module>
    from cachetools import TTLCache

ModuleNotFoundError: No module named 'cachetools'

下载安装了模块之后，发现 相关资源缺失 没有下载下来

 No such file or directory: 'resources/image/draw_card/genshin/shen2she4shou3zhi1shi4.png'

可能是网络问题，我稍后再排查 ，


感谢作者大大




***@***.***
 
发件人： HibiKier
发送时间： 2022-12-26 01:31
收件人： HibiKier/zhenxun_bot
抄送： TKINGNAMe; Author
主题： Re: [HibiKier/zhenxun_bot] 碧蓝航线抽卡报错（下面是报错） (Issue #1213)
加载了，帮助中没显示出来
802f4df 已优化

**Comment by TKINGNAMe** [comment]
今天再测试了一下 鲁迅说 和 抽卡 功能 ，全都正常

谢谢作者大大


***@***.***
 
发件人： ***@***.***
发送时间： 2022-12-26 18:23
收件人： HibiKier/zhenxun_bot; HibiKier/zhenxun_bot
抄送： 1490783711; Author
主题： Re: Re: [HibiKier/zhenxun_bot] 碧蓝航线抽卡报错（下面是报错） (Issue #1213)
好像并不奏效，可能是因为我改动了一些地方（签到？改动了经验的获得数值） 还有关于bt种子那边的搜索网站，你代码中的网址失效了"http://www.eclzz.guru" 现在是这个，
关于鲁迅说也有有些报错，
我明天重新部署一个新的再试试

  File "/data/bot/zhenxun_bot/plugins/luxun/__init__.py", line 46, in handle_event
    content = state["content"].strip()
              └ {'_prefix': {'command': ('鲁迅说',), 'raw_command': '鲁迅说', 'command_arg': [MessageSegment(type='text', data={'text': '我是
你爹'})], ...

AttributeError: 'Message' object has no attribute 'strip'


关于抽卡的报错，我看到了缺少模块

  File "/data/bot/zhenxun_bot/plugins/draw_card/count_manager.py", line 3, in <module>
    from cachetools import TTLCache

ModuleNotFoundError: No module named 'cachetools'

下载安装了模块之后，发现 相关资源缺失 没有下载下来

 No such file or directory: 'resources/image/draw_card/genshin/shen2she4shou3zhi1shi4.png'

可能是网络问题，我稍后再排查 ，


感谢作者大大




***@***.***
 
发件人： HibiKier
发送时间： 2022-12-26 01:31
收件人： HibiKier/zhenxun_bot
抄送： TKINGNAMe; Author
主题： Re: [HibiKier/zhenxun_bot] 碧蓝航线抽卡报错（下面是报错） (Issue #1213)
加载了，帮助中没显示出来
802f4df 已优化
