### ISSUE TITLE
'Plugin' object is not subscriptable

### ISSUE THREAD

**Issue by AHBYCR** [HibiKier/zhenxun_bot#1215]
### 错误截图

![image](https://user-images.githubusercontent.com/96919094/208082370-1b50e257-f29f-454c-81e5-94d91ab64d87.png)

### 日志截图

![image](https://user-images.githubusercontent.com/96919094/208089377-0c86b430-8a7f-4a7e-9c85-94cee6957158.png)

### 错误说明

问了一句查看插件列表就这样了

**Comment by HibiKier** [comment]
0dc11b7edb693d36593cdbf6e2946d4d48b8be10
