### ISSUE TITLE
第三方chatGPT插件的使用

### ISSUE THREAD

**Issue by bbyyds** [HibiKier/zhenxun_bot#1218]
### 错误截图
![image](https://user-images.githubusercontent.com/59153565/208632171-531f4856-542d-4140-8f5f-8f3e3e4f0a52.png)
![image](https://user-images.githubusercontent.com/59153565/208632399-8b1fea40-caf7-4e2c-9263-bdbc7d516306.png)

### 日志截图

[img]

### 错误说明

比较小白，想接入chatgpt，使用第三方的https://github.com/A-kirami/nonebot-plugin-chatgpt插件
修改了插件里config.py的配置，但是依旧没有反应，回复还是默认的ai回复，包括添加关键词依旧无效
不知道还应该该什么东西，请教一下大佬
谢谢

**Comment by TouMing77** [comment]
不要填入api，将chatgpt_to_me:bool的值改为False（禁用@）

**Comment by bbyyds** [comment]
> 不要填入api，将chatgpt_to_me:bool的值改为False（禁用@）

我改为False后有反应了，但是依旧报错，cf cookies获取失败，然后就是超时
![image](https://user-images.githubusercontent.com/59153565/208700012-1199db25-89fd-4e55-a7d9-46f281edc007.png)

**Comment by lingyuan520** [comment]
超时是chatgpt本身问题，你要按那个插件的教程想办法获取cookie，账密登录需要外网环境，也就是配置代理，走token则不需要代理

**Comment by Reversedeer** [comment]
这东西快成closeai了，而且你应该去问对应插件的issues而不是在这里问
