### ISSUE TITLE
关于帮助指令无法使用

### ISSUE THREAD

**Issue by TouMing77** [HibiKier/zhenxun_bot#1219]
### 错误截图

![RXYN4PWFR879 S4( S5HNLR](https://user-images.githubusercontent.com/120631511/208650572-beb6663f-f1d9-4900-b366-81a34ec14480.png)
![~3ZMKEZGJCJ%0_B)1(ZHJNT](https://user-images.githubusercontent.com/120631511/208650622-d4576923-dd02-453e-b5c6-c9f748212d30.png)

### 日志截图

[img]

### 错误说明

输入“真寻帮助”后，聊天中没有回应

**Comment by text233** [comment]
我也遇到了，感觉是依赖的问题
解决了吗？

**Comment by HibiKier** [comment]
群聊里发的吗还是私聊

**Comment by TouMing77** [comment]
> 

群聊私聊都会出现

**Comment by HibiKier** [comment]
群聊应该不会吧，私聊会出现

**Comment by HibiKier** [comment]
b25b9ca928597e38d4aabd6f5227991a80caf0d0 试试

**Comment by Lycofuture** [comment]
解决了吗？
