### ISSUE TITLE
pix指令无法下载图片的问题

### ISSUE THREAD

**Issue by 2228515561** [HibiKier/zhenxun_bot#1222]
### 错误截图

![image](https://user-images.githubusercontent.com/55988289/209781416-f1729bdf-050c-43d7-8e6c-49f9ee8a4593.png)

### 错误说明

向真寻发送pix指令 发生错误ValueError: 'www.pixiv_master1200.net' does not appear to be an IPv4 or IPv6 address
目前还有小概率发生错误ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2622)
服务器位于宿迁   
真寻配置文件没有发生过改动 
有90%概率会发生此问题
使用omega图库

**Comment by HibiKier** [comment]
看着是网络问题

**Comment by 2228515561** [comment]
请问我该如何操作？ 通过什么指令来检测是不是网络问题？亦或者需要更改配置文件来解决问题？

**Comment by MWTJC** [comment]
目前的源码似乎并不能捕获一部分错误，要看具体报错因果得把下文也放出来。
因为我移动宽带下pix也没怎么成功过，所以来说几句废话：
也就三种问题，Hibiapi和你机子不通(配置改Hibiapi)，默认的pix代理和你机子不通(配置改pix代理)，网络本身不稳定所以频繁不通(玄学：配置里把超时设置长一点)

**Comment by 2228515561** [comment]
我这台网络环境是宿迁BGP
这是我的所有错误截图：
![1](https://user-images.githubusercontent.com/55988289/210301001-29353f66-82aa-45e4-bd73-c6a36c9c162c.png)
![2](https://user-images.githubusercontent.com/55988289/210301013-8c41c23a-d2df-4e73-8f6a-0d90cbb4df43.png)
![3](https://user-images.githubusercontent.com/55988289/210301020-3ba60c83-ab5f-4dba-81fd-7a93fc01b70c.png)
![4](https://user-images.githubusercontent.com/55988289/210301026-0dbf428f-cf1f-461c-a466-6390e2019e58.png)
这是ping的结果
![image](https://user-images.githubusercontent.com/55988289/210301366-29ad28e5-0095-4bbd-9a56-e5ff1a9aae0d.png)
这两个ip均为cf的ip 我认为这台服务器访问cf应该是没有问题的
我会把超时时长改长一点来尝试解决问题的

**Comment by 2228515561** [comment]
我尝试更改了超时时长 问题成功得到解决了
Problem solving!
