### ISSUE TITLE
词库问答报错

### ISSUE THREAD

**Issue by molanp** [HibiKier/zhenxun_bot#1223]
### 错误截图

触发词条无反馈

### 日志截图
![屏幕截图_20221228_183850](https://user-images.githubusercontent.com/104612722/209800051-378099ba-25cf-4468-b01a-82379a619970.png)

![屏幕截图_20221228_183857](https://user-images.githubusercontent.com/104612722/209800063-784bab40-040e-487c-8971-77a574444a29.png)

### 错误说明

触发词条‘深夜福利’时报错
词条内容为下
添加词条问深夜福利答 爸❤️妈❤ ️不❤️在❤️家 一❤️个❤️人❤️寂❤️寞 现❤️代❤️青❤️年❤️男❤️女 必  备 学 习 资 料 [CQ:face,id=76] [CQ:face,id=76] [CQ:face,id=76] https://www.xuexi.cn/
![屏幕截图_20221228_184721](https://user-images.githubusercontent.com/104612722/209801527-e694a52d-6c5c-4a5d-8efe-14e7d0129090.png)

**Comment by HibiKier** [comment]
2070014021fa3b490fb93559593363f0afa70e55
