### ISSUE TITLE
有办法修改真寻的ws-reverse Universal的地址吗

### ISSUE THREAD

**Issue by XKaguya** [HibiKier/zhenxun_bot#1224]
请问 我想在一台机子上挂多个机器人，虽然ws后面的不一样，但是都是用的8080端口，结果出现了badhandshake报错，这个有办法改吗？

**Comment by HibiKier** [comment]
一个nb多个gocq吗

**Comment by XKaguya** [comment]
其实应该是2个nb，但是不清楚他用的什么框架 ， 但是有多个gocq

**Comment by HibiKier** [comment]
多个gocq连真寻的话直接gocq配置都填 universal: ws://127.0.0.1:8080/onebot/v11/ws  就行了

**Comment by XKaguya** [comment]
好像和我的想法不太一样 设想是2个号 也就是2个gocq 分别对应2个nb（或者有可能一个不是） 想实现这个 但是他的是java写的 更不会看了

**Comment by XKaguya** [comment]
![image](https://user-images.githubusercontent.com/96401952/210130714-200fbfcd-b512-4d92-9869-b37fa4f3423c.png)
这个是另一个gocq的地址 个人不太清楚，不过猜测可能 改个端口应该就差不多了？

**Comment by HibiKier** [comment]
？
![图片](https://user-images.githubusercontent.com/45528451/210134290-80c69577-c81b-4c28-8c62-727a8a0a0410.png)

**Comment by XKaguya** [comment]
这个是另一个机器人的，文档里叫我这么填

**Comment by XKaguya** [comment]
![image](https://user-images.githubusercontent.com/96401952/210134427-47e3d1dd-2671-4cc6-a360-73c08418be84.png)
![image](https://user-images.githubusercontent.com/96401952/210134434-50f5d74d-24dc-4b55-a494-46402ea4f246.png)
如果开启了另一个，会导致真寻也用不了，想问的是这个，就是能不能更改一下真寻的这个地址

**Comment by hwf160** [comment]
在真寻目录的.dev.env里改

**Comment by hwf160** [comment]
PORT

**Comment by XKaguya** [comment]
> PORT

哦，明白了，感谢
