### ISSUE TITLE
更新到最新版zhenxun_bot的时候help插件错误的解决方案

### ISSUE THREAD

**Issue by barryblueice** [HibiKier/zhenxun_bot#1225]
### 真寻版本：0.1.6.6

今天晚上通过指令更新zhenxun_bot的之后发现bot的help插件突然error了。

具体表现为向bot发送“帮助”指令时，bot输出为文字而非图片：

![image](https://user-images.githubusercontent.com/44601454/210099982-83eff3ac-6126-490d-9002-d5dd1c581467.png)

接着在终端中重启机器人后查看输出，找到了出错原因。具体原因为不能导入TEMPLATE_PATH：

![image](https://user-images.githubusercontent.com/44601454/210100071-88b0f071-3c93-43c0-bd0d-51f897060dac.png)

**解决方案：**

打开bot安装目录/configs下的path_config.py，在路径那一块添加参数TEMPLATE_PATH = Path() / "resources" / "template"即可解决：

![image](https://user-images.githubusercontent.com/44601454/210100209-ea3df9b9-b689-45ee-bd29-7e5a9adedc72.png)

添加参数后重启bot，即可正常输出图片：

![image](https://user-images.githubusercontent.com/44601454/210100318-9d58bafc-b524-4e64-bb4c-c392a23e7794.png)

**Comment by 1457937851** [comment]
谢谢大佬！！
