### ISSUE TITLE
关于temp文件夹占用问题

### ISSUE THREAD

**Issue by ChthollyWn** [HibiKier/zhenxun_bot#1227]
### 错误截图

![image](https://user-images.githubusercontent.com/85938618/210290149-e90d9065-875f-4e7c-8257-72bd07a39c09.png)

### 日志截图

[img]

### 错误说明
之前因为img/_setu文件占用过大，就把图片全部清除了，今天发现这个temp文件直接占用了10个G，服务直接寄了，请问这个temp文件夹是储存的什么文件呢，为何会突然占用这么大的内存

**Comment by HibiKier** [comment]
临时文件，每天会定时清理

**Comment by ChthollyWn** [comment]
> 临时文件，每天会定时清理

但是这个文件占用太大，超过了服务器内存，导致服务器宕机了，而且已经连续两天出现这种情况了，请问有什么解决的办法吗

**Comment by HibiKier** [comment]
basic_plugin/super_cmd/clear_data中修改定时任务执行时间
