### ISSUE TITLE
关于genshin插件中resin功能导致attribute error

### ISSUE THREAD

**Issue by HoshisakiRakusei** [HibiKier/zhenxun_bot#1230]
### 错误截图

![7N _0P6~V{{J3@1$L3X@~C0](https://user-images.githubusercontent.com/122346715/211489354-a7060a00-d5ec-4186-bb1f-9f065d6053bb.png)
bot无法正常开启，截图截日志报错部分

### 日志截图

![L4I@58E 7$Y8MW)0~ET~ZZU](https://user-images.githubusercontent.com/122346715/211489554-d17ddd2a-330b-4383-b86d-42ac8090d938.png)
![Q1}{{A7I(ZI3S S5F`J`294](https://user-images.githubusercontent.com/122346715/211489588-13b3d5a7-d781-4510-b9d0-83cab003b8a3.png)

报错日志如上，报错显示插件内报错代码如上

### 错误说明

在尝试兼容其他nonebot插件重启后出现报错，bot无法正常启动，经由日志报错排查到是为genshin插件导致的报错，直接删除插件后，bot可正常使用，后尝试将报错代码所在代码块及相关代码删除，以及将resin_remind文件夹删除，genshin插件正常运行，经此确定错误为resin功能导致

**Comment by HibiKier** [comment]
已重构
