### ISSUE TITLE
cos图片发送失败

### ISSUE THREAD

**Issue by xzzt1267** [HibiKier/zhenxun_bot#1234]
### 错误截图

![QQ图片20230115001341](https://user-images.githubusercontent.com/96318711/212482605-e9f82a65-c5d3-49ce-bbf8-bb2f60502958.png)

### 日志截图

<img width="1266" alt="1" src="https://user-images.githubusercontent.com/96318711/212482773-5290201b-7774-4db2-8a66-489d1b0258dd.png">

**Comment by NathanSummer** [comment]
我用两个都不行
