### ISSUE TITLE
b站开始用新的uuid算法了，新的uuid会超出int32的范围

### ISSUE THREAD

**Issue by SHDocter** [HibiKier/zhenxun_bot#1235]
`[INFO] bilibili_sub | bilibili_sub 添加订阅错误 <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: 3493113179933630 (value out of int32 range)`

**Comment by HibiKier** [comment]
尽快修

**Comment by litousteven** [comment]
还没修吗...

**Comment by HibiKier** [comment]
1c63384082f45a176012edc7d1f96abf15a72cc9

**Comment by cj1357** [comment]
> [1c63384](https://github.com/HibiKier/zhenxun_bot/commit/1c63384082f45a176012edc7d1f96abf15a72cc9)

is out of range for type integer还是提示发生错误，订阅UP的时候提示“添加订阅失败”
![image](https://user-images.githubusercontent.com/40661342/232289466-d004469b-6fe6-4391-b5f4-041050382519.png)

**Comment by HibiKier** [comment]
what，订阅id多少

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/232309018-8c2d0052-20f6-4e42-9fbe-dfd51a7cdba3.png) 可以吧？

**Comment by cj1357** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/232309018-8c2d0052-20f6-4e42-9fbe-dfd51a7cdba3.png) 可以吧？

噫？怎么回事，只有我这样么，我是单独把bilibili_sub这个插件文件夹替换更新了… er'q而且现在主播开播后还会报错了，原先是正常的
![image](https://user-images.githubusercontent.com/40661342/232310072-48ce8acd-bd2b-42fb-aa38-101ad27d4000.png)

**Comment by cj1357** [comment]
是不是原先torotise里面的数据还是integer，然后冲突了？我要不要把bilibili_sub的数据库删掉…我想试试但是不知道怎么操作…

**Comment by HibiKier** [comment]
更新试试

**Comment by cj1357** [comment]
还是会报错，但是跟之前的报错不太一样了（变成int32了）
![image](https://user-images.githubusercontent.com/40661342/233783724-4f64729c-30f9-409d-a8ef-1f3c2a2f57a2.png)

改动我看了好像就是这个地方吧
![image](https://user-images.githubusercontent.com/40661342/233783867-a4cd0ea5-286a-486a-a62c-e0839efe6f5c.png)

还有就是我发现添加订阅主播用的是直播间房间号，房间号都是比较短的，订阅了主播后也是可以收到动态通知的，尽管up的空间ID很长

**Comment by cj1357** [comment]
是不是我的数据库有问题……

**Comment by webjoin111** [comment]
我是把数据库里B站订阅的表删了，重启下就行了

**Comment by cj1357** [comment]
> 我是把数据库里B站订阅的表删了，重启下就行了

原来真的要这样，谢谢
