### ISSUE TITLE
关于用户使用道具出现错误

### ISSUE THREAD

**Issue by opaup** [HibiKier/zhenxun_bot#1236]
### 错误截图

![N8@ {7CN1K))FNATH5CB8BS](https://user-images.githubusercontent.com/73473196/212603448-3f373df9-3cde-42f1-9701-1b57130c5294.png)

### 日志截图

![1](https://user-images.githubusercontent.com/73473196/212603325-6d3a38d3-1d03-4d1a-a177-559b6aa468f4.png)
![2](https://user-images.githubusercontent.com/73473196/212603331-b2b3b863-1489-4a5f-b92c-17c15ab86bee.png)
![3](https://user-images.githubusercontent.com/73473196/212603333-fbd70231-2f47-495f-9f00-d7ed3a6d956b.png)
![4](https://user-images.githubusercontent.com/73473196/212603338-efb70a7f-9e53-474b-975c-b8b88bf57998.png)

### 错误说明

在使用指令："使用道具1"\"使用道具2"\"使用道具好感度双倍加持卡Ⅰ"时，真寻不会回复，并且出现以上报错，但不存在道具如"使用道具3"时，真寻会回复"@xx 仔细看看自己的道具仓库有没有这个道具？"

最近突然有一位用户提出 使用道具之后真寻没有回复 的问题，并且在gocq端会返回如上问题(但实际上并没有被风控，真寻依旧能够响应其他指令)，据他的描述，这个问题在我从版本0.1.6.5更新到0.1.6.6之前就存在了。

并且似乎只有他一个人存在这个问题。我尝试了去数据库中清空了他的道具，但是问题依旧存在。

**Comment by HibiKier** [comment]
没有禁言的话基本就是风控，你把文字消息转成图片看看能不能发送就知道了
