### ISSUE TITLE
如何让真寻在发出一条消息过一段时间后自动撤回

### ISSUE THREAD

**Issue by barryblueice** [HibiKier/zhenxun_bot#1237]
如题。最近在写定制插件，但是我没办法实现这个功能。请问如何让真寻在发出一条消息过一段时间后自动撤回？

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/213928073-cd0a8a6c-822f-4eb8-82d1-5bbad4ec2da8.png)
