### ISSUE TITLE
几个小疑惑

### ISSUE THREAD

**Issue by NathanSummer** [HibiKier/zhenxun_bot#1238]

**Comment by HibiKier** [comment]
https://hibikier.github.io/zhenxun_bot/docs/development_doc/shop_handle.html#%E6%B3%A8%E5%86%8C%E5%95%86%E5%93%81%E5%92%8C%E7%94%9F%E6%95%88%E6%96%B9%E6%B3%95

**Comment by NathanSummer** [comment]
方式二应该咋用，复制代码创建新.py之后放在哪呀？

**Comment by HibiKier** [comment]
随便，可以放你插件的文件夹里

**Comment by NathanSummer** [comment]
> 随便，可以放你插件的文件夹里

感谢🙏

**Comment by NathanSummer** [comment]
大佬，那个识图的网站SauceNAO现在好像被墙了怎么办？

**Comment by HibiKier** [comment]
代理

**Comment by NathanSummer** [comment]
那搜番的https://share.dmhy.org/topics/rss/rss.xml?keyword=现在也需要代理了嘛？
