### ISSUE TITLE
错误操作致使词条系统出了点问题

### ISSUE THREAD

**Issue by NathanSummer** [HibiKier/zhenxun_bot#1240]
### 错误说明
添加词条的时候一不小心在问题里用了QQface，结果
发所有词条id都提示不在范围内，那个出错的词条也删不掉
这个应该怎么办？

**Comment by NathanSummer** [comment]
> QQ face也可以的啊

可是我放在问题里了呜呜呜（对不起）
![image](https://user-images.githubusercontent.com/88868171/214333334-9a61f164-e063-417d-9b5e-9b721df7d5d4.png)

**Comment by HibiKier** [comment]
日志

**Comment by NathanSummer** [comment]
![image](https://user-images.githubusercontent.com/88868171/214335278-2f43d750-abcd-457f-8194-eb814b38ea43.png)
![微信图片_20230124232708](https://user-images.githubusercontent.com/88868171/214335769-8fedecd4-7ee3-4e15-8e67-42dd379cae86.jpg)
![微信图片_20230124232843](https://user-images.githubusercontent.com/88868171/214336028-e655ac71-cdc6-4f47-8baf-1063d2a9cc16.jpg)
好像...不会报错
而且不光是这一条，所有词条的id都失效了

**Comment by NathanSummer** [comment]
指令换成gid也没有用，用”查看词条“的话gid是乱的（有的重复有的缺失）
用”删除词条“的话全部提示词条不存在

**Comment by NathanSummer** [comment]
![image](https://user-images.githubusercontent.com/88868171/214813089-e74791b2-f168-46f1-8fcc-f3fea8f4c06a.png)
![微信图片_20230126182509](https://user-images.githubusercontent.com/88868171/214813134-f3b6d6fe-9e6b-43c5-9626-383522188707.jpg)
![微信图片_20230126182517](https://user-images.githubusercontent.com/88868171/214813139-9e6fa295-0db8-4be6-a5ed-beaa197cf75e.jpg)

**Comment by HibiKier** [comment]
你这个词条是全局的吗？

**Comment by NathanSummer** [comment]
> 你这个词条是全局的吗？

是的啊，只有全局词条出问题

**Comment by NathanSummer** [comment]
> 你这个词条是全局的吗？

是的啊，只有全局词条出问题

**Comment by HibiKier** [comment]
你命令不对啊，全局词条是私聊 `删除全局词条 id:6`

**Comment by NathanSummer** [comment]
> 你命令不对啊，全局词条是私聊 `删除全局词条 id:6`

那查看词条哩？

**Comment by HibiKier** [comment]
查看词条是分id和gid的啊，帮助不是都写了吗

**Comment by NathanSummer** [comment]
> 查看词条是分id和gid的啊，帮助不是都写了吗

出问题的那条已经删掉了，但是现在”查看词条 gid:X“指令出来的词条和gid还是不对应（捂脸

**Comment by NathanSummer** [comment]
> 出问题的那条已经删掉了，但是现在”查看词条 gid:X“指令出来的词条和gid还是不对应（捂脸

有的是几个gid她发同一个词条，有的gid她没反应

**Comment by HibiKier** [comment]
日志

**Comment by NathanSummer** [comment]
从0到6不报错但是顺序是乱的而且有重复
从7到10都这样报错
![image](https://user-images.githubusercontent.com/88868171/214822108-8151eb0a-d804-49a3-b091-91a9e9a03dc6.png)
从11到13这样报错
![image](https://user-images.githubusercontent.com/88868171/214823299-2ed8aecc-5806-4312-a625-dbe84b980cfb.png)
从14到17不报错但是顺序也是乱的（可是现在gid最大是16）
18开始提示超出范围

**Comment by HibiKier** [comment]
稍等
