### ISSUE TITLE
自定义入群欢迎报错

### ISSUE THREAD

**Issue by hutu0913** [HibiKier/zhenxun_bot#1243]
### 系统版本：	
Windows Server 2012
### 日志截图

[img]
![QQ图片20230127221918](https://user-images.githubusercontent.com/75601433/215109204-f5925657-def4-4a3f-b074-2a72bec0ebf9.png)

![QQ图片20230127221933](https://user-images.githubusercontent.com/75601433/215109238-c4717414-8e52-4a10-9b3e-15bf19662b72.png)

### 错误说明

![QQ图片20230127222320](https://user-images.githubusercontent.com/75601433/215109612-1193257a-39d0-458e-907b-b31dff293c43.png)

**Comment by DDS-DS** [comment]
更换图片也是没有办法成功吗？方便把图片文件发一下嘛

**Comment by hutu0913** [comment]
换了图片也不行
![QQ图片20230129223950](https://user-images.githubusercontent.com/75601433/215333807-8dccf391-b13a-4b04-80ba-da91a68d2ed7.png)
![QQ图片20230129224151](https://user-images.githubusercontent.com/75601433/215333919-bf65d933-264d-4f1b-b3a9-979bdd2c4f98.jpg)
![QQ图片20230129191236](https://user-images.githubusercontent.com/75601433/215334003-b3f56836-ca47-4a3e-b74b-6f99b825115b.jpg)

**Comment by hutu0913** [comment]
![QQ图片20230129191206](https://user-images.githubusercontent.com/75601433/215334395-dadcd224-b521-42e2-ac95-8f287459ba59.gif)
动图也不行滴

**Comment by DDS-DS** [comment]
很遗憾，我这边没有办法复现你这个问题，是否可以尝试把环境重新进行配置？
![image](https://user-images.githubusercontent.com/75608102/215372118-d5b24ce1-2830-4c1b-b731-50982f6e5dee.png)

**Comment by hutu0913** [comment]
好吧蟹蟹
