### ISSUE TITLE
如果我想给真寻换服务器 该怎么连带着数据转移过去呢

### ISSUE THREAD

**Issue by niucattle** [HibiKier/zhenxun_bot#1246]
如题

**Comment by HibiKier** [comment]
保留data和数据库

**Comment by niucattle** [comment]
> 保留data和数据库

真寻根目录下的data保留了，数据库也备份并导入了，但是出现了部分人好感和签到都丢失数据的情况，请问这怎么办呢

**Comment by niucattle** [comment]
同一个群里部分人有部分人没有，包括我本人也丢失了一个群中的数据

**Comment by niucattle** [comment]
![~FF%4(XL$TCZ5W{Q(56NDTD](https://user-images.githubusercontent.com/118875129/215522315-c8da970b-8e8f-48c0-85d3-fd72c30cfb96.png)

**Comment by niucattle** [comment]
![A23JL4Y`LR`O0BIT L6(MVM](https://user-images.githubusercontent.com/118875129/215522551-e80e5b91-41d3-4d3d-a6f6-34062cc5cd82.png)

**Comment by niucattle** [comment]
我在pgadmin中能查到这些人的数据，但实际上并没有显示出来

**Comment by niucattle** [comment]
已解决，在第二天数据就恢复了，虽然不知道为什么

**Comment by fuyang0811** [comment]
> 已解决，在第二天数据就恢复了，虽然不知道为什么

应该是缓存的图片，第二天会生成新的图片，所以就正常了
