### ISSUE TITLE
指定的网络名不再可用

### ISSUE THREAD

**Issue by SHERD1** [HibiKier/zhenxun_bot#1247]
系统版本：win10
真寻版本：0.1.5.3

**错误截图**
![QQ截图20230130123510](https://user-images.githubusercontent.com/123920739/215388684-91700007-2579-4844-8ace-412180725ee5.png)
![QQ截图20230130123539](https://user-images.githubusercontent.com/123920739/215388723-2da4f0b9-f56d-442e-9eae-5be1edc3c57b.png)

**错误说明**
首次安装真寻时启动成功无异常
重启电脑后报错
重装真寻也无法启动

**Comment by HibiKier** [comment]
config里数据库配置没写对吧
