### ISSUE TITLE
“重载插件配置”的帮助说明指令与实际命令不符

### ISSUE THREAD

**Issue by MWTJC** [HibiKier/zhenxun_bot#1248]
如题，小问题，`BOT\basic_plugins\super_cmd\reload_setting.py`中，存在帮助说明指令(重载插件配置)与实际触发指令(重载配置)不符的情况，仅告知。
兔年吉祥。

**Comment by HibiKier** [comment]
1f68481256b99e6ef3077ffd5cfb19a2d936c0ac
