### ISSUE TITLE
一种避免安装poetry直接安装包的方法

### ISSUE THREAD

**Issue by mnixry** [HibiKier/zhenxun_bot#125]
理论上建个空壳文件夹叫`zhenxun_bot`, 塞个`__init__.py`, 这样在项目目录下直接就可以用`pip install .`指令了

原因是这样这个项目就是一个Python包, 可以被pip识别并安装, 可以测试一下

同时, 以Python包的形式组织项目也是我个人比较推荐的一种形式, 可以尝试把Bot往这种组织形式迁移

**Comment by evlic** [comment]
其实是比较支持用 poetry 创建虚拟环境的，虽然 poetry 本身存在 update 非常非常慢的问题（大约一次更新依赖会执行，半个小时），但是虚拟环境可以隔开本机的依赖，有可能一定程度上可以减少奇奇怪怪的 Bug。

我一直用 pm2 来做守护线程，poetry 唯一会有的麻烦是在写执行脚本的时候会比较困难。而后又遇到一些奇怪 BUG（比如无法获取浏览器 Browser 对象），最后尝试使用 root 用户启动而解决了 Bug。

`sudo pm2 start -n 'zxbot' -x 'su - ubuntu -c " cd ~/AtCode/qq-robot/zx && source /home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-HfkEkzli-py3.8/bin/activate && python3 bot.py" '`

**Comment by mnixry** [comment]
> 其实是比较支持用 poetry 创建虚拟环境的，虽然 poetry 本身存在 update 非常非常慢的问题（大约一次更新依赖会执行，半个小时），但是虚拟环境可以隔开本机的依赖，有可能一定程度上可以减少奇奇怪怪的 Bug。

我基本同意您的观点, 但是需要补充的一点是虚拟环境不是poetry独有的, 也可以自己创建虚拟环境, 比如用conda, venv, 甚至pipx(对真寻来说暂时不行).

另外, 关于poetry的依赖安装较慢这一点, 和poetry的安装解析策略不无关系, 在根本上, poetry会直接无视pip镜像配置而是直接去pypi官网解析(这一点在执行`poetry install -vvv`的时候就可以看到), 这使得它在大陆的网络条件下工作很差. 
这个问题在poetry上一直存在, 我很久之前[提了一个Issue](https://github.com/python-poetry/poetry/issues/3553), 但是到现在都没有得到解决 (可能是因为老外用不着... 他们对修改**公共镜像源**这种功能根本没需求).
值得注意的一点是, 真寻在`pyproject.toml`中强制指定了镜像源, 这是有用的, 但是灵活性不足, 在连接大陆网络比较差的国外服务器上工作效果可能会不太好.

> 我一直用 pm2 来做守护线程，poetry 唯一会有的麻烦是在写执行脚本的时候会比较困难。而后又遇到一些奇怪 BUG（比如无法获取浏览器 Browser 对象），最后尝试使用 root 用户启动而解决了 Bug。

PM2确实是一款非常好用的进程管理工具, 我也在用, 但是基本是在Node上, 对于部署有虚拟环境的Python项目经验不足.
目前NoneBot2文档对于[使用PM2部署的这一节](https://v2.nonebot.dev/docs/tutorial/deployment#%E4%BD%BF%E7%94%A8-pm2-%E9%83%A8%E7%BD%B2)暂时是空缺的, 如果您有兴趣, 也可以来为NoneBot2贡献这一部分的文档 ~~(试图打广告)~~

**Comment by evlic** [comment]
> PM2确实是一款非常好用的进程管理工具, 我也在用, 但是基本是在Node上, 对于部署有虚拟环境的Python项目经验不足. 目前NoneBot2文档对于[使用PM2部署的这一节](https://v2.nonebot.dev/docs/tutorial/deployment#%E4%BD%BF%E7%94%A8-pm2-%E9%83%A8%E7%BD%B2)暂时是空缺的, 如果您有兴趣, 也可以来为NoneBot2贡献这一部分的文档 ~(试图打广告)~

很荣幸能收到邀请，稍后我会前往文档中尝试完善有关「pm2部署」的部分，很乐意能为 NoneBot 贡献我的一点点经验。

**Comment by noahzark** [comment]
> 其实是比较支持用 poetry 创建虚拟环境的，虽然 poetry 本身存在 update 非常非常慢的问题（大约一次更新依赖会执行，半个小时），但是虚拟环境可以隔开本机的依赖，有可能一定程度上可以减少奇奇怪怪的 Bug。
> 
> 我一直用 pm2 来做守护线程，poetry 唯一会有的麻烦是在写执行脚本的时候会比较困难。而后又遇到一些奇怪 BUG（比如无法获取浏览器 Browser 对象），最后尝试使用 root 用户启动而解决了 Bug。
> 
> `sudo pm2 start -n 'zxbot' -x 'su - ubuntu -c " cd ~/AtCode/qq-robot/zx && source /home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-HfkEkzli-py3.8/bin/activate && python3 bot.py" '`

提供另一种思路w 我PM2是这样起的

```
pm2 start ./bot.py --name=mahiro --interpreter /root/.cache/pypoetry/virtualenvs/zhenxun-bot-k3Ru0nAG-py3.8/bin/python
```

参考 [USING TRANSPILERS WITH PM2](https://pm2.keymetrics.io/docs/tutorials/using-transpilers-with-pm2)
