### ISSUE TITLE
求助，真寻启动发生错误

### ISSUE THREAD

**Issue by Mic2333** [HibiKier/zhenxun_bot#1250]
### 错误截图

一小部分的报错
![1](https://img1.imgtp.com/2023/02/02/E7HJbpF4.png "1")
![2](https://img1.imgtp.com/2023/02/02/3889lDCn.png "2")
![3](https://img1.imgtp.com/2023/02/02/DKyisGP2.png "3")

### 日志截图

报错太多了不知道直接放整个日志行不行（）
https://privatebin.net/?cce9b7c287f9216a#7o8bU1qqKNLNLUdmo2Ce3STRYD2K7Z1Jp9HzH6LQXCSQ

### 错误说明

启动bot.py后大量报错

**Comment by PackageInstaller** [comment]
你这个work_bank插件有那么点问题啊，先把真寻更新到0.1.6.7试试

**Comment by HibiKier** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/373#issuecomment-1131638639
