### ISSUE TITLE
求助，翻译功能出错

### ISSUE THREAD

**Issue by Huang1932539** [HibiKier/zhenxun_bot#1251]
### 错误截图

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/122792813/216363002-826f6fda-d294-4ad1-b194-888eabc18d19.png">

### 错误说明

没法翻译了，一输入就报错

**Comment by HibiKier** [comment]
api坏了

**Comment by Huang1932539** [comment]
> api坏了

请问那这怎么解决啊？

**Comment by HibiKier** [comment]
等更新
