### ISSUE TITLE
将nonebot插件作为真寻插件加载的简陋实现

### ISSUE THREAD

**Issue by IAXRetailer** [HibiKier/zhenxun_bot#1255]
详见 https://gist.github.com/IAXRetailer/c722b93c4ee716284be53da572d747bf

原理大概就是先从site-package找包，然后复制到bot目录下，再进行pather添加几个基本变量，最后调用nonebot的插件加载器导入

(大佬轻喷)

**Comment by HibiKier** [comment]
。一般插件都是有github仓库的

**Comment by IAXRetailer** [comment]
也是，当初最开始的想法是想看看能不能更方便的安装下载为库的插件，没想太多，其实意义并不大（X
