### ISSUE TITLE
插件‘draw_card’报错

### ISSUE THREAD

**Issue by Zmincrix** [HibiKier/zhenxun_bot#1262]
### 错误截图
![image](https://user-images.githubusercontent.com/35093819/219280902-a4302e0b-2029-40a4-be06-1e29ce3cac32.png)

### 错误说明
02-16 05:55:22 [INFO] init_plugin_config | 初始化数据完成...
02-16 05:55:22 [WARNING] draw_card | azur_up_char 解析出错
02-16 05:55:22 [WARNING] draw_card | guardian_up_char 解析出错
02-16 05:55:22 [WARNING] draw_card | pretty_up_char 解析出错
02-16 05:55:23 [WARNING] draw_card | 碧蓝档案 更新数据错误：<class 'json.decoder.JSONDecodeError'>：Expecting value: line 1 column 1 (char 0)

**Comment by HibiKier** [comment]
碧蓝档案是有点问题的
