### ISSUE TITLE
求助!显示远程计算机拒绝连接

### ISSUE THREAD

**Issue by Huang1932539** [HibiKier/zhenxun_bot#1265]
### 错误内容

02-18 18:17:55 [ERROR] logging | Traceback (most recent call last):  File "E:\ZhenXun\zhenxun_bot-0.1.6.6\services\db_context.py", line 19, in init    await db.set_bind(i_bind)  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\gino\api.py", line 417, in set_bind    bind = await create_engine(bind, loop=loop, **kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\gino\strategies.py", line 55, in create    pool = await dialect.init_pool(u, loop, pool_class=pool_class)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\gino\dialects\asyncpg.py", line 465, in init_pool    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\gino\dialects\asyncpg.py", line 218, in _init    self._pool = await asyncpg.create_pool(**args)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\pool.py", line 409, in _async__init__    await self._initialize()  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\pool.py", line 437, in _initialize    await first_ch.connect()  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\pool.py", line 129, in connect    self._con = await self._pool._get_new_connection()                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\pool.py", line 507, in _get_new_connection    con = await connection.connect(          ^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\connection.py", line 2092, in connect    return await connect_utils._connect(           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\connect_utils.py", line 895, in _connect    raise last_error  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\connect_utils.py", line 881, in _connect    return await _connect_addr(           ^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\connect_utils.py", line 773, in _connect_addr    return await __connect_addr(params, timeout, True, *args)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\connect_utils.py", line 825, in __connect_addr    tr, pr = await compat.wait_for(connector, timeout=timeout)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\compat.py", line 56, in wait_for    return await asyncio.wait_for(fut, timeout)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 479, in wait_for    return fut.result()           ^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\asyncpg\connect_utils.py", line 684, in _create_ssl_connection    tr, pr = await loop.create_connection(             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1079, in create_connection    raise exceptions[0]  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1063, in create_connection    sock = await self._connect_sock(           ^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 967, in _connect_sock    await self.sock_connect(sock, address)  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect    return await self._proactor.connect(sock, address)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 841, in _poll    value = callback(transferred, key, ov)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 628, in finish_connect    ov.getresult()ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\starlette\routing.py", line 671, in lifespan    async with self.lifespan_context(app):  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\starlette\routing.py", line 566, in __aenter__    await self._router.startup()  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-a_M5aK_5-py3.11\Lib\site-packages\starlette\routing.py", line 648, in startup    await handler()  File "E:\ZhenXun\zhenxun_bot-0.1.6.6\services\db_context.py", line 23, in init    raise Exception(f'数据库连接错误.... {type(e)}: {e}')Exception: 数据库连接错误.... <class 'ConnectionRefusedError'>: [WinError 1225] 远程计算机拒绝网络连接。

**Comment by Huang1932539** [comment]
还有这个：
![0(V9 {}SMHFR_OG}U 17~V6(1)](https://user-images.githubusercontent.com/122792813/219855882-18cd3b09-4889-4e6f-819c-f45696cffef0.png)

**Comment by HibiKier** [comment]
本地数据库没开

**Comment by Huang1932539** [comment]
> 本地数据库没开

可是像上面发的图片一样，我连接不上啊

**Comment by HibiKier** [comment]
因为你本地数据库没开啊
