### ISSUE TITLE
运行bot.py发生错误

### ISSUE THREAD

**Issue by drftcv** [HibiKier/zhenxun_bot#1268]
### 错误截图

![image](https://user-images.githubusercontent.com/122135303/220053689-ca3d103f-ec05-44d4-acd8-1cd32a05413d.png)

**Comment by HibiKier** [comment]
依赖没装

**Comment by drftcv** [comment]
![image](https://user-images.githubusercontent.com/122135303/220142652-d7f8ed91-3a6b-4513-8911-41089424962a.png)


> 依赖没装

它提示不需要安装或更新依赖项，这又是什么情况

**Comment by drftcv** [comment]
playwright install chromium
目前问题大概是在这步运行之后不会报错但也没有任何反应直接就结束了

**Comment by drftcv** [comment]
不知道如何解决

**Comment by drftcv** [comment]
解决了

**Comment by a042979** [comment]
我也出现这个问题了 tortoise 我是装了的
![image](https://user-images.githubusercontent.com/114063925/222923128-d819432f-0a31-4140-96d7-10bd45bf8e94.png)
![image](https://user-images.githubusercontent.com/114063925/222923138-38d47e09-8119-43cd-820e-c0034b84d635.png)

**Comment by a042979** [comment]
请问是怎么解决的
