### ISSUE TITLE
第一次启动没有生成配置文件

### ISSUE THREAD

**Issue by Xiaojack1026** [HibiKier/zhenxun_bot#1269]
![image](https://user-images.githubusercontent.com/125620242/220064073-d2268b1e-f20f-4fee-90ed-0cc9f9943b48.png)

**Comment by HibiKier** [comment]
日志

**Comment by Xiaojack1026** [comment]
辛苦大佬了，会不会跟我系统有关系啊，我用的win11

这是安装的版本


透不过的夜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 晚上9:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] 第一次启动没有生成配置文件 (Issue #1269)





 
日志

**Comment by HibiKier** [comment]
发日志啊
