### ISSUE TITLE
docker部署时的一点小问题

### ISSUE THREAD

**Issue by Putarku** [HibiKier/zhenxun_bot#127]
拉取官方镜像部署以后gocqhttp连接不上。排查了一圈以后才发现，容器内的地址是127.0.0.1，因为我的gocqhttp是单独一个容器的所以没法连接。更改为0.0.0.0后便可以连接了。
![image](https://user-images.githubusercontent.com/66679443/156038257-09adeb7e-e039-4d40-9d3d-22c2969907fd.png)
![image](https://user-images.githubusercontent.com/66679443/156038328-654647ba-5ea3-47bf-b680-f430b85d57a3.png)

**Comment by Sakuracio** [comment]
可以将Bot容器网络设置为host 或者GOCQHTTP填写容器的IP
