### ISSUE TITLE
报告两个问题

### ISSUE THREAD

**Issue by Blank-Cao** [HibiKier/zhenxun_bot#1271]
1. gino 改成 tortoise 后，poetry 依赖并没有进行相应修改，导致运行 poetry install 后还需要进入虚拟环境手动用 pip 安装相关依赖项（而且相关依赖项有三个，难以找全依赖项进行修复）
2. models/level_user.py 文件中 LevelUser 类的 check_level 方法应检查用户权限等级是否大于等于相应 level。bot 应该允许权限等级为对应最低等级的用户使用至少需要相应权限等级才能触发的指令。比如说等级5用户应该可以调用等级5的指令，而不是等级6的用户才能调用

**Comment by UVJkiNTQ** [comment]
我也遇到了 tortoise的问题

**Comment by HibiKier** [comment]
已更新
