### ISSUE TITLE
如何同意其他用户的邀请入群申请

### ISSUE THREAD

**Issue by dong2005923** [HibiKier/zhenxun_bot#1273]
其他用户邀请会自动退出，超级用户也无法决定同意或是不同意其他用户的邀请入群申请

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/220508576-eb58c6b9-1df5-4cdd-bb78-86c7c2daa4d5.png)
文档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档

**Comment by dong2005923** [comment]
抱歉，是我没有仔细翻看文档

**Comment by dong2005923** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/220508576-eb58c6b9-1df5-4cdd-bb78-86c7c2daa4d5.png) 文档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档



> ![图片](https://user-images.githubusercontent.com/45528451/220508576-eb58c6b9-1df5-4cdd-bb78-86c7c2daa4d5.png) 文档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档档

抱歉，是我没有仔细翻看文档
