### ISSUE TITLE
多连开箱展示结果为空白

### ISSUE THREAD

**Issue by MiaoYuuuu** [HibiKier/zhenxun_bot#1277]
### 错误截图

![QQ图片20230223234242](https://user-images.githubusercontent.com/104083956/220957090-77eedaf1-12ae-48f7-867c-ff01f6989f0a.png)

**Comment by dong2005923** [comment]
我也有这个问题，而且单次开箱不消耗次数

**Comment by HibiKier** [comment]
8133b61ebd28459a5a33bd53e998eb636c3725b4

**Comment by dong2005923** [comment]
更新后，问题依然存在，多次开箱图片为空白，单次开箱不消耗次数。
由于使用“检查更新真寻指令失败”提示自动获取真寻版本失败，我使用git pull命令来进行更新。
系统版本win11
真寻版本0.1.6.6

**Comment by dong2005923** [comment]
> [8133b61](https://github.com/HibiKier/zhenxun_bot/commit/8133b61ebd28459a5a33bd53e998eb636c3725b4)

更新后，问题依然存在，多次开箱图片为空白，单次开箱不消耗次数。

由于使用“检查更新真寻指令失败”提示自动获取真寻版本失败，我使用git pull来进行更新。

真寻版本0.1.6.6
系统版本win11，Python版本3.10

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/221553055-57d8a88a-d4d5-4b18-995f-fe02a39c7164.png)
一切正常捏，看看更新成功了没有
