### ISSUE TITLE
work_bank持续监听报错

### ISSUE THREAD

**Issue by mmbbhh** [HibiKier/zhenxun_bot#1278]
### 真寻版本：v0.1.6.6
大半年没更新，重新pull后出了问题。。。
_model.py 252行 query = query.filter(Q(cword_scope=2) | Q(word_scope=0))
删了c监听没报错了，但是无法添加词汇
![image](https://user-images.githubusercontent.com/22720994/221221399-1f3ac9f6-94a4-4450-af54-f51017727d2c.png)

**Comment by HibiKier** [comment]
现在应该没了吧
