### ISSUE TITLE
有关EdgeGPT的问题

### ISSUE THREAD

**Issue by Huang1932539** [HibiKier/zhenxun_bot#1279]
大佬有考虑过把EdgeGPT接入真寻吗？我是个小白，跟着EdgeGPT的介绍文档安装好，发现这个可以实现新Bing的功能，希望可以接入真寻，这样可以让真寻变得更智能了（要是没时间就当我没说，同时也希望其他有能力有时间的大佬帮个忙）

**Comment by Einck0** [comment]
不是有chatgpt的插件了吗，差距不大还更稳定
