### ISSUE TITLE
真寻签到报错

### ISSUE THREAD

**Issue by WillyerQ** [HibiKier/zhenxun_bot#1290]
### 错误截图

[img]

### 日志截图

[img]

### 错误说明

在群里发送签到时发生了图里的错误
![32ecabde8fad45c3](https://user-images.githubusercontent.com/126785476/222436585-9d13d4af-4ad4-4cd8-9443-301bdec7a560.jpg)

**Comment by HibiKier** [comment]
更新

**Comment by WillyerQ** [comment]
更新了还是报错

**Comment by HibiKier** [comment]
？你没更新成功吧

**Comment by WillyerQ** [comment]
那要怎么更新？整个文件夹换了？

**Comment by HibiKier** [comment]
换签到文件夹吧
