### ISSUE TITLE
关于手动更新真寻文件

### ISSUE THREAD

**Issue by NathanSummer** [HibiKier/zhenxun_bot#1291]
### 真寻版本：0.1.6.6

直接用仓库里面的最新文件把原来真寻的文件目录（zhenxun_bot-main）全部替换会不会丢什么东西呀？

**Comment by PackageInstaller** [comment]
emm,起码配置文件什么的都没了，得重新配

**Comment by NathanSummer** [comment]
> emm,起码配置文件什么的都没了，得重新配

也就是说用户数据不会丢咩？

**Comment by PackageInstaller** [comment]
数据什么的一般都是在数据库吧（

**Comment by NathanSummer** [comment]
> 数据什么的一般都是在数据库吧（

对哦（恍然大悟

**Comment by NathanSummer** [comment]
![image](https://user-images.githubusercontent.com/88868171/222895344-d8987e50-8223-435d-a4fc-acd5a4872861.png)
我“手动更新”然后把config.py配置好了，其他的也没有乱动，但是现在跑不起来力

**Comment by PackageInstaller** [comment]
这个我记得没有按照新安装来直接导入配置文件就会这样（大概吧）

**Comment by PackageInstaller** [comment]
更新的话还是推荐直接git pull好一些

**Comment by NathanSummer** [comment]
> 这个我记得没有按照新安装来直接导入配置文件就会这样（大概吧）

咦，是按照安装文档来的呀，config也是重新手动配置的，原来是直接下载zip的问题嘛（？

**Comment by PackageInstaller** [comment]
草，我更新了也寄了

**Comment by NathanSummer** [comment]
啊 辣肿么办？

**Comment by PackageInstaller** [comment]
看了下，是配置文件的原因

**Comment by PackageInstaller** [comment]
![image](https://user-images.githubusercontent.com/80018096/222896554-458179d8-3630-444a-867a-c0b52007c5cd.png)
最前面这个以前是postgresql,改成postgres就好了

**Comment by NathanSummer** [comment]
> ![image](https://user-images.githubusercontent.com/80018096/222896554-458179d8-3630-444a-867a-c0b52007c5cd.png) 最前面这个以前是postgresql,改成postgres就好了

挖藕 我试一哈（星星眼

**Comment by NathanSummer** [comment]
有没有一种可能我滴数据库在本地
![image](https://user-images.githubusercontent.com/88868171/222897157-93af492d-59c4-4b60-ace6-bfe1f62c062f.png)

**Comment by PackageInstaller** [comment]
我数据库也在本地啊

**Comment by NathanSummer** [comment]
我这样配置不对嘛？

**Comment by PackageInstaller** [comment]
我直接寄咯（没备份，淦）![image](https://user-images.githubusercontent.com/80018096/222897780-b71491dd-5c3e-4145-8e88-4f2939a1d710.png)

**Comment by NathanSummer** [comment]
> 我直接寄咯（没备份，淦）![image](https://user-images.githubusercontent.com/80018096/222897780-b71491dd-5c3e-4145-8e88-4f2939a1d710.png)

啊这，你这么多额外插件的吗？（看起来好高级

**Comment by NathanSummer** [comment]
不是，那我咋办

**Comment by PackageInstaller** [comment]
额啊，我也不知道了（

**Comment by NathanSummer** [comment]
> ![image](https://user-images.githubusercontent.com/88868171/222895344-d8987e50-8223-435d-a4fc-acd5a4872861.png) 我“手动更新”然后把config.py配置好了，其他的也没有乱动，但是现在跑不起来力

这样的报错有啥可能的原因嘛？

**Comment by PackageInstaller** [comment]
看报错是和数据库有关的，还是等大佬来解决吧

**Comment by NathanSummer** [comment]
> 看报错是和数据库有关的，还是等大佬来解决吧
阿巴阿巴阿巴

**Comment by HibiKier** [comment]
你文件夹没替换全

**Comment by NathanSummer** [comment]
> 你文件夹没替换全

git pull可以吗？

**Comment by NathanSummer** [comment]
![image](https://user-images.githubusercontent.com/88868171/222902861-a7ec3453-5d7b-49a9-9198-ef3644e55738.png)
这样怎么办

**Comment by NathanSummer** [comment]
原来的全删了就好了呜呜呜
