### ISSUE TITLE
更新武器箱报错

### ISSUE THREAD

**Issue by zyima** [HibiKier/zhenxun_bot#1292]
### 真寻版本：0.1.6.6

![open4](https://user-images.githubusercontent.com/66709758/222871727-9c5e0363-1fd5-45ac-82ae-daa650e53048.png)
![open2](https://user-images.githubusercontent.com/66709758/222871635-c21bec85-0146-4428-b411-7b3e22b26975.jpg)
![open3](https://user-images.githubusercontent.com/66709758/222871642-3ad13c78-7936-4744-9640-6ae88f61712a.png)

### 错误说明

一步一步说。
在更新了两天前发布的重写更新箱子后，开箱显示“未收录任何武器箱”(如图1)。尝试更新武器箱，发生了图2的报错。
在将buy_num所在的所有文件的该变量注释掉后，buy_max_price也出现了同样的错误。
在将buy_max_price也注释掉后，更新武器箱发生了KeyError:msg错误(如图3)。
然后我到了issue页下发现了hibikier昨天发布的fix bug，在更新后仍然发生图3的报错。
将先前被注释的buy_num和buy_max_price注释掉后，报错又变回了图2。
不知如何解决。

**Comment by HibiKier** [comment]
把buff_skin表干掉重启，访问失败要么是网络要么是cookie session问题

**Comment by zyima** [comment]
> 把buff_skin表干掉重启，访问失败要么是网络要么是cookie session问题

解决了，是cookie问题。我在查询如何获取cookie的时候，某个回答是在求购页面下获得的cookie，而实际上要在饰品市场页获取cookie。十分感谢hibikier大大！
