### ISSUE TITLE
真寻gocqhttp登录错误

### ISSUE THREAD

**Issue by Kazemiyuu** [HibiKier/zhenxun_bot#1293]
### 错误截图

![`TF R9N02 S6XM5DRO9%LOK](https://user-images.githubusercontent.com/111101842/222915318-a1dd1fe4-8c85-4169-b8f3-d7d5dd2d6035.png)

### 错误说明

用gocqhttp扫码登录时一直提示“你的用户身份已失效，为保证账号安全，请你重新登录”，即使重新打开再登录还是会弹出这个错误

**Comment by Nthing734** [comment]
这玩意你应该去go-cqhttp项目下提issue

**Comment by dong2005923** [comment]
现在gocq仅能使用手表协议
