### ISSUE TITLE
无法运行BOT.PY

### ISSUE THREAD

**Issue by a042979** [HibiKier/zhenxun_bot#1295]
### 错误截图

![image](https://user-images.githubusercontent.com/114063925/222923237-3b39f498-0370-42fe-9b34-f37ad297c911.png)
![image](https://user-images.githubusercontent.com/114063925/222923250-d7e8e0b0-80af-4dfb-94e8-5638809a123b.png)

### 错误说明

运行BOT.PY的时候出现了问题，tortoise这个依赖是安装上了的,不知道是那方面出问题了

**Comment by HibiKier** [comment]
虚拟环境说你没装上

**Comment by a042979** [comment]
> 虛擬環境說你沒裝上
![image](https://user-images.githubusercontent.com/114063925/222951779-db2efa3d-52af-4b21-9505-45743c59ff9e.png)

也就是說要在虛擬環境下安裝依賴?但也是解決不了

**Comment by Sakuracio** [comment]
你的虚拟环境有问题

**Comment by a042979** [comment]
> 你的虚拟环境有问题

那要怎查那里出問題了....

**Comment by Sakuracio** [comment]
重新安装依赖 不行就删了虚拟环境重新安装

**Comment by a042979** [comment]
> 重新安装依赖 不行就删了虚拟环境重新安装

解決了,重裝解決了 THX
