### ISSUE TITLE
ubuntu执行部署命令后 重启系统 无法启动并且也无图形界面

### ISSUE THREAD

**Issue by XiaoYuQiRain** [HibiKier/zhenxun_bot#1298]
### 错误
![M~~U%A66Z7 E}REH0BQBA56](https://user-images.githubusercontent.com/110403748/222956505-497a037e-928e-4679-b620-fad78735126b.png)

### 最后执行的代码
![)RFD2{GKIU~~ EM$48HT3)T](https://user-images.githubusercontent.com/110403748/222956529-535c88c0-b73a-4471-ab37-7a63f431c023.png)

### 错误说明

执行此命令后系统卡死，重启系统后 如图1所示，无法启动图形界面

**Comment by Sakuracio** [comment]
我觉得你需要先解决系统问题

**Comment by XiaoYuQiRain** [comment]
系统是官网下的原版ubuntu，校验过md5，新安装的系统，没有安装其他东西，包括刚刚安装的新的虚拟机也是这个样子，我认为应该不是系统问题

**Comment by Sakuracio** [comment]
playwright的命令你可以不执行 有问题提供报错截图
