### ISSUE TITLE
 cannot import name 'T_CalledAPIHook' from 'nonebot.typing'

### ISSUE THREAD

**Issue by a930389426** [HibiKier/zhenxun_bot#1305]
### 错误截图

![image](https://user-images.githubusercontent.com/59648220/223940483-2862c0ed-4034-44fc-ade9-36f022775eb2.png)

启动失败

**Comment by HibiKier** [comment]
nb2和nb1混装了

**Comment by a930389426** [comment]
哦，我把nb1删了就可以了，谢谢
