### ISSUE TITLE
关于pix的问题

### ISSUE THREAD

**Issue by dong2005923** [HibiKier/zhenxun_bot#1306]
![{GD$32T 3738_CBWZTFWMFY](https://user-images.githubusercontent.com/109427426/224489850-5a2ec14b-598d-465e-afb3-7406160a3222.png)
我观看文档后，发现是需要放置数据库？
![`HQMNS9MCUI~9}TS{R0%Y4I](https://user-images.githubusercontent.com/109427426/224489928-42997f66-f4e8-4cce-b4d9-397c9c8687c3.png)
能否出一个教程辅助进行放置与配置，不胜感激！

**Comment by HibiKier** [comment]
把数据库sql文件放在bot.py同级目录
