### ISSUE TITLE
Docker全量版登录错误

### ISSUE THREAD

**Issue by NathanSummer** [HibiKier/zhenxun_bot#1307]
### 日志截图

![capture_20230312083223855](https://user-images.githubusercontent.com/88868171/224517849-ad3a30aa-680a-48cd-bac8-7e3bacb1ade4.jpg)

### 错误说明

gocq发生了登录错误

**Comment by PackageInstaller** [comment]
修改device.json中"protocol"参数成2（原本应该是5）

**Comment by NathanSummer** [comment]
> 修改device.json中"protocol"参数成2（原本应该是5）

话说在哪里改（汗

**Comment by PackageInstaller** [comment]
go-cqhttp中

**Comment by NathanSummer** [comment]
> go-cqhttp目录下的device.json

可是它不是在容器里面嘛？

**Comment by PackageInstaller** [comment]
那就不清楚了，我没用过docker

**Comment by NathanSummer** [comment]
> 那就不清楚了，我没用过docker

呜呜呜我也不会
