### ISSUE TITLE
真寻运行报错

### ISSUE THREAD

**Issue by INSide-734** [HibiKier/zhenxun_bot#1308]
### 日志截图
![$BF_J(T9PM79{H7`{I48$9](https://user-images.githubusercontent.com/109641391/224535456-a4d7cf01-56de-4210-be15-38ab73e200ad.png)
![3L0WW%AAKF42 YCTXPNL6M1](https://user-images.githubusercontent.com/109641391/224535486-abc997b4-4355-415c-8d6a-a5454e2f2502.png)

**Comment by HibiKier** [comment]
更新
