### ISSUE TITLE
求问图库改名该怎么改，我在config.yaml里改了后重启会直接被改回来

### ISSUE THREAD

**Issue by velvetbibeak** [HibiKier/zhenxun_bot#1309]
[](url)### 系统版本：Ubuntu 20.04
### 真寻版本：0.1.5.3

[想改成如图效果](![Y{PJD $9_A3CU$8PHF)BJ`8](https://user-images.githubusercontent.com/127666043/224545591-3c589b2b-9afc-4549-81c8-55404f61a4d9.png))

**Comment by HibiKier** [comment]
不会吧，怎么改的

**Comment by velvetbibeak** [comment]
> 不会吧，怎么改的

我也奇怪哇，最初在吹水群里的，就那个 是真寻酱哒 里看到的，自己也想改但是改不了诶

**Comment by HibiKier** [comment]
你配置文件怎么改的

**Comment by velvetbibeak** [comment]
> 你配置文件怎么改的

data/configs/config.yaml 里直接更改蓝框里的名字并保存，然后重启真寻再打开config.yaml会重新变成图示的这三个名字
![屏幕截图 2023-03-13 082251](https://user-images.githubusercontent.com/127666043/224645818-63c686f8-0f6a-4bf5-ab1c-3ee4369743b0.jpg)
