### ISSUE TITLE
更新武器箱时，JSON解析错误

### ISSUE THREAD

**Issue by grasstractor** [HibiKier/zhenxun_bot#1311]
### 错误截图

<img width="773" alt="image" src="https://user-images.githubusercontent.com/12790465/224604647-15907503-2c71-455d-af37-532e57f5cb10.png">

![89d1ffa90b8b4515b0328fa211661062](https://user-images.githubusercontent.com/12790465/224604808-515b04fd-1732-4e2b-956d-caa72d6001c8.png)
![image](https://user-images.githubusercontent.com/12790465/224604827-15088ca5-a1dd-4a13-a84e-a9569b221e34.png)

### 日志截图

[img]

### 错误说明

更新武器箱出错，配置了cookie，提示JSON解析错误，python3.9.5

**Comment by grasstractor** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/12790465/224605871-07cacdc1-b99b-460e-b5b6-d031acfc3a4c.png">
使用curl尝试访问buff主页 直接提示403

**Comment by HibiKier** [comment]
试试加代理BUFF_PROXY

**Comment by grasstractor** [comment]
> 试试加代理BUFF_PROXY

加什么类型的代理啊？socks5可以吗？ 127.0.0.1:12345的形式吗？

**Comment by HibiKier** [comment]
你要保证自己的网络可以访问到buff，网上随便找点代理就行了，不用翻墙

**Comment by grasstractor** [comment]
> 

我有socks5/HTTP/HTTPS的代理 这个代理需要哪一种类型的呢？输入格式是什么样的？

**Comment by HibiKier** [comment]
先更新后开debug看看日志

**Comment by zyima** [comment]
填请求标头的cookie，不是响应标头的...

**Comment by grasstractor** [comment]
> 填请求标头的cookie，不是响应标头的...

感谢 更改之后又挂了HTTP代理 好了
