### ISSUE TITLE
poetry install时报错

### ISSUE THREAD

**Issue by AliksFan** [HibiKier/zhenxun_bot#1313]
### 错误截图

[img]
![image](https://user-images.githubusercontent.com/95276472/224700790-5e315fcf-8783-402a-b63f-128140ac6b0c.png)
![image](https://user-images.githubusercontent.com/95276472/224701003-518e6352-a50b-4a2a-9719-a197777a7db1.png)

### 错误说明
重启过，python时3.9，重装过poetry，删除过poetry.lock都没有解决

**Comment by unknownpop** [comment]
+1

**Comment by eeeachan27** [comment]
+1

**Comment by HibiKier** [comment]
py啥版本

**Comment by AliksFan** [comment]
> py啥版本

3.9，我后来装的1.6.4，scipy的版本是1.9.1，可以用
