### ISSUE TITLE
签到图片：进度条反向

### ISSUE THREAD

**Issue by MWTJC** [HibiKier/zhenxun_bot#1314]
### 错误截图

![image](https://user-images.githubusercontent.com/74529082/224873274-8d5cbb6c-3e4b-4cc1-a5e2-c01eefec7aaf.png)

### 日志截图

![image](https://user-images.githubusercontent.com/74529082/224873768-2fa613c0-b803-4686-9727-42dae17c1009.png)
![image](https://user-images.githubusercontent.com/74529082/224873767-add77c0e-24bf-45ca-9e9d-f438cbf45a6a.png)

### 错误说明

是昨天从release0.1.6.6版自动更新到的release0.1.6.7版，但这签到进度条不晓得为何反过来了，日志内并无异常，想问下这可能是哪方面引起的问题…

**Comment by HibiKier** [comment]
f8371e733029d5d01d36536dd05f13e5a4d8e999

**Comment by MWTJC** [comment]
谢大佬，下载最新源码已解决。
另，对应commit似乎应为
379a689ebcf4f1280c749513b7e92338386ae6b6
