### ISSUE TITLE
色图插件发送本地色图时会在消息中多发一张同样的

### ISSUE THREAD

**Issue by Glospred** [HibiKier/zhenxun_bot#1316]
### 错误截图

![Screenshot_20230314-144252](https://user-images.githubusercontent.com/103896688/224919154-ca6bdd8d-8e20-4fce-9304-0c1c347f1852.png)

### 错误说明

如图，问题仅在输出本地色图时出现

**Comment by Erlla** [comment]
我也出现过

**Comment by lioshushu** [comment]
我找到原因了，是这个判断导致的问题，但我不知道怎么改，索性把_path注释掉了
![image](https://user-images.githubusercontent.com/48851662/225389476-8309388d-ee4e-446b-b801-f81890921ce7.png)
![image](https://user-images.githubusercontent.com/48851662/225389803-cf7bc620-b1d1-4581-a2a4-c34e05034c37.png)

**Comment by YuS1aN** [comment]
> 我找到原因了，是这个判断导致的问题，但我不知道怎么改，索性把_path注释掉了 ![image](https://user-images.githubusercontent.com/48851662/225389476-8309388d-ee4e-446b-b801-f81890921ce7.png) ![image](https://user-images.githubusercontent.com/48851662/225389803-cf7bc620-b1d1-4581-a2a4-c34e05034c37.png)
> 
> 过了一天，发现注释也不能解决问题，变成群聊一张都发不出，私聊发一张了

`data_source.py -> gen_message`  把最后面拼接的两个 image(image_path) 删掉 / 改成空字符串就行。
