### ISSUE TITLE
查看武器箱无回应报错，但更新武器箱与开箱正常

### ISSUE THREAD

**Issue by MWTJC** [HibiKier/zhenxun_bot#1318]
### 错误截图

无回应报错，仅有日志报错

### 日志截图

![image](https://user-images.githubusercontent.com/74529082/224989625-986ec9c6-6761-4812-9082-e51395ae06b1.png)

### 错误说明

从release0.1.6.6自动更新到release0.1.6.7后，遵照md更新日志，尝试添加cookie后使用新增功能，发现“查看武器箱”无法使用，第一次是报`No such file or directory: 'resources/image/csgo_cases/_background/shu'`的错，自行新建后，报错变成上图所示`IndexError: list index out of range`，但与此同时，开箱正常，更新武器箱也能显示各箱的更新状态。

**Comment by HibiKier** [comment]
更新

**Comment by MWTJC** [comment]
谢大佬，下载最新源码已解决。
