### ISSUE TITLE
添加词库报错捏

### ISSUE THREAD

**Issue by smallka1** [HibiKier/zhenxun_bot#1319]
### 错误截图
![image](https://user-images.githubusercontent.com/108041850/225009015-2103bb2e-ba02-4730-b2d4-f8f990e7a727.png)

### 日志截图

[img]

### 错误说明

添加词库发生了错误

**Comment by ayakasuki** [comment]
![image](https://user-images.githubusercontent.com/20859971/226121201-35ab70e3-359e-4d92-8c0a-f1c25571798c.png)
确实 同日志报错

**Comment by ayakasuki** [comment]
![image](https://user-images.githubusercontent.com/20859971/226121201-35ab70e3-359e-4d92-8c0a-f1c25571798c.png)
确实 同日志报错

**Comment by HibiKier** [comment]
fb04f7fffb3a49a496085451f4b710f58ecd4ab4
