### ISSUE TITLE
无法启动机器人

### ISSUE THREAD

**Issue by LTorch** [HibiKier/zhenxun_bot#132]
环境centos python3.9.6
![image](https://user-images.githubusercontent.com/101314685/157620189-5fb61a71-dfe7-418d-8357-f4126a4da476.png)

poetry安装依赖
![image](https://user-images.githubusercontent.com/101314685/157621780-9414811c-08d2-486f-a322-9a06ffa3d9d8.png)
![image](https://user-images.githubusercontent.com/101314685/157621842-b6139d4d-a0de-422d-8d22-d21673fb159b.png)

playwright 已安装 chromium

日志
[日志.log](https://github.com/HibiKier/zhenxun_bot/files/8221907/default.log)

**Comment by LTorch** [comment]
[日志.log](https://github.com/HibiKier/zhenxun_bot/files/8221916/default.log)

**Comment by HibiKier** [comment]
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
缺环境，百度安装libGL.so.1

**Comment by LTorch** [comment]
已解决，感谢作者！
