### ISSUE TITLE
武器箱更新失败

### ISSUE THREAD

**Issue by imxianyu21** [HibiKier/zhenxun_bot#1320]
### 错误截图

[img]
![Screenshot_20230315-114134_JuiceSSH](https://user-images.githubusercontent.com/110275302/225200458-08b30e27-ee16-46b7-9668-4786fee17ce9.png)

### 日志截图

[img]
![IMG_20230315_114213](https://user-images.githubusercontent.com/110275302/225200557-35ff9cfd-5fcb-46c9-bb30-ee9de74a608d.jpg)

### 错误说明

发生了武器箱更新失败， 错误：
 <class 'json.decoder.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)

**Comment by imxianyu21** [comment]
![Uploading IMG_20230315_114032.jpg…]()

**Comment by imxianyu21** [comment]
![IMG_20230315_114032](https://user-images.githubusercontent.com/110275302/225200963-fbb7c4a6-2c6e-4365-92f5-e24d4c6c7c78.jpg)

**Comment by HibiKier** [comment]
更新一下开debug看看日志

**Comment by zyima** [comment]
cookie是这么短的么...为啥我的一大段，然后之前配错cookie了也是更新不了武器箱。你看看打开BUFF，进到CSGO饰品市场，打开F12刷新一下，在网络的请求标头哪里，用那个cookie试试

**Comment by imxianyu21** [comment]
> 

长的吗，我试试看

**Comment by imxianyu21** [comment]
/

> 

我进行了尝试，但它仍然不工作，我想看看你的cookie(隐私部分请注意打码，只是看看你的cookie是什么格式的)是否和我一样

**Comment by imxianyu21** [comment]
> cookie是这么短的么...为啥我的一大段，然后之前配错cookie了也是更新不了武器箱。你看看打开BUFF，进到CSGO饰品市场，打开F12刷新一下，在网络的请求标头哪里，用那个cookie试试



> cookie是这么短的么...为啥我的一大段，然后之前配错cookie了也是更新不了武器箱。你看看打开BUFF，进到CSGO饰品市场，打开F12刷新一下，在网络的请求标头哪里，用那个cookie试试

我进行了尝试，但它仍然不工作，我想看看你的cookie(隐私部分请注意打码，只是看看你的cookie是什么格式的)是否和我一样

**Comment by zyima** [comment]
> > cookie是这么短的么...为啥我的一大段，然后之前配错cookie了也是更新不了武器箱。你看看打开BUFF，进到CSGO饰品市场，打开F12刷新一下，在网络的请求标头哪里，用那个cookie试试
> 
> 我进行了尝试，但它仍然不工作，我想看看你的cookie(隐私部分请注意打码，只是看看你的cookie是什么格式的)是否和我一样

![CC6CA8F457C02B35D624A9A8854C1C08](https://user-images.githubusercontent.com/66709758/226116034-f7e54da2-94f4-42f2-81e5-8844f5b8b4fd.jpg)

**Comment by imxianyu21** [comment]
> > > cookie是这么短的么...为啥我的一大段，然后之前配错cookie了也是更新不了武器箱。你看看打开BUFF，进到CSGO饰品市场，打开F12刷新一下，在网络的请求标头哪里，用那个cookie试试
> > 
> > 
> > 我进行了尝试，但它仍然不工作，我想看看你的cookie(隐私部分请注意打码，只是看看你的cookie是什么格式的)是否和我一样
> 
> ![CC6CA8F457C02B35D624A9A8854C1C08](https://user-images.githubusercontent.com/66709758/226116034-f7e54da2-94f4-42f2-81e5-8844f5b8b4fd.jpg)

感谢，现在正常了
