### ISSUE TITLE
自定义群欢迎消息报错

### ISSUE THREAD

**Issue by molanp** [HibiKier/zhenxun_bot#1322]
### 错误截图

![-424f5355dca9919f](https://user-images.githubusercontent.com/104612722/225341525-f1556208-56ea-4526-a1a2-999705a77bda.jpg)

### 日志截图

![-424f5355dca9919f](https://user-images.githubusercontent.com/104612722/225341525-f1556208-56ea-4526-a1a2-999705a77bda.jpg)

### 错误说明

发生了未知错误...

**Comment by HibiKier** [comment]
你是自己改过custom_welcome_msg.json文件了吗

**Comment by molanp** [comment]
> 你是自己改过custom_welcome_msg.json文件了吗

没有做任何修改

**Comment by molanp** [comment]
之前服务器有一次异常关机，会导致这个问题吗

**Comment by molanp** [comment]
目前查看该文件内容为空，如何修复该文件？

**Comment by molanp** [comment]
文件输入`{}`修复成功
# 建议

对此文件增加备份功能
