### ISSUE TITLE
未收录武器箱？

### ISSUE THREAD

**Issue by zzbo777** [HibiKier/zhenxun_bot#1327]
发送开箱，机器人回答未收录武器箱，后台也没有报错

**Comment by zzbo777** [comment]
![F5966BB0-B9A4-4C23-994F-295BD619D12E](https://user-images.githubusercontent.com/59078736/226075941-ca6833e5-6e15-4299-8989-91547a1c578f.jpeg)

**Comment by zzbo777** [comment]
现在开箱都需要填cookie了吗，以前啥都不用填的吧

**Comment by zyima** [comment]
> 现在开箱都需要填cookie了吗，以前啥都不用填的吧

要填cookie的，你到饰品市场复制cookie，填入配置文件就可以了

**Comment by zzbo777** [comment]
昨晚更新过全部武器箱
![Uploading 3F2E6936-BAF5-4328-8D02-44FC070F914D.png…]()

**Comment by zzbo777** [comment]
> 

好的我去试试

**Comment by elastichow** [comment]
cookie是哪个，很长的那个吗
