### ISSUE TITLE
0.1.6.7版本更新后出现问题

### ISSUE THREAD

**Issue by Saddle19** [HibiKier/zhenxun_bot#1328]
### 错误截图
![image](https://user-images.githubusercontent.com/85019741/226168447-56aa2f1f-f64d-4398-a6b4-9eb675610ddf.png)

### 错误说明

再issue上看到了一篇类似的问题，但是我使用的docker部署好像没办法进入到容器更新依赖。启动之后进入容器来不及更新依赖就会宕掉。这种情况我可以手动安装好tortoise使用docker cp复制到容器内吗？应该怎么操作。

**Comment by tanzhi77** [comment]
bot.py加延时，然后进容器更新依赖，我的笨比方法
`import time
time.sleep(100000)`
