### ISSUE TITLE
B站转发解析报错401

### ISSUE THREAD

**Issue by mxk736850509** [HibiKier/zhenxun_bot#1332]
### 错误截图

![QQ](https://user-images.githubusercontent.com/39251155/227689041-ed9a3d3a-259b-4e16-afc8-8696fbe64e66.png)

### 日志截图

![cmd](https://user-images.githubusercontent.com/39251155/227690429-42cd8913-c689-4f96-80f1-31cb77cadea6.png)

![QQ截图20230325110419](https://user-images.githubusercontent.com/39251155/227688966-de9129dc-2d5e-4111-b207-c4ad2c79391c.png)

### 错误说明

昨天突然就出现401了，升级bilireq后依旧报错，删除订阅后重新添加也是报错，网络是正常的

**Comment by Kuro96** [comment]
遇到了同样的问题，不知道是否和https://github.com/RayWangQvQ/BiliBiliToolPro/issues/260#issuecomment-1345486230中的情况一致

**Comment by Kuro96** [comment]
尝试更新bilireq到0.2.4问题解决，猜测是api有变化
pip douban源暂无最新版本，换官方源可安装：
`pip install bilireq==0.2.4 -i https://pypi.python.org/simple`

**Comment by mxk736850509** [comment]
> 尝试更新bilireq到0.2.4问题解决，猜测是api有变化 pip douban源暂无最新版本，换官方源可安装： `pip install bilireq==0.2.4 -i https://pypi.python.org/simple`

升级后还是401
![升级后QQ](https://user-images.githubusercontent.com/39251155/227907207-30bafede-1397-45bd-94a5-73a35eba7ef6.png)
![升级后cmd](https://user-images.githubusercontent.com/39251155/227907221-2f7e5e52-a781-415a-9593-9bf6308241cd.png)

**Comment by yjywybb** [comment]
相同错误，bilireq 版本 0.2.4， 真寻版本 0.1.6.7

**Comment by Orwell-Yu** [comment]
一样，bilireq  0.2.4， 真寻 0.1.6.7...十分怀疑叔叔今天是不是又换新的api了

**Comment by lad-coder** [comment]
找一下lib/site-packages/bilireq/utils/__init__.py 这个文件 然后把请求头的user-agent换一下

**Comment by lad-coder** [comment]
找一下lib/site-packages/bilireq/utils/__init__.py 这个文件 然后把请求头的user-agent换一下
![C@Y803T1 L7KUEN(7DAKQ_Q](https://user-images.githubusercontent.com/50281356/228189295-b3111643-c05e-4ccf-a996-52a9df79f11e.png)

**Comment by mxk736850509** [comment]
> 找一下lib/site-packages/bilireq/utils/**init**.py 这个文件 然后把请求头的user-agent换一下 ![C@Y803T1 L7KUEN(7DAKQ_Q](https://user-images.githubusercontent.com/50281356/228189295-b3111643-c05e-4ccf-a996-52a9df79f11e.png)

改完解决了
谢谢带佬

**Comment by yjywybb** [comment]
![image](https://user-images.githubusercontent.com/18324677/228225095-183ce19b-2621-401f-8c57-e314cb536c7a.png)
修改后仍旧报错…

**Comment by lad-coder** [comment]
> ![image](https://user-images.githubusercontent.com/18324677/228225095-183ce19b-2621-401f-8c57-e314cb536c7a.png) 修改后仍旧报错…

换一个其他的user-agent  还是报错那就不是这个api出的问题 你可以在排查一下你的问题是哪个api出的

**Comment by mxk736850509** [comment]
> ![image](https://user-images.githubusercontent.com/18324677/228225095-183ce19b-2621-401f-8c57-e314cb536c7a.png) 修改后仍旧报错…

不知对你有没有用，我是这样该的
![QQ截图20230328194432](https://user-images.githubusercontent.com/39251155/228225967-2eceaa7a-5675-466b-8bc7-eed43cc4085f.png)

**Comment by lad-coder** [comment]
> > ![image](https://user-images.githubusercontent.com/18324677/228225095-183ce19b-2621-401f-8c57-e314cb536c7a.png) 修改后仍旧报错…
> 
> 不知对你有没有用，我是这样该的 ![QQ截图20230328194432](https://user-images.githubusercontent.com/39251155/228225967-2eceaa7a-5675-466b-8bc7-eed43cc4085f.png)

我用apipost测了一下 好像可以删除这个user-agent
![image](https://user-images.githubusercontent.com/50281356/228227638-7d8367b8-781f-406a-99b0-00d20961b6c8.png)

**Comment by yjywybb** [comment]
感觉不像是ua的问题…？改成啥样都一样报错（

**Comment by Emperor-Xian** [comment]
> > ![image](https://user-images.githubusercontent.com/18324677/228225095-183ce19b-2621-401f-8c57-e314cb536c7a.png) 修改后仍旧报错…
> 
> 换一个其他的user-agent 还是报错那就不是这个api出的问题 你可以在排查一下你的问题是哪个api出的

你这个改的位置不对
真寻使用的python环境不是系统环境，而是poetry隔离出来的虚拟环境，你要改文件应该跑到虚拟环境的文件夹下找到对应文件修改
具体那个文件夹可以在真寻的根目录下运行poetry env info --path命令查看
我刚刚就这么改的，然后成功了

**Comment by Emperor-Xian** [comment]
> 感觉不像是ua的问题…？改成啥样都一样报错（

刚刚没回复正确，现在重新回复下吧。别人家不知道……

**Comment by SK-415** [comment]
![image](https://user-images.githubusercontent.com/36433929/228280803-38ae0b34-11c7-490e-9925-1453991b82d1.png)
![image](https://user-images.githubusercontent.com/36433929/228280984-7fb9fcc3-0dc6-446b-bc81-dc278ee19eb3.png)

我这边无法复现，根据历史经验，遇到 `-401` 是 B 站在更新鉴权规则，可能是各地的服务器需要时间同步，所以每个人的请求结果会不一样。一般过个几天，大部分人都会遇到 `-401`，等 `-401` 能稳定复现的时候再研究鉴权多了什么东西，比如上一次是必须要附带 bilibili.com 主页的 cookies。
