### ISSUE TITLE
查看武器箱&开启更新后的武器箱报错

### ISSUE THREAD

**Issue by zyima** [HibiKier/zhenxun_bot#1333]
### 错误说明

真寻0.1.6.6版本， 今天下午更新了最新的开箱代码(3.25)，查看任何武器箱时都报错(包括单纯的查看武器箱)，如图一。在更新完武器箱后，显示新创建皮肤(如图二)，然而该武器箱之前就已经有皮肤的了。开启该武器箱，发生报错，如图三。开其他箱子是正常的。
![1](https://user-images.githubusercontent.com/66709758/227715528-d63f07da-edf5-4c89-b06d-1fcf67297000.png)
![2](https://user-images.githubusercontent.com/66709758/227715532-097ca07b-16f9-43f4-bbed-944df1c40eb1.png)
![3](https://user-images.githubusercontent.com/66709758/227715536-faefbac6-d6e4-487b-b423-ab47a2690fa6.png)

**Comment by zyima** [comment]
补充。在更新了代码后，首先进行了指令：更新皮肤蝴蝶刀。bot回复更新成功，之后想查看武器箱时发现了上述问题。

**Comment by HibiKier** [comment]
有个武器箱重复了吧

**Comment by HibiKier** [comment]
在数据库里删了试试

**Comment by zyima** [comment]
> 在数据库里删了试试

我干掉了buff_skin和buff_skin_log里的内容，然后重新更新，发生了如下报错
![87601YXW 6$)F}W2HRZK V](https://user-images.githubusercontent.com/66709758/227749201-84fca2fb-035b-4dec-9636-6e7e4ca4bb4a.png)
![M`HCH10VXP(80T2ESY$6)FW](https://user-images.githubusercontent.com/66709758/227749210-5d723489-e4e6-4101-bf0d-deee642c21b7.png)

**Comment by HibiKier** [comment]
重复是因为之前没有加skin_id，然后更新了skin_id字段导致的，建议把skin_id为空的全部删除，上面这个问题也更新了

**Comment by zyima** [comment]
> 重复是因为之前没有加skin_id，然后更新了skin_id字段导致的，建议把skin_id为空的全部删除，上面这个问题也更新了

正常了，阿咪辛苦了
