### ISSUE TITLE
发送help报错

### ISSUE THREAD

**Issue by INSide-734** [HibiKier/zhenxun_bot#1334]
### 日志截图

![Screenshot_2023-03-26-01-27-06-39_2665fb67b16260a8d818298cef8dc107.jpg](https://user-images.githubusercontent.com/109641391/227732481-3af50952-7b36-4448-bfa8-c1c457f67c6b.jpg)

### 错误说明

无法获取help图片

**Comment by HibiKier** [comment]
超时了
