### ISSUE TITLE
执行poetry install时出现错误[RecursionError] 

### ISSUE THREAD

**Issue by 147graze** [HibiKier/zhenxun_bot#1336]
### 错误截图

![QQ图片20230327230821](https://user-images.githubusercontent.com/126667762/227982774-2e4c1ebe-5fd9-4ab9-b9c8-01456f7e1dc3.png)

### 错误说明

执行poetry install时出现错误

**Comment by PackageInstaller** [comment]
试试升级 Poetry update，重新生成锁定文件
