### ISSUE TITLE
检查更新真寻报错

### ISSUE THREAD

**Issue by lihaojie87** [HibiKier/zhenxun_bot#134]
使用检查更新真寻指令报错

检测真寻已更新，当前版本：v0.1.4.3，最新版本：v0.1.4.4
开始更新.....

更新真寻未知错误 <class 'tarfile.ReadError'>：file could not be opened successfully

应该怎么样更新真寻呢

**Comment by Sakuracio** [comment]
（手动更

**Comment by HibiKier** [comment]
保留data和resource，其他都可以替换
