### ISSUE TITLE
无法发送语音

### ISSUE THREAD

**Issue by NathanSummer** [HibiKier/zhenxun_bot#1341]
### 错误截图

![微信图片_20230330230445](https://user-images.githubusercontent.com/88868171/228882148-479de649-cd30-44dd-8706-eec8143ddae8.jpg)

### 日志截图

![image](https://user-images.githubusercontent.com/88868171/228882480-8edb5f27-a7ca-4996-9e39-a2f827a6bc2a.png)

![image](https://user-images.githubusercontent.com/88868171/228882658-c4f25e3d-5dc6-4372-89f3-f2cde6b9a268.png)

**Comment by PackageInstaller** [comment]
你需要安装ffmpeg

`sudo apt-get install ffmpeg`

**Comment by NathanSummer** [comment]
> 你需要安装ffmpeg
> 
> `sudo apt-get install ffmpeg`（这是Ubuntu的，其他发行版换换包管理器名即可）

欸，我以为poetry.lock里面都有呢

**Comment by PackageInstaller** [comment]
> > 你需要安装ffmpeg
> > `sudo apt-get install ffmpeg`（这是Ubuntu的，其他发行版换换包管理器名即可）
> 
> 欸，我以为poetry.lock里面都有呢

你用的是无gui的吧，我记得不会默认安装这个，需要手动安装，总之你先试试吧

**Comment by NathanSummer** [comment]
要添加到环境变量吗？

**Comment by PackageInstaller** [comment]
一般来说安装后会自己加进环境变量中。你在安装好后有重启bot嘛，如果是重启后出现的这个warning,那就加环境变量吧（ffmpeg安装位置你可以谷歌下）

**Comment by NathanSummer** [comment]
> 一般来说安装后会自己加进环境变量中。你在安装好后有重启bot和go-cqhttp嘛，如果是重启后出现的这个warning,那就加环境变量吧（ffmpeg安装位置你可以谷歌下）

确实重启了，看来要手动添加了
