### ISSUE TITLE
字段: “is_passive” 不存在

### ISSUE THREAD

**Issue by Terli** [HibiKier/zhenxun_bot#1342]
### 错误截图
![1](https://user-images.githubusercontent.com/39787342/228924949-bb875c2f-dd6d-44f2-8806-3a3ac03cd9da.png)

![2](https://user-images.githubusercontent.com/39787342/228924909-15c25214-51d2-4382-a59c-c23d30b93bdb.png)

### 错误说明
今天在Releases下载0.1.6.7并解压安装，出现了该错误，在使用购买道具时会卡主进程无法使用，老版本未遇到过该问题

发生了字段: “is_passive” 不存在错误...

**Comment by HibiKier** [comment]
198386e500775875cfc1dc8ecb7cf67d1dc94ff4
