### ISSUE TITLE
登记的武器箱出现重复

### ISSUE THREAD

**Issue by a930389426** [HibiKier/zhenxun_bot#1344]
![2678283772-1935571672-FA675D4716C5D294EDAC5496A27733A0](https://user-images.githubusercontent.com/59648220/229030623-ce651938-1d12-4d8a-82c3-da15a0e513c9.png)
如果抽取出现重复的武器箱，则报错
![image](https://user-images.githubusercontent.com/59648220/229030797-0eff0c1b-443b-43da-b5d9-93f9d7eba629.png)

**Comment by a930389426** [comment]
![image](https://user-images.githubusercontent.com/59648220/229030896-79739e96-3360-46ef-8940-399d96b06649.png)

**Comment by HibiKier** [comment]
更新到最新的代码并将数据库中skin_id为空的数据都删除

**Comment by a930389426** [comment]
> 更新到最新的代码并将数据库中skin_id为空的数据都删除

是buff_skin这个表吗？里面没有skin_id为空的数据

**Comment by a930389426** [comment]
![image](https://user-images.githubusercontent.com/59648220/229065622-77bc326a-3be9-49cc-8d16-2eab4a2efb0b.png)
我可以确认，这里没有空着的数据

**Comment by a930389426** [comment]
![image](https://user-images.githubusercontent.com/59648220/229067771-a4579a0e-d78d-4886-b5e3-9ea9dd04f705.png)
![image](https://user-images.githubusercontent.com/59648220/229067872-19dc1a1d-a126-497e-90ba-b920e312ee2a.png)
看了一段时间发现数据库中存在两条除了ID一摸一样的数据，而有一些并没有，是不是意味着我要直接删除重复武器箱的所有数据重新更新该武器箱才能解决问题？

**Comment by a930389426** [comment]
已解决，将出现重复的武器箱的所有数据删除，再重新更新武器箱即可
