### ISSUE TITLE
webui出错

### ISSUE THREAD

**Issue by ayakasuki** [HibiKier/zhenxun_bot#1345]
### 错误截图

[img]

### 日志截图
![image](https://user-images.githubusercontent.com/20859971/229257824-2fa367fa-4b4a-40c2-afe3-0ad6a081273b.png)

[img]

### 错误说明

git pull最新代码后，web_ui出现AttributeError: 'Depends' object has no attribute 'rsplit'

**Comment by HibiKier** [comment]
webui在重写

**Comment by ayakasuki** [comment]
> webui在重写

新git pull的webui 群聊还是有问题
![image](https://user-images.githubusercontent.com/20859971/229659649-6d181c2a-1ddd-451a-b4de-1538f2f5d68e.png)
![image](https://user-images.githubusercontent.com/20859971/229659709-07a70a72-3510-42df-8891-b905efafa323.png)

**Comment by MobiusT** [comment]
能否告知下nonebot2的版本呢
