### ISSUE TITLE
添加群认证 回复 以下群聊不合法或不存在:

### ISSUE THREAD

**Issue by gagadaxiao** [HibiKier/zhenxun_bot#1347]
04-01 19:06:12 [SUCCESS] nonebot | OneBot V11 3289526897 | [message.private.friend]: Message -1108297222 from 529819010 '添加群认证 1034439737'
04-01 19:06:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
04-01 19:06:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
04-01 19:06:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
04-01 19:06:12 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
04-01 19:06:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.super_cmd.manager_group)
04-01 19:06:12 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
04-01 19:06:12 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
04-01 19:06:12 [INFO] nonebot | Matcher(type='message', module=basic_plugins.super_cmd.manager_group) running complete

**Comment by HibiKier** [comment]
更新
