### ISSUE TITLE
ban功能出现问题

### ISSUE THREAD

**Issue by NathanSummer** [HibiKier/zhenxun_bot#1348]
### 日志截图

![image](https://user-images.githubusercontent.com/88868171/229328049-4239360d-066c-4eae-b080-c9a7fc113e2e.png)
![image](https://user-images.githubusercontent.com/88868171/229328060-bf464b73-2b2e-4d67-acfe-b4ec35067e7e.png)

### 错误说明

本来重复说同一句话应该是自动ban该用户X秒，但是没有回复而且报错了

**Comment by NathanSummer** [comment]
普通的ban指令也同样报错
![image](https://user-images.githubusercontent.com/88868171/229328198-4f5f066d-6876-4ef2-b107-708647c14aa3.png)
![image](https://user-images.githubusercontent.com/88868171/229328209-14911bad-0873-4873-85f3-f7503560ec59.png)

**Comment by PackageInstaller** [comment]
这个报错是用户的qq号长度超出int上限了

**Comment by NathanSummer** [comment]
> 这个报错是用户的qq号长度超出int上限了

？那肿么办

**Comment by HibiKier** [comment]
用户qq号是多少

**Comment by HibiKier** [comment]
用户qq号是几位

**Comment by HibiKier** [comment]
？怎么会超出呢，是可以存的啊，试试把ban_users表删了重启？
![图片](https://user-images.githubusercontent.com/45528451/229491344-5ab56e0a-92be-4c11-8eeb-c3bbb0899871.png)
![图片](https://user-images.githubusercontent.com/45528451/229491460-729ef3c5-9113-4a6f-bc54-a24a74ee69a6.png)

**Comment by NathanSummer** [comment]
> ？怎么会超出呢，是可以存的啊，试试把ban_users表删了重启？ ![图片](https://user-images.githubusercontent.com/45528451/229491344-5ab56e0a-92be-4c11-8eeb-c3bbb0899871.png) ![图片](https://user-images.githubusercontent.com/45528451/229491460-729ef3c5-9113-4a6f-bc54-a24a74ee69a6.png)

辣个表在哪里鸭？

**Comment by INSide-734** [comment]
报错+1

**Comment by HibiKier** [comment]
有其他插件吗，可以先试试不加载其他插件再试一下

**Comment by NathanSummer** [comment]
> 有其他插件吗，可以先试试不加载其他插件再试一下

没有外加插件

**Comment by yajiwa** [comment]
私聊真寻发送`exec ALTER TABLE ban_users ALTER COLUMN user_id TYPE bigint;`应该能解决

**Comment by NathanSummer** [comment]
> 私聊真寻发送`exec ALTER TABLE ban_users ALTER COLUMN user_qq TYPE bigint;`应该能解决

3Q （鞠躬
