### ISSUE TITLE
添加词条功能的答案部分无法正确输出问题部分匹配的捕获组

### ISSUE THREAD

**Issue by Shir0na** [HibiKier/zhenxun_bot#1349]
### 错误截图

![图片](https://user-images.githubusercontent.com/129878627/229843564-c3023c61-6ab9-4b51-ad26-afd67ca43ef0.png)

### 日志截图

暂无

### 错误说明

在问题中用(.+)正则匹配字符串，在答案部分用\1  \\1   $1  \$1都无法正确输出。
询问管理员，管理员说没有该功能，可以提交issue。

**Comment by HibiKier** [comment]
6eebb8229feb2ec9f1fc6c750bc12307ef3ad681
