### ISSUE TITLE
关于真寻自带的cos插件

### ISSUE THREAD

**Issue by WillyerQ** [HibiKier/zhenxun_bot#1351]
### 真寻版本：0.1.6.7

我想问下怎么给这个插件单独设置代理

**Comment by HibiKier** [comment]
config.py可以给真寻所有插件设置代理，单独的话要改代码

**Comment by INSide-734** [comment]
# 代理，例如 "http://127.0.0.1:7890"
# 如果是WLS 可以 f"http://{hostip}:7890" 使用寄主机的代理

**Comment by WillyerQ** [comment]
请问代理地址填在哪里

**Comment by WillyerQ** [comment]
搞好了，谢谢大佬
