### ISSUE TITLE
关于词库的小问题

### ISSUE THREAD

**Issue by Huang1932539** [HibiKier/zhenxun_bot#1353]
从https://github.com/HibiKier/zhenxun_bot/issues/1201
这个里面的链接下载了词库的.xls文件，请问要如何导入小真寻呢？

**Comment by HibiKier** [comment]
自己解析成json之类的吧

**Comment by Huang1932539** [comment]
> 自己解析成json之类的吧

是不是得用数据库命令啊，本人小白，不是很懂（哭唧唧）
