### ISSUE TITLE
开箱的一些问题

### ISSUE THREAD

**Issue by dong2005923** [HibiKier/zhenxun_bot#1357]
请问一下，如何将我本地电脑内的开箱图片，收录的武器箱迁移进服务器内。
我尝试过迁移open_cases整个文件夹与开箱的图片文件夹，但是均提示未收录武器箱，或许包含在数据库内？
我没有使用更新武器箱的命令来更新图片的原因是我的服务器ip在buff平台貌似黑了？403错误，并且也无法直接访问，我也不知道如何获取代理后填入代理地址。
希望能解决一下，不胜感激！！

**Comment by HibiKier** [comment]
可以本地连服务器上的数据库进行更新，然后把本地图片放到服务器上

**Comment by dong2005923** [comment]
> 可以本地连服务器上的数据库进行更新，然后把本地图片放到服务器上

好的，多谢
