### ISSUE TITLE
真寻启动报错，

### ISSUE THREAD

**Issue by ctrlxcvs** [HibiKier/zhenxun_bot#1359]
/### 系统版本：Ubuntu 20.04
### 错误截图

[img]
<img width="828" alt="截屏2023-04-10 19 09 51" src="https://user-images.githubusercontent.com/109337282/230890942-327cb04f-5b66-4ed7-910a-773fb36d440b.png">
<img width="1100" alt="截屏2023-04-10 19 10 54" src="https://user-images.githubusercontent.com/109337282/230890961-76b8a3c4-8263-4928-b7cc-e5751effd9c6.png">

### 日志截图

[img]

### 错误说明

TypeError: 'NoneType' object is not iterable

**Comment by ctrlxcvs** [comment]
系统是ubuntu22.04
最新版本真寻

**Comment by HibiKier** [comment]
是升级上来的吗还是首次安装？

**Comment by YvanW-Amine** [comment]
解决了吗，我好像也是一样

**Comment by 1230zzk** [comment]
大佬，解决了吗，，我也是同样的报错

**Comment by ctrlxcvs** [comment]
我换了个python版本就没问题了

**Comment by 1230zzk** [comment]
是换了哪个版本，我的是3.10

**Comment by 1230zzk** [comment]
感谢，我换3.9.9的已经正常了
