### ISSUE TITLE
国内无法访问i.pixiv.re导致的se图获取问题

### ISSUE THREAD

**Issue by RWGLQJ** [HibiKier/zhenxun_bot#1361]
### 真寻版本：0.1.5.3
![-40367a5d9a3fcf96](https://user-images.githubusercontent.com/79353322/230949457-932dc5c0-2730-4d44-8155-e58289334ace.jpg)
![-275827d57b1be836](https://user-images.githubusercontent.com/79353322/230949472-7e9cabef-d797-4cf6-9fcb-498b732bc824.jpg)

报错：
04-11 08:55:51 [ERROR] services | 下载 https://i.pixiv.re/img-original/img/2022/12/23/13/10/56/103827444_p10.png 下载超时.. Path：/home/zhenxun_bot/resources/temp/77.jpg

服务器位于国内，前面这个api可以访问，但是api获取的i.pixiv.re连接不了获取不了se图求解决，现在已知一个pixiv反向代理：pixiv.yuki.sh

**Comment by HibiKier** [comment]
在configs/config.yaml里修改

**Comment by RWGLQJ** [comment]
OK

**Comment by RWGLQJ** [comment]
问题已解决
