### ISSUE TITLE
无法修改pixiv反向代理

### ISSUE THREAD

**Issue by RWGLQJ** [HibiKier/zhenxun_bot#1362]
### 真寻版本：0.1.5.3
在配置文件中更改了pixiv的反向代理，重启机器人后依然使用原来的i.pixiv.re
![Screenshot_2023-04-11-01-12-27-911_com mixplorer silver](https://user-images.githubusercontent.com/79353322/230954293-91e47c5c-c9c7-4111-90b7-50f9d01a0c7b.jpg)

**Comment by HibiKier** [comment]
configs/config.yaml

**Comment by RWGLQJ** [comment]
OK的
