### ISSUE TITLE
昵称插件无反应

### ISSUE THREAD

**Issue by PPPPParas** [HibiKier/zhenxun_bot#1369]
### 日志截图
![1](https://user-images.githubusercontent.com/91717560/231748505-5089d07b-1e35-4b6f-a5cf-46c475a9c322.png)
![2](https://user-images.githubusercontent.com/91717560/231748515-fb1a489e-254b-4a7e-8709-2cc835a64f4e.png)
![3](https://user-images.githubusercontent.com/91717560/231748543-cd7bec37-d21e-41d3-8686-1ca0b40eee60.png)

### 错误说明
更新后昵称插件无反应

**Comment by HibiKier** [comment]
是更新上来的吗，models里的group_member_info是不是没更新

**Comment by PPPPParas** [comment]
> 
感谢
看了一眼时间确实是没更新...
这次更新出了好多问题，比如resources下的图片资源缺失之类的
奇怪，下次手动更新好了
