### ISSUE TITLE
有没有备份数据库的教程啊?

### ISSUE THREAD

**Issue by m0eak** [HibiKier/zhenxun_bot#1371]
有没有备份数据库的教程啊?

**Comment by PackageInstaller** [comment]
我说一下我的过程，希望对你有帮助
### 备份：
在/var/lib/postgres下写了一个脚本**backup.sh**

> #! /bin/sh
>su - postgres <<EOF
>Postgres@2k7au4au3  // 使用管道符输入postgres用户密码
>EOF
>
>pg_dump -U postgres -F t -f /var/lib/postgres/backup/db_$(date +\%Y\%m\%d).sql zhenxun_bot  
// 备份名为zhenxun_bot的数据库到/var/lib/postgres/backup/这个文件夹，需要提前创建并调好权限


授予可执行权限，./backup.sh手动执行，或是用crontab这类工具每天自动执行都可。



### 恢复：
同样在/var/lib/postgres下写了一个脚本**restore.sh**

> #!/bin/bash
>
>su - postgres <<EOF
>Postgres@2k7au4au3 // 使用管道符输入postgres用户密码
>EOF
>
>backup_path="/var/lib/postgres/backup/" // 备份数据库的路径
>
>backup_file=$(ls -t $backup_path | head -n 1) 
 // 用ls -t指令查看最新的那个备份文件
>
>pg_restore -U postgres -d zhenxun_bot "$backup_path/$backup_file"
// 恢复数据库，恢复之前需要新建**zhenxun_bot**这个空数据库，具体情况视个人而定
>
>if [[ $? -eq 0 ]]; then
>    echo "恢复完成"
>else
>    echo "恢复失败，错误消息如下："
>    echo "$restore_output"
>fi
> 

授予可执行权限，./backup.sh手动执行，或是用crontab这类工具每天自动执行都可。

**Comment by m0eak** [comment]
谢谢大佬我等会试一下。--发自新浪邮箱客户端
在 4月15日 00:52，PackageInstaller ***@***.***> 写道：

我说一下我的过程，希望对你有帮助
备份：
在/var/lib/postgres下写了一个脚本backup.sh

#! /bin/sh

su - postgres <<EOF

***@***.***  // 使用管道符输入postgres用户密码

EOF
pg_dump -U postgres -F t -f /var/lib/postgres/backup/db_$(date +%Y%m%d).sql zhenxun_bot

// 备份名为zhenxun_bot的数据库到/var/lib/postgres/backup/这个文件夹，需要提前创建并调好权限

授予可执行权限，./backup.sh手动执行，或是用crontab这类工具每天自动执行都可。
恢复：
同样在/var/lib/postgres下写了一个脚本restore.sh

#!/bin/bash
su - postgres <<EOF

***@***.*** // 使用管道符输入postgres用户密码

EOF
backup_path="/var/lib/postgres/backup/" // 备份数据库的路径
backup_file=$(ls -t $backup_path | head -n 1)

// 用ls -t指令查看最新的那个备份文件
pg_restore -U postgres -d zhenxun_bot "$backup_path/$backup_file"

// 恢复数据库，恢复之前需要新建zhenxun_bot这个空数据库，具体情况视个人而定
if [[ $? -eq 0 ]]; then

echo "恢复完成"

else

echo "恢复失败，错误消息如下："

echo "$restore_output"

fi

授予可执行权限，./backup.sh手动执行，或是用crontab这类工具每天自动执行都可。

&mdash;

**Comment by PackageInstaller** [comment]
> 谢谢大佬我等会试一下。--发自新浪邮箱客户端 在 4月15日 00:52，PackageInstaller ***@***.***> 写道： 我说一下我的过程，希望对你有帮助 备份： 在/var/lib/postgres下写了一个脚本backup.sh #! /bin/sh su - postgres <<EOF ***@***.*** // 使用管道符输入postgres用户密码 EOF pg_dump -U postgres -F t -f /var/lib/postgres/backup/db_$(date +%Y%m%d).sql zhenxun_bot // 备份名为zhenxun_bot的数据库到/var/lib/postgres/backup/这个文件夹，需要提前创建并调好权限 授予可执行权限，./backup.sh手动执行，或是用crontab这类工具每天自动执行都可。 恢复： 同样在/var/lib/postgres下写了一个脚本restore.sh #!/bin/bash su - postgres <<EOF ***@***.*** // 使用管道符输入postgres用户密码 EOF backup_path="/var/lib/postgres/backup/" // 备份数据库的路径 backup_file=$(ls -t $backup_path | head -n 1) // 用ls -t指令查看最新的那个备份文件 pg_restore -U postgres -d zhenxun_bot "$backup_path/$backup_file" // 恢复数据库，恢复之前需要新建zhenxun_bot这个空数据库，具体情况视个人而定 if [[ $? -eq 0 ]]; then echo "恢复完成" else echo "恢复失败，错误消息如下：" echo "$restore_output" fi 授予可执行权限，./backup.sh手动执行，或是用crontab这类工具每天自动执行都可。 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

具体情况你记得按照你的情况改，比如pgsql的位置，数据库的名字啥的

**Comment by PackageInstaller** [comment]
> 我用写的是这个sh脚本，只备份不会恢复，需要自己手动加计划任务定时备份
> 
> ```
> #!/bin/bash
> 
> # 定义备份文件存储目录
> backup_dir=/home/my/bot/zhenxun_bot/backup/pgsql/
> 
> # 定义备份文件名
> backup_file=zhenxun_$(date +%Y%m%d_%H%M%S).sql
> 
> # 定义要备份的数据库
> database=zhenxun
> 
> # 定义要保留的备份天数
> max_days=7
> 
> # 定义数据库的用户名和密码
> username=*******
> password=*******
> 
> # 执行备份
> PGPASSWORD=$password pg_dump -U $username -h localhost $database > $backup_dir/$backup_file
> 
> # 删除过期备份
> find $backup_dir/* -mtime +$max_days -exec rm {} \;
> ```

比我的好，抄了抄了（
