### ISSUE TITLE
查看帮助详情会返回base64的数据导致日志超长

### ISSUE THREAD

**Issue by Rod-fish** [HibiKier/zhenxun_bot#1374]
### 错误截图

![image](https://user-images.githubusercontent.com/108643053/232078901-2e9f6e53-b745-4f35-94b2-1a617846304d.png)

### 日志截图

![image](https://user-images.githubusercontent.com/108643053/232078983-c9fa34f6-b224-45d7-af7d-5978a72f1fda.png)

### 错误说明

对bot发送帮助 ai等查看插件帮助详情时，日志会包含base64信息导致日志超长，如果次数够多日志文件还会很大

**Comment by yajiwa** [comment]
你自己填的真寻版本不是0.1.5.3吗

**Comment by yajiwa** [comment]
[5f97485](https://github.com/HibiKier/zhenxun_bot/pull/1373/commits/5f9748582dd3c74cf5d8ed584b55af014d2de3d5) 已解决
