### ISSUE TITLE
如何更新开箱武器箱

### ISSUE THREAD

**Issue by INSide-734** [HibiKier/zhenxun_bot#1375]
### 真寻版本：0.1.6.7

    如何更新武器箱/开箱图片/武器价格
文档并未作详细说明，且相关命令无法触发(或已更改)

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/232234366-506436b3-46b7-489c-9874-30b66ff34203.png)

**Comment by INSide-734** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/232234366-506436b3-46b7-489c-9874-30b66ff34203.png)
> 

![Screenshot_2023-04-15-23-36-51-77_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/109641391/232234596-4e08263b-887d-466d-b6a9-d177f95358db.jpg)

**Comment by HibiKier** [comment]
配置一下buff token

**Comment by INSide-734** [comment]
如何获取？

**Comment by HibiKier** [comment]
去buff登录后f12在token里找到session把值放到配置文件就行了
