### ISSUE TITLE
群事件处理插件（basic_plugins/group_handle）报错

### ISSUE THREAD

**Issue by ZiAzusa** [HibiKier/zhenxun_bot#1377]
### 错误截图

![报错日志的最后一段](https://user-images.githubusercontent.com/64982342/232283458-b4986ffd-6953-45a2-b3d0-0634c5f5fac1.png)

### 日志截图

![完整报错日志第1页](https://user-images.githubusercontent.com/64982342/232283466-13c9bfcd-2dcc-4f8f-ba22-10feeb000c6b.png)
![完整报错日志第2页](https://user-images.githubusercontent.com/64982342/232283495-c9ae6c1c-5831-419a-b5b6-a660b8c20824.png)
![完整报错日志第3页](https://user-images.githubusercontent.com/64982342/232283516-578c94ea-c740-4d07-850e-308c58ef4886.png)

### 错误说明

在更新完最新版（v0.1.6.7）真寻Bot后，入群退群消息处理插件（basic_plugins/group_handle）出现了以上报错，个人认为是在更新数据库数据时出现了时间格式错误，但我不知道如何修复它，希望能有大佬来帮我解决一下，谢谢！
此外，在检查过程中，我查找了Tortoise的Issues，发现了类似的报错信息[tortoise/tortoise-orm #465](https://github.com/tortoise/tortoise-orm/issues/465)，希望有所帮助。

**Comment by HibiKier** [comment]
更新到0.1.6.7的吗，models/group_member_info更新了吗

**Comment by ZiAzusa** [comment]
models/group_member_info更新了，依然存在该问题

**Comment by ZiAzusa** [comment]
解决了...是我的问题，抱歉——
