### ISSUE TITLE
涩图偶尔撤回会失败

### ISSUE THREAD

**Issue by JHDZ33** [HibiKier/zhenxun_bot#1379]
### 错误截图
配置文件：
![图片](https://user-images.githubusercontent.com/78144612/232367470-5118b07c-75a4-4304-8f70-095527f242d0.png)

### 日志截图

![图片](https://user-images.githubusercontent.com/78144612/232367319-ce5182d4-88b3-462d-baa8-60a8702bef0a.png)

### 错误说明
偶尔会出现发送涩图后不会进行自动撤回，查看日志会报上图错误
使用docker单机版部署的

**Comment by HibiKier** [comment]
只能说，网络问题

**Comment by JHDZ33** [comment]
> 只能说，网络问题

细说，是不是因为服务器带宽低图片发送太久了，一直到执行撤回时图片仍未发送成功导致的
还是其他原因
