### ISSUE TITLE
加载插件报错，好像是重复加载，但是我找不到这个重复加载的插件是什么，它还导致真寻启动不了，

### ISSUE THREAD

**Issue by lintonxue00** [HibiKier/zhenxun_bot#1380]
### 错误截图
![`~R2N_Z$3DMY%CDHF Z4 (O](https://user-images.githubusercontent.com/115356968/232674858-953fe3ac-236b-4046-bcf6-fa5eed9b7e7c.jpg)

[img]

### 日志截图

[img]

### 错误说明
加载插件报错，好像是重复加载，但是我找不到这个重复加载的插件是什么，它还导致真寻启动不了，
发生了xx错误...

**Comment by PackageInstaller** [comment]
看着像是你用pip装了manager这个模块？但是这个模块和ex_plugin里面也有个叫manager的插件冲突了
