### ISSUE TITLE
 cannot import name 'export' from 'nonebot'

### ISSUE THREAD

**Issue by a930389426** [HibiKier/zhenxun_bot#1381]
启动时报错，是我nonebot2或者"nonebot_plugin_apscheduler的版本有问题吗？如果是的话我要换成什么版本的
![image](https://user-images.githubusercontent.com/59648220/232699177-36cea194-7a70-4370-81a3-ddf59d9efe05.png)

**Comment by a930389426** [comment]
![image](https://user-images.githubusercontent.com/59648220/232700200-63ed9d94-2979-4f68-aaf4-32b09c59ac0a.png)

**Comment by PackageInstaller** [comment]
nonebot.export方法我记得早就过期了吧
你可以注释掉export的部分试试
