### ISSUE TITLE
在执行poetry shell出现错误,并且出现ModuleNotFoundError: No module named 'nonebot'

### ISSUE THREAD

**Issue by heixiaoou** [HibiKier/zhenxun_bot#1383]
### 错误截图

![image](https://user-images.githubusercontent.com/106435645/233342519-deb6dc30-6d5b-484b-8bae-9afbe9b3cad6.png)
![image](https://user-images.githubusercontent.com/106435645/233343354-ed5b8612-b3c0-468b-b567-433d20c8f80e.png)

### 错误说明

正常执行了pip install poetry与poetry install，在执行poetry shell出现此错误,并且无法执行python bot.py

**Comment by Karmau-Git** [comment]
兄弟 你是怎么解决的呢

**Comment by heixiaoou** [comment]
> 兄弟 你是怎么解决的呢

请注意！我不一定保证我的方法对你的有效！
在bot安装目录里，用Powershell执行set-ExecutionPolicy RemoteSigned，后输入Y，之后重新从这里开始
![image](https://github.com/HibiKier/zhenxun_bot/assets/106435645/ae042d55-4609-40eb-bb7b-c9f647cb33e6)
如果有所帮助，我将非常高兴
