### ISSUE TITLE
开启允许真寻自身触发命令后报错

### ISSUE THREAD

**Issue by dong2005923** [HibiKier/zhenxun_bot#1384]
gocq内也将report-self-message修改为了true。

超级用户使用超级用户帮助，管理员帮助时均会报错，但可以执行成功。

现在貌似很多命令都有报错，且都是同一个报错，命令顺利执行，但有报错。

真寻自身触发命令时，也会报错，命令并未执行成功。

gocq内无相关错误信息。

错误日志

![MBZY JLTRT@__Z(W3R 5)_8](https://user-images.githubusercontent.com/109427426/233415565-7d5b5254-be52-4625-bde4-12dc268fade4.png)

**Comment by HibiKier** [comment]
e4ca110938732863ba58c0e286eaf62be5a68379
