### ISSUE TITLE
真寻启动时错误 Error when running RunPreProcessors. Running cancelled!

### ISSUE THREAD

**Issue by zyima** [HibiKier/zhenxun_bot#1385]
### 日志截图
![1](https://user-images.githubusercontent.com/66709758/233775117-d5e2fdaf-d083-4287-8492-cb21d40993ad.png)
![2](https://user-images.githubusercontent.com/66709758/233775122-5b6dedb4-7350-417c-8768-b95408806e60.png)

### 错误说明
如图二错误。下面是情况说明：
使用poetry安装某nb商店插件，安装完成后重启真寻，发生上图报错。现在启动不了了。

**Comment by zyima** [comment]
补充：以前加载插件的时候是没有图一那些粉字的from的。目前将插件删除仍然无法启动真寻

**Comment by PackageInstaller** [comment]
有后面的报错吗，我遇到这情况是安装了和真寻数据库连接冲突的依赖

**Comment by PackageInstaller** [comment]
应该是nonebot-plugin-tortoise-orm这个依赖，你试试
`pip uninstall nonebot-plugin-tortoise-orm`

**Comment by zyima** [comment]
> 有后面的报错吗，我遇到这情况是安装了和真寻数据库连接冲突的依赖

后面没有报错，所有的报错信息就是图二那张图。然后在真寻群里问了问，把依赖文件夹删了重新poetry install安装真寻依赖，就可以跑了。

**Comment by zyima** [comment]
> 应该是nonebot-plugin-tortoise-orm这个依赖，你试试 `pip uninstall nonebot-plugin-tortoise-orm`

因为旧的依赖文件已经全删了试不了了(捂脸)

**Comment by PackageInstaller** [comment]
> > 有后面的报错吗，我遇到这情况是安装了和真寻数据库连接冲突的依赖
> 
> 后面没有报错，所有的报错信息就是图二那张图。然后在真寻群里问了问，把依赖文件夹删了重新poetry install安装真寻依赖，就可以跑了。

实际上应该就是我说的那个依赖的问题，不信你手动装以下试试就知道了（滑稽）

**Comment by zyima** [comment]
> > > 有后面的报错吗，我遇到这情况是安装了和真寻数据库连接冲突的依赖
> > 
> > 
> > 后面没有报错，所有的报错信息就是图二那张图。然后在真寻群里问了问，把依赖文件夹删了重新poetry install安装真寻依赖，就可以跑了。
> 
> 实际上应该就是我说的那个依赖的问题，不信你手动装以下试试就知道了（滑稽）

亚达哟~

**Comment by MobiusT** [comment]
> 应该是nonebot-plugin-tortoise-orm这个依赖，你试试
> `pip uninstall nonebot-plugin-tortoise-orm`

我没有这个依赖，但同样出现了这个问题，删除虚拟环境重新安装依赖后问题消失，可惜没能查出来是什么依赖的问题
