### ISSUE TITLE
开箱报错

### ISSUE THREAD

**Issue by 2055135** [HibiKier/zhenxun_bot#1398]
### 错误截图

![image](https://user-images.githubusercontent.com/119772101/234504276-84845a8c-0c7b-426f-a5a7-7717f9f73b4a.png)

### 日志截图

![image](https://user-images.githubusercontent.com/119772101/234504321-bbd223b1-039a-4058-881e-73e53159bf54.png)

### 错误说明

发送开箱指令报错，事先更新过武器箱

**Comment by HibiKier** [comment]
有个武器箱或皮肤重复了，在数据库里删掉
