### ISSUE TITLE
发送 签到 指令后报错

### ISSUE THREAD

**Issue by BMC-Gordon0921** [HibiKier/zhenxun_bot#1399]
### 错误截图

![67b397def8a14efc9691182a65d2e91](https://user-images.githubusercontent.com/92096046/234558756-2b3dbaed-1cd6-49e1-97aa-fedb010f4756.png)

### 日志截图

![f387b1822c7d8a58a8ff697dfca8bbf](https://user-images.githubusercontent.com/92096046/234558769-def4aeac-74ef-48db-af6e-ebe2c83d0ce6.png)

### 错误说明
（以上图片为同一报错）
发送 签到 指令时后台出现如上报错，bot无消息推送。

**Comment by PackageInstaller** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/1321

**Comment by BMC-Gordon0921** [comment]
> #1321

这个会和我用的postgresql14有关系吗（有些没看懂）

**Comment by PackageInstaller** [comment]
> > #1321
> 
> 这个会和我用的postgresql14有关系吗（有些没看懂）

不是，我也用的14，

**Comment by BMC-Gordon0921** [comment]
> 

好的，那就针对几句数据库指令一个个摸过去吧（躺）

**Comment by PackageInstaller** [comment]
改完代码之后搜inf然后改正常就好了

**Comment by BMC-Gordon0921** [comment]
> 改完代码之后搜inf然后改正常就好了

好，改完代码了，现在刚摸进数据库（动作好慢，我是fw）——感谢您的帮助，少姜小姐）

**Comment by BMC-Gordon0921** [comment]
好，遇到新问题：
输入 select * from group_info_users where user_qq = xxx 后，给我报了这样一个东西：

ERROR:  column "user_qq" does not exist
LINE 1: select * from group_info_users where user_qq = 2710464988;
                                             ^
HINT:  Perhaps you meant to reference the column "group_info_users.user_id".

**Comment by PackageInstaller** [comment]
其实可以直接

`UPDATE "group_info_users" SET "user_join_time" = '0001-01-02 00:00:00+08:05:43' WHERE "user_join_time" ='-infinity'`

**Comment by BMC-Gordon0921** [comment]
update 0

**Comment by BMC-Gordon0921** [comment]
哦找到了，两个表都改好了
sign_group_users 那张 update 2

**Comment by PackageInstaller** [comment]
那再试试这个？

`UPDATE "sign_group_users" SET "checkin_time_last" = '0001-01-02 00:00:00+08:05:43' WHERE "user_join_time" ='-infinity'`

**Comment by BMC-Gordon0921** [comment]
> 

update 2 ，现在正在重启……

**Comment by BMC-Gordon0921** [comment]
好了，这个问题解决了，如果以后有新用户且问题复现的话参照 #1321 及 本issue #1399 进行修复。
