### ISSUE TITLE
有谁在树莓派上安装了嘛，启动有好多问题

### ISSUE THREAD

**Issue by 223333** [HibiKier/zhenxun_bot#14]
![1](https://user-images.githubusercontent.com/11299674/127726662-0b341166-dfa7-45f8-9ce3-2f9d72d88043.jpg)
![2](https://user-images.githubusercontent.com/11299674/127726665-769fb574-17a1-440c-96c3-d701f26bd501.jpg)
![3](https://user-images.githubusercontent.com/11299674/127726706-39ffd434-2260-4c92-8feb-c61896df8ccf.jpg)
会有很多插件加载失败

**Comment by HibiKier** [comment]
你这模块和文件夹都没clone全啊，pip安装requirements.txt了吗？

**Comment by 223333** [comment]
安装requirements.txt过程好像也有红色的报错，老哥我可以加你qq问你问题嘛

**Comment by 223333** [comment]
文件我是直接下载的zip到树莓派解压的

**Comment by HibiKier** [comment]
az，也行

**Comment by 223333** [comment]
21426323 好哥哥你加我下
