### ISSUE TITLE
数据库配置未填写

### ISSUE THREAD

**Issue by NathanSummer** [HibiKier/zhenxun_bot#1401]
### 日志截图
![capture_20230430194828042](https://user-images.githubusercontent.com/88868171/235361336-764d688b-dc19-4f86-bbc9-194bd038b991.jpg)

![capture_20230430195038230](https://user-images.githubusercontent.com/88868171/235361317-4e466de6-4568-4b72-bb76-15da51c132fa.jpg)

![capture_20230430195329505](https://user-images.githubusercontent.com/88868171/235361302-66fdbd13-5f47-4472-9afc-73352aad13f6.jpg)

### 错误说明

按照文档全部填写好后依然报错（是保存过的）

**Comment by yajiwa** [comment]
看看你填的配置文件

**Comment by NathanSummer** [comment]
> 看看你填的配置文件

欸？错了嘛？

**Comment by yajiwa** [comment]
你发的图片没有真寻的数据库配置，需要在`configs/config.py`里填写

**Comment by NathanSummer** [comment]
> 你发的图片没有真寻的数据库配置，需要在`configs/config.py`里填写

欸，奇怪，我都没有动过为什么都清空了...
postgres的配置也是，自己就没了，还是我昨天补写的（

**Comment by NathanSummer** [comment]
总之肥肠感谢，祝大佬五一快乐！！！
