### ISSUE TITLE
关于cos

### ISSUE THREAD

**Issue by NathanSummer** [HibiKier/zhenxun_bot#1405]
### 错误截图

![image](https://user-images.githubusercontent.com/88868171/235977311-7ca34a61-6626-43c1-bf3d-cbf350fc4d20.png)

### 日志截图

![image](https://user-images.githubusercontent.com/88868171/235977170-44b5c92a-99b9-4b06-81d7-e8e417b3e302.png)

### 错误说明

图片下载成功发送失败，一张都发不出去

**Comment by MisakaMikoto2333** [comment]
我以前遇到这个问题的时候是网站问题，网站进不去机器人就获取不到图片就会这样，你试试换一个？

**Comment by NathanSummer** [comment]
> 我以前遇到这个问题的时候是网站问题，网站进不去机器人就获取不到图片就会这样，你试试换一个？

我用的就是注释那两个里面速度快的那个

**Comment by q56535** [comment]
可以试着在gocq配置设置代理

**Comment by HibiKier** [comment]
gocq提示什么错误

**Comment by NathanSummer** [comment]
> gocq提示什么错误

![image](https://github.com/HibiKier/zhenxun_bot/assets/88868171/55fdd991-e39e-4b88-b325-5cad8ccd17e6)
k'q'l看起来是这样的

**Comment by HibiKier** [comment]
看网站好像404了

**Comment by HibiKier** [comment]
看网站好像404了

**Comment by NathanSummer** [comment]
> 看网站好像404了

啊，那要找新的网站力

**Comment by slanderou** [comment]
> 看网站好像404了

我用的windows server2022，然后用的是原先的那个，挂了梯子，go-cqhttp也配置了下载图片代理。但是cos功能还是会报错。网站用浏览器也能正常访问。
![image](https://github.com/HibiKier/zhenxun_bot/assets/92035109/0ee33d64-5a16-48db-8508-d375cad9a3b9)
