### ISSUE TITLE
开箱爆率能调整吗

### ISSUE THREAD

**Issue by ARCHERXTY** [HibiKier/zhenxun_bot#1408]
### 错误截图
![image](https://user-images.githubusercontent.com/59302439/236396502-bbae08d6-8560-451b-998b-3e47ee63b2c3.png)
![image](https://user-images.githubusercontent.com/59302439/236396770-62013c60-9f59-47e7-af73-7b3935f3ed22.png)

### 日志截图
![image](https://user-images.githubusercontent.com/59302439/236397542-8d1e8a83-6bd6-4a4c-84aa-581fd09d7620.png)

### 错误说明
开箱更新后和群里的小伙伴好像就没开出过金，就自己去试了下，开了1000多发，除非我是真的非，不然怎么也该出一个了，在想是不是那里没设置对，望大佬解惑。
还有就是偶尔会少开一箱，不知道和开不出金有没有关系。

**Comment by HibiKier** [comment]
金色的皮肤更新了吗
