### ISSUE TITLE
开箱增加新的武器箱

### ISSUE THREAD

**Issue by Zhuazizizi** [HibiKier/zhenxun_bot#1414]
如果我打算增加新的武器箱，我是不是直接在 zhenxun_bot\plugins\open_cases\config.py 文件中的 CASE2ID 里自行添加武器箱名字和在buff上对应的编码就行，这样会出什么bug吗。
![image](https://github.com/HibiKier/zhenxun_bot/assets/107139732/546bd1d3-020f-443c-84fc-8f4a8b3522ff)

**Comment by HibiKier** [comment]
应该可以
