### ISSUE TITLE
可以把俄罗斯转盘做成以图片形式发送吗？

### ISSUE THREAD

**Issue by a930389426** [HibiKier/zhenxun_bot#1417]
可以把俄罗斯转盘做成以图片形式发送吗？我家小真寻因为这个插件被冻结过一次，理由是传播诈骗行为

**Comment by a930389426** [comment]
![20230512162918](https://github.com/HibiKier/zhenxun_bot/assets/59648220/b976618c-7c30-4b07-b057-bc6b8e856883)

**Comment by a930389426** [comment]
![AQSN}6(ZWBXAD20SZ$T}B8U](https://github.com/HibiKier/zhenxun_bot/assets/59648220/d6919ec5-c2eb-4d49-88b9-3b1b534446fe)
其他群友看到小真寻的消息还会提示个“涉及资金往来请谨慎操作”

**Comment by HibiKier** [comment]
6，将结算消息以图片发送？

**Comment by a930389426** [comment]
> 6，将结算消息以图片发送？

如果可以的话过程也能以图片发送就更好了，因为有时候我这边文字消息会风控发不出来，可能是“子弹”之类的关键词也会触发风控（难蚌）

**Comment by a930389426** [comment]
但过程被风控了发不出来一般让群友发多一次“开枪”就能解决，不会说直接跳到对手开枪，所以也不算什么大问题
