### ISSUE TITLE
无法使用涩图功能

### ISSUE THREAD

**Issue by neal240** [HibiKier/zhenxun_bot#1419]
### 错误截图

![QQ图片20230514203937](https://github.com/HibiKier/zhenxun_bot/assets/106437969/ca4829a3-3e66-4602-bdec-d2cce64e515f)

### 日志截图

![QQ图片20230514203957](https://github.com/HibiKier/zhenxun_bot/assets/106437969/c2598472-9396-48e2-8a94-6eb2595c3f63)

### 错误说明

无法使用涩图功能

**Comment by neal240** [comment]
![QQ图片20230514212447](https://github.com/HibiKier/zhenxun_bot/assets/106437969/72875320-5c59-49a7-b77f-15d3ff69f19c)
该功能在私聊里可以正常使用，在群聊却不行

**Comment by PackageInstaller** [comment]
看着像数据库里面的问题？你去看看数据库里面是不是有inf的地方

**Comment by neal240** [comment]
> 看着像数据库里面的问题？你去看看数据库里面是不是有inf的地方

![QQ图片20230520181856](https://github.com/HibiKier/zhenxun_bot/assets/106437969/6ddc90e5-7322-4f91-8a92-7014a702d004)
数据库里的setu列这样显示是有问题吗

**Comment by PackageInstaller** [comment]
你先去搜一下看看里面是不是有inf的部分

**Comment by neal240** [comment]
> 你先去搜一下看看里面是不是有inf的部分

在gpt上问了半天都不知道怎么查

**Comment by PackageInstaller** [comment]
先用select 大體看一下表結構，然後再精準搜索可能有inf的地方（inf是無窮大的簡寫）

**Comment by neal240** [comment]
> 先用select 大體看一下表結構，然後再精準搜索可能有inf的地方（inf是無窮大的簡寫）

没有

**Comment by PackageInstaller** [comment]
那我就不知道啦

**Comment by neal240** [comment]
> 那我就不知道啦

如果有inf的话怎么解决？问一下以防下次遇到这种情况

**Comment by neal240** [comment]
重装数据库解决了
