### ISSUE TITLE
签到插件部分人使用报错

### ISSUE THREAD

**Issue by MisakaMikoto2333** [HibiKier/zhenxun_bot#1420]
有部分人签到会这样报错，我自己使用却是所有群都报错并且无法使用

**Comment by MisakaMikoto2333** [comment]
![image](https://github.com/HibiKier/zhenxun_bot/assets/68831929/e57539bd-354b-42ff-8154-fa659865b9ff)

**Comment by zhx79513** [comment]
是bug，临时解决方法在这：
https://github.com/HibiKier/zhenxun_bot/issues/1321#issuecomment-1488509084
