### ISSUE TITLE
image_management 的“上传图片功能”的“请选择要上传的图库”中的图库目录不会在重载配置后更新

### ISSUE THREAD

**Issue by zhx79513** [HibiKier/zhenxun_bot#1421]
### 错误截图
![图片](https://github.com/HibiKier/zhenxun_bot/assets/5063357/adc57f3f-1a4c-4bd7-a1fb-6d00ed4432bb)

### 日志截图

![图片](https://github.com/HibiKier/zhenxun_bot/assets/5063357/722d511e-42d6-4fb1-8865-4c87df483c8f)

### 错误说明

在配置中修改IMAGE_DIR_LIST下的目录后，重载配置，其他图库功能的目录都会更新，但只有“请选择要上传的图库”提示还是原来的。
个人猜测是不是在 [image_management/upload_image/__init__.py](https://github.com/HibiKier/zhenxun_bot/tree/main/plugins/image_management/upload_image/__init__.py) 中 [第57行](https://github.com/HibiKier/zhenxun_bot/blob/9e0add7bde1e1cec5bb99f830065d230fce87eab/plugins/image_management/upload_image/__init__.py#LL57C1-L61C2)：

```python
   @upload_img.got(
    "path",
    prompt=f"请选择要上传的图库\n- "
    + "\n- ".join(Config.get_config("image_management", "IMAGE_DIR_LIST")),
    )
```

的调用会有缓存，只会在第一次调用`Config.get_config("image_management", "IMAGE_DIR_LIST")`时读取配置，之后都是读的缓存？

**Comment by HibiKier** [comment]
26db0fad855a4755f93b382e31b51038cc5d12c0
