### ISSUE TITLE
首次启动bot报错

### ISSUE THREAD

**Issue by Pikachu067** [HibiKier/zhenxun_bot#1422]
### 截图
![image](https://github.com/HibiKier/zhenxun_bot/assets/133853733/0f892a66-9e9d-49a3-8632-386088718b3b)
![image](https://github.com/HibiKier/zhenxun_bot/assets/133853733/6d9cf1c0-c132-4ed8-8c98-dedece63c4c0)

### 日志

(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>poetry install
Installing dependencies from lock file

No dependencies to install or update

(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>poetry shell
Virtual environment already activated: C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-wIer85dA-py3.9

(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>playwright install chromium

(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>python bot.py
Traceback (most recent call last):
  File "D:\bot\zhenxun_bot-main\zhenxun_bot-main\bot.py", line 3, in <module>
    from services.db_context import init, disconnect
  File "D:\bot\zhenxun_bot-main\zhenxun_bot-main\services\__init__.py", line 1, in <module>
    from .db_context import *
  File "D:\bot\zhenxun_bot-main\zhenxun_bot-main\services\db_context.py", line 5, in <module>
    from tortoise.connection import connections
ModuleNotFoundError: No module named 'tortoise.connection'

(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>

### 说明
首次启动碰到的 ImportError: cannot import name 'connections' from 'tortoise'  按百度试了半天变成了下面的问题
ModuleNotFoundError: No module named 'tortoise.connection' （

**Comment by neal240** [comment]
> ### 系统版本：win10
> 
> ### 真寻版本：v0.1.6.7
> 
> 
> 
> ### 截图
> 
> ![image](https://github.com/HibiKier/zhenxun_bot/assets/133853733/0f892a66-9e9d-49a3-8632-386088718b3b)
> 
> ![image](https://github.com/HibiKier/zhenxun_bot/assets/133853733/6d9cf1c0-c132-4ed8-8c98-dedece63c4c0)
> 
> 
> 
> ### 日志
> 
> 
> 
> (zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>poetry install
> 
> Installing dependencies from lock file
> 
> 
> 
> No dependencies to install or update
> 
> 
> 
> (zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>poetry shell
> 
> Virtual environment already activated: C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-wIer85dA-py3.9
> 
> 
> 
> (zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>playwright install chromium
> 
> 
> 
> (zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>python bot.py
> 
> Traceback (most recent call last):
> 
>   File "D:\bot\zhenxun_bot-main\zhenxun_bot-main\bot.py", line 3, in <module>
> 
>     from services.db_context import init, disconnect
> 
>   File "D:\bot\zhenxun_bot-main\zhenxun_bot-main\services\__init__.py", line 1, in <module>
> 
>     from .db_context import *
> 
>   File "D:\bot\zhenxun_bot-main\zhenxun_bot-main\services\db_context.py", line 5, in <module>
> 
>     from tortoise.connection import connections
> 
> ModuleNotFoundError: No module named 'tortoise.connection'
> 
> 
> 
> (zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main>
> 
> 
> 
> ### 说明
> 
> 首次启动碰到的 ImportError: cannot import name 'connections' from 'tortoise'  按百度试了半天变成了下面的问题
> 
> ModuleNotFoundError: No module named 'tortoise.connection' （
> 
> 

试一下pip install tortoise.connection？
记得在虚拟环境在运行

**Comment by Pikachu067** [comment]
感谢解答  我昨天用csdn的机器人给我解决了 用的pip install tortoise-orm
pip install --upgrade tortoise-orm  这个

**Comment by Pikachu067** [comment]
感谢解答 昨天csdn机器人给我解决了 用的pip install tortoise-ormpip install --upgrade tortoise-orm 这两




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 晚上6:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 首次启动bot报错 (Issue #1422)





  
系统版本：win10
 
真寻版本：v0.1.6.7
 
截图
 

 

 
日志
 
(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main&gt;poetry install
 
Installing dependencies from lock file
 
No dependencies to install or update
 
(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main&gt;poetry shell
 
Virtual environment already activated: C:\Users\DELL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-wIer85dA-py3.9
 
(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main&gt;playwright install chromium
 
(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main&gt;python bot.py
 
Traceback (most recent call last):
 
File "D:\bot\zhenxun_bot-main\zhenxun_bot-main\bot.py", line 3, in 
 from services.db_context import init, disconnect  
File "D:\bot\zhenxun_bot-main\zhenxun_bot-main\services_init_.py", line 1, in 
 from .db_context import *  
File "D:\bot\zhenxun_bot-main\zhenxun_bot-main\services\db_context.py", line 5, in 
 from tortoise.connection import connections  
ModuleNotFoundError: No module named 'tortoise.connection'
 
(zhenxun-bot-py3.9) D:\bot\zhenxun_bot-main\zhenxun_bot-main&gt;
 
说明
 
首次启动碰到的 ImportError: cannot import name 'connections' from 'tortoise'  按百度试了半天变成了下面的问题
 
ModuleNotFoundError: No module named 'tortoise.connection' （
  
试一下pip install tortoise.connection？
 记得在虚拟环境在运行

**Comment by PackageInstaller** [comment]
实际上一个`pip install tortoise-orm -U`就好了（
还有记得关闭issue哟
