### ISSUE TITLE
各位大佬，小白求助

### ISSUE THREAD

**Issue by DTR3912** [HibiKier/zhenxun_bot#1423]
请问nonebot商店的插件，生成配置文件在哪里啊，好多配置文件都是说在.env，可是根目录里的.env没有啊，config.yaml里也没有，找了好多文件都没找到，是要自己复制进去吗，还是怎么弄，求教求教😱（插件我装好了，可以正常运行，就是找不到配置文件在哪）

**Comment by neal240** [comment]
> 请问nonebot商店的插件，生成配置文件在哪里啊，好多配置文件都是说在.env，可是根目录里的.env没有啊，config.yaml里也没有，找了好多文件都没找到，是要自己复制进去吗，还是怎么弄，求教求教😱（插件我装好了，可以正常运行，就是找不到配置文件在哪）

多半是指真寻里的.env.dev

**Comment by DTR3912** [comment]
> > 请问nonebot商店的插件，生成配置文件在哪里啊，好多配置文件都是说在.env，可是根目录里的.env没有啊，config.yaml里也没有，找了好多文件都没找到，是要自己复制进去吗，还是怎么弄，求教求教😱（插件我装好了，可以正常运行，就是找不到配置文件在哪）
> 
> 多半是指真寻里的.env.dev

我找了，没有生成啊

**Comment by DTR3912** [comment]
> > > > 请问nonebot商店的插件，生成配置文件在哪里啊，好多配置文件都是说在.env，可是根目录里的.env没有啊，config.yaml里也没有，找了好多文件都没找到，是要自己复制进去吗，还是怎么弄，求教求教😱（插件我装好了，可以正常运行，就是找不到配置文件在哪）
> > 
> > 
> > > 
> > 
> > 
> > > 多半是指真寻里的.env.dev
> > 
> > 
> > 我找了，没有生成啊
> 
> 是在zhenxun_bot目录下的.env.dev 不是在插件目录里的

找过了，也没有啊

**Comment by neal240** [comment]
> > > > > 请问nonebot商店的插件，生成配置文件在哪里啊，好多配置文件都是说在.env，可是根目录里的.env没有啊，config.yaml里也没有，找了好多文件都没找到，是要自己复制进去吗，还是怎么弄，求教求教😱（插件我装好了，可以正常运行，就是找不到配置文件在哪）
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 多半是指真寻里的.env.dev
> 
> > > 
> 
> > > 
> 
> > > 我找了，没有生成啊
> 
> > 
> 
> > 是在zhenxun_bot目录下的.env.dev 不是在插件目录里的
> 
> 
> 
> 找过了，也没有啊

你没有这个文件bot怎么跑得起来的

**Comment by PackageInstaller** [comment]
我来解释一下吧，如有错误，欢迎指出
原版的nonebot插件没有对真寻做适配，对真寻适配了的插件的配置文件在configs/config.yaml中，就算.env.dev中没有相关配置插件也是能运行的，但是会以config.py中默认配置运行，如果你想以自己的配置运行，有以下两种方法

1.在.env.dev中添加插件要求的配置，就像下图这样
![Screenshot_20230518_134004](https://github.com/HibiKier/zhenxun_bot/assets/80018096/72bb3429-5487-4d2b-b5ba-e5e5b4f0d560)

2.直接在插件的config.py中进行修改（如果有这个文件的话），如下图
![image](https://github.com/HibiKier/zhenxun_bot/assets/80018096/6aa2735c-8a23-4dff-a7e6-695f402e5098)

**Comment by DTR3912** [comment]
> 我来解释一下吧，如有错误，欢迎指出 原版的nonebot插件没有对真寻做合适的配置，对真寻合适配了的插件的配置文件在configs/config.yaml中，就算.env.d ev中没有相关配置插件也是能运行的，但是会以config.py中默认配置运行，如果你想以自己的配置运行，有以下两种方法
> 
> 1.在.env.dev中添加插件需要的配置，就像下图这样 ![截图_20230518_134004](https://user-images.githubusercontent.com/80018096/239149658-72bb3429-5487-4d2b-b5ba-e5e5b4f0d560.png)
> 
> 2.直接在插件的config.py中进行修改（如果有这个文件的话），如下图 ![图像](https://user-images.githubusercontent.com/80018096/239149939-6aa2735c-8a23-4dff-a7e6-695f402e5098.png)

好的，谢谢大佬。｡◕‿◕｡

**Comment by PackageInstaller** [comment]
> 

如果没有疑问了就close issuse吧
