### ISSUE TITLE
已知问题不支持py3.11

### ISSUE THREAD

**Issue by lhx2136** [HibiKier/zhenxun_bot#1424]
### 错误截图

[img]

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by lhx2136** [comment]
lxml和wordcloud这两个依赖装不上

**Comment by PackageInstaller** [comment]
![image](https://github.com/HibiKier/zhenxun_bot/assets/80018096/9ee4410c-25c8-4cfd-8224-1e511f28ebe1)
python 3.11.3没问题

**Comment by PackageInstaller** [comment]
顺带一提，我也是Arch，poetry 从3.10.10开始用的，Syu升级Python的时候直接也给我升版本了，缺了很多依赖，我手动装的

**Comment by PackageInstaller** [comment]
我已在python3.11.3中成功安装并运行了真寻，poetry install这一步会剩下一个lxml要求4.6.5版本安装不上，但是你可以执行`pip install lxml`手动安装符合你的版本，这不影响Bot启动，之后python bot.py,还会提示你少依赖，按照他说的继续手动装完就好了

**Comment by PackageInstaller** [comment]
![image](https://github.com/HibiKier/zhenxun_bot/assets/80018096/6a277683-6a5f-4348-8206-cf5641604312)
