### ISSUE TITLE
原神绑定cookie报错

### ISSUE THREAD

**Issue by LIUXIMING** [HibiKier/zhenxun_bot#1425]
### 错误截图
![image](https://github.com/HibiKier/zhenxun_bot/assets/20311699/227c6458-804c-4b07-aca5-8f0902eb802f)
![image](https://github.com/HibiKier/zhenxun_bot/assets/20311699/57037ad0-a78e-48d7-8cc1-62e9956bffc2)

**Comment by LIUXIMING** [comment]
大佬邦邦![-731844b964d7a315.jpg](https://github.com/HibiKier/zhenxun_bot/assets/20311699/a14de930-2f84-497b-9793-c5ee76dd0019)

**Comment by PackageInstaller** [comment]
你是不是好久没更新了，我看源码里面就没有你报错的那一行
