### ISSUE TITLE
查看词条功能有大部分图片无法显示

### ISSUE THREAD

**Issue by a930389426** [HibiKier/zhenxun_bot#1428]
![image](https://github.com/HibiKier/zhenxun_bot/assets/59648220/a09a6422-d343-45bd-9459-89119bc9f650)
![image](https://github.com/HibiKier/zhenxun_bot/assets/59648220/782046d9-f12c-495c-bc87-007baa019c6d)

**Comment by HibiKier** [comment]
ac98ec8351e06320f367033fce083d578560030c
