### ISSUE TITLE
真寻从0.1.6.5更新至0.1.6.7后启动失败

### ISSUE THREAD

**Issue by Careful-S** [HibiKier/zhenxun_bot#1429]
系统版本：Ubuntu 20.04
真寻版本：0.1.6.7

错误截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/95528354/8bbdc695-e810-45f0-9a88-6aee10d39e6e)

之前是有提示tortoise没有安装 安装后变成了这样
求dalao邦邦

**Comment by HibiKier** [comment]
更新config.py
