### ISSUE TITLE
群权限功能无法正常使用

### ISSUE THREAD

**Issue by Careful-S** [HibiKier/zhenxun_bot#1430]
### 错误截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/95528354/b450b932-0776-4093-8fd9-a8043e6da427)
![image](https://github.com/HibiKier/zhenxun_bot/assets/95528354/22bc89dd-1417-42ae-9d7f-77560a20d0c9)
![image](https://github.com/HibiKier/zhenxun_bot/assets/95528354/c53c4d6c-126f-4eed-8ee0-d6947943a989)
![image](https://github.com/HibiKier/zhenxun_bot/assets/95528354/9a95c942-7d6e-4442-ab38-c9c68ba2d94b)

### 错误说明

在尝试修改群权限的时候，出现许多错误，并且修改权限不成功

**Comment by Scorpio0398** [comment]
我也是这个问题，大佬有解决办法吗

**Comment by HibiKier** [comment]
> 总开关“休息吧”，在重启后失效 全部改群权限，在重启后恢复至默认，关闭过的重启后会恢复关闭前的状态

试了下，好像没有遇到

**Comment by Nenot233** [comment]
> > 总开关“休息吧”，在重启后失效 全部改群权限，在重启后恢复至默认，关闭过的重启后会恢复关闭前的状态
> 
> 试了下，好像没有遇到

更新了一下可以了，但是又出现[[_task|fudu]]这样的群被动字样，包括解析B站视频也是发送

**Comment by HibiKier** [comment]
> > > 总开关“休息吧”，在重启后失效 全部改群权限，在重启后恢复至默认，关闭过的重启后会恢复关闭前的状态
> > 
> > 
> > 试了下，好像没有遇到
> 
> 更新了一下可以了，但是又出现[[_task|fudu]]这样的群被动字样，包括解析B站视频也是发送

在更新下

**Comment by Nenot233** [comment]
> > > > 总开关“休息吧”，在重启后失效 全部改群权限，在重启后恢复至默认，关闭过的重启后会恢复关闭前的状态
> > > 
> > > 
> > > 试了下，好像没有遇到
> > 
> > 
> > 更新了一下可以了，但是又出现[[_task|fudu]]这样的群被动字样，包括解析B站视频也是发送
> 
> 在更新下

已解决
