### ISSUE TITLE
群消息报错

### ISSUE THREAD

**Issue by cyear** [HibiKier/zhenxun_bot#1431]
### 错误截图

![IMG_20230525_133941.jpg](https://github.com/HibiKier/zhenxun_bot/assets/77969791/dbb2e6e7-8a93-411b-bc1e-336b0c4615ee)

### 日志截图

![IMG_20230525_134107.jpg](https://github.com/HibiKier/zhenxun_bot/assets/77969791/2ee74bfc-2c66-42d3-b804-437f94aedac8)

![IMG_20230525_134119.jpg](https://github.com/HibiKier/zhenxun_bot/assets/77969791/6e0e3808-0e9c-4103-9344-df80eab5de95)

![IMG_20230525_134148.jpg](https://github.com/HibiKier/zhenxun_bot/assets/77969791/ad81a234-db46-4f05-8ad1-e3f620ca42e8)

### 错误说明

无法正常使用

**Comment by HibiKier** [comment]
更新
