### ISSUE TITLE
真寻怎么加载nb-cli安装的插件啊

### ISSUE THREAD

**Issue by 123xuwu** [HibiKier/zhenxun_bot#1434]
我用nb-cli下载了一些插件，想加载到真寻里该咋办

**Comment by PackageInstaller** [comment]
建议git clone下载到你的ex_plugin文件夹

**Comment by 123xuwu** [comment]
好吧



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 10:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

建议git clone下载到你的ex_plugin文件夹

**Comment by 123xuwu** [comment]
那是只克隆插件还是整个git仓库


好吧



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 10:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

建议git clone下载到你的ex_plugin文件夹

**Comment by PackageInstaller** [comment]
插件

**Comment by 123xuwu** [comment]
那咋装依赖啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 12:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

插件

**Comment by PackageInstaller** [comment]
pip install

poetry add

**Comment by 123xuwu** [comment]
poetry add在哪执行啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 12:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

pip install

poetry add

**Comment by PackageInstaller** [comment]
虚拟环境里面，pip install也是要在虚拟环境里面执行

**Comment by 123xuwu** [comment]
是真寻根目录还是插件目录



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 12:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

虚拟环境里面，pip install也是要在虚拟环境里面执行

**Comment by PackageInstaller** [comment]
你启动poetry 就行了，不管在哪里都可以直接装

**Comment by 123xuwu** [comment]
直接poetry add报错了
Not enough arguments (missing: "name")



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 12:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

你启动poetry 就行了，不管在哪里都可以直接装

**Comment by PackageInstaller** [comment]
你要装什么依赖后面接名字啊
poetry add xxxx

**Comment by 123xuwu** [comment]
已经用pip install了还需要poetry add吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 12:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

你要装什么依赖后面接名字啊
poetry add xxxx

**Comment by PackageInstaller** [comment]
不用，二选一

**Comment by 123xuwu** [comment]
原来如此，感谢大佬



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 12:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

不用，二选一

**Comment by PackageInstaller** [comment]
别着急谢，如果你后面插件装多了各种依赖冲突，直接起飞，我现在就是只能舍弃一些插件来保证大部分插件正常运行（

**Comment by 123xuwu** [comment]
啊，还有这种问题啊，pip不是会自动查找冲突吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 12:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

别着急谢，如果你后面插件装多了各种依赖冲突，直接起飞，我现在就是只能舍弃一些插件来保证大部分插件正常运行（

**Comment by PackageInstaller** [comment]
是这样，我举个例子，加入某个插件依赖于SQLAlchemy1.41.4,但是另一个插件又依赖于更高的版本，这时候两个插件就冲突了，你只能保一个

**Comment by 123xuwu** [comment]
这，到时候再说吧



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月29日 12:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HibiKier/zhenxun_bot] 真寻怎么加载nb-cli安装的插件啊 (Issue #1434) |

是这样，我举个例子，加入某个插件依赖于SQLAlchemy1.41.4,但是另一个插件又依赖于更高的版本，这时候两个插件就冲突了，你只能保一个
