### ISSUE TITLE
b站订阅报错

### ISSUE THREAD

**Issue by gakki0611** [HibiKier/zhenxun_bot#1437]
### 错误截图
![image](https://github.com/HibiKier/zhenxun_bot/assets/33803535/bc4017d3-94f0-4b58-b556-673381ab97cb)

### 错误说明
订阅后提示成功，测试发动态后不管用，日志报错

**Comment by xl2729** [comment]
一样, 我是Debian11.7
![QQ图片20230530231556](https://github.com/HibiKier/zhenxun_bot/assets/55801045/5255215b-8f1a-4541-a4f3-c718f9038004)

**Comment by lingsamuel** [comment]
把 bilireq 改回 bilibili-api-python 吧。那边已经更新了新版 api

**Comment by smallmayi** [comment]
> 

来个地址

**Comment by LittIeRed** [comment]
> 把 bilireq 改回 bilibili-api-python 吧。那边已经更新了新版 api

佬，bilibli-api-python会影响playwright的运行吗，翻了下以前issue貌似是因为这个原因才改用bilreq的，我尝试换回bilibili-api-python后卡在playwright截图超时问题上了

**Comment by lingsamuel** [comment]
> > 把 bilireq 改回 bilibili-api-python 吧。那边已经更新了新版 api
> 
> 佬，bilibli-api-python会影响playwright的运行吗，翻了下以前issue貌似是因为这个原因才改用bilreq的，我尝试换回bilibili-api-python后卡在playwright截图超时问题上了

playwright超时是因为鼠鼠的风控严格，要求输入验证码了吧。登陆一下。
