### ISSUE TITLE
功能正常，但图片发不出，只有商店可以

### ISSUE THREAD

**Issue by Domgur0** [HibiKier/zhenxun_bot#1441]
### 真寻版本：0.1.5.3
###配合云崽ws反向连接的

### 错误截图

![C123692F2F9EB216C1A4B32D9097663E](https://github.com/HibiKier/zhenxun_bot/assets/130534195/490818ae-143c-4f3f-8add-efe1d65d2388)

### 日志截图

<img width="704" alt="image" src="https://github.com/HibiKier/zhenxun_bot/assets/130534195/90effa2e-f920-467c-9f5d-b36d9f01c2e3">

### 错误说明

如题，日志好像也没有错误，云崽的图片可以正常发出，应该不是风控吧。
但 真寻部署在香港服务器上，云崽是国内本地，这个应该不会构成问题吧
求救各位大佬！！

**Comment by molanp** [comment]
go-cq日志看看

**Comment by Domgur0** [comment]
这个是我的问题，忘记关了，不好意思，路径没挂载
