### ISSUE TITLE
执行sql语句报错

### ISSUE THREAD

**Issue by NathanSummer** [HibiKier/zhenxun_bot#1443]
### 日志截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/88868171/74a9ce9c-98f4-488c-9467-1bbd4d5362af)

### 错误说明

使用exec UPDATE "sign_group_user" SET impression=** WHERE user_qq=** AND group_id=**语句修改好感度报错

**Comment by PackageInstaller** [comment]
真寻最近在改表结构，user_qq都换成了user_id了我记得，你试试
`exec UPDATE "sign_group_user" SET impression=** WHERE user_id=** AND group_id=**`

**Comment by NathanSummer** [comment]
> 真寻最近在改表结构，user_qq都换成了user_id了我记得，你试试 `exec UPDATE "sign_group_user" SET impression=** WHERE user_id=** AND group_id=**`

换了之后报错是这样滴
![image](https://github.com/HibiKier/zhenxun_bot/assets/88868171/80b90e12-2f14-447b-9cc6-ec37a3ae3d41)

**Comment by PackageInstaller** [comment]
![image](https://github.com/HibiKier/zhenxun_bot/assets/80018096/f42110a2-7519-4b88-8250-99f70a38f177)
你表没打全，我这是没改表结构的，你再试试
`exec update sign_group_users set impression = impression + 100 where user_id = xxx and group_id = xxx;`
这样应该对了

**Comment by NathanSummer** [comment]
> ![image](https://user-images.githubusercontent.com/80018096/243148706-f42110a2-7519-4b88-8250-99f70a38f177.png) 你表没打全，我这是没改表结构的，你再试试 `exec update sign_group_users set impression = impression + 100 where user_id = xxx and group_id = xxx;` 这样应该对了
![image](https://github.com/HibiKier/zhenxun_bot/assets/88868171/2972562f-740a-4cd7-9874-e49be7f25e8e)

![image](https://github.com/HibiKier/zhenxun_bot/assets/88868171/d9881be0-4308-4a84-aa22-7d23257cfe22)

**Comment by PackageInstaller** [comment]
> > ![image](https://user-images.githubusercontent.com/80018096/243148706-f42110a2-7519-4b88-8250-99f70a38f177.png) 你表没打全，我这是没改表结构的，你再试试 `exec update sign_group_users set impression = impression + 100 where user_id = xxx and group_id = xxx;` 这样应该对了
> ![image](https://github.com/HibiKier/zhenxun_bot/assets/88868171/2972562f-740a-4cd7-9874-e49be7f25e8e)
> 
> ![image](https://github.com/HibiKier/zhenxun_bot/assets/88868171/d9881be0-4308-4a84-aa22-7d23257cfe22)
> 

要不咱直接在數據庫裡面操作吧…

**Comment by PackageInstaller** [comment]
不是。你结尾分号呢

**Comment by NathanSummer** [comment]
> 不是。你结尾分号呢

![image](https://github.com/HibiKier/zhenxun_bot/assets/88868171/4f3cf3f6-e90a-452e-9818-2ad84a1eef04)

**Comment by Zxieyuan** [comment]
[https://github.com/HibiKier/zhenxun_bot/issues/1445#issue-1746371536](url)
user_id和group_id前后的数字加上单引号

**Comment by gakki0611** [comment]
> #1445 
> 
> user_id和group_id数字的前后加上单引号

**Comment by slanderou** [comment]
@NathanSummer 
exec update sign_group_users set impression = ’100.000‘ where user_id = ’**‘ and group_id = ’**‘。
在五月份的更新中，user_qq改为了user_id，同时后面报的这个错是不匹配，可能是因为格式改为了字符串因此所有的数据都要像我上面那样使用单引号括起来。

**Comment by Puff-pastry-star** [comment]
我都不知道为啥我直接触发ai了，数据库指令不对吗
![image](https://github.com/user-attachments/assets/4bd8e787-d508-41f0-a386-344c0891bfc1)

**Comment by HibiKier** [comment]
配置超级用户了吗

**Comment by Puff-pastry-star** [comment]
可以正常输出超级用户菜单
![image](https://github.com/user-attachments/assets/187b7e84-397e-46a6-911f-bac2fc321186)

**Comment by HibiKier** [comment]
超级用户帮助中有  执行sql  这个功能吗

**Comment by Puff-pastry-star** [comment]
是的
![image](https://github.com/user-attachments/assets/93fcc40a-350b-406c-9513-d22767d6a901)

**Comment by HibiKier** [comment]
开新的issues，把.env.dev里log_info打开后发命令后发日志
