### ISSUE TITLE
poetry update后bot启动失败

### ISSUE THREAD

**Issue by 534019023** [HibiKier/zhenxun_bot#1444]
### 错误截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/95991937/0c91d771-14cf-420b-9976-88968f0ae588)

### 错误说明

之前更新后报错太多于是想起来poetry没更新，今天更新了一下后发现被删了4个依赖，当时没注意以为不需要了，但是启动的时候报错提醒需要fastapi，我也用pip安装了，再启动让我playwright install一下，再启动就没其他依赖提醒就上面那张图里的报错了，请问这是什么问题，是被删掉的依赖导致的吗

**Comment by zhx79513** [comment]
我也报这个错，反正webui我不用，就把模块目录直接移走了，就可以启动了。
