### ISSUE TITLE
新的docker镜像好像有点小问题

### ISSUE THREAD

**Issue by BestRailgun** [HibiKier/zhenxun_bot#145]
如图
![2022-04-18 093042](https://user-images.githubusercontent.com/53421615/163741185-22c2fff0-ad80-44c8-a2c8-fa13f89c8225.png)
没有修改过文件但是nonebot的运行环境是prod而不是dev，导致所有的插件都没有加载

**Comment by Sakuracio** [comment]
（入口文件中的运行目录写错了 等更新吧）

**Comment by BestRailgun** [comment]
好的，谢谢大佬

**Comment by Sakuracio** [comment]
已经推送了新的镜像
