### ISSUE TITLE
真寻不能回复超级用户的私聊消息，群消息却正常回复

### ISSUE THREAD

**Issue by qq351959684** [HibiKier/zhenxun_bot#1452]
发送消息时py程序和cqhttp的状态看起来正常
![image](https://github.com/HibiKier/zhenxun_bot/assets/61103131/98968ff0-5a4d-4536-9826-d64d680d513b)
![image](https://github.com/HibiKier/zhenxun_bot/assets/61103131/dcbdb3b1-4491-4db0-bf47-42f4850c81e3)
但是QQ里未收到回复
![image](https://github.com/HibiKier/zhenxun_bot/assets/61103131/64d7b60b-eef1-4c93-afed-ac5171d87c01)

**Comment by PackageInstaller** [comment]
风控了

**Comment by lioshushu** [comment]
有什么解决方法吗，例如换个qq或者重装真寻之类的？

**Comment by PackageInstaller** [comment]
> 有什么解决方法吗，例如换个qq或者重装真寻之类的？

重装倒没必要，这个问题还是蛮杂的，号/协议可能哪个的问题吧，反正我用的gocq最新协议也是私聊发不出，群聊倒是没事，把加好友自动通过，还有允许拉群开了，每周定期看看将就着用
