### ISSUE TITLE
我的时区是正常的，但是真寻的早晚安好像不正常

### ISSUE THREAD

**Issue by Domgur0** [HibiKier/zhenxun_bot#1453]
### 错误截图

![-3cc20799ee6ff1cd](https://github.com/HibiKier/zhenxun_bot/assets/130534195/3387b611-62ff-44a1-a659-81be2945b430)

### 错误说明

早晚安时间不正常，重装过一次了还是这样

**Comment by PackageInstaller** [comment]
https://github.com/HibiKier/zhenxun_bot/pull/1427

可能是这个pr说的原因？

**Comment by Domgur0** [comment]
![Screenshot_20230617_072710_alook browser](https://github.com/HibiKier/zhenxun_bot/assets/130534195/96ef2012-e160-4e19-b50b-6487171e697f)
看完佬发的，去看了看真寻的更新提交发现这个，会不会是这个原因

**Comment by Domgur0** [comment]
时间刚好对得上，改改应该就可以了吧

**Comment by molanp** [comment]
检查了一下，是commit 83b108f91f98d2b72d0c30d8fb71d86ed6072853 导致的这个问题

**Comment by Domgur0** [comment]
好耶，解决了！
