### ISSUE TITLE
CSGO开箱模块最后开箱日期只在第一次开箱的时候更新过，之后再开箱就不会再更新了

### ISSUE THREAD

**Issue by zhx79513** [HibiKier/zhenxun_bot#1454]
### 错误截图
![图片](https://github.com/HibiKier/zhenxun_bot/assets/5063357/38dbf79a-9bbd-4b39-8748-224c2a819f29)

![图片](https://github.com/HibiKier/zhenxun_bot/assets/5063357/43cf8b93-0aea-40f2-8ed4-0313c2fb798a)

![图片](https://github.com/HibiKier/zhenxun_bot/assets/5063357/8afcd0cf-cd7e-4523-919b-63e2f3d127e7)

### 错误说明

最后开箱日期实际上是第一次开箱的日期
https://github.com/HibiKier/zhenxun_bot/blob/83b108f91f98d2b72d0c30d8fb71d86ed6072853/plugins/open_cases/open_cases_c.py#L87
open_case方法中，OpenCasesUser只在create的时候传入了时间，在save的时候没有传入时间，所以只有第一次创建的时候才保存了最后开箱日期，之后都没有更新过。

**Comment by HibiKier** [comment]
6519ed7101d4d51bf75b897362dfe8ea6bb241ad
