### ISSUE TITLE
词条的模糊添加似乎有点问题

### ISSUE THREAD

**Issue by SuLiuming** [HibiKier/zhenxun_bot#1456]
苏流明 18:45:26
添加词条模糊问为什么答@苏流明

绪山真寻 18:45:26
添加词条 YES 成功！

大体是这样的 如果不加模糊是正常的 
版本用的是右边Release 但word_bank是用库里面最新替换的

**Comment by SuLiuming** [comment]
补充 关键词”哪里有“ 也不会触发词条

**Comment by HibiKier** [comment]
0a4df8296eb5a89c996077b953622313bab5975a
