### ISSUE TITLE
小真寻的搜番功能报错

### ISSUE THREAD

**Issue by cy-tian** [HibiKier/zhenxun_bot#1457]
搜番的时候一直报错，麻烦各位大佬看看有什么解决方法
![image](https://github.com/HibiKier/zhenxun_bot/assets/68091442/2ccef32a-469d-42c1-87b5-29373c763b23)
![image](https://github.com/HibiKier/zhenxun_bot/assets/68091442/fa1d3c01-4ace-4b93-b7a6-ea7f7c37d193)

**Comment by PackageInstaller** [comment]
我记得是某个依赖等级太高了？

**Comment by HibiKier** [comment]
网络问题
