### ISSUE TITLE
真寻bot按照步骤部署最后无法启动

### ISSUE THREAD

**Issue by acb2333** [HibiKier/zhenxun_bot#1458]
$ python bot.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot\bot.py", line 1, in <module>
    import nonebot
ModuleNotFoundError: No module named 'nonebot'
显示这个东西

前面也有看不懂的
Administrator@WIN10-20220828F MINGW64 ~/Desktop/zhenxun_bot (main)
$ poetry install
**Installing dependencies from lock file** 

Administrator@WIN10-20220828F MINGW64 ~/Desktop/zhenxun_bot (main)
$ poetry shell
Spawning shell within **C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.10**

**Comment by HibiKier** [comment]
你可以把你.lock文件删了重新poetry install
