### ISSUE TITLE
求助：安装Postgresql数据库时遇到问题

### ISSUE THREAD

**Issue by tiehu** [HibiKier/zhenxun_bot#1460]
我知道这个问题不太应该在真寻的Issues里发，但是我已经查找了各种资料，确实没能解决问题。

系统版本：Debian 12（在Linux Deploy上搭建）
Postgresql版本：15

我已仔细遵循了[安装文档](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_postgresql.html)给出的步骤，但在使用psql命令时收到报错信息如下：

psql: 错误: 连接到套接字"/var/run/postgresql/.s.PGSQL.5432"上的服务器失败:没有那个文件或目录
	服务器是否在本地运行并接受该套接字上的连接?

通过命令检查发现Postgresql服务确实是运行状态，重启系统或者重新安装Postgresql皆无法解决，网上提供的五花八门的解决方法也没什么用。

由于找不到更详细的日志文件，能提供的信息不多，见谅。

**Comment by yodsgo** [comment]
怎么不试试看重装系统

**Comment by tiehu** [comment]
> 怎么不试试看重装系统

已经试过了，还换了Linux发行版，还是无法安装成功

**Comment by yodsgo** [comment]
重装完还是一样的错误？

**Comment by yodsgo** [comment]
> > 重装完成还是一样的错误？
> 
> 是

个人经验来说这种情况还是属于安装失败某些东西阻止了.s.PGSQL.5432，不过重装系统不行那要么是服务器提供商有问题或者你安装方法有问题

**Comment by tiehu** [comment]
> > > 重装完成还是一样的错误？
> > 
> > 
> > 是
> 
> 个人经验来说这种情况还是属于安装失败某些东西阻止了.s.PGSQL.5432，不过重装系统不行那要么是服务器提供商有问题或者你安装方法有问题

应该不是，之后测试过完全一样的发行版在实体机系统中是能安装运行的。安装源官方和镜像源都试过，过程也没什么问题。不排除是容器的问题？

**Comment by yodsgo** [comment]
> > > > 重装完成还是同样的错误？
> > > 
> > > 
> > > 是
> > 
> > 
> > 个人经验说这种情况还是属于安装失败某些东西阻止了.s.PGSQL.5432，不过重装系统不行那或者是安装成功有问题或者你安装方法有问题
> 
> 应该不是，之后测试过完全一样的发行版在实体机系统中是能安装运行的。安装源官方和镜像源都试过了，过程也没有问题。不排除是容器的问题吗？

你用容器啊？传统安装方法没试过吗

**Comment by tiehu** [comment]
> > > > > 重装完成还是同样的错误？
> > > > 
> > > > 
> > > > 是
> > > 
> > > 
> > > 个人经验说这种情况还是属于安装失败某些东西阻止了.s.PGSQL.5432，不过重装系统不行那或者是安装成功有问题或者你安装方法有问题
> > 
> > 
> > 应该不是，之后测试过完全一样的发行版在实体机系统中是能安装运行的。安装源官方和镜像源都试过了，过程也没有问题。不排除是容器的问题吗？
> 
> 你用容器啊？传统安装方法没试过吗

和上面最开始说的一样，是在Linux Deploy（基于chroot）中搭建的Debian 12。

**Comment by Eastleimu** [comment]
使用不了这个数据库（如果可以用mysql搞可以指教），说说问题啊：安装会乱码，具体可以看一下给的链接，试了，没用，依旧是这个问题，下载其他安装包可以安装，但在配置的时候不行，需要下载新的，到这也就不想搞了[https://blog.csdn.net/d960704119/article/details/106760469?spm=1001.2101.3001.6650.4&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-4-106760469-blog-130089569.235%5Ev38%5Epc_relevant_anti_vip_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-4-106760469-blog-130089569.235%5Ev38%5Epc_relevant_anti_vip_base&utm_relevant_index=9](url)

**Comment by NSZA156** [comment]
你的PostgreSQL很可能并没有真正启动！这是一个存在于安卓系统上关于内核中CONFIG_ANDROID_PARANOID_NETWORK配置的经典问题，对于用户只有其加入AID_INET和AID_NET_RAW才拥有访问网络的权限。chroot容器中在安装postgreSQL时并不会自动将其添加以上用户组，因此实际上在启动过程中PostgreSQL会因没有权限创建套接字而启动失败，详情请查看启动log。在LinuxDeploy中这几个用户组已被创建，因此你只需要运行`sudo usermod -aG 3001,3002,3003,3004,3005 postgres`来授予其网络访问权限，在此之后重新启动PostgreSQL并尝试连接即可，详情参考https://stackoverflow.com/questions/36451444/what-can-cause-a-socket-permission-denied-error
