### ISSUE TITLE
真寻打不开力

### ISSUE THREAD

**Issue by Cintser** [HibiKier/zhenxun_bot#1461]
### 错误截图
![image](https://github.com/HibiKier/zhenxun_bot/assets/98868806/76d53b8f-fafc-4d47-a1ad-dada3cf76c82)

### 日志截图

[img]

### 错误说明

真寻私聊更新加重启之后打不开力

**Comment by zhx79513** [comment]
configs/config.py文件第11行的缩进错误，打开看下是什么原因

**Comment by HibiKier** [comment]
替换下config.py文件
