### ISSUE TITLE
bilireq报错

### ISSUE THREAD

**Issue by SHDocter** [HibiKier/zhenxun_bot#1462]
```
[ERROR] services | 获取订阅状态发生预料之外的错误 Id_：25488129 || 错误 <class 'playwright._impl._api_types.TimeoutError'>: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator(".bili-dyn-item__main") to be visible
============================================================
[INFO] services | 已成功加载 4 个Cd限制.
[INFO] services | 已成功加载 11 个Block限制.
[ERROR] services | Id：26931657 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
```

**Comment by SS9-0191** [comment]
同样的错误：
[ERROR] services | 获取订阅状态发生预料之外的错误 Id_：144900114 || 错误 <class 'playwright._impl._api_types.TimeoutError'>: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator(".bili-dyn-item__main") to be visible
============================================================
07-25 12:37:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:37:37 [ERROR] services | Id：23947287 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:38:08 [ERROR] services | Id：23237175 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:39:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:39:37 [ERROR] services | Id：159293985 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:40:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:40:37 [ERROR] services | Id：518231549 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试

**Comment by SS9-0191** [comment]
### 遇到了同样的错误：

 `[ERROR]services | 获取订阅状态发生预料之外的错误 Id_：144900114 || 错误 <class 'playwright._impl._api_types.TimeoutError'>: Timeout 30000ms exceeded.

=========================== logs ===========================
waiting for locator(".bili-dyn-item__main") to be visible
============================================================
07-25 12:37:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:37:37 [ERROR] services | Id：23947287 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:38:08 [ERROR] services | Id：23237175 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:39:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:39:37 [ERROR] services | Id：159293985 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:40:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:40:37 [ERROR] services | Id：518231549 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试`

**Comment by SS9-0191** [comment]
遇到了同样的错误：
```
[ERROR] services | 获取订阅状态发生预料之外的错误 Id_：144900114 || 错误 <class 'playwright._impl._api_types.TimeoutError'>: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator(".bili-dyn-item__main") to be visible
============================================================
07-25 12:37:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:37:37 [ERROR] services | Id：23947287 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:38:08 [ERROR] services | Id：23237175 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:39:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:39:37 [ERROR] services | Id：159293985 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:40:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:40:37 [ERROR] services | Id：518231549 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
```

**Comment by LittIeRed** [comment]
> ```
> [ERROR] services | 获取订阅状态发生预料之外的错误 Id_：25488129 || 错误 <class 'playwright._impl._api_types.TimeoutError'>: Timeout 30000ms exceeded.
> =========================== logs ===========================
> waiting for locator(".bili-dyn-item__main") to be visible
> ============================================================
> [INFO] services | 已成功加载 4 个Cd限制.
> [INFO] services | 已成功加载 11 个Block限制.
> [ERROR] services | Id：26931657 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
> ```
问下解决了吗

**Comment by HibiKier** [comment]
呃，我先研究下，看看bilireq那边

**Comment by HibiKier** [comment]
1130569a201127f9afceef61e561142838ebfaac 试试

**Comment by SHDocter** [comment]
![~ 3HLL4MTE@XW1SYS_7FP(E](https://github.com/HibiKier/zhenxun_bot/assets/72510879/5e5fd139-17df-416b-a1cf-4b0f14004556)

根据https://github.com/SK-415/bilireq/pull/26/files 改了传参之后报超时，然后bot会一直发空消息

**Comment by SHDocter** [comment]
那咋处理x

**Comment by smallmayi** [comment]
> ![~ 3HLL4MTE@XW1SYS_7FP(E](https://user-images.githubusercontent.com/72510879/266825430-5e5fd139-17df-416b-a1cf-4b0f14004556.png)
> 
> 根据https://github.com/SK-415/bilireq/pull/26/files 改了传参之后报超时，然后bot会一直发空消息

请问有找到解决方法吗
