### ISSUE TITLE
创建数据库显示实例未持久化

### ISSUE THREAD

**Issue by Ju1YMoon** [HibiKier/zhenxun_bot#1464]
### 错误截图
![image](https://github.com/HibiKier/zhenxun_bot/assets/122370395/a121332a-0d50-444c-9bcb-8647ebc55647)

### 错误说明

在一次重装系统后数据库变得无法使用和连接，即使删除重装问题依旧存在

**Comment by HibiKier** [comment]
这，没遇到过，建议百度
![3f430be9f484d8b922ab98d2251a4526](https://github.com/HibiKier/zhenxun_bot/assets/45528451/045f62d4-a1d2-4e9b-84a9-35bd7598c9cc)
