### ISSUE TITLE
遇到了同样的错误：

### ISSUE THREAD

**Issue by SS9-0191** [HibiKier/zhenxun_bot#1465]
系统版本：Windows10

              遇到了同样的错误：
```
[ERROR] services | 获取订阅状态发生预料之外的错误 Id_：144900114 || 错误 <class 'playwright._impl._api_types.TimeoutError'>: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator(".bili-dyn-item__main") to be visible
============================================================
07-25 12:37:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:37:37 [ERROR] services | Id：23947287 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:38:08 [ERROR] services | Id：23237175 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:39:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:39:37 [ERROR] services | Id：159293985 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:40:07 [ERROR] services | Id：786258 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
07-25 12:40:37 [ERROR] services | Id：518231549 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
```

_Originally posted by @SS9-0191 in https://github.com/HibiKier/zhenxun_bot/issues/1462#issuecomment-1649210598_

**Comment by LittIeRed** [comment]
请问下解决了吗

**Comment by HibiKier** [comment]
不造，看看bilireq那边怎么说

**Comment by tyh81920** [comment]
试试关掉B站订阅?

**Comment by SS9-0191** [comment]
> 试试关掉B站订阅?

试过了，还是报错

**Comment by SS9-0191** [comment]
> 请问下解决了吗

还没有

**Comment by SS9-0191** [comment]
> 试试关掉B站订阅?

关闭B站订阅后私信呼叫真寻情况如下：
`09-03 00:30:11 [SUCCESS] nonebot | OneBot V11 2849663138 | [message.private.friend]: Message -2008645954 from 1667407529 "真寻"
09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
09-03 00:30:11 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
09-03 00:30:11 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
09-03 00:30:11 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.ai)
09-03 00:30:12 [INFO] nonebot | Matcher(type='message', module=plugins.ai) running complete`
此时go-cqhttp情况如下：
`[2023- -09-03 00:30:11] [INF0]: 收到好友****(16****7529) 的消息:真寻(-2008645954)
[2023-09-03 00:30:12] [INFO]: 发送好友1667407529 (1667407529)    的消息: [{"type" :   …   (-755605554)`

不知道有没有帮助

**Comment by SS9-0191** [comment]
> 试试关掉B站订阅?

关闭B站订阅后私信呼叫真寻情况如下：

`09-03 00:30:11 [SUCCESS] nonebot | OneBot V11 2849663138 | [message.private.friend]: Message -2008645954 from 1667407529 "真寻"'
'09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)'
'09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)'
'09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)'
'09-03 00:30:11 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete'
'09-03 00:30:11 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete'
'09-03 00:30:11 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete'
'09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.ai)'
'09-03 00:30:12 [INFO] nonebot | Matcher(type='message', module=plugins.ai) running complete'
'09-03 00:30:49 [WARNING] apscheduler | Execution of job "_ (trigger: interval[0:00:30], next run at: 2023-09-03 00:30:49 CST)" skipped: maximum number of running instances reached (1)`'

此时go-cqhttp显示如下：

`[2023- -09-03 00:30:11] [INF0]: 收到好友****(16*****529) 的消息:真寻(-2008645954)`
‘[2023-09-03 00:30:12] [INFO]: 发送好友16*****529 (16*****529)   的消息: [{"type" :   …   (-755605554)’

(部分个人信息屏蔽，不影响代码及运行）
不知道有没有帮助

**Comment by SS9-0191** [comment]
> > 试试关掉B站订阅?
> 
> 关闭B站订阅后私信呼叫真寻情况如下：
> 
> `09-03 00:30:11 [SUCCESS] nonebot | OneBot V11 2849663138 | [message.private.friend]: Message -2008645954 from 1667407529 "真寻"' '09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)' '09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)' '09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)' '09-03 00:30:11 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete' '09-03 00:30:11 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete' '09-03 00:30:11 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete' '09-03 00:30:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.ai)' '09-03 00:30:12 [INFO] nonebot | Matcher(type='message', module=plugins.ai) running complete' '09-03 00:30:49 [WARNING] apscheduler | Execution of job "_ (trigger: interval[0:00:30], next run at: 2023-09-03 00:30:49 CST)" skipped: maximum number of running instances reached (1)`'
> 
> 此时go-cqhttp显示如下：
> 
> `[2023- -09-03 00:30:11] [INF0]: 收到好友****(16*****529) 的消息:真寻(-2008645954)` ‘[2023-09-03 00:30:12] [INFO]: 发送好友16_**529 (16**_529) 的消息: [{"type" : … (-755605554)’
> 
> (部分个人信息屏蔽，不影响代码及运行） 不知道有没有帮助

代码有点乱，不知道怎么变成一行一行的（悲）

**Comment by tyh81920** [comment]
> 
现在是报哪个错？

**Comment by SS9-0191** [comment]
> 现在是报哪个错？

跟原先一样报错，然后昨晚发送新代码前重装了一次真寻

**Comment by SS9-0191** [comment]
> 现在是报哪个错？

跟最上面的报错一样

**Comment by tyh81920** [comment]
> > 现在是报哪个错？
> 
> 跟最上面的报错一样

把所有的重新启动一次，然后从头到尾看看是哪个模块出现error

**Comment by SS9-0191** [comment]
> > > 现在是报哪个错？
> > 
> > 
> > 跟最上面的报错一样
> 
> 把所有的重新启动一次，然后从头到尾看看是哪个模块出现error

每次只运行一个模块吗

**Comment by HibiKier** [comment]
1130569a201127f9afceef61e561142838ebfaac  试试

**Comment by SS9-0191** [comment]
> [1130569](https://github.com/HibiKier/zhenxun_bot/commit/1130569a201127f9afceef61e561142838ebfaac) 试试

好的

**Comment by SS9-0191** [comment]
> [1130569](https://github.com/HibiKier/zhenxun_bot/commit/1130569a201127f9afceef61e561142838ebfaac) 试试

还是不行。我重新装了bot，在启动前替换了更新后的八个文件，启动后仍然报错
`07-08 15:09:39 [ERROR] nonebot | Failed to import "web_ui"
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "E:\QQBot\Python388\Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\__init__.py", line 15, in <module>
    from .api.logs import router as ws_log_routes
  File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\__init__.py", line 1, in <module>
    from .tabs import *
  File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\tabs\__init__.py", line 1, in <module>
    from .database import *
  File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\tabs\database\__init__.py", line 15, in <module>
    from ....config import QueryDateType
  File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\config.py", line 8, in <module>
    from strenum import StrEnum
ModuleNotFoundError: No module named 'strenum'`

**Comment by HibiKier** [comment]
> > [1130569](https://github.com/HibiKier/zhenxun_bot/commit/1130569a201127f9afceef61e561142838ebfaac) 试试
> 
> 还是不行。我重新装了bot，在启动前替换了更新后的八个文件，启动后仍然报错
> `07-08 15:09:39 [ERROR] nonebot | Failed to import "web_ui"
> Traceback (most recent call last):
>   File "bot.py", line 14, in <module>
>     nonebot.load_plugins("plugins")
>   File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
>     return manager.load_all_plugins()
>   File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
>     return set(
>   File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
>     filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
>     module = importlib.import_module(
>   File "E:\QQBot\Python388\Lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
>     super().exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\__init__.py", line 15, in <module>
>     from .api.logs import router as ws_log_routes
>   File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\__init__.py", line 1, in <module>
>     from .tabs import *
>   File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\tabs\__init__.py", line 1, in <module>
>     from .database import *
>   File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\tabs\database\__init__.py", line 15, in <module>
>     from ....config import QueryDateType
>   File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\config.py", line 8, in <module>
>     from strenum import StrEnum
> ModuleNotFoundError: No module named 'strenum'`

pip install strenum

**Comment by SS9-0191** [comment]
> > > [1130569](https://github.com/HibiKier/zhenxun_bot/commit/1130569a201127f9afceef61e561142838ebfaac) 试试
> > 
> > 
> > 还是不行。我重新装了bot，在启动前替换了更新后的八个文件，启动后仍然报错
> > `07-08 15:09:39 [ERROR] nonebot | Failed to import "web_ui"
> > Traceback (most recent call last):
> > File "bot.py", line 14, in 
> > nonebot.load_plugins("plugins")
> > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
> > return manager.load_all_plugins()
> > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
> > return set(
> > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 169, in 
> > filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
> > > module = importlib.import_module(
> > > File "E:\QQBot\Python388\Lib\importlib__init__.py", line 127, in import_module
> > > return _bootstrap._gcd_import(name[level:], package, level)
> > > File "", line 1014, in _gcd_import
> > > File "", line 991, in _find_and_load
> > > File "", line 975, in _find_and_load_unlocked
> > > File "", line 671, in _load_unlocked
> > > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
> > > super().exec_module(module)
> > > File "", line 783, in exec_module
> > > File "", line 219, in _call_with_frames_removed
> > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui__init__.py", line 15, in 
> > > from .api.logs import router as ws_log_routes
> > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api__init__.py", line 1, in 
> > > from .tabs import *
> > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\tabs__init_.py", line 1, in 
> > > from .database import *
> > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\tabs\database__init_.py", line 15, in 
> > > from ....config import QueryDateType
> > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\config.py", line 8, in 
> > > from strenum import StrEnum
> > > ModuleNotFoundError: No module named 'strenum'`__
> 
> pip install strenum

是没装pip？

**Comment by tyh81920** [comment]
> > > > [1130569](https://github.com/HibiKier/zhenxun_bot/commit/1130569a201127f9afceef61e561142838ebfaac) 试试
> > > 
> > > 
> > > 还是不行。我重新装了bot，在启动前替换了更新后的八个文件，启动后仍然报错
> > > `07-08 15:09:39 [ERROR] nonebot | Failed to import "web_ui"
> > > Traceback (most recent call last):
> > > File "bot.py", line 14, in
> > > nonebot.load_plugins("plugins")
> > > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
> > > return manager.load_all_plugins()
> > > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
> > > return set(
> > > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 169, in
> > > filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
> > > > module = importlib.import_module(
> > > > File "E:\QQBot\Python388\Lib\importlib__init__.py", line 127, in import_module
> > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > File "", line 1014, in _gcd_import
> > > > File "", line 991, in _find_and_load
> > > > File "", line 975, in _find_and_load_unlocked
> > > > File "", line 671, in _load_unlocked
> > > > File "C:\Users\THL\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-nnpqMRRt-py3.8\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
> > > > super().exec_module(module)
> > > > File "", line 783, in exec_module
> > > > File "", line 219, in _call_with_frames_removed
> > > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui__init__.py", line 15, in
> > > > from .api.logs import router as ws_log_routes
> > > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api__init__.py", line 1, in
> > > > from .tabs import *
> > > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\tabs__init_.py", line 1, in
> > > > from .database import *
> > > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\api\tabs\database__init_.py", line 15, in
> > > > from ....config import QueryDateType
> > > > File "E:\QQBot\zhenxun_bot-main\plugins\web_ui\config.py", line 8, in
> > > > from strenum import StrEnum
> > > > ModuleNotFoundError: No module named 'strenum'`__
> > 
> > 
> > pip install strenum
> 
> 是没装pip？

是缺strenum
