### ISSUE TITLE
真寻部署到最后一步寄了

### ISSUE THREAD

**Issue by Shazusa** [HibiKier/zhenxun_bot#1466]
### 错误截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/140448205/40e91dd3-f02a-45be-a261-7eba936f559c)

### 日志截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/140448205/6fe5603d-39aa-4d18-8b35-e5aa74e1ee59)

### 错误说明

按教程一步一步来的，到最后一步了弹ERROR了

**Comment by zhx79513** [comment]
改成user_id

**Comment by Yuanmxc** [comment]
在哪里改啊

**Comment by Yuanmxc** [comment]
> ### 系统版本：WIN11 22H2
> ### 真寻版本：0.1.6.7
> ### 错误截图
> ![image](https://user-images.githubusercontent.com/140448205/256062994-40e91dd3-f02a-45be-a261-7eba936f559c.png)
> 
> ### 日志截图
> ![image](https://user-images.githubusercontent.com/140448205/256063149-6fe5603d-39aa-4d18-8b35-e5aa74e1ee59.png)
> 
> ### 错误说明
> 按教程一步一步来的，到最后一步了弹ERROR了

兄弟，怎么改，看不懂
