### ISSUE TITLE
poetry install报错

### ISSUE THREAD

**Issue by uchzmal** [HibiKier/zhenxun_bot#1469]
### 错误截图

![c535ea0721b51fbd4049e54bd68478a6](https://github.com/HibiKier/zhenxun_bot/assets/117048798/127deb5f-ba07-44b0-9cf7-921686d91fb4)

### 日志截图

[img]
![c535ea0721b51fbd4049e54bd68478a6](https://github.com/HibiKier/zhenxun_bot/assets/117048798/4b4d6d5f-ee52-41fc-9f87-a0975c2ee222)

### 错误说明
安装pyyaml失败

**Comment by relifenoxiao** [comment]
have this problem been solved? I met the same problem

**Comment by uchzmal** [comment]
> 可以试试 sudo apt-get install gcc python3-dev 我之前安装psutil也会有类似的。

还是不行

**Comment by uchzmal** [comment]
> ### 系统版本：Ubuntu 22.04
> ### 真寻版本：0.1.5.3
> ### 错误截图
> ![c535ea0721b51fbd4049e54bd68478a6](https://user-images.githubusercontent.com/117048798/257035613-127deb5f-ba07-44b0-9cf7-921686d91fb4.png)
> 
> ### 日志截图
> [img] ![c535ea0721b51fbd4049e54bd68478a6](https://user-images.githubusercontent.com/117048798/257035618-4b4d6d5f-ee52-41fc-9f87-a0975c2ee222.png)
> 
> ### 错误说明
> 安装pyyaml失败

**Comment by acm233** [comment]
Windows11 Python 3.10.6 好像遇到了同样的问题
<img width="1280" alt="image" src="https://github.com/HibiKier/zhenxun_bot/assets/97425519/e815701f-cab1-4cd8-a2d2-eda3290b210b">
<img width="1280" alt="image" src="https://github.com/HibiKier/zhenxun_bot/assets/97425519/8cda9319-9a8c-49a9-a185-e1b8d5b69fb2">
都是在安装pyyaml的时候失败

**Comment by uchzmal** [comment]
> Windows11 Python 3.10.6 好像遇到了同样的问题 <img alt="image" width="1280" src="https://user-images.githubusercontent.com/97425519/257437106-e815701f-cab1-4cd8-a2d2-eda3290b210b.png"> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/97425519/257437167-8cda9319-9a8c-49a9-a185-e1b8d5b69fb2.png"> 都是在安装pyyaml的时候失败

你这个背景怎么搞的，可以教我吗

**Comment by acm233** [comment]
> > Windows11 Python 3.10.6 好像遇到了同样的问题 <img alt="image" width="1280" src="https://user-images.githubusercontent.com/97425519/257437106-e815701f-cab1-4cd8-a2d2-eda3290b210b.png"> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/97425519/257437167-8cda9319-9a8c-49a9-a185-e1b8d5b69fb2.png"> 都是在安装pyyaml的时候失败
> 
> 你这个背景怎么搞的，可以教我吗

设置->配置文件->默认值->外观->背景图像路径

附上原图:
![image](https://github.com/HibiKier/zhenxun_bot/assets/97425519/8e9dac37-5ae8-401f-adc4-02b6e47750a5)

**Comment by 1402056242** [comment]
> 感谢@群猫娘帮忙解决了这个问题 ![IMG_20230801_193247](https://user-images.githubusercontent.com/117048798/257501562-48ae2059-46ad-43f0-ac77-a16eefd78e8e.jpg) 可以参考一下这个解决方案

![J7 (_QB ~O1TD FL_4PT7HH](https://github.com/HibiKier/zhenxun_bot/assets/141205093/ba85a6d6-9379-4748-857c-07812e252cca)
我改了之后还是不行啊，有什么版本行吗？

**Comment by uchzmal** [comment]
> > 感谢@群猫娘帮忙解决了这个问题 ![IMG_20230801_193247](https://user-images.githubusercontent.com/117048798/257501562-48ae2059-46ad-43f0-ac77-a16eefd78e8e.jpg) 可以参考一下这个解决方案
> 
> ![J7 (_QB ~O1TD FL_4PT7HH](https://user-images.githubusercontent.com/141205093/257702091-ba85a6d6-9379-4748-857c-07812e252cca.png) 我改了之后还是不行啊，有什么版本行吗？

5.3.0可以
往低改

**Comment by nighamare** [comment]
![image](https://github.com/HibiKier/zhenxun_bot/assets/93499735/a5e18588-6a68-42eb-92d2-f8eb9208fa52)
![image](https://github.com/HibiKier/zhenxun_bot/assets/93499735/2dd315dd-cfb5-4ca8-8723-6e0b8afcdcc9)
然后poetry install
出现报错就运行
poetry lock --no-update

**Comment by uchzmal** [comment]
> ![image](https://user-images.githubusercontent.com/93499735/258583981-a5e18588-6a68-42eb-92d2-f8eb9208fa52.png) ![image](https://user-images.githubusercontent.com/93499735/258583997-2dd315dd-cfb5-4ca8-8723-6e0b8afcdcc9.png) 然后poetry install 出现报错就运行 poetry lock --no-update

让你往低改，还不听
实测5.3.0可以

**Comment by Yuzii11** [comment]
Because zhenxun-bot depends on PyYAML (5.3.1) which doesn't match any versions, version solving failed.我也是报这个  有大哥解决了嘛 
)

**Comment by uchzmal** [comment]
> Because zhenxun-bot depends on PyYAML (5.3.1) which doesn't match any versions, version solving failed.我也是报这个 有大哥解决了嘛 )

自己看上面啊，改版本5.3.0
