### ISSUE TITLE
[bug]管理员帮助图片图层问题

### ISSUE THREAD

**Issue by misaka10843** [HibiKier/zhenxun_bot#147]
不知道是特定的机器中出现的问题还是本身就是有这个问题
在我测试的时候，发现管理员帮助图片中的背景图层高于文字图层
虽然没有太大关系，但是还是希望能修一下qwq
（本菜鸟看了下源码，没什么问题的感觉www，感觉是机器问题www）
![图片](https://user-images.githubusercontent.com/69132853/163815392-610c4b50-f7b5-4df3-9a75-ba2c0e11e8f2.png)

**Comment by HibiKier** [comment]
不是你的问题捏，代码问题

**Comment by HibiKier** [comment]
晚上修修
