### ISSUE TITLE
一人血书，抽卡插件再增加一个重返未来1999

### ISSUE THREAD

**Issue by saltyplum** [HibiKier/zhenxun_bot#1471]
![image](https://github.com/HibiKier/zhenxun_bot/assets/42204608/9984e201-d7a6-4476-9e68-9f4f07324c9b)

**Comment by izasaraba** [comment]
别急，方舟的抽卡好像都有问题，等先修完（要不修完加个1999和铁道

**Comment by LittIeRed** [comment]
太好了太好了，希望先加1999（喜
