### ISSUE TITLE
手动安装提示找不到cv2模块

### ISSUE THREAD

**Issue by nanxu2019** [HibiKier/zhenxun_bot#1473]
### 错误截图
![PO82 FX 8CV2NYPS4 GV@WH](https://github.com/HibiKier/zhenxun_bot/assets/108602897/c010ac0d-4b18-4021-923b-3b24b38a669c)

### 错误说明
使用简易部署教程，进入poetry虚拟环境后运行提示ImportError: DLL load failed while importing cv2: 找不到指定的模块。
手动用pip安装OpenCV-Python也是找不到模块。。。

**Comment by LittIeRed** [comment]
下载最新版真寻试试

**Comment by nanxu2019** [comment]
哦好吧

**Comment by HibiKier** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/373
