### ISSUE TITLE
自行添加新插件时出现问题

### ISSUE THREAD

**Issue by simpleYOTO** [HibiKier/zhenxun_bot#1477]
### 真寻版本：0.1.5.3

自行添加插件(自建了一个新文件夹，并且将插件放入新文件夹，用poetry安装)后启动bot.py。有些插件未导入(如nonebot_plugin_pixivbot），有些插件导入成功但未运行(如read_60,每日一句)，有些是可以导入成功且运行成功。

恳请大佬指教

**Comment by HibiKier** [comment]
你应该看导入运行的具体报错是什么，然后根据报错来解决问题

**Comment by simpleYOTO** [comment]
现在的问题是我导入了一个插件，在我运行bot.py的时候这个插件都没有出现，Succeeded to import里面没有这个插件。我是已经在虚拟环境安装，然后在bot.py添加load该插件的代码。大佬有遇到这样子的问题吗，我之前自己搞bot也没有出现显示导入都没有的，我其他插件是有显示导入成功的。就是这个nonebot_plugin_pixivbot插件，是因为不兼容吗？恳请大佬指教

**Comment by simpleYOTO** [comment]
> 你应该看导入运行的具体报错是什么，然后根据报错来解决问题

现在的问题是我导入了一个插件，在我运行bot.py的时候这个插件都没有出现，Succeeded to import里面没有这个插件。我是已经在虚拟环境安装，然后在bot.py添加load该插件的代码。大佬有遇到这样子的问题吗，我之前自己搞bot也没有出现显示导入都没有的，我其他插件是有显示导入成功的。就是这个nonebot_plugin_pixivbot插件，是因为不兼容吗？恳请大佬指教

**Comment by HibiKier** [comment]
![图片](https://github.com/HibiKier/zhenxun_bot/assets/45528451/b9aca646-6c24-4713-babf-850d8c36ad3c)
你是把这个文件夹放进去的吧

**Comment by simpleYOTO** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/263544591-b9aca646-6c24-4713-babf-850d8c36ad3c.png) 你是把这个文件夹放进去的吧

我放的是上一级的pixivbot

**Comment by HibiKier** [comment]
放这个

**Comment by simpleYOTO** [comment]
> 放这个

感谢大佬，确实有显示导入了
