### ISSUE TITLE
真寻答非所问如何解决

### ISSUE THREAD

**Issue by izasaraba** [HibiKier/zhenxun_bot#1480]
### 错误截图

![95(QS}PZ`KKMWG{RWNCD~ZM](https://github.com/HibiKier/zhenxun_bot/assets/123343468/8fc6b51c-bd0b-4ffa-8888-946a3ce2e05d)

### 日志截图
![@({D@_XY6Y SBXC`0{RCPH1](https://github.com/HibiKier/zhenxun_bot/assets/123343468/82c81925-5050-4232-9866-69e251d2da61)

[img]

### 错误说明

对于一些发言，回答有些奇怪，例如开箱但是却不回复有关箱子，包括平时其他发言比如“骂我”，好像只是从语音库挑一条语音出来，答非所问的感觉，请问如何解决。

**Comment by OVOU4** [comment]
猜测用了Python3.9以上的版本，这个问题我也碰到了，是有些插件加载了却无法触发，可能是推测是由于pyyaml用了6.0.1版本过高引起的，也有可能是其他原因

**Comment by OVOU4** [comment]
开箱插件只有群聊功能，没有私聊，这个貌似要改源码

**Comment by OVOU4** [comment]
> > 猜测用了Python3.9以上的版本，这个问题我也碰到了，是有些插件加载了却无法触发，可能是推测是由于pyyaml用了6.0.1版本过高引起的，也有可能是其他原因
> 
> 后续去了解了一下，首先一些功能由于有AI插件，优先级被AI插件盖过去了，其次类似于开箱这种功能实测是在群聊中可以使用的，可能没同步到个人？（
开箱插件只有群聊功能，没有私聊，这个貌似要改源码

**Comment by OVOU4** [comment]
开箱插件只有群聊功能，没有私聊，这个貌似要改源码

**Comment by izasaraba** [comment]
> 开箱插件只有群聊功能，没有私聊，这个貌似要改源码

今天又看了一下，好像群聊也触发不了（？，去插件那里看了一下，感觉是和方舟一样少了插件

**Comment by HibiKier** [comment]
![图片](https://github.com/HibiKier/zhenxun_bot/assets/45528451/af94f37b-62db-472f-8152-a23f4c5267d9)
只有群聊可以触发，群聊中触发不了需要查看是否风控，数据库是否有武器箱
