### ISSUE TITLE
真寻启动报错date value out of range

### ISSUE THREAD

**Issue by meng-luo** [HibiKier/zhenxun_bot#1481]
### 错误截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/79274361/604f036a-cb62-4327-b853-bbabf080d599)
### 错误说明
pull最新分支后，启动时报错

**Comment by Mira-LeafTown** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/262396350-540664a0-14e5-4948-867b-c78613e56a3f.png) linux上小乌龟连接设置时区的时候可能会报，你可以先把这个去掉

这个在以后会修复嘛）

**Comment by HibiKier** [comment]
> > ![图片](https://user-images.githubusercontent.com/45528451/262396350-540664a0-14e5-4948-867b-c78613e56a3f.png) linux上小乌龟连接设置时区的时候可能会报，你可以先把这个去掉
> 
> 这个在以后会修复嘛）

先去掉了
