### ISSUE TITLE
不会弄 一直不行

### ISSUE THREAD

**Issue by x-fong** [HibiKier/zhenxun_bot#1482]
### 错误截图

![QQ截图20230823210723](https://github.com/HibiKier/zhenxun_bot/assets/139618144/1e961601-48f5-40e9-bf3e-2a78c5ecbe0c)

### 错误说明

一开始打不开 报错已经下了的nonebot
No module named 。。。
下了之后ModuleNotFoundError: No module named 'nonebot.adapters" 可能有所出入 没截图
重启电脑又再次报错No module named "nonebot"
重下了一次打开后 报错No module named 'tortoise“
输入一遍pip install tortoise
 note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
好像下载出了什么错误
再次打开bot.py 报错ModuleNotFoundError: No module named 'tortoise.connection'
本人第一次弄 什么也不懂 可能漏了些细节 还望指教

**Comment by Nenot233** [comment]
试试pip install tortoise-orm

**Comment by x-fong** [comment]
Traceback (most recent call last):
  File "C:\Users\Public\Desktop\zhenxun_bot-0.1.6.7\bot.py", line 2, in <module>
    from nonebot.adapters.onebot.v11 import Adapter
ModuleNotFoundError: No module named 'nonebot.adapters'
这几次重启电脑错误又显示ModuleNotFoundError: No module named 'nonebot.adapters'
nonebot下了 python版本是3.10 不知道是何原因

**Comment by x-fong** [comment]
启动又好了 试了刚刚"试试pip install tortoise-orm
还是不行
![QQ截图20230824125448](https://github.com/HibiKier/zhenxun_bot/assets/139618144/f79d6663-2164-45a4-a44a-83423a236bda)

**Comment by x-fong** [comment]
> 试试pip install tortoise-orm
![image](https://github.com/HibiKier/zhenxun_bot/assets/139618144/0b16d094-623e-44cb-8139-b6aeb6aaedac)
还是不行QAQ

**Comment by izasaraba** [comment]
自己用poetry help查找所需要的安装包，然后放在一个txt文件里面，例如requirements.txt，然后用指令下载，记得先删除poetry的虚拟环境所在的文件夹，ubuntu下为/root/.cache/pypoetry/virtualenvs。然后进入虚拟环境，使用pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple安装

**Comment by izasaraba** [comment]
aiofiles==0.8.0
aiohttp==3.7.4.post0
aiosqlite==0.17.0
anyio==3.6.2
apscheduler==3.9.1.post1
async-timeout==3.0.1
asyncpg==0.27.0
attrs==22.2.0
beautifulsoup4==4.9.3
bilireq==0.2.3.post0
black==22.12.0
cachetools==5.2.0
cattrs==22.2.0
certifi==2022.12.7
chardet==4.0.0
click==8.1.3
cn2an==0.5.19
colorama==0.4.6
commonmark==0.9.1
contourpy==1.0.6
cycler==0.11.0
dateparser==1.1.4
ecdsa==0.18.0
emoji==1.7.0
exceptiongroup==1.1.0
fastapi==0.88.0
feedparser==6.0.10
fonttools==4.38.0
greenlet==2.0.1
grpcio==1.51.1
h11==0.14.0
httpcore==0.16.3
httptools==0.5.0
httpx==0.23.1
idna==3.4
imagehash==4.3.1
importlib-metadata==5.2.0
iso8601==1.1.0
jieba==0.42.1
jinja2==3.1.2
kiwisolver==1.4.4
loguru==0.6.0
lxml==4.6.5
markdown==3.4.1
markupsafe==2.1.1
matplotlib==3.6.2
msgpack==1.0.4
multidict==6.0.3
mypy-extensions==0.4.3
nonebot-adapter-onebot==2.2.0
nonebot-plugin-apscheduler==0.2.0
nonebot-plugin-htmlrender==0.2.0.1
nonebot2==2.0.0rc2
numpy==1.24.0
opencv-python==4.6.0.66
packaging==22.0
pathspec==0.10.3
pillow==9.3.0
platformdirs==2.6.0
playwright==1.29.0
proces==0.1.3
protobuf==4.21.12
psutil==5.9.4
pyasn1==0.4.8
pydantic==1.10.2
pyee==9.0.4
pygments==2.13.0
pygtrie==2.5.0
pymdown-extensions==9.9
pyparsing==3.0.9
pypika-tortoise==0.1.6
pypinyin==0.46.0
python-dateutil==2.8.2
python-dotenv==0.21.0
python-jose==3.3.0
python-markdown-math==0.8
python-multipart==0.0.5
pytz==2022.7
pytz-deprecation-shim==0.1.0.post0
pywavelets==1.4.1
pyyaml==5.4.1
regex==2022.10.31
retrying==1.3.4
rfc3986==1.5.0
rich==12.6.0
rsa==4.9
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scipy==1.9.3
setuptools-scm==7.1.0
sgmllib3k==1.0.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
starlette==0.22.0
tomli==2.0.1
tomlkit==0.11.6
tortoise-orm==0.19.3
typing-extensions==4.4.0
tzdata==2022.7
tzlocal==4.2
ujson==5.6.0
uvicorn==0.20.0
watchfiles==0.18.1
websockets==10.4
win32-setctime==1.1.0
wordcloud==1.8.2.2
yarl==1.8.2
zipp==3.11.0
（这是0.1.6.7的requirements对应的插件，如果版本一样可以直接复制

**Comment by x-fong** [comment]
> ip3 install -r requirements.txt -i [https://pypi.tuna.tsinghua.edu.cn/simple](https://pypi.tuna.tsinghua.edu.cn/simple%E5%AE%89%E8%A3%85)
![QQ截图20230828201037](https://github.com/HibiKier/zhenxun_bot/assets/139618144/d1820f00-a4e3-48b2-8ca8-1ef8edab52a1)

版本一样对着复制了 出现了下面俩段报错 QAQ
![QQ截图20230828201055](https://github.com/HibiKier/zhenxun_bot/assets/139618144/c4ebd8e6-9bbd-46e7-ad4a-cfe370b89513)

**Comment by txzhao2023** [comment]
我补充下，可能是这个情况：不知道是哪里出了问题，题主应该已经完美的安装了所有的依赖，但是他就是显示NO MODULE NAME......我在试图使用chatgpt的openai依赖的时候就是这样。安装好了openai，但是用的时候就是给你显示no module name openai
