### ISSUE TITLE
在群聊发送色图时报错date value out of range，但私信可以发送成功

### ISSUE THREAD

**Issue by Wh1teHead** [HibiKier/zhenxun_bot#1483]
### 错误截图

[img]
![QQ截图20230823234643](https://github.com/HibiKier/zhenxun_bot/assets/110686200/4e7a54f8-bef5-4660-991e-d39dae921a39)

### 日志
![1](https://github.com/HibiKier/zhenxun_bot/assets/110686200/e1da8b6a-65ff-4112-934c-a9e950d8e29c)
截图
![2](https://github.com/HibiKier/zhenxun_bot/assets/110686200/33d1b591-b509-458c-9dec-9cd7de2f1336)
![3](https://github.com/HibiKier/zhenxun_bot/assets/110686200/024fe16d-014e-4c18-970c-a34ee9f04b2c)
![4](https://github.com/HibiKier/zhenxun_bot/assets/110686200/328254f7-06d7-4a27-8006-d02b4be25011)
![5](https://github.com/HibiKier/zhenxun_bot/assets/110686200/e5372c17-812b-479a-97a5-b0a46b5c9076)

[img]

### 错误说明

在使用色图功能时，往群内发送色图指令会报错，但私聊可以正常发送，同时更改过config.yaml文件后，私聊发送的色图并不会撤回

**Comment by Wh1teHead** [comment]
真寻版本错了，是目前最新的

**Comment by HibiKier** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/1481 试一下这个
