### ISSUE TITLE
真寻在搭建go-cqhttp时使用自动提交，然后出现的网址进不去

### ISSUE THREAD

**Issue by izasaraba** [HibiKier/zhenxun_bot#1485]
### 错误截图

![59E_MFDAQ6H 0MG)~8U3_%I](https://github.com/HibiKier/zhenxun_bot/assets/123343468/d69b8bc6-dca0-490c-8ca7-31131af57d61)

![33)SEDX{ZPG@3F}(BI~HUNV](https://github.com/HibiKier/zhenxun_bot/assets/123343468/9bcef9dd-701d-447f-99ca-d3653f83b996)

![JS $BXQH9 4 V4@_KCGW6IJ](https://github.com/HibiKier/zhenxun_bot/assets/123343468/1d6a3b7d-9a72-4bbf-8e35-ad38f1d2d5f1)

### 错误说明

我已经把梯子关掉了，并且重新下载和反复修改json文件，(protocal从6改成0再改成1），如果改成2进行扫码登录的话，发现账户被风控，看了很多解决办法是将protocal改成1，这样就无法扫码，想问问各位是怎么解决的

**Comment by izasaraba** [comment]
同时如果选择2，可以见到滑动验证码，但是见不到生成的ticket码

**Comment by izasaraba** [comment]
解决办法（复制从go-cqhttp）：
先打开chrome浏览器(或edge, 或类似浏览器), 打开一个空白标签页, 等空白页加载完成后按F12打开开发者模式, 选"Network/网络"选项卡.
gocqhttp里选手动抓取, 复制地址到浏览器之前的空白页里. 这时网络选项卡下边会弹出几行, 表示所有的网络请求. 先不管它, 在浏览器里完成这个滑块.
全完成过几秒之后, 看开发者工具这里不动了, 找到叫"cap_union_new_verify"的一行, 就是这个链接给ticket. 默认选中时右侧会打开"标头/Headers"这个选项卡, 能看到一些网络连接的信息.
不管headers, 选"预览/Preview"选项卡, 右边会有一个js值, js里边有"ticket"项.

**Comment by molanp** [comment]
gocq的网站挂了为什么在真寻仓库发issues

**Comment by HibiKier** [comment]
呃，这个确实应该发gocq那边
