### ISSUE TITLE
pyyaml因poetry.lock文件中强制5.4.1版本无法正常安装

### ISSUE THREAD

**Issue by lizhuolun2010** [HibiKier/zhenxun_bot#1486]
### 错误截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/84306316/952b6362-6a51-4f3c-81dc-882c14526f58)

### 日志截图

（无）

### 错误说明

真寻bot提供插件列表中pyyaml(5.4.1)无法正常安装，并且在pyproject.toml中修改版本后因poetry.lock文件中的设置无法成功安装更新/更旧版本的pyyaml，请尽快对其进行修复

**Comment by lizhuolun2010** [comment]
pyyaml无法安装是共性问题，麻烦尽快修复

**Comment by Tobias272727** [comment]
因为七月的时候更新了cython3.0, ref: https://github.com/yaml/pyyaml/issues/724
降级也是因为这个问题，所以解决方案是fix cython版本。

**Comment by cj1357** [comment]
暂时的解决方法：
1、修改pyproject.toml→PyYAML = "5.3.1"保存
2、执行poetry lock --no-update
3、执行poetry install

**Comment by ThreeAurora** [comment]
这个问题依然存在，之前以为是环境问题，结果确实是pyyaml的问题。我采用掩耳盗铃法，临时换用anaconda去管理包。
（下面不用看了，只是一个笨办法）
1.在控制台，把需要的包导出。
`poetry export -f requirements.txt --output requirements.txt --without-hashes`
2.换anaconda虚拟环境。
3.从requirements.txt里直接删掉pyyaml这行（后面自己手动安装了）
4.在虚拟环境里，`pip install -r requirements.txt`，没有再报错

**Comment by lizhuolun2010** [comment]
> 这个问题依然存在，之前以为是环境问题，结果确实是pyyaml的问题。我采用掩耳盗铃法，临时换用anaconda去管理包。 （下面不用看了，只是一个笨办法） 1.在控制台，把需要的包导出。 `poetry export -f requirements.txt --output requirements.txt --without-hashes` 2.换anaconda虚拟环境。 3.从requirements.txt里直接删掉pyyaml这行（后面自己手动安装了） 4.在虚拟环境里，`pip install -r requirements.txt`，没有再报错

我是直接改了pyproject.toml（5.4.1->6.0.1），然后删掉poetry.lock，最后执行poetry install，等待自动解决冲突和重新生成poetry.lock，同样可以安装成功
