### ISSUE TITLE
CSGO开箱错误

### ISSUE THREAD

**Issue by izasaraba** [HibiKier/zhenxun_bot#1487]
### 错误截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/123343468/5bfcd390-6e4e-415a-9724-ec95d2d9c880)

![image](https://github.com/HibiKier/zhenxun_bot/assets/123343468/bc55d719-2b17-49c6-a3f9-f29d0331ac8e)

### 日志截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/123343468/9f4fa4f1-a1d5-4e95-b84e-9a9c90bb8ce1)

![image](https://github.com/HibiKier/zhenxun_bot/assets/123343468/877307b2-aa9b-4b6a-9e9c-9b17b512851b)

### 错误说明

本身似乎未收录任何武器箱，但是根据教程而言应该是有的，同时更新武器箱的时候不成功，触发了AI插件的回复，想问问怎么解决

**Comment by HibiKier** [comment]
本身确实不带有任何武器箱，应该去buff获取cookie/session，然后发送命令 “更新武器箱命悬一线” 等等，因为怕被封所以访问api的接口很慢

**Comment by izasaraba** [comment]
> 本身确实不带有任何武器箱，应该去buff获取cookie/session，然后发送命令 “更新武器箱命悬一线” 等等，因为怕被封所以访问api的接口很慢

请问一下可以说具体一点吗，还是说作者的文档里面已经写了

**Comment by HibiKier** [comment]
fb26be821bd0ca5c5e7da807a06031eb8298751e 提供了一个新命令，sql文件群中有
