### ISSUE TITLE
红包功能:开红包参数未匹配，信息返回失败

### ISSUE THREAD

**Issue by hotdog404** [HibiKier/zhenxun_bot#1489]
### 错误截图

![企业微信截图_20230906104255](https://github.com/HibiKier/zhenxun_bot/assets/140482848/4ca7ee2c-f171-44f3-a4d5-8a3bad049094)

### 日志截图
![企业微信截图_20230906104034](https://github.com/HibiKier/zhenxun_bot/assets/140482848/5ed7bb1c-50ea-494c-ad3d-cfe0f2807717)

### 错误说明
红包功能，开红包指令输出时，类似参数不匹配，没有让插件接手，导致返回失败。

发生了xx错误...

**Comment by HibiKier** [comment]
报错截全

**Comment by hotdog404** [comment]
不好意思，再补一张完整报错
![企业微信截图_20230906131549](https://github.com/HibiKier/zhenxun_bot/assets/140482848/30afcce0-2feb-4604-91e1-c01d9e3f42f0)

**Comment by hotdog404** [comment]
解决了，我以为是匹配问题，结果是字体问题，少了某种字体

**Comment by hotdog404** [comment]
回过头又看了看代码，把data_source.py", line 136下的getsize(amount)修改为getsize(str(amount))，就可以正常返回信息了

**Comment by hotdog404** [comment]
完结，还有问题我再来问
