### ISSUE TITLE
使用第三方的插件，对于指令回复发生错误

### ISSUE THREAD

**Issue by RocksonLee** [HibiKier/zhenxun_bot#149]
原插件链接为 <https://github.com/SEAFHMC/nonebot-plugin-arcaeabot>

已经按照真寻开发插件指南进行适配 

![image](https://user-images.githubusercontent.com/57697347/164965458-c9c840dd-e8d4-459d-af7d-74bc26e4c5b9.png)

![image](https://user-images.githubusercontent.com/57697347/164965466-5eba6b15-e158-4c3e-a374-02df91843ff0.png)

指令回复发生错误

![image](https://user-images.githubusercontent.com/57697347/164965522-41d49c20-edfc-4e19-8426-fb1c3e468426.png)

寻求解决方式

**Comment by HibiKier** [comment]
暂时先将data["message_type"]替换成data.get("message_type")吧，之后会修
