### ISSUE TITLE
bilireq获取动态失败

### ISSUE THREAD

**Issue by LibrationCrisis** [HibiKier/zhenxun_bot#1490]
### Python版本：3.10.13

已经使用了最新的commit：**https://github.com/HibiKier/zhenxun_bot/commit/1130569a201127f9afceef61e561142838ebfaac**

### 错误截图

![图片](https://github.com/HibiKier/zhenxun_bot/assets/44491001/39365e17-1cde-4426-9c0a-4afd01390677)

**Comment by HibiKier** [comment]
https://github.com/SK-415/HarukaBot/issues/422 看一下这个可以解决，然后等bilireq一个更新
