### ISSUE TITLE
首次运行下载资源耗时过长

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#1491]
本地Ubuntu Server 22.04.3 LTS首次部署和运行zhenxun_bot
版本Commits on Sep 9, 2023: b9a39c2
![Image_1695142829511](https://github.com/HibiKier/zhenxun_bot/assets/105090141/117ac1df-9942-4075-bd5e-8b005f8edc5d)
如图，下载了差不多一个小时，几乎全是超时
想问一下可以更改或删除哪些文件或配置项以使首次运行时不进行这些资源下载？
话说这些陈旧/失效的功能该更新的更新该删的删了吧（）

**Comment by AlanFH1842** [comment]
这个网站好像寄了，plugins\draw_card\handles\fgo_handle.py最后好像是获取头像的代码
