### ISSUE TITLE
HTML Help无法正常显示

### ISSUE THREAD

**Issue by PercyDan54** [HibiKier/zhenxun_bot#1492]
### 错误截图

![2316da2f1612aaf32d22fb0a527c9c66](https://github.com/HibiKier/zhenxun_bot/assets/50285552/443e7b6a-01d2-4ffe-a223-e063c799a870)

### 日志截图

没有报错

### 错误说明
生成的HTML Help都有不同程度的损坏

**Comment by PackageInstaller** [comment]
是不是nonebot插件太多了啊
