### ISSUE TITLE
go-cqhttp停止维护了，真寻要迁移到NTQQ了吗

### ISSUE THREAD

**Issue by saltyplum** [HibiKier/zhenxun_bot#1493]
![image](https://github.com/HibiKier/zhenxun_bot/assets/42204608/5507cbd0-87de-42ab-9c49-89a29629d135)
详见：https://github.com/Mrs4s/go-cqhttp/issues/2471

**Comment by ayakasuki** [comment]
要么适配chronocat 要么shamrock了吧

**Comment by ayakasuki** [comment]
虽然我是TRSS+ws用了挺久

**Comment by ayakasuki** [comment]
> 虽然我是TRSS+ws用了挺久

go-cq因为之前协议适配不如icqq快 很早就trss+ws+zhenxunbot了 [ws-plugin)](https://gitee.com/xiaoye12123/ws-plugin)

**Comment by snakeuncle2** [comment]
> 虽然我是TRSS+ws用了挺久

可以指个路吗兄弟，谢谢

**Comment by MWTJC** [comment]
尝试了安卓模拟器（mumu+magiskdelta+shizuku）装安卓qq+shamrock充当收发器：稳定是稳定，但因为真寻默认代码向收发器传输图片只传生成的图片在win里的路径，位于安卓模拟器内的收发器肯定读不到，所以只能发送文本消息属于是；查了onebot协议虽然也支持base64传图，能解决问题，但终究得改真寻甚至插件源码；准备折腾上面佬讲的trss+ws去了

**Comment by czjdr** [comment]
> 虽然我是TRSS+ws用了挺久
@ayakasuki 
你好，请问是用ws,6连接吗？我这边连后后台404

**Comment by PackageInstaller** [comment]
> chronocat

chronocat我也用上了，不知道是不是真寻的原因，没法合并转发

**Comment by Nozomimahiru** [comment]
很多功能要项目重写了 基本自带功能在QQNT全部失效 有些外部nb2插件还可以正常用

**Comment by PackageInstaller** [comment]
> 很多功能要项目重写了 基本自带功能在QQNT全部失效 有些外部nb2插件还可以正常用

破案了，没法合并转发是ws不支持inux的原因（
