### ISSUE TITLE
出现了 Host system is missing dependencies to run browsers.Missing libraries: libgbm.so.1

### ISSUE THREAD

**Issue by xiaoguang00** [HibiKier/zhenxun_bot#1494]
系统：CentOS 8.5.2111 x86_64(Py3.7.9)
[root@hecs-210451 zhenxun_bot]# poetry shell
Warning: Found deprecated key 'default' or 'secondary' in pyproject.toml configuration for source ali. Please provide the key 'priority' instead. Accepted values are: 'default', 'primary', 'secondary', 'supplemental', 'explicit'.
Spawning shell within /root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8
[root@hecs-210451 zhenxun_bot]# . /root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/bin/activate
(zhenxun-bot-XjfceV-K-py3.8) [root@hecs-210451 zhenxun_bot]# python3 bot.py
10-15 13:09:46 [INFO] services.log | 加载配置完成，共加载 42 个配置组及对应 130 个配置项
10-15 13:09:46 [SUCCESS] nonebot | NoneBot is initializing...
10-15 13:09:46 [INFO] nonebot | Current Env: dev
10-15 13:09:47 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
10-15 13:09:48 [SUCCESS] nonebot | Succeeded to load plugin "update_info" from "basic_plugins.update_info"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "plugin_shop" from "basic_plugins.plugin_shop"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "ban" from "basic_plugins.ban"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "broadcast" from "basic_plugins.broadcast"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "use" from "basic_plugins.shop.use"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "shop_handle" from "basic_plugins.shop.shop_handle"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "buy" from "basic_plugins.shop.buy"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "my_props" from "basic_plugins.shop.my_props"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "gold" from "basic_plugins.shop.gold"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "shop" from "basic_plugins.shop"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "apscheduler" from "basic_plugins.apscheduler"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "group_handle" from "basic_plugins.group_handle"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "clear_data" from "basic_plugins.super_cmd.clear_data"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "update_friend_group_info" from "basic_plugins.super_cmd.update_friend_group_info"
10-15 13:09:49 [SUCCESS] nonebot | Succeeded to load plugin "exec_sql" from "basic_plugins.super_cmd.exec_sql"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "manager_group" from "basic_plugins.super_cmd.manager_group"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "reload_setting" from "basic_plugins.super_cmd.reload_setting"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "set_admin_permissions" from "basic_plugins.super_cmd.set_admin_permissions"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "bot_friend_group" from "basic_plugins.super_cmd.bot_friend_group"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "super_cmd" from "basic_plugins.super_cmd"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "hooks" from "basic_plugins.hooks"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "help" from "basic_plugins.help"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "admin_help" from "basic_plugins.admin_help"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "init_plugin_config" from "basic_plugins.init_plugin_config"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "invite_manager" from "basic_plugins.invite_manager"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "scripts" from "basic_plugins.scripts"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "update_group_member_info" from "basic_plugins.admin_bot_manage.update_group_member_info"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "rule" from "basic_plugins.admin_bot_manage.rule"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "switch_rule" from "basic_plugins.admin_bot_manage.switch_rule"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "timing_task" from "basic_plugins.admin_bot_manage.timing_task"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "custom_welcome_message" from "basic_plugins.admin_bot_manage.custom_welcome_message"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "admin_config" from "basic_plugins.admin_bot_manage.admin_config"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "admin_bot_manage" from "basic_plugins.admin_bot_manage"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "nickname" from "basic_plugins.nickname"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "super_help" from "basic_plugins.super_help"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "chat_message" from "basic_plugins.chat_history.chat_message"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "chat_message_handle" from "basic_plugins.chat_history.chat_message_handle"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "chat_history" from "basic_plugins.chat_history"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "update_gocqhttp" from "plugins.update_gocqhttp"
10-15 13:09:50 [SUCCESS] nonebot | Succeeded to load plugin "epic" from "plugins.epic"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "open_cases" from "plugins.open_cases"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "nbnhhsh" from "plugins.nbnhhsh"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "fudu" from "plugins.fudu"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "search_buff_skin_price" from "plugins.search_buff_skin_price"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "yiqing" from "plugins.yiqing"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "coser" from "plugins.coser"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "almanac" from "plugins.genshin.almanac"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "query_resource_points" from "plugins.genshin.query_resource_points"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "reset_today_query_user_data" from "plugins.genshin.query_user.reset_today_query_user_data"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "query_role" from "plugins.genshin.query_user.query_role"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "genshin_sign" from "plugins.genshin.query_user.genshin_sign"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "mihoyobbs_sign" from "plugins.genshin.query_user.mihoyobbs_sign"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "query_memo" from "plugins.genshin.query_user.query_memo"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "resin_remind" from "plugins.genshin.query_user.resin_remind"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "bind" from "plugins.genshin.query_user.bind"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "query_memo" from "plugins.genshin.query_user.query_memo"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "query_user" from "plugins.genshin.query_user"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "material_remind" from "plugins.genshin.material_remind"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "genshin" from "plugins.genshin"
10-15 13:09:51 [SUCCESS] nonebot | Succeeded to load plugin "send_image" from "plugins.image_management.send_image"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "upload_image" from "plugins.image_management.upload_image"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "delete_image" from "plugins.image_management.delete_image"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "move_image" from "plugins.image_management.move_image"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "image_management" from "plugins.image_management"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "sign_in" from "plugins.sign_in"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "what_anime" from "plugins.what_anime"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "black_word" from "plugins.black_word"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "send_dinggong_voice" from "plugins.send_dinggong_voice"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "check" from "plugins.check"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "fake_msg" from "plugins.fake_msg"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "russian" from "plugins.russian"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "gold_redbag" from "plugins.gold_redbag"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "my_info" from "plugins.my_info"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "white2black_image" from "plugins.white2black_image"
10-15 13:09:52 [SUCCESS] nonebot | Succeeded to load plugin "ai" from "plugins.ai"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "word_clouds" from "plugins.word_clouds"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "cover" from "plugins.alapi.cover"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "poetry" from "plugins.alapi.poetry"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "comments_163" from "plugins.alapi.comments_163"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "jitang" from "plugins.alapi.jitang"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "alapi" from "plugins.alapi"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "update_picture" from "plugins.update_picture"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "aconfig" from "plugins.aconfig"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "bt" from "plugins.bt"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "one_friend" from "plugins.one_friend"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "quotations" from "plugins.quotations"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "roll" from "plugins.roll"
10-15 13:09:53 [SUCCESS] nonebot | Succeeded to load plugin "music" from "plugins.music"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "word_handle" from "plugins.word_bank.word_handle"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "message_handle" from "plugins.word_bank.message_handle"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "word_bank" from "plugins.word_bank"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "pixiv_rank_search" from "plugins.pixiv_rank_search"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "translate" from "plugins.translate"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "about" from "plugins.about"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "mute" from "plugins.mute"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "withdraw" from "plugins.withdraw"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "poke" from "plugins.poke"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "self_message" from "plugins.self_message"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "parse_bilibili_json" from "plugins.parse_bilibili_json"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "statistics_handle" from "plugins.statistics.statistics_handle"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "statistics_hook" from "plugins.statistics.statistics_hook"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "statistics" from "plugins.statistics"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "update_setu" from "plugins.send_setu_.update_setu"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "send_setu" from "plugins.send_setu_.send_setu"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "send_setu_" from "plugins.send_setu_"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "wbtop" from "plugins.wbtop"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "group_welcome_msg" from "plugins.group_welcome_msg"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "search_image" from "plugins.search_image"
10-15 13:09:54 [SUCCESS] nonebot | Succeeded to load plugin "pix_pass_del_keyword" from "plugins.pix_gallery.pix_pass_del_keyword"
10-15 13:09:55 [SUCCESS] nonebot | Succeeded to load plugin "pix_add_keyword" from "plugins.pix_gallery.pix_add_keyword"
10-15 13:09:55 [SUCCESS] nonebot | Succeeded to load plugin "pix_show_info" from "plugins.pix_gallery.pix_show_info"
10-15 13:09:55 [SUCCESS] nonebot | Succeeded to load plugin "pix" from "plugins.pix_gallery.pix"
10-15 13:09:55 [SUCCESS] nonebot | Succeeded to load plugin "pix_update" from "plugins.pix_gallery.pix_update"
10-15 13:09:55 [SUCCESS] nonebot | Succeeded to load plugin "pix_gallery" from "plugins.pix_gallery"
10-15 13:09:55 [SUCCESS] nonebot | Succeeded to load plugin "dialogue" from "plugins.dialogue"
10-15 13:09:56 [SUCCESS] nonebot | Succeeded to load plugin "draw_card" from "plugins.draw_card"
10-15 13:09:56 [SUCCESS] nonebot | Succeeded to load plugin "web_ui" from "plugins.web_ui"
10-15 13:09:56 [SUCCESS] nonebot | Succeeded to load plugin "pid_search" from "plugins.pid_search"
10-15 13:09:56 [SUCCESS] nonebot | Succeeded to load plugin "weather" from "plugins.weather"
10-15 13:09:56 [SUCCESS] nonebot | Succeeded to load plugin "luxun" from "plugins.luxun"
10-15 13:09:57 [SUCCESS] nonebot | Succeeded to load plugin "bilibili_sub" from "plugins.bilibili_sub"
10-15 13:09:57 [SUCCESS] nonebot | Succeeded to load plugin "check_zhenxun_update" from "plugins.check_zhenxun_update"
10-15 13:09:57 [SUCCESS] nonebot | Succeeded to load plugin "search_anime" from "plugins.search_anime"
10-15 13:09:57 [SUCCESS] nonebot | Succeeded to load plugin "task_hook" from "basic_plugins.hooks.task_hook"
10-15 13:09:57 [SUCCESS] nonebot | Succeeded to load plugin "withdraw_message_hook" from "basic_plugins.hooks.withdraw_message_hook"
10-15 13:09:57 [SUCCESS] nonebot | Succeeded to load plugin "chkdsk_hook" from "basic_plugins.hooks.chkdsk_hook"
10-15 13:09:57 [SUCCESS] nonebot | Succeeded to load plugin "auth_hook" from "basic_plugins.hooks.auth_hook"
10-15 13:09:57 [SUCCESS] nonebot | Succeeded to load plugin "other_hook" from "basic_plugins.hooks.other_hook"
10-15 13:09:57 [SUCCESS] nonebot | Succeeded to load plugin "ban_hook" from "basic_plugins.hooks.ban_hook"
10-15 13:09:57 [SUCCESS] nonebot | Running NoneBot...
10-15 13:09:57 [INFO] uvicorn | Started server process [166974]
10-15 13:09:57 [INFO] uvicorn | Waiting for application startup.
10-15 13:09:57 [INFO] services | Database loaded successfully!
10-15 13:09:57 [INFO] nonebot_plugin_apscheduler | Scheduler Started
10-15 13:09:59 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 166, in _lifespan_manager
    await self._lifespan.startup()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/lib/python3.8/site-packages/nonebot/drivers/_lifespan.py", line 36, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/lib/python3.8/site-packages/nonebot/drivers/_lifespan.py", line 30, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "/home/testqqbot/zhenxun_bot/utils/browser.py", line 21, in start_browser
    _browser = await _playwright.chromium.launch()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 14675, in launch
    await self._impl_obj.launch(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/lib/python3.8/site-packages/playwright/_impl/_browser_type.py", line 96, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-XjfceV-K-py3.8/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libgbm.so.1                                      ║
出现了这样的报错，求大佬帮忙解决一下，用yum install libgbm.so.1还是有这个问题

**Comment by PackageInstaller** [comment]
ubuntu下的解决方案，其他发行版去看wiki
sudo apt-get update
sudo apt-get install -y libgbm-dev

**Comment by xiaoguang00** [comment]
装了个yum localinstall ./chromium-117.0.5938.132-1.el8.x86_64.rpm这个然后还有一个依赖项就好了
