### ISSUE TITLE
0166版本真寻启动报错

### ISSUE THREAD

**Issue by alone1324** [HibiKier/zhenxun_bot#1498]
### 错误截图

![WindowsTerminal_3ddCQcYWH4](https://github.com/HibiKier/zhenxun_bot/assets/113954924/d208816c-4621-4cc9-a929-5d73ed5e492b)

### 错误说明
安装老版真寻0.1.6.6时，在启动真寻的时候多文件报错。 python版本是3.9.13 不知道是为什么。

**Comment by 1411484730** [comment]
把旧的数据库删了或者把对应表格中的user_qq字段改成user_id

**Comment by alone1324** [comment]
> 把旧的数据库删除了或者把对应表格中的user_qq字段改成user_id

我把旧的数据库删除了，表格数据中并没有user字段。 但是我的问题已经解决了。感谢你的帮助。

**Comment by alone1324** [comment]
我将python更新到3.10.11且卸载重装数据库（postgreSQL）版本降级到了14.9 重新安装poetry依赖（遇到pyyaml安装失败问题移步https://github.com/HibiKier/zhenxun_bot/issues/1486）后成功启动bot

**Comment by alone1324** [comment]
我将python更新到3.10.11且卸载重装数据库（postgreSQL）版本降级到了14.9重新安装poetry依赖（遇到pyyaml安装失败问题移步https://github.com/HibiKier/zhenxun_bot/issues/1486            成功启动bot
