### ISSUE TITLE
go-cqhttp ws无法连接

### ISSUE THREAD

**Issue by Nothingness-Void** [HibiKier/zhenxun_bot#1499]
### 错误截图
![image](https://github.com/HibiKier/zhenxun_bot/assets/55913486/5b782502-d065-4ec3-ba67-8d69975a536e)
bot已运行
![image](https://github.com/HibiKier/zhenxun_bot/assets/55913486/4386cf9b-bbd3-4d15-afff-3a8d03bba491)
go-cqhttp却无法连接
### 日志截图

[img]

### 错误说明

go-cqhttp无法连接到bot

**Comment by KurosakiRei** [comment]
怎么解决的啊大佬，能告知一声吗，我碰到同样的错误了 "拒绝连接"
