### ISSUE TITLE
PIX功能容易卡住

### ISSUE THREAD

**Issue by Adsicmes** [HibiKier/zhenxun_bot#15]
如题所示 PIX功能容易卡住，导致整个机器人没反应
终端不再输出任何信息只能ctrl+c

**Comment by HibiKier** [comment]
PIX的哪个功能？ 就是 pix 命令吗？

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/127740262-ba12c876-b655-4ce5-9d38-c8f7071f6e4f.png)

**Comment by HibiKier** [comment]
我无法复现？输入pix后，在运行其他命令一切正常，看看日志

**Comment by Adsicmes** [comment]
日志 就是 收不到任何消息 没有任何输出 等待好久之后恢复正常
go-cqhttp正常

**Comment by HibiKier** [comment]
啊，你输入pix命令后的nonebot日志给我康康

**Comment by Adsicmes** [comment]
我没记录（
就是正常输出匹配模块之后
没有任何输出

**Comment by HibiKier** [comment]
你的操作系统时？

**Comment by Adsicmes** [comment]
Ubuntu 20.04 大概

**Comment by HibiKier** [comment]
每次 pix 之后都卡住吗？

**Comment by Adsicmes** [comment]
有  几  率
还挺大的

**Comment by HibiKier** [comment]
我无法复现，可以的话，在plugins/pix_gallery/pix.py中添加一些print来定位耗时的代码

**Comment by Adsicmes** [comment]
好  我尝试一下
可能要在明天了
我把可能的地方加print
明天发

**Comment by HibiKier** [comment]
好的

**Comment by Adsicmes** [comment]
他好像没这情况了（（
