### ISSUE TITLE
一些群组和请求命令不成功，是我打开姿势不对吗？

### ISSUE THREAD

**Issue by moelody** [HibiKier/zhenxun_bot#150]
bot运行还算正常，就是群更新和请求出了点问题，不清楚算不算bug求帮助
![image](https://user-images.githubusercontent.com/30750380/165077163-e0b37e4a-1bac-49fd-b0ee-38f9e314c146.png)
![剪贴板图片](https://user-images.githubusercontent.com/30750380/165077198-2b7b697c-cae4-411f-8ab2-04fc8325c2b8.png)
![剪贴板图片 (1)](https://user-images.githubusercontent.com/30750380/165077202-a3c9ddbb-1c24-484c-bdbf-db900dfb0a3b.png)
python版本是3.8的
![image](https://user-images.githubusercontent.com/30750380/165077847-2b9f981b-55d4-4fc5-bbc1-84b3d2012629.png)

**Comment by HibiKier** [comment]
你这个日志只有ai的，没有更新群信息的日志

**Comment by moelody** [comment]
啊对了上面这个是同意请求的报错信息，这个是更新群信息的日志
![image](https://user-images.githubusercontent.com/30750380/165251085-0dc5d61d-82c7-4307-a849-c1614cb2df21.png)

**Comment by HibiKier** [comment]
试试把数据库里的GroupInfo表删除然后重启bot重新更新
