### ISSUE TITLE
zhenxunbot连接shamrock发送图片的问题

### ISSUE THREAD

**Issue by HuaWaterED** [HibiKier/zhenxun_bot#1501]
### 错误截图

![QQ图片20231126132000](https://github.com/HibiKier/zhenxun_bot/assets/116249117/d2d6cf3d-32dc-410e-9f96-5c2a754b2ba5)

### 日志截图

![Snipaste_2023-11-26_13-20-35](https://github.com/HibiKier/zhenxun_bot/assets/116249117/22eecfeb-8527-4d78-8f7a-778aa5487250)

### 错误说明

zhenxunbot连接shamrock（可以理解为gocq的平替（？），连接成功，并且可以回应文本消息，在发送图片的时候，可能因为shamrock和真寻bot不在同一个机器上导致的报错：找不到一个png文件。我在电脑上看到实际存在这个png文件，shamrock找不到这个文件，可以有其他的方式来尝试上传文件吗？

**Comment by PackageInstaller** [comment]
用base64吧，不过要改源码

**Comment by HuaWaterED** [comment]
emmm，我用另一种方式解决了

**Comment by HuaWaterED** [comment]
就是，把Windows的smb挂载到了安卓手机的/mnt/c目录下，实现了shamrock直接通过路径访问Windows的文件，也可以访问，现在就是，图片会这样：
![Snipaste_2023-11-27_18-00-20](https://github.com/HibiKier/zhenxun_bot/assets/116249117/35366dc6-e444-4132-b82e-99dcffd5ee07)

**Comment by HuaWaterED** [comment]
（我不会python语言，所以想的另一个方法

**Comment by PackageInstaller** [comment]
> 就是，把Windows的smb挂载到了安卓手机的/mnt/c目录下，实现了shamrock直接通过路径访问Windows的文件，也可以访问，现在就是，图片会这样： ![Snipaste_2023-11-27_18-00-20](https://private-user-images.githubusercontent.com/116249117/285815396-35366dc6-e444-4132-b82e-99dcffd5ee07.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzk2OTYsIm5iZiI6MTcwMTA3OTM5NiwicGF0aCI6Ii8xMTYyNDkxMTcvMjg1ODE1Mzk2LTM1MzY2ZGM2LWU0NDQtNDEzMi1iODJlLTk5ZGNmZmQ1ZWUwNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxMDAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjAyZGY3MGJmZTlmZTgyNjAyZDJlYWZjMmE5OWE4NmI4MzQ2ZTNiOWVmY2Q1Yzk0OTJhMWY2NzRlNTQwNmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.88FLEuZYwKvOGpL57-Q7bTVIxVvhRl04SJZfFeadQZM)

Html 版的老问题，换回正常版显示正常

**Comment by YingLing3** [comment]
修改\utils\message_builder.py，修改    if isinstance(file, Path):这个判断下的逻辑，
    if isinstance(file, Path):
        if file.exists():
            # return MessageSegment.image(file)
            try:
                with open(file.absolute(), 'rb') as file:
                    # 读取图片文件并进行 Base64 编码
                    image_data = base64.b64encode(file.read())
                    image_base64 = image_data.decode('utf-8')
                    # print(image_base64)
                    return MessageSegment.image("base64://" + image_base64)
            except FileNotFoundError:
                logger.warning(f"图片 {file.absolute()} 缺失...")
        logger.warning(f"图片 {file.absolute()}缺失...")
别忘了最上面加上import base64
或者你懒直接粘贴我的image方法
def image(
    file: Optional[Union[str, Path, bytes, BuildImage, io.BytesIO]] = None,
    b64: Optional[str] = None,
) -> MessageSegment:
    """
    说明:
        生成一个 MessageSegment.image 消息
        生成顺序：绝对路径(abspath) > base64(b64) > img_name
    参数:
        :param file: 图片文件
        :param b64: 图片base64（兼容旧方法）
    """
    if b64:
        file = b64 if b64.startswith("base64://") else ("base64://" + b64)
    if isinstance(file, str):
        if file.startswith(("http", "base64://")):
            return MessageSegment.image(file)
        else:
            return MessageSegment.image(IMAGE_PATH / file)
    if isinstance(file, Path):
        if file.exists():
            # return MessageSegment.image(file)
            try:
                with open(file.absolute(), 'rb') as file:
                    # 读取图片文件并进行 Base64 编码
                    image_data = base64.b64encode(file.read())
                    image_base64 = image_data.decode('utf-8')
                    # print(image_base64)
                    return MessageSegment.image("base64://" + image_base64)
            except FileNotFoundError:
                logger.warning(f"图片 {file.absolute()} 缺失...")
        logger.warning(f"图片 {file.absolute()}缺失...")
    if isinstance(file, (bytes, io.BytesIO)):
        return MessageSegment.image(file)
    if isinstance(file, BuildImage):
        return MessageSegment.image(file.pic2bs4())
    return MessageSegment.image("")

**Comment by ReactXS** [comment]
> 修改\utils\message_builder.py，修改` if isinstance(file, Path):这个判断下的逻辑，
> 
> ```
>     if isinstance(file, Path):
>         if file.exists():
>             # return MessageSegment.image(file)
>             try:
>                 with open(file.absolute(), 'rb') as file:
>                     # 读取图片文件并进行 Base64 编码
>                     image_data = base64.b64encode(file.read())
>                     image_base64 = image_data.decode('utf-8')
>                     # print(image_base64)
>                     return MessageSegment.image("base64://" + image_base64)
>             except FileNotFoundError:
>                 logger.warning(f"图片 {file.absolute()} 缺失...")
>         logger.warning(f"图片 {file.absolute()}缺失...")
> ```
> 
> 别忘了最上面加上import base64 或者你懒直接粘贴我的image方法
> 
> ```
> def image(
>     file: Optional[Union[str, Path, bytes, BuildImage, io.BytesIO]] = None,
>     b64: Optional[str] = None,
> ) -> MessageSegment:
>     """
>     说明:
>         生成一个 MessageSegment.image 消息
>         生成顺序：绝对路径(abspath) > base64(b64) > img_name
>     参数:
>         :param file: 图片文件
>         :param b64: 图片base64（兼容旧方法）
>     """
>     if b64:
>         file = b64 if b64.startswith("base64://") else ("base64://" + b64)
>     if isinstance(file, str):
>         if file.startswith(("http", "base64://")):
>             return MessageSegment.image(file)
>         else:
>             return MessageSegment.image(IMAGE_PATH / file)
>     if isinstance(file, Path):
>         if file.exists():
>             # return MessageSegment.image(file)
>             try:
>                 with open(file.absolute(), 'rb') as file:
>                     # 读取图片文件并进行 Base64 编码
>                     image_data = base64.b64encode(file.read())
>                     image_base64 = image_data.decode('utf-8')
>                     # print(image_base64)
>                     return MessageSegment.image("base64://" + image_base64)
>             except FileNotFoundError:
>                 logger.warning(f"图片 {file.absolute()} 缺失...")
>         logger.warning(f"图片 {file.absolute()}缺失...")
>     if isinstance(file, (bytes, io.BytesIO)):
>         return MessageSegment.image(file)
>     if isinstance(file, BuildImage):
>         return MessageSegment.image(file.pic2bs4())
>     return MessageSegment.image("")
> ```

nice兄弟

**Comment by sagirisense** [comment]
> 修改\utils\message_builder.py，修改` if isinstance(file, Path):这个判断下的逻辑，
> 
> ```
>     if isinstance(file, Path):
>         if file.exists():
>             # return MessageSegment.image(file)
>             try:
>                 with open(file.absolute(), 'rb') as file:
>                     # 读取图片文件并进行 Base64 编码
>                     image_data = base64.b64encode(file.read())
>                     image_base64 = image_data.decode('utf-8')
>                     # print(image_base64)
>                     return MessageSegment.image("base64://" + image_base64)
>             except FileNotFoundError:
>                 logger.warning(f"图片 {file.absolute()} 缺失...")
>         logger.warning(f"图片 {file.absolute()}缺失...")
> ```
> 
> 别忘了最上面加上import base64 或者你懒得直接粘贴我的图片方法
> 
> ```
> def image(
>     file: Optional[Union[str, Path, bytes, BuildImage, io.BytesIO]] = None,
>     b64: Optional[str] = None,
> ) -> MessageSegment:
>     """
>     说明:
>         生成一个 MessageSegment.image 消息
>         生成顺序：绝对路径(abspath) > base64(b64) > img_name
>     参数:
>         :param file: 图片文件
>         :param b64: 图片base64（兼容旧方法）
>     """
>     if b64:
>         file = b64 if b64.startswith("base64://") else ("base64://" + b64)
>     if isinstance(file, str):
>         if file.startswith(("http", "base64://")):
>             return MessageSegment.image(file)
>         else:
>             return MessageSegment.image(IMAGE_PATH / file)
>     if isinstance(file, Path):
>         if file.exists():
>             # return MessageSegment.image(file)
>             try:
>                 with open(file.absolute(), 'rb') as file:
>                     # 读取图片文件并进行 Base64 编码
>                     image_data = base64.b64encode(file.read())
>                     image_base64 = image_data.decode('utf-8')
>                     # print(image_base64)
>                     return MessageSegment.image("base64://" + image_base64)
>             except FileNotFoundError:
>                 logger.warning(f"图片 {file.absolute()} 缺失...")
>         logger.warning(f"图片 {file.absolute()}缺失...")
>     if isinstance(file, (bytes, io.BytesIO)):
>         return MessageSegment.image(file)
>     if isinstance(file, BuildImage):
>         return MessageSegment.image(file.pic2bs4())
>     return MessageSegment.image("")
> ```

太牛了

**Comment by xingyu42** [comment]
> 修改\utils\message_builder.py，修改` if isinstance(file, Path):这个判断下的逻辑，
> 
> ```
>     if isinstance(file, Path):
>         if file.exists():
>             # return MessageSegment.image(file)
>             try:
>                 with open(file.absolute(), 'rb') as file:
>                     # 读取图片文件并进行 Base64 编码
>                     image_data = base64.b64encode(file.read())
>                     image_base64 = image_data.decode('utf-8')
>                     # print(image_base64)
>                     return MessageSegment.image("base64://" + image_base64)
>             except FileNotFoundError:
>                 logger.warning(f"图片 {file.absolute()} 缺失...")
>         logger.warning(f"图片 {file.absolute()}缺失...")
> ```
> 
> 别忘了最上面加上import base64 或者你懒直接粘贴我的image方法
> 
> ```
> def image(
>     file: Optional[Union[str, Path, bytes, BuildImage, io.BytesIO]] = None,
>     b64: Optional[str] = None,
> ) -> MessageSegment:
>     """
>     说明:
>         生成一个 MessageSegment.image 消息
>         生成顺序：绝对路径(abspath) > base64(b64) > img_name
>     参数:
>         :param file: 图片文件
>         :param b64: 图片base64（兼容旧方法）
>     """
>     if b64:
>         file = b64 if b64.startswith("base64://") else ("base64://" + b64)
>     if isinstance(file, str):
>         if file.startswith(("http", "base64://")):
>             return MessageSegment.image(file)
>         else:
>             return MessageSegment.image(IMAGE_PATH / file)
>     if isinstance(file, Path):
>         if file.exists():
>             # return MessageSegment.image(file)
>             try:
>                 with open(file.absolute(), 'rb') as file:
>                     # 读取图片文件并进行 Base64 编码
>                     image_data = base64.b64encode(file.read())
>                     image_base64 = image_data.decode('utf-8')
>                     # print(image_base64)
>                     return MessageSegment.image("base64://" + image_base64)
>             except FileNotFoundError:
>                 logger.warning(f"图片 {file.absolute()} 缺失...")
>         logger.warning(f"图片 {file.absolute()}缺失...")
>     if isinstance(file, (bytes, io.BytesIO)):
>         return MessageSegment.image(file)
>     if isinstance(file, BuildImage):
>         return MessageSegment.image(file.pic2bs4())
>     return MessageSegment.image("")
> ```

完美解决了问题

**Comment by xingyu42** [comment]
> 修改\utils\message_builder.py，修改` if isinstance(file, Path):这个判断下的逻辑，
> 
> ```
>     if isinstance(file, Path):
>         if file.exists():
>             # return MessageSegment.image(file)
>             try:
>                 with open(file.absolute(), 'rb') as file:
>                     # 读取图片文件并进行 Base64 编码
>                     image_data = base64.b64encode(file.read())
>                     image_base64 = image_data.decode('utf-8')
>                     # print(image_base64)
>                     return MessageSegment.image("base64://" + image_base64)
>             except FileNotFoundError:
>                 logger.warning(f"图片 {file.absolute()} 缺失...")
>         logger.warning(f"图片 {file.absolute()}缺失...")
> ```
> 
> 别忘了最上面加上import base64 或者你懒直接粘贴我的image方法
> 
> ```
> def image(
>     file: Optional[Union[str, Path, bytes, BuildImage, io.BytesIO]] = None,
>     b64: Optional[str] = None,
> ) -> MessageSegment:
>     """
>     说明:
>         生成一个 MessageSegment.image 消息
>         生成顺序：绝对路径(abspath) > base64(b64) > img_name
>     参数:
>         :param file: 图片文件
>         :param b64: 图片base64（兼容旧方法）
>     """
>     if b64:
>         file = b64 if b64.startswith("base64://") else ("base64://" + b64)
>     if isinstance(file, str):
>         if file.startswith(("http", "base64://")):
>             return MessageSegment.image(file)
>         else:
>             return MessageSegment.image(IMAGE_PATH / file)
>     if isinstance(file, Path):
>         if file.exists():
>             # return MessageSegment.image(file)
>             try:
>                 with open(file.absolute(), 'rb') as file:
>                     # 读取图片文件并进行 Base64 编码
>                     image_data = base64.b64encode(file.read())
>                     image_base64 = image_data.decode('utf-8')
>                     # print(image_base64)
>                     return MessageSegment.image("base64://" + image_base64)
>             except FileNotFoundError:
>                 logger.warning(f"图片 {file.absolute()} 缺失...")
>         logger.warning(f"图片 {file.absolute()}缺失...")
>     if isinstance(file, (bytes, io.BytesIO)):
>         return MessageSegment.image(file)
>     if isinstance(file, BuildImage):
>         return MessageSegment.image(file.pic2bs4())
>     return MessageSegment.image("")
> ```

高兴太早了，其他都可以了就剩下帮助怎么都不行，最后只能直接挂载目录了

**Comment by YuS1aN** [comment]
> > 修改\utils\message_builder.py，修改` if isinstance(file, Path):这个判断下的逻辑，
> > ```
> >     if isinstance(file, Path):
> >         if file.exists():
> >             # return MessageSegment.image(file)
> >             try:
> >                 with open(file.absolute(), 'rb') as file:
> >                     # 读取图片文件并进行 Base64 编码
> >                     image_data = base64.b64encode(file.read())
> >                     image_base64 = image_data.decode('utf-8')
> >                     # print(image_base64)
> >                     return MessageSegment.image("base64://" + image_base64)
> >             except FileNotFoundError:
> >                 logger.warning(f"图片 {file.absolute()} 缺失...")
> >         logger.warning(f"图片 {file.absolute()}缺失...")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 别忘了最上面加上import base64 或者你懒直接粘贴我的image方法
> > ```
> > def image(
> >     file: Optional[Union[str, Path, bytes, BuildImage, io.BytesIO]] = None,
> >     b64: Optional[str] = None,
> > ) -> MessageSegment:
> >     """
> >     说明:
> >         生成一个 MessageSegment.image 消息
> >         生成顺序：绝对路径(abspath) > base64(b64) > img_name
> >     参数:
> >         :param file: 图片文件
> >         :param b64: 图片base64（兼容旧方法）
> >     """
> >     if b64:
> >         file = b64 if b64.startswith("base64://") else ("base64://" + b64)
> >     if isinstance(file, str):
> >         if file.startswith(("http", "base64://")):
> >             return MessageSegment.image(file)
> >         else:
> >             return MessageSegment.image(IMAGE_PATH / file)
> >     if isinstance(file, Path):
> >         if file.exists():
> >             # return MessageSegment.image(file)
> >             try:
> >                 with open(file.absolute(), 'rb') as file:
> >                     # 读取图片文件并进行 Base64 编码
> >                     image_data = base64.b64encode(file.read())
> >                     image_base64 = image_data.decode('utf-8')
> >                     # print(image_base64)
> >                     return MessageSegment.image("base64://" + image_base64)
> >             except FileNotFoundError:
> >                 logger.warning(f"图片 {file.absolute()} 缺失...")
> >         logger.warning(f"图片 {file.absolute()}缺失...")
> >     if isinstance(file, (bytes, io.BytesIO)):
> >         return MessageSegment.image(file)
> >     if isinstance(file, BuildImage):
> >         return MessageSegment.image(file.pic2bs4())
> >     return MessageSegment.image("")
> > ```
> 
> 高兴太早了，其他都可以了就剩下帮助怎么都不行，最后只能直接挂载目录了

把上面返回MessageSegment那行改成file转Path就行了
```
            # return MessageSegment.image(IMAGE_PATH / file)
            file = Path(IMAGE_PATH / file)
```

**Comment by xingyu42** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月10日(周三) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HibiKier/zhenxun_bot] zhenxunbot连接shamrock发送图片的问题 (Issue #1501)




   
修改\utils\message_builder.py，修改` if isinstance(file, Path):这个判断下的逻辑，
     if isinstance(file, Path):         if file.exists():             # return MessageSegment.image(file)             try:                 with open(file.absolute(), 'rb') as file:                     # 读取图片文件并进行 Base64 编码                     image_data = base64.b64encode(file.read())                     image_base64 = image_data.decode('utf-8')                     # print(image_base64)                     return MessageSegment.image("base64://" + image_base64)             except FileNotFoundError:                 logger.warning(f"图片 {file.absolute()} 缺失...")         logger.warning(f"图片 {file.absolute()}缺失...")  
别忘了最上面加上import base64 或者你懒直接粘贴我的image方法
 def image(     file: Optional[Union[str, Path, bytes, BuildImage, io.BytesIO]] = None,     b64: Optional[str] = None, ) -&gt; MessageSegment:     """     说明:         生成一个 MessageSegment.image 消息         生成顺序：绝对路径(abspath) &gt; base64(b64) &gt; img_name     参数:         :param file: 图片文件         :param b64: 图片base64（兼容旧方法）     """     if b64:         file = b64 if b64.startswith("base64://") else ("base64://" + b64)     if isinstance(file, str):         if file.startswith(("http", "base64://")):             return MessageSegment.image(file)         else:             return MessageSegment.image(IMAGE_PATH / file)     if isinstance(file, Path):         if file.exists():             # return MessageSegment.image(file)             try:                 with open(file.absolute(), 'rb') as file:                     # 读取图片文件并进行 Base64 编码                     image_data = base64.b64encode(file.read())                     image_base64 = image_data.decode('utf-8')                     # print(image_base64)                     return MessageSegment.image("base64://" + image_base64)             except FileNotFoundError:                 logger.warning(f"图片 {file.absolute()} 缺失...")         logger.warning(f"图片 {file.absolute()}缺失...")     if isinstance(file, (bytes, io.BytesIO)):         return MessageSegment.image(file)     if isinstance(file, BuildImage):         return MessageSegment.image(file.pic2bs4())     return MessageSegment.image("")   
高兴太早了，其他都可以了就剩下帮助怎么都不行，最后只能直接挂载目录了
  
把上面返回MessageSegment那行改成file转Path就行了
             # return MessageSegment.image(IMAGE_PATH / file)             file = Path(IMAGE_PATH / file)
