### ISSUE TITLE
python bot.py运行出错

### ISSUE THREAD

**Issue by ghost** [HibiKier/zhenxun_bot#1502]
### 错误截图

![QQ图片20231126140032](https://github.com/HibiKier/zhenxun_bot/assets/121286436/5272713c-0b8f-4f79-96ee-a54d71aa6a51)
![QQ图片20231126140032](https://github.com/HibiKier/zhenxun_bot/assets/121286436/a90b9947-b41c-451e-899b-e5f5d0cf8f22)

### 日志截图

![QQ图片20231126140621](https://github.com/HibiKier/zhenxun_bot/assets/121286436/66a84796-f661-4afb-abf2-3dd3ae2092c8)

### 错误说明
python版本是3.9.2
我按照教程进行操作输入前面都没有问题，运行python bot.py的时候就报错

**Comment by Lu-666-dev** [comment]
哥们怎么解决的
