### ISSUE TITLE
pg_ctl: 无法启动服务器进程,数据库连接错误.

### ISSUE THREAD

**Issue by gaqwe767** [HibiKier/zhenxun_bot#1503]
### 错误截图

![QQ截图20231206211707](https://github.com/HibiKier/zhenxun_bot/assets/64371245/5ae910f3-decd-48b6-9cb0-e8984e90b4de)

### 日志截图

![QQ截图20231206211751](https://github.com/HibiKier/zhenxun_bot/assets/64371245/490ce057-28d2-4745-aa34-862aa1065f29)
![QQ截图20231206211816](https://github.com/HibiKier/zhenxun_bot/assets/64371245/60a3a7f6-09a8-48bb-9de2-ff865adb5fff)
![QQ截图20231206211844](https://github.com/HibiKier/zhenxun_bot/assets/64371245/98a0f221-3fbd-4a45-92da-d0803e310662)

### 错误说明

pg_ctl: 无法启动服务器进程,数据库连接错误.重新安装也不行，不知道什么原因。

**Comment by MstZzz** [comment]
同上

**Comment by HibiKier** [comment]
看看数据库是不是新建成功了，看看配置有没有写错

**Comment by MstZzz** [comment]
重配置了数据库 还是不行

**Comment by HibiKier** [comment]
看看配置和数据库
