### ISSUE TITLE
poetry install安装依赖及虚拟环境报错#164

### ISSUE THREAD

**Issue by kobayashi911** [HibiKier/zhenxun_bot#1504]
### 错误截图
![image](https://github.com/HibiKier/zhenxun_bot/assets/104967787/ecd02f1a-bbb1-43c9-bb83-b6f2d331e491)
![image](https://github.com/HibiKier/zhenxun_bot/assets/104967787/0db65c96-b156-40b9-8b6a-8b33a229b1de)
[](url)
[log file.zip](https://github.com/HibiKier/zhenxun_bot/files/13624255/log.file.zip)

**Comment by PackageInstaller** [comment]
看起来是你环境中没有对应的gcc？
