### ISSUE TITLE
B站动态推送获取失败时，真寻会发送空消息

### ISSUE THREAD

**Issue by zhx79513** [HibiKier/zhenxun_bot#1506]
### 错误截图
![图片](https://github.com/HibiKier/zhenxun_bot/assets/5063357/deef2863-fc3f-4be9-8e53-8a32bdc2f46a)

### 日志截图
![图片](https://github.com/HibiKier/zhenxun_bot/assets/5063357/e86dc27d-d771-45e3-b5c0-e178e16de06d)

### 错误说明

B站动态获取失败的时候，真寻会发送空消息，原因是下面代码新版加了"\n"，导致send_sub_msg将其判断为非空消息而进行了发送
https://github.com/HibiKier/zhenxun_bot/blob/1130569a201127f9afceef61e561142838ebfaac/plugins/bilibili_sub/__init__.py#L267-L267

**Comment by HibiKier** [comment]
72e0c7fdb57ad4201c871331d3baa442462bc6aa
