### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by xuyufenfei** [HibiKier/zhenxun_bot#1511]
### 错误截图

[img]

### 日志截图

![Screenshot_2024-01-04-23-21-24-987_com termux](https://github.com/HibiKier/zhenxun_bot/assets/133896005/d1b1c70d-fe42-447d-a66a-85c79b12d17d)

### 错误说明

发生了xx错误...

**Comment by xuyufenfei** [comment]
![Image_1704384793452](https://github.com/HibiKier/zhenxun_bot/assets/133896005/c4f526e3-60dd-4f70-8b50-732e362a697b)

**Comment by xuyufenfei** [comment]
无法找到包

**Comment by PackageInstaller** [comment]
一个是没有java环境，另一个是你poetry虚拟环境的根文件夹叫zhenxun-bot而你现在的路径所在文件夹是zhenxun_bot
