### ISSUE TITLE
使用WebUi账号密码问题

### ISSUE THREAD

**Issue by Shu-Ying** [HibiKier/zhenxun_bot#1512]
根据文档所述: 在configs/config.yaml文件中配置项设置账号密码
但是在文档另一项所述:
config.yaml
插件配置项文件，摒弃了原所有插件配置都在config.py，对新增插件无法很好的进行统一配置管理
现在将通过插件标准将插件配置项统一管理和修改
所有插件的配置项全部在这里！
该文件自动生成，仅仅可修改值，请不要手动添加配置项

所以每次启动bot让其重新载入配置文件都会导致初始化config.yaml, 无法正常配置web账号密码

我在zhenxun_bot_webui文件夹内创建configs/config.yaml还是无法正常登录

所以来求助, 我该如何设置账号密码?

**Comment by Shu-Ying** [comment]
> 在真寻目录下configs/config.yaml里设置 ![图片](https://private-user-images.githubusercontent.com/45528451/300352973-fe48df27-c344-462a-9418-debddbe0806e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjA2NjgsIm5iZiI6MTcwNjUyMDM2OCwicGF0aCI6Ii80NTUyODQ1MS8zMDAzNTI5NzMtZmU0OGRmMjctYzM0NC00NjJhLTk0MTgtZGViZGRiZTA4MDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MjYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYWQyZTMwYmM0YzJkNjQ4NDQ0OWI3OTFiYWU3MTc2NGY4NjdmNTQ1MmVjZDVlMWQ1MjVlYzI0MWMzYTI5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.msdfkjjHO1DOzi7CRVFa_5sKLKAO_yyVInsKEe3mIA0)

我每次启动真寻之后，这些配置就会被初始化，很遗憾我不能这么使用

**Comment by HibiKier** [comment]
有这事？什么版本的真寻，是0.1.6.7还是最新的main分支

**Comment by Shu-Ying** [comment]
> 有这事？什么版本的真寻，是0.1.6.7还是最新的main分支

0.1.6.7

**Comment by HibiKier** [comment]
> > 有这事？什么版本的真寻，是0.1.6.7还是最新的main分支
> 
> 0.1.6.7

用main里的

**Comment by Shu-Ying** [comment]
> > > 有这事？什么版本的真寻，是0.1.6.7还是最新的main分支
> > 
> > 
> > 0.1.6.7
> 
> 用main里的

问题已经得到解决，但是服务器被吃了（悲
