### ISSUE TITLE
python bot.py 出现错误ModuleNotFoundError: No module named 'nonebot.adapters.onebot

### ISSUE THREAD

**Issue by LoganHaiz** [HibiKier/zhenxun_bot#1515]
### 错误截图
P1
<img width="545" alt="Screenshot 2024-01-29 041318" src="https://github.com/HibiKier/zhenxun_bot/assets/58725983/7295212f-c39f-4029-b25c-759a939f896f">
P2
<img width="443" alt="Screenshot 2024-01-29 041653" src="https://github.com/HibiKier/zhenxun_bot/assets/58725983/ce159c1b-1796-4356-a262-ee4c8426fe2c">

### 日志截图

[img]

### 错误说明
Python版本3.10.0
每一步都严格按照文档操作，但到文档[https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_zhenxun.html]中步骤一，第四行poetry shell进入虚拟环境后，playwright不是内部或外部命令，也不是可运行的程序《P1》
如果跳过playwright的两条命令直接执行第三、四步，在第五步时在zhenxun_bot-main目录下运行cmd：python bot.py 出现错误ModuleNotFoundError: No module named 'nonebot.adapters.onebot' 《P2》

**Comment by HibiKier** [comment]
可以在 poetry shell 后 执行 python -m playwright install chromium 试试

python bot.py同样需要在poetry shell之后执行
![图片](https://github.com/HibiKier/zhenxun_bot/assets/45528451/751741c3-f677-4a00-b258-3c68a7140441)

**Comment by LoganHaiz** [comment]
<img width="547" alt="Screenshot 2024-01-29 233517" src="https://github.com/HibiKier/zhenxun_bot/assets/58725983/cff9bb08-c808-4919-a8f4-bca065bd2c46">
进入poetry shell正常，但提示No module named playwright

**Comment by HibiKier** [comment]
你poetry install运行了吗
