### ISSUE TITLE
poetry install报错

### ISSUE THREAD

**Issue by yangyuan-hu** [HibiKier/zhenxun_bot#1517]
### 错误截图

![微信截图_20240130112857](https://github.com/HibiKier/zhenxun_bot/assets/53074158/aabd9bb2-e962-46bc-8076-6767c237fb51)

### 日志截图

[img]

### 错误说明

The current project could not be installed: No file/folder found for package zhenxun-bot

**Comment by HibiKier** [comment]
进真寻目录在执行命令

**Comment by dtlnor** [comment]
根据这里的说法
- https://github.com/python-poetry/poetry/issues/8662#issuecomment-1812777906
这只是一个警告，对结果没有影响。而原因是没有符合peotry的一些奇怪而无理的要求（1.7.0之后）
