### ISSUE TITLE
BiliBili订阅不支持动态订阅

### ISSUE THREAD

**Issue by RocksonLee** [HibiKier/zhenxun_bot#152]
BiliBili订阅不支持动态订阅

可参考 <https://github.com/SK-415/HarukaBot> 改进 bilibili_sub

**Comment by HibiKier** [comment]
支持动态订阅啊

**Comment by HibiKier** [comment]
[修改bilibili_sub插件在windows平台下报错](https://github.com/HibiKier/zhenxun_bot/pull/153)，主要是bilibiliapi在win上使用playwright有些问题
