### ISSUE TITLE
初次运行真寻报错

### ISSUE THREAD

**Issue by willater** [HibiKier/zhenxun_bot#1524]
### 错误截图

![image](https://github.com/HibiKier/zhenxun_bot/assets/60524164/70465527-f2ac-46ae-b6f6-90f80a176ea0)

### 日志截图

03-02 01:11:36 [SUCCESS] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "D:\bot\zhenxun_bot-0.1.6.7\bot.py", line 5, in <module>
    nonebot.init()
  File "C:\Users\willater\anaconda3\envs\zhenxun\lib\site-packages\nonebot\__init__.py", line 298, in init
    config = Config(
  File "C:\Users\willater\anaconda3\envs\zhenxun\lib\site-packages\nonebot\config.py", line 343, in __init__
    super().__init__(
  File "C:\Users\willater\anaconda3\envs\zhenxun\lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
session_expire_timeout
  Input should be a valid timedelta, "day" identifier in duration not correctly formatted [type=time_delta_parsing, input_value='30', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/time_delta_parsing
### 错误说明
不管是按照教程用poetry还是conda环境，第一次运行真寻都会报这个错

**Comment by PackageInstaller** [comment]
这个我记得是依赖问题，你装错依赖了，报错是因为env.dev那个超时的30秒设置

**Comment by willater** [comment]
> 这个我记得是依赖问题，你装错依赖了，报错是因为env.dev那个超时的30秒设置

重新下载pyproject.toml装了一遍依赖，但是还是不行唉

**Comment by PackageInstaller** [comment]
反正我也有一次装nb插件的依赖和你一样报错，重装依赖后好了，

**Comment by willater** [comment]
> 反正我也有一次装nb插件的依赖和你一样报错，重装依赖后好了，

唉，没事谢谢啦，我晚上再试试叭

**Comment by YoisakiYui** [comment]
找到问题的原因了，是因为pydantic的那个一块代码，Input should be a valid timedelta, "day" identifier in duration not correctly formatted [type=time_delta_parsing, input_value='30', input_type=str]，这里的input_value输入的是你.env.dev的SESSION_EXPIRE_TIMEOUT的内容30，你把它改成SESSION_EXPIRE_TIMEOUT= "30d"就可以运行了

**Comment by willater** [comment]
> 找到问题的原因了，是因为pydantic的那个一块代码，Input should be a valid timedelta, "day" identifier in duration not correctly formatted [type=time_delta_parsing, input_value='30', input_type=str]，这里的input_value输入的是你.env.dev的SESSION_EXPIRE_TIMEOUT的内容30，你把它改成SESSION_EXPIRE_TIMEOUT= "30d"就可以运行了

感谢，改成30d之后成功运行了！

**Comment by PackageInstaller** [comment]
超时30天可还行（
