### ISSUE TITLE
求救

### ISSUE THREAD

**Issue by bcuiwikb** [HibiKier/zhenxun_bot#1525]
### 错误截图

![Screenshot_2024-03-10-01-54-49-03.jpg](https://github.com/HibiKier/zhenxun_bot/assets/134070277/253903c4-daa9-43fd-9b56-6c965c61c31d)

### 错误说明

刚加载的时候遇到了这个问题 好像和#22 一样

**Comment by HibiKier** [comment]
poetry install

**Comment by bcuiwikb** [comment]
之前找别人求救过了 每次到最后都还是报错
