### ISSUE TITLE
go-cqhttp无法连接zhenxun_bot

### ISSUE THREAD

**Issue by twdhu** [HibiKier/zhenxun_bot#1533]
### 错误截图
go-cqhttp
![Screenshot_2024-04-25-00-16-37-22_3d419158bad5872c40592a6c9956e692](https://github.com/HibiKier/zhenxun_bot/assets/128219291/6e704da8-bc3d-472b-a7e6-a5c3e1d671f4)

### 日志截图
zhenxun_bot
[img]
![Screenshot_2024-04-25-00-17-29-52_3d419158bad5872c40592a6c9956e692](https://github.com/HibiKier/zhenxun_bot/assets/128219291/b9c18c15-c2cf-43e6-b8a3-48208dcb6830)

### 错误说明
原本以为可能是因为8080端口被导致错误
改成10000端口后已依旧报错

**Comment by 1411484730** [comment]
怎么有人4202年了还在用gocq（）
你改完gocq的端口有没有改真寻的？

**Comment by KurosakiRei** [comment]
> 怎么有人4202年了还在用gocq（）
> 
> 你改完gocq的端口有没有改真寻的？

我也是楼主同样的错误，大佬能否告知一下除了gocq还能用什么吗

**Comment by Windsland52** [comment]
> > 怎么有人4202年了还在用gocq（）
> > 你改完gocq的端口有没有改真寻的？
> 
> 我也是楼主同样的错误，大佬能否告知一下除了gocq还能用什么吗

图方便然后不介意只能在频道用的话，可以走qq官方 https://bot.q.qq.com/wiki

**Comment by lumia1998** [comment]
用llob协议的其他工具啊,,现在是ntqq的时代了
