### ISSUE TITLE
按教程部署无法启动

### ISSUE THREAD

**Issue by HeiCreeper** [HibiKier/zhenxun_bot#1537]
### 错误截图

[img]

### 日志截图

![eeac2283-0c6a-4423-9b38-449ec9aa4a91](https://github.com/HibiKier/zhenxun_bot/assets/116493838/730fc1f3-1855-481a-a27b-071245373378)

### 错误说明

按教程部署后无法启动zhenxun

**Comment by HeiCreeper** [comment]
> ### 系统版本：window 10
> ### 真寻版本：0.1.6.7
> ### 错误截图
> [img]
> 
> ### 日志截图
> ![eeac2283-0c6a-4423-9b38-449ec9aa4a91](https://private-user-images.githubusercontent.com/116493838/334131637-90812d74-04bc-4a05-bdc8-d4ead36f0e27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTk1MzYsIm5iZiI6MTcxNjgxOTIzNiwicGF0aCI6Ii8xMTY0OTM4MzgvMzM0MTMxNjM3LTkwODEyZDc0LTA0YmMtNGEwNS1iZGM4LWQ0ZWFkMzZmMGUyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNDEzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OThkNzRhZTk2YzkyYzMxMjZjNjZlNDM0MDA0ZGU1NjA0NzNlMGQ1OWMyNGQyYmRiMTIwYzhlMWM5OTkxMGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gMgcFqHkzbqHv9BA6iAMrVqiY078udyGtWNricknuPQ)
> 
> ### 错误说明
> 按教程部署后无法启动zhenxun

**Comment by HibiKier** [comment]
试试降低python版本，或者试试仓库dev里的版本

**Comment by HeiCreeper** [comment]
py版本降低至3.9可解决该问题
