### ISSUE TITLE
最新版本真寻无法添加群认证

### ISSUE THREAD

**Issue by HeiCreeper** [HibiKier/zhenxun_bot#1539]
### 真寻版本：0.1.6.7

###使用了同为onebot协议的Lagrange，且为最新版本
### 错误截图

![IMG_20240620_231633](https://github.com/HibiKier/zhenxun_bot/assets/116493838/17aa937f-1e60-4089-91f9-ef2911da82a5)

### 日志截图

![IMG_20240620_231612](https://github.com/HibiKier/zhenxun_bot/assets/116493838/0b5cec0e-637a-4c86-9edf-bed999e2341f)

### 错误说明

已查阅之前的issue，仍然无法添加群认证

**Comment by HibiKier** [comment]
试试main中最新的代码
