### ISSUE TITLE
ModuleNotFoundError: No module named 'nonebot'

### ISSUE THREAD

**Issue by 123fire123** [HibiKier/zhenxun_bot#1540]
### 错误截图
![XRTPI9YR5Q_%U0 F Z)2A E](https://github.com/user-attachments/assets/6d2507de-ddc0-49b1-b33c-4daabd2e3475)

### 错误说明
熟知issue提问，已浏览相同问题，没有解决这个问题
pythpn 3.10
按照安装流程进行，其中流程无任何异常，其中修改了poetry install为pipx install poetry 并pipx ensurepath 配置进环境变量
最后启动时找不到nonebot

**Comment by HibiKier** [comment]
你poetry install报错了，main分支中建议使用python3.9，如果要使用python3.10及以上推荐使用dev分支
