### ISSUE TITLE
进群欢迎消息无法正常发出

### ISSUE THREAD

**Issue by enKl03B** [HibiKier/zhenxun_bot#1541]
### 日志截图

![image](https://github.com/user-attachments/assets/c32282eb-5cba-4a18-92b0-8fb18ff9be9a)

![image](https://github.com/user-attachments/assets/0fb41ae4-cd8d-4b15-87d5-82a57b0a2c6d)

### 错误说明
无其他显示，附设置的内容如下：
欢迎来到--！     #注：-代表中文，不方便展示
什么？--？
--，--，--!(40-5)并附---！
可以添加微信或 qq：
wx:   #这里是字符
qq:   #这里是数字

**Comment by HibiKier** [comment]
尝试在/basic_plugins/group_handle/__init__.py中将第158行的
```
data = json.load(open(custom_welcome_msg_json, "r"))
```
修改为
```
data = json.load(open(custom_welcome_msg_json, "r", encoding='utf-8'))
```
