### ISSUE TITLE
几个使用中的问题

### ISSUE THREAD

**Issue by enKl03B** [HibiKier/zhenxun_bot#1542]
系统版本：Windows11 23H2
真寻版本：0.1.6.7

问题1：无法正常读取图库中的图片，报错如下图
![image](https://github.com/user-attachments/assets/f725eda2-dcaa-4412-9698-af98cb2e679c)
![image](https://github.com/user-attachments/assets/865c97c3-c934-44a3-a95e-512f3d908e04)

问题2：机器人偶发报错
![image](https://github.com/user-attachments/assets/7142ef0b-9b3d-4781-81b0-b0368813734b)
![image](https://github.com/user-attachments/assets/9b7b82e7-7149-497b-95cd-dec8e876aefb)

**Comment by HibiKier** [comment]
项目路径上有中文吗？有中文的话可以试试改成英文，如果不方便可以/plugins/image_management/send_image/anti.py中删除这几行
```
img = cv2.imread(str_path)
img[0, 0, 0] = random.randint(0, 0xFFFFFFF)
cv2.imwrite(str_path, img)
```
