### ISSUE TITLE
涉及图片发送的操作均报错，提示找不到文件

### ISSUE THREAD

**Issue by Sagiri996** [HibiKier/zhenxun_bot#1545]
### 错误截图

<img width="756" alt="51d9d5669f46cf643f2aaf41dc4bf3b" src="https://github.com/user-attachments/assets/1014772b-17cf-40f7-a845-441c79ba49b0">

<img width="778" alt="2513b03edfe5fc1aa7df88c1db84139" src="https://github.com/user-attachments/assets/8d854d9e-6beb-4e37-8c08-4a7571d90abd">

### 日志截图

result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': xxxxxx, 'message_type': 'private', 'message': [MessageSegment(type='text', data={'text': '呼呼，叫俺干嘛'}), Message...
                   │    │       │         │     └ 'send_msg'
                   │    │       │         └ Bot(type='OneBot V11', self_id='xxxxxxx')
                   │    │       └ <function Adapter._call_api at 0x7f53f2e89ca0>
                   │    └ Adapter(name='OneBot V11')
                   └ Bot(type='OneBot V11', self_id='xxxxxxx')
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 132, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
           │                       │    │             │     │    └ 30.0
           │                       │    │             │     └ 1
           │                       │    │             └ <function ResultStore.fetch at 0x7f53f2e89a60>
           │                       │    └ <nonebot.adapters.onebot.store.ResultStore object at 0x7f53f2e8ca30>
           │                       └ Adapter(name='OneBot V11')
           └ <function handle_api_result at 0x7f53f2eff4c0>
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
          │              └ {'status': 'failed', 'retcode': 1200, 'data': None, 'message': "Error: ENOENT: no such file or directory, open '/bot/resource...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

### 错误说明

涉及图片发送的操作均报错无法找到文件，尝试过python3.8 ，python3.9，python3.10，docker环境部署，都报同样的错误，使用的框架为 NapCatQQ

**Comment by HibiKier** [comment]
napcat和zhenxun_bot在同一台服务器上吗

**Comment by HibiKier** [comment]
napcat是docker部署的吗

**Comment by Sagiri996** [comment]
是在同一台服务器，napcat和zhenxun_bot在docker部署和直接部署均有尝试

**Comment by HibiKier** [comment]
呃，你现在部署是什么样的，napcat和zhenxun_bot在同一个docker里吗？还是两个都在本地

**Comment by Sagiri996** [comment]
目前真寻在docker，napcat在本地

**Comment by HibiKier** [comment]
真寻的resources和data目录映射出来了吗

**Comment by Sagiri996** [comment]
映射出来了的

**Comment by HibiKier** [comment]
![image](https://github.com/user-attachments/assets/e55f5b0f-8c2d-44dc-8f37-3bbad58131fd)
映射路径和这个一样吧？

**Comment by Sagiri996** [comment]
这个报错截图是之前采用直接部署的时候报的，目前docker中报错的位置是/bot/xxxxxx

**Comment by Sagiri996** [comment]
映射的路径在/home/zhenxun_docker

**Comment by HibiKier** [comment]
> 映射的路径在/home/zhenxun_docker

你的文件夹映射路径要和报错路径一样

**Comment by HibiKier** [comment]
![6202d64420d882fa54ac482b1188f34a](https://github.com/user-attachments/assets/b3f95b5a-08e7-496c-a442-7e95b6df68f4)
没事
