### ISSUE TITLE
发送信息没反应

### ISSUE THREAD

**Issue by swyefun** [HibiKier/zhenxun_bot#1546]
### 真寻版本：0.1.5.3
我已按照安装教程安装真寻gocq换用Napcat

### 错误截图

![Screenshot_2024_0808_143119](https://github.com/user-attachments/assets/b127190f-22fe-40b1-99a3-366cffbadb6c)
在发送"真寻帮助"之后报错

**Comment by swyefun** [comment]
截图貌似没显示
![Screenshot_2024_0808_143119](https://github.com/user-attachments/assets/fe487977-b294-4a48-8891-532153d30c20)

**Comment by HibiKier** [comment]
在？报错截全点？

**Comment by HibiKier** [comment]
![image](https://github.com/user-attachments/assets/adf5a714-2c7a-4a90-a6c2-20ef449f22bc)
报错是不是没截全？

**Comment by swyefun** [comment]
我试了许多次只截取了一次，我再试试dev版本

**Comment by swyefun** [comment]
> ![image](https://private-user-images.githubusercontent.com/45528451/356130889-adf5a714-2c7a-4a90-a6c2-20ef449f22bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTIzMjgsIm5iZiI6MTcyMzExMjAyOCwicGF0aCI6Ii80NTUyODQ1MS8zNTYxMzA4ODktYWRmNWE3MTQtMmM3YS00YTkwLWE2YzItMjBlZjQ0OWYyMmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDEwMTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMmQ3OTBiMDRmYTg1ZDA2YzAzMjkxNDQ2ZjNmOWU4ZjcxNzk3NTdhZjJmNjIwMzc3NjBiNjM3YTBiNzQ1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t5kLG0POKTdSfx6bVWEaEC7BblkT3oD9A_8tKCYM_F8) 报错是不是没截全？

这次换用了dev版本这是日志文件希望大佬看看我是哪里出了问题
[错误日志.zip](https://github.com/user-attachments/files/16541576/default.zip)

**Comment by HibiKier** [comment]
超时了，不是zhenxun这边的，建议去napcat那边问问
