### ISSUE TITLE
部署WebUI遇到问题。Ubuntu使用Nginx部署生产环境登录提示404，使用npm部署开发环境可登录但无法获取数据

### ISSUE THREAD

**Issue by Zxieyuan** [HibiKier/zhenxun_bot#1552]
### 错误截图

![80web](https://github.com/user-attachments/assets/0f4923ad-7eef-4b3e-83da-2033a38f043b)
↑这是nginx部署生产环境报404↑
![18081](https://github.com/user-attachments/assets/136a35e6-2eda-4ba7-9fc5-e123de0e940e)
![28081](https://github.com/user-attachments/assets/fb232c04-af18-4393-b6a2-8f0670044874)
![38081](https://github.com/user-attachments/assets/5119f3a9-75a5-4228-80af-cac0d9b5419b)
![48081](https://github.com/user-attachments/assets/8db2fe65-bfd3-409d-83c7-188d534e86e5)
↑这是npm部署开发环境报错且无法获取数据，网页格式也没有获取到↑

### 日志截图

![bot](https://github.com/user-attachments/assets/e7eb4183-4585-46c8-b406-87d1985c7e07)
开发环境可以链接到真寻，但是生产环境无法连接到

### 错误说明

如题，nodejs版本为v20.16.0。另外，点击网页的更改端口似乎并没有用。

**Comment by HibiKier** [comment]
你nginx配置的转发是正确的 吗，端口设置是改成真寻的端口用来连接ws

**Comment by Zxieyuan** [comment]
> 你nginx配置的转发是正确的 吗，端口设置是改成真寻的端口用来连接ws

![web](https://github.com/user-attachments/assets/3e4added-2f44-45bd-bdc7-e779190f51f3)
![web2](https://github.com/user-attachments/assets/91808f51-3ea7-499a-ae56-f53c2efaaf49)

嗯，我配置了一下nginx的转发，可以登录了，谢谢大佬。就是登录后的面板有些还是报错

**Comment by HibiKier** [comment]
修改端口，改成你真寻的

**Comment by Zxieyuan** [comment]
> 修改端口，改成你真寻的

嗯嗯，我在网页端端口设置改成http://localhost:{我的端口}了。改完之后除了控制台其他的页面显示正常，控制台页面显示的都是0

**Comment by HibiKier** [comment]
端口设置只填个端口就行了

**Comment by Zxieyuan** [comment]
> 端口设置只填个端口就行了

嗯嗯，现在消息接受这一栏也有数据了。目前CPU、DISK、MEMORY一栏和后台日志一栏还是空的

**Comment by HibiKier** [comment]
修改成你真寻的端口后刷新看看报错

**Comment by HibiKier** [comment]
点开看看

**Comment by Zxieyuan** [comment]
> 点开看看

![long](https://github.com/user-attachments/assets/04b268fe-a27c-4854-ab1a-d86ebe65c8d5)

**Comment by HibiKier** [comment]
你服务器端口开了吗，8080

**Comment by Zxieyuan** [comment]
> 你服务器端口开了吗，8080

开了 入8080

**Comment by HibiKier** [comment]
f12网络那边这个ws状态码是多少

**Comment by Zxieyuan** [comment]
> f12网络那边这个ws状态码是多少

![js](https://github.com/user-attachments/assets/8f474690-3412-4384-81e9-2687ed3faa54)
是这个吧200

**Comment by Zxieyuan** [comment]
> f12网络那边这个ws状态码是多少

![web304](https://github.com/user-attachments/assets/8ffc8c53-394d-4694-a517-f5916859f2c1)
还有这个网站的网络显示304

**Comment by HibiKier** [comment]
![图片](https://github.com/user-attachments/assets/70ee1684-531e-46e3-bd04-989436412395)
这个的状态码，是多少

**Comment by Zxieyuan** [comment]
![QQ20240814-194524](https://github.com/user-attachments/assets/e962da5b-cf0e-459c-862f-a52536f90a28)
这个吗，只显示已完成

**Comment by HibiKier** [comment]
![图片](https://github.com/user-attachments/assets/d54d925c-b267-4b14-9c78-3a671f86a11e)
点开看一下

**Comment by Zxieyuan** [comment]
> ![图片](https://private-user-images.githubusercontent.com/45528451/357800212-d54d925c-b267-4b14-9c78-3a671f86a11e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzY5MzMsIm5iZiI6MTcyMzYzNjYzMywicGF0aCI6Ii80NTUyODQ1MS8zNTc4MDAyMTItZDU0ZDkyNWMtYjI2Ny00YjE0LTljNzgtM2E2NzFmODZhMTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDExNTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0YWE3ZmRhYTJmZTQ1MTcyMTQxN2EzZTBkOTUwN2M4NDcxMzg3OWFhZjEwMzhiNDZlZTM4Njc5ZWViY2UxZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PO4FeJPclRmAc-6Fl58wZfecHIhL7VaqImrQ_hQbHb8) 点开看一下

![Uploading 12.png…]()

**Comment by HibiKier** [comment]
你端口开的tcp吧？

**Comment by Zxieyuan** [comment]
> 你端口开的tcp吧？

对的，都是tcp，没开udp

**Comment by HibiKier** [comment]
620174107 进群

**Comment by HibiKier** [comment]
620174107 进群当面蕉流
