### ISSUE TITLE
发送签到或帮助后会无报错退出

### ISSUE THREAD

**Issue by anotherATTCK** [HibiKier/zhenxun_bot#1553]
### 错误截图

无

### 日志截图

![image](https://github.com/user-attachments/assets/72ac289a-ebd6-4fed-a4ba-47522ddd03b4)

### 错误说明

nonebot直接退出

**Comment by anotherATTCK** [comment]
系统是win11非常抱歉忘改了

**Comment by HibiKier** [comment]
开debug看一下

**Comment by anotherATTCK** [comment]
> 开debug看一下

![image](https://github.com/user-attachments/assets/69cd2a61-2930-42bf-b599-2ba857cb146c)

完全没报错就退出了

**Comment by anotherATTCK** [comment]
vs版本是17.11.0

**Comment by anotherATTCK** [comment]
用cmd命令echo %errorlevel%获取的错误代码是-1073741819

**Comment by HibiKier** [comment]
python版本是多少

**Comment by anotherATTCK** [comment]
似乎是在zhenxun\builtin_plugins\sign_in\utils.py的第127行await info_img.text((0, 0), f"· 好感度等级：{level} [{lik2relation[level]}]")跳出去的

**Comment by HibiKier** [comment]
其他功能有问题吗，还是就签到和ai，帮助怎么样

**Comment by anotherATTCK** [comment]
目前就试崩了签到和帮助

**Comment by HibiKier** [comment]
内存是多少？做图的内存不够？

**Comment by anotherATTCK** [comment]
![image](https://github.com/user-attachments/assets/fa2a9d69-5b0b-453c-8e63-0a3e32765175)
ne内存应该没问题

**Comment by anotherATTCK** [comment]
![image](https://github.com/user-attachments/assets/c7582828-9ab5-49ae-9e69-b1563348aed9)

原神的应该是我没配置好

**Comment by anotherATTCK** [comment]
问题解决不要使用python3.12
