### ISSUE TITLE
tortoise.exceptions.OperationalError: unterminated quoted string at or near "'\' LIMIT 1"

### ISSUE THREAD

**Issue by idonotthinksoso** [HibiKier/zhenxun_bot#1554]
### 错误截图
![20240814-224716](https://github.com/user-attachments/assets/3b6d9685-e96c-4e63-b3d7-8c703a678c76)

### 日志截图

[img]

### 错误说明

使用lagrange 连接真寻dev版，所有消息都出现上图问题。

**Comment by HibiKier** [comment]
tortoise-orm的版本是？

**Comment by idonotthinksoso** [comment]
0.20.0
![image](https://github.com/user-attachments/assets/975e971d-7aa5-4b04-b40f-e0f9a8bafd64)

**Comment by HibiKier** [comment]
把你那边
![图片](https://github.com/user-attachments/assets/7975e3a1-f0a8-4a66-9346-afbb2c521db5)
这个路径下第128行的
```python
return await cls.exists(
      group_id=group_id,
      channel_id__isnull=True,
      block_task__contains=f"{task},",
  )
```
换成
```python
return bool(await cls.get_or_none(group_id=group_id,
    channel_id__isnull=True,
    block_task__contains=f"{task},")
)
```
试试

**Comment by HibiKier** [comment]
你的postgresql是什么版本
