### ISSUE TITLE
v0.2即使已填写数据库配置仍然会报错数据库配置未填写

### ISSUE THREAD

**Issue by yozorachan** [HibiKier/zhenxun_bot#1558]
### 错误截图

![image](https://github.com/user-attachments/assets/7841987b-cf5b-4e9d-a74f-d08ebd478ebf)

![image](https://github.com/user-attachments/assets/50019607-8a5b-40e5-9456-75b53f1a9a7e)

### 日志截图

[img]

### 错误说明

真寻v0.2即使已在config.py文件中填写了以往正常使用的数据库配置，仍然会报错数据库配置未填写

**Comment by HibiKier** [comment]
在data/database.json里填

**Comment by yozorachan** [comment]
> 在data/database.json里填

OK，谢谢
