### ISSUE TITLE
安装Postgresql数据库出错

### ISSUE THREAD

**Issue by SakuraAzusa** [HibiKier/zhenxun_bot#156]
系统版本：win7 sp1
环境：Python3.8.3，java jdk17.0.2

根据真寻文档的安装步骤，尝试过安装版本9.6.24-1（无法安装vc报错），10.20.2，14.2-2，启动pgAdmin4均失败，提示Fatal error：The pgAdmin 4 server could not be contacted:
这个数据库有系统版本要求吗？但是也没有限制安装使用，查找以往issues也没有相应问答。
尝试搜索寻找的答案也无法启动，更老的版本好像并没有找到下载方式，同时也不清楚bot是否能使用，特来提出issues

**Comment by SakuraNami** [comment]
换个狐务器吧宝，或者装个虚拟机，你有没有觉得Windows7SP1太老了？虽然我觉得应该没问题（官方提供的支持是面向Window Server的 不过w10&w11没有遇见过你说的问题 附个图？或者来群里问问

**Comment by SakuraAzusa** [comment]
> 换个狐务器吧宝，或者装个虚拟机，你有没有觉得Windows7SP1太老了？虽然我觉得应该没问题（官方提供的支持是面向Window Server的 不过w10&w11没有遇见过你说的问题 附个图？或者来群里问问

系统确实有点老这个没办法，用的是一种叫挂机宝的东西，主要用来测试用的。手上还有一台ubuntu但只有1G内存，可能跑不动真寻（主要在跑gocq和别的插件，测试可以了才会丢过来这边）。
看看尝试能不能解决安装问题，不可以的话我通过虚拟机测试吧thx。

截图内容如图所示：
![pic](https://user-images.githubusercontent.com/97999241/168007714-7a6edb93-5a48-4eba-9dd4-d1836e7ea8c6.png)

log完整内容如下：
`pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\Administrator\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\PostgreSQL\14\pgAdmin 4\web\config.py"
Webapp Path: "C:\Program Files\PostgreSQL\14\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\PostgreSQL\14\pgAdmin 4\python\python.exe -s C:\Program Files\PostgreSQL\14\pgAdmin 4\web\pgAdmin4.py"
Environment: 
  - ALLUSERSPROFILE: C:\ProgramData
  - APPDATA: C:\Users\Administrator\AppData\Roaming
  - CHROME_CRASHPAD_PIPE_NAME: \\.\pipe\crashpad_3876_YDEKJKMWAEABISRE
  - CHROME_RESTART: NW.js|哎呀！NW.js 崩溃了。要立即重新启动吗？|LEFT_TO_RIGHT
  - CLIENTNAME: PC-20211025ESLF
  - CommonProgramFiles: C:\Program Files\Common Files
  - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
  - CommonProgramW6432: C:\Program Files\Common Files
  - COMPUTERNAME: jdDYyN9028
  - ComSpec: C:\Windows\system32\cmd.exe
  - FP_NO_HOST_CHECK: NO
  - HOMEDRIVE: C:
  - HOMEPATH: \Users\Administrator
  - JAVA_HOME: C:\Program Files\Java\jdk-17.0.2
  - LOCALAPPDATA: C:\Users\Administrator\AppData\Local
  - LOGONSERVER: \\jdDYyN9028
  - NUMBER_OF_PROCESSORS: 2
  - OS: Windows_NT
  - Path: C:\Users\Administrator\AppData\Local\Programs\Python\Python38;C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files\Java\jdk-17.0.2\bin;C:\Users\Administrator\AppData\Roaming\npm
  - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  - PGADMIN_INT_KEY: e16f3b68-0b5c-4dca-8c65-3d11115bd534
  - PGADMIN_INT_PORT: 52196
  - PGADMIN_SERVER_MODE: OFF
  - PROCESSOR_ARCHITECTURE: AMD64
  - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
  - PROCESSOR_LEVEL: 6
  - PROCESSOR_REVISION: 3f02
  - ProgramData: C:\ProgramData
  - ProgramFiles: C:\Program Files
  - ProgramFiles(x86): C:\Program Files (x86)
  - ProgramW6432: C:\Program Files
  - PSModulePath: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
  - PUBLIC: C:\Users\Public
  - SESSIONNAME: RDP-Tcp#0
  - SystemDrive: C:
  - SystemRoot: C:\Windows
  - TEMP: C:\Users\ADMINI~1\AppData\Local\Temp
  - TMP: C:\Users\ADMINI~1\AppData\Local\Temp
  - USERDOMAIN: jdDYyN9028
  - USERNAME: Administrator
  - USERPROFILE: C:\Users\Administrator
  - windir: C:\Windows
  - windows_tracing_flags: 3
  - windows_tracing_logfile: C:\BVTBin\Tests\installpackage\csilogfile.log
--------------------------------------------------------`

**Comment by SakuraNami** [comment]
pgadmin打不开不重要 他只是个图形化管理工具 数据库能正常运行吗 pgsql那个能打开吗

**Comment by SakuraAzusa** [comment]
> pgadmin打不开不重要 他只是个图形化管理工具 数据库能正常运行吗 pgsql那个能打开吗

使用psql好像是正常的，这样能继续下一步吗？
![pic](https://user-images.githubusercontent.com/97999241/168016908-8a0ddd1c-10cf-40c6-8dc8-277d17cfce56.png)

**Comment by SakuraNami** [comment]
可以

**Comment by SakuraAzusa** [comment]
看到项目突然多了好多人来，想了一下可以把我部署在老系统上的经验分享出来，也懒得新开lssues了在我这个直接说明吧。
这个部署方法是为了想尝鲜/贪便宜购买老服务器/远古老机器上运行真寻所使用的方式，系统最最低要求为`Windows 7 **SP1**`or`Windows Server 2008 R2 **SP1**`，高版本安装原真寻文档部署即可。
1.首先安装文档正常进行，当部署到`安装Postgresql数据库`时，下载高于10以上版本即可（目前14.3能正常运行），安装完成后通过开始→程序→PostgreSQL 14，点击SQL Shell (psql)。
2.确认server（是localhost直接回车，下面同理），确认Database[postgres]后回车，确认port[5432]后回车,确认Username[postgres]后回车,最后弹出用户postgres的口令时，输入你安装时设置的密码，你将会进入到这个状态。
![11](https://user-images.githubusercontent.com/97999241/169488019-0ece4a5a-2d31-461e-a79d-09c49de7f2f5.png)
随后输入以下命令创建用户：
`CREATE USER uname WITH PASSWORD 'zhenxun';`
提示成功后输入命令创建数据库：
`CREATE DATABASE testdb OWNER uname;`
那么数据库就搭建完成啦
*tips：因为图形窗口会崩溃（正是我提该lssues的原因），所以需要通过命令行进行并创建数据库运行
3.接着来到`安装真寻Bot`步骤，这里使用Python3.8.3，[这个是Python下载地址](https://www.python.org/ftp/python/3.8.3/python-3.8.3-amd64.exe),继续按照真寻文档进行。
*tips：Python3.9需要使用win8及以上系统运行
4.安装完poetry依赖后先执行一次`poetry shell`确认没有问题，上面会有一行提示，后面有一行路径（可能会有所不同），复制并进入它，示例：
```
Spawning shell within C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-4eqwiYJl-py3.8
```
然后依次进入`Lib\site-packages\playwright\driver`文件夹，备份`node.exe`，保留这个窗口先不要动。
5.随后先安装node13.14，[这个是node下载地址](https://nodejs.org/download/release/v13.14.0/node-v13.14.0-x64.msi)，进入你的安装目录`X:\Program Files\nodejs`，找到`node.exe`并复制，粘贴到刚才保留的窗口并确认覆盖。
*tips：因为安装poetry时内置的playwright包使用的node版本为16以上，高于14以上的所有版本在老系统都不会被支持
6.继续跟着文档走就可以了随后的步骤都可以照常部署，目前启动时除了一个bilibili的插件爆红，其他均正常读取（原神老黄历那些插件win下是无法使用的），我个人测试了一部分功能也是正常的，应该没有太大问题，当然我已经迁移回linux服务器下了，目前一切正常。
希望能提供一些帮助。☺
