### ISSUE TITLE
poetry install报错

### ISSUE THREAD

**Issue by Huang1932539** [HibiKier/zhenxun_bot#1562]
### 错误截图

![image](https://github.com/user-attachments/assets/09695c20-7e3a-49b1-8360-0accb2e60433)
![image](https://github.com/user-attachments/assets/e8bc6344-74bc-4ddf-b41d-0c37b84e2c5f)

后面的都是一样的报错。

**Comment by Copaan** [comment]
Python版本是多少

**Comment by Huang1932539** [comment]
> Python版本是多少

3.10.10

**Comment by Huang1932539** [comment]
之前用的3.12，出了#1537的问题，降到3.10后又出这个问题（
![029FB287](https://github.com/user-attachments/assets/f388c616-eb34-4e9c-becd-306258851d4a)
）

**Comment by HibiKier** [comment]
![图片](https://github.com/user-attachments/assets/20251911-aef7-4e5e-95cf-e539b5757f72)
试试看？

**Comment by Huang1932539** [comment]
> ![图片](https://private-user-images.githubusercontent.com/45528451/360450787-20251911-aef7-4e5e-95cf-e539b5757f72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTEyMjcsIm5iZiI6MTcyNDQxMDkyNywicGF0aCI6Ii80NTUyODQ1MS8zNjA0NTA3ODctMjAyNTE5MTEtYWVmNy00ZTVlLTk1Y2YtZTUzOWI1NzU3ZjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDExMDIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYTY4OGIxNjI2NTEzNGQ5OTJiM2NiZTdlYWEzNjJjMDA3MTNjNjg5MTI5YTc0NzE5YTI4YjlmZGNiM2JiNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sM8c7N1PLASsJb47pLW1yTmtK1DgnR5jvXjoCRJE0bY) 试试看？

![image](https://github.com/user-attachments/assets/9949a98a-546c-43d8-8f39-60097ab09247)
直接没有这个选项，证书更新了也是错误（悲）
我待会儿换到3.9试试看吧

**Comment by molanp** [comment]
参见[https://x-item.com/poetry%e7%89%b9%e6%ae%8a%e9%97%ae%e9%a2%98%e8%ae%b0%e5%bd%95.html](https://x-item.com/poetry%e7%89%b9%e6%ae%8a%e9%97%ae%e9%a2%98%e8%ae%b0%e5%bd%95.html)
