### ISSUE TITLE
更新提示未知错误

### ISSUE THREAD

**Issue by Zhuazizizi** [HibiKier/zhenxun_bot#1563]
### 错误截图
未知错误 <class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'temp\\HibiKier-zhenxun_bot-4d6013c\\update_info.json'
![image](https://github.com/user-attachments/assets/4fec785c-a4fc-4f7b-adf7-2a5639b3c50b)
### 日志截图
![image](https://github.com/user-attachments/assets/823b2b9b-4903-4fb7-aad9-d4a7054c0223)
### 错误说明
更新时失败提示未知错误如何对敌
如果干脆整个重装的话想保留数据应该保存哪些文件

**Comment by HibiKier** [comment]
0.1.6.7不能自动更新到2.1，项目完全重构了，保存data文件夹就行，不想下载资源可以保存resources文件夹

**Comment by Zhuazizizi** [comment]
> 0.1.6.7不能自动更新到2.1，项目完全重构了，保存data文件夹就行，不想下载资源可以保存resources文件夹

重构后旧版本那些插件库里的插件还可用吗，原本我是放在extensive_plugin中，现在的结构应该放在哪呢

**Comment by molanp** [comment]
> > 0.1.6.7不能自动更新到2.1，项目完全重构了，保存data文件夹就行，不想下载资源可以保存resources文件夹
> 
> 重构后旧版本那些插件库里的插件还可用吗，原本我是放在extensive_plugin中，现在的结构应该放在哪呢

可以用，自己在bot文件加上插件文件夹引用，还有如果插件没meta，不会显示在帮助，需要自己改
