### ISSUE TITLE
AttributeError: 'LogStorage' object has no attribute 'list'

### ISSUE THREAD

**Issue by duHtiGGitHub** [HibiKier/zhenxun_bot#1570]
### 错误截图

![ssb](https://github.com/user-attachments/assets/c1c0da45-0a23-489b-8efa-46a594c693f0)

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by HibiKier** [comment]
不管

**Comment by duHtiGGitHub** [comment]
这不是后端的问题吗 ，还是部署的问题，还是设计就是这样的

**Comment by HibiKier** [comment]
这个错误不会影响你前端的数据显示，现在dev里集成了webui不用额外部署，也可以试试

**Comment by duHtiGGitHub** [comment]
这个是 ng 配置的问题，ws 转成了 http,刚好 http 也有个 logs 接口，谢谢了
