### ISSUE TITLE
ws 连接异常

### ISSUE THREAD

**Issue by duHtiGGitHub** [HibiKier/zhenxun_bot#1571]
### 错误截图

![aa](https://github.com/user-attachments/assets/f3e3add6-1aa1-42a5-80c2-aafbbdba62a8)
![bb](https://github.com/user-attachments/assets/f18cd6d0-95b9-4a16-a543-04283418dc61)
![c](https://github.com/user-attachments/assets/b79aac4f-359b-4c7f-a510-02f9c1ec150a)

### 日志截图

[img]

### 错误说明

同样是 socket连接，zhenxun/socket/logs连接就是500，后台可以看到异常日志(已经提交issue)，但是zhenxun/socket/system_status为什么是404，检查代码也没发现问题。

**Comment by HibiKier** [comment]
zhenxun/socket/system_status 404是没转发到zhenxun这边， logs 500报错完整截图看看

**Comment by duHtiGGitHub** [comment]
谢谢 已经没问题了 是ng 的问题
