### ISSUE TITLE
更新后的色图问题

### ISSUE THREAD

**Issue by Adsicmes** [HibiKier/zhenxun_bot#16]
![image](https://user-images.githubusercontent.com/79645438/127741086-de6e05a1-78e2-4794-ab1b-8102510b2c74.png)
如图

我发送了 色图 a

更新我是下载了最新的code 然后 删除了data和resource文件夹 覆盖进去的

**Comment by HibiKier** [comment]
已修，替换该文件即可，实际搜索数量小于指定数量导致的
