### ISSUE TITLE
[Feature Request] 改善webui

### ISSUE THREAD

**Issue by Singl-Daemon** [HibiKier/zhenxun_bot#1600]
rt，目前的webui没办法自定义端口，希望大佬们可以实现一下()
顺便支持一下https吧，我什么都会做的()

**Comment by AkashiCoin** [comment]
自定义端口的话你修改`.env.dev`的`PORT`就行
https现目前没有支持的打算，你可以自行使用`nginx`或者其他软件反代。

**Comment by Singl-Daemon** [comment]
> 自定义端口的话你修改`.env.dev`的`PORT`就行

我发现在修改`.env.dev`的`PORT`之后，连接OneBot的端口也会随之改变。
有计划把webui端口和连接ob的端口分开吗(

**Comment by AkashiCoin** [comment]
分开是有什么特殊的需求吗？如果是暴露公网的问题，你可以考虑反代时屏蔽ob的路径。然后我感觉用两个不同端口有点多此一举

**Comment by Singl-Daemon** [comment]
> 分开是有什么特殊的需求吗？如果是暴露公网的问题，你可以考虑反代时屏蔽ob的路径。然后我感觉用两个不同端口有点多此一举

好的，谢谢
这个issue可以close了
