### ISSUE TITLE
启动时报错：pydantic.generics:GenericModel已移动至pydantic.BaseModel

### ISSUE THREAD

**Issue by Strawxiguan** [HibiKier/zhenxun_bot#1603]
`(zhenxun-bot-py3.10) G:\bot\zhenxun\zhenxun_bot>python bot.py
C:\Users\Straw\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--J5vPfcz-py3.10\lib\site-packages\pydantic\_migration.py:283: UserWarning: `pydantic.generics:GenericModel` has been moved to `pydantic.BaseModel`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
C:\Users\Straw\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--J5vPfcz-py3.10\lib\site-packages\pydantic\_internal\_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
09-06 07:08:20 [SUCCESS] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "G:\bot\zhenxun\zhenxun_bot\bot.py", line 8, in <module>
    nonebot.init()
  File "C:\Users\Straw\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--J5vPfcz-py3.10\lib\site-packages\nonebot\__init__.py", line 299, in init
    config = Config(
  File "C:\Users\Straw\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--J5vPfcz-py3.10\lib\site-packages\nonebot\config.py", line 333, in __init__
    super().__init__(
  File "C:\Users\Straw\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot--J5vPfcz-py3.10\lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
session_expire_timeout
  Input should be a valid timedelta, "day" identifier in duration not correctly formatted [type=time_delta_parsing, input_value='30', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/time_delta_parsing`
截图报错：
![image](https://github.com/user-attachments/assets/ab1dc352-03fb-4d82-8b12-f6ecdd9f79b4)
版本为0.2.2最新release版本，python版本为3.10.6，电脑系统为Win11 23H2
请问如何修改文件以解决此报错问题？

**Comment by HibiKier** [comment]
pip install pydantic=1.10.18

**Comment by Strawxiguan** [comment]
main的文件有问题，用dev解决了，这个issues我就close了
