### ISSUE TITLE
playwright install-deps chromium 命令出现错误

### ISSUE THREAD

**Issue by wuyukwi** [HibiKier/zhenxun_bot#161]
Installing Ubuntu dependencies...
Switching to root user to install dependencies...
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://cdn-aws.deb.debian.org/debian bullseye InRelease           
Hit:3 http://cdn-aws.deb.debian.org/debian bullseye-updates InRelease   
Hit:4 http://cdn-aws.deb.debian.org/debian bullseye-backports InRelease 
Hit:5 http://ftp.jp.debian.org/debian bullseye InRelease                
Reading package lists... Done                     
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-ubuntu-font-family' has no installation candidate

系统是debian11

**Comment by HibiKier** [comment]
可能系统没有一些其他依赖？试试百度报错

**Comment by wyh0106** [comment]
同样遇到这个错误，请问你解决了吗

**Comment by wyh0106** [comment]
我放弃挣扎了，把vps重装了个Ubuntu20，之前的努力全部木大

**Comment by BlackLotus-AL** [comment]
Ubuntu 22.04 LTS遇到了同样的问题 :(

**Comment by BlackLotus-AL** [comment]
> 我放弃挣扎了，把vps重装了个Ubuntu20，之前的努力全部木大

请问重装Ubuntu20后解决这个问题了么 o/

**Comment by wyh0106** [comment]
> 

还没测试，刚把数据库装好，然后我这边要写专业课作业，暂时没空弄了，明天如果你先完成测试，也请告知我一下，谢谢

**Comment by wyh0106** [comment]
> > 我放弃挣扎了，把vps重装了个Ubuntu20，之前的努力全部木大
> 
> 请问重装Ubuntu20后解决这个问题了么 o/
还没测试，刚把数据库装好，然后我这边要写专业课作业，暂时没空弄了，明天如果你先完成测试，也请告知我一下，谢谢

**Comment by wyh0106** [comment]
> > 我放弃挣扎了，把vps重装了个Ubuntu20，之前的努力全部木大
> 
> 请问重装Ubuntu20后解决这个问题了么 o/

我今天试了下，是可以解决问题的

**Comment by jk6589jk** [comment]
vim /etc/apt/sources.list
添加
```
deb http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse
deb http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse
deb http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse
deb http://mirrors.aliyun.com/ubuntu/ focal-proposed main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ focal-proposed main restricted universe multiverse
deb http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse
```
然后sudo apt update一下试试

**Comment by BlackLotus-AL** [comment]
因为我用的阿里云Ubuntu20，所以不知道是因为有阿里云源还是因为Ubuntu20解决了这个问题

**Comment by BlackLotus-AL** [comment]
> > > 我放弃挣扎了，把vps重装了个Ubuntu20，之前的努力全部木大
> > 
> > 
> > 请问重装Ubuntu20后解决这个问题了么 o/
> 
> 我今天试了下，是可以解决问题的

是的，我刚刚也解决了这个问题 o7
