### ISSUE TITLE
粗暴更改签到数据库后新用户无法签到

### ISSUE THREAD

**Issue by SinGone949** [HibiKier/zhenxun_bot#1610]
### 错误截图

![Screenshot_20240908-181228](https://github.com/user-attachments/assets/fc0d24a8-3aac-4d62-9c0e-46285d993783)

### 日志截图

![ChainedBox - Xshell 8 Beta (Build 0047) 2024_9_8 17_53_07](https://github.com/user-attachments/assets/d21cb1b1-9273-46f1-9242-7d28b9e1956f)

### 错误说明

前段时间跑真寻的服务器坏了，好久没管，最近换了新的，刚好发现真寻更新新版本了，就直接安装新版本，打算把之前备份的签到数据库直接拿过来用。后来发现新版本的签到数据结构和之前版本有很大不同，就做了一张excel表，按照新的"user_console"和"sign_user"两张表的表头把原来数据复制过来，再用DBeaver导入。完成后发现原来在表上的用户能够正常签到，而表上没有的用户签到无响应，后台报上图错误，请问各位大佬有无想法

**Comment by HibiKier** [comment]
你自己还迁移了一遍？你自己导入的话要更改表的自增id，新版本是有对旧版本数据的迁移的，建议啥也不干把user_console和sign_user表删了重启

**Comment by SinGone949** [comment]
最初就是用旧的数据库进去的，但是报错
<img width="941" alt="屏幕截图 2024-09-08 160047" src="https://github.com/user-attachments/assets/e6433afa-ef98-420d-a223-cbd894e76a64">

**Comment by HibiKier** [comment]
你是0.1.6.7之前的版本吧，把数据库里的所有user_qq字段改成user_id后删那俩表再重启

**Comment by SinGone949** [comment]
是的，我试试

**Comment by SinGone949** [comment]
问题解决了，但是新生成的签到图没有头像，不知道怎么回事
![Screenshot_20240908-185832](https://github.com/user-attachments/assets/09a50393-69a7-45d5-ac49-91822218c83f)

**Comment by SinGone949** [comment]
应该是我这边自己的网络问题
