### ISSUE TITLE
无法正确发送好友申请消息

### ISSUE THREAD

**Issue by leekooyo** [HibiKier/zhenxun_bot#1611]
### 错误截图

![image](https://github.com/user-attachments/assets/fbafa068-0f54-4685-b48d-ba8da2ababba)
![53ed6513442bbc8f71a97adf6f4096c0](https://github.com/user-attachments/assets/7e1fd160-fd02-4b5f-a4e4-95b964231694)

### 日志截图
![日志截图1](https://github.com/user-attachments/assets/a98acfe5-8a71-4d21-b6e0-cbff0c28b5d8)
![日志截图2](https://github.com/user-attachments/assets/4ab33402-5dba-436c-8984-36e46f3e1aae)

### 错误说明

未开启自动添加好友时，无法向超级用户发送消息，并将原本给超级用户发送的消息发送给未知QQ号（见错误截图）

**Comment by HibiKier** [comment]
你看看你env里的PLATFORM_SUPERUSERS是不是配置正确的

**Comment by leekooyo** [comment]
> 你看看你env里的PLATFORM_SUPERUSERS是不是配置正确的

![f6c733e971f89dd4849c48545f6b8cb4](https://github.com/user-attachments/assets/bcb9c6cd-d5ff-4803-b3a1-4a3f6736287f)

找到原因所在了，在\zhenxun\utils\platform.py文件中85行`superuser_id = random.choice(platform_superusers)`，这句代码将完整的superuser_id拆分为单个字符，导致消息构建中的target_id出错。将superuser_id写死为我的QQ后能正常工作，可以断定是random.choice()函数的问题。

由于我不清楚跨平台开发的代码的逻辑，因此不提交pr了，希望能在后续开发中进行修复。

**Comment by HibiKier** [comment]
啊？你env里这个字段怎么填写的

**Comment by HibiKier** [comment]
噢，没事了

**Comment by HibiKier** [comment]
d94e1b18bf9b830b4642b76f6d89f9092a3bdcef
