### ISSUE TITLE
webui问题

### ISSUE THREAD

**Issue by ATTomatoo** [HibiKier/zhenxun_bot#1614]
### 真寻版本：0.2.2
![CEAMW VZ{JEE 93T _6FWF](https://github.com/user-attachments/assets/4eb6bdc7-a3a7-4451-a72a-9e51166404eb)

webui中，禁用某个群的某个功能，测试下来无法禁用，插件依旧正常
![5}J)5QE5~(3}ZGD5AFR(Z(P](https://github.com/user-attachments/assets/51e882df-ee4b-40d8-8937-2c81260a193e)
每点击一次应用会多出来一个箭头所指的框框
![)9G(S 7ON~DQI33BK6BRN3](https://github.com/user-attachments/assets/672aabea-01b7-4416-a59a-bbfb3fffe3b7)
webui 页面缩放也有问题，后台日志很少能正常加载出来

**Comment by ATTomatoo** [comment]
![HR HLSZUM 7}JW}KU5LH](https://github.com/user-attachments/assets/84c0de29-ee56-460f-a88b-006bddae295d)
0.2.3版本
无法通过webui删除好友或者退出群

**Comment by ATTomatoo** [comment]
0.2.3测试可以正常禁用某个插件了,后台日志也可以正常加载显示出来了,在控制台中的CPU，MEM,DISK也会变动了。

**Comment by ATTomatoo** [comment]
每点击一次应用会多出来一个箭头所指的框框，页面缩放还是依旧

**Comment by ATTomatoo** [comment]
![HR HLSZUM 7}JW}KU5LH](https://github.com/user-attachments/assets/ff13450e-72a6-4f10-9c67-7ffafc48ceb9)
无法通过WEBUI删除好友，退出群聊

**Comment by ATTomatoo** [comment]
![ZN4KQ~GLOB R$6Y1XNUN$}M](https://github.com/user-attachments/assets/0a2809ee-e47b-414e-aedd-4f69afb4b6d1)
系统信息中cpu,mem,disk无显示出来

**Comment by HibiKier** [comment]
页面缩放先别急，其他的先改了

**Comment by ATTomatoo** [comment]
不急不急，先反馈在这

**Comment by HibiKier** [comment]
使用 zhenxun_bot 的 [feature/refactor-base](https://github.com/HibiKier/zhenxun_bot/tree/feature/refactor-base) 分支
和
zhenxun_bot_webui 的 [feature/refactor-ui](https://github.com/HibiKier/zhenxun_bot_webui/tree/feature/refactor-ui) 分支
进行了ui自适应和修改bug以及全局维护ws

**Comment by ATTomatoo** [comment]
![4QMO5U8CXI8I0T$%1ETSNWJ](https://github.com/user-attachments/assets/e91a6a72-0b38-45e1-9185-5fc321d90411)
UI好了，但不是很好

每点击一次应用会多出来一个箭头所指的框框，这个好了
后台日志可以正常显示

最后一条网页观测群聊，没好，依旧关了重开之后不显示

**Comment by HibiKier** [comment]
ui你没更新到最新版本

**Comment by ATTomatoo** [comment]
更新好了，UI也正常显示了
观测群聊和之前一样
在地址栏输入后台地址时，直接输入控制台地址的话
![image](https://github.com/user-attachments/assets/56354141-95ea-4142-aae0-88a36913119c)
![image](https://github.com/user-attachments/assets/f2969cd8-1fda-48bb-be0a-d34c972809b3)
可以直接进入仪表盘内，虽然没数据显示，但是还是直接退回到主页面且强制输入密码之后才能访问比较好

**Comment by HibiKier** [comment]
更新真寻分支代码再测聊天

**Comment by ATTomatoo** [comment]
聊天OK了,关了再开也能显示记录了

**Comment by HibiKier** [comment]
> 更新好了，UI也正常显示了 观测群聊和之前一样 在地址栏输入后台地址时，直接输入控制台地址的话 ![image](https://private-user-images.githubusercontent.com/93612024/398224398-56354141-95ea-4142-aae0-88a36913119c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Nzk1MjUsIm5iZiI6MTczNDk3OTIyNSwicGF0aCI6Ii85MzYxMjAyNC8zOTgyMjQzOTgtNTYzNTQxNDEtOTVlYS00MTQyLWFhZTAtODhhMzY5MTMxMTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE4NDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMzdjMWM5ZjdkM2U2NTA5MWU4MGQ2NzdhMGVhYTdhNTkxNjAzODljZWE3YmI4OWJjZWNkZGU2ODg0MTdkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yRaHAURXMgEpQxpBNnqOVjage7KFpKZ78ymbzgy5CPg) ![image](https://private-user-images.githubusercontent.com/93612024/398224428-f2969cd8-1fda-48bb-be0a-d34c972809b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Nzk1MjUsIm5iZiI6MTczNDk3OTIyNSwicGF0aCI6Ii85MzYxMjAyNC8zOTgyMjQ0MjgtZjI5NjljZDgtMWZkYS00OGJiLWJlMGEtZDM0Yzk3MjgwOWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE4NDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNmE0NWZhM2ZlMjcyYTY5Y2EwYzZiN2VlYWQ1NmM3YWRkMjc4Yzk1N2EyNjdhNzRhNzYyY2NkYmY0MTZmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CI4Sw438B7ZUEhPEthbrfcNrAh64_P6u28JQGeDQfvw) 可以直接进入仪表盘内，虽然没数据显示，但是还是直接退回到主页面且强制输入密码之后才能访问比较好

更新ui

**Comment by ATTomatoo** [comment]
登录页面地址设置无法修改了

**Comment by HibiKier** [comment]
已更新

**Comment by ATTomatoo** [comment]
ok了，暂时没什么新问题了
