### ISSUE TITLE
图片排版问题

### ISSUE THREAD

**Issue by am-q** [HibiKier/zhenxun_bot#1618]
### 错误截图
![156c1d339d7df080b9c007203dd266b2_0](https://github.com/user-attachments/assets/a2547ebe-6a8f-48dc-bdf0-e5cbeb7646ab)
![c66fbd8b247421e352e71dad55142511](https://github.com/user-attachments/assets/51dcd1cc-df4b-4a2d-a36c-84276f8fb5b3)

### 日志截图

[img]

### 错误说明

1、帮助zhenxun模式会出现错位。
2、签到右上角图片会挡住过多的文字。

**Comment by HibiKier** [comment]
94ef33264b54873105d305ba2e6b00aa51328784 a8355fbab919a3f3671ebb7ae4bd2c5a48e85eb4
