### ISSUE TITLE
真寻要火

### ISSUE THREAD

**Issue by mnixry** [HibiKier/zhenxun_bot#162]
现在全QQ已经传遍了，估计明天GitHub Trending登顶， 太牛了！

---

# 广告位招租

- [hikari.obfs.dev](https://hikari.obfs.dev/) 动漫图片聚合搜索网站！接入的API比真寻更多！
- [nonebot/nonebot2](https://github.com/nonebot/nonebot2) 真寻根基的基础框架！学习它写出自己的涩图Bot！
- [Ice-Cirno/HoshinoBot](https://github.com/Ice-Cirno/HoshinoBot) 也是很不错的Bot！真寻很多功能的来源，历史悠久用户很多

**Comment by yanyongyu** [comment]
要🔥:fire:

**Comment by Witcher-Evan** [comment]
我一个没学过python的已经在看文档了...

**Comment by errors4ever** [comment]
非常好工作,爱来自瓷器

**Comment by lancer-wang** [comment]
是哪个模块搜图啊,只找到一个saucenao的

**Comment by BlueGlassBlock** [comment]
愿我们能在更开放的平行宇宙相遇。

**Comment by MingxuanGame** [comment]
希望真寻没事

**Comment by mnixry** [comment]
然而真寻火了我还是连个contributor都没混上，令人感叹

**Comment by JustUndertaker** [comment]
然而真寻火了我还是连个contributor都没混上，令人感叹

**Comment by MingxuanGame** [comment]
我预言一波
真寻会比 nonebot2 star 多

**Comment by BlueGlassBlock** [comment]
> 然而真寻火了我还是连个contributor都没混上，令人感叹

~~那我可以混个 nb2 的 contributor 吗~~

**Comment by Nova-Noir** [comment]
> 然而真寻火了我还是连个contributor都没混上，令人感叹

加入我，当(++3 --3)的typo高手！

**Comment by MingxuanGame** [comment]
> > 然而真寻火了我还是连个contributor都没混上，令人感叹
> 
> ~~那我可以混个 nb2 的 contributor 吗~~

~~水个插件就行~~

**Comment by mnixry** [comment]
> 那我可以混个 nb2 的 contributor 吗

@BlueGlassBlock 随时欢迎，只要不是把README改成Ariadne就行

**Comment by BlueGlassBlock** [comment]
> > 那我可以混个 nb2 的 contributor 吗
> 
> @BlueGlassBlock 随时欢迎，只要不是把README改成Ariadne就行

XD 我把 `inrich` 做完写个 nb2 适配吧

**Comment by MingxuanGame** [comment]
我 contributor 混的
我是彩笔

**Comment by Nranphy** [comment]
火钳>"<

**Comment by yzyyz1387** [comment]
啊啊啊，嗯嗯嗯，啊啊啊啊啊啊啊啊啊啊啊

**Comment by MiooHiioo** [comment]
慕名而来，谢谢大佬。

**Comment by synodriver** [comment]
怪

**Comment by Kt-MarIn** [comment]
好好好！太好啦，膜！

**Comment by MingxuanGame** [comment]
> 啊啊啊，嗯嗯嗯，啊啊啊啊啊啊啊啊啊啊啊

别在这理发店

**Comment by yanyongyu** [comment]
进行一波复制粘贴的骗star

## 感谢
[botuniverse / onebot](https://github.com/botuniverse/onebot) ：超棒的机器人协议  
[Mrs4s / go-cqhttp](https://github.com/Mrs4s/go-cqhttp) ：cqhttp的golang实现，轻量、原生跨平台.  
[nonebot / nonebot2](https://github.com/nonebot/nonebot2) ：跨平台Python异步机器人框架  
[Angel-Hair / XUN_Bot](https://github.com/Angel-Hair/XUN_Bot) ：一个基于NoneBot和酷Q的功能性QQ机器人  
[pcrbot / cappuccilo_plugins](https://github.com/pcrbot/cappuccilo_plugins) ：hoshino插件合集  
[MeetWq /nonebot-plugin-withdraw](https://github.com/MeetWq/nonebot-plugin-withdraw) ：A simple withdraw plugin for Nonebot2  
[maxesisn / nonebot_plugin_songpicker2](https://github.com/maxesisn/nonebot_plugin_songpicker2) ：适用于nonebot2的点歌插件  
[nonepkg / nonebot-plugin-manager](https://github.com/nonepkg/nonebot-plugin-manager) ：Nonebot Plugin Manager base on import hook  
[H-K-Y / Genshin_Impact_bot](https://github.com/H-K-Y/Genshin_Impact_bot) ：原神bot，这是一个基于nonebot和HoshinoBot的原神娱乐及信息查询插件  
[NothAmor / nonebot2_luxun_says](https://github.com/NothAmor/nonebot2_luxun_says) ：基于nonebot2机器人框架的鲁迅说插件  
[Kyomotoi / AnimeThesaurus](https://github.com/Kyomotoi/AnimeThesaurus) ：一个~~特二刺螈~~（文爱）的适用于任何bot的词库  
[Ailitonia / omega-miya](https://github.com/Ailitonia/omega-miya) ：基于nonebot2的qq机器人  
[KimigaiiWuyi / GenshinUID]("https://github.com/KimigaiiWuyi/GenshinUID") ：一个基于HoshinoBot/NoneBot2的原神UID查询插件

**Comment by MingxuanGame** [comment]
提醒：把邮件提醒关掉，不然你今晚会睡不着
![image](https://user-images.githubusercontent.com/68982190/168777591-9903e10e-4bea-4b3c-a082-f68cb708e192.png)

**Comment by djkcyl** [comment]
有没有大哥能帮我搞一个这个机器人啊，好麻烦，我搞不明白

**Comment by salted-yu** [comment]
慕名而来，谢谢大佬。

**Comment by MingxuanGame** [comment]
既然都在这里发病了，大声脱出来也没事吧

哼哼哼，啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊，啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by Nova-Noir** [comment]
> 有没有大哥能帮我搞一个这个机器人啊，好麻烦，我搞不明白

把你的shell给我看看，哥哥帮你搞一个\爱心眼/

**Comment by MingxuanGame** [comment]
> 有没有大佬救救我啊，这个pythom该装哪个版本啊，救命啊

装 11.45.14 版，主流

**Comment by djkcyl** [comment]
> > 有没有大哥能帮我搞一个这个机器人啊，好麻烦，我搞不明白
> 
> 把你的shell给我看看，哥哥帮你搞一个\爱心眼/

什么是shell

**Comment by Twip-Emma** [comment]
刚刚下载这个zip打开双击那个开始文件，提示说没安装Python，我应该怎么办啊

**Comment by yzyyz1387** [comment]
警惕上面大佬装萌新钓鱼

**Comment by Nranphy** [comment]
> 

检测到救命啊（doge

**Comment by MingxuanGame** [comment]
【活跃】Millie Parfait 17:25:43
ddl：

【潜水】群萌新，时不时来抱大腿的友华子 17:25:48
ddl：

【潜水】 我的bot存活和我在群里说话只能同时发生一个 17:25:50
ddl：🍋

【活跃】黯星座 NovaNo1r 17:25:52
xmsl

【潜水】小晖 17:25:52
ddl：🍋

【潜水】Chu 3 17:25:52
ddl：🍋

【吐槽】DJH-菜！ 17:25:54
ddl：🍋

【潜水】嘉然今天吃什么 17:25:55
ddl：🍋

【潜水】18870 17:25:55
ddl：🍋

【潜水】明见@今天寄了吗 17:25:55
ddl：🍋

【潜水】夜里的向日葵 17:25:56
ddl：🍋

【活跃】pip install koishi 17:25:58
ddl：🍋

【潜水】eya46 17:25:59
ddl：🍋

【潜水】lazycat 17:26:00
ddl：🍋

【潜水】折令秋 17:26:00
ddl：🍋

**Comment by mnixry** [comment]
警惕上面大佬装萌新钓鱼

**Comment by MingxuanGame** [comment]
【活跃】小CAI
![XNYFCAP_I9EF0GJGYU33~$B](https://user-images.githubusercontent.com/68982190/168778349-85745c41-ef53-4172-9de1-3f60cae512ca.PNG)

**Comment by salted-yu** [comment]
救命啊

**Comment by yanyongyu** [comment]
🍋

**Comment by MingxuanGame** [comment]
![IJYWTJBN4)~CTUA4DL2 17G](https://user-images.githubusercontent.com/68982190/168778464-3860f916-dee4-468a-8018-aef82d00ccfe.png)

**Comment by MingxuanGame** [comment]
哔！统计
s：677

**Comment by Wybxc** [comment]
还在用假 bot？

来试试这款真 bot！

https://github.com/YiriMiraiProject/YiriMirai

极简启动，无需多余配置，十倍性能刀刀爆！

（逃）

**Comment by Nranphy** [comment]
> 提醒：把邮件提醒关掉，不然你今晚会睡不着 ![image](https://user-images.githubusercontent.com/68982190/168777591-9903e10e-4bea-4b3c-a082-f68cb708e192.png)

好捏，我可以贴贴mingxuanl吗[![贴贴！！](https://s1.ax1x.com/2022/05/17/O5mOpt.jpg)](https://imgtu.com/i/O5mOpt)

**Comment by MingxuanGame** [comment]
> > 提醒：把邮件提醒关掉，不然你今晚会睡不着 ![image](https://user-images.githubusercontent.com/68982190/168777591-9903e10e-4bea-4b3c-a082-f68cb708e192.png)
> 
> 好捏，我可以贴贴mingxuanl吗[![贴贴！！](https://camo.githubusercontent.com/6bd3a0936da636e6b3a16cd2e6f6c05dd715d112429b07dd844c5ca89c2e2365/68747470733a2f2f73312e617831782e636f6d2f323032322f30352f31372f4f356d4f70742e6a7067)](https://imgtu.com/i/O5mOpt)

来陪我睡觉

**Comment by Nova-Noir** [comment]
> > > 有没有大哥能帮我搞一个这个机器人啊，好麻烦，我搞不明白
> > 
> > 
> > 把你的shell给我看看，哥哥帮你搞一个\爱心眼/
> 
> 什么是shell

脱下裤子就有啦

**Comment by MingxuanGame** [comment]
哔！统计
s：682
f：137
s=star f=fork
17:29:42

**Comment by Nova-Noir** [comment]
> 提醒：把邮件提醒关掉，不然你今晚会睡不着 ![image](https://user-images.githubusercontent.com/68982190/168777591-9903e10e-4bea-4b3c-a082-f68cb708e192.png)

太晚了，我已经接了30多封email了()

**Comment by Kt-MarIn** [comment]
> > 有没有大哥能帮我搞一个这个机器人啊，好麻烦，我搞不明白
> 
> 把你的shell给我看看，哥哥帮你搞一个\爱心眼/

我真的真的要酸了！！！！NOVA！！！

**Comment by MingxuanGame** [comment]
引流->[GraiaProject/Ariadne](https://github.com/GraiaProject/Ariadne)

**Comment by Nranphy** [comment]
> > > 提醒：把邮件提醒关掉，不然你今晚会睡不着 ![image](https://user-images.githubusercontent.com/68982190/168777591-9903e10e-4bea-4b3c-a082-f68cb708e192.png)
> > 
> > 
> > 好捏，我可以贴贴mingxuanl吗[![贴贴！！](https://camo.githubusercontent.com/6bd3a0936da636e6b3a16cd2e6f6c05dd715d112429b07dd844c5ca89c2e2365/68747470733a2f2f73312e617831782e636f6d2f323032322f30352f31372f4f356d4f70742e6a7067)](https://imgtu.com/i/O5mOpt)
> 
> 来陪我睡觉

[我啊，真的要生气了！](https://s1.ax1x.com/2022/05/17/O5nMN9.gif)](https://imgtu.com/i/O5nMN9)

**Comment by MingxuanGame** [comment]
哔！统计
s：684
f：138
s=star f=fork
17:31:03

**Comment by synodriver** [comment]
## 开始发情了吗（

**Comment by eido999** [comment]
這波引大流

**Comment by MingxuanGame** [comment]
> ## 开始发情了吗（

Kyomotoi/AnimeThesaurus#1

**Comment by mnixry** [comment]
> 這波引大流

@eido999 莫名其妙就火了)

**Comment by mnixry** [comment]
> 哔！统计 s：689 f：139 s=star f=fork 17:33:04

@MingxuanGame 别统计了 怪吵的 我邮箱已经炸了捏

![图片](https://user-images.githubusercontent.com/32300164/168779914-4621fc66-87da-4cbf-b361-5e5d1e077c1d.png)

**Comment by MingxuanGame** [comment]
> > 哔！统计 s：689 f：139 s=star f=fork 17:33:04
> 
> @MingxuanGame 别统计了 怪吵的 我邮箱已经炸了捏
> 
> ![图片](https://user-images.githubusercontent.com/32300164/168779914-4621fc66-87da-4cbf-b361-5e5d1e077c1d.png)

![image](https://user-images.githubusercontent.com/68982190/168780021-99d927c7-6879-4f5f-82bf-1dc85850f935.png)

**Comment by yzyyz1387** [comment]
AD time 广告时间，欢迎浏览机器人部署保姆教程（教不会那种）[https://yzyyz.top/archives/nb2b1.html](https://yzyyz.top/archives/nb2b1.html)

**Comment by KimigaiiWuyi** [comment]
要火！

**Comment by MingxuanGame** [comment]
~~快去水 pr，明天的 github trending 就有你~~

**Comment by mnixry** [comment]
> 快去水 pr，明天的 github trending 就有你

@MingxuanGame 今天水PR 明天上GitHub首页地球转转转

**Comment by KimigaiiWuyi** [comment]
> ~快去水 pr，明天的 github trending 就有你~

水个MD文档的PR（bushi

**Comment by RafuiiChan** [comment]
纯萌新，不会搞，有没有一键部署的安装包啊（）

**Comment by MingxuanGame** [comment]
> > ~快去水 pr，明天的 github trending 就有你~
> 
> 水个MD文档的PR（bushi

![image](https://user-images.githubusercontent.com/68982190/168780958-adacf170-af09-4539-8e38-b679787654eb.png)

**Comment by BlueGlassBlock** [comment]
羡慕真寻 bot？
想要从头开始写自己的 bot？
点 击 这 里 -> <https://graiax.cn>

**Comment by MingxuanGame** [comment]
> 羡慕真寻 bot？ 想要从头开始写自己的 bot？ 点 击 这 里 -> https://graiax.cn

我是学生，所以你能帮帮我吗

**Comment by mnixry** [comment]
羡慕真寻 bot？
想要从头开始写自己的 bot？ 
B站教程点击就送 -> https://www.bilibili.com/video/BV1aZ4y1f7e2

**Comment by ilharp** [comment]
已经传遍各大群了  前来围观

**Comment by Nranphy** [comment]
**【引流】**
快使用[Onebot协议](https://onebot.dev/)一起开发可爱的机器人们⑧~
[![giragira](https://s1.ax1x.com/2022/05/17/O5K06P.jpg)](https://imgtu.com/i/O5K06P)

**Comment by MingxuanGame** [comment]
记得去 nonebot2 点 star -> https://github.com/nonebot/nonebot2

**Comment by RafuiiChan** [comment]
> 

我是小学生，还不会搞这些，也没啥钱，你可以直接免费帮我弄吗

**Comment by yanyongyu** [comment]
羡慕真寻 bot？
想要从头开始写自己的 bot？
NoneBot文档点击就送 -> https://v2.nonebot.dev/

**Comment by MingxuanGame** [comment]
> 羡慕真寻 bot？ 想要从头开始写自己的 bot？ NoneBot文档点击就送 -> https://v2.nonebot.dev/

793 警告

**Comment by mnixry** [comment]
> 已经传遍各大群了 前来围观

@ilharp 不给koishi打个广告吗）

**Comment by yzyyz1387** [comment]
在任何时候向我们提出问题，我们有专业的客服人员为您解决，我们的价目表：
![image](https://user-images.githubusercontent.com/51691024/168781749-7d73ca07-7de4-42ab-832a-9068a575c807.png)

**Comment by MingxuanGame** [comment]
> > 羡慕真寻 bot？ 想要从头开始写自己的 bot？ NoneBot文档点击就送 -> https://v2.nonebot.dev/
> 
> 793 警告

即刻参与文档改进，赚12000￥
https://nonebot.dev/ospp-2022.html

**Comment by Nranphy** [comment]
> > 羡慕真寻 bot？ 想要从头开始写自己的 bot？ NoneBot文档点击就送 -> https://v2.nonebot.dev/
> 
> 793 警告

mingxuanl加油写文档！

**Comment by mnixry** [comment]
> > > 羡慕真寻 bot？ 想要从头开始写自己的 bot？ NoneBot文档点击就送 -> [v2.nonebot.dev](https://v2.nonebot.dev/)
> > 
> > 
> > 793 警告
> 
> 即刻参与文档改进，赚12000￥ [nonebot.dev/ospp-2022.html](https://nonebot.dev/ospp-2022.html)

@MingxuanGame 支持正义广告！

**Comment by RafuiiChan** [comment]
> > 羡慕真寻 bot？ 想要从头开始写自己的 bot？ 点 击 这 里 -> https://graiax.cn
> 
> 我是学生，所以你能帮帮我吗

我是小学生，没钱，也不会弄，你可以免费帮我买个服务器免费帮我弄吗？

**Comment by yzyyz1387** [comment]
代开发票，戳：[[新-基于Nonebot2和go-cqhttp的机器人搭建](https://yzyyz.top/archives/nb2b1.html)](https://yzyyz.top/archives/nb2b1.html)

**Comment by RafuiiChan** [comment]
全都来贴广告了是吧

**Comment by SaarChaffee** [comment]
送一张
![JTL}@PQ10I45U6RR~D P_AV](https://user-images.githubusercontent.com/53519746/168782373-f9a6d871-ab63-4c79-a164-199607f9ab92.jpg)

**Comment by MingxuanGame** [comment]
nonebot2 文档->[点击即送](https://graia.readthedocs.io//)

**Comment by mnixry** [comment]
各位听众们，这可真谓

> 三年Bot无人问，一朝搜图天下知

欲知真寻后事如何，且听下回——分解（拍板）！

**Comment by Siota02** [comment]
都来蹭一蹭是吧

**Comment by RafuiiChan** [comment]
> nonebot2 文档->[点击即送](https://graia.readthedocs.io//)

写着nonebot2文档内容却是graia，你究竟是什么人

**Comment by CMHopeSunshine** [comment]
![J{ED%X 0IX5PH)PB PA`PS](https://user-images.githubusercontent.com/63870437/168782689-7936b951-36cd-4eba-8195-f32dbff89c15.jpg)
太热闹了

**Comment by MingxuanGame** [comment]
真寻一键部署脚本：[点此领取](https://www.bilibili.com/video/BV1GJ411x7h7)

**Comment by lookup-cat** [comment]
火钳刘明

**Comment by yzyyz1387** [comment]
![image](https://user-images.githubusercontent.com/51691024/168783036-0fcbc5f9-f3ca-4bff-af6c-50ded1114241.png)

**Comment by Nranphy** [comment]
推荐书目
![Nonebot梗图](https://s3.bmp.ovh/imgs/2022/05/17/080cb0cfb87dde40.jpg)

**Comment by kexue-z** [comment]
> 真寻一键部署脚本：[点此领取](https://www.bilibili.com/video/BV1GJ411x7h7)

这个是骗子 举办了

**Comment by Nova-Noir** [comment]
> 真寻一键部署脚本：[点此领取](https://www.bilibili.com/video/BV1GJ411x7h7)

Commented 18days ago
不想和你这种人废话，block了

**Comment by PadorFelice** [comment]
想要属于和真寻bot一样的bot吗！！还在苦恼自己不会写吗！！戳链接 https://v2.nonebot.dev/ 参与活动！！只需一颗star即可免费领取学习资料！！！名额有限！先到先得！https://v2.nonebot.dev/

**Comment by Azurlane-a** [comment]
> 在任何时候向我们提出问题，我们有专业的客服人员为您解决，我们的价目表： ![image](https://user-images.githubusercontent.com/51691024/168781749-7d73ca07-7de4-42ab-832a-9068a575c807.png)

![%(0ZQ48F$S8L8Y(NKNDUI$8](https://user-images.githubusercontent.com/42808392/168783585-09114122-a8a9-4fe6-8788-fa1c543d2707.jpg)

**Comment by MeetWq** [comment]
[真寻插件库](https://github.com/noneplugin) ，超多实用插件（大雾）

**Comment by Nranphy** [comment]
> > 真寻一键部署脚本：[点此领取](https://www.bilibili.com/video/BV1GJ411x7h7)
> 
> Commented 18days ago 不想和你这种人废话，block了

我有这张，但是怕发出来对大佬不好捏

**Comment by ilharp** [comment]
呜呜呜……邮箱要……要……要溢出来了……（哭

**Comment by MingxuanGame** [comment]
> [真寻插件库](https://github.com/noneplugin) ，超多实用插件（大雾）

明明是[这个](https://github.com/pcrbot/HoshinoBot-plugins-index)

**Comment by mnixry** [comment]
那我也打个广告

https://hikari.obfs.dev/

动漫图片聚合搜索网站！接入的API比真寻更多！

**Comment by RafuiiChan** [comment]
我也打个广告

# 广告

**Comment by Nranphy** [comment]
> [真寻插件库](https://github.com/noneplugin) ，超多实用插件（大雾）

![mq佬赛高！！！！](https://s3.bmp.ovh/imgs/2022/05/17/3d338ec14655e7a6.jpg)

**Comment by mnixry** [comment]
![图片](https://user-images.githubusercontent.com/32300164/168784288-15e55480-f7eb-4e93-9add-d0c616214615.png)

有人租吗 目前优惠价一张女装照一个广告位！

**Comment by MingxuanGame** [comment]
> ![图片](https://user-images.githubusercontent.com/32300164/168784288-15e55480-f7eb-4e93-9add-d0c616214615.png)
> 
> 有人租吗 目前优惠价一张女装照一个广告位！

@yanyongyu 的女装行吗（不是

**Comment by yzyyz1387** [comment]
如果您在开发过程中注意到了某nb群，它的加群验证问题是
> nb的最新版本号是？  

此时您应当回答如下版本号：  
> v1.0.0-rc1

**Comment by yzyyz1387** [comment]
> > ![图片](https://user-images.githubusercontent.com/32300164/168784288-15e55480-f7eb-4e93-9add-d0c616214615.png)
> > 有人租吗 目前优惠价一张女装照一个广告位！
> 
> @yanyongyu 的女装行吗（不是

我出我肉丝照

**Comment by Nova-Noir** [comment]
> > ![图片](https://user-images.githubusercontent.com/32300164/168784288-15e55480-f7eb-4e93-9add-d0c616214615.png)
> > 有人租吗 目前优惠价一张女装照一个广告位！
> 
> @yanyongyu 的女装行吗（不是

我品鉴一下:monocle_face:

**Comment by mnixry** [comment]
> v1.0.0-rc1

不合适 真不合适 这就太不合适了

**Comment by BlueGlassBlock** [comment]
> 此时您应当回答如下版本号：
> 
> > v1.0.0-rc1

不是 `0.6.16` 吗 （跑）

**Comment by MingxuanGame** [comment]
> > > ![图片](https://user-images.githubusercontent.com/32300164/168784288-15e55480-f7eb-4e93-9add-d0c616214615.png)
> > > 有人租吗 目前优惠价一张女装照一个广告位！
> > 
> > 
> > @yanyongyu 的女装行吗（不是
> 
> 我品鉴一下🧐

![image](https://user-images.githubusercontent.com/68982190/168785210-728fe3bc-73dd-4f48-bb39-97ca9dc7db72.png)

**Comment by Siota02** [comment]
![image](https://user-images.githubusercontent.com/88393237/168785174-978d6bec-4e60-449e-b76e-dc000d7585a3.png)

**Comment by ilharp** [comment]
> > 已经传遍各大群了 前来围观
> 
> @ilharp 不给koishi打个广告吗）

##### （基建还在建设中  不想打广告

##### （而且打广告也应该是梦梦来

**Comment by MingxuanGame** [comment]
真寻 star 统计图表（单位：天）
[![Star History Chart](https://api.star-history.com/svg?repos=HibiKier/zhenxun_bot&type=Date)](https://star-history.com/#HibiKier/zhenxun_bot&Date)

**Comment by yzyyz1387** [comment]
![image](https://user-images.githubusercontent.com/51691024/168789765-50a41014-1d18-42bb-a4a3-b07626f37db4.png)
与作者的早期合影，非常可爱

**Comment by synodriver** [comment]
> ![image](https://user-images.githubusercontent.com/51691024/168789765-50a41014-1d18-42bb-a4a3-b07626f37db4.png) 与作者的早期合影，非常可爱

来和我超  ~~哈斯哈斯~~

**Comment by RxinnotRstar** [comment]
英雄联盟，非常好安卓，爱来自瓷器

**Comment by ilharp** [comment]
![image](https://user-images.githubusercontent.com/20179549/168794809-365b9745-8735-4652-aa16-87c7053c95ab.png)

感觉这样的图很有纪念意义啊

**Comment by Lyuu23** [comment]
这个机器人要怎么搭啊，小白，求大佬教教

**Comment by RxinnotRstar** [comment]
> ![image](https://user-images.githubusercontent.com/20179549/168794809-365b9745-8735-4652-aa16-87c7053c95ab.png)
> 
> 感觉这样的图很有纪念意义啊
> 
> src -> [#162 (comment)](https://github.com/HibiKier/zhenxun_bot/issues/162#issuecomment-1128675555)

我点star的时候（几分钟前）855，现在873，确实很快

**Comment by KafCoppelia** [comment]
欢迎使用👉[适合小白的即插即用插件](https://github.com/MinatoAquaCrews/nonebot_instant_plugins)
老❤婆❤不❤在❤家❤
nb2👈机器人🤖部署🚧
激㊙爽🈲使🔞用
即刻🚚插件🚚
即⛏插即🛠用
小白机器人本当上手

**Comment by yyuueexxiinngg** [comment]
👀

**Comment by Golden-Pigeon** [comment]
所以，为什么删库了

**Comment by Myfanqie** [comment]
好耶

**Comment by Ayaya233** [comment]
慕名而来，发生甚么事了

**Comment by MingxuanGame** [comment]
跑路了

**Comment by Ayaya233** [comment]
> 跑路了 #167

切换分支

**Comment by MingxuanGame** [comment]
看破不说破

> > 跑路了 #167
> 
> 切换分支

**Comment by ilharp** [comment]
看起来跑路了，默哀五秒钟（迫真

**Comment by Ayaya233** [comment]
> 看破不说破
> 
> > > 跑路了 #167
> > 
> > 
> > 切换分支

打扰了，进行一个撤回（

**Comment by Ice-Cirno** [comment]
用了好多Hoshino的插件却没有Hoshino本家的广告位🤡😢

**Comment by DaiShengSheng** [comment]
> 用了好多的Hoshino插件却没有[Hoshino](https://github.com/Ice-Cirno/HoshinoBot)本家的广告位🤡😢

呜呜呜，咖啡佬我的咖啡佬！
重振hoshino荣光，我辈义不容辞！！！

**Comment by Fader282** [comment]
> 用了好多的Hoshino插件却没有[Hoshino](https://github.com/Ice-Cirno/HoshinoBot)本家的广告位🤡😢

咖啡佬我的咖啡佬！

**Comment by j1g5awi** [comment]
合影留念！

**Comment by Well2333** [comment]
寒假的时候我还打算出个docker部署成品机器人来着，本来预定是真寻，结果被我咕了（

**Comment by Well2333** [comment]
看来错过了爆火的良机

**Comment by mnixry** [comment]
> 用了好多的Hoshino插件却没有[Hoshino](https://github.com/Ice-Cirno/HoshinoBot)本家的广告位🤡😢

@Ice-Cirno 已添加）

**Comment by mnixry** [comment]
![图片](https://user-images.githubusercontent.com/32300164/168814531-f050b4ab-0f5e-4dd2-b1fb-6f5bca60422b.png)

@HibiKier 我突然觉得这个选项就是为真寻现在的状况打造的）不考虑开一个嘛（

**Comment by shiodd** [comment]
> 看破不说破
> 
> > > 跑路了 #167
> > 
> > 
> > 切换分支

大家懂得都懂就行了（）

**Comment by zhzRedstone** [comment]
我错过了什么（
