### ISSUE TITLE
签到问题

### ISSUE THREAD

**Issue by QAQATT** [HibiKier/zhenxun_bot#1621]
### 真寻版本：0.2.2
之前按照 #1601 操作了下，然后正常了，今天发送签到时返回的是签到排行，且还是有部分群员不在例表里
![PN%{27WI941 AD9QOYTG`T0](https://github.com/user-attachments/assets/ab106420-d7bc-42b7-b002-b3227669037c)
![JA_}DRB$@P%RKO3PW9NPUM3](https://github.com/user-attachments/assets/b9160643-5b1b-4894-97e6-0783fc3a95af)

**Comment by AkashiCoin** [comment]
再跑一下 #1601

**Comment by QAQATT** [comment]
刚又跑完之后才发的这个ISS

**Comment by HibiKier** [comment]
更新代码或者锁定版本

**Comment by QAQATT** [comment]
签到也更新到dev之后好了
