### ISSUE TITLE
启动机器人失败不知道什么原因

### ISSUE THREAD

**Issue by krasus1995** [HibiKier/zhenxun_bot#1631]
### 错误截图

![1726336773529](https://github.com/user-attachments/assets/b2c8fa1b-e856-48f5-856b-32ca8fbc6cdd)

**Comment by HibiKier** [comment]
换个端口看看？

**Comment by AkashiCoin** [comment]
大概权限问题，你当前用户没有权限监听端口，可以换root用户再进行尝试

**Comment by Windsland52** [comment]
配置里的12549换一下看看

**Comment by krasus1995** [comment]
ok了，我把代理删了就行了，我的电脑不知道怎么了，clash设置不了固定的端口
