### ISSUE TITLE
群机器人的webui启动失败

### ISSUE THREAD

**Issue by fuhua963** [HibiKier/zhenxun_bot#1636]
### 错误截图

![image](https://github.com/user-attachments/assets/e512f933-656b-4538-8df8-42b44c2cb9e0)

### 日志截图

![image](https://github.com/user-attachments/assets/3e4413ca-a6ef-41c6-835a-c81c38527185)

### 错误说明

真寻的webui 页面空白，机器人无反应，使用的webui插件为v0.2，（bot.py下载有错误，自行手动下载的），已经安装
![image](https://github.com/user-attachments/assets/e4d3d471-0644-4ea0-b738-54f264c0c3f2)
和登录bot的QQ，数据库安装教程设置完毕
![image](https://github.com/user-attachments/assets/42ca4d01-f2ac-4269-904f-23baadcf682f)
配置文件config.yaml在data文件夹下未修改，请问可能是什么问题导致的？

**Comment by Windsland52** [comment]
感觉还是数据库相关的问题

**Comment by HibiKier** [comment]
你手动下载后放置的路径不对吧
![图片](https://github.com/user-attachments/assets/6e675ada-1b02-419c-9b13-f052f73710b6)
![图片](https://github.com/user-attachments/assets/b7b51a6b-4fb7-435b-8e30-f21e4416ee8d)

**Comment by fuhua963** [comment]
> 你手动下载后放置的路径不对吧 ![图片](https://private-user-images.githubusercontent.com/45528451/368254306-6e675ada-1b02-419c-9b13-f052f73710b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTgwMTUsIm5iZiI6MTcyNjc1NzcxNSwicGF0aCI6Ii80NTUyODQ1MS8zNjgyNTQzMDYtNmU2NzVhZGEtMWIwMi00MTljLTliMTMtZjA1MmY3MzcxMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE0NTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3N2FmYmY3YzNkNjQ3OTczY2ZiNWI3MzU0NDY1NDI2MjUzYjI4N2JlYjJiMDdmZGJhYWUyM2E2MjNjMzY3YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J7NJ4q0L3Wf4Xtil6UJlh0I88C6L476dbyYSQ163ne0) ![图片](https://private-user-images.githubusercontent.com/45528451/368254337-b7b51a6b-4fb7-435b-8e30-f21e4416ee8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTgwMTUsIm5iZiI6MTcyNjc1NzcxNSwicGF0aCI6Ii80NTUyODQ1MS8zNjgyNTQzMzctYjdiNTFhNmItNGZiNy00MzViLThlMzAtZjIxZTQ0MTZlZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE0NTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0Y2U5NzkxYjllZDU0NWMzNjJhM2U5YzYzNjE1YTFlMTg2ZDhlM2M5MWY3NWRiY2U4MjRjZWViOGQyMTgyNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uWFXIopDQTCiT5IlvA4W1kiOzCgejXSp-xu6RButpUo)

放置的路径应该是没问题的
![image](https://github.com/user-attachments/assets/1296c81f-4b9f-46d5-b094-0208fd5216f6)

**Comment by HibiKier** [comment]
在.env.dev中打开debug后看看启动后webui相关的日志

**Comment by HibiKier** [comment]
数据库报错没关系，webui相关的日志报错了吗，有看到挂在css什么的吗

**Comment by fuhua963** [comment]
> 数据库报错没关系，webui相关的日志报错了吗，有看到挂在css什么的吗

webui的相关日志存放在哪个文件夹呢？还是说直接print输出的？目前print输出的红色报错，只有上图这些

**Comment by HibiKier** [comment]
就这个控制台日志里有看到挂载css之类的日志吗

**Comment by fuhua963** [comment]
> 就这个控制台日志里有看到挂载css之类的日志吗
无论是.log文件或者控制台的print输出，我ctrl+F查找 ccs 都没有匹配的结果
![image](https://github.com/user-attachments/assets/13749dd3-bac1-42e3-af26-60b065120e17)

**Comment by HibiKier** [comment]
你webui插件加载成功了吗？

**Comment by HibiKier** [comment]
把你debug开启后的日志文件发来看看

**Comment by fuhua963** [comment]
> 把你debug开启后的日志文件发来看看
我是在.env.dev的这行开启的debug
![image](https://github.com/user-attachments/assets/e0683a71-fab3-4c8f-9707-3c17c32e5bd9)
今天运行的日志文件如下
[2024-09-21.log](https://github.com/user-attachments/files/17084347/2024-09-21.log)
[error_2024-09-21.log](https://github.com/user-attachments/files/17084348/error_2024-09-21.log)
