### ISSUE TITLE
反向websocket连接错误

### ISSUE THREAD

**Issue by Windsland52** [HibiKier/zhenxun_bot#1637]
### 错误截图

![屏幕截图 2024-09-18 232823](https://github.com/user-attachments/assets/ede8a103-5d61-40a9-a5b0-bcf36a62b39c)

### 日志截图

![屏幕截图 2024-09-18 232825](https://github.com/user-attachments/assets/e30ed9d3-a1f5-46af-973b-d75a26fc2b1a)

### 错误说明

napcat采用docker部署，启动命令为：

```bash
docker run -d \
-e ACCOUNT=1057521489 \
-e WSR_ENABLE=true \
-e WS_URLS='["ws://127.0.0.1:8080/onebot/v11/ws"]' \
-e NAPCAT_GID=0 \
-e NAPCAT_UID=0 \
--name napcat \
--restart=always \
mlikiowa/napcat-docker:latest
```

postgresql按照[postgresql安装文档](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/psql_ubuntu.html)直接在系统完成`1.安装`小节

真寻也是直接按照[真寻安装文档](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/zhenxun.html)直接安装在系统。
配置文件：
```
# .env
ENVIRONMENT=dev
```
```
# .env.dev
SUPERUSERS=["已填"]

COMMAND_START=[""]

SESSION_RUNNING_EXPRESSION="别急呀,小真寻要宕机了!QAQ"

NICKNAME=["真寻", "小真寻", "绪山真寻", "小寻子"]

SESSION_EXPIRE_TIMEOUT=30

# 全局图片统一使用bytes发送，当真寻与协议端不在同一服务器上时为True
IMAGE_TO_BYTES = False

# 回复消息时自称
SELF_NICKNAME="小真寻"

# 数据库配置
# 示例: "postgres://user:password@127.0.0.1:5432/database"
DB_URL = "postgres://postgres:zhenxun_bot@127.0.0.1:5432/zhenxun_bot"

# 系统代理
# SYSTEM_PROXY = "http://127.0.0.1:7890"

PLATFORM_SUPERUSERS = '
  {
    "qq": ["已填"],
    "dodo": [""]
  }
'

DRIVER=~fastapi+~httpx+~websockets


# LOG_LEVEL=DEBUG
# 服务器和端口
HOST = 127.0.0.1
PORT = 8080
```

目前真寻这边除了连接数据库时报错`数据迁移 || 错误<class 'tortoise.exceptions.OperationalError'>: relation "public.sign_group_users" does not exist`，就没有别的问题了。现在问题在docker部署的napcat反向ws连接失败，不知道问题在什么地方

**Comment by HibiKier** [comment]
host改成0.0.0.0

**Comment by Windsland52** [comment]
> host改成0.0.0.0

改完还是不行

**Comment by HibiKier** [comment]
napcat连接的地址也要改

**Comment by Windsland52** [comment]
> napcat连接的地址也要改

改成ws://0.0.0.0:8080/onebot/v11/ws了，还是不行

**Comment by Windsland52** [comment]
> > napcat连接的地址也要改
> 
> 改成ws://0.0.0.0:8080/onebot/v11/ws了，还是不行

![Uploading 屏幕截图 2024-09-18 232823.png…]()

**Comment by HibiKier** [comment]
napcat里的127要改成你宿主机的ip

**Comment by Windsland52** [comment]
> napcat里的127要改成你宿主机的ip

可以了，感谢大佬
