### ISSUE TITLE
check中没有cpuinfo

### ISSUE THREAD

**Issue by ATTomatoo** [HibiKier/zhenxun_bot#1648]
### 真寻版本：dev-v0.2.2-d539b1f

![PMMYFR_~~{WA2%N@UW@F`GB](https://github.com/user-attachments/assets/9279a759-b134-4402-a6f9-34bc85193b2b)

**Comment by HibiKier** [comment]
获取dev里的pyproject.toml和lock文件 poetry install

**Comment by ATTomatoo** [comment]
重新获取了，OK了
