### ISSUE TITLE
通过插件商店成功安装插件，但有多项插件启动时报错

### ISSUE THREAD

**Issue by yozorachan** [HibiKier/zhenxun_bot#1649]
### 错误截图

![5IH R`XVZM8JXN80AF } E](https://github.com/user-attachments/assets/b3bfe80e-4742-4dc0-a5c3-39048a3f062d)

![% 0XF~%0AEXA1D(CTIXIAEC](https://github.com/user-attachments/assets/356c9191-d4e8-412c-981d-f605abe16bed)

![O_ 9XH2FY$9ZPQ%C`NF)` I](https://github.com/user-attachments/assets/03204d85-3ba6-417b-b79a-0ed0298b2fe2)

![_5HEC7I8PX)8`X69)5Y~73B](https://github.com/user-attachments/assets/2472de30-3653-45a1-8dfd-fb15ed1b9d0a)

![E_HRCJ00 )R1 LNYS`2ZNUW](https://github.com/user-attachments/assets/c503e11c-8a49-4db1-9f66-37ed8cdd3326)

![HHHO`PL$PXD`5 }MK D{W$7](https://github.com/user-attachments/assets/ac729067-20d6-4eeb-8286-aa01dcd24179)

![S`F$U4% A}7KCKAGG6 GL%V](https://github.com/user-attachments/assets/d4f32ad2-fc36-437f-9a80-bcdb4a9274f9)

### 日志截图

[img]

### 错误说明

即使通过插件商店成功安装了插件，但是在启动时，仍有多项插件会产生上述报错
![313e2a0eb74c10578f3402dadcdfe681](https://github.com/user-attachments/assets/e55e69c5-1bd6-498a-b6da-a4d1a163c159)
![1c38b560cf367fe8e4a25289bab32f7b](https://github.com/user-attachments/assets/5c561721-2405-4ce9-8b90-48fbfa2e2cb3)

**Comment by HibiKier** [comment]
真寻版本更新到dev

**Comment by yozorachan** [comment]
> 真寻版本更新到dev

谢谢，解决了
![397EAE85DB7AF094777BC29FFB57AAF4](https://github.com/user-attachments/assets/26267f38-d711-45e9-be35-ea60d0c4a06f)
