### ISSUE TITLE
真寻无法响应指令

### ISSUE THREAD

**Issue by wclwind** [HibiKier/zhenxun_bot#1656]
### 错误截图
插件商店错误↓
![image](https://github.com/user-attachments/assets/f11c6586-36f1-4706-80c0-2bd7ed59f26b)

帮助错误↓
![image](https://github.com/user-attachments/assets/9c669015-b2b5-4535-8f40-edaa4043b7ea)

### 日志截图

![7b245633-40fa-4e8f-9c6c-2e779a0ac324](https://github.com/user-attachments/assets/ef9a5ea7-1aa3-4b86-9d8c-df6e3a42365a)

### 错误说明
我向真寻发送了【插件商店】和【帮助】两个指令，但是没有得到响应。关于【插件商店】的错误，我不知道那个“httpx.connectTimeout”是不是指的我的网络连接性有问题；而关于【帮助】的错误，我现在仍然不明白 真寻和NapCatQQ之间到底要不要有实际的储存路径映射关系，还是说它们之间只要通过反向代理连接就可以实现文字和图片的交换。以上是我的一些理解和不解，希望大佬能给我解答下疑惑。

**Comment by HibiKier** [comment]
插件商店建议上个魔法，napcat和zhenxun肯定是要实际路径映射的，但是zhenxun 的.env.dev中提供了全局图片转base64转发配置，你可以通过修改该配置来避免映射路径

**Comment by wclwind** [comment]
> 插件商店建议上个魔法，napcat和zhenxun肯定是要实际路径映射的，但是zhenxun 的.env.dev中提供了全局图片转base64转发配置，你可以通过修改该配置来避免映射路径

感谢，两个问题解决。还有点疑问就是，“全局图片转base64转发配置”，那么是不是代表语音没法转发了？我刚刚也还发现一个问题就是让真寻自己重启的话，它会提示地址被占用了，但是手动停止真寻再启动的话是没有这个问题的。
![image](https://github.com/user-attachments/assets/66b88474-5b79-4456-a2d6-1531a3ff1829)

**Comment by HibiKier** [comment]
语音没有，因为zhenxun基本上是图片，如果有需要后续会加上，重启实际上是执行根目录下restar.sh脚本，你可以看着改这个文件

**Comment by wclwind** [comment]
> 语音没有，因为zhenxun基本上是图片，如果有需要后续会加上，重启实际上是执行根目录下restar.sh脚本，你可以看着改这个文件

okk，最后一个问题，如果我想把真寻的路径映射出去，那么我该映射哪个路径呢（如何映射）？

**Comment by HibiKier** [comment]
参考dev分支中dockerfiler

**Comment by wclwind** [comment]
> 参考dev分支中dockerfiler

ok，感谢。
