### ISSUE TITLE
真寻最多只能上传11张图片到图库

### ISSUE THREAD

**Issue by wclwind** [HibiKier/zhenxun_bot#1660]
### 日志截图

![image](https://github.com/user-attachments/assets/e6ab53af-c70a-48cd-8294-c8f69f703bb4)
![image](https://github.com/user-attachments/assets/f8e4dd73-f1d5-4705-9b23-659b54038804)

### 错误说明

使用QQ让真寻上传图片到图库，真寻只能上传11张（0-10）；后续继续上传会把第11张（编号10）给覆盖掉。图中我上传一张图片到【萝莉】图库，显示为编号10，此时真寻已经将原本的编号为10的图片覆盖。

**Comment by HibiKier** [comment]
插件库已更新
