### ISSUE TITLE
代码下载失败

### ISSUE THREAD

**Issue by modcrafts** [HibiKier/zhenxun_bot#167]
我下载下来只有两个文件,怎么回事,原来的代码哪去了  
刷新一下就没了,有没有大佬教我怎么下载啊,什么破项目,下载个代码都这么费劲  
(((((((((((((

**Comment by Golden-Pigeon** [comment]
看来作者删库了

**Comment by synodriver** [comment]
git fetch origin main:main && git checkout main

**Comment by lhhxxxxx** [comment]
懂得都懂，不懂的去学学git

**Comment by yanyongyu** [comment]
🎣执法

**Comment by MingxuanGame** [comment]
看破不说破

**Comment by Rui9700K** [comment]
已跑路哈哈哈哈

**Comment by Myfanqie** [comment]
估计是跑路了，hh

**Comment by synodriver** [comment]
# run

**Comment by TBSdesu** [comment]
笑死了,我先放一个git教程在这里
https://www.w3cschool.cn/git/

**Comment by kexue-z** [comment]
![JP0M3HS8}ZR8NA2$}P0X__5](https://user-images.githubusercontent.com/71873002/168804884-9b782233-65d6-43c5-8614-e9ca9daa3419.jpg)

**Comment by HYLnP** [comment]
# 闷声发大财不好吗

**Comment by MingxuanGame** [comment]
![{38FBR`B}_EVA9(YU$X{LW5](https://user-images.githubusercontent.com/68982190/168805180-21ae9dda-5013-48d0-8653-64164363d2cc.jpg)

**Comment by synodriver** [comment]
呜呜呜（发出ddl的声音

**Comment by summerkirakira** [comment]
![C324483FD2EF846B815141C7EA7CD62B](https://user-images.githubusercontent.com/56951617/168805945-3467cf85-6a41-421b-8189-9a0d2ea9d939.jpg)
这边建议是直接去柬埔寨问问（（（

**Comment by Myfanqie** [comment]
![%EO(YMU5}4PGIJJ~ZLOO19K](https://user-images.githubusercontent.com/50412437/168806675-6c321d0b-2ea3-4af3-b20a-24a7aca2e086.jpg)

**Comment by MingxuanGame** [comment]
star 超过 [HoshinoBot](https://github.com/Ice-Cirno/HoshinoBot)力

**Comment by synodriver** [comment]
# 喧 宾 夺 主

**Comment by MingxuanGame** [comment]
hoshino 两年的 star 被真寻一天超了

> # 喧 宾 夺 主

**Comment by MingxuanGame** [comment]
# 真寻 1000 star 纪念！

# 你我都是见证人！

明早看：https://github.com/trending
![image](https://user-images.githubusercontent.com/68982190/168808142-14c7d509-969e-44e0-96f8-02f100751739.png)

**Comment by DaiShengSheng** [comment]
> hoshino 两年的 star 被真寻一天超了
> 
> > # 喧 宾 夺 主

hoshino 呜呜呜呜，我的hoshino

**Comment by Special-Week** [comment]
真寻我的真寻,呜呜呜,瓜群你罪该万死

**Comment by ayanamiblhx** [comment]
> # 真寻 1000 star 纪念！
> 
> # 你我都是见证人！
> 
> 明早看：https://github.com/trending
> ![image](https://user-images.githubusercontent.com/68982190/168808142-14c7d509-969e-44e0-96f8-02f100751739.png)
> 

zhenxun为什么是神?在谈论这个问题之前，我想先说说其它bot相较于zhenxun究竟差在了哪里
首先是犯下傲慢之罪的hoshino，凭借起步早首先打下bot社区半壁江山就露出不屑的笑，这种傲慢的bot注定走不长远，事实也是如此，靠着一个公主连结收获大量star后就一直迟于更新，最终泯然众人。与之相比神就很谦卑，每周都保持着2～3次的高频率更新，神不是不会，只是不想通过太完美的表现让对手绝望，可笑有些人不理解神的良苦用心，竟然还用这些事来讥讽神，我劝你们好自为之。

**Comment by MingxuanGame** [comment]
> > # 真寻 1000 star 纪念！
> > # 你我都是见证人！
> > 明早看：https://github.com/trending
> > ![image](https://user-images.githubusercontent.com/68982190/168808142-14c7d509-969e-44e0-96f8-02f100751739.png)
> 
> zhenxun为什么是神?在谈论这个问题之前，我想先说说其它bot相较于zhenxun究竟差在了哪里 首先是犯下傲慢之罪的hoshino，凭借起步早首先打下bot社区半壁江山就露出不屑的笑，这种傲慢的bot注定走不长远，事实也是如此，靠着一个公主连结收获大量star后就一直迟于更新，最终泯然众人。与之相比神就很谦卑，每周都保持着2～3次的高频率更新，神不是不会，只是不想通过太完美的表现让对手绝望，可笑有些人不理解神的良苦用心，竟然还用这些事来讥讽神，我劝你们好自为之。

[#162(comment)](https://github.com/HibiKier/zhenxun_bot/issues/162#issuecomment-1128795179)

**Comment by Liunkwww** [comment]
警惕大佬打萌新牌

**Comment by Nranphy** [comment]
警惕大佬打萌新牌（噗哈哈哈哈）

**Comment by King1778** [comment]
搜了一下
![image](https://user-images.githubusercontent.com/96098725/168817862-46beeb64-8479-4244-bd63-e608895940e9.png)

**Comment by Slinet6056** [comment]
作者跑路了呢（

**Comment by EvanFried** [comment]
试到最后一步发现nonebot.adapters.onebot这东西找不到，装了半天包都不行，算了算了（明明在全局都能找到nonebot2）

**Comment by othinus001** [comment]
> 试到最后一步发现nonebot.adapters.onebot这东西找不到，装了半天包都不行，算了算了（明明在全局都能找到nonebot2）

如果不是poetry环境，要么与nonebot1冲突，要么nonebot2版本不对

**Comment by wanghaisheng** [comment]
实锤跑路了

**Comment by h265642327** [comment]
永远支持你，真寻❤

**Comment by lightbearer1** [comment]
> 试到最后一步发现nonebot.adapters.onebot这东西找不到，装了半天包都不行，算了算了（明明在全局都能找到nonebot2）

我也遇到了同样的问题，根据大佬的回复，应该是适配器未安装，试试这个：
pip install nonebot-adapter-onebot

**Comment by EvanFried** [comment]
> > 试到最后一步发现nonebot.adapters.onebot这东西找不到，装了半天包都不行，算了算了（明明在全局都能找到nonebot2）
> 
> 我也遇到了同样的问题，根据大佬的回复，应该是适配器未安装，试试这个： pip install nonebot-adapter-onebot

下班回家去试试，不过我昨天也查到了这个安装，装完之后还是不行，我的powershell打开的路径是这个项目的根目录，不过应该没什么影响。

**Comment by EvanFried** [comment]
> > > 试到最后一步发现nonebot.adapters.onebot这东西找不到，装了半天包都不行，算了算了（明明在全局都能找到nonebot2）
> > 
> > 
> > 我也遇到了同样的问题，根据大佬的回复，应该是适配器未安装，试试这个： pip install nonebot-adapter-onebot
> 
> 下班回家去试试，不过我昨天也查到了这个安装，装完之后还是不行，我的powershell打开的路径是这个项目的根目录，不过应该没什么影响。

已成功启动，我重新拉了代码，删了之前的包，重点是要把python版本换掉，我之前是3.10，我换成了3.9，然后再install就没有报错了，之后就很顺利地启动了，已经在调戏了（），我现在在看表结构，除了群权限的数字找不到存在哪个表以外（明明群管理的权限都找在user_info里面了），其他都看的差不多了。
