### ISSUE TITLE
0.2.3版本的开箱插件，启动时会自动把BUFF_PROXY删掉然后报错

### ISSUE THREAD

**Issue by xyzzxy123** [HibiKier/zhenxun_bot#1671]
### 错误截图

[img]

![image](https://github.com/user-attachments/assets/898ca927-5ac1-4da5-a4ef-39448bab80de)

### 日志截图

[img]

![image](https://github.com/user-attachments/assets/4db190d7-33fc-4c97-949d-846647090073)

### 错误说明

更新武器箱时报错：没有配置项 `open_cases .BUFF_PROXY `。然后我想着反正我之前也没用代理，就手动加一行吧。但是加完后重启，这一行就没辣！自动被清楚辣！

> 10-02 14:17:37 [ERROR] zhenxun | Adapter[OneBot V11] 平台[qq] 用户[397921478] 更新武器箱: 暗影 || 错误 <class 'zhenxun.configs.utils.NoSuchConfig'>: 未查询到配置项 MODULE: [ open_cases ] | KEY: [ BUFF_PROXY ]

**Comment by molanp** [comment]
保存了吗

**Comment by HibiKier** [comment]
已更新
