### ISSUE TITLE
某些参数对unban不生效

### ISSUE THREAD

**Issue by molanp** [HibiKier/zhenxun_bot#1676]
### 错误截图

![Image_1728054910650.jpg](https://github.com/user-attachments/assets/a32c5850-760c-4720-945d-40e977fecde4)

### 错误说明

-  `-g`参数对`unban`不生效，无法unban群组
- 人工可以对一个用户或群组ban多次，即使已经被ban
-  希望可以通过id来进行ban和unban操作

**Comment by HibiKier** [comment]
#1681
