### ISSUE TITLE
p站排行显示网络不太好？没有该页数？也许过一会就好了...

### ISSUE THREAD

**Issue by Qyyxzz** [HibiKier/zhenxun_bot#1689]
### 错误截图
![3c0e07bfa3f47bf40071a3148980cc9d](https://github.com/user-attachments/assets/f17f44cb-8b34-4e72-8193-4c5316e89a6d)

### 日志截图
![928a813a3ce6d43080f31f0c95459874](https://github.com/user-attachments/assets/a7008543-eaf3-4c8b-a226-9e17722dc5a5)

### 错误说明
p站排行显示网络不太好？没有该页数？也许过一会就好了...
是hibiapi寄了吗
代理好像是没填漏？ 大佬看看
![928a813a3ce6d43080f31f0c95459874](https://github.com/user-attachments/assets/e0b4d30b-0d6c-4ec9-a237-3cc1cb933e66)
![a408246b1ccdc2d8a989f5f9f5a2b733](https://github.com/user-attachments/assets/04cff2ad-36a1-4129-b893-e57219305749)
![c9531c70f66a35295a88765dc6d4163d](https://github.com/user-attachments/assets/cd16b5bd-4d58-4214-8e2f-b97b3c95292e)

**Comment by HibiKier** [comment]
hibiapi示例站g了，要自己搭一个

**Comment by HibiKier** [comment]
放data/config.yaml下hibiapi配置下面
