### ISSUE TITLE
群聊或私聊除签到功能外均无法响应

### ISSUE THREAD

**Issue by eeeachan27** [HibiKier/zhenxun_bot#1695]
### 错误截图
图1
![6](https://github.com/user-attachments/assets/221c490c-7204-4887-90cd-a77bb6b868b7)

### 日志截图
启动后的机器人终端：
图2
![2](https://github.com/user-attachments/assets/51aacd12-9101-4fec-ba57-9440e83f2386)

拉格朗日：
图3
![3](https://github.com/user-attachments/assets/c860e2fb-9952-4dc9-b940-6e8b3133cb16)

发送帮助后的机器人：
图4
![4](https://github.com/user-attachments/assets/579b7c04-a89c-4157-8aca-78dec08b3d23)

发送后的拉格朗日：
图5
![5](https://github.com/user-attachments/assets/251edade-5d59-4b95-bb5e-f50a3f45cd4d)

### 错误说明

在群组内@聊天，或者私聊 除签到功能外均无法响应
![7](https://github.com/user-attachments/assets/a7672550-e7b4-40dc-9347-0e648311a29b)

私聊发送帮助后发生如图4、图5错误，真寻机器人关闭

小白真心请教，麻烦大佬解答😣

**Comment by HibiKier** [comment]
换python3.10或3.11

**Comment by eeeachan27** [comment]
> 换python3.10或3.11

好的我试试，谢谢！

**Comment by AkashiCoin** [comment]
#1646
