### ISSUE TITLE
在接入QQbot后访问webui时报错

### ISSUE THREAD

**Issue by rubbish-wang** [HibiKier/zhenxun_bot#1696]
### 错误截图
![1fbed9e3455e444644043c6a5e75c59b](https://github.com/user-attachments/assets/0187f6ef-8b89-4a2f-89d1-f8e9bc8b88e2)
### 日志截图

![10c388d865f06fe786c1c73dca1eca24](https://github.com/user-attachments/assets/0a44125c-98f5-4343-b7f4-f5fbf0b14111)
![515251c7f223ed2b45236c708e3aa38a](https://github.com/user-attachments/assets/92629809-2e1c-4730-ad7e-b06a09154143)

### 错误说明

在使用webui时，切换成官方QQbot提示错误

**Comment by HibiKier** [comment]
5a92a4fe3d7bc77b5d826f248dfb43bbb627d16f 该分支已修复
