### ISSUE TITLE
新 意见

### ISSUE THREAD

**Issue by Adsicmes** [HibiKier/zhenxun_bot#17]
![Screenshot_20210801-091501_QQ.png](https://user-images.githubusercontent.com/79645438/127756092-dd8ff25a-4a1f-4327-a557-0af8342ca3a5.png)

**Comment by HibiKier** [comment]
可以考虑，不过要修改数据库结构

**Comment by Adsicmes** [comment]
TODO

- [ ] 定时重启
- [ ] 表情包高度自定义（鲁迅说）
- [ ] 延迟解决
- [ ] 真寻对超级用户态度好点！！！
- [ ] 俄罗斯转盘最大金币数量加入config.py
- [ ] 尽早换掉绘图库（（
- [ ] csgo开箱数据图下载指令
- [ ] 指定群发布公告
- [ ] 用户自己上传图片到免费图床
- [ ] 能不能好好说话整合进去！
- [ ] roll 随机文本 随机数     吃没吃 干不干之类问题的随机回答

就这样吧 嘿嘿

**Comment by Adsicmes** [comment]
TODO +1
- [ ] 指定群指定人ban指定功能

**Comment by HibiKier** [comment]
收到

**Comment by hentaipzl** [comment]
> 收到

请问全局代理支持socks5吗

感谢

**Comment by RealKiro** [comment]
> 收到

- [ ] Docker 啥时候能适配吖，服务器买不起只能最大化利用群晖设备了（大雾

**Comment by HibiKier** [comment]
> 
> 
> > 收到
> 
>     * [ ]  Docker 啥时候能适配吖，服务器买不起只能最大化利用群晖设备了（大雾

9月份

**Comment by RealKiro** [comment]
> 9月份

嗯哪，感谢大佬的项目，目前是在群晖Docker的ubuntu环境下正常运行，期待纯Docker部署 ❤️  🌹

**Comment by wangjiahui1126** [comment]
- [ ] 希望增加网页ui的功能开关插件

类似的我只有找到nonebot1的相关项目https://github.com/pcrbot/HosBotManagerWeb
![6P80@3 4{TXV8E5RJ%7M11O](https://user-images.githubusercontent.com/30306738/134954562-ae72f438-88f9-4a57-8f9d-aca2afc9bae0.png)
![_H}A@$YNNM51HA$3QIPUL}Y](https://user-images.githubusercontent.com/30306738/134954692-11442b4c-264c-4473-9e78-8b50cd27a7a1.png)

另。感谢大佬的项目，真寻真好用呀！

**Comment by HibiKier** [comment]
有空再说，先close了
