### ISSUE TITLE
发生了什么

### ISSUE THREAD

**Issue by Cintser** [HibiKier/zhenxun_bot#170]
我刚刚下载好机器人和一键部署的压缩包，两个都解压了打开一看没安装文件，两个zip都换成exe我的win告诉我运行不了，回来一看作者跑路了？

**Comment by HYLnP** [comment]
# 救命啊
## 救命啊
### 救命啊

**Comment by Lyuu23** [comment]
> 我刚刚下载好机器人和一键部署的压缩包，两个都解压了打开一看没安装文件，两个zip都换成exe我的win告诉我运行不了，回来一看作者跑路了？

突然爆火，怕出事，就先跑路避避风头

**Comment by Cintser** [comment]
那不影响我用机器人吧（还没整明白机器人怎么部署）








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 晚上8:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 发生了什么 (Issue #170)





  
我刚刚下载好机器人和一键部署的压缩包，两个都解压了打开一看没安装文件，两个zip都换成exe我的win告诉我运行不了，回来一看作者跑路了？
  
突然爆火，怕出事，就先跑路避避风头

**Comment by Lyuu23** [comment]
> 那不影响我用机器人吧（还没整明白机器人怎么部署）
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年5月17日(星期二) 晚上8:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HibiKier/zhenxun_bot] 发生了什么 (Issue #170) 我刚刚下载好机器人和一键部署的压缩包，两个都解压了打开一看没安装文件，两个zip都换成exe我的win告诉我运行不了，回来一看作者跑路了？ 突然爆火，怕出事，就先跑路避避风头 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

已经下载下来了的话可以用

**Comment by Cintser** [comment]
不大会用捏，大佬能教一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 晚上8:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 发生了什么 (Issue #170)





  
那不影响我用机器人吧（还没整明白机器人怎么部署）
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年5月17日(星期二) 晚上8:19 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [HibiKier/zhenxun_bot] 发生了什么 (Issue #170) 我刚刚下载好机器人和一键部署的压缩包，两个都解压了打开一看没安装文件，两个zip都换成exe我的win告诉我运行不了，回来一看作者跑路了？ 突然爆火，怕出事，就先跑路避避风头 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
已经下载下来了的话可以用

**Comment by Lyuu23** [comment]
> 

看文档.jpg

**Comment by Cintser** [comment]
文档在哪？（痴呆）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 晚上8:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 发生了什么 (Issue #170)





   
看文档.jpg

**Comment by sakura12135** [comment]
> 

救。。。来迟了文件都没了，能不能有分享。。我研究成功就来教大家

**Comment by Cintser** [comment]
我挽救到两个压缩包，一个大概是机器人本体，一个是《一键部署》文件，加qq3439327248可以发你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 晚上8:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 发生了什么 (Issue #170)





   
救。。。来迟了文件都没了，能不能有分享。。我研究成功就来教大家

**Comment by Cintser** [comment]
我也不会用

**Comment by sakura12135** [comment]
https://hibikier.github.io/zhenxun_bot/
