### ISSUE TITLE
戳一戳问题

### ISSUE THREAD

**Issue by tyh81920** [HibiKier/zhenxun_bot#1707]
### 错误截图

[img]

### 日志截图

![image](https://github.com/user-attachments/assets/f286fe7d-d1f0-427e-9a58-a4d16907f973)
![Screenshot_20241021_212100_com tencent mobileqq](https://github.com/user-attachments/assets/dcd9e472-bcb2-47a9-a943-cf38437c85c6)

### 错误说明

戳一戳没反应

**Comment by HibiKier** [comment]
啊？
