### ISSUE TITLE
好感度问题

### ISSUE THREAD

**Issue by tyh81920** [HibiKier/zhenxun_bot#1709]
### 错误截图

![0368e2f3e13311f5bc86c2301a4ac17c](https://github.com/user-attachments/assets/825ed507-06bb-4520-8030-df7f24651388)
![c9795913f204b15861fa552a36b3e26a](https://github.com/user-attachments/assets/280d5f5e-ca8a-4f31-95db-82c151a4c862)

### 日志截图
![image](https://github.com/user-attachments/assets/0264da8d-7dd8-4406-9b86-6b6b93803cef)

### 错误说明

好感度改了没反应

**Comment by HibiKier** [comment]
有缓存，可以发 我的签到 看看

**Comment by HibiKier** [comment]
才看到你sql错了，用 exec UPDATE "sign_users" SET impression=1000 WHERE  user_id='xxxxx'

**Comment by tyh81920** [comment]
> 才看到你sql错了，用 exec UPDATE "sign_users" SET impression=1000 WHERE user_id='xxxxx'

谢谢解决了

**Comment by tyh81920** [comment]
话说怎么改金币呢？

**Comment by HibiKier** [comment]
exec UPDATE "user_console" SET gold=1000 WHERE user_id='xxxxx'

**Comment by tyh81920** [comment]
> exec UPDATE "user_console" SET gold=1000 WHERE user_id='xxxxx'

好的谢谢大佬
