### ISSUE TITLE
加载TK插件时出现的“bag_user“报错

### ISSUE THREAD

**Issue by Puff-pastry-star** [HibiKier/zhenxun_bot#1722]
### 错误截图

nothing

### 日志截图

![image](https://github.com/user-attachments/assets/7b00fd56-6cee-4b57-bcc4-5abe3d00b095)

### 错误说明

发生了加载插件错误...
但是真寻本体以及其他插件仍然可以使用

**Comment by HibiKier** [comment]
第三方插件没适配新版本真寻

**Comment by Puff-pastry-star** [comment]
有什么解决方法吗

**Comment by HibiKier** [comment]
帮你催作者了，桀桀桀

**Comment by Puff-pastry-star** [comment]
好银
