### ISSUE TITLE
出现sql语句不执行的情况

### ISSUE THREAD

**Issue by Puff-pastry-star** [HibiKier/zhenxun_bot#1723]
### 错误截图

![image](https://github.com/user-attachments/assets/5df35e5b-c47a-4ddc-aa14-dfdd235d77e0)

### 日志截图

无报错，但不执行
![image](https://github.com/user-attachments/assets/c33ddcbe-6087-4669-ab77-8042768cf1ba)
_11-11 12:58:13 [SUCCESS] nonebot | OneBot V11 3455634233 | [message.private.friend]: Message 15424106 from 3575277439 'exec UPDATE "user_console" SET gold=\'114514\' WHERE user_id=\'3575277439\''
11-11 12:58:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-11 12:58:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.web_ui.api.tabs.manage.chat, lineno=26)
11-11 12:58:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-11 12:58:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
11-11 12:58:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-11 12:58:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.web_ui.api.tabs.manage.chat, lineno=26) running complete
11-11 12:58:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
11-11 12:58:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-11 12:58:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.help_help, lineno=32)
11-11 12:58:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.help_help, lineno=32) running complete
11-11 12:58:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.ai, lineno=54)
11-11 12:58:16 [INFO] zhenxun | Adapter[OneBot V11] 平台[qq] 用户[3575277439] CMD[ai] 问题：exec UPDATE "user_console" SET gold='114514' WHERE user_id='3575277439' ---- 回答：没什么话题聊了是吗
11-11 12:58:17 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.ai, lineno=54) running complete_

### 错误说明

发生了真寻没有正确理解指令错误...

**Comment by HibiKier** [comment]
你的nb版本是多少

**Comment by HibiKier** [comment]
有装其他bot吗

**Comment by Puff-pastry-star** [comment]
服务器环境：

**Comment by Puff-pastry-star** [comment]
服务器环境：
python 3.11.0
nonebot-plugin-alconna     0.53.1
nonebot_plugin_minesweeper 0.4.1
nonebot_plugin_session     0.3.2
nonebot-plugin-waiter      0.8.0
nonebot2                   2.4.0

**Comment by Puff-pastry-star** [comment]
实现端Lagrange.OneBot 0.0.3+94b639008036aa21de1c9de0e18b1fdf48272702

**Comment by Puff-pastry-star** [comment]
没有装其他的bot

**Comment by HibiKier** [comment]
![图片](https://github.com/user-attachments/assets/cf30d6b1-f695-4007-9f8f-4bf68611ae81)
.env.dev这个打开执行命令 在截图

**Comment by HibiKier** [comment]
进 真寻技术群

**Comment by Puff-pastry-star** [comment]
建议LOG出极简（仅保留必要日志），正常，DEBUG

**Comment by Puff-pastry-star** [comment]
已申请加群
