### ISSUE TITLE
向机器人发送消息没有回应

### ISSUE THREAD

**Issue by amethystia** [HibiKier/zhenxun_bot#1725]
### 错误截图

[img]

### 日志截图
![image](https://github.com/user-attachments/assets/386aef6f-d633-4387-b176-610bc583448f)
![image](https://github.com/user-attachments/assets/1c0bff01-1a34-4004-91f3-386c19a20018)
[img]

### 错误说明
反向代理已经配置好了。
发送消息没有反应。

**Comment by HibiKier** [comment]
poetry install有没有报错
