### ISSUE TITLE
查看好感度异常

### ISSUE THREAD

**Issue by zhengjiaocc** [HibiKier/zhenxun_bot#1726]
####  真寻报
[
![Snipaste_2024-11-16_02-58-37](https://github.com/user-attachments/assets/a003556f-6d11-4107-a30e-ad3a269c704a)
](url)

####  NapCat报
![image](https://github.com/user-attachments/assets/69ff9eec-c323-463b-a343-c51ac8a00359)

### 2. 群聊发送“好感度总排行” ，等待几秒后Bot被killed
![image](https://github.com/user-attachments/assets/c5a508bc-2ffe-4901-a0b1-65849914e932)

**Comment by BalconyJH** [comment]
请尝试更新真寻至0.2.4fix2看看能不能复现，复现的话请使用pip list命令获取并提供环境内包版本清单和提供服务器配置

**Comment by HibiKier** [comment]
更新到fix3

**Comment by zhengjiaocc** [comment]
正常了，谢谢
