### ISSUE TITLE
点歌等插件没反应

### ISSUE THREAD

**Issue by akua0z** [HibiKier/zhenxun_bot#1729]
### 操作系统

Windows

### Python 版本

3.10

### zhenxun_bot 版本

 v0.2.4-fix2

### 适配器

one bot v11 2.2.2

### 协议端

Llonebot v4.3

### 描述问题

点歌插件、关于插件都没反应（可能也有其他个别插件没反应）。看后台是被识别为普通对话，而不是插件命令，也没有报错信息，求解

### 复现步骤

.

### 截图或日志（请勿包含敏感信息如密码、令牌等）

![09c22b1e406da600f37e03166788bcaf](https://github.com/user-attachments/assets/3661c834-7b5c-45b8-a94d-e467e9fe9fd1)
![f3684deace762eaa9ef977e9a96e2c15](https://github.com/user-attachments/assets/c5ba9b83-bb0a-444b-ad2e-f6cc64728737)

**Comment by HibiKier** [comment]
点歌 爱你，要加空格

**Comment by akua0z** [comment]
> 点歌 爱你，要加空格

试了加空格，不过群里的真寻还是没有响应

![Image_2067042875967519.png](https://github.com/user-attachments/assets/f81daa88-4b1a-4992-8bd7-b8dde4b0a9e5)
