### ISSUE TITLE
Check_api_time配置项无效

### ISSUE THREAD

**Issue by cannedH** [HibiKier/zhenxun_bot#1734]
### 描述问题或主题

**系统版本：Windows11
Bot版本：v0.2.4-fix2
数据库：sqlite**
默认30s有点频繁了，个人倾向于1h以上。
同时在修改config.yaml、sql语句：exec update github_sub set update_time=21600后仍然为30s的间隔检测更新。
![屏幕截图 2024-11-18 222913](https://github.com/user-attachments/assets/fd0cec77-ca07-474e-9b3d-33386b3ced57)
![屏幕截图 2024-11-18 222435](https://github.com/user-attachments/assets/5ae8f0f4-7706-4b67-b4ab-ab31ca7b7489)
![屏幕截图 2024-11-18 223021](https://github.com/user-attachments/assets/3f0aae3c-4a1b-4db0-9325-c06f18d904cf)
![屏幕截图 2024-11-18 223125](https://github.com/user-attachments/assets/d3c5b90f-e2c1-426d-be04-35e13146c929)

### 需做出的修改

延长github订阅api默认间隔时间，修复配置文件无效修改。

**Comment by BalconyJH** [comment]
请前往 [github_sub](https://github.com/xuanerwa/zhenxun_github_sub) 插件提交 issue
