### ISSUE TITLE
Bug: 真寻不说话/WEBUI账号配置异常

### ISSUE THREAD

**Issue by Cintser** [HibiKier/zhenxun_bot#1739]
### 操作系统

Windows

### Python 版本

Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32

### zhenxun_bot 版本

zhenxun_bot-0.2.4-fix3

### 适配器

nonebot2==2.3.3（是这个嘛）

### 协议端

Lagrange.Core

### 描述问题

不知道是不是我的操作出了什么问题，发生了3件奇怪的事
1.按照流程部署完之后真寻不发消息，LLOneBot和Lagrange.Core都试过了
![image](https://github.com/user-attachments/assets/452f2acf-1ab9-4000-89a8-2689cb1b25d5)

2.真寻的窗口放在后台一会后再放到前台看发现没反应了，按一下enter之前群友的对话会突然蹦出来，然后再最后面加上一大串，不知道会不会影响真寻稳定性
![image](https://github.com/user-attachments/assets/0678f9c2-a353-4586-b2df-d059152d1343)
3.我在配置webui的密码之后无法运行bot，报错直指这个文件
![image](https://github.com/user-attachments/assets/4c93836c-9fb7-4152-a456-c1aa3ccb9e12)

### 复现步骤

a

### 截图或日志（请勿包含敏感信息如密码、令牌等）

[2024-11-24.log](https://github.com/user-attachments/files/17891761/2024-11-24.log)
[error_2024-11-24.log](https://github.com/user-attachments/files/17891763/error_2024-11-24.log)

**Comment by HibiKier** [comment]
第一个
1.帮助插件是否正确加载
2.是否自己加了命令前缀

**Comment by HibiKier** [comment]
第一个
1.确认是否配置超级用户
2.打开env.dev中的debug模式查看日志
