### ISSUE TITLE
Feature: 功能描述词库可以批量增加

### ISSUE THREAD

**Issue by foxdad** [HibiKier/zhenxun_bot#1762]
### 希望能解决的问题

现在只能通过机器人手动添加词条，不能默认根据某种格式添加，比如代码文件里面有一个anime.json文件的格式，这种可以直接默认初始化

### 描述所需要的功能

根据定义的格式默认初始化词条

**Comment by HibiKier** [comment]
![图片](https://github.com/user-attachments/assets/cb1b2262-35b1-4974-9a5d-da90971ec44e)
新版本词条已支持
