### ISSUE TITLE
Bug: 商店限购问题

### ISSUE THREAD

**Issue by ATTomatoo** [HibiKier/zhenxun_bot#1794]
### 操作系统

Linux

### Python 版本

3.10.10

### zhenxun_bot 版本

 v0.2.4-4291cda

### 适配器

nonebot v11 2.3.3

### 协议端

NapCat 4.1.5

### 描述问题

在商店中，将物品1设置为限购1次，再将物品2也限购1次，用户买了物品1之后，无法购买物品2，会提示“今天的购买已达限制了喔!”
限购次数不是单个商品了，而是全局

### 复现步骤

将物品1设置限购为1次
将物品2设置限购为1次
购买物品1，然后购买物品2

**Comment by HibiKier** [comment]
bugfix/shop-daily-limit 该分支已修复
