### ISSUE TITLE
功能调用统计字体问题

### ISSUE THREAD

**Issue by Adsicmes** [HibiKier/zhenxun_bot#18]
如图

![-2744425cb8b864c7.png.jpg](https://user-images.githubusercontent.com/79645438/127776165-b109888c-fa94-43b1-a3df-ac64c602fdb6.jpg)

**Comment by HibiKier** [comment]
你linux系统没中文字体，查看 https://github.com/HibiKier/nonebot_plugin_statistical 注的 第一个
