### ISSUE TITLE
有个文件命名 requirements.txt

### ISSUE THREAD

**Issue by Cheng-ge1** [HibiKier/zhenxun_bot#182]
有大哥下这文件了吗，能不能发一下

**Comment by lyk19990329** [comment]
多次运行，缺啥装啥（×

**Comment by King1778** [comment]
我刚知道，作者就跑了？？？

**Comment by foxwhite25** [comment]
[requirements.txt在这里](https://github.com/Ice-Cirno/HoshinoBot/blob/master/requirements.txt)
