### ISSUE TITLE
[DOCUMENTATION] Quickstart With Bot Building

### ISSUE THREAD

**Issue by lhhxxxxx** [HibiKier/zhenxun_bot#191]
## Quick setup guide

**Note:** For support please join our [Discord](https://www.bilibili.com/video/BV1GJ411x7h7).

### Requirements

* Python 3.8 ([link](https://www.bilibili.com/video/BV1GJ411x7h7))

* requirements.txt ([link](https://www.bilibili.com/video/BV1GJ411x7h7))

### Running

**Note:** If you updated from an older version, delete `config.json` to regenerate it.

1. Get `run.py`
   - Download from [link](https://www.bilibili.com/video/BV1GJ411x7h7)
2. Run Bot with the following commands. **Make sure shutdown service is running as well.**

##### Windows

```shell
git clone https://github.com/keroserene/rickrollrc.git
cd rickrollrc
.\README.md
```

##### Linux

```bash
git clone https://github.com/keroserene/rickrollrc.git
cd rickrollrc
vim README.md
```

**Comment by MingxuanGame** [comment]
Title shuold be:
[DOCUMENTATION] Help us about i18n

**Comment by Nova-Noir** [comment]
This documentation is so powerful! I have built over 114514 bots in just a few seconds!
I wish this issue could be pinned.

**Comment by zhanbao2000** [comment]
Thank you! I have successfully built my bot and found 1919810 pictures. 😋

**Comment by Forever331** [comment]
やりますね👍

**Comment by Ailitonia** [comment]
Great! This is the easiest and most understandable deployment guide I've ever seen😍

**Comment by Liunkwww** [comment]
Good issues, love form china. LOL

**Comment by corvo007** [comment]
好议题 爱来自中国 英雄联盟
