### ISSUE TITLE
安装数据库的postgresql时错误，怎么办

### ISSUE THREAD

**Issue by adsk113** [HibiKier/zhenxun_bot#193]

**Comment by lhhxxxxx** [comment]
Visit #191 for help plz.

**Comment by Liunkwww** [comment]
[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)
报错捏，另外建议看完 #190

**Comment by adsk113** [comment]
知道了

**Comment by zhanbao2000** [comment]
Read [别像弱智一样提问](https://github.com/dogfight360/Stop-Ask-Questions-The-Stupid-Ways) and [提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way) first, then post your logs or previous steps.
