### ISSUE TITLE
py包导入错误

### ISSUE THREAD

**Issue by Noob-in-computers** [HibiKier/zhenxun_bot#195]
报错内容：
`ujson module not found, using json
Traceback (most recent call last):
  File "D:\QQBOT研究中\zhenxun_bot-main\bot.py", line 2, in <module>
    from nonebot.adapters.onebot.v11 import Adapter
ModuleNotFoundError: No module named 'nonebot.adapters'`
操作环境：Win10，Python3.8

基本按照教程走，但是不知道为什么报错了
有没有大佬能救一下，谢谢各位了……

**Comment by lgc2333** [comment]
请问你安装onebot适配器没有

**Comment by Nova-Noir** [comment]
阅读[如何安装驱动器](https://v2.nonebot.dev/docs/start/install-driver)章节。

**Comment by Nova-Noir** [comment]
阅读[如何安装驱动器](https://v2.nonebot.dev/docs/start/install-driver)章节。

**Comment by zhanbao2000** [comment]
尝试手动安装一下 `nonebot` 及其适配器

```cmd
pip install nonebot2
pip install nonebot-adapter-cqhttp
```

另外请先阅读 [如何安装驱动器](https://v2.nonebot.dev/docs/start/install-driver)

**Comment by Noob-in-computers** [comment]
> `nonebot`试安装一下
> 
> ```batchfile
> 点安装 nonebot2
> pip install nonebot-adapter-cqhttp
> ```
> 
> 另外请先阅读[如何安装驱动器](https://v2.nonebot.dev/docs/start/install-driver)

谢谢您的指导，谢谢

**Comment by Noob-in-computers** [comment]
> 阅读[如何安装驱动器](https://v2.nonebot.dev/docs/start/install-driver)章节。

谢谢您的指导，我先读一下……

**Comment by Noob-in-computers** [comment]
> 请问你安装onebot适配器没有

啊……抱歉，我应该是忘了，谢谢您的提醒……
