### ISSUE TITLE
群聊图片问题

### ISSUE THREAD

**Issue by 1sthentai** [HibiKier/zhenxun_bot#197]
部署完成后，私聊功能正常，看log群聊可以识别p站排行榜等功能但并不调用函数处理，请问有方法解决吗
![QQ截图20220517225439](https://user-images.githubusercontent.com/37441846/168842858-450a0a54-b145-43b6-ba59-14e0924286df.png)
群聊
![QQ截图20220517225616](https://user-images.githubusercontent.com/37441846/168842915-92aa48ad-5556-4cf7-9a97-80a849b2a2a9.png)
私聊

**Comment by ShuangChenyue** [comment]
请问是为什么?我也出现了这种情况

**Comment by 1sthentai** [comment]
> 

一个是这个功能需要@（我蠢了），还有一个是ai插件的优先级比pixiv插件优先级高，群聊里要使用的话需要手动修改
