### ISSUE TITLE
schedule时区问题

### ISSUE THREAD

**Issue by Raysamatoken** [HibiKier/zhenxun_bot#2]
系统时区在Asia/Shanghai下报错
![QQ截图20210623083812](https://user-images.githubusercontent.com/26264287/123016998-5ff55680-d3fe-11eb-8d6d-6229438b59ac.png)

**Comment by HibiKier** [comment]
请查看issues https://github.com/nonebot/nonebot2/issues/78

**Comment by Raysamatoken** [comment]
> 请查看issues [nonebot/nonebot2#78](https://github.com/nonebot/nonebot2/issues/78)

这在Ubuntu 20.04 LTS 下就很迷，用了好几种改时区的方式都不行，我先装其它系统试试

**Comment by HibiKier** [comment]
> 
> 
> > 请查看issues [nonebot/nonebot2#78](https://github.com/nonebot/nonebot2/issues/78)
> 
> 这在Ubuntu 20.04 LTS 下就很迷，用了好几种改时区的方式都不行，我先装其它系统试试

ok

**Comment by Raysamatoken** [comment]
> > > 请查看issues [nonebot/nonebot2#78](https://github.com/nonebot/nonebot2/issues/78)
> > 
> > 
> > 这在Ubuntu 20.04 LTS 下就很迷，用了好几种改时区的方式都不行，我先装其它系统试试
> 
> ok

更换arch Linux后无问题了，arch邪教大法好（滑稽）

**Comment by HibiKier** [comment]
> 
> 
> > > > 请查看issues [nonebot/nonebot2#78](https://github.com/nonebot/nonebot2/issues/78)
> > > 
> > > 
> > > 这在Ubuntu 20.04 LTS 下就很迷，用了好几种改时区的方式都不行，我先装其它系统试试
> > 
> > 
> > ok
> 
> 更换arch Linux后无问题了，arch邪教大法好（滑稽）

这个我之前上传的有一点点小问题（上次传坏了），我迟点更新的上去
