### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by XXiaoJie22** [HibiKier/zhenxun_bot#200]
![1](https://user-images.githubusercontent.com/100270031/168842976-5c6fa26c-3662-4236-8807-9ffcb1071f2a.jpg)
##### 启动bot的时候，为啥没有这个模块...

**Comment by Liunkwww** [comment]
你依赖呢，装齐全了再启动

**Comment by HibiKier** [comment]
看文档安装

**Comment by XXiaoJie22** [comment]
谢谢，我用python3.10，安装依赖的时候没安装那些包，换成3.9就可以了
