### ISSUE TITLE
register服务器名称该如何命名？

### ISSUE THREAD

**Issue by afafafaf51511** [HibiKier/zhenxun_bot#202]
是有什么命名的规则吗？
这里随便输了几个字母命名，显示必须指定主机名、地址和服务。
这个问题可能很白痴，希望各位大佬不要介意。

**Comment by HibiKier** [comment]
register服务器是什么

**Comment by afafafaf51511** [comment]
> register服务器是什么

当我打开pgadmin之后，界面有一个添加服务器，添加之后不知道该怎么命名

**Comment by HibiKier** [comment]
随便写

**Comment by HibiKier** [comment]
随便写应为
