### ISSUE TITLE
这个如何解决，前面解决了nonebot，后面又出现了gino

### ISSUE THREAD

**Issue by dingzhenbaohujiaran** [HibiKier/zhenxun_bot#204]
![picture](https://user-images.githubusercontent.com/105736187/168853716-71cdb7e5-c373-4d1a-8b3f-1b838df4e82e.png)
![picture](https://user-images.githubusercontent.com/105736187/168853789-2fe9ce79-d549-4ddc-8ccb-fbce73dc34b7.png)

**Comment by ALNthy** [comment]
pip install gion

**Comment by Nova-Noir** [comment]
部署教程中写到
```sh
pip install poetry
# pip3 install poetry 
poetry install
```

**Comment by jk6589jk** [comment]
我也是遇到这个问题，搞了半天...
poetry install 已经安装完了
poetry没自动安装的包：NoneBot2、gion、ruamel.yaml
特别是NoneBot2...提示缺NoneBot，很容易想当然pip去安装NoneBot...然后就gg了



> 部署教程中写到
> 
> ```shell
> pip install poetry
> # pip3 install poetry 
> poetry install
> ```

**Comment by HibiKier** [comment]
请确保py版本在3.8或3.9，不然poetry install会出错
