### ISSUE TITLE
线程’MainThread’中没有当前事件循环

### ISSUE THREAD

**Issue by dongdong1011** [HibiKier/zhenxun_bot#206]
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\dzy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-eALgSHsI-py3.9\lib\site-packages\bilibili_api\utils\network.py", line 26, in __clean
    loop = asyncio.get_event_loop()
  File "c:\users\dzy\appdata\local\programs\python\python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

![1](https://user-images.githubusercontent.com/86366620/168866228-428ca049-e8b0-4edb-94a3-68d84aea7cd1.png)
![2](https://user-images.githubusercontent.com/86366620/168866868-6ae22d2a-323c-4aff-9ddd-eedb917b6f59.png)

**Comment by dongdong1011** [comment]
E:\BOT\zhenxun_bot-main>python bot.py
05-18 08:51:43 [SUCCESS] nonebot | NoneBot is initializing...
05-18 08:51:43 [INFO] nonebot | Current Env: dev
05-18 08:51:43 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "update_group_member_info"
C:\Users\dzy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-eALgSHsI-py3.9\lib\site-packages\apscheduler\util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "timing_task"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "custom_welcome_message"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "rule"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "switch_rule"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "admin_config"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "admin_bot_manage"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "init_plugin_config"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "scripts"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "admin_help"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "invite_manager"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "chat_message_handle"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "chat_message"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "chat_history"
05-18 08:51:45 [SUCCESS] nonebot | Succeeded to import "apscheduler"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "ban"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "help"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "super_help"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "nickname"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "update_info"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "broadcast"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "super_task_switch"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "clear_data"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "exec_sql"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "set_admin_permissions"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "reload_setting"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "update_friend_group_info"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "manager_group"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "bot_friend_group"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "super_cmd"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "hooks"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "reset_today_gold"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "use"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "shop_handle"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "shop_handle"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "buy"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "use"
05-18 08:51:46 [SUCCESS] nonebot | Succeeded to import "my_props"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "gold"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "shop"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "group_handle"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "russian"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "black_word"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "pid_search"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "message_handle"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "model"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "word_hanlde"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "word_bank"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "ai"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "check"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "yiqing"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "poke"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "dialogue"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "music"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "web_ui"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "search_buff_skin_price"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "statistics_hook"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "statistics_handle"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "statistics"
05-18 08:51:47 [SUCCESS] nonebot | Succeeded to import "update_picture"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "upload_image"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "send_image"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "move_image"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "delete_image"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "image_management"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "translate"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "weather"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "poetry"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "comments_163"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "cover"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "jitang"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "wbtop"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "alapi"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "nbnhhsh"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "one_friend"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "withdraw"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "about"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "mute"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "send_setu"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "update_setu"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "send_setu_"
05-18 08:51:48 [SUCCESS] nonebot | Succeeded to import "send_dinggong_voice"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "draw_card"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "fudu"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "group_welcome_msg"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "quotations"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "update_gocqhttp"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "gold_redbag"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "luxun"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "roll"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "almanac"
05-18 08:51:49 [SUCCESS] nonebot | Succeeded to import "query_resource_points"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "material_remind"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "query_role"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "query_memo"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "resin_remind"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "bind"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "query_memo"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "genshin_sign"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "reset_today_query_user_data"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "query_user"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "genshin"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "parse_bilibili_json"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "what_anime"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "pixiv_rank_search"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "epic"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "my_info"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "white2black_image"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "search_anime"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "bt"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "fake_msg"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "search_image"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "aconfig"
05-18 08:51:50 [SUCCESS] nonebot | Succeeded to import "pix"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "pix_pass_del_keyword"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "pix_show_info"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "pix_update"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "pix_add_keyword"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "pix_gallery"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "bilibili_sub"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "sign_in"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "coser"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "check_zhenxun_update"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "open_cases"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "other_hook"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "task_hook"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "ban_hook"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "auth_hook"
05-18 08:51:51 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
05-18 08:51:51 [SUCCESS] nonebot | Running NoneBot...
05-18 08:51:51 [INFO] uvicorn | Started server process [6884]
05-18 08:51:51 [INFO] uvicorn | Waiting for application startup.
05-18 08:51:52 [INFO] services | Database loaded successfully!
C:\Users\dzy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-eALgSHsI-py3.9\lib\site-packages\apscheduler\triggers\cron\__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
C:\Users\dzy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-eALgSHsI-py3.9\lib\site-packages\apscheduler\triggers\cron\__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
C:\Users\dzy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-eALgSHsI-py3.9\lib\site-packages\apscheduler\triggers\interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)
05-18 08:51:52 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-18 08:51:52 [INFO] basic_plugins | 已成功加载 59 个非限制插件.
05-18 08:51:52 [INFO] utils | 已成功加载 5 个Cd限制.
05-18 08:51:52 [INFO] utils | 已成功加载 12 个Block限制.
05-18 08:51:52 [INFO] utils | 已成功加载 1 个Count限制.
05-18 08:51:59 [INFO] basic_plugins | 初始化数据完成...
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/4b1a29183d0ac1a267ba4a8a64db5f6b_5091052195206844315.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\296.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/abf57f467b7c9404b3e47f00fcf3813c_157108456459849289.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\301.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/4b1a29183d0ac1a267ba4a8a64db5f6b_5091052195206844315.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/abf57f467b7c9404b3e47f00fcf3813c_157108456459849289.png
05-18 08:52:00 [ERROR] plugins | 获取原神资源数据未知错误 <class 'FileNotFoundError'>：[Errno 2] No such file or directory: 'E:\\BOT\\zhenxun_bot-main\\resources\\image\\genshin\\genshin_icon\\resources\\image\\genshin\\genshin_icon\\296.png'
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/5ac615d92c774a0befb61c5df58949b2_5106362145059134740.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\289.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/7ebe43d06a70e3d6240fd03d08e44661_8823606768185129608.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\283.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/5ac615d92c774a0befb61c5df58949b2_5106362145059134740.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/59da9abce6afd01f089a3efca6db9544_7038973255776382150.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\280.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/7ebe43d06a70e3d6240fd03d08e44661_8823606768185129608.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/59da9abce6afd01f089a3efca6db9544_7038973255776382150.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/d6279980121d76f31054e1025940cb54_177887402954595404.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\287.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/d6279980121d76f31054e1025940cb54_177887402954595404.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/fdaef46f7d7bda53a75552cd91e84add_8889556744159090795.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\295.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/dc91128cbe42afd2beb80b9d875fdc0d_3704974644510104752.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\282.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/dd7a0fd142d9cfdf909a37848a543866_5593844105387921823.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\304.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/fdaef46f7d7bda53a75552cd91e84add_8889556744159090795.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/dc91128cbe42afd2beb80b9d875fdc0d_3704974644510104752.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/dd7a0fd142d9cfdf909a37848a543866_5593844105387921823.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/32add73120bf53b4afe17e5a130497ee_7731060857774575975.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\300.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/8269127f7b4cc78702a3917ef5c41012_3267338587770624131.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\278.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/32add73120bf53b4afe17e5a130497ee_7731060857774575975.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/8269127f7b4cc78702a3917ef5c41012_3267338587770624131.png
05-18 08:52:00 [INFO] plugins | 更新原神资源类型成功...
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/9365968ae710394131f2ba33ae9103cd_6357176062164449470.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\292.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/9365968ae710394131f2ba33ae9103cd_6357176062164449470.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/c3674a442c4d636ac5321e0e6714544a_5422145187642381198.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\297.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/c3674a442c4d636ac5321e0e6714544a_5422145187642381198.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/2cd26ac121b7b3a6ed853da079eb2da3_6211420679554943149.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\307.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/2cd26ac121b7b3a6ed853da079eb2da3_6211420679554943149.png
05-18 08:52:00 [INFO] uvicorn | Application startup complete.
05-18 08:52:00 [ERROR] uvicorn | [Errno 10013] error while attempting to bind on address ('127.0.0.1', 5432): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
05-18 08:52:00 [INFO] uvicorn | Waiting for application shutdown.
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/01/08/75276545/b71fabe5cae6c8e8e1412121b4c28c89_1413246670718980593.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\164.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/01/08/75276545/b71fabe5cae6c8e8e1412121b4c28c89_1413246670718980593.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/21d90b3dd945a4c06f94d7dbdefbf837_4029802170462104137.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\313.png
05-18 08:52:00 [INFO] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/e1398605035948ed8b39873dd5524f64_3940714216224951423.png 成功.. Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\312.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/21d90b3dd945a4c06f94d7dbdefbf837_4029802170462104137.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/e1398605035948ed8b39873dd5524f64_3940714216224951423.png
05-18 08:52:00 [INFO] uvicorn | Application shutdown complete.
05-18 08:52:00 [ERROR] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/ce123e8787b37d7905616190da192a97_6800133382960324945.png 未知错误 <class 'RuntimeError'>：The connection pool was closed while 1 HTTP requests/responses were still in-flight... Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\310.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/22/75379475/ce123e8787b37d7905616190da192a97_6800133382960324945.png 失败，等待下次更新...
05-18 08:52:00 [ERROR] utils | 下载 https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/ce7dea7a7d6327dba864d87bc286e02d_6899452121064095360.png 未知错误 <class 'RuntimeError'>：The connection pool was closed while 1 HTTP requests/responses were still in-flight... Path：E:\BOT\zhenxun_bot-main\resources\image\genshin\genshin_icon\277.png
05-18 08:52:00 [INFO] plugins | 下载原神资源图标：https://uploadstatic.mihoyo.com/ys-obc/2021/10/21/75379475/ce7dea7a7d6327dba864d87bc286e02d_6899452121064095360.png 失败，等待下次更新...
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\dzy\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-eALgSHsI-py3.9\lib\site-packages\bilibili_api\utils\network.py", line 26, in __clean
    loop = asyncio.get_event_loop()
  File "c:\users\dzy\appdata\local\programs\python\python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by HibiKier** [comment]
端口不要改成5432，和数据库冲突的
