### ISSUE TITLE
请问nonebot哪个版本才是适配的

### ISSUE THREAD

**Issue by lightbearer1** [HibiKier/zhenxun_bot#207]
运行bot.py的时候报错：
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\bot.py", line 2, in <module>
    from nonebot.adapters.onebot.v11 import Adapter
ModuleNotFoundError: No module named 'nonebot.adapters.onebot'
根据百度结果初步认为是nonebot版本问题导致的，原谅我确实没有找到requirements.txt文件不知道该用哪个版本......
又或者说是别的什么导致了这个问题？

另外说两句题外话：
慕名而来，对着文档操作半天回来发现作者run了，很遗憾没有早些发现这么优秀的作品，突然火了既是幸运也是不幸，非常能理解作者的苦楚，互联网三巨头之一的威胁谁都不能忽视。虽然我到现在还没项目跑起来...但还是很感谢作者们的分享，折腾本身就是一种趣味。千言万语，最后只能说：f**k you,t**t。

**Comment by HibiKier** [comment]
requirements.txt已经没用了，文档里只是还没删提示，具体教程命令中根本用不到requirements.txt
