### ISSUE TITLE
启动后自动关闭

### ISSUE THREAD

**Issue by Saukurs** [HibiKier/zhenxun_bot#208]
日志中显示是数据库认证失败？
![无标题](https://user-images.githubusercontent.com/105751058/168905115-c4ba9f60-55b7-4d28-ade1-d111d61bea78.png)

**Comment by Nova-Noir** [comment]
数据库认证错误。

请检查数据库地址、用户名、密码端口等信息

**Comment by Saukurs** [comment]
> 数据库认证错误。
> 
> 请检查数据库地址、用户名、密码端口等信息

用的是默认配置，数据库信息我都一一对应没有填写错误

**Comment by Nova-Noir** [comment]
> > 数据库认证错误。
> > 请检查数据库地址、用户名、密码端口等信息
> 
> 用的是默认配置，数据库信息我都一一对应没有填写错误

如果是默认配置的话，根据教程
```sh
       #  用户名↓                # 密码↓
 CREATE USER uname WITH PASSWORD 'zhenxun';      # 创建用户
         # 数据库名称↓       所有者↓
 CREATE DATABASE testdb OWNER uname;
```
用户名应该是`uname`，图上显示用户名是`'zhenxun'`，请检查`configs/config.py`里的数据库连接配置。

**Comment by Nova-Noir** [comment]
也可以附带上数据库信息和`configs/config.py`文件的内容方便诊断问题

**Comment by Saukurs** [comment]
> 问题的内容也可以轻松上数据库信息和`configs/config.py`文件

![1](https://user-images.githubusercontent.com/105751058/168936045-dfdd2726-1ba0-466d-84f7-3b837c0905cc.png)
![2](https://user-images.githubusercontent.com/105751058/168936050-755dbfbf-ce55-420e-ac60-c2f9bc6a919d.png)
刚刚是使用的zhenxun这个账户，现在改回uname也显示连接失败

**Comment by Nova-Noir** [comment]
怀疑还是数据库验证的问题
你可以尝试重新创建一个数据库用户与数据库并给予权限
参考#193

**Comment by Saukurs** [comment]
> 怀疑还是数据库验证的问题 你可以尝试重新创建一个数据库用户与数据库并给予权限 参考#194

是否对应数据库用户需要为超级用户？还是拥有对应数据库权限即可？

**Comment by HibiKier** [comment]
这个用户的数据库密码错了

**Comment by Saukurs** [comment]
> 这个用户的数据库密码错了

已经尝试多个用户，并且使用和配置正确的- 密码，仍然提示此错误

**Comment by MousenIvan** [comment]
我用pg10也是验证失败，换成pg14就好了

**Comment by Saukurs** [comment]
> 我用pg10也是验证失败，换成pg14就好了

感谢，已成功连接数据库，确实换了pg14就好了不知道为啥(悲

**Comment by MingxuanGame** [comment]
如果您已经解决了问题

恳请点击一下这个按钮将此 issue 关闭

![image](https://user-images.githubusercontent.com/68982190/169042615-c6b1148f-5cb7-4af1-a27a-66d75d6220ef.png)
