### ISSUE TITLE
QQ登录不成功

### ISSUE THREAD

**Issue by XiaoLi-sach** [HibiKier/zhenxun_bot#212]
我在config.yml 中配置了账号密码， 但还是提示需要扫码登录， 扫码后提示不安全， 怎么处理

![image](https://user-images.githubusercontent.com/55753927/168949894-172a0630-82bf-4dac-b4ff-ee6066372970.png)

**Comment by HibiKier** [comment]
本地登录后将token文件传至服务器

**Comment by Saukurs** [comment]
使用4G网络登录，出界面就快速点击登录可以避免使用token文件

**Comment by AlanMULI** [comment]
token文件具体如何操作呢orz

**Comment by XiaoLi-sach** [comment]
好的， 已成功登录

**Comment by XD-TW** [comment]
> 好的， 已成功登录

你是怎么操作的。

**Comment by LaffeyLa** [comment]
> 

请问是怎么解决的啊，我也是同样的问题

**Comment by Exgungnir** [comment]
会先有正常的登录界面，然后再弹出这个存在风险界面的，只不过弹出的比较快。手速够快的话可以点到登录键。

**Comment by XiaoLi-sach** [comment]
> 

本地登陆后， 目录会有个token文件， 放进服务器里 再启动就好了

**Comment by LaffeyLa** [comment]
> > 
> 
> 本地登陆后， 目录会有个token文件， 放进服务器里 再启动就好了

没有太理解，找了半天也没找到token文件在哪里？百度也没找到

**Comment by gongjing666** [comment]
自己本地搭建一个登录？
