### ISSUE TITLE
go-cqhttp报错：配置文件不合法

### ISSUE THREAD

**Issue by Qian033** [HibiKier/zhenxun_bot#213]
![6)74L%6)PN`B3X{9 BM Q3X](https://user-images.githubusercontent.com/96489171/168950914-7d3bdc54-dd30-4d44-86cc-fc1445133479.png)

![7`F1`G1HS2NX(53~F09BQP2](https://user-images.githubusercontent.com/96489171/168950930-bfc58e49-a35f-41ba-a973-ae89da13db09.png)

只改了config.yml文件的QQ号和WS地址如图P2，显示报错如P1...
是搭建在华为云服务器上的，有dalao有什么头绪吗...小白真的傻了...orz

**Comment by HibiKier** [comment]
注意缩进

**Comment by Qian033** [comment]
> 

您好！可以细讲一下那行的缩进有问题吗！我是直接更改的默认的配置文件啊呜呜orz

**Comment by CMHopeSunshine** [comment]
你的universal那一行明显缩进不对

**Comment by Qian033** [comment]
> 你的universal那一行明显缩进不对

！！！看到了！谢谢您！！！
