### ISSUE TITLE
机器人工作问题

### ISSUE THREAD

**Issue by FedoraTLR** [HibiKier/zhenxun_bot#214]
更改了群聊权限为9，除了超级用户的指令机器人会回复，其他人的指令不回复了，刚部署好的时候还是正常的

**Comment by HibiKier** [comment]
发日志

**Comment by FedoraTLR** [comment]
05-18 12:12:45 [INFO] nonebot | Matcher <Matcher from plugins.sign_in, type=message, priority=5, temp=False> running is cancelled
签到
05-18 12:12:45 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False>
05-18 12:12:45 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.invite_manager, type=message, priority=9, temp=False>
05-18 12:12:45 [INFO] nonebot | Event will be handled by <Matcher from plugins.fudu, type=message, priority=9, temp=False>
05-18 12:12:45 [INFO] nonebot | Matcher <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False> running is cancelled
05-18 12:12:45 [INFO] nonebot | Matcher <Matcher from basic_plugins.invite_manager, type=message, priority=9, temp=False> running is cancelled
05-18 12:12:45 [INFO] nonebot | Matcher <Matcher from plugins.fudu, type=message, priority=9, temp=False> running is cancelled
