### ISSUE TITLE
请教下大佬from .utils import ConfigsManager 报错怎么办啊QAQ

### ISSUE THREAD

**Issue by jiuxiangshaonian** [HibiKier/zhenxun_bot#216]
![R(V3QR~PZ@QQ@XEWMP@LW)X](https://user-images.githubusercontent.com/105766545/168954637-46dd7040-2b0b-4149-9f3c-9ab3f2d6e0f9.png)

**Comment by MingxuanGame** [comment]
运行 bot.py 而不是其他的 py 文件

**Comment by jiuxiangshaonian** [comment]
> 

大佬，不是说要启动一次config.py才会生成congfig.yaml插件配置文件吗

**Comment by jiuxiangshaonian** [comment]
> 运行 bot.py 而不是其他的 py 文件
大佬，不是说要启动一次config.py才会生成congfig.yaml插件配置文件吗

**Comment by jiuxiangshaonian** [comment]
> 运行 bot.py 而不是其他的 py 文件

大佬，不是说要启动一次config.py才会生成congfig.yaml插件配置文件吗

**Comment by MingxuanGame** [comment]
> 使用python3 bot.py启动真寻Bot，会在 configs 和 data/configs 目录下生成各种配置文件
 ——文档
