### ISSUE TITLE
关于Saucenao 缺失API_KEY问题

### ISSUE THREAD

**Issue by eachbol2333** [HibiKier/zhenxun_bot#220]
如题，填写Saucenaoapi后再次运行出现了这个，大佬能不能解决一下
![B8DDQ4GQJOU9(@YV$ $1K%S](https://user-images.githubusercontent.com/105063888/168964409-feff388c-7c8d-410a-91d8-e4a6e778debc.png)

**Comment by chara1051** [comment]
自己找配置文件，把API填上去，没有的话，先去网站注册，网站地址配置文件里有

**Comment by eachbol2333** [comment]
> 

![image](https://user-images.githubusercontent.com/105063888/168964767-64f872f3-ac4d-4020-8408-ee6821cfe58c.png)
我就是在这里面找填写到config.yaml里面的，难道还有改什么配置文件吗

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/168965432-27aeac80-e77f-4446-b710-424e1b679294.png)

**Comment by eachbol2333** [comment]
> 

谢谢大佬，成了！
