### ISSUE TITLE
启动问题，这一步是为什么？？

### ISSUE THREAD

**Issue by yoke0104x** [HibiKier/zhenxun_bot#221]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/44898730/168966625-9f6624f1-3978-4872-93a0-d49f9138f25d.png">

**Comment by MingxuanGame** [comment]
你 go-cqhttp 的地址配置错了

**Comment by yoke0104x** [comment]
@MingxuanGame 大佬 我用的docker 部署的 go-cqhttp 这个在哪里配置呢？？？

**Comment by h265642327** [comment]
https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_gocq.html这里有讲到

**Comment by h265642327** [comment]
1. 这里我补充一下，我go-cqhttp已经更改了config.yml，但是仍然出现错误
![Uploading 屏幕截图 2022-05-18 143946.jpg…]()

**Comment by h265642327** [comment]
这里我补充一下，我go-cqhttp已经更改了config.yml，但是仍然出现错误
![屏幕截图 2022-05-18 143946](https://user-images.githubusercontent.com/94788823/168974049-f439142f-f4c3-444b-9db4-5013c5afeccc.jpg)

**Comment by h265642327** [comment]
错误指出现的三个warning
05-18 14:29:20 [WARNING] plugins | azur_up_char 解析出错
05-18 14:29:20 [WARNING] plugins | pretty_up_char 解析出错
05-18 14:29:20 [WARNING] plugins | prts_up_char 解析出错

**Comment by HibiKier** [comment]
> 这里我补充一下，我go-cqhttp已经更改了config.yml，但是仍然出现错误 ![屏幕截图 2022-05-18 143946](https://user-images.githubusercontent.com/94788823/168974049-f439142f-f4c3-444b-9db4-5013c5afeccc.jpg)

![图片](https://user-images.githubusercontent.com/45528451/168974307-0cd012a2-0e91-4d6e-a23e-ecc7d7b8a7c1.png)

**Comment by yoke0104x** [comment]
@h265642327 大佬，为什么我在别的服务器上面可以启动，但是一直在下载东西
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/44898730/168974538-e1e71a58-6fc5-4e4c-a9bd-89c766d0bcb3.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/44898730/168974565-054b2d83-d93a-4b4c-b533-22d316df7aca.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/44898730/168974580-a15f8e0d-e086-4f2f-8192-4fe6335a5f74.png">

就很离谱

**Comment by h265642327** [comment]
一开始会下载很多东西
等等就好了

**Comment by h265642327** [comment]
大部分是功能的背景图片，在image可以看到

**Comment by yoke0104x** [comment]
@h265642327 大佬，已经下载二十多分钟了
已经卡这里了
<img width="963" alt="image" src="https://user-images.githubusercontent.com/44898730/168975039-68425969-9328-4924-a145-3ed3ca5cc4da.png">

**Comment by h265642327** [comment]
退出重新再进来，会一直下载到完成

**Comment by h265642327** [comment]
然后出现开始接收消息的画面

**Comment by h265642327** [comment]
ARNING] plugins | azur_up_char 解析出错
05-18 14:46:11 [WARNING] plugins | pretty_up_char 解析出错
05-18 14:46:11 [WARNING] plugins | prts_up_char 解析出错
05-18 14:46:11 [INFO] uvicorn | Application startup complete.
05-18 14:46:11 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:53245 (Press CTRL+C to quit)
05-18 14:46:13 [INFO] uvicorn | ('127.0.0.1', 55716) - "WebSocket /onebot/v11/ws/" [accepted]
05-18 14:46:13 [INFO] nonebot | OneBot V11 | Bot 489363232 connected
05-18 14:46:13 [INFO] websockets | connection open
05-18 14:46:14 [DEBUG] nonebot | Running CallingAPI hooks...
05-18 14:46:14 [DEBUG] nonebot | OneBot V11 | Calling API get_group_list
05-18 14:46:14 [INFO] basic_plugins | 已成功加载 9 个被动技能.
05-18 14:46:14 [INFO] basic_plugins | register_use 成功注册商品：好感度双倍加持卡Ⅰ 的使用函数
05-18 14:46:14 [INFO] basic_plugins | register_use 成功注册商品：好感度双倍加持卡Ⅱ 的使用函数
05-18 14:46:14 [INFO] basic_plugins | register_use 成功注册商品：好感度双倍加持卡Ⅲ 的使用函数
05-18 14:46:15 [INFO] basic_plugins | 已成功加载 28 条超级用户命令
05-18 14:46:17 [SUCCESS] nonebot | ONEBOT V11 489363232 | [message.group.normal]: Message 170133133 from 2576152504@[群:980367522] "[CQ:image,file=68fa389a3f324e9d8fb4c2e4360c5585.image,url=https://gchat.qpic.cn/gchatpic_new/2576152504/980367522-3131629636-68FA389A3F324E9D8FB4C2E4360C5585/0?term=3,subType=1]"
05-18 14:46:17 [DEBUG] nonebot | Checking for matchers in priority 1...
05-18 14:46:17 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-18 14:46:17 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, pr

**Comment by yoke0104x** [comment]
@h265642327 好的大佬我试试

**Comment by h265642327** [comment]
![屏幕截图 2022-05-18 144629](https://user-images.githubusercontent.com/94788823/168975488-4bb96e0a-97e5-4348-b073-805f4c9314e9.jpg)
@HibiKier

**Comment by h265642327** [comment]
刚刚是关闭了go-cqhttp，并且打开运行`yarn run serve`，随后关闭webui并且运行go-cqhttp，机器人正常运转，但是还是出现了如上图的warning

**Comment by yoke0104x** [comment]
@h265642327 不行还是起不来，好难啊

**Comment by h265642327** [comment]
其实你的cofig.yml文件还没配置问题不大，如果还是卡在图片下载，兴许就是网络的问题了

**Comment by h265642327** [comment]
我那时候直接screen打开挂着就没再理会了

**Comment by yoke0104x** [comment]
@h265642327 不行我的go-cqhttp配置了显示。 这是为啥？
<img width="963" alt="image" src="https://user-images.githubusercontent.com/44898730/168982202-11b03018-194e-41ab-a148-c2c41dfecc45.png">

**Comment by h265642327** [comment]
出现这个问题，请不要停止，而是新界面进入bot文件位置，poetry shell创建虚拟环境，运行bot.py就可以了

**Comment by yoke0104x** [comment]
@h265642327 如果用的是docker怎么搞呢？

**Comment by h265642327** [comment]
docker里应该还是linux系统，linux下可以下载screen

**Comment by lhr9645** [comment]
![IMG_20220519_000525](https://user-images.githubusercontent.com/95252733/169089791-9cf9a95c-367c-47fe-ad81-ca4edde3cebc.jpg)
我这也是解析错误 然后直接被终止了 求助 怎么破 我这不是国内的服务器

**Comment by HibiKier** [comment]
> ![IMG_20220519_000525](https://user-images.githubusercontent.com/95252733/169089791-9cf9a95c-367c-47fe-ad81-ca4edde3cebc.jpg) 我这也是解析错误 然后直接被终止了 求助 怎么破 我这不是国内的服务器

大概率是原神下地图拼接的时候内存炸了，可以暂时把原神资源插件删掉，plugins/genshin/query_resource_...
