### ISSUE TITLE
启动过程中数据库认证失败，原因不明

### ISSUE THREAD

**Issue by Graicaa** [HibiKier/zhenxun_bot#225]
出现认证错误：
![image](https://user-images.githubusercontent.com/50552632/168971983-72460614-69a7-4039-bee1-6b492c2bc683.png)

已配置数据库 ：
![image](https://user-images.githubusercontent.com/50552632/168971065-85670a9e-ef61-4a68-9e06-4e57d6cd9f18.png)

![image](https://user-images.githubusercontent.com/50552632/168971209-e096808a-f6f4-480c-bc05-fc61ce1e6b60.png)

直接用账号密码登入数据库也不行：
![image](https://user-images.githubusercontent.com/50552632/168971374-f2a57306-a669-41af-a4d7-3f45079ee2d1.png)

环境：centos7 python3.9 Postgresql-12

**Comment by Graicaa** [comment]
![image](https://user-images.githubusercontent.com/50552632/168972746-68374462-a17c-40e6-8033-aa706447cfa2.png)

**Comment by HibiKier** [comment]
密码错了？

**Comment by Yuzi1477** [comment]
我跟你一样的错误，直到我把config.py文件的address设置成我服务器的ip地址之后就跑通了

**Comment by Graicaa** [comment]
> 我跟你一样的错误，直到我把config.py文件的address设置成我服务器的ip地址之后就跑通了

感谢，换成公网ip就可以了
