### ISSUE TITLE
启动bot后没有生成文件

### ISSUE THREAD

**Issue by MB19890425** [HibiKier/zhenxun_bot#226]
![图片](https://user-images.githubusercontent.com/105762714/168977198-abb2ff2f-3ff6-4df4-84dc-5ae7f3edfa23.png)
启动bot后没有发现生成各种配置文件

**Comment by MingxuanGame** [comment]
有没有可能

你的目录没有插件

**Comment by MB19890425** [comment]
> 有没有可能
> 
> 你的目录没有插件
> 
> dir 和 tree 看一下

![图片](https://user-images.githubusercontent.com/105762714/168978483-989bbe7a-1903-4e90-9dd5-33e03466bfa1.png)
![图片](https://user-images.githubusercontent.com/105762714/168978583-52d8e0db-0508-4616-b257-635663b1303c.png)

按照教程一点一点做的，不知道少了什么

**Comment by MingxuanGame** [comment]
你这是在哪运行的。。。

在 bot 目录下运行

**Comment by MB19890425** [comment]
> 你这是在哪运行的。。。
> 
> 在 bot 目录下运行

我是在cmd里运行bot.py的

**Comment by MingxuanGame** [comment]
`cd Desktop\bot\gocq\zhenxun_bot-main` 再运行

**Comment by MB19890425** [comment]
> cd Desktop\bot\gocq\zhenxun_bot-main

谢谢大佬指点
