### ISSUE TITLE
部分插件（报错）及命令无法使用

### ISSUE THREAD

**Issue by ChenPiTang-Hui** [HibiKier/zhenxun_bot#227]
[error_2022-05-18.log](https://github.com/HibiKier/zhenxun_bot/files/8713982/error_2022-05-18.log)

**Comment by MingxuanGame** [comment]
你 `bilireq` 都没装。。。

```bash
pip install poetry
poetry install
poetry shell
python bot.py
```

**Comment by ChenPiTang-Hui** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/69108232/168980399-95abe31e-54c1-470a-af30-4b38b5824506.png">

**Comment by ChenPiTang-Hui** [comment]
> 你`bilireq`没装。。。
> 
> ```shell
> pip install poetry
> poetry install
> poetry shell
> python bot.py
> ```

<img width="393" alt="image" src="https://user-images.githubusercontent.com/69108232/168980490-a16c94e6-4cef-487d-b0f5-6aeeb7e52d31.png">

**Comment by HibiKier** [comment]
pip install poetry
poetry install
poetry shell
python bot.py
请按顺序执行

**Comment by ChenPiTang-Hui** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/69108232/169072146-76243b81-7747-473d-88e0-fa7156fc5ecf.png"> 已经照顺序执行依旧有错误

**Comment by xcf1127** [comment]
![ZH{PSP_SW _IP%HKO}%_CL8](https://user-images.githubusercontent.com/105791636/169308083-a398d379-aa37-4a6e-b913-de64f6b936d6.png)
大佬们，到这儿怎么整阿

**Comment by HibiKier** [comment]
> ![ZH{PSP_SW _IP%HKO}%_CL8](https://user-images.githubusercontent.com/105791636/169308083-a398d379-aa37-4a6e-b913-de64f6b936d6.png) 大佬们，到这儿怎么整阿

看你数据库开了没，配置有没有写错
