### ISSUE TITLE
关于webui的一些问题

### ISSUE THREAD

**Issue by h265642327** [HibiKier/zhenxun_bot#228]
我按照步骤完成了node的安装以及cve-lic的安装，并且一切正常一直到开始运行（yarn run serve）这一步
![屏幕截图 2022-05-18 144629](https://user-images.githubusercontent.com/94788823/168982739-949b887b-db2b-42d8-8157-3bb51dce0f2e.jpg)

之后是配置了config。yml里面的账号密码：输入的是数据库的uname和密码

以及更新了vue.config.js的端口
![屏幕截图 2022-05-18 153708](https://user-images.githubusercontent.com/94788823/168983843-ccff6361-2a9c-4ffd-a87a-f1a1f6acff2a.jpg)

**Comment by h265642327** [comment]
随后也打开了127.0.0.1：端口的网站，但是打不开
![屏幕截图 2022-05-18 154608](https://user-images.githubusercontent.com/94788823/168985703-0a8b0242-3dc2-482a-9a14-d53f2af97e4f.jpg)

**Comment by SinGone949** [comment]
127.0.0.1换成你服务器的ip地址

**Comment by h265642327** [comment]
是访问的时候吗？ @SinGone949

**Comment by h265642327** [comment]
请问是访问的时候更改为我的服务器地址：端口还是什么

**Comment by SinGone949** [comment]
是的，只改访问的时候的网址。

**Comment by h265642327** [comment]
http://47.107.101.71:53246/还是打不开 @SinGone949

**Comment by SinGone949** [comment]
那我就不知道啦，我只知道127.0.0.1代表本机，你访问本机是肯定访问不到服务器的内容的。

**Comment by SinGone949** [comment]
对了，有没有放行端口

**Comment by h265642327** [comment]
上服务器控制台看看有没有给端口，我也给忘了 @SinGone949

**Comment by h265642327** [comment]
还是不行 @SinGone949

**Comment by Sakuracio** [comment]
WebUI仍是一个预览性开发版本，它的功能有限，如果你只需要使用Bot是不需要安装的。

**Comment by Sakuracio** [comment]
如果你只需要使用Bot是不需要安装WebUI的

**Comment by h265642327** [comment]
好吧，我还有一个问题关于开发插件，新增的额外插件是需要更改新增插件的源代码，做到统一插件标准的好处，然后再在config添加优先级吗 @SinGone949

**Comment by HibiKier** [comment]
优先级是nonebot定义matcher时的priority字段，一般在1-9之间，正常设置为5，为1时不受权限检查（任何时候都会启用），9一般为最后执行的插件，也不会受权限检查

**Comment by h265642327** [comment]
好的，开发文档讲得也很清楚，谢谢你们的帮助

**Comment by HibiKier** [comment]
你访问web ui的地址咋写的？127.0.0.1:8081 吗？

**Comment by Excalibur5100** [comment]
![image](https://user-images.githubusercontent.com/105792144/169038027-45e73754-6373-4a47-809d-683cb16ba04b.png)
![image](https://user-images.githubusercontent.com/105792144/169038677-1f9def28-91e5-43c8-a7a8-275aa359b3d6.png)
![image](https://user-images.githubusercontent.com/105792144/169038802-f7745b83-73ff-41cf-9e70-c23637445b75.png)

我的可以，就是用的部署bot的云服务器的公网ip作为前缀直接在浏览器地址栏输入访问，要先在服务器控制台那配置安全策略，也就是开放对应端口防火墙，如果你的不一样，不知道关掉防火墙会不会有效
![image](https://user-images.githubusercontent.com/105792144/169038530-fdc6511a-a14e-4161-bf08-bcf654681cd5.png)

**Comment by h265642327** [comment]
@Excalibur5100 看看你这里配置怎么填写的
![屏幕截图 2022-05-18 223905](https://user-images.githubusercontent.com/94788823/169068678-b0babec3-0ccc-4454-b375-fdf60accf016.jpg)

**Comment by Excalibur5100** [comment]
> @Excalibur5100 看看你这里配置怎么填写的 ![屏幕截图 2022-05-18 223905](https://user-images.githubusercontent.com/94788823/169068678-b0babec3-0ccc-4454-b375-fdf60accf016.jpg)

![image](https://user-images.githubusercontent.com/105792144/169071720-ae033da4-8194-42a7-b66b-31c4df3b263f.png)
我的是这样的
