### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by opase** [HibiKier/zhenxun_bot#229]
![image](https://user-images.githubusercontent.com/49069876/168985506-665fbf3a-0ed4-4c24-91b9-47fa9d40f359.png)
按照文档安装的，试了好几遍都不行

**Comment by po-lan** [comment]
最下边红字 ，缺东西
自己看

**Comment by opase** [comment]
> 最下边红字 ，缺东西 自己看

![image](https://user-images.githubusercontent.com/49069876/168988209-bbeb3b1b-1389-4812-a6bf-47c05a33e3bb.png)
已经安装了模块，一直不能读取

**Comment by po-lan** [comment]
> > 最下边红字 ，缺东西 自己看
> 
> ![image](https://user-images.githubusercontent.com/49069876/168988209-bbeb3b1b-1389-4812-a6bf-47c05a33e3bb.png) 已经安装了模块，一直不能读取

阿这 ，这个问题我 没法帮你因为我没遇到过

**Comment by MingxuanGame** [comment]
依照下面的顺序修改
```bash
vim /etc/localtime
```
如果不是Asia/Shanghai就改为这个（需要会vim操作）

```bash
rm -f /etc/localtime
cp /usr/share/zoneinfo/Asia/Shanghai/etc/localtime
```

_需要root权限_
