### ISSUE TITLE
帮助功能只在私聊生效，群聊不生效

### ISSUE THREAD

**Issue by Leu552** [HibiKier/zhenxun_bot#232]
主要体现在，群聊里发送“帮助色图”，真寻没有反应
私聊发送“帮助色图”，真寻有图片返回
超级用户在群聊里也不行
但是在群聊里发送“真寻帮助”就会有图片

**Comment by Sakuracio** [comment]
真寻帮助 [功能]
OR
@Bot 帮助 [功能]
你需要叫她！

**Comment by Leu552** [comment]
> 真寻帮助 [功能] OR @bot 帮助 [功能] 你需要叫她！

感谢
