### ISSUE TITLE
数据库出错了好像

### ISSUE THREAD

**Issue by eENmame** [HibiKier/zhenxun_bot#235]

**Comment by eENmame** [comment]
![image](https://user-images.githubusercontent.com/105780794/168999146-9b4c2054-94c8-4967-ab33-13fbf087d217.png)

**Comment by eENmame** [comment]
这个是数据库哪里出问题了啊

**Comment by MingxuanGame** [comment]
检查用户名，密码，端口，以及数据库是否开启

可以的话，发一下你的 `configs/config.py` 便于诊断问题

**Comment by eENmame** [comment]
好的 我看下






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 数据库出错了好像 (Issue #235)





 
检查用户名，密码，端口，以及数据库是否开启
 
可以的话，发一下你的 configs/config.py 便于诊断问题

**Comment by eENmame** [comment]
![image](https://user-images.githubusercontent.com/105780794/169002593-3f0e84d5-d83a-432b-8e1d-fc6e7d408e68.png)

**Comment by eENmame** [comment]
后面还是这个问题= =

**Comment by eENmame** [comment]
运行报错数据库错误

**Comment by eENmame** [comment]
还是说数据库还要设置其他的东西啊= =

**Comment by eENmame** [comment]
> 检查用户名，密码，端口，以及数据库是否开启
> 
> 可以的话，发一下你的 便于诊断问题`configs/config.py`

老哥老哥 图发了 不过好像设置应该没问题吧

**Comment by MingxuanGame** [comment]
感觉像是数据库没开或者没开放访问

你检查一下数据库设置

**Comment by eENmame** [comment]
好的老哥






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 下午5:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 数据库出错了好像 (Issue #235)





 
感觉像是数据库没开或者没开放访问
 
你检查一下数据库设置

**Comment by eENmame** [comment]
不会是这个文件的问题吧






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 下午5:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 数据库出错了好像 (Issue #235)





 
感觉像是数据库没开或者没开放访问
 
你检查一下数据库设置
