### ISSUE TITLE
使用启动真寻Bot，会在 configs 和 data/configs 目录下生成各种配置文件

### ISSUE THREAD

**Issue by zlsSGuang** [HibiKier/zhenxun_bot#237]
标题那一段是启动哪个？用bot.py弹出了命令窗之后就闪退了

**Comment by MingxuanGame** [comment]
bot.py 
请使用终端 例如 `cmd` 或 `powershell` 运行

**Comment by eENmame** [comment]
用python也能启动

**Comment by borntree** [comment]
启动虚拟环境后在运行这个命令，而且要在有bot.py的目录下运行，我的命令是python bot.py而不是python3 bot.py，不知道你是不是也是这样

**Comment by eENmame** [comment]
cmd打开的话我也是python bot.py




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] 使用启动真寻Bot，会在 configs 和 data/configs 目录下生成各种配置文件 (Issue #237)





 
启动虚拟环境后在运行这个命令，而且要在有bot.py的目录下运行，我的命令是python bot.py而不是python3 bot.py，不知道你是不是也是这样

**Comment by eENmame** [comment]
cmd打开的话我也是python bot.py





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] 使用启动真寻Bot，会在 configs 和 data/configs 目录下生成各种配置文件 (Issue #237)





 
启动虚拟环境后在运行这个命令，而且要在有bot.py的目录下运行，我的命令是python bot.py而不是python3 bot.py，不知道你是不是也是这样

**Comment by dick0841** [comment]
poetry shell进入虚拟环境后，我尝试python bot.py，但是
![1](https://user-images.githubusercontent.com/50237543/169011341-f02b81ab-3151-410f-b7eb-590a1911c94b.png)
![2](https://user-images.githubusercontent.com/50237543/169011349-1af58748-60ca-4990-9beb-4dc1cf3bb53e.png)
反馈如图，请问我该如何解决这个问题？远程主机关闭链接是tt的降维打击吗？以及考虑到问题可能跟我configs/configs.py有关，我将我configs.py中的数据附上如图。感谢大佬帮助
![3](https://user-images.githubusercontent.com/50237543/169012098-53447823-2248-4cbc-b0e0-dd49c515feb6.png)
！

**Comment by zlsSGuang** [comment]
> bot.py 请使用终端 例如 或 运行`cmd``powershell`

![image](https://user-images.githubusercontent.com/105781964/169014432-6727f4a6-e39a-4459-95e2-b641a6871962.png)
似乎不行……

**Comment by zlsSGuang** [comment]
已经装了python3.10，一直闪退
![image](https://user-images.githubusercontent.com/105781964/169014832-1cc5ebf5-8765-46d7-afdc-ef488ef825d6.png)

**Comment by eENmame** [comment]
3.8或者3.9吧 3.10可能版本太低






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 晚上6:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 使用启动真寻Bot，会在 configs 和 data/configs 目录下生成各种配置文件 (Issue #237)





 
已经装了python3.10，一直闪退

**Comment by MingxuanGame** [comment]
> 已经装了python3.10，一直闪退
> ![image](https://user-images.githubusercontent.com/105781964/169014832-1cc5ebf5-8765-46d7-afdc-ef488ef825d6.png)
> 

要 3.8 或 3.9

**Comment by zlsSGuang** [comment]
> 3.8或者3.9吧 3.10可能版本太低
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年5月18日(星期三) 晚上6:07 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HibiKier/zhenxun_bot] 使用启动真寻Bot，会在 configs 和 data/configs 目录下生成各种配置文件 (Issue #237) 已经装了python3.10，一直闪退 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

谢谢我去试试！！！

**Comment by zlsSGuang** [comment]
> > 已经装了python3.10，一直闪退
> > ![图像](https://user-images.githubusercontent.com/105781964/169014832-1cc5ebf5-8765-46d7-afdc-ef488ef825d6.png)
> 
> 要 3.8 或 3.9

感谢大佬

**Comment by MingxuanGame** [comment]
如果您已经解决了问题

恳请点击一下这个按钮将此 issue 关闭

![image](https://user-images.githubusercontent.com/68982190/169042615-c6b1148f-5cb7-4af1-a27a-66d75d6220ef.png)

**Comment by eENmame** [comment]
我这里直接用python 打开bot文件的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 下午5:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 使用启动真寻Bot，会在 configs 和 data/configs 目录下生成各种配置文件 (Issue #237)





 
启动虚拟环境后在运行这个命令，而且要在有bot.py的目录下运行，我的命令是python bot.py而不是python3 bot.py，不知道你是不是也是这样
