### ISSUE TITLE
稳定运行了，但是机器人好像没有反应

### ISSUE THREAD

**Issue by zy143** [HibiKier/zhenxun_bot#241]
好兄弟们，我搞完没报错，挂到宝塔上，稳定运行了，但是机器人好像没有反应，这是什么原因
![image](https://user-images.githubusercontent.com/71754921/169007714-35c59668-ce28-4591-9012-98020af08c7a.png)

**Comment by MingxuanGame** [comment]
你是怎么使用机器人的

**Comment by zy143** [comment]
放到群里@它






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 下午5:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 稳定运行了，但是机器人好像没有反应 (Issue #241)





 
你是怎么使用机器人的

**Comment by MingxuanGame** [comment]
你的 go-cqhttp 是否开启

**Comment by zy143** [comment]
hhhh,可以了谢谢大佬

**Comment by zy143** [comment]
感谢大佬！！！！！
