### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by JuuiceP** [HibiKier/zhenxun_bot#243]
环境：docker   真寻与数据库同机
测试：使用其他机器可远程连接到数据库，但是真寻无法连接数据库

就很怪
端口密码用户名均没错

![QQ截图20220518172857](https://user-images.githubusercontent.com/90129856/169009207-b2e6c042-c6e7-4f2c-8437-d10db0cc3b8c.png)
![QQ截图20220518173849](https://user-images.githubusercontent.com/90129856/169009231-5953d41f-2498-488e-8597-9075fd80342d.png)

**Comment by HibiKier** [comment]
试试把地址换成127.0.0.1？

**Comment by JuuiceP** [comment]
自建的数据库用户已给予所有权限，试过了127.0.0.1 也不行，连接到其他机器的数据库也连不上==

**Comment by JuuiceP** [comment]
解决了，将机器人docker网络设为host就解决了，很怪
明明数据库是bridge，但是机器人是bridge就不行
