### ISSUE TITLE
在configs/utils/__init__.py中，调用add_plugin_config，显示_data类型为NoneType

### ISSUE THREAD

**Issue by WYH9355** [HibiKier/zhenxun_bot#244]
使用python3.8 启动，单独加载configs/utils/__init__.py能看到_data是dict

但是以python3.8 bot.py 运行就会显示None

各位大佬有什么解决方法吗？

![image](https://user-images.githubusercontent.com/32318216/169009497-eaec8d91-b161-489d-afaa-8cd6b9d7b2f0.png)

打印了下
![image](https://user-images.githubusercontent.com/32318216/169011039-764d26ee-1c37-44a4-a915-f359b6b838f9.png)

**Comment by HibiKier** [comment]
删除data/configs/plugin2configs重新生成
