### ISSUE TITLE
腾讯云Linux ubuntu ./go-cqhttp | python3 bot.py 异常无法处理

### ISSUE THREAD

**Issue by F-Yaohu** [HibiKier/zhenxun_bot#245]
将运行`./go-cqhttp`后就一直报连接错误，但群里发的消息却能接收到，就是没反应
![图片](https://user-images.githubusercontent.com/76428495/169010850-221a7a45-1093-46e0-b66c-44a9b230e615.png)

zhenxun_bot文件夹里面运行 `python3 bot.py` 完成后，也会抛出一段Error
![图片](https://user-images.githubusercontent.com/76428495/169011523-15237ed3-82e9-4cf6-8ddc-688ff937a7f3.png)

（百度上没有搜到相应的解决方案，都是一些解决端口冲突的帖子）
有大佬知道这是怎么一回事吗？

**Comment by HibiKier** [comment]
尝试pip卸载bilibili api再启动

**Comment by F-Yaohu** [comment]
> 您好，麻烦问一下，这个bilibili api是什么格式的文件，直接用sudo apt-get remove xxx能删掉吗？

**Comment by h265642327** [comment]
首先第一个报错没关系，启动了bot之后就正常了

**Comment by h265642327** [comment]
可能是可能是端口8080太过很多人用，然后超时，建议多试几次或者更换端口

**Comment by F-Yaohu** [comment]
>

**Comment by F-Yaohu** [comment]
> 可能是可能是端口8080太过很多人用，然后超时，建议多试几次或者更换端口

嗯，谢谢大佬，我会尝试的
