### ISSUE TITLE
wei-ui无法登录

### ISSUE THREAD

**Issue by 1561057334** [HibiKier/zhenxun_bot#246]
我根据安装文档在zhenxun_bot/configs/config.yaml的94行处填写了前端管理密码，但登录web-ui时提示用户名或密码错误，请问这是什么原因

**Comment by HibiKier** [comment]
重载配置或重启过了吗，还有
![图片](https://user-images.githubusercontent.com/45528451/169013496-68de2692-be97-413b-b136-5f6f7426f4bc.png)
了吗

**Comment by 1561057334** [comment]
> 重载配置或重启了，还有 ![图片](https://user-images.githubusercontent.com/45528451/169013496-68de2692-be97-413b-b136-5f6f7426f4bc.png)
是我没有重载配置，多谢大佬。
