### ISSUE TITLE
中文文件名打不开

### ISSUE THREAD

**Issue by SinGone949** [HibiKier/zhenxun_bot#248]
其他功能一切正常，但是骂我没有反应，翻了一下日志：

May 18 17:50:04 Chainedbox bash[160859]: #033[0m#033[33m[2022-05-18 17:50:04] [WARNING]: 转换CQ码 ({"type": "record", "data": {"file": "file:////opt/wwwroot/gocq/zhenxun_bot/resources/record/dinggong/12_\u518d\u89c1\u4e4b\u7c7b\u7684\u8bdd\uff0c\u6211\u624d\u61d2\u5f97\u5bf9\u4f60\u8bf4\u2026_.mp3", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in $PATH 将忽略本段CQ码.
May 18 17:50:04 Chainedbox bash[160859]: #033[0m#033[33m[2022-05-18 17:50:04] [WARNING]: 好友消息发送失败: 消息为空.

看了一下对应目录是有相应文件的，命令打的是Unicode码，估计就是编码问题了，但是怎么解决没有什么头绪……

**Comment by ID114514** [comment]
ffmpeg

**Comment by SinGone949** [comment]
谢谢解答
