### ISSUE TITLE
大佬救命！启动bot.py时报错

### ISSUE THREAD

**Issue by ardsgfcrtjhj** [HibiKier/zhenxun_bot#249]
(zhenxun-bot-NUwrpPNM-py3.9) [root@localhost zhenxun_bot]# python3 bot.py
Traceback (most recent call last):
  File "/home/git/bot/zhenxun_bot/bot.py", line 2, in <module>
    from nonebot.adapters.onebot.v11 import Adapter
ModuleNotFoundError: No module named 'nonebot.adapters.onebot'

看起来好像缺少模块，但我已经安装了nonebot

**Comment by MingxuanGame** [comment]
pip install poetry
poetry install
poetry shell
python bot.py

**Comment by ID114514** [comment]
虚拟环境

**Comment by ardsgfcrtjhj** [comment]
> pip 安装诗歌 诗歌安装 诗歌外壳 python bot.py

多谢大佬 已经搞定

**Comment by ardsgfcrtjhj** [comment]
> pip install poetry poetry install poetry shell python bot.py

多谢大佬 搞定了！
