### ISSUE TITLE
微博热点，网易云热搜评问题

### ISSUE THREAD

**Issue by chara1051** [HibiKier/zhenxun_bot#250]
![Screenshot_20220518_182529](https://user-images.githubusercontent.com/105768555/169018869-5d95823e-7631-44dd-8ec0-72fee83ce366.jpg)
![捕获(3)](https://user-images.githubusercontent.com/105768555/169018881-eca794e4-b851-448f-bfc1-d62faf0a5e9f.PNG)

**Comment by h265642327** [comment]
+1

**Comment by MingxuanGame** [comment]
see #223

**Comment by h265642327** [comment]
ok
![屏幕截图 2022-05-18 185249](https://user-images.githubusercontent.com/94788823/169023346-d6fe3072-3789-455f-bad1-f4969eb4f8cb.jpg)

**Comment by h265642327** [comment]
![屏幕截图 2022-05-18 ](https://user-images.githubusercontent.com/94788823/169023387-0a58eeab-4d93-4e1a-9c38-5cabc6acd51a.jpg)

**Comment by h265642327** [comment]
@HibiKier 已经配置了 
![屏幕截图 2022-05-18 223905](https://user-images.githubusercontent.com/94788823/169073297-394fa0c3-e700-4092-8f7c-788d5eb66555.jpg)

**Comment by HibiKier** [comment]
并没有运行到alapi方面的插件，插件成功加载了吗

**Comment by ExcitedEven** [comment]
> @HibiKier 已经配置过的 ![28X% IGS5XDS% X@W%0PXS](https://user-images.githubusercontent.com/94788823/169073616-40f63dbe-8c9b-4455-9ffc-d07d787fcad2.png)

 @HibiKier  顺便请问一下, ALAPI的token怎么写. 是就这样写, 还是要加引号

**Comment by h265642327** [comment]
memes

nonebot_plugin_r6s

nonebot_plugin_petpet

random_cat_gif

abstract

mockingbird

asoulcnki

avatar

import失败的只有这些，

**Comment by h265642327** [comment]
05-19 13:31:39 [SUCCESS] nonebot | Succeeded to import "alapi"

**Comment by h265642327** [comment]
@HibiKier

**Comment by h265642327** [comment]
其他插件的问题是缺少相应的库

**Comment by HibiKier** [comment]
> 05-19 13:31:39 [SUCCESS] nonebot | Succeeded to import "alapi"

![图片](https://user-images.githubusercontent.com/45528451/169222065-3a844734-59e2-48d5-9884-1a93a57649ee.png)
这几个

**Comment by h265642327** [comment]
我把其他插件修复了，现在莫名恢复正常了 。! _ ！

**Comment by h265642327** [comment]
![ITNV(60H0S2 4OY{)_3Q TP](https://user-images.githubusercontent.com/94788823/169225816-42a8a72f-69cb-4e19-8956-a3a1dffa788a.png)

**Comment by cyberaltoria** [comment]
> 我把其他插件修复了，现在莫名恢复正常了 。! _ ！
大佬这些插件都需要什么库啊，为什么我安装了库还是加载失败呀
