### ISSUE TITLE
关于无法正常运行python bot.py的问题

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#251]
萌新摸索了2天想办法搞到了bot安装这步，但是遇到了感觉超出解决能力的问题QAQ
在cmd中定位了目标文件夹构建poetry shell环境后，出现如图错误反馈
![1](https://user-images.githubusercontent.com/50237543/169019211-7dd410b4-e731-4b04-ba17-4f7508c3d866.png)
![2](https://user-images.githubusercontent.com/50237543/169019235-44bf88e4-f9c2-4b02-bcbe-3b5c68d9f85d.png)
![3](https://user-images.githubusercontent.com/50237543/169019253-311a7ae3-3565-4ecd-977f-8fbe68716092.png)
![4](https://user-images.githubusercontent.com/50237543/169019276-23d50a4b-dcda-46d8-b6fe-a872c71b7aae.png)
![5](https://user-images.githubusercontent.com/50237543/169019323-6cd8f512-62fa-4020-9cea-7309133eaa0e.png)
![6](https://user-images.githubusercontent.com/50237543/169019338-9784a033-0c75-4d93-8d1a-76e3ab45eed8.png)
![7](https://user-images.githubusercontent.com/50237543/169019345-82230537-786a-4e4f-9a50-4f7f2abf9b77.png)
考虑到该问题可能与我数据库的配置与configs\configs.py内数据填写有误有关，附图如下：
![db1](https://user-images.githubusercontent.com/50237543/169019682-415c39d8-fb57-4a36-91e9-5295f59a3a3d.png)
![con1](https://user-images.githubusercontent.com/50237543/169019886-6249cf5f-e6ef-46d2-b1d9-00a9dcef4d2e.png)
以上程序使用了python3.9为编译器，没用将数据库与云端连接（不清楚是否一定要云端链接，如果本机数据库是不能运行的我再去查查怎么做），pip、poetry等库均已经install，主机账户为超级账户且为英文名，以及go-cqhttp运行结果如下（我感觉cqhttp里host应该是bot把，所以应该问题不大等bot设好就好了，但是以防万一还是向大佬确认一下，非常感谢！！
![go1](https://user-images.githubusercontent.com/50237543/169020731-5a965d99-8e5b-47a9-b4f2-501bdfb1fe1b.png)

**Comment by MingxuanGame** [comment]
see #227

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169028812-b34e615e-ab5f-4020-85db-9364d6dddda0.png)
新建你的
![图片](https://user-images.githubusercontent.com/45528451/169028876-d18c9c3e-1f43-4396-ba4a-14f942b9358d.png)

**Comment by dick0841** [comment]
非常感谢，目前真寻已经可以进行一定的回复，但是功能并不完全，调用网易热评、原神黄历等功能还无法使用。而我在配置webui时发生如下错误
![q1](https://user-images.githubusercontent.com/50237543/169099430-0f7a2f57-4c26-4306-963e-71b9c701ccd8.png)
，请问我该如何处理让指令正常运行？

**Comment by dick0841** [comment]
装了，现在大多数功能都可以正常使用，包括但不限于发语音、查buff价格、更新原神卡池信息、自动退被强拉的群等，但是识图、搜番、识番几个功能好像无法识别我发送的图片（不知道应该一条信息包括命令行及图片还是可以一句话命令行后面跟图片），不过大多功能都可以用了，感谢大佬帮助！（真寻真可爱阿（流口水

**Comment by dick0841** [comment]
以及想问问web-ui那里的 用户名和密码在哪注册，我只能得到如图结果
![微信截图_20220519094023](https://user-images.githubusercontent.com/50237543/169185569-c78354e0-ddbf-44d8-8acd-a842d610d9d7.png)
不知道在哪看用户名密码QAQ，以及我现在本地运行一停止真寻就宕机了，有办法让真寻不用本地运行就可以自己跑吗

再次感谢大佬们抽空帮助萌新QWQ

**Comment by HibiKier** [comment]
> 以及想问问web-ui那里的 用户名和密码在哪注册，我只能得到如图结果 ![微信截图_20220519094023](https://user-images.githubusercontent.com/50237543/169185569-c78354e0-ddbf-44d8-8acd-a842d610d9d7.png) 不知道在哪看用户名密码QAQ，以及我现在本地运行一停止真寻就宕机了，有办法让真寻不用本地运行就可以自己跑吗
> 
> 再次感谢大佬们抽空帮助萌新QWQ

webui文档说的很清楚了，你可以在阿里云什么的整个服务器跑
