### ISSUE TITLE
修改 listen_addresses: '*' 无法退出问题

### ISSUE THREAD

**Issue by F-Yaohu** [HibiKier/zhenxun_bot#253]
我在 `listen_addresses: '*'` 前面的注释删掉后，就发现退不出去了
![图片](https://user-images.githubusercontent.com/76428495/169023880-b93da818-4996-4281-b3f6-76f369d1875f.png)
![图片](https://user-images.githubusercontent.com/76428495/169023995-ef5c4caf-15a8-4042-9ccf-d24a930b47ef.png)

**Comment by h265642327** [comment]
.wq

**Comment by h265642327** [comment]
:wq

**Comment by h265642327** [comment]
或者直接退出重新开始，一般会保留草稿

**Comment by F-Yaohu** [comment]
> :wq

是的，我时使用的wq退出，但它一直跑readonly

**Comment by F-Yaohu** [comment]
每次就只能重启服务器

**Comment by h265642327** [comment]
还有冒号，漏了冒号吗？readonly是只读，可能是权限不够

**Comment by Slinet6056** [comment]
用`:q!`呢

**Comment by MingxuanGame** [comment]
你是怎么进入 vim 编辑的

**Comment by MingxuanGame** [comment]
> 用`:q!`呢

不会保存

**Comment by F-Yaohu** [comment]
> 

![图片](https://user-images.githubusercontent.com/76428495/169024728-fdcda786-d2bd-494a-bd90-9136c2515eda.png)

**Comment by MingxuanGame** [comment]
> > 
> 
> ![图片](https://user-images.githubusercontent.com/76428495/169024728-fdcda786-d2bd-494a-bd90-9136c2515eda.png)

加 sudo

**Comment by F-Yaohu** [comment]
> > > 
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/76428495/169024728-fdcda786-d2bd-494a-bd90-9136c2515eda.png)
> 
> 加 sudo

嗯，谢谢大佬，已经成功了
