### ISSUE TITLE
启动bot后退出报错

### ISSUE THREAD

**Issue by F-Yaohu** [HibiKier/zhenxun_bot#255]
大佬们，我在虚拟环境启动bot后，就不知道怎么退出了，如果使用 `ctrl + c` 或者 `quit` ，那么bot就会直接报错，`./go-cqhttp` 也就还是会被拒绝连接
![图片](https://user-images.githubusercontent.com/76428495/169028245-b96f7205-f60a-408d-a54f-07191039a22f.png)

**Comment by HibiKier** [comment]
试试pip下载bilibili api再启动

**Comment by HibiKier** [comment]
试试pip卸载bilibili api再启动

**Comment by F-Yaohu** [comment]
> 

大佬你好，这个bilibili api 是个什么文件啊，一直没有找到

**Comment by HibiKier** [comment]
如果你在虚拟环境外 poetry remove bilibili_api
如果你在虚拟环境内 pip uninstall bilibili_api

**Comment by F-Yaohu** [comment]
> 如果你在虚拟环境外 poetry remove bilibili_api 如果你在虚拟环境内 pip uninstall bilibili_api

谢谢大佬！退出已经没有问题了！
![图片](https://user-images.githubusercontent.com/76428495/169032004-f3b49019-3a6a-48df-8e19-61780271509b.png)
就是 `./go-cqhttp` 还是被拒绝连接。。
![图片](https://user-images.githubusercontent.com/76428495/169032140-43e81a58-5561-4814-844a-0dbff72e5902.png)
