### ISSUE TITLE
部分功能报错异常，麻烦懂的大佬帮忙看看

### ISSUE THREAD

**Issue by zhong946555** [HibiKier/zhenxun_bot#256]
![1](https://user-images.githubusercontent.com/61000018/169028784-ebd2db68-52e5-4571-80ac-c2cd629b6cf1.png)
![image](https://user-images.githubusercontent.com/61000018/169028907-5c565853-2247-4835-87b3-294a7657d3af.png)
![image](https://user-images.githubusercontent.com/61000018/169028933-49ae5e35-a5b6-445e-9061-b86bc98f86a9.png)

**Comment by zhong946555** [comment]
这几个异常在使用部分功能的时候会出现，且这些功能都没有效果，我对此也错误也没有什么头绪，想请大佬帮忙指导一下

**Comment by HibiKier** [comment]
ffmpeg下载后配置环境变量

**Comment by zhong946555** [comment]
> ffmpeg下载后配置环境变量

非常感谢，按照您说的做后成功了

**Comment by borntree** [comment]
大哥你的ffmpeg啥版本的，我的配置完path发送“骂我”没反应

**Comment by HibiKier** [comment]
> 大哥你的ffmpeg啥版本的，我的配置完path发送“骂我”没反应

gocq重启了吗

**Comment by zhong946555** [comment]
> > 大哥你的ffmpeg啥版本的，我的配置完path发送“骂我”没反应
> 
> gocq重启了吗

![image](https://user-images.githubusercontent.com/61000018/169040502-a72f4752-1b83-4795-b252-72914c3931fa.png)
大佬，想请问一些关于这种问题该怎么处理呢

**Comment by zhong946555** [comment]
> 大哥你的ffmpeg啥版本的，我的配置完path发送“骂我”没反应

ffmpeg-4.1

**Comment by borntree** [comment]
> > 大哥你的ffmpeg啥版本的，我的配置完path发送“骂我”没反应
> 
> gocq重启了吗



> > > > 大哥你的ffmpeg啥版本的，我的配置完path发送“骂我”没反应
> > > 
> > > 
> > > gocq重启了吗
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/61000018/169040502-a72f4752-1b83-4795-b252-72914c3931fa.png) 大佬，想请问一些关于这种问题该怎么处理呢
> 
> ```shell
> playwright install chromium
> # or 
> playwright install-deps chromium
> ```

你这个上面进入虚拟环境poetry shell了吗

**Comment by borntree** [comment]
> > 大哥你的ffmpeg啥版本的，我的配置完path发送“骂我”没反应
> 
> ffmpeg-4.1

好的

**Comment by borntree** [comment]
> > 大哥你的ffmpeg啥版本的，我的配置完path发送“骂我”没反应
> 
> gocq重启了吗

电脑都重启了  我看看咋发图片的   图片应该可以描述的更清楚

**Comment by zhong946555** [comment]
> > > > 大哥你的ffmpeg啥版本的，我的配置完path发送“骂我”没反应
> > > 
> > > 
> > > gocq重启了吗
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/61000018/169040502-a72f4752-1b83-4795-b252-72914c3931fa.png) 大佬，想请问一些关于这种问题该怎么处理呢
> 
> ```shell
> playwright install chromium
> # or 
> playwright install-deps chromium
> ```

太强了，感谢

**Comment by MingxuanGame** [comment]
如果您已经解决了问题

恳请点击一下这个按钮将此 issue 关闭

![image](https://user-images.githubusercontent.com/68982190/169042615-c6b1148f-5cb7-4af1-a27a-66d75d6220ef.png)
