### ISSUE TITLE
有人在windows下实现了bot的“骂我”功能吗？

### ISSUE THREAD

**Issue by borntree** [HibiKier/zhenxun_bot#258]
想问一下有无大佬在windows安装依赖ffmpeg后可以实现的

**Comment by MingxuanGame** [comment]
Windows 下正常装 ffmpeg 并添加到 PATH 即可

**Comment by borntree** [comment]
感谢大佬，可以用了

**Comment by borntree** [comment]
其实并没完全可以用   我这都配置完了  可是输入“骂我”后还是没反应
甚至重启了电脑都没用  可以麻烦再帮忙看看吗
我下载的ffmpeg版本是ffmpeg-5.0.1-essentials_build 不能用后我删除path和原文件又用下载了ffmpeg-n5.0-latest-win64-lgpl-shared-5.0版本，然后配置了path
是因为版本的原因吗
上一个帖子他用的4.1，我等下去试试
Duplicate of #256 
![QQ图片20220518201639](https://user-images.githubusercontent.com/82987943/169042145-c1097bab-d904-4360-97f0-7b6199cdf98f.png)
![QQ图片20220518201654](https://user-images.githubusercontent.com/82987943/169042157-88db38ac-dbd5-4d99-9300-d09925c8a8df.png)
