### ISSUE TITLE
大佬救救，web-ui无法登录，只会显示报错

### ISSUE THREAD

**Issue by gaosumaodan** [HibiKier/zhenxun_bot#259]
![image](https://user-images.githubusercontent.com/105725248/169029727-b41b6a7d-3052-4f50-bc2f-d34867688a4b.png)
在config.yaml中也已经添加的账户和密码，但是无法登录
![image](https://user-images.githubusercontent.com/105725248/169030334-5848cefb-c167-401e-b802-92021627c77f.png)
救救

**Comment by MingxuanGame** [comment]
刷新了吗

see #246

**Comment by gaosumaodan** [comment]
> 有没有刷新
> 
> 见#246

刷新是指刷新登录网站吗

**Comment by MingxuanGame** [comment]
> > 有没有刷新
> > 见#246
> 
> 刷新是指刷新登录网站吗

重启真寻

**Comment by gaosumaodan** [comment]
> > > 有没有刷新
> > > 见#246
> > 
> > 
> > 刷新是指刷新登录网站吗
> 
> 重启真寻

哦哦，我试一下

**Comment by gaosumaodan** [comment]
> > > > 有没有刷新
> > > > 见#246
> > > 
> > > 
> > > 刷新是指刷新登录网站吗
> > 
> > 
> > 重启真寻
> 
> 哦哦，我试一下

谢谢大佬，解决了

**Comment by Ironieser** [comment]
请问一下开启webui的话，postgresql 的监听ip和port写服务器的吗？别的还要改不

**Comment by Ironieser** [comment]
我这儿是这样子，下面那个是腾讯云的内网地址，打不开的
![image](https://user-images.githubusercontent.com/32543247/169217308-f9754bb5-580f-46cd-96d9-42c753c74486.png)

**Comment by gaosumaodan** [comment]
> 我这儿是这样子，下面那个是腾讯云的内网地址，打不开的 ![image](https://user-images.githubusercontent.com/32543247/169217308-f9754bb5-580f-46cd-96d9-42c753c74486.png)

我是按照教程一步步来的，教程改的哪些我就改的哪些，如果运行没反应的话可以试一下在运行前输yarn build

**Comment by Ironieser** [comment]
解决了，我check了下防火墙，把tcp和udp端口都打开了，就好了（印象中我tcp早早就打开了，也应该是tcp链接

**Comment by Ironieser** [comment]
> > 我这儿是这样子，下面那个是腾讯云的内网地址，打不开的 ![image](https://user-images.githubusercontent.com/32543247/169217308-f9754bb5-580f-46cd-96d9-42c753c74486.png)
> 
> 我是按照教程一步步来的，教程改的哪些我就改的哪些，如果运行没反应的话可以试一下在运行前输yarn build

解决了，我check了下防火墙，把tcp和udp端口都打开了，就好了（印象中我tcp早早就打开了，也应该是tcp链接
