### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by RealKiro** [HibiKier/zhenxun_bot#26]
无论是`CentOS`还是`Ubuntu`都是同样的错误
- `pip3 install -r requirements.txt`
[![https://www.hualigs.cn/image/610fc178e59cb.jpg](https://www.hualigs.cn/image/610fc178e59cb.jpg)](https://www.hualigs.cn/image/610fc178e59cb.jpg)

- `pip2 install -r requirements.txt` 或 `pip install -r requirements.txt`
[![https://www.hualigs.cn/image/610fc22e2163d.jpg](https://www.hualigs.cn/image/610fc22e2163d.jpg)](https://www.hualigs.cn/image/610fc22e2163d.jpg)

**Comment by HibiKier** [comment]
python版本是？

**Comment by RealKiro** [comment]
> python版本是？

python 2.7.17
python 3.6.9

---
- 是和python版本有关吗？

**Comment by HibiKier** [comment]
对的，先不说bilibili-api，nonebot最低要求是3.7.3，不过最好3.8以上

**Comment by RealKiro** [comment]
> 对的，先不说bilibili-api，nonebot最低要求是3.7.3，不过最好3.8以上

好的，感谢🙏 ，我先试试

**Comment by RealKiro** [comment]
感谢🙏 ， 切换到python3.9依赖已安装成功 

`pip3.9 install -r requirements.txt`
