### ISSUE TITLE
两个功能

### ISSUE THREAD

**Issue by AlanMULI** [HibiKier/zhenxun_bot#260]
1.启动时只更新原神相关数据，其他抽卡功能的卡池都是上古卡池（？）
2.pixiv相关功能如何使用？我看到有配置文件里有配置反代，也去查了一下，但是仍然无法使用。
<img width="1464" alt="Screenshot 2022-05-18 at 19 54 46" src="https://user-images.githubusercontent.com/20946955/169032945-f985033d-68c3-47e2-bf2f-42c824ff097a.png">

**Comment by HibiKier** [comment]
上古卡池？卡池数据是根据bwiki自动更新的，功能使用方面参考文档

**Comment by AlanMULI** [comment]
> 

但是内容都是三月份的，使用文档里提供的指令也没有用处。

**Comment by Nova-Noir** [comment]
<html>
<body>
<ul style="padding-left: 1.2em; line-height: 2.2; color: rgb(36, 36, 36); font-family: Ubuntu, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="margin-top: 0px;"><strong style="font-weight: 600; margin-top: 0px;">超级用户指令</strong>：</li></ul>

指令 | 参数 | 示例 | 说明
-- | -- | -- | --
更新方舟信息 | None | None | 更新明日方舟数据信息
重载方舟卡池 | None | None | 更新明日方舟UP卡池
更新原神信息 | None | None | 更新原神数据信息
重载原神卡池 | None | None | 更新原神UP卡池
更新赛马娘信息 | None | None | 更新赛马娘数据信息
重载赛马娘卡池 | None | None | 更新赛马娘UP卡池
更新坎公骑冠剑信息 | None | None | 更新坎公骑冠剑数据信息
更新碧蓝航线信息 | None | None | 更新碧蓝航线数据信息
更新fgo信息 | None | None | 更新fgo数据信息
更新阴阳师信息 | None | None | 更新阴阳师数据信息


</body>
</html>

**Comment by AlanMULI** [comment]
<img width="1070" alt="Screenshot 2022-05-18 at 20 13 04" src="https://user-images.githubusercontent.com/20946955/169036068-025ef594-ee05-41e0-a63a-35f33a2aec03.png">
补充一个错误信息

**Comment by MingxuanGame** [comment]
> <img alt="Screenshot 2022-05-18 at 20 13 04" width="1070" src="https://user-images.githubusercontent.com/20946955/169036068-025ef594-ee05-41e0-a63a-35f33a2aec03.png">
> 
> 补充一个错误信息

see #196

**Comment by Nova-Noir** [comment]
方舟的等aya更新吧，改版了得重新爬
