### ISSUE TITLE
omega图库更新问题

### ISSUE THREAD

**Issue by macggg** [HibiKier/zhenxun_bot#262]
![5ZB$73Y{941W3O7TU}21NG5](https://user-images.githubusercontent.com/82862163/169034597-9701351e-654c-41a5-86de-cb8be403dd83.png)
开始检测后进程自动被kill

以及playwright貌似不支持centos有没有什么解决办法

**Comment by Nova-Noir** [comment]
怀疑是内存炸了被cent os kill了
