### ISSUE TITLE
这个uvicorn报错是怎么回事

### ISSUE THREAD

**Issue by woaoaj** [HibiKier/zhenxun_bot#264]
按照安装顺序走的，但是在playwright install chromium
playwright install-deps [chromium这两条时没出现安装进度条之类的也不知道安装成功没
![29FCYX6YHKWC~O~7B~_$ESQ](https://user-images.githubusercontent.com/105791979/169035699-8a72d542-37a9-44ac-a282-c1e12a0c1b1a.png)

然后运行bot到最后出现个error uvicorn报错，有大佬知道怎么回事嘛
![18 QF ER}`U60LQL49GO8~2](https://user-images.githubusercontent.com/105791979/169035847-34477877-482f-40f9-b97f-2ffca0261ce4.png)

**Comment by MingxuanGame** [comment]
可能是你的端口被占用了，试试换一个端口

**Comment by MingxuanGame** [comment]
可参考 #194 #208
