### ISSUE TITLE
关于invalid syntax的问题

### ISSUE THREAD

**Issue by Shimakazelewis** [HibiKier/zhenxun_bot#267]
![image](https://user-images.githubusercontent.com/99003751/169039989-c5ae5ac4-c4c3-464e-a1bd-886a751ff903.png)
没有动过代码，在运行时出现invalid syntax的问题，大佬们这个应该怎么解决？

**Comment by Nova-Noir** [comment]
requirements安装问题，这个jose是Python2的

**Comment by Nova-Noir** [comment]
使用`pip install python-jose`

**Comment by Shimakazelewis** [comment]
解决了，非常感谢！

**Comment by Nova-Noir** [comment]
如果问题已经解决的话，可以点击一下`Close`关闭这个Issue
