### ISSUE TITLE
识图的时候提示Saucenao 缺失API_KEY！

### ISSUE THREAD

**Issue by Natsumelan** [HibiKier/zhenxun_bot#269]
怎么解决

**Comment by Nova-Noir** [comment]
Saucenao 缺失API_KEY

**Comment by Nova-Noir** [comment]
根据文档，
`打开 configs/config.yaml，里面包含的是各种插件的配置项，填写完毕后重启真寻Bot`

**Comment by sblvbon** [comment]
申请API并填入，还能怎么办（

**Comment by MingxuanGame** [comment]
统一回答：

![image](https://user-images.githubusercontent.com/68982190/169551583-cdfbef6a-4609-40b8-bc0d-da708155e26b.png)

这里有个地址，注册后左边点 `api` 复制 api key

![image](https://user-images.githubusercontent.com/68982190/169552408-45d045b1-799b-4fdf-a15a-1d05a4585cc5.png)

填到这里

![image](https://user-images.githubusercontent.com/68982190/169552657-8a201f3a-a672-483d-90c3-f00080a01549.png)

`API_KEY` 冒号后面有空格！

**Comment by NathanSummer** [comment]
> 统一回答：
> 
> ![image](https://user-images.githubusercontent.com/68982190/169551583-cdfbef6a-4609-40b8-bc0d-da708155e26b.png)
> 
> 这里有个地址，注册后左边点 `api` 复制 api key
> 
> ![image](https://user-images.githubusercontent.com/68982190/169552408-45d045b1-799b-4fdf-a15a-1d05a4585cc5.png)
> 
> 填到这里
> 
> ![image](https://user-images.githubusercontent.com/68982190/169552657-8a201f3a-a672-483d-90c3-f00080a01549.png)
> 
> `API_KEY` 冒号后面有空格！

没法注册了现在
