### ISSUE TITLE
运行bot.py时的问题，我没啥基础，如果我没问清的话，大佬问啥我都会仔细回答，只求能解决问题，先谢过各位了（磕头）

### ISSUE THREAD

**Issue by kyi-wuc** [HibiKier/zhenxun_bot#271]
![图片](https://user-images.githubusercontent.com/105788280/169046145-832e7646-03fc-4cd8-861c-adf345d8bd7f.png)
![图片](https://user-images.githubusercontent.com/105788280/169046199-9c49db4a-1180-4f26-9cee-58de10fe009d.png)
如图，windows系统，文档中的步骤我全都照做了，端口用的5432

**Comment by borntree** [comment]
Duplicate of #256  是不是没进虚拟环境呢   里面有一条是我发的进虚拟环境再运行

**Comment by kyi-wuc** [comment]
> Duplicate of #256 是不是没进虚拟环境呢 里面有一条是我发的进虚拟环境再运行

poetry shell已运行，不运行shell的时候运行bot提示的是无nonebot.log

**Comment by MingxuanGame** [comment]
参考 #194 #208 配置数据库连接

**Comment by kyi-wuc** [comment]
![图片](https://user-images.githubusercontent.com/105788280/169051331-fe2527ab-4199-4269-89bf-7f0b5e3cf804.png)
![图片](https://user-images.githubusercontent.com/105788280/169051506-d61b6a5b-d532-4924-9d74-4ff20d6bd762.png)
请问我这样配置是对的么，数据库密码是postgresql安装时候设置的密码么？如果是的话那数据库密码也无误
![图片](https://user-images.githubusercontent.com/105788280/169051743-5c5c99e8-28d2-40aa-8c48-ade2740ff648.png)
![图片](https://user-images.githubusercontent.com/105788280/169051775-0473c3a4-5fc5-472e-bb20-09be59393c1a.png)
仍然报错

**Comment by LEorEu** [comment]
看看你数据库的角色权限

**Comment by kyi-wuc** [comment]
![图片](https://user-images.githubusercontent.com/105788280/169052371-c5a5381d-580b-4e9f-a832-9e6b543a287c.png)
admin权限全开

**Comment by LEorEu** [comment]
> ![图片](https://user-images.githubusercontent.com/105788280/169052371-c5a5381d-580b-4e9f-a832-9e6b543a287c.png) admin权限全开

重启一下pgsql试试呢

**Comment by kyi-wuc** [comment]
windows请问是在这里重启pgsql么
![图片](https://user-images.githubusercontent.com/105788280/169053717-24b5c9b1-92fa-4143-abbe-4a0540430474.png)
如果是的话，那么问题仍然没有解决
![图片](https://user-images.githubusercontent.com/105788280/169053834-f24dd6b3-999d-410c-9d86-85a3c806ac49.png)
![图片](https://user-images.githubusercontent.com/105788280/169053884-6ea41506-4c0b-4b34-ab44-a049a68f9eed.png)

**Comment by SuLeheng** [comment]
大佬，我跟你遇到的一样的问题

**Comment by YancyGuo** [comment]
> 大佬，我跟你遇到的一样的问题

整了一晚上没查出问题,有解决办法了quote我一下

**Comment by kyi-wuc** [comment]
发现一个现象，我不太懂，拿出来问问是怎么导致的
![图片](https://user-images.githubusercontent.com/105788280/169241097-fc7d632e-8a3c-4aa9-aa62-50474942339e.png)
![图片](https://user-images.githubusercontent.com/105788280/169241140-a3e9e831-2145-4253-9c5e-0b5cd4ad0c81.png)
我随便输入一个端口的时候，报错就成了这样了，跟5432端口的报错不一样，这是为什么

**Comment by HibiKier** [comment]
> 发现一个现象，我不太懂，拿出来问问是怎么导致的 ![图片](https://user-images.githubusercontent.com/105788280/169241097-fc7d632e-8a3c-4aa9-aa62-50474942339e.png) ![图片](https://user-images.githubusercontent.com/105788280/169241140-a3e9e831-2145-4253-9c5e-0b5cd4ad0c81.png) 我随便输入一个端口的时候，报错就成了这样了，跟5432端口的报错不一样，这是为什么

因为你这端口没数据库这服务

**Comment by HibiKier** [comment]
> windows请问是在这里重启pgsql么 ![图片](https://user-images.githubusercontent.com/105788280/169053717-24b5c9b1-92fa-4143-abbe-4a0540430474.png) 如果是的话，那么问题仍然没有解决 ![图片](https://user-images.githubusercontent.com/105788280/169053834-f24dd6b3-999d-410c-9d86-85a3c806ac49.png) ![图片](https://user-images.githubusercontent.com/105788280/169053884-6ea41506-4c0b-4b34-ab44-a049a68f9eed.png)

这里检查你数据库配置是否正确，比如数据库是否已经创建,config.py是否填写正确之类的

**Comment by kyi-wuc** [comment]
> > windows请问是在这里重启pgsql么 ![图片](https://user-images.githubusercontent.com/105788280/169053717-24b5c9b1-92fa-4143-abbe-4a0540430474.png) 如果是的话，那么问题仍然没有解决 ![图片](https://user-images.githubusercontent.com/105788280/169053834-f24dd6b3-999d-410c-9d86-85a3c806ac49.png) ![图片](https://user-images.githubusercontent.com/105788280/169053884-6ea41506-4c0b-4b34-ab44-a049a68f9eed.png)
> 
> 这里检查你数据库配置是否正确，比如数据库是否已经创建,config.py是否填写正确之类的

![图片](https://user-images.githubusercontent.com/105788280/169254079-5b41c883-8352-470d-b65d-e222d2bf784a.png)
![图片](https://user-images.githubusercontent.com/105788280/169254151-de5c0ca9-b895-4209-ab7b-52aa3c543227.png)
所有文档里提到的步骤我都更改了，放在这两张图里了，麻烦大佬看一下我哪里不对

**Comment by kyi-wuc** [comment]
> > windows请问是在这里重启pgsql么 ![图片](https://user-images.githubusercontent.com/105788280/169053717-24b5c9b1-92fa-4143-abbe-4a0540430474.png) 如果是的话，那么问题仍然没有解决 ![图片](https://user-images.githubusercontent.com/105788280/169053834-f24dd6b3-999d-410c-9d86-85a3c806ac49.png) ![图片](https://user-images.githubusercontent.com/105788280/169053884-6ea41506-4c0b-4b34-ab44-a049a68f9eed.png)
> 
> 这里检查你数据库配置是否正确，比如数据库是否已经创建,config.py是否填写正确之类的

![图片](https://user-images.githubusercontent.com/105788280/169254079-5b41c883-8352-470d-b65d-e222d2bf784a.png)
![图片](https://user-images.githubusercontent.com/105788280/169254151-de5c0ca9-b895-4209-ab7b-52aa3c543227.png)
所有文档里提到的步骤我都更改了，放在这两张图里了，麻烦大佬看一下我哪里不对

**Comment by HibiKier** [comment]
把用户改成 postgres呢，密码也改成对应的

**Comment by kyi-wuc** [comment]
> 把用户改成 postgres呢，密码也改成对应的

解决了，十分感谢（磕头）
