### ISSUE TITLE
一个时常出现的报错，求助

### ISSUE THREAD

**Issue by zhong946555** [HibiKier/zhenxun_bot#273]
![image](https://user-images.githubusercontent.com/61000018/169052319-850c1c19-e10c-42c5-af72-92628e3b1111.png)
在使用pix功能时出现的，另外在更新pix关键词时也出现搜索错误的提示
![image](https://user-images.githubusercontent.com/61000018/169052491-ad95b28a-2241-4a77-8207-b079af364740.png)

**Comment by HibiKier** [comment]
似乎是网络问题
