### ISSUE TITLE
麻烦问下，识图功能报以下错误是咋回事，是go-cqhttp版本不对吗？

### ISSUE THREAD

**Issue by qiuyang163** [HibiKier/zhenxun_bot#275]
![image](https://user-images.githubusercontent.com/8520472/169057927-b06225d0-e36f-49a8-a5cd-98cc6906ff44.png)

**Comment by MingxuanGame** [comment]
请参考 go-cqhttp  的输出

大概率是被风控了

**Comment by qiuyang163** [comment]
@MingxuanGame go-cqhttp没有任何输出，bot回复未在图库中找到与 xxx 相关Tag/UID/PID的图片...

**Comment by MingxuanGame** [comment]
> @MingxuanGame go-cqhttp没有任何输出，bot回复未在图库中找到与 xxx 相关Tag/UID/PID的图片...

你贴一下你的 go-cqhttp 日志

**Comment by qiuyang163** [comment]
![image](https://user-images.githubusercontent.com/8520472/169061589-a69e614d-93c6-49dc-a515-3e34d8364a9e.png)
如图

**Comment by MingxuanGame** [comment]
see #165
