### ISSUE TITLE
linux配置go-cqhttp运行弹出二维码，手机扫完后提示扫码失败，已失效或存在异常，这个咋解决

### ISSUE THREAD

**Issue by Mujids** [HibiKier/zhenxun_bot#276]

**Comment by VanLewis2003** [comment]
这个百度是能找得到的

**Comment by Mujids** [comment]
> 提供一个办法 下载windows版本，在自己电脑上扫码登录，将生成的device.json文件上传到服务器相应位置即可运行 具体可参考https://blog.csdn.net/yxn4065/article/details/124355637

这个下午的时候试过，不行，还是需要扫码登陆，扫码后直接跳到下载qq的页面了，直接黑人问号

**Comment by LEorEu** [comment]
我是更新了手机QQ的app后可以扫码了

**Comment by Kanase** [comment]
> > 提供一个办法 下载windows版本，在自己电脑上扫码登录，将生成的device.json文件上传到服务器相应位置即可运行 具体可参考https://blog.csdn.net/yxn4065/article/details/124355637
> 
> 这个下午的时候试过，不行，还是需要扫码登陆，扫码后直接跳到下载qq的页面了，直接黑人问号

我这边也碰到这个问题，我的办法是把device.json和在win登录成功后的token一起上传到服务器，然后就能启动go-cqhttp了
