### ISSUE TITLE
装依赖包的时候包这个错怎么处理啊

### ISSUE THREAD

**Issue by nertcy** [HibiKier/zhenxun_bot#279]
![image](https://user-images.githubusercontent.com/94539226/169063139-656c3052-4bee-4d2d-924a-4c6407f0e0cc.png)
本地win11，在安装Python3.8.10的时候在cmt安装了nb-cli

**Comment by MingxuanGame** [comment]
超时了

尝试使用[清华镜像源](https://mirrors.tuna.tsinghua.edu.cn/help/pypi/)

**Comment by HibiKier** [comment]
按顺序执行

**Comment by nertcy** [comment]
> 按顺序执行

太感谢你了，大佬，请收下我的膝盖

**Comment by nertcy** [comment]
> 按顺序执行

https://github.com/HibiKier/zhenxun_bot/issues/279#issuecomment-1130102537抱歉还想在咨询一下，最后一个好像无法安装，是重复安装倒置的呢还是怎么回事了，谢谢

**Comment by HibiKier** [comment]
> > 按顺序执行
> 
> ![image](https://user-images.githubusercontent.com/94539226/169072585-24a94a40-cd37-435e-b87b-1017f93afb64.png) 抱歉还想在咨询一下，最后一个好像无法安装，是重复安装倒置的呢还是怎么回事了，谢谢

暂时不用管
