### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by gqcdm** [HibiKier/zhenxun_bot#280]
![image](https://user-images.githubusercontent.com/78142321/169063350-b37d78f2-04f3-4f3e-aca9-41d73798e12c.png)

**Comment by Arturia169** [comment]
同问

**Comment by gqcdm** [comment]
> 检查一下是否存在 `pyproject.toml`

![image](https://user-images.githubusercontent.com/78142321/169178256-b43c07b0-7268-4bc4-b574-50d1143e0dc1.png)
我直接使用git clone克隆下来打开文件夹执行的`sudo poetry install`

**Comment by HibiKier** [comment]
。。现在不建议使用clone

**Comment by gqcdm** [comment]
> 

哈哈哈，不重要了
