### ISSUE TITLE
文档里的超级用户帮助指令没反应

### ISSUE THREAD

**Issue by woaoaj** [HibiKier/zhenxun_bot#281]
怎么添加超级用户还有提高群权限？
文档里的指令无效...
![4W%@C(`J{9XEV`2MM)C$EUW](https://user-images.githubusercontent.com/105791979/169063825-af161682-598f-4895-8cf1-e9f1a36613df.png)
![T6GVVYVKK}9(11 `(`~SQMB](https://user-images.githubusercontent.com/105791979/169063932-ea3e243b-306b-4ccd-984d-a4259ad96518.png)

**Comment by MingxuanGame** [comment]
你是怎么发送的消息

**Comment by sblvbon** [comment]
不发日志怎么解决？

**Comment by woaoaj** [comment]
@真寻 超级用户帮助
和
@真寻 添加权限 @对象 5

**Comment by MingxuanGame** [comment]
只需要 `真寻` 即可

不需要 @

**Comment by woaoaj** [comment]
![IO4_YNKFEUM`ZG}LD@7}VNL](https://user-images.githubusercontent.com/105791979/169066916-c1af42c8-a1c2-4e7a-ab62-e261e7ea1c64.png)
......

**Comment by woaoaj** [comment]
是我没开什么功能吗

**Comment by HibiKier** [comment]
你env配置自己超级用户了吗

**Comment by woaoaj** [comment]
哦哦我env设成真寻了，感谢！
