### ISSUE TITLE
安装依赖出现这个错误 实在是解决不了了

### ISSUE THREAD

**Issue by tanging22** [HibiKier/zhenxun_bot#282]
![image](https://user-images.githubusercontent.com/105801295/169064960-16688f69-3d06-4728-bd2b-ce5355381dcb.png)

**Comment by MingxuanGame** [comment]
截图截全一点

**Comment by tanging22** [comment]
> 



> 截图截全一点
![image](https://user-images.githubusercontent.com/105801295/169066220-c39ec26c-33b3-4761-b5bc-2e8a487d0190.png)
这样的

**Comment by tanging22** [comment]
> 



> 应该是没关VPN，我之前也这样，关了就好了

我代理在路由器上 服务器是腾讯云呀有影响的嘛

**Comment by EvanFried** [comment]
python版本换成3.9，我之前3.10安装也报这个，安装不全

**Comment by 11Moyan7** [comment]
楼主解决了吗，我换成3.9版本也还是这个问题

**Comment by tanging22** [comment]
> 楼主解决了吗，我换成3.9版本也还是这个问题

依赖解决了 又遇到新问题

**Comment by 11Moyan7** [comment]
> 
![image](https://user-images.githubusercontent.com/105837174/169203766-f63d49f8-d6b7-4368-9890-5d45ad4237a8.png)

我还是这个问题（哭）

**Comment by tanging22** [comment]
> ![image](https://user-images.githubusercontent.com/105837174/169203766-f63d49f8-d6b7-4368-9890-5d45ad4237a8.png)
> 
> 我还是这个问题（哭）

在项目根目录里面执行cmd

**Comment by tanging22** [comment]
![B883F2B2-B481-4F67-8910-23C0DFA947E7](https://user-images.githubusercontent.com/105801295/169204903-dc3bb849-38ad-4e4a-8bd1-278254067335.png)我现在依赖好了 启动不了 还是出问题 我也解决不了

**Comment by 11Moyan7** [comment]
> 

这一步解决了，谢谢

**Comment by HibiKier** [comment]
> ![B883F2B2-B481-4F67-8910-23C0DFA947E7](https://user-images.githubusercontent.com/105801295/169204903-dc3bb849-38ad-4e4a-8bd1-278254067335.png)我现在依赖好了 启动不了 还是出问题 我也解决不了

你poetry shell都没输没进虚拟环境肯定启动不了
