### ISSUE TITLE
bilibili_sub添加订阅主播房间号与主播名称对不上。

### ISSUE THREAD

**Issue by Ashtarlia** [HibiKier/zhenxun_bot#284]
使用bilibili_sub订阅主播之后，显示的名字是将房间号作为uid对应的名称。
栗：
添加订阅主播 3394945  #订阅叔叔直播间

bot：
已成功订阅主播：
	title：用户208259的直播间
	name： DEBU斌
	live_id：3394945
	uid：208259
——————————————————
房间号与uid显示正确，然而，名称显示的确实uid为：3394945的人。
同样 查询订阅与开播之后，显示的名称都是为UID为3394945的人。而不是房间号为3394945，UID为208259的叔叔。
这让我作为一个叔叔单推人很为难（
难道是我的配置出现了问题？导致定向错误吗？

**Comment by HibiKier** [comment]
Fix wrong live streamer name [@pull/284](https://github.com/HibiKier/zhenxun_bot/pull/284)
