### ISSUE TITLE
数据库连接错误怎么办？

### ISSUE THREAD

**Issue by EDXPRE233** [HibiKier/zhenxun_bot#285]
![image](https://user-images.githubusercontent.com/105802491/169068917-942ac652-16fb-4bf1-8585-8e5d4695b6c2.png)

**Comment by EDXPRE233** [comment]
> #194
无论我如何修改数据库名称，数据库用户和配置文件，尽管他们一致，我还无法成功连接

**Comment by EDXPRE233** [comment]
![image](https://user-images.githubusercontent.com/105802491/169088852-48dc1c39-9a29-44b3-b2a0-0a61dd66fe24.png)


> #194
![image](https://user-images.githubusercontent.com/105802491/169088893-606ecf5e-fb8d-4b36-9e84-d15b139d8296.png)

**Comment by HibiKier** [comment]
你config.py配置咋写的

**Comment by EDXPRE233** [comment]
> 你 config.py 配置咋写的
![image](https://user-images.githubusercontent.com/105802491/169296954-f4a7fa1a-bb94-45bb-8581-c2e09e2c96ce.png)
