### ISSUE TITLE
请求添加批量上传图片至图库

### ISSUE THREAD

**Issue by VCE1** [HibiKier/zhenxun_bot#29]
上传图片，每次只能上传一张图片，而且要确认上传到什么图库过于繁琐。希望加一个批量上传的指令，输入指令就结束上传，再添加一个指定默认的图库命令。这样能方便许多。

**Comment by HibiKier** [comment]
上传图片是可以多图上传的啊，比如：上传图片美图 [图片] [图片] [图片]，不过上传图片在release最新包中有已知bug，需要在plugins/upload_img/__init__.py第58行改为    path = IMAGE_PATH + cn2py(state["path"]) + '/'

**Comment by VCE1** [comment]
这个适用于pc端，不是很适用于手机端。因为手机qq只有最近浏览栏的图片可以与指令一起发送，点进相册选择的图片却不行，不能和指令一块发送。

**Comment by HibiKier** [comment]
噢噢，好的，会添加该操作
