### ISSUE TITLE
运行Postgresql安装程序出错！

### ISSUE THREAD

**Issue by xxr777** [HibiKier/zhenxun_bot#293]
![F4E BO69O5Q_`_F3YLG`L(N](https://user-images.githubusercontent.com/105805521/169080725-1b2df194-db64-49b6-8bff-8f04839f5a62.png)
如图，系统WIN11  运行安装程序后就这样

**Comment by HibiKier** [comment]
不要有中文路径

**Comment by EvanFried** [comment]
我下载了低版本的Postgresql解决的，高版本也是报这个错
