### ISSUE TITLE
寻问下如何更改默认的权限设置，比如群聊禁用r18

### ISSUE THREAD

**Issue by Dimension-luo** [HibiKier/zhenxun_bot#296]
首先谢谢作者提供的机器人老婆（
部署了真寻和几个朋友在小群玩，所以寻问下如何更改群聊被ban掉的r18和磁力搜索的权限，能够直接在群聊中使用

**Comment by HibiKier** [comment]
写死了，需要改代码

**Comment by HibiKier** [comment]
bt文件夹和send_setu_文件夹

**Comment by Dimension-luo** [comment]
哦哦找到了，改好了，谢谢啦

**Comment by lonelyenderman233** [comment]
借楼问一下，请问大佬是怎么更改的，我也想启用群聊功能

**Comment by HibiKier** [comment]
> 借楼问一下，请问大佬是怎么更改的，我也想启用群聊功能

GroupMessageEvent改成PrivateMessageEvent之类的

**Comment by 1033022842** [comment]
大佬，改成PrivateMessageEvent后发送图片的时候报错了鸭，'PrivateMessageEvent' object has no attribute 'group_id'
