### ISSUE TITLE
启动bot失败，模块缺失问题

### ISSUE THREAD

**Issue by VanLewis2003** [HibiKier/zhenxun_bot#298]
![屏幕截图 2022-05-19 000103](https://user-images.githubusercontent.com/93692468/169088968-bae9b3ef-e2fc-4ecb-aded-a8dbb78249d5.png)
安装完依赖进入环境，运行bot时出现以上反馈，不知道这个services也算依赖吗？
参考过其他帖子了，暂时没有找到有效的方法。

**Comment by MingxuanGame** [comment]
services 与 bot.py 在同一级

你应该 `ls` 查看一下当前文件夹内容

**Comment by VanLewis2003** [comment]
已解决，感谢
