### ISSUE TITLE
启动python3 bot.py失败 解析失败直接被终止

### ISSUE THREAD

**Issue by lhr9645** [HibiKier/zhenxun_bot#299]
![Uploading IMG_20220519_000525.jpg…]()
解析失败直接被终止 我见别人还能跑下去的啊 求助 怎么破？

**Comment by MingxuanGame** [comment]
你图没发上来

**Comment by lhr9645** [comment]
![Uploading IMG_20220519_000525.jpg…]()

**Comment by MingxuanGame** [comment]
如果你连接 GitHub 的网络不佳

请尝试使用第三方图床

**Comment by lhr9645** [comment]
![Uploading IMG_20220519_000525.jpg…]()

**Comment by lhr9645** [comment]
https://sukiio.com/i/2022/05/19/d5vb1.jpg

**Comment by MingxuanGame** [comment]
see #234

**Comment by lhr9645** [comment]
谢谢老哥 解决了！！！
