### ISSUE TITLE
关于群权限的一个建议

### ISSUE THREAD

**Issue by yusana213214** [HibiKier/zhenxun_bot#30]
最近碰到一个问题，就是我把A群权限设置为1屏蔽绝大部分功能，会有群友恶作剧不断尝试调用指令，机器人频繁回复[所权限不足]的提示，影响了部分群友的水群体验。还是说对于屏蔽插件功能我的操作不对

给个建议
建议当该群被屏蔽绝大部分功能时，只有权限＞5的用户尝试触发是发送反馈信息，普通群员触发则直接不回复反馈信息

另外，大佬怎么把自己写的插件添加进真寻的帮助图片和权限控制插件里面啊，之前尝试添加启动控制台直接报错了

**Comment by HibiKier** [comment]
群权限不足提示是有cd的，默认为60秒，需要修改的话在plugins/group_level/__init__.py第21行，未来应该会加入至config.py配置，该建议也可以考虑。

权限控制在configs/configs.py中第122行的字典中添加即可：
```python
admin_plugins_auth = {
    '模块名称'(str): 权限等级（int）
}
```
帮助的话是在plugins/help/configs.py中，在对应的字典中添加：
```python
{
    '模块名称'(str): '介绍以及指令' (str)
}
```
报错的话具体的报错请截图，不能闭眼开车

**Comment by yusana213214** [comment]
> 群权限不足提示是有cd的，默认为60秒，需要修改的话在plugins/group_level/**init**.py第21行，未来应该会加入至config.py配置，该建议也可以考虑。
> 
> 权限控制在configs/configs.py中第122行的字典中添加即可：
> 
> ```python
> admin_plugins_auth = {
>     '模块名称'(str): 权限等级（int）
> }
> ```
> 
> 帮助的话是在plugins/help/configs.py中，在对应的字典中添加：
> 
> ```python
> {
>     '模块名称'(str): '介绍以及指令' (str)
> }
> ```
> 
> 报错的话具体的报错请截图，不能闭眼开车

我等这边事情处理完以后看看
