### ISSUE TITLE
24点钟的晚安提醒和开箱刷新提醒会连续发两次

### ISSUE THREAD

**Issue by railannad** [HibiKier/zhenxun_bot#300]
![image](https://user-images.githubusercontent.com/36919867/169090950-6e79a415-c5e1-43aa-983c-1dc0e66cdcee.png)
![image](https://user-images.githubusercontent.com/36919867/169090963-76c94abf-1f2b-4c7d-b1ca-47883c0adadc.png)

用conda创建了个python3.8.0环境装的，在.env.dev中开启debug能查出来原因吗（

顺便问一下用saucenao搜图，4秒钟才返回结果，这个性能正常吗？ 因为鲁迅说在1秒内就返回了结果，这个差异甚至让我怀疑搜图里主动限制了速度。

**Comment by HibiKier** [comment]
发两次可能是bug，图片方面需要并不是所有图片回复都调用了api，大部分是本地pil实现的

**Comment by MingxuanGame** [comment]
> 所以大部分开销是花在了网络传输上了吗

是的

**Comment by HibiKier** [comment]
和py版本无关，也许是代码问题，虽然我并没有出现重复发的问题

**Comment by MingxuanGame** [comment]
https://github.com/HibiKier/zhenxun_bot/blob/7dd68cf1ef13740ba022f2d1405ed475a20894a1/plugins/open_cases/utils.py#L265-L269

发两次可能是 go-cqhttp 那边的返回问题
