### ISSUE TITLE
风控问题怎么解决

### ISSUE THREAD

**Issue by chara1051** [HibiKier/zhenxun_bot#301]
![Uploading Screenshot_20220519_001653_com.microsoft.rdc.android.jpg…]()

**Comment by chara1051** [comment]
> 

多挂几天有用吗？

**Comment by MingxuanGame** [comment]
> 多挂几天有用吗？

有用的

**Comment by chara1051** [comment]
> > 多挂几天有用吗？
> 
> 有用的

更换之后还是风控
