### ISSUE TITLE
pix的Omega图库导入卡住了怎么办

### ISSUE THREAD

**Issue by inkbloom** [HibiKier/zhenxun_bot#303]
如题 卡死在这了
![NVIDIA_Share_gXwkB2duuY](https://user-images.githubusercontent.com/45934514/169094943-2e3657ec-47f5-4ebb-94f4-de42bb76d0f8.png)

**Comment by woaoaj** [comment]
这个图库在哪里下的？文档里的omega图库网址打不开

**Comment by inkbloom** [comment]
> 这个图库在哪里下的？文档里的omega图库网址打不开

PIX插件介绍里有提

**Comment by HibiKier** [comment]
啥意思，看看日志

**Comment by inkbloom** [comment]
> 啥意思，看看日志
![NVIDIA_Share_Z1lq5Sdlkj](https://user-images.githubusercontent.com/45934514/169211714-6a8777f8-dcf7-4db7-9f4e-099c1ef29e96.png)
![NVIDIA_Share_gCeKQOspnf](https://user-images.githubusercontent.com/45934514/169211722-363a895f-3edf-4c9b-8c91-89d6224eaced.png)

**Comment by inkbloom** [comment]
> 啥意思，看看日志
就大佬的图库是gkb编码  但我导入的时候是utf8 试了网上很多种设置方法都没法成功

**Comment by HibiKier** [comment]
你新建数据库的时候有自己操作别的东西吗，并没有遇到过这样的问题

**Comment by inkbloom** [comment]
> 你新建数据库的时候有自己操作别的东西吗，并没有遇到过这样的问题

安装的时候吗 就选了语言选了c  建的数据库都是按安装文档里的来的

**Comment by inkbloom** [comment]
> 你新建数据库的时候有自己操作别的东西吗，并没有遇到过这样的问题

用来restore的表的话 只命了名 别的都是默认设置

**Comment by HibiKier** [comment]
> > 你新建数据库的时候有自己操作别的东西吗，并没有遇到过这样的问题
> 
> 用来restore的表的话 只命了名 别的都是默认设置

命了名？你是自己手动建的表？
