### ISSUE TITLE
机器人对命令无反应

### ISSUE THREAD

**Issue by JuuiceP** [HibiKier/zhenxun_bot#304]
如题，只会智障回复，插件不起作用
超级用户帮助 无反应
搜图无反应 色图无反应 所有插件都无反应，只会智障回复

![QQ截图20220519003733](https://user-images.githubusercontent.com/90129856/169096363-7ea3b1b9-c9d5-4a56-a541-ff8fd1605636.png)
![QQ截图20220519003943](https://user-images.githubusercontent.com/90129856/169096373-6cb1afb2-4fb4-412c-8fc0-25e27feb7c75.png)
![QQ截图20220519004038](https://user-images.githubusercontent.com/90129856/169096489-556d7c89-bd98-4592-8314-3bb9ee3e958a.png)

**Comment by MingxuanGame** [comment]
请问，是否设置超级用户

**Comment by woaoaj** [comment]
env里超级用户填自己的大号，我刚刚也是填了机器人的号导致没反应

**Comment by JuuiceP** [comment]
![QQ截图20220519005459](https://user-images.githubusercontent.com/90129856/169099284-27cd6543-df23-4103-8d1a-b0c6ae7e2e41.png)
没填错
