### ISSUE TITLE
导入Omega库并调整完比例配置项后，使用pix指令会出错

### ISSUE THREAD

**Issue by yozorachan** [HibiKier/zhenxun_bot#306]
![image](https://user-images.githubusercontent.com/105808870/169098577-c46a284c-0762-426a-b1ed-b94e1c5a9133.png)
![image](https://user-images.githubusercontent.com/105808870/169098743-44039ab4-e9b3-47f8-8f77-05b3f7897d6f.png)

**Comment by HibiKier** [comment]
可能需要代理
