### ISSUE TITLE
为何bot的识番和trace的识别不相同？

### ISSUE THREAD

**Issue by Saukurs** [HibiKier/zhenxun_bot#309]
![QQ截图20220519011850](https://user-images.githubusercontent.com/105751058/169103586-90f478e7-cf61-4933-bf51-1eb32696cac0.png)
我看了一下模块的py文件应该用的是trace的api啊

**Comment by HibiKier** [comment]
呃，周末再看看，如果api返回的结果还是不通也没办法了捏

**Comment by Saukurs** [comment]
> 呃，周末再看看，如果api返回的结果还是不通也没办法了捏

谢谢了捏

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169643422-60feff6a-090a-4cc0-a158-323e57d618ac.png)
大概率是你黑边导致的

**Comment by Saukurs** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169643422-60feff6a-090a-4cc0-a158-323e57d618ac.png)
> 大概率是你黑边导致的

好的感谢，我测试后发现识图和识番都是如此(丢人
