### ISSUE TITLE
很多指令不生效，而且它还骂我

### ISSUE THREAD

**Issue by TiAmoJIA** [HibiKier/zhenxun_bot#310]
已经成功使用，但是我添加群和原神绑定等许多功能都无法实现，插件我在webui上看是开着的
![Screenshot_20220519_012247_com tencent mobileqq](https://user-images.githubusercontent.com/91871280/169104120-dabfe13d-67d2-4154-bf94-52bbbd60db81.jpg)

**Comment by TiAmoJIA** [comment]
请问有大佬能帮助我嘛，还有个问题是戳一戳本来会发送个图片，但没有发送，go-chttp后台是这样报错的
![16528946348978256311108580466374](https://user-images.githubusercontent.com/91871280/169104436-4d1f4256-0712-403c-ab7f-f54681c2282e.jpg)

**Comment by TiAmoJIA** [comment]
超级管理员权限大概解决了，是我输账号的时候小键盘问题9没输进去，抱歉，其他插件仍在摸索

**Comment by HibiKier** [comment]
请查看插件是否成功加载没有报错，戳一戳是发送 语音/图片 二选一，建议删除resources/record文件夹重新上传

**Comment by TiAmoJIA** [comment]
> 请查看插件是否成功加载没有报错，戳一戳是发送 语音/图片 二选一，建议删除resources/record文件夹重新上传

查看了下，record里面的文件确实都变成乱码且打不开了，蟹蟹

**Comment by Myanswerdy** [comment]
大佬帮我看看这是什么情况
![WSW4 _2FDC87D0 K9E194D](https://user-images.githubusercontent.com/74899308/210808841-734f63be-ab1b-482d-b3f2-db862aacd484.png)

**Comment by Azusa-mikan** [comment]
难绷
