### ISSUE TITLE
安装依赖时找不到pyproject.toml怎么办

### ISSUE THREAD

**Issue by alan22056** [HibiKier/zhenxun_bot#311]
![image](https://user-images.githubusercontent.com/105813229/169106228-adb3b870-be2b-49fe-bcf1-4c09bc950e3f.png)

**Comment by akademeia** [comment]
你的路径不是bot的那个文件夹吧

**Comment by HibiKier** [comment]
进bot文件夹再输命令

**Comment by xcf1127** [comment]
![CK~FYRI0M8J81($U9U0RMVO](https://user-images.githubusercontent.com/105791636/169211208-781fc0f0-5696-46b8-a317-e20fe7a5d668.png)
大佬们，我这种情况是怎么回事阿

**Comment by HibiKier** [comment]
> ![CK~FYRI0M8J81($U9U0RMVO](https://user-images.githubusercontent.com/105791636/169211208-781fc0f0-5696-46b8-a317-e20fe7a5d668.png) 大佬们，我这种情况是怎么回事阿

python -m poetry install
你前面都加个python -m试试
