### ISSUE TITLE
获取 browser 失败，请部署至 linux 环境

### ISSUE THREAD

**Issue by gongjing666** [HibiKier/zhenxun_bot#313]
这玩意咋解决，而且我的pixiv排行和到点了，还有游戏资源更新都报错咋整

**Comment by gongjing666** [comment]
没反应

**Comment by gongjing666** [comment]
945] "p搜 98440891"
05-19 08:39:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-19 08:39:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-19 08:39:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
05-19 08:39:28 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-19 08:39:28 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
05-19 08:39:28 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-19 08:39:28 [INFO] nonebot | Event will be handled by <Matcher from plugins.pid_search, type=message, priority=5, temp=False>
05-19 08:39:43 [ERROR] utils | 下载 https://i.pximg.net/img-original/img/2022/05/19/00/12/10/98440891_p0.jpg 未知错误 <class 'httpx.ConnectError'>：All connection attempts failed.. Path：/home/zhenxun_bot-main/resources/image/temp/pid_search_3031379629.png
05-19 08:39:43 [INFO] nonebot | Matcher <Matcher from plugins.pid_search, type=message, priority=5, temp=False> running complete

**Comment by gongjing666** [comment]
代理咋整，自己搭建梯子？

**Comment by gongjing666** [comment]
不是 发送色图能下载pixiv，但是p搜就不行

**Comment by gongjing666** [comment]
https://i.pixiv.re/img-original/img/2010/04/30/22/53/02/10345855_p0.jpg这个是发生色图的下载连接
https://i.pximg.net/img-original/img/2014/07/01/19/48/53/44437404_p0.jpg这是p搜的下载连接
域名换一下p搜的连接就能显示

**Comment by HibiKier** [comment]
会在后续完善替换域名

**Comment by gongjing666** [comment]
行吧

**Comment by gongjing666** [comment]
05-19 08:59:14 [ERROR] nonebot | Running matcher <Matcher from plugins.search_anime, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "/home/zhenxun_bot-main/bot.py", line 20, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/zhenxun_bot-main/plugins/search_anime/__init__.py", line 47, in _
    anime_report = await from_anime_get_info(
  File "/home/zhenxun_bot-main/plugins/search_anime/data_source.py", line 18, in from_anime_get_info
    repass.insert(0, f"搜索 {key_word} 结果（耗时 {int(time.time() - s_time)} 秒）：\n")
AttributeError: 'str' object has no attribute 'insert'

这是搜番报的错，这咋解决

**Comment by HibiKier** [comment]
> 05-19 08:59:14 [ERROR] nonebot | Running matcher <Matcher from plugins.search_anime, type=message, priority=5, temp=False> failed. Traceback (most recent call last): File "/home/zhenxun_bot-main/bot.py", line 20, in nonebot.run() File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/**init**.py", line 258, in run get_driver().run(*args, **kwargs) File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 168, in run uvicorn.run( File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run server.run() File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "/usr/local/python3/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 153, in _check_matcher await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> 
> > File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 202, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
> > await handler(
> > File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-xRHTbRVY-py3.9/lib/python3.9/site-packages/nonebot/dependencies/**init**.py", line 92, in **call**
> > return await self.call(**values)
> > File "/home/zhenxun_bot-main/plugins/search_anime/**init**.py", line 47, in _
> > anime_report = await from_anime_get_info(
> > File "/home/zhenxun_bot-main/plugins/search_anime/data_source.py", line 18, in from_anime_get_info
> > repass.insert(0, f"搜索 {key_word} 结果（耗时 {int(time.time() - s_time)} 秒）：\n")
> > AttributeError: 'str' object has no attribute 'insert'
> 
> 这是搜番报的错，这咋解决

没找到番剧可能报这错

**Comment by HibiKier** [comment]
该问题已修复

**Comment by TianMing013** [comment]
> 该问题已修复

docker出现这个问题呢
