### ISSUE TITLE
pgAdmin4注册服务器

### ISSUE THREAD

**Issue by StarChaserX** [HibiKier/zhenxun_bot#315]
![image](https://user-images.githubusercontent.com/71445929/169184031-376f0f59-5865-4003-80c6-779ad4145500.png)
我这个直接不让保存了，有没有大佬知道为什么，感谢了

**Comment by eENmame** [comment]
主机名称地址改127.0.0.1试试

**Comment by eENmame** [comment]
> > ![image](https://user-images.githubusercontent.com/68982190/169186389-f293c174-d45c-4be2-a9a2-14e5b387c439.png) 检查一下这个服务是否开启
> 
> ![image](https://user-images.githubusercontent.com/71445929/169187160-5118bf46-49c4-4508-bdd2-8d2df3612783.png) 我这离好像没有这个服务，我是不是安装的时候出问题了

如果改地址还是不行就卸载重装

**Comment by eENmame** [comment]
> > > ![image](https://user-images.githubusercontent.com/68982190/169186389-f293c174-d45c-4be2-a9a2-14e5b387c439.png) 检查一下这个服务是否开启
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/71445929/169187160-5118bf46-49c4-4508-bdd2-8d2df3612783.png) 我这离好像没有这个服务，我是不是安装的时候出问题了
> 
> 如果改地址还是不行就卸载重装

我就是这样的，先把你那个主机名称/地址改成127.0.0.1

**Comment by StarChaserX** [comment]
> 

管理员运行也一样，所以我现在重装一下这个

**Comment by StarChaserX** [comment]
> 应该是安装出现问题了，试着以`管理员身份运行`，然后 `Locate` 那里不用动即可

![image](https://user-images.githubusercontent.com/71445929/169192075-8de48547-11a3-4d76-9979-3ba767c8deed.png)
我重新安装后就出现这个问题了
![image](https://user-images.githubusercontent.com/71445929/169192107-4d5a91ea-dc20-420e-9d1b-810f1bb74dfa.png)
这个我也重启了，pgadmin4也是用管理员打开的，大佬这个怎么办啊

**Comment by MingxuanGame** [comment]
你点开 Servers 那一栏

应该是有一个默认服务器的

右键输入密码连接就行

**Comment by akademeia** [comment]
你安装postgresql的时候是不是有提示The database cluster initialisation failed？
如果是的话你现在应该电脑上并没有postgresql的数据库，可以尝试手动initdb，然后注册一下service
