### ISSUE TITLE
webui报告未知错误

### ISSUE THREAD

**Issue by DeparturesNeko** [HibiKier/zhenxun_bot#316]
通过守护进程启动webui，访问网页可以正常打开，但是输入用户名与密码后登录提示未知错误，webui后台日志为如下报错：

Proxy error: Could not proxy request /webui/login from xxx.xxx.xxx.xxx(ip地址):8081 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

这是我的vue.config.js
![图片](https://user-images.githubusercontent.com/96569888/169187237-72cfb3c4-b2c2-4007-9065-f53b8b36287a.png)

**Comment by HibiKier** [comment]
8081端口有被占用吗

**Comment by Su-Dream** [comment]
不打包直接yarn serve运行

**Comment by DeparturesNeko** [comment]
> 不打包直接yarn serve运行

我是跟着真寻Bot官网的教程做的，上面好像没有写到打包，我是install完了后直接yarn serve运行的

**Comment by DeparturesNeko** [comment]
> 8081端口有被占用吗

没有，我从外网访问8081是可以打开网页的，就是没法登录

**Comment by HibiKier** [comment]
你用户名密码改了吗

**Comment by Su-Dream** [comment]
我使用yarn build打包之后部署在nginx服务器上输入正确/错误的账号密码也是提示未知错误
并且请求发送在了http://IP:Prot/webui/login(不打包也是发这个
打包之后请求这个路径控制台报404resource未找到

**Comment by DeparturesNeko** [comment]
> 你用户名密码改了吗

嗯改过了

**Comment by DeparturesNeko** [comment]
> 我使用yarn build打包之后部署在nginx服务器上输入正确/错误的账号密码也是提示未知错误 并且请求发送在了[http://IP:Prot/webui/login(不打包也是发这个](http://IP:Prot/webui/login(%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA) 打包之后请求这个路径控制台报404resource未找到

我好像是在重定向的时候被拒绝连接了

**Comment by Su-Dream** [comment]
> > 我使用yarn build打包之后部署在nginx服务器上输入正确/错误的账号密码也是提示未知错误 并且请求发送在了[http：//IP：Prot/webui/login（不打包也是发这个]（[http：//IP：Prot/webui/login（%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA）](http://IP:Prot/webui/login(%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA)) 打包之后请求路径控制台报404未找到
> 
> 我好像是在重定向的时候被拒绝连接了

按F12看看你的控制台和网络

**Comment by DeparturesNeko** [comment]
> > > 我使用yarn build打包之后部署在nginx服务器上输入正确/错误的账号密码也是提示未知错误 并且请求发送在了[http：//IP：Prot/webui/login（不打包也是发这个]（[http：//IP：Prot/webui/login（%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA）](http://IP:Prot/webui/login(%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA)) 打包之后请求路径控制台报404未找到
> > 
> > 
> > 我好像是在重定向的时候被拒绝连接了
> 
> 按F12看看你的控制台和网络

![图片](https://user-images.githubusercontent.com/96569888/169288140-85140d8d-7cbe-4df9-bd20-525b81566f20.png)

**Comment by DeparturesNeko** [comment]
![图片](https://user-images.githubusercontent.com/96569888/169288532-25d0969e-8864-4ba8-9b71-d11b8e78466f.png)

**Comment by DeparturesNeko** [comment]
> > > 我使用yarn build打包之后部署在nginx服务器上输入正确/错误的账号密码也是提示未知错误 并且请求发送在了[http：//IP：Prot/webui/login（不打包也是发这个]（[http：//IP：Prot/webui/login（%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA）](http://IP:Prot/webui/login(%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA)) 打包之后请求路径控制台报404未找到
> > 
> > 
> > 我好像是在重定向的时候被拒绝连接了
> 
> 按F12看看你的控制台和网络

![图片](https://user-images.githubusercontent.com/96569888/169288593-ba6c7d1e-17d9-4c11-97ec-ccdd9434540e.png)

**Comment by MarmotSun** [comment]
![image](https://user-images.githubusercontent.com/73126692/169320836-5d4f42f6-afa6-4b76-b6ff-357fad05f740.png)
噢噢我的还不太一样，我的是这种情况，请问大佬这个是什么意思

**Comment by Su-Dream** [comment]
> ![image](https://user-images.githubusercontent.com/73126692/169320836-5d4f42f6-afa6-4b76-b6ff-357fad05f740.png) 噢噢我的还不太一样，我的是这种情况，请问大佬这个是什么意思

不要打包，直接yarn serve运行

**Comment by MarmotSun** [comment]
![image](https://user-images.githubusercontent.com/73126692/169322860-96433763-1974-4a59-8238-a85515450f66.png)
我在webui的文件夹里运行了yarn serve，再去登录的时候是这个情况

**Comment by HibiKier** [comment]
> ![image](https://user-images.githubusercontent.com/73126692/169322860-96433763-1974-4a59-8238-a85515450f66.png) 我在webui的文件夹里运行了yarn serve，再去登录的时候是这个情况

你bot没开

**Comment by HibiKier** [comment]
> > > > > > 我使用yarn build打包之后部署在nginx服务器上输入正确/错误的账号密码也是提示未知错误 并且请求发送在了[http：//IP：Prot/webui/login（不打包也是发这个]（[http：//IP：Prot/webui/login（%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA）](http://IP:Prot/webui/login(%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA)) 打包之后请求路径控制台报404未找到
> > > > > 
> > > > > 
> > > > > 我好像是在重定向的时候被拒绝连接了
> > > > 
> > > > 
> > > > 按F12看看你的控制台和网络
> > > 
> > > 
> > > ![图片](https://user-images.githubusercontent.com/96569888/169288593-ba6c7d1e-17d9-4c11-97ec-ccdd9434540e.png)
> > 
> > 
> > 你试试把防火墙关了
> 
> ![图片](https://user-images.githubusercontent.com/96569888/169328363-5f726916-856f-4a29-8954-968a834944eb.png) 还是一样的报错

bot开着的吗

**Comment by DeparturesNeko** [comment]
> > > > > > > 我使用yarn build打包之后部署在nginx服务器上输入正确/错误的账号密码也是提示未知错误 并且请求发送在了[http：//IP：Prot/webui/login（不打包也是发这个]（[http：//IP：Prot/webui/login（%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA）](http://IP:Prot/webui/login(%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA)) 打包之后请求路径控制台报404未找到
> > > > > > 
> > > > > > 
> > > > > > 我好像是在重定向的时候被拒绝连接了
> > > > > 
> > > > > 
> > > > > 按F12看看你的控制台和网络
> > > > 
> > > > 
> > > > ![图片](https://user-images.githubusercontent.com/96569888/169288593-ba6c7d1e-17d9-4c11-97ec-ccdd9434540e.png)
> > > 
> > > 
> > > 你试试把防火墙关了
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/96569888/169328363-5f726916-856f-4a29-8954-968a834944eb.png) 还是一样的报错
> 
> bot开着的吗

开的，在群聊里基本能正常交互，就是webui登陆不上

**Comment by DeparturesNeko** [comment]
> > > > > > > 我使用yarn build打包之后部署在nginx服务器上输入正确/错误的账号密码也是提示未知错误 并且请求发送在了[http：//IP：Prot/webui/login（不打包也是发这个]（[http：//IP：Prot/webui/login（%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA）](http://IP:Prot/webui/login(%E4%B8%8D%E6%89%93%E5%8C%85%E4%B9%9F%E6%98%AF%E5%8F%91%E8%BF%99%E4%B8%AA)) 打包之后请求路径控制台报404未找到
> > > > > > 
> > > > > > 
> > > > > > 我好像是在重定向的时候被拒绝连接了
> > > > > 
> > > > > 
> > > > > 按F12看看你的控制台和网络
> > > > 
> > > > 
> > > > ![图片](https://user-images.githubusercontent.com/96569888/169288593-ba6c7d1e-17d9-4c11-97ec-ccdd9434540e.png)
> > > 
> > > 
> > > 你试试把防火墙关了
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/96569888/169328363-5f726916-856f-4a29-8954-968a834944eb.png) 还是一样的报错
> 
> bot开着的吗

![图片](https://user-image.githubusercontent.com/96569888/169453480-0f65e957-ee49-4135-8c6b-668fb7d34a45.png)
这个是谷歌浏览器视角的报错，之前的截图是火狐的

**Comment by Su-Dream** [comment]
> 

把浏览器代理关闭试试？

**Comment by DeparturesNeko** [comment]
> > 
> 
> 把浏览器代理关闭试试？

是指梯子吗，那个我平常是不开的

**Comment by Su-Dream** [comment]
> > > 
> > 
> > 
> > 把浏览器代理关闭试试？
> 
> 是指梯子吗，那个我平常是不开的

你可以尝试以下步骤
1、将webui文件夹解压到和真寻bot同级目录
例如
`
---zhenxunbot
---go-cqhttp
---zhenxunbot_webUi

`
2、进入到webui使用cmd输入yarn serve
运行成功应该是localhost:8081

3、使用外网访问你服务器http://服务器公网地址:8081

如果无法解决，请在win10搜索中搜索Internet选项-链接处和windows设置-网络-代理中查看你的代理设置

**Comment by DeparturesNeko** [comment]
> 

我从外网是可以打开那个网页的，但是无法登录，报未知错误

**Comment by DeparturesNeko** [comment]
> > > > 
> > > 
> > > 
> > > 把浏览器代理关闭试试？
> > 
> > 
> > 是指梯子吗，那个我平常是不开的
> 
> 你可以尝试以下步骤 1、将webui文件夹解压到和真寻bot同级目录 例如 ` ---zhenxunbot ---go-cqhttp ---zhenxunbot_webUi
> 
> ` 2、进入到webui使用cmd输入yarn serve 运行成功应该是localhost:8081
> 
> 3、使用外网访问你服务器[http://服务器公网地址:8081](http://%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%85%AC%E7%BD%91%E5%9C%B0%E5%9D%80:8081)
> 
> 如果无法解决，请在win10搜索中搜索Internet选项-链接处和windows设置-网络-代理中查看你的代理设置

问题已解决，环境：阿里云ubuntu20.04镜像，已安装宝塔面板，在nodejs版本为18时会出现上述错误，通过卸载node与npm，并将node版本安装为14.7时成功解决
