### ISSUE TITLE
大佬们为什么一直打不开bot.py

### ISSUE THREAD

**Issue by zlsSGuang** [HibiKier/zhenxun_bot#317]
直接打开会闪现一个控制窗，然后瞬间关，用命令也是没反应
![image](https://user-images.githubusercontent.com/105781964/169189448-63b4bce7-4bab-4e81-9380-d020d754c414.png)

**Comment by zlsSGuang** [comment]
> 看文档 [传送门](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_zhenxun.html)

已经一个一个输入了，然后playwright install chromium
playwright install-deps chromium这两个会报错

**Comment by HibiKier** [comment]
你截图上并没有输入poetry install

**Comment by zlsSGuang** [comment]
![image](https://user-images.githubusercontent.com/105781964/169191468-bb2c557b-ffd8-4520-9971-559aa075cb5f.png)

**Comment by HibiKier** [comment]
进bot目录再输入

**Comment by zlsSGuang** [comment]
![image](https://user-images.githubusercontent.com/105781964/169191667-217a54c7-0f50-4cbf-9b61-6614df648bf3.png)

**Comment by summer904** [comment]
![image](https://user-images.githubusercontent.com/80885131/169191647-81b6dfb7-1506-4bd1-95d1-d3dda2200b52.png)
我在bot目录输入了，但还是有报错，请大佬帮忙看下是怎么回事，代码都是按顺序输入的

**Comment by HibiKier** [comment]
代理关了

**Comment by zlsSGuang** [comment]
> 你这代理关了？

刚刚还没关，现在关了，加载有点久而且不敢开代理怕又重新加载就没回复了不好意思！

**Comment by zlsSGuang** [comment]
![image](https://user-images.githubusercontent.com/105781964/169192492-da573474-cdd7-46c1-abeb-d2f22009fdc0.png)
![image](https://user-images.githubusercontent.com/105781964/169192512-1d162969-309c-4505-8f9c-fa5aaef6f679.png)

**Comment by HibiKier** [comment]
poetry shell
python3 bot.py

**Comment by HibiKier** [comment]
python -m playwright install chromium

**Comment by summer904** [comment]
> python -m playwright install chromium
![image](https://user-images.githubusercontent.com/80885131/169194041-71f29999-fb0a-4e83-a41d-ffa698ef887a.png)
还是无法找到这一条，在对应的文件夹也没有相关文件，请问是否需要另行安装

**Comment by StarChaserX** [comment]
> > python3并不会读取，试试python bot.py，然后你再去下个python 3.9，我就是这么搞的
> 
> 我超可以了谢谢大佬！

还有你的poetry没有正常安装，所以才叫你换到3.9python，

**Comment by zlsSGuang** [comment]
> > > python3并不会读取，试试python bot.py，然后你再去下个python 3.9，我就是这么搞的
> > 
> > 
> > 我超可以了谢谢大佬！
> 
> 还有你的poetry没有正常安装，所以才叫你换到3.9python，

好的感谢！
