### ISSUE TITLE
B站订阅：获取用户动态 发送错误

### ISSUE THREAD

**Issue by SuPeng-Git** [HibiKier/zhenxun_bot#320]
B站订阅插件
![image](https://user-images.githubusercontent.com/92625642/169194802-7544b9c4-6722-4ff8-a6d5-aed02de1a7e5.png)
[error_2022-05-19.log]
这是我的日志文件
(https://github.com/HibiKier/zhenxun_bot/files/8723132/error_2022-05-19.log)

**Comment by HibiKier** [comment]
可能是bug？周末看看

**Comment by HibiKier** [comment]
测试后并无复现，可以提供一下订阅id？

**Comment by SuPeng-Git** [comment]
当前订阅的UP：
	UP：凛子同学提不起劲
	uid：1338715561
------------------
	UP：Ado豆苗
	uid：2043028
------------------
	UP：SmokeSakuya
	uid：17832530
------------------
	UP：冯提莫
	uid：436473455
------------------
	UP：岩论
	uid：688031185
------------------
	UP：狈总
	uid：283036476
------------------
	UP：Mischa_Shaner
	uid：245599876
------------------
	UP：大狸子切切里
	uid：471303350
------------------
	UP：Warma
	uid：53456
------------------
	UP：嘉然今天吃什么
	uid：672328094
------------------
	UP：贝拉kira
	uid：672353429
------------------
	UP：卢克文工作室
	uid：438173577
------------------
	UP：原神
	uid：401742377
------------------
	UP：哔哩哔哩英雄联盟赛事
	uid：50329118
------------------
	UP：Steam官方特惠
	uid：518876755
------------------

**Comment by SuPeng-Git** [comment]
![image](https://user-images.githubusercontent.com/92625642/169641604-fa385f95-8183-4355-b129-b032f419375c.png)
它好像可以正常工作，但是它会在后台一直发送如上图的报错

**Comment by HibiKier** [comment]
更新代码
