### ISSUE TITLE
原神黄历汉字无法显示

### ISSUE THREAD

**Issue by fuyang0811** [HibiKier/zhenxun_bot#321]
使用一键安装脚本搭建。
centos系统，其他功能正常。log也没有报错。
![image](https://user-images.githubusercontent.com/61312850/169197055-598e79e1-303c-4c55-a532-c0438014a13e.png)
05-19 11:20:19 [SUCCESS] nonebot | ONEBOT V11 3561478820 | [message.group.normal]: Message -230702728 from xxxxxxxxx@[群:xxxxxxxx] "原神黄历"
05-19 11:20:19 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-19 11:20:19 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-19 11:20:19 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
05-19 11:20:19 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-19 11:20:20 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-19 11:20:20 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
05-19 11:20:20 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-19 11:20:20 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-19 11:20:20 [INFO] nonebot | Event will be handled by <Matcher from plugins.genshin.almanac, type=message, priority=5, temp=False>
05-19 11:20:20 [INFO] plugins | (USER 415276785, GROUP 399087282) 发送查看原神黄历
05-19 11:20:20 [INFO] nonebot | Matcher <Matcher from plugins.genshin.almanac, type=message, priority=5, temp=False> running complete

**Comment by HibiKier** [comment]
给你服务器安装中文字体

**Comment by Excalibur5100** [comment]
我之前也遇到过这个问题，解决了 ，可以看#266

**Comment by fuyang0811** [comment]
> 给你服务器安装中文字体

谢谢作者，主要是一些其他功能都没问题，所以没考虑过这一点。谢谢ヾ(≧▽≦*)o

**Comment by fuyang0811** [comment]
> 我之前也遇到过这个问题，解决了 ，可以看#266

谢谢φ(゜▽゜*)♪

**Comment by akademeia** [comment]
顺带提一下，这个图片是缓存在resources/image/genshin/alc里面的，装完字体记得把旧的删掉不然查黄历还是发之前带框框的图

**Comment by fuyang0811** [comment]
> 顺带提一下，这个图片是缓存在resources/image/genshin/alc里面的，装完字体记得把旧的删掉不然查黄历还是发之前带框框的图

谢谢（￣︶￣）↗
