### ISSUE TITLE
机器人可以用了但是缺少这两个模块怎么办

### ISSUE THREAD

**Issue by 80546033** [HibiKier/zhenxun_bot#322]
![image](https://user-images.githubusercontent.com/67412155/169197356-eef19f9b-7c98-42d5-8792-336e502e53f7.png)

**Comment by sblvbon** [comment]
+1

**Comment by HibiKier** [comment]
poetry add bilireq

**Comment by 80546033** [comment]
> poetry add bilireq

大佬还有机器人用的时候有这个错误
Saucenao 缺失API_KEY！

**Comment by 740333480** [comment]
> 

参考https://github.com/HibiKier/zhenxun_bot/issues/269

**Comment by Saukurs** [comment]
> > poetry add bilireq
> 
> 大佬还有机器人用的时候有这个错误
> Saucenao 缺失API_KEY！

看说明先到saucenao获取apikey
