### ISSUE TITLE
真寻BOT打开时 连线数据库错误

### ISSUE THREAD

**Issue by Focuskenny** [HibiKier/zhenxun_bot#323]
BOT连接数据库的错误画面
![bandicam 2022-05-19 11-26-17-193](https://user-images.githubusercontent.com/93857726/169199285-567fff84-e5c6-4344-8e1e-b2e12cfdad4e.jpg)
![bandicam 2022-05-19 11-26-29-304](https://user-images.githubusercontent.com/93857726/169199290-d6e2149c-9688-488b-a2f4-c031c581bfbb.jpg)
![bandicam 2022-05-19 11-26-31-668](https://user-images.githubusercontent.com/93857726/169199295-6271aa02-0fa2-4c38-8f32-ac64ee161c13.jpg)

BOT的设置文件画面
![bandicam 2022-05-19 11-27-04-213](https://user-images.githubusercontent.com/93857726/169199355-4dd8d940-6163-47dc-b064-cfcf7376f4df.jpg)

PG的database画面
![bandicam 2022-05-19 11-27-30-099](https://user-images.githubusercontent.com/93857726/169199403-84412cde-920b-4251-9aa1-097823a07c87.jpg)
![bandicam 2022-05-19 11-27-40-387](https://user-images.githubusercontent.com/93857726/169199408-0bee3197-e2ea-4953-a7b1-510433c07fd4.jpg)

Nonebot的Python画面
![bandicam 2022-05-19 11-43-43-973](https://user-images.githubusercontent.com/93857726/169199851-aa269172-6527-4555-ae8f-50652e611fcd.jpg)

gocqhttp的画面
![bandicam 2022-05-19 11-43-40-825](https://user-images.githubusercontent.com/93857726/169199888-f14b56d2-1348-4643-8c42-5d54c3284ed8.jpg)

Windows
Python 3.9
PG14
依赖包／环境都有打上，设置超级用户也整上，config的设置文件也有调整过
重试好几个database重新创建都还是不行，数据的名称也都跟BOT设置文件一样，也还是整不上
想请求大佬能否给予解答，不好意思麻烦了

**Comment by MingxuanGame** [comment]
能否发一下  pg_hba.conf

**Comment by Focuskenny** [comment]
> 能否发一下 pg_hba.conf

应该是在PG／14／data下的pg_hba.conf吧?
我把截图发上来，再麻烦了
![bandicam 2022-05-19 12-34-23-827](https://user-images.githubusercontent.com/93857726/169205781-54114f57-7a9e-4784-9585-c298169dfed7.jpg)
![bandicam 2022-05-19 12-34-29-059](https://user-images.githubusercontent.com/93857726/169205786-be657080-659c-4971-b5d8-f5c0d5b52c70.jpg)
![bandicam 2022-05-19 12-34-32-299](https://user-images.githubusercontent.com/93857726/169205791-b9cd918b-ceac-4db5-a2fc-9f5a078e918a.jpg)

**Comment by MingxuanGame** [comment]
试着在末尾添加这一行

```conf
host    all             all             0.0.0.0/0               md5
```
