### ISSUE TITLE
如何连接数据库，创建连接，新建数据库

### ISSUE THREAD

**Issue by xxr777** [HibiKier/zhenxun_bot#324]
![image](https://user-images.githubusercontent.com/105805521/169203299-8c21690a-91cb-45f2-a2f1-b4817f06eacd.png)
不是很懂这是啥意思

**Comment by HibiKier** [comment]
打开pgadmin，左侧了最上边右键新建数据库

**Comment by xxr777** [comment]
> ![image](https://user-images.githubusercontent.com/105805521/169203299-8c21690a-91cb-45f2-a2f1-b4817f06eacd.png) 不是很懂这是啥意思
