### ISSUE TITLE
不提到昵称的情况下也触发了指令

### ISSUE THREAD

**Issue by ru8lq0005** [HibiKier/zhenxun_bot#327]
我的.env.dev中昵称配置是默认的，但是遇到一个情况，在群内即使没有@真寻或者使用昵称，仅仅是对话内容中提到了关键字如“识图”，真寻也会相应地作出回复，干扰了正常对话体验，请问这是设定 还是我的配置错误呢？

**Comment by HibiKier** [comment]
大部分命令是开头匹配，例如 "识图"，如果是 "哈哈哈识图" 这样是不会匹配的，如果你觉得干扰对话，可以在env.dev配置中添加COMMAND_START
