### ISSUE TITLE
本人使用的是Ubuntu云服务器，整个流程都操作了一遍，有两个问题无法解决，一个是QQ的扫码登录；我看说解决方法是本地登录获取token文件传到服务器，想知道本地登录是在手机电脑还是云服务器，token文件又是在哪里；第二个问题是webUI的地址，yarn run serve后是成功了，但是地址打不开，bot和数据库都是已经打开的

### ISSUE THREAD

**Issue by LaffeyLa** [HibiKier/zhenxun_bot#328]
![img](https://s1.ax1x.com/2022/05/19/OHgVFP.png)
![img](https://s1.ax1x.com/2022/05/19/OHgGF0.png)

**Comment by LaffeyLa** [comment]
端口已经放行

**Comment by HibiKier** [comment]
本地电脑运行gocq会生成token'文件

**Comment by HibiKier** [comment]
webui地址外网就是  ip:8081

**Comment by Ironieser** [comment]
> webui地址外网就是 ip:8081

请问，yarn run serve后这样的提示，并没有提示在公网ip运行。

使用公网ip:port 也打不开
![image](https://user-images.githubusercontent.com/32543247/169217605-79bca996-34a7-4240-b074-5712252fc635.png)
请问是不是因为postgresql没开放在公网呢 还是什么原因呢

**Comment by HibiKier** [comment]
和数据库无关，大概率是你没放服务器端口

**Comment by Ironieser** [comment]
> 和数据库无关，大概率是你没放服务器端口

谢谢！解决了，我检查了下防火墙，把tcp和udp端口都打开了，就好了（印象中我tcp早早就打开了，也应该是tcp链接

**Comment by LaffeyLa** [comment]
> 

谢谢，qq登陆问题解决了，不过这个webui始终是打不开，端口也都放行了，更改端口也没用，整懵了，我这里ip不就是172.20.97.17吗？
[img](https://s1.ax1x.com/2022/05/19/ObmvAf.png)

**Comment by LaffeyLa** [comment]
> webui地址外网就是 ip:8081

感谢，已经解决
