### ISSUE TITLE
数据库连接链接怎么填

### ISSUE THREAD

**Issue by xxr777** [HibiKier/zhenxun_bot#329]
![image](https://user-images.githubusercontent.com/105805521/169205474-cb2a0d54-dfa5-47ca-976b-c4ae87835d26.png)

**Comment by zzcabc** [comment]
postgresql://用户名:密码@ip地址:端口/数据库名称

**Comment by HibiKier** [comment]
你下面填了bind可以不填

**Comment by zzcabc** [comment]
你填写了bind，下面可以不填，填了下面，bind可以不填

**Comment by yingyi9898** [comment]
xxr777您好，我想询问您一些事情，请问可以留一个联系方式吗

**Comment by xxr777** [comment]
> xxr777您好，我想询问您一些事情，请问可以留一个联系方式吗

QQ820213486
