### ISSUE TITLE
可不可以把AI回复放进被动技能里面进去

### ISSUE THREAD

**Issue by yusana213214** [HibiKier/zhenxun_bot#33]
如题，有些群并不需要这个功能，反而会觉得烦人，希望下次更新能加进去

**Comment by yusana213214** [comment]
> 如题，有些群并不需要这个功能，反而会觉得烦人，希望下次更新能加进去



> 如题，有些群并不需要这个功能，反而会觉得烦人，希望下次更新能加进去

**Comment by HibiKier** [comment]
有命令 ‘关闭ai’，群内关闭就是该群关闭ai
超级用户私聊 ‘关闭功能有更多选择’，可以查看超级用户命令帮助文档

**Comment by yusana213214** [comment]
> 有命令 ‘关闭ai’，群内关闭就是该群关闭ai
> 超级用户私聊 ‘关闭功能有更多选择’，可以查看超级用户命令帮助文档

我超，您这是住在git了吗

**Comment by HibiKier** [comment]
![74(IGIMX2R% ~F4LEA39U8](https://user-images.githubusercontent.com/45528451/130341204-a35b3fa1-e6a3-4ff9-b0a3-6da16470ab22.gif)

**Comment by yusana213214** [comment]
> 有命令 ‘关闭ai’，群内关闭就是该群关闭ai
> 超级用户私聊 ‘关闭功能有更多选择’，可以查看超级用户命令帮助文档

emmmm其实我一直想说了，查找群组/好友指令无效，还有，既然都做了退群功能了，删好友功能也做了吧

**Comment by HibiKier** [comment]
我超，并不是无效，是帮助命令写错了，命令应该是 ‘所有群组/好友’

**Comment by yusana213214** [comment]
> 我超，并不是无效，是帮助命令写错了，命令应该是 ‘所有群组/好友’

我有个建议，ai功能的初始状态能不能是关闭啊，根据需要开启，我的群氛围有那么点严肃，关ai还不彻底，建议配置文件直接让ai功能保持关闭，群里好几个人对ai回复表示反感了

**Comment by HibiKier** [comment]
你的意思是有管理员会使用命令 开启AI？

**Comment by yusana213214** [comment]
> 你的意思是有管理员会使用命令 开启AI？

就是希望ai功能默认关闭，有些群友话题讨论讨论着就触发ai了

**Comment by HibiKier** [comment]
啊？ai功能只有艾特真寻或 消息开头是 bot nickname 才会触发啊，如果要关闭ai，直接在群中发送 ‘关闭ai’，或者通过私聊发送‘关闭ai [group_id]’ 来禁用该群的ai（管理员也无法开启），或者私聊发送‘关闭ai g’来禁用所有群聊的ai功能

**Comment by yusana213214** [comment]
> 啊？ai功能只有艾特真寻或 消息开头是 bot nickname 才会触发啊，如果要关闭ai，直接在群中发送 ‘关闭ai’，或者通过私聊发送‘关闭ai [group_id]’ 来禁用该群的ai（管理员也无法开启），或者私聊发送‘关闭ai g’来禁用所有群聊的ai功能

关闭功能那个可以好好写指令吗，，，研究半天都是格式错误，另外，能把readme里面的npm去掉吗，已经误导我好几次了

**Comment by HibiKier** [comment]
好的，部分功能展示确实有段时间没有更新了，建议看功能具体指令

**Comment by yusana213214** [comment]
> 好的，部分功能展示确实有段时间没有更新了，建议看功能具体指令

彳亍，大佬也早点休息，放心脱发啊/

**Comment by yusana213214** [comment]
> 好的，部分功能展示确实有段时间没有更新了，建议看功能具体指令

顺带一提，能不能功能和指令触发带个空格
比如关闭功能改成   关闭 ai g，这样，别的模块功能跟参数中间习惯带空格导致在真寻上经常格式错误

**Comment by yusana213214** [comment]
> > 好的，部分功能展示确实有段时间没有更新了，建议看功能具体指令
> 
> 顺带一提，能不能功能和指令触发带个空格或者适配一下各种参数之间带空格的情况
> 比如关闭ai功能用 关闭 ai g和 关闭ai g 这两种写法都能触发这样子，别的模块功能跟参数中间习惯带空格导致在真寻上经常格式错误

话说，，，有没有查看群功能状态这功能的?（不是群被动）

**Comment by HibiKier** [comment]
关闭ai是一个完整的命令，后面的g才是参数，所以关闭ai g和关闭aig一个效果。
没发现在群内的帮助功能左侧都有一个×或√嘛，代表该群功能状态，超级用户有命令‘功能状态’来显示超级用户对功能的管理

**Comment by yusana213214** [comment]
> 关闭ai是一个完整的命令，后面的g才是参数，所以关闭ai g和关闭aig一个效果。
> 没发现在群内的帮助功能左侧都有一个×或√嘛，代表该群功能状态，超级用户有命令‘功能状态’来显示超级用户对功能的管理

大佬，超级用户帮助图片是由哪个py文件控制输出的啊，打算在里面加个自己写的禁言退群指令

**Comment by HibiKier** [comment]
plugins/super_help
