### ISSUE TITLE
可以添加其他的搜图网站吗

### ISSUE THREAD

**Issue by woaoaj** [HibiKier/zhenxun_bot#330]
搜小本本
![8Y }J(C(@WFR)`2VNZGF9R7](https://user-images.githubusercontent.com/105791979/169206397-c1ee24ce-10a4-4343-9bc4-687176aa6903.jpg)

**Comment by ID114514** [comment]
建议使用专业的搜图机器人，真寻并不是为搜图而诞生的

**Comment by eENmame** [comment]
233搜小本本

**Comment by HibiKier** [comment]
未来可期（bushi

**Comment by HibiKier** [comment]
帮我也搜搜（bushi
