### ISSUE TITLE
启动时出现问题，求大佬解答QAQ

### ISSUE THREAD

**Issue by 11Moyan7** [HibiKier/zhenxun_bot#331]
![image](https://user-images.githubusercontent.com/105837174/169211581-30462829-f76b-4272-b1a7-e4a9fa6fce50.png)

没有看到生成config.yaml

**Comment by 11Moyan7** [comment]
![image](https://user-images.githubusercontent.com/105837174/169211734-5b03f1b1-7b27-4a67-aeba-4975e38e2050.png)

**Comment by HibiKier** [comment]
日志发全，你数据库链接失败了

**Comment by 11Moyan7** [comment]
![image](https://user-images.githubusercontent.com/105837174/169212097-325cb10c-c154-4a1f-9bc2-c004f4feacc1.png)
![image](https://user-images.githubusercontent.com/105837174/169212120-4445c4da-f32c-4c79-915a-6823c30ab486.png)
![image](https://user-images.githubusercontent.com/105837174/169212129-839a527e-e193-473b-9e81-bd38ff4c53c7.png)

**Comment by HibiKier** [comment]
查看你数据库配置是否填写正确

**Comment by 11Moyan7** [comment]
> 
好的，谢谢大佬我等会去看看
