### ISSUE TITLE
为什么识图的api key填上后bot就运行不了了

### ISSUE THREAD

**Issue by Natsumelan** [HibiKier/zhenxun_bot#332]
![_72KY(UK{%UU_@AB6FBAZ(7](https://user-images.githubusercontent.com/105765802/169212246-979165e4-7db1-4a68-ba41-052ad6ae5ffa.png)

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169212471-ef3378c7-43db-464e-b050-aa3cb7541db2.png)

**Comment by Natsumelan** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169212471-ef3378c7-43db-464e-b050-aa3cb7541db2.png)

哦哦，谢谢
