### ISSUE TITLE
识图输出报错

### ISSUE THREAD

**Issue by eENmame** [HibiKier/zhenxun_bot#333]
![image](https://user-images.githubusercontent.com/105780794/169213266-e4834243-f905-44d3-8af8-3af2919960e8.png)
如图修改识图的API运行后，输入对应指令qq显示正在处理图片 但后台显示这个报错

**Comment by HibiKier** [comment]
连接失败，尝试挂代理

**Comment by eENmame** [comment]
我试试

**Comment by eENmame** [comment]
挂代理了 好像还是没用

**Comment by HibiKier** [comment]
挂了代理需要在config.py里配置代理链接

**Comment by eENmame** [comment]
好了 解决了 谢谢大佬

**Comment by eENmame** [comment]
好了 解决了 谢谢大佬
