### ISSUE TITLE
执行poetry install时出现问题

### ISSUE THREAD

**Issue by LINK-URIBOH** [HibiKier/zhenxun_bot#336]
运行poetry install 后有两个包安装失败，再次执行后依然无法安装，请问应该如何解决这个问题。
使用的是vultr的位于日本东京的服务器。
root@vultr:/home/zhenxun_bot-main#  poetry install
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

Package operations: 53 installs, 0 updates, 0 removals

  • Installing pygtrie (2.4.2): Failed

  HTTPError

  403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/a5/8b/90d0f21a27a354e808a73eb0ffb94db990ab11ad1d8b3db3e5196c882cad/pygtrie-2.4.2.tar.gz#sha256=43205559d28863358dbbf25045029f58e2ab357317a59b11f11ade278ac64692

  at /usr/lib/python3/dist-packages/requests/models.py:940 in raise_for_status
      936│         elif 500 <= self.status_code < 600:
      937│             http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
      938│ 
      939│         if http_error_msg:
    → 940│             raise HTTPError(http_error_msg, response=self)
      941│ 
      942│     def close(self):
      943│         
      944│         called the underlying ``raw`` object must not be accessed again.

  • Installing zhconv (1.4.3): Failed

  HTTPError

  403 Client Error: Forbidden for url: https://pypi.tuna.tsinghua.edu.cn/packages/25/47/c8ae2d5d4025e253211ff3d8c163f457db1da94976cb582337a5ab76cb87/zhconv-1.4.3.tar.gz#sha256=ad42d9057ca0605f8e41d62b67ca797f879f58193ee6840562c51459b2698c45

  at /usr/lib/python3/dist-packages/requests/models.py:940 in raise_for_status
      936│         elif 500 <= self.status_code < 600:
      937│             http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
      938│ 
      939│         if http_error_msg:
    → 940│             raise HTTPError(http_error_msg, response=self)
      941│ 
      942│     def close(self):
      943│         
      944│         called the underlying ``raw`` object must not be accessed again.

**Comment by Nova-Noir** [comment]
日本东京服务器的话可以不换源，看起来是被清华源拦截了。

**Comment by LINK-URIBOH** [comment]
看了看代码，改一下pyproject.toml设置的pip下载源就好了，问题解决了。

**Comment by rinhon** [comment]
> 

大佬咋弄的，我好像也是这个
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

Package operations: 96 installs, 0 updates, 0 removals

  • Installing idna (3.3): Pending...
  • Installing sniffio (1.2.0): Pending...
