### ISSUE TITLE
在执行python bot.py 的时候出现错误 Application startup failed. Exiting.

### ISSUE THREAD

**Issue by AngelBeats401** [HibiKier/zhenxun_bot#338]
在执行python bot.py 的时候出现的错误
![134417](https://user-images.githubusercontent.com/65359943/169219015-0f1ea999-b2e2-4c77-974c-d0bccb97edcd.png)
`05-19 11:48:45 [SUCCESS] nonebot | NoneBot is initializing...
05-19 11:48:45 [INFO] nonebot | Current Env: dev
05-19 11:48:46 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
05-19 11:48:46 [SUCCESS] nonebot | Succeeded to import "admin_config"
05-19 11:48:47 [SUCCESS] nonebot | Succeeded to import "custom_welcome_message"
/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TsibdEpJ-py3.8/lib/python3.8/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
05-19 11:48:47 [SUCCESS] nonebot | Succeeded to import "timing_task"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "update_group_member_info"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "rule"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "switch_rule"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "admin_bot_manage"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "nickname"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "scripts"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "super_task_switch"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "clear_data"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "bot_friend_group"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "exec_sql"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "manager_group"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "reload_setting"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "update_friend_group_info"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "set_admin_permissions"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "super_cmd"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "group_handle"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "ban"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "update_info"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "apscheduler"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "init_plugin_config"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "broadcast"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "admin_help"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "chat_message_handle"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "chat_message"
05-19 11:48:48 [SUCCESS] nonebot | Succeeded to import "chat_history"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "super_help"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "invite_manager"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "use"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "shop_handle"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "shop_handle"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "reset_today_gold"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "my_props"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "buy"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "use"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "gold"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "shop"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "hooks"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "help"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "luxun"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "coser"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "quotations"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "update_gocqhttp"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "wbtop"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "comments_163"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "poetry"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "cover"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "jitang"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "alapi"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "poke"
05-19 11:48:49 [SUCCESS] nonebot | Succeeded to import "query_resource_points"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "query_memo"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "resin_remind"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "reset_today_query_user_data"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "query_memo"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "query_role"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "bind"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "genshin_sign"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "query_user"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "almanac"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "material_remind"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "genshin"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "weather"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "update_picture"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "translate"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "search_image"
05-19 11:48:50 [SUCCESS] nonebot | Succeeded to import "one_friend"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "web_ui"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "white2black_image"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "roll"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "search_anime"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "fake_msg"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "statistics_hook"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "statistics_handle"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "statistics"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "epic"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "check"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "mute"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "open_cases"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "aconfig"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "sign_in"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "russian"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "bilibili_sub"
05-19 11:48:51 [SUCCESS] nonebot | Succeeded to import "my_info"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "black_word"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "search_buff_skin_price"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "about"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "ai"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "withdraw"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "dialogue"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "fudu"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "pix_show_info"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "pix_add_keyword"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "pix_update"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "pix_pass_del_keyword"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "pix"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "pix_gallery"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "music"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "message_handle"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "word_hanlde"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "model"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "word_bank"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "nbnhhsh"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "move_image"
05-19 11:48:52 [SUCCESS] nonebot | Succeeded to import "send_image"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "upload_image"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "delete_image"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "image_management"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "group_welcome_msg"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "pixiv_rank_search"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "parse_bilibili_json"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "yiqing"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "what_anime"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "bt"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "gold_redbag"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "pid_search"
05-19 11:48:53 [SUCCESS] nonebot | Succeeded to import "check_zhenxun_update"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "draw_card"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "send_dinggong_voice"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "update_setu"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "send_setu"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "send_setu_"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "auth_hook"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "other_hook"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "ban_hook"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
05-19 11:48:54 [SUCCESS] nonebot | Succeeded to import "task_hook"
05-19 11:48:54 [SUCCESS] nonebot | Running NoneBot...
05-19 11:48:54 [INFO] uvicorn | Started server process [17103]
05-19 11:48:54 [INFO] uvicorn | Waiting for application startup.
05-19 11:48:54 [INFO] services | Database loaded successfully!
/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TsibdEpJ-py3.8/lib/python3.8/site-packages/apscheduler/triggers/cron/__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TsibdEpJ-py3.8/lib/python3.8/site-packages/apscheduler/triggers/cron/__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TsibdEpJ-py3.8/lib/python3.8/site-packages/apscheduler/triggers/interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)
05-19 11:48:54 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-19 11:48:59 [INFO] basic_plugins | 自动更新城市列表完成.....
05-19 11:48:59 [INFO] basic_plugins | 已成功加载 58 个非限制插件.
05-19 11:48:59 [INFO] utils | 已成功加载 5 个Cd限制.
05-19 11:48:59 [INFO] utils | 已成功加载 12 个Block限制.
05-19 11:48:59 [INFO] utils | 已成功加载 1 个Count限制.
05-19 11:48:59 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TsibdEpJ-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TsibdEpJ-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TsibdEpJ-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 600, in startup
    handler()
  File "/www/wwwroot/zhenxun/zhenxun_bot-main/basic_plugins/init_plugin_config/__init__.py", line 53, in _
    raise Exception("首次运行，已在configs目录下生成配置文件config.yaml，修改后重启即可...")
Exception: 首次运行，已在configs目录下生成配置文件config.yaml，修改后重启即可...

05-19 11:48:59 [ERROR] uvicorn | Application startup failed. Exiting.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TsibdEpJ-py3.8/lib/python3.8/site-packages/bilibili_api/utils/network.py", line 26, in __clean
    loop = asyncio.get_event_loop()
  File "/.pyenv/versions/3.8.0/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
`

**Comment by MingxuanGame** [comment]
修改配置后重启即可
