### ISSUE TITLE
Saucenao识图失败..

### ISSUE THREAD

**Issue by Natsumelan** [HibiKier/zhenxun_bot#339]
是网络问题吗，挂个vpn行不行

**Comment by HibiKier** [comment]
提供日志

**Comment by Natsumelan** [comment]
> 提供日志

![image](https://user-images.githubusercontent.com/105765802/169224559-3e509db0-4889-4516-9e26-c71b11ee84e3.png)

**Comment by Nova-Noir** [comment]
你的报错截的像艺术品。

**Comment by Natsumelan** [comment]
> 你的报错截的像艺术品。

没有报错，识图的时候要么说识图失败要么说等等在试试

**Comment by Natsumelan** [comment]
![image](https://user-images.githubusercontent.com/105765802/169227441-fe2ac450-7d2c-44c0-8858-d19ba1272c2f.png)
![image](https://user-images.githubusercontent.com/105765802/169227469-23ce7cb0-6254-4b05-9174-7b6440014aa8.png)

**Comment by Natsumelan** [comment]
还是说程序没问题，只是单纯没找到🤔

**Comment by WYH9355** [comment]
尝试比对一下ApiKey，之前部署时把网址上的key拷贝到config.yaml后，手贱点了regen，生成了新的key，我也出现了识图失败

**Comment by Natsumelan** [comment]
> 尝试比对一下ApiKey，之前部署时把网址上的key拷贝到config.yaml后，手贱点了regen，生成了新的key，我也出现了识图失败

原来如此，感谢
