### ISSUE TITLE
目前成功启动了机器人，但是怎么没有回应

### ISSUE THREAD

**Issue by zlsSGuang** [HibiKier/zhenxun_bot#341]
![image](https://user-images.githubusercontent.com/105781964/169225731-876d4718-9d04-47d3-aeca-30d04503f6c5.png)
是不是还要给某个群权限，还有管理员权限怎么给……求大佬指点

**Comment by 11Moyan7** [comment]
同问

**Comment by Fengshou-Xu** [comment]
你这看起来没启动go-cqhttp啊

**Comment by zlsSGuang** [comment]
> 你这看起来没启动go-cqhttp啊

忘了……现在启动了还是没回应……

**Comment by Fengshou-Xu** [comment]
> > 你这看起来没启动go-cqhttp啊
> 
> 忘了……现在启动了还是没回应……

那你go-cqhttp那边输出是什么？有连接到bot吗

**Comment by 11Moyan7** [comment]
![image](https://user-images.githubusercontent.com/105837174/169227375-ae984eb2-22fb-4528-a308-365aebf707de.png)
![image](https://user-images.githubusercontent.com/105837174/169227406-72f3e946-0c54-44f6-9016-65658e20bcb3.png)
求大佬帮助QAQ

**Comment by zlsSGuang** [comment]
![image](https://user-images.githubusercontent.com/105781964/169227474-fde1006b-84a4-46f7-99c7-4d44acd62243.png)
我目前是这样的，应该是连了吧？

**Comment by Fengshou-Xu** [comment]
> ![image](https://user-images.githubusercontent.com/105781964/169227474-fde1006b-84a4-46f7-99c7-4d44acd62243.png) 我目前是这样的，应该是连了吧？

你这样是连接成功了

**Comment by Fengshou-Xu** [comment]
> ![image](https://user-images.githubusercontent.com/105837174/169227375-ae984eb2-22fb-4528-a308-365aebf707de.png) ![image](https://user-images.githubusercontent.com/105837174/169227406-72f3e946-0c54-44f6-9016-65658e20bcb3.png) 求大佬帮助QAQ

你这个肯定是端口配置错误了 倒回去看看配置文件里面的端口是不是统一了

**Comment by zlsSGuang** [comment]
> > ![图像](https://user-images.githubusercontent.com/105837174/169227375-ae984eb2-22fb-4528-a308-365aebf707de.png) ![图像](https://user-images.githubusercontent.com/105837174/169227406-72f3e946-0c54-44f6-9016-65658e20bcb3.png)求大佬帮助QAQ
> 
> 你这个肯定是端口配置错误了 倒回去看看配置文件里面的端口是不是统一了

大佬，还是不行，没回应
![image](https://user-images.githubusercontent.com/105781964/169228008-8757a424-4c89-4b6d-8c56-0f67dff0d770.png)

**Comment by Fengshou-Xu** [comment]
> > > ![图像](https://user-images.githubusercontent.com/105837174/169227375-ae984eb2-22fb-4528-a308-365aebf707de.png) ![图像](https://user-images.githubusercontent.com/105837174/169227406-72f3e946-0c54-44f6-9016-65658e20bcb3.png)求大佬帮助QAQ
> > 
> > 
> > 你这个肯定是端口配置错误了 倒回去看看配置文件里面的端口是不是统一了
> 
> 大佬，还是不行，没回应 ![image](https://user-images.githubusercontent.com/105781964/169228008-8757a424-4c89-4b6d-8c56-0f67dff0d770.png)

你得贴出你的控制台输出 ，不然我也不可能通过意念连接到你的电脑帮你查看啊

**Comment by MingxuanGame** [comment]
你的地址错了

https://docs.go-cqhttp.org/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF

https://onebot.adapters.nonebot.dev/docs/guide/setup

**Comment by zlsSGuang** [comment]
![image](https://user-images.githubusercontent.com/105781964/169228878-e4c35532-ccf7-43d3-8a69-2a2b5fcfe085.png)
![image](https://user-images.githubusercontent.com/105781964/169228901-cb0f2a47-417f-4b3e-97d7-06e67f8cc82f.png)

**Comment by zlsSGuang** [comment]
我宣布个事，我是个傻逼！我把go-cqhttp的QQ号写成了另一个小号，真寻的是另一个QQ号，麻烦各位大佬了，已经解决了
