### ISSUE TITLE
无法发送消息

### ISSUE THREAD

**Issue by 1354961639** [HibiKier/zhenxun_bot#344]
如题，cqhttp控制台显示已经发送消息，但是实际并没有发送
![IMG_20220519_152216](https://user-images.githubusercontent.com/22723142/169237778-e8be4e53-cffb-48c5-9a3e-ac1b2d0de903.jpg)

**Comment by MingxuanGame** [comment]
私聊 那应该是被风控了

**Comment by HibiKier** [comment]
风控挺玄学的，也有可能是qq卡了

**Comment by xcf1127** [comment]
![NOZV2J4 `7X1%` NYHORZC8](https://user-images.githubusercontent.com/105791636/169460107-d9d805e9-b7ee-4432-893c-51145f29e55a.png)
大佬们，私聊真寻帮助也没反应是怎么回事儿

**Comment by MingxuanGame** [comment]
> ![NOZV2J4 7X1% NYHORZC8](https://user-images.githubusercontent.com/105791636/169460107-d9d805e9-b7ee-4432-893c-51145f29e55a.png) 大佬们，私聊真寻帮助也没反应是怎么回事儿

你的 go-cqhttp 都没连上

**Comment by xcf1127** [comment]
![)GXCD~LIRI0V~582LOKV766](https://user-images.githubusercontent.com/105791636/169463727-59c81952-37fe-4623-afdb-36804cbb027e.png)
我的go-cqhttp是这样的

**Comment by MingxuanGame** [comment]
你的 go-cqhttp 和 nonebot 同时运行了吗

**Comment by xcf1127** [comment]
我是憨憨
谢谢大佬
