### ISSUE TITLE
bot.py运行后，如何切出去运行go-cqhttp ?

### ISSUE THREAD

**Issue by housiyang-ufo** [HibiKier/zhenxun_bot#345]
![image](https://user-images.githubusercontent.com/73540078/169238423-82baa363-62b2-4ecc-a4e7-215c0be34694.png)
这里无法输入命令了，quit的话就bot.py停止运行了

**Comment by HibiKier** [comment]
为啥不再开一个终端，或者放screen之类的

**Comment by MingxuanGame** [comment]
使用 nohup 或者 screen 将真寻切到后台

https://hibikier.github.io/zhenxun_bot/docs/installation_doc/start_.html

**Comment by housiyang-ufo** [comment]
使用了screen解决了
