### ISSUE TITLE
小白请教，python3 bot.py报错

### ISSUE THREAD

**Issue by ppp1453839388** [HibiKier/zhenxun_bot#349]
![image](https://user-images.githubusercontent.com/39877018/169243976-327849ce-fa6a-47be-b476-0334bde885b0.png)
![image](https://user-images.githubusercontent.com/39877018/169244157-316a622b-f735-4e53-99ff-9442b2e1943c.png)
还有好多处类似这个报错，这是有哪里没装好嘛

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169245590-0103be3c-c817-45e6-bda2-b2c7268a9f7c.png)
系统环境少了，百度一下这个报错可以找到安装命令

**Comment by Sakuracio** [comment]
运行这段命令然后重启Bot
```
apt-get install -y \
	build-essential \
	libgl1 \
	libglib2.0-0 \
	libnss3 \
	libatk1.0-0 \
	libatk-bridge2.0-0 \
	libcups2 \
	libxkbcommon0 \
	libxcomposite1 \
	libxrandr2 \
	libgbm1 \
	libgtk-3-0 \
	libasound2 \
```

**Comment by ppp1453839388** [comment]
蟹蟹大佬们

**Comment by YancyGuo** [comment]
> 运行这段命令然后重启Bot
> 
> ```
> apt-get install -y \
> 	build-essential \
> 	libgl1 \
> 	libglib2.0-0 \
> 	libnss3 \
> 	libatk1.0-0 \
> 	libatk-bridge2.0-0 \
> 	libcups2 \
> 	libxkbcommon0 \
> 	libxcomposite1 \
> 	libxrandr2 \
> 	libgbm1 \
> 	libgtk-3-0 \
> 	libasound2 \
> ```

请问在Windows系统中要如何解决?在自查完新用户和数据库连接后有和题主一样的问题,但是根据关键词百度完没有任何头绪.
