### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by yusana213214** [HibiKier/zhenxun_bot#35]
使用 关闭[功能] [g/p]关闭某功能时，如果优先使用关闭功能A g关闭群聊开关后，再次发送关闭功能A p关闭私聊开关时，会重置group的功能状态，从而打开功能A的群聊开关

另外，希望部分功能在已经关闭时，不被@机器人触发
，还有部分功能即使被关闭，超级用户依旧无视开关状态，有点影响私聊测试功能状态的体验（ps：还是觉得ai这种功能一开始就应该作为可选功能默认关闭）

**Comment by HibiKier** [comment]
关闭[功能] 有一个参数是'a'，本来是默认为 'a'，少写了一行（下次更新已修复），可以通过 '关闭[功能]a'来禁用全部，超级用户不受限制本来是特权的，下次更新可以给plugins2info_dict增加键自定义配置限制回复超级用户，默认功能状态的话也可以增加进plugins2info_dict，另外，关闭功能会被@bot触发？难道不是回复类似‘该功能已关闭’之类的话吗

**Comment by yusana213214** [comment]
> 关闭[功能] 有一个参数是'a'，本来是默认为 'a'，少写了一行（下次更新已修复），可以通过 '关闭[功能]a'来禁用全部，超级用户不受限制本来是特权的，下次更新可以给plugins2info_dict增加键自定义配置限制回复超级用户，默认功能状态的话也可以增加进plugins2info_dict，另外，关闭功能会被@bot触发？难道不是回复类似‘该功能已关闭’之类的话吗

感谢回复
