### ISSUE TITLE
数据库链接错误，求教大佬是哪一步出了问题？

### ISSUE THREAD

**Issue by summer904** [HibiKier/zhenxun_bot#350]
按照流程输入命令后，无法连接到数据库
![image](https://user-images.githubusercontent.com/80885131/169246362-51d50de4-4e03-4243-b850-0275c6a67fe8.png)

![image](https://user-images.githubusercontent.com/80885131/169246313-819e0f30-a075-474b-a60c-102f8186f53b.png)
![image](https://user-images.githubusercontent.com/80885131/169246397-3d84bd6f-5b17-4065-96b6-94102fc3d345.png)
![image](https://user-images.githubusercontent.com/80885131/169246448-f1d6c5f7-bdda-462b-a7cd-f7c71e05e9e1.png)
![image](https://user-images.githubusercontent.com/80885131/169246487-d6f77be2-cb1e-44fb-9c85-aa3e76fa7413.png)

想请问是哪一步流程出了问题，是不是数据库设置出错了？

**Comment by HibiKier** [comment]
在pgadmin创建testdb数据库和uname用户，或者把uanme改成postgres也行

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169248023-5f1d36f3-49f8-4434-85e5-3c29c73f56b3.png)
右键创建

**Comment by summer904** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169248023-5f1d36f3-49f8-4434-85e5-3c29c73f56b3.png) 右键创建

已经成功链接，感谢大佬，另外作为小白想请问一下config.yaml有什么是必须重新配置的吗，我直接按照默认的可以吗？

**Comment by HibiKier** [comment]
> 

可以默认，但是缺失一些key可能导致某些功能用不了

**Comment by summer904** [comment]
> > 
> 
> 可以默认，但是缺失一些key可能导致某些功能用不了

好的，非常感谢，我再自己研究一下~
