### ISSUE TITLE
大佬求救！如何修改色图命令权限，让群友也可以使用

### ISSUE THREAD

**Issue by ardsgfcrtjhj** [HibiKier/zhenxun_bot#351]
群友发送色图二字时bot会发送'群权限不足...'，该如何修改权限呢

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169253110-839d13f7-8eca-4b43-a099-74b4c6e45bfc.png)

**Comment by ardsgfcrtjhj** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169253110-839d13f7-8eca-4b43-a099-74b4c6e45bfc.png)

**Comment by ardsgfcrtjhj** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169253110-839d13f7-8eca-4b43-a099-74b4c6e45bfc.png)

小白想问下在哪里改...是在config.yaml中吗？这个文件里好像没group_id level......

**Comment by Natsumelan** [comment]
> > ![图片](https://user-images.githubusercontent.com/45528451/169253110-839d13f7-8eca-4b43-a099-74b4c6e45bfc.png)
> 
> 小白想问下在哪里改...是在config.yaml中吗？这个文件里好像没group_id level......

直接在qq上@ 然后按照格式输入指令 如：@绪山真寻 修改群权限 12345678 9
其中12345678是群号 后面的数字是你要改的权限等级

**Comment by ardsgfcrtjhj** [comment]
> > > ![图片](https://user-images.githubusercontent.com/45528451/169253110-839d13f7-8eca-4b43-a099-74b4c6e45bfc.png)
> > 
> > 
> > 小白想问下在哪里改...是在config.yaml中吗？这个文件里好像没group_id level......
> 
> 直接在qq上@ 然后按照格式输入指令 如：@绪山真寻 修改群权限 12345678 9 其中12345678是群号 后面的数字是你要改的权限等级

哦哦感谢大佬
