### ISSUE TITLE
请问在执行python3 bot.py的时候出现这个错误该怎么办？

### ISSUE THREAD

**Issue by CLT96** [HibiKier/zhenxun_bot#353]
![image](https://user-images.githubusercontent.com/87683293/169255811-8a9c38e9-54f0-4904-b574-bfa6ee2e6649.png)

**Comment by HibiKier** [comment]
感觉是系统少了点东西，试试百度
centos7 python3.8 moduleNotFoundError: No module named _ssl

**Comment by Nova-Noir** [comment]
需要重新编译安装python且将相关依赖安装。 我记得这个过程非常折磨。

**Comment by CLT96** [comment]
> 需要重新编译安装python且将相关依赖安装。 我记得这个过程非常折磨。

按照网上的方法，重新编译安装了python3.8，但还是报错No module named _ssl，有没有可能是playwright install-deps chromium
这一步出了问题？

**Comment by CLT96** [comment]
> 感觉是系统少了点东西，试试百度 centos7 python3.8 moduleNotFoundError: No module named _ssl

按照网上的方法，重新编译安装了python3.8，但还是报错No module named _ssl，有没有可能是playwright install-deps chromium
这一步出了问题？因为我系统是centos7，当时执行这一步的时候告诉我说
![image](https://user-images.githubusercontent.com/87683293/169425985-77793270-62ab-425f-9eed-04b1c7f99875.png)

**Comment by Nova-Noir** [comment]
centos使用的是yum而不是apt来获取软件包
关于_ssl问题，你可以在终端里使用python然后键入`import ssl`估计也会报错。

在CentOS下要安装的包和Ubuntu里要安的包名称不一样，关于这点，你可以搜索关键词 "centos"。
在编译安装python前，你应该先编译安装最新版本的openssl。

打击人的是，根据我的经验，即使安装好了ssl模块，估计还会有其他模块安装失败，这要让你再次重复上面的编译安装python过程并下载其他的依赖库且添加不同的编译指令，这非常折磨人。如果有能力还是推荐直接更换系统到Ubuntu最新发行版。

**Comment by CLT96** [comment]
了解，非常感谢解答！我试一下ubuntu

**Comment by CLT96** [comment]
> centos使用的是yum而不是apt来获取软件包 关于_ssl问题，你可以在终端里使用python然后键入`import ssl`估计也会报错。
> 
> 在CentOS下要安装的包和Ubuntu里要安的包名称不一样，关于这点，你可以搜索关键词 "centos"。 在编译安装python前，你应该先编译安装最新版本的openssl。
> 
> 打击人的是，根据我的经验，即使安装好了ssl模块，估计还会有其他模块安装失败，这要让你再次重复上面的编译安装python过程并下载其他的依赖库且添加不同的编译指令，这非常折磨人。如果有能力还是推荐直接更换系统到Ubuntu最新发行版。

了解，非常感谢！我试一下ubuntu
