### ISSUE TITLE
机器人会自己停止运行

### ISSUE THREAD

**Issue by SecretLoved** [HibiKier/zhenxun_bot#354]
![image](https://user-images.githubusercontent.com/73172198/169259036-254a1bd2-5327-49c8-a0ff-756cb144e157.png)
会自己莫名其妙结束了

**Comment by MingxuanGame** [comment]
see #234

**Comment by SecretLoved** [comment]
> 
好的，我是运行了几个小时，然后突然停止，也适用这个方法吗？

**Comment by MingxuanGame** [comment]
> 好的，我是运行了几个小时，然后突然停止，也适用这个方法吗？

出现 killed 就是适用的
