### ISSUE TITLE
下载原神资源图标失败

### ISSUE THREAD

**Issue by fhyhy** [HibiKier/zhenxun_bot#355]
![QQ图片20220519171139](https://user-images.githubusercontent.com/66163285/169259229-22e64d93-903a-4d4a-856f-c26593b4b18d.png)
失败了就直接退出了,大佬有什么解决办法吗,或者说怎么关闭这个功能

**Comment by MingxuanGame** [comment]
你的 8080 端口被占用了

试着换一个端口

**Comment by fhyhy** [comment]
那这部分功能的端口在哪可以更换呢
