### ISSUE TITLE
saucenao的代理地址是订阅连接的地址吗

### ISSUE THREAD

**Issue by 1501853016** [HibiKier/zhenxun_bot#358]
saucenao的API已经填上了，返回服务器连接超时，问一下代理地址如何填写，和订阅链接有什么关系呢

**Comment by 181860143** [comment]
老哥你代理地址是怎么填写的呀

**Comment by LumineSakura** [comment]
> 老哥你代理地址是怎么填写的呀

v2rayn窗口界面左下角那个就是地址，就是最下面一行的http后面，开绕过大陆就行
