### ISSUE TITLE
请问在执行bot.py时出现这个问题怎么办，已经进入虚拟环境

### ISSUE THREAD

**Issue by Judp28** [HibiKier/zhenxun_bot#359]
![KJ3B3E{IHS3PQR_7PJMB}5L](https://user-images.githubusercontent.com/105803689/169271598-664b0b39-484c-410f-be10-0019bbd6d1bb.png)

**Comment by MingxuanGame** [comment]
你的 nonebot 和 nonebot2 混装了

```bash
pip uninstall nonebot
pip uninstall nonebot2
poetry install
playwright install chromium
```

试试

**Comment by Judp28** [comment]
> 你的 nonebot 和 nonebot2 混装了
> 
> ```shell
> pip uninstall nonebot
> pip uninstall nonebot2
> poetry install
> playwright install chromium
> ```
> 
> 试试
非常有用，谢谢你
