### ISSUE TITLE
更新原神今日素材失败

### ISSUE THREAD

**Issue by wanwdbb** [HibiKier/zhenxun_bot#36]
请问这个是不是chromium没安装好的原因，没在网上找到解决办法，希望能得到回答，谢谢！

![QQ截图20210901180116](https://user-images.githubusercontent.com/28987404/131659673-410b825e-9121-41d4-8bd8-5d9ae635f1c3.png)

**Comment by wanwdbb** [comment]
系统是

> 请问这个是不是chromium没安装好的原因，没在网上找到解决办法，希望能得到回答，谢谢！

> 系统是CentOS7

> ![QQ截图20210901180116](https://user-images.githubusercontent.com/28987404/131659673-410b825e-9121-41d4-8bd8-5d9ae635f1c3.png)

**Comment by wanwdbb** [comment]
> 请问这个是不是chromium没安装好的原因，没在网上找到解决办法，希望能得到回答，谢谢！
> 
> ![QQ截图20210901180116](https://user-images.githubusercontent.com/28987404/131659673-410b825e-9121-41d4-8bd8-5d9ae635f1c3.png)

**Comment by HibiKier** [comment]
环境没装好，少了libatk-1.0-so.0
