### ISSUE TITLE
bot.py打不开，python下载了好多个版本都是

### ISSUE THREAD

**Issue by xxr777** [HibiKier/zhenxun_bot#362]

**Comment by MingxuanGame** [comment]
log 呢

依赖安装了吗

```bash
pip install poetry
poetry install
poetry shell
playwright install chromium
python bot.py
```

**Comment by 1501853016** [comment]
先poetry shell
再py bot.py
每次启动好像都要这样

**Comment by xxr777** [comment]
> log 呢
> 
> 依赖安装了吗
> 
> ```shell
> pip install poetry
> poetry install
> poetry shell
> playwright install chromium
> python bot.py
> ```

我直接下载的压缩包解压的，然后怎么安装依赖呢

**Comment by MingxuanGame** [comment]
切到解压的目录运行

**Comment by MingxuanGame** [comment]
你的 python 安装时是否勾选了添加到 `PATH`

若没有，请尝试手动添加或卸载重装

**Comment by xxr777** [comment]
> 你的 python 安装时是否勾选了添加到 `PATH`
> 
> 若没有，请尝试手动添加或卸载重装

![image](https://user-images.githubusercontent.com/105805521/169505267-36c4ad44-4ff1-42d7-9996-ba26bf1538d2.png)
然后是这样的

**Comment by Sakuracio** [comment]
> > 你的 python 安装时是否勾选了添加到 `PATH`
> > 若没有，请尝试手动添加或卸载重装
> 
> ![image](https://user-images.githubusercontent.com/105805521/169505267-36c4ad44-4ff1-42d7-9996-ba26bf1538d2.png) 然后是这样的

@xxr777 Windows无需执行该命令
