### ISSUE TITLE
大佬们请问这个错误怎么解决

### ISSUE THREAD

**Issue by 80546033** [HibiKier/zhenxun_bot#363]
![image](https://user-images.githubusercontent.com/67412155/169274932-00baab81-e422-4b88-802f-e8dc9b588568.png)

**Comment by MingxuanGame** [comment]
你的 python 版本多少

**Comment by 80546033** [comment]
> 

3.8.9,我现在用的是服务器在装这个，win7系统只能装这个版本

**Comment by MingxuanGame** [comment]
能发一下你的 `config.py` 吗

**Comment by 80546033** [comment]
> 能发一下你的 `config.py` 吗



# 回复消息名称
NICKNAME: str = "小真寻"

# 数据库（必要）
# 如果填写了bind就不需要再填写后面的字段了#）
# 示例："bind": "postgresql://user:password@127.0.0.1:5432/database"
bind: str = ""  # 数据库连接链接
sql_name: str = "postgresql"
user: str = "wudi"  # 数据用户名
password: str = "123456"  # 数据库密码
address: str = "127.0.0.1"  # 数据库地址
port: str = "5432"  # 数据库端口
database: str = "bot"  # 数据库名称

# 代理，例如 "http://127.0.0.1:7890"
SYSTEM_PROXY: Optional[str] = None  # 全局代理


Config = ConfigsManager(Path() / "data" / "configs" / "plugins2config.yaml")

**Comment by 80546033** [comment]
> 能发一下你的 `config.py` 吗

不好意思大佬，我弄好了，因为不小心改了这个文件的格式，win7他是没换行和空格的，我吧我win11的配置直接粘贴上去弄错了
