### ISSUE TITLE
运行bot.py问题,已阅读相关issue仍未解决

### ISSUE THREAD

**Issue by YancyGuo** [HibiKier/zhenxun_bot#365]
操作系统window10
程序版本pg14
在config对着教程设置了也换了好几个pg版本,确定进入了部署环境以及连通了数据库
阅读了#194 以及#349 等类似issue还是没法解决.
附上配置图以及cmd部分过程
第一次部署环境,有劳大佬们解答一下~~thx

![`4RYOF 2LHMK~0CS_%SMLZL](https://user-images.githubusercontent.com/72378142/169276130-0f9713dd-a426-4bd8-8c1f-1cbc6647eb77.png)
![5OAEHO_0VFQYQHV853W(G76](https://user-images.githubusercontent.com/72378142/169276150-c5d8aa70-1c2e-40a3-afa1-000e27b1e468.png)
![C SNO67@5FBF~B{${QTBJ}N](https://user-images.githubusercontent.com/72378142/169276156-d9310c1a-5ffd-4491-b414-d3f3c12683b0.png)
类似与#251 与#349 
也照着 #323  自顾自加了一段,可能大佬们需要查看,先附上 pg_hba.conf了,麻烦大佬们了
[pg_hba.txt](https://github.com/HibiKier/zhenxun_bot/files/8728461/pg_hba.txt)

照着 #317  将python3.8升级到3.9,仍然未能解决,依旧是相同的多个modulenotFound.
[erro.txt](https://github.com/HibiKier/zhenxun_bot/files/8729618/erro.txt)

**Comment by HibiKier** [comment]
有点忘了，你把config.yaml删了再启动试试

**Comment by YancyGuo** [comment]
> 

由于没有成功启动bot.py 在\config下好像没有生成config.yaml

**Comment by HibiKier** [comment]
cmd也没事（大概，你先把data/configs文件夹和configs/config.yaml删了再启动吧

**Comment by Sakuracio** [comment]
在真寻目录执行 poetry run python bot.py 如果报错将日志截图发送

**Comment by YancyGuo** [comment]
> cmd也没事（大概，你先把data/configs文件夹和configs/config.yaml删了再启动吧

我将整个真寻的文件夹都删了重新从release上打包下载了zip,还是和上面截图的效果一样.

**Comment by HibiKier** [comment]
看日志我怎么感觉你是文件不全，你目录下真的models文件夹吗

**Comment by YancyGuo** [comment]
> 看日志我怎么感觉你是文件不全，你目录下真的models文件夹吗

没道理阿,我重新下载过一遍,models文件夹里面也有.py文件
![image](https://user-images.githubusercontent.com/72378142/169312314-fb986207-ed52-471a-a4f3-84e7a1729524.png)

**Comment by YancyGuo** [comment]
> 贴一下 poetry install 的结果 以及 pip freeze 的结果

麻烦大佬了
![OET14EZWJL~U39 UH4Q7L1J](https://user-images.githubusercontent.com/72378142/169314769-76d93dfb-24c7-49dc-8d69-aedff4c25eaa.png)

**Comment by Sakuracio** [comment]
删除 poetry.lock 文件 然后运行poetry install 可能需要等待十分钟左右 然后运行 poetry run python bot,py

**Comment by YancyGuo** [comment]
> 删除 poetry.lock 文件 然后运行poetry install 可能需要等待十分钟左右 然后运行 poetry run python bot,py

收到,感谢您的耐心指导

**Comment by YancyGuo** [comment]
> 留言企鹅号，我远程看看。

793073035

**Comment by YancyGuo** [comment]
回头转成linux虚拟机试试,大佬很热心~~
