### ISSUE TITLE
启动真寻出现的问题

### ISSUE THREAD

**Issue by hotwu0** [HibiKier/zhenxun_bot#366]
大佬们我现在这个问题咋解决

**Comment by hotwu0** [comment]
![Uploading K`~L{LJV20$LFPSKHWLAU1D.png…]()

**Comment by hotwu0** [comment]
![image](https://user-images.githubusercontent.com/105857571/169278857-a41a6ad1-1454-4bbb-9c1c-72c01fa84a98.png)

**Comment by zhanbao2000** [comment]
config.yaml 的语法有问题，找到 267 行 22 列修复语法错误后再尝试启动

**Comment by HibiKier** [comment]
或者删了config.yaml，重启会生成你上一次成功保存的配置
