### ISSUE TITLE
在启动bot.py时出现了问题

### ISSUE THREAD

**Issue by ayachimako** [HibiKier/zhenxun_bot#367]
操作系统Ubuntu 22.04
Python版本 3.10.4
![9IN0BUAQ7( `~L)PM4P@0(Y](https://user-images.githubusercontent.com/105858150/169281818-71920c39-7c84-4cf9-a5b9-4c48f36d482e.jpg)
看了相关的issues但还是不知道怎么解决...好像是版本问题？
![_LZ 0GD9L3_I96N7%P8BUN1](https://user-images.githubusercontent.com/105858150/169282373-13ad7d21-3f7e-45cd-be46-72013d8a4545.png)
在poetry install这一步骤看到版本对不上了，update了pip好像还是报错
求解决方式！！！孩子快看到胜利的终点了QAQ

**Comment by HibiKier** [comment]
文档不是写了要求3.8或3.9吗

**Comment by ayachimako** [comment]
看到了！我是瞎比，，，这就去试试
