### ISSUE TITLE
原神资源查询图片错位

### ISSUE THREAD

**Issue by jx9468** [HibiKier/zhenxun_bot#37]
这两天才出的问题，材料坐标和传说点之类的全都错位了😂就像所有坐标以某个·点向外扩张了一样
![2](https://user-images.githubusercontent.com/78193384/131806508-7da1fec9-433c-455d-a905-67b340471920.PNG)
![1](https://user-images.githubusercontent.com/78193384/131806572-8d6e136f-8ed5-467b-8604-525478d1c334.PNG)

**Comment by HibiKier** [comment]
你是改过代码了？截图看看plugins/genshin/query_resource_points/map.py中Map类的def __init__，另外，快用’更新原神资源信息’更新大地图

**Comment by jx9468** [comment]
> 你是改过代码了？截图看看plugins/genshin/query_resource_points/map.py中Map类的def **init**，另外，快用'更新原资源信息'更新大地图

OK，好了，只更新了材料信息不更新地图就会导致坐标错位，我才发现材料和地图不是同时更新的🤣
