### ISSUE TITLE
大佬求识图问题

### ISSUE THREAD

**Issue by ayanami648** [HibiKier/zhenxun_bot#370]
![捕获 222JPG](https://user-images.githubusercontent.com/105802556/169286799-56e7771c-e9b2-4856-b47c-fc333b43dbc0.JPG)
大佬识图的时候突然就不行了
上午还是好好的
配置如下
![捕获weqwe](https://user-images.githubusercontent.com/105802556/169287004-d2a1fd9e-02e8-4bd1-bc0d-9723258693b7.JPG)

**Comment by ayanami648** [comment]
上午还是好好的 群里其他人也能用

**Comment by HibiKier** [comment]
网络问题

**Comment by ayanami648** [comment]
好的大佬我看看他自己能不能恢复

**Comment by HibiKier** [comment]
最好挂代理

**Comment by ayanami648** [comment]
大佬挂了梯子了 我现在就在用梯子上github

**Comment by HibiKier** [comment]
config.py设置梯子地址了吗

**Comment by ayanami648** [comment]
![捕获qqqqq](https://user-images.githubusercontent.com/105802556/169301404-02f32295-9e8c-4021-99d2-061ea7ac7856.JPG)
大佬是这样配置吗

**Comment by ayanami648** [comment]
![捕获sssss](https://user-images.githubusercontent.com/105802556/169301600-f0e76c56-56f5-4195-af1f-21a51da6dbff.JPG)

**Comment by ayanami648** [comment]
![image](https://user-images.githubusercontent.com/105802556/169317278-b99b8d77-85b1-4475-ae31-1c51329e335b.png)

**Comment by ayanami648** [comment]
大佬 昨天的代理问题解决了非常感谢 一个新问题请教 能否可以做到群里每个人都能增减群词条呢 
![image](https://user-images.githubusercontent.com/105802556/169438472-0a03b817-c2e5-408c-b107-97fee3a2aa6e.png)
我是超级用户可以 别人就是这样  十分感谢
![image](https://user-images.githubusercontent.com/105802556/169438551-c466e2bc-9f0f-4ede-9f5c-b0524eb7c57d.png)

**Comment by ayanami648** [comment]
我自己是没问题的
![image](https://user-images.githubusercontent.com/105802556/169438646-9c87c1a4-49cc-44e6-bbee-4826a9ac5808.png)

**Comment by ayanami648** [comment]
请问大佬改哪个值呢
![image](https://user-images.githubusercontent.com/105802556/169443940-3ae1287a-8ef7-4251-8985-27d101915049.png)

**Comment by xAnYan** [comment]
> 大佬 昨天的代理问题解决了非常感谢 一个新问题请教 能否可以做到群里每个人都能增减群词条呢 ![image](https://user-images.githubusercontent.com/105802556/169438472-0a03b817-c2e5-408c-b107-97fee3a2aa6e.png) 我是超级用户可以 别人就是这样 十分感谢 ![image](https://user-images.githubusercontent.com/105802556/169438551-c466e2bc-9f0f-4ede-9f5c-b0524eb7c57d.png)

> 请问大佬改哪个值呢 ![image](https://user-images.githubusercontent.com/105802556/169443940-3ae1287a-8ef7-4251-8985-27d101915049.png)

根据[这篇文档](https://hibikier.github.io/zhenxun_bot/docs/help_doc/basic_plugins/common_plugins.html)，将`WORD_BANK_LEVEL`中的`value`对应值改为0即可。

**Comment by ayanami648** [comment]
好的我尝试一下

**Comment by ayanami648** [comment]
呜呜 我尝试了 他会自动变回5
![image](https://user-images.githubusercontent.com/105802556/169451750-4eca87f3-0bc9-457a-8c34-a7284d857a38.png)

**Comment by xAnYan** [comment]
> 好的我尝试一下

不要发送无意义内容，GitHub Issues并非通常意义上的论坛或社区，而是一个[邮件列表](https://zh.wikipedia.org/wiki/%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)。任何一条Comment都会通知到参与此Issue的全体成员，无意义内容会导致成员的邮箱被垃圾信息淹没。

- 若此问题已解决，请编辑标题和你的最后一条回复，追加`（已解决）`，并自行关闭此issue，这有助于项目方进行问题追踪，亦有助于后来者解决问题。

- 如果你遇到了新的、与此issue无关的问题，请创建新issue，而非在此issue上追加。

- 开源社区不是免费客服，对社区而言，贡献者的时间是最重要的稀缺资源之一。因此，在创建任何issue之前，请确保你已尝试过用**一切可能有效的手段**解决问题，包括仔细通读文档，或者备份配置文件后，根据文本提示试验性地修改一下某个看起来很可能有用的值。

- 建议在空闲时阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)，该文档描述了人们在GitHub和其他开源社区提问时应遵守的一般行为准则，有助于避免可能发生的不愉快。

**Comment by xAnYan** [comment]
> 呜呜 我尝试了 他会自动变回5 ![image](https://user-images.githubusercontent.com/105802556/169451750-4eca87f3-0bc9-457a-8c34-a7284d857a38.png)

请确认你修改的`value`还是`default_value`？另外，授予普通用户权限应赋值`0`，而非`1`。

**Comment by HibiKier** [comment]
权限会自动刷新，或者你自己手动上
