### ISSUE TITLE
有几个问题。。

### ISSUE THREAD

**Issue by Lightning627** [HibiKier/zhenxun_bot#371]
1. pix具体怎么用，一直提示找不到相关图片。下载的sql文件是mysql的，不能导入到pgsql。
2. windows怎么安装ffmpeg使用“骂我”命令。
3. 搜番会报错
![image](https://user-images.githubusercontent.com/23275257/169288418-45e26fc8-db42-4c4f-a0fd-ce5cc53feba3.png)

**Comment by LEorEu** [comment]
1.psql可以导入，看另一个issues #39 
2.ffmpeg看[go-cqhttp文档](https://docs.go-cqhttp.org/guide/quick_start.html#%E5%AE%89%E8%A3%85-ffmpeg)，设置完环境变量要重启电脑生效
3.网络问题
