### ISSUE TITLE
原神板块的yss和ys+id指令查询失败

### ISSUE THREAD

**Issue by 1501853016** [HibiKier/zhenxun_bot#372]
这个是要更新自己的cookie吗

**Comment by 1501853016** [comment]
> yss要自己的cookie

我绑定了自己的cookie的，可还是查询失败了

**Comment by MingxuanGame** [comment]
参考 #231 

米游社 API 地址变了

**Comment by HibiKier** [comment]
[@pull/357](https://github.com/HibiKier/zhenxun_bot/pull/357)

**Comment by 1501853016** [comment]
> [@pull/357](https://github.com/HibiKier/zhenxun_bot/pull/357)

搞好了，代理开绕过大陆就行得通了，之前开代理搞sauce搜图时开的全局

**Comment by SuLiuming** [comment]
请问下 你的保存是提示 Please login 么 个人目前遇到了 配置文件也看了 没找都在哪设置的  这个问题暂时不知道怎么解决
