### ISSUE TITLE
启动时bot报错

### ISSUE THREAD

**Issue by tibbar213** [HibiKier/zhenxun_bot#373]
ImportError: DLL load failed while importing cv2:找不到指定的模块
![image](https://user-images.githubusercontent.com/49330075/169295588-b08f57dc-ca29-4d11-8e3e-f97eeaa6b731.png)

**Comment by borntree** [comment]
我也买的这个服务器  哈哈哈  现在也是这个问题
![image](https://user-images.githubusercontent.com/82987943/170181443-155b4190-87fe-4a3c-9221-aafb6360f23d.png)
![image](https://user-images.githubusercontent.com/82987943/170181464-692b9b96-ba39-4274-a460-c4fb2d0e4535.png)
大哥你最后是怎么解决的啊，缺失了什么文件

**Comment by borntree** [comment]
兄弟还在吗 @tibbar213    我弄一下午了，一直循环在错误闭环出不去了
我安装 Windows Media Feature Pack时候提示
![image](https://user-images.githubusercontent.com/82987943/170227416-cc842598-ae9c-46ca-bc5a-29db976973a3.png)
然后我解决这个错误时候用win+r运行regsvr32 softpub.dll    regsvr32 wintrust.dll     regsvr32 initpki.dll 
又出现缺失initpki.dll
我去下载了一个initpki.dll结果又是不支持64位操作系统    也找不到64位操作系统的   请问你是如何解决的呢

**Comment by borntree** [comment]
解决了
