### ISSUE TITLE
大佬求p站相关问题

### ISSUE THREAD

**Issue by AlanMULI** [HibiKier/zhenxun_bot#374]
p搜不能下载图片、p站排行只有文字没有图片。
是网络问题吗？
另外，我在ubuntu系统里配置了代理，config.py里的代理我不知道该修改哪个参数，想问一下optional[str] = None里的str和none分别是什么意思。。

**Comment by Sakuracio** [comment]
> 代理，例如 "http://127.0.0.1:7890"
> SYSTEM_PROXY: Optional[str] = None  # 全局代理
e.g.
SYSTEM_PROXY: Optional[str] = http://127.0.0.1:7890
SYSTEM_PROXY: Optional[str] = https://127.0.0.1:7890
SYSTEM_PROXY: Optional[str] = socks5://127.0.0.1:7890

**Comment by AlanMULI** [comment]
问题已解决：执行命令`pip install pysocks`
