### ISSUE TITLE
webui登陆时432  请求头超限 请问这个怎么解决

### ISSUE THREAD

**Issue by AngelBeats401** [HibiKier/zhenxun_bot#376]
![U5G0JTE2NB6YR~RJ0GV@{~0](https://user-images.githubusercontent.com/65359943/169300570-2de79e16-42cc-4a1c-a95b-87dc1a480364.png)

**Comment by AngelBeats401** [comment]
![@FXZQ8M4Z92Q38)RMJOJCFJ](https://user-images.githubusercontent.com/65359943/169301219-fe258648-4853-462a-9707-63edb578290c.png)
配置文件

**Comment by Sakuracio** [comment]
如非必要 可以不使用 WebUI 它并不影响 Bot 运行

**Comment by AngelBeats401** [comment]
都配置都完成了  但是机器人没反应 这个徐亚设置什么么

**Comment by AngelBeats401** [comment]
> 如果它非必要可以不使用 WebUI 不影响 Bot 运行


都配置都完成了 机器人没有反应  请问还需要设置什么么

**Comment by Sakuracio** [comment]
提供一下日志

**Comment by AngelBeats401** [comment]
![B{I%_I6ZI XBFX HH)AJ$)2](https://user-images.githubusercontent.com/65359943/169304195-45fa5a46-5899-46ab-ba9b-df345a78d956.png)


> 提供一下日志

**Comment by MingxuanGame** [comment]
请问你的 nonebot 开启了吗

**Comment by AngelBeats401** [comment]
> 

请问是在哪里开启的   这边应该是没开

**Comment by AngelBeats401** [comment]
> 请问你的 nonebot 开启了吗

请问是在哪里开启的 这边应该是没开

**Comment by MingxuanGame** [comment]
`python bot.py`

**Comment by AngelBeats401** [comment]
> `python bot.py`

这个已经开启了
![Uploading %RAQ%K6V@$PULAW61D]WDOK.png…]()

**Comment by AngelBeats401** [comment]
> `python bot.py`

![%RAQ%K6V@$PULAW61D WDOK](https://user-images.githubusercontent.com/65359943/169305606-4f791d3a-2e60-41e2-bd4a-22a9ce396382.png)
已经开启了的

**Comment by MingxuanGame** [comment]
> > `python bot.py`
> 
> ![%RAQ%K6V@$PULAW61D WDOK](https://user-images.githubusercontent.com/65359943/169305606-4f791d3a-2e60-41e2-bd4a-22a9ce396382.png) 已经开启了的

你这已经退出了

**Comment by AngelBeats401** [comment]
> > > `python bot.py`
> > 
> > 
> > ![%RAQ%K6V@$PULAW61D WDOK](https://user-images.githubusercontent.com/65359943/169305606-4f791d3a-2e60-41e2-bd4a-22a9ce396382.png) 已经开启了的
> 
> 你这已经退出了

webui 可以进行插件和权限设置吗

**Comment by Sakuracio** [comment]
再次重复一遍 不建议使用WebUI 这仍是一个开发版本 会导致错误
