### ISSUE TITLE
webui网址无法进入

### ISSUE THREAD

**Issue by VanLewis2003** [HibiKier/zhenxun_bot#378]
阿里云服务器，Ubuntu系统，bot正常能跑，想试试webui怎么操作，按安装文档操作成功跑了起来，使用服务器ip登入时无法加载，防火墙都关了，实在想不到哪方面出了问题，请求大佬帮助一下
![image](https://user-images.githubusercontent.com/93692468/169307612-c4ec154a-be9e-4874-b48f-c78d4843381a.png)
![image](https://user-images.githubusercontent.com/93692468/169308042-e2b88494-8fbd-42a4-bbd6-f9a4499ffe00.png)
![image](https://user-images.githubusercontent.com/93692468/169312596-34a55851-0572-41cf-9e2c-04a317c0fe6d.png)

**Comment by HibiKier** [comment]
你服务器安全组端口开了吗

**Comment by AngelBeats401** [comment]
阿里云服务器要在阿里云控制台开启端口 还要在服务器本事防火墙开启端口才行正常访问
阿里云要开两个
