### ISSUE TITLE
关于pix命令的问题

### ISSUE THREAD

**Issue by 283Gawin** [HibiKier/zhenxun_bot#379]
![image](https://user-images.githubusercontent.com/69577009/169316067-72f05d41-df95-4df3-ae1a-f129041a2dcc.png)
如图输入pix黑丝 2后命令行报错，看起来是数据类型错误，不知道是哪里出了问题，希望有大佬解答

**Comment by HibiKier** [comment]
你config.yaml配置填坏了

**Comment by HibiKier** [comment]
不是啊，为什么要弄成字符串，原来就是数字啊

**Comment by 283Gawin** [comment]
> 不是啊，为什么要弄成字符串，原来就是数字啊

谢谢，已解决。
