### ISSUE TITLE
模块报错

### ISSUE THREAD

**Issue by yusana213214** [HibiKier/zhenxun_bot#38]
send_setu，use，open_cases，sign_in，四个模块报错no module named model_sign_group_user

**Comment by HibiKier** [comment]
稍等，一会0.0.4.2

**Comment by yusana213214** [comment]
> 稍等，一会0.0.4.2

草

**Comment by HibiKier** [comment]
update_info.json写的问题

**Comment by HibiKier** [comment]
现在试试

**Comment by yusana213214** [comment]
> 现在试试

更新未知错误 998
第二次尝试，未知错误999

**Comment by meng-luo** [comment]
是不是少
![Snipaste_2021-09-05_13-52-19](https://user-images.githubusercontent.com/79274361/132116948-c8cd0489-d222-4438-ba74-ed829f2e4eda.png)
写了逗号

**Comment by yusana213214** [comment]
> 是不是少
> ![Snipaste_2021-09-05_13-52-19](https://user-images.githubusercontent.com/79274361/132116948-c8cd0489-d222-4438-ba74-ed829f2e4eda.png)
> 写了逗号

母鸡啊，电脑不在身边，编辑不了py文件

**Comment by HibiKier** [comment]
是少了逗号。。

**Comment by yusana213214** [comment]
> 是少了逗号。。

是我的错觉吗，，，更新0043报错200

**Comment by HibiKier** [comment]
没事，200不用管，已经改了

**Comment by yusana213214** [comment]
> 没事，200不用管，已经改了

那个输出更新日志那个图看着太费力了，稍微改下图片尺寸吧

**Comment by HibiKier** [comment]
尺寸能改，超管要被限制功能的话可以删除plugins/hook.py第167行
```
or str(event.user_id) in bot.config.superusers
````
另外，cos API找的几个貌似都不怎么好用，慢慢找了

**Comment by yusana213214** [comment]
> 尺寸能改，超管要被限制功能的话可以删除plugins/hook.py第167行
> 
> ```
> or str(event.user_id) in bot.config.superusers
> ```
> 
> 另外，cos API找的几个貌似都不怎么好用，慢慢找了

就是单纯超管也不想触发ai

**Comment by HibiKier** [comment]
> 
> 
> > 尺寸能改，超管要被限制功能的话可以删除plugins/hook.py第167行
> > ```
> > or str(event.user_id) in bot.config.superusers
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外，cos API找的几个貌似都不怎么好用，慢慢找了
> 
> 就是单纯超管也不能触发ai
plugins/hook.py第167行修改
```python
or (str(event.user_id) in bot.config.superusers and matcher.module != 'ai')
```

**Comment by yusana213214** [comment]
> > > 尺寸能改，超管要被限制功能的话可以删除plugins/hook.py第167行
> > > ```
> > > or str(event.user_id) in bot.config.superusers
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 另外，cos API找的几个貌似都不怎么好用，慢慢找了
> > 
> > 
> > 就是单纯超管也不能触发ai
> > plugins/hook.py第167行修改
> 
> ```python
> or (str(event.user_id) in bot.config.superusers and matcher.module != 'ai')
> ```

167行是个人权限相关的hook啊，，，不是限制的，是不是哪里弄错了

**Comment by HibiKier** [comment]
没，那个函数不仅包含个人权限，也包含功能权限的检测

**Comment by yusana213214** [comment]
> 没，那个函数不仅包含个人权限，也包含功能权限的检测

![AP703D})O8RQCF}PHJJOGLR](https://user-images.githubusercontent.com/35253755/133180109-9e9282cb-a774-4dab-b0ba-af2f76ba2e88.png)

完全不懂

**Comment by HibiKier** [comment]
![0DD$3 TA1GXD}C$8KFQ$%L9](https://user-images.githubusercontent.com/45528451/133217993-d22e7cc7-2328-47b9-bd6e-e472c2143ead.png)

**Comment by yusana213214** [comment]
我还是觉得有必要在配置文件层添加一个超级用户受限开关，不然很容易造成别人无法触发，我无视功能状态触发，很讨厌，总体讲，AI功能在某一些群非常反感

**Comment by HibiKier** [comment]
行，不过这个初衷是给超级用户的特权

**Comment by yusana213214** [comment]
> 行，不过这个初衷是给超级用户的特权

我记得nb2不是有个网络测试插件吗，，，或许可以考虑魔改一下

**Comment by HibiKier** [comment]
已提供 超级用户权限限制 和 黑名单群 限制
