### ISSUE TITLE
机器人开一会他就不会自动回消息了，一定要点一下go-cqhttp的窗口才行，有啥解决办法不

### ISSUE THREAD

**Issue by NGPhoenixair** [HibiKier/zhenxun_bot#383]

**Comment by NGPhoenixair** [comment]
> ![图片](https://user-images.githubusercontent.com/29254102/169329301-77442714-db45-4c54-8e57-dbdaade7aa61.png)
> 
> 尝试取消勾选 ，然后看一下问题有无解决？`快速编辑模式`

我打开属性发现这已经是开的了，让我放一晚上看他停不停

**Comment by Misaka12456** [comment]
> > ![图片](https://user-images.githubusercontent.com/29254102/169329301-77442714-db45-4c54-8e57-dbdaade7aa61.png)
> > 尝试取消勾选 ，然后看一下问题有无解决？`快速编辑模式`
> 
> 我打开属性发现这已经是开的了，让我放一晚上看他停不停

他是让你把这个取消勾选……

**Comment by HibiKier** [comment]
hhhhh

**Comment by NGPhoenixair** [comment]
> > > ![图片](https://user-images.githubusercontent.com/29254102/169329301-77442714-db45-4c54-8e57-dbdaade7aa61.png)
> > > 尝试取消勾选 ，然后看一下问题有无解决？`快速编辑模式`
> > 
> > 
> > 我打开属性发现这已经是开的了，让我放一晚上看他停不停
> 
> 他是让你把这个取消勾选……

说的好，以后让真寻每天骂我一遍不长眼睛
