### ISSUE TITLE
运行python3 bot.py后到Uvicorn running on卡住了

### ISSUE THREAD

**Issue by lolng** [HibiKier/zhenxun_bot#386]
05-19 23:27:43 [INFO] uvicorn | Started server process [4665]
05-19 23:27:43 [INFO] uvicorn | Waiting for application startup.
05-19 23:27:43 [INFO] services | Database loaded successfully!
/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/apscheduler/triggers/cron/__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum
/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/apscheduler/triggers/cron/__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
/root/.cache/pypoetry/virtualenvs/zhenxun-bot-guhZIsCX-py3.8/lib/python3.8/site-packages/apscheduler/triggers/interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)
05-19 23:27:43 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-19 23:27:44 [INFO] basic_plugins | 已成功加载 59 个非限制插件.
05-19 23:27:44 [INFO] utils | 已成功加载 5 个Cd限制.
05-19 23:27:44 [INFO] utils | 已成功加载 12 个Block限制.
05-19 23:27:44 [INFO] utils | 已成功加载 1 个Count限制.
05-19 23:27:50 [INFO] basic_plugins | 初始化数据完成...
05-19 23:27:50 [WARNING] plugins | pretty_up_char 解析出错
05-19 23:27:51 [INFO] plugins | 更新原神资源类型成功...
05-19 23:27:51 [INFO] uvicorn | Application startup complete.
05-19 23:27:51 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)

到这就卡住了没有后续反应

**Comment by MingxuanGame** [comment]
请问你的 go-cqhttp 是否成功连接？

**Comment by lolng** [comment]
@MingxuanGame go-chttp在运行可以收发消息

**Comment by SEAFHMC** [comment]
gocq里面有填反向ws地址吗

**Comment by HibiKier** [comment]
gocq没连上啊

**Comment by lolng** [comment]
> gocq没连上啊

![VXKY9)W9{TK%2WGY5RRD_73](https://user-images.githubusercontent.com/105873686/169441999-9115cd82-9b98-4b37-a6af-8a2a3579afe2.png)
![WWE$@A`NF}@F8$ZOFU8B5HT](https://user-images.githubusercontent.com/105873686/169442152-bf36c8f3-f2be-43b3-8c07-2fba03ca65bc.png)

![Y}_G_N{ GRO00YCP66~%H)2](https://user-images.githubusercontent.com/105873686/169442049-a7501970-7ae8-4bd5-8054-906b14005009.png)
![P9AHXGD`LZ}}BUHQX1X3X{J](https://user-images.githubusercontent.com/105873686/169442062-e65e99b7-2c34-456a-99db-69a960a5066a.png)
这个情况

**Comment by MingxuanGame** [comment]
你试试等待一下

还有 ip 记得打码，然后把 comment 记录删除

**Comment by SEAFHMC** [comment]
emmm， 你运行真寻的时候gocq有在后台运行吗？ 是否有使用类似screen的方式使其后台运行

**Comment by lolng** [comment]
> emmm， 你运行真寻的时候gocq有在后台运行吗？ 是否有使用类似screen的方式使其后台运行

gocq用的nohup
真寻用的screen
