### ISSUE TITLE
碧蓝航线抽卡出错

### ISSUE THREAD

**Issue by chara1051** [HibiKier/zhenxun_bot#387]
![Uploading 1148dfb95bfde5d.png…]()

**Comment by chara1051** [comment]
![Uploading Screenshot_20220519_232324_com.microsoft.rdc.android_edit_2037216330417.jpg…]()

**Comment by MingxuanGame** [comment]
用图床这些东西

图片你没传上来

**Comment by chara1051** [comment]
> 用图床这些东西
> 
> 图片你没传上来
![36440ee21a93372f](https://user-images.githubusercontent.com/105768555/169351536-c3c91172-daa7-491d-9cc1-c3d3f5254384.jpg)
![34441af358f89e23](https://user-images.githubusercontent.com/105768555/169351552-93c96f9e-6cbf-4951-9867-e60f08c4c68f.jpg)

**Comment by MingxuanGame** [comment]
似乎是页面改了(#218)

没法爬到数据

等待修复吧

**Comment by chara1051** [comment]
> 似乎是页面改了(#218)
> 
> 没法爬到数据
> 
> 等待修复吧

好的
