### ISSUE TITLE
配置代理后，要发图的功能都用不了了

### ISSUE THREAD

**Issue by AlanMULI** [HibiKier/zhenxun_bot#389]
<img width="935" alt="Screenshot 2022-05-20 at 00 05 02" src="https://user-images.githubusercontent.com/20946955/169346453-6439ccd6-1b55-451d-8a11-a7a27c2658c3.png">
包括签到、帮助等功能的错误均是这个，怀疑是图片走代理服务器传输不到gocq，求问解决方法。

**Comment by AlanMULI** [comment]
但是色图、p搜等均正常

**Comment by MingxuanGame** [comment]
go-cqhttp 能发出图片吗

**Comment by AlanMULI** [comment]
> 

其他要发图的功能也可以用，所以应该是能发出图片的？

**Comment by MingxuanGame** [comment]
> 其他要发图的功能也可以用，所以应该是能发出图片的？

那就是 gocq 能发出图片，但是 nonebot 报错

应该是 gocq 发图片发太久了，nonebot 等待返回超时报错了
