### ISSUE TITLE
色图sql无法导入

### ISSUE THREAD

**Issue by Raysamatoken** [HibiKier/zhenxun_bot#39]
sql文件解压到bot目录启动后，直接死机了（我用的性能低的小主机），sql文件是mysql的格式用navicat无法导入，请问有什么好的解决办法吗。

**Comment by HibiKier** [comment]
[xx.zip](https://github.com/HibiKier/zhenxun_bot/files/7113326/xx.zip)
psql导出的数据库，应该可以手动导入

**Comment by Raysamatoken** [comment]
> [xx.zip](https://github.com/HibiKier/zhenxun_bot/files/7113326/xx.zip)
> psql导出的omega数据表，应该可以手动导入

感谢，使用pg_restore成功导入
