### ISSUE TITLE
请问被动在comfig.yaml中关闭了还是会到时发消息

### ISSUE THREAD

**Issue by yangwangkong** [HibiKier/zhenxun_bot#390]
如题，我想关闭早晚安、开箱重置和原神老黄历
`_task:
  DEFAULT_GROUP_WELCOME: true
  DEFAULT_REFUND_GROUP_REMIND: true
  DEFAULT_BROADCAST: true
  DEFAULT_ZWA: false
  DEFAULT_FUDU: true
  DEFAULT_PA: true
  DEFAULT_GENSHIN_ALC: false
  DEFAULT_EPIC_FREE_GAME: false
  DEFAULT_BILIBILI_PARSE: true
  DEFAULT_OPEN_CASE_RESET_REMIND: false`

**Comment by NekoInValkyr** [comment]
请问一下config.yaml这个文件是在哪个位置

**Comment by yangwangkong** [comment]
在configs文件夹下边

--------------原始邮件--------------
发件人："NekoInValkyr ***@***.***&gt;;
发送时间：2022年5月20日(星期五) 凌晨0:32
收件人："HibiKier/zhenxun_bot" ***@***.***&gt;;
抄送："杨滢榕 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [HibiKier/zhenxun_bot] 请问被动在comfig.yaml中关闭了还是会到时发消息 (Issue #390)
-----------------------------------

 

 
请问一下config.yaml这个文件是在哪个位置

**Comment by chara1051** [comment]
> 如题，我想关闭早晚安、开箱重置和原神老黄历 `_task: DEFAULT_GROUP_WELCOME: true DEFAULT_REFUND_GROUP_REMIND: true DEFAULT_BROADCAST: true DEFAULT_ZWA: false DEFAULT_FUDU: true DEFAULT_PA: true DEFAULT_GENSHIN_ALC: false DEFAULT_EPIC_FREE_GAME: false DEFAULT_BILIBILI_PARSE: true DEFAULT_OPEN_CASE_RESET_REMIND: false`

好像可以在QQ里直接关
![Uploading Screenshot_20220520_003538_com.tencent.mobileqq.jpg…]()

**Comment by chara1051** [comment]
> 如题，我想关闭早晚安、开箱重置和原神老黄历 `_task: DEFAULT_GROUP_WELCOME: true DEFAULT_REFUND_GROUP_REMIND: true DEFAULT_BROADCAST: true DEFAULT_ZWA: false DEFAULT_FUDU: true DEFAULT_PA: true DEFAULT_GENSHIN_ALC: false DEFAULT_EPIC_FREE_GAME: false DEFAULT_BILIBILI_PARSE: true DEFAULT_OPEN_CASE_RESET_REMIND: false`

![Uploading 192066ed049eea.jpg…]()

**Comment by NekoInValkyr** [comment]
大佬，在yarn run 那一步执行后，弹出来Note that the development build is not optimized. 这个有办法解决吗？

**Comment by chara1051** [comment]
![Uploading 192066ed049eea.jpg…]()

**Comment by HibiKier** [comment]
因为配置文件里存的只影响之后加的群

**Comment by yangwangkong** [comment]
那我退群重加可以么

--------------原始邮件--------------
发件人："HibiKier ***@***.***&gt;;
发送时间：2022年5月20日(星期五) 上午8:31
收件人："HibiKier/zhenxun_bot" ***@***.***&gt;;
抄送："杨滢榕 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [HibiKier/zhenxun_bot] 请问被动在comfig.yaml中关闭了还是会到时发消息 (Issue #390)
-----------------------------------

 

 
因为配置文件里存的只影响之后加的群

**Comment by yangwangkong** [comment]
> 

没看到你的图，能再发一次吗

**Comment by HibiKier** [comment]
> 那我退群重加可以么 。。。退群重加一样发。。。
> […](#)
> --------------原始邮件-------------- 发件人："HibiKier ***@***.***&gt;; 发送时间：2022年5月20日(星期五) 上午8:31 收件人："HibiKier/zhenxun_bot" ***@***.***&gt;; 抄送："杨滢榕 ***@***.***&gt;;"Author ***@***.***&gt;; 主题：Re: [HibiKier/zhenxun_bot] 请问被动在comfig.yaml中关闭了还是会到时发消息 (Issue #390) ----------------------------------- 因为配置文件里存的只影响之后加的群 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

把data/manage/group_manage删了重启就行了

**Comment by EvanFried** [comment]
> > 那我退群重加可以么 。。。退群重加一样发。。。
> > […](#)
> > --------------原始邮件-------------- 发件人："HibiKier _**@**_._**>; 发送时间：2022年5月20日(星期五) 上午8:31 收件人："HibiKier/zhenxun_bot" _**@**_.**_>; 抄送："杨滢榕 _**@**_._**>;"Author _**@**_.**_>; 主题：Re: [HibiKier/zhenxun_bot] 请问被动在comfig.yaml中关闭了还是会到时发消息 (Issue #390) ----------------------------------- 因为配置文件里存的只影响之后加的群 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 把data/manage/group_manage删了重启就行了
i
我感觉我这也是一样的问题。事情发展是这样的。
1、我想去sign_group_users直接修改impression好感度。修改完之后重启，在群里发送好感度发现还是没有修改。
![image](https://user-images.githubusercontent.com/52389532/169534032-030f962d-cf0e-4254-8332-8f87128103a3.png)
2、于是我就换了个方向，我选择直接修改INITIAL_SETU_PROBABILITY初始色图概率，从0.7变成了1，我改了大概两个地方config.yaml和data/config/plugins2config.yaml因为我看到了config.py的路径到了那里。
![image](https://user-images.githubusercontent.com/52389532/169534555-d1d3d334-3586-4885-8e9c-132d97173fb4.png)
![image](https://user-images.githubusercontent.com/52389532/169534278-5d056852-85dc-4393-adf2-923e45235530.png)
![image](https://user-images.githubusercontent.com/52389532/169534446-d8dfcf98-9c80-4d6b-acfc-811528983b85.png)
重启，发送好感度，发现还是没修改。
3、于是我直接找代码，我找到了sign_in的util，我直接把那个gold变量改成了数字的123456，重启之后发现他还是我的金币量(这个金币量我在数据库修改是生效的)
![image](https://user-images.githubusercontent.com/52389532/169535200-bf4e02e0-181f-4cd3-b805-2b46205a3985.png)
4、最后我今天的探索以失败告终，我中间尝试着删过几次config.yaml或者是data/manage，也还是这样的结果。

**Comment by HibiKier** [comment]
因为签到图片是有缓存的
