### ISSUE TITLE
求助为什么我没有config.yaml文件

### ISSUE THREAD

**Issue by NekoInValkyr** [HibiKier/zhenxun_bot#391]
已经做到yarn run serve这一步了 然后弹出来Note that the development build is not optimized.

**Comment by HibiKier** [comment]
因为config.yaml是真寻生成的，在configs/config.yaml

**Comment by NekoInValkyr** [comment]
> 因为config.yaml是真寻生成的，在configs/config.yaml

也就是说，我的python3 bot.py没有编译完全嘛

**Comment by HibiKier** [comment]
你看看你跑成功没有，最后报错也是无法生成的
