### ISSUE TITLE
机器人的一些报错

### ISSUE THREAD

**Issue by SecretLoved** [HibiKier/zhenxun_bot#392]
![image](https://user-images.githubusercontent.com/73172198/169348712-43995528-409e-4731-be39-79e1c58a962e.png)

**Comment by SecretLoved** [comment]
![image](https://user-images.githubusercontent.com/73172198/169351811-7e3a7c42-f4fb-46eb-94b9-bfc4168ebd47.png)

**Comment by MingxuanGame** [comment]
似乎是你的浏览器寄了

重启看看

**Comment by SecretLoved** [comment]
> 似乎是你的浏览器寄了
> 
> 重启看看

重启过了，还是一样

**Comment by MingxuanGame** [comment]
```bash
playwright install chromium
# 如果是 Ubuntu/Debian 这个也输入
playwright install-deps chromium
```
试一下

**Comment by SecretLoved** [comment]
> ```shell
> playwright install chromium
> # 如果是 Ubuntu/Debian 这个也输入
> playwright install-deps chromium
> ```
> 
> 试一下

我是Centos 用yum装了chromium的依赖项

**Comment by HibiKier** [comment]
更新代码试一试
