### ISSUE TITLE
怎么获取超级用户权限

### ISSUE THREAD

**Issue by zynetc** [HibiKier/zhenxun_bot#393]
怎么获取超级用户权限，怎么更改群权限，文件里改吗

**Comment by chara1051** [comment]
> 怎么获取超级用户权限，怎么更改群权限，文件里改吗

超级用户在文件里填qq教程里有，群权限可以在QQ里改

**Comment by zynetc** [comment]
> > 怎么获取超级用户权限，怎么更改群权限，文件里改吗
> 
> 超级用户在文件里填qq教程里有，群权限可以在QQ里改

我改了根目录里的那个文件，但是没反应，不是那里吗

**Comment by MingxuanGame** [comment]
参考文档:https://v2.nonebot.dev/docs/tutorial/configuration#superusers

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169431550-cd2b2cbf-9bb0-41f1-990a-d2193721bd15.png)
![图片](https://user-images.githubusercontent.com/45528451/169431566-9d3bf03b-3374-4c1f-8ad5-0dd98360cbd7.png)
