### ISSUE TITLE
关于网易云点歌问题，求解

### ISSUE THREAD

**Issue by a3162368** [HibiKier/zhenxun_bot#394]
点歌不论输入什么都是几首莫名其妙的歌随机出来

**Comment by HibiKier** [comment]
网易云api的问题，应该过段时间就好了，是国外的服务器吗？

**Comment by a3162368** [comment]
对 国外的服务器

**Comment by Fengshou-Xu** [comment]
> 对 国外的服务器

你可以试试更改hosts文件 把music.163.com强制解析成45.254.48.1 应该就好了
我是本地挂上了vpn 虽然有选绕过lan和China
后面要是有问题可以去ipip.net查music.163.com的ip就行
