### ISSUE TITLE
在登入webui时出现未知错误

### ISSUE THREAD

**Issue by MarmotSun** [HibiKier/zhenxun_bot#395]
![image](https://user-images.githubusercontent.com/73126692/169374622-98378ac6-dfb3-4fc5-8a70-e659ece8b6f6.png)
大佬们，这个是什么问题？已经在webui文件夹里面运行了yarn serve，登录账号和密码在bot文件夹的config.yml里设置了，但是不知道为什么出现这个问题，无论我是否输入了正确的账号密码，都是如此

**Comment by MarmotSun** [comment]
![image](https://user-images.githubusercontent.com/73126692/169376563-ec6a0814-0417-47ab-995f-87290019b2f3.png)
是因为这个吗，但是我不知道怎么解决XD

**Comment by HibiKier** [comment]
因为你bot没开起来，看你bot日志大概是端口被占用了

**Comment by MarmotSun** [comment]
> 因为你bot没开起来，看你bot日志大概是端口被占用了

好的，我这就去试

**Comment by MarmotSun** [comment]
> 因为你bot没开起来，看你bot日志大概是端口被占用了

感谢大佬，进去后台了
