### ISSUE TITLE
识图报错

### ISSUE THREAD

**Issue by LoliconXX** [HibiKier/zhenxun_bot#396]
![QQ截图20220520025325](https://user-images.githubusercontent.com/35798517/169379605-9d7c45bf-85de-4c7a-bed8-33363670769e.png)

**Comment by HibiKier** [comment]
每张图都这样吗

**Comment by changgongz** [comment]
> 每张图都这样吗

有时候有，有时候没有，把出问题的两行代码注释可以运行，但是识图结果没有源地址

**Comment by HibiKier** [comment]
> 

这方面先当做bug吧，周末看看

**Comment by LoliconXX** [comment]
> 每张图都这样吗

刚试了下，确实是部分图片会出现这个问题

**Comment by HibiKier** [comment]
忘了哪个push，已修
