### ISSUE TITLE
cqhttp尝试连接反向websocket Universal服务器失败

### ISSUE THREAD

**Issue by flower-knight** [HibiKier/zhenxun_bot#397]
因为库没了群也没了，所以我弄了docker版的机器人。但是在cqhttp连接zhenxun_bot时报了这个错。cqhttp和真寻都分配了独立ip，所以不存在端口没映射的情况。cqhttp同时还被另外一个机器人qqbot使用。
<img width="670" alt="Snipaste_2022-05-20_03-29-57" src="https://user-images.githubusercontent.com/75349850/169387394-36f35e12-382b-4cbe-b940-c114684ebebf.png">

**Comment by HibiKier** [comment]
你bot没开

**Comment by JPAdCoder** [comment]
你启动了zhenxun-bot然后就好了
