### ISSUE TITLE
关于web ui无法进入真寻后台的问题

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#398]
真寻多数功能已可以使用，但是无法进入web-ui后台  
![image](https://user-images.githubusercontent.com/50237543/169406752-e52459a6-f713-4611-87d5-1af8e090d5e4.png)
↑我根据运行结果中3000将vue.config中port端口改为了3000，不知道是否正确
以及华为云接口管理中无任何记录，是因为他系统升级中的问题吗？
![image](https://user-images.githubusercontent.com/50237543/169407202-5831b275-a191-4d77-9bd3-00d002b7a0a1.png)
在接口管理中找不到任何记录...（或者改用别的云端服务？该再哪改欸
防火墙全关了，主要就是想连上web-ui（以及如果配置都好了后我应该用Local访问还是network端口访问，萌新瑟瑟发抖

**Comment by HibiKier** [comment]
如果你在本地，直接localhost:3000就行了，外网就要安全组开放端口 ip:3000

**Comment by JPAdCoder** [comment]
看你描述应该是使用华为云，先用在线的[端口监测工具](http://coolaf.com/tool/port)测一下有没有开放
已经开放是这样的
![image](https://user-images.githubusercontent.com/28727241/169445491-8dd64f6c-c60d-4412-9d59-5e3bbae3df20.png)
没有开放的话登录华为云找到云主机控制台，我使用的HECS，大约在这个位置
![image](https://user-images.githubusercontent.com/28727241/169445191-f7f13c21-9006-4285-9822-905c3475ceaf.png)
记下你在用的是哪个安全组然后点开点新建安全组
![image](https://user-images.githubusercontent.com/28727241/169444945-5dc04f98-ce9e-4743-b2ad-2e342269e778.png)
找你在用的那个安全组然后点后边的管理规则
![image](https://user-images.githubusercontent.com/28727241/169444971-2fbfcd3f-7cd0-4254-8f11-b64fadb3ee5e.png)
然后在入口规则下边找找对应的端口有没有开放
![image](https://user-images.githubusercontent.com/28727241/169445018-582842af-f03d-41ec-8b00-19c35d20029e.png)
没有开放的话直接添加规则就可以了

**Comment by dick0841** [comment]
啊我原以为我用的是华为云，但是实际上好像是个叫ALAPI的东西。ALAPI是我从config/config.yaml文件alapi中找到的，我以为它跟web-ui功能相关
![image](https://user-images.githubusercontent.com/50237543/169495321-7802a88b-6d5d-4ef8-814e-4020bd467db4.png)
所以我目前先没配置华为云，按HibiKier佬的方法得到如图界面，请问这样正确吗
![image](https://user-images.githubusercontent.com/50237543/169495814-044fd796-58e9-4e29-b1c9-c65d433ca061.png)
我以为应该得到这样的界面才对
![image](https://user-images.githubusercontent.com/50237543/169508510-e135f36b-d0b0-47d3-9f80-acd847ff0b41.png)
非常感谢QwQ
