### ISSUE TITLE
识图后开始处理图片，然后就没有反应了

### ISSUE THREAD

**Issue by TreesFeather** [HibiKier/zhenxun_bot#399]
![QQ截图20220520080738](https://user-images.githubusercontent.com/105774046/169423627-b4517618-d3c7-4e76-843e-f73c49a035da.png)

![image](https://user-images.githubusercontent.com/105774046/169423639-7b329a32-035a-4bfc-8682-91005d1104b4.png)
API_KET已经填写过了，顺便问一下梯子怎么挂（详细一点），本人纯纯的小白，谢谢大佬们QAQ

**Comment by HibiKier** [comment]
每张图都这样？

**Comment by TreesFeather** [comment]
> 每张图都这样？

是的，试了好几次都是这样

**Comment by HibiKier** [comment]
api key是正确的吗

**Comment by TreesFeather** [comment]
> api key是正确的吗
检查了一下，key的话没有问题，前面也留了空格

**Comment by HibiKier** [comment]
图片方便发一下吗

**Comment by TreesFeather** [comment]
![image](https://user-images.githubusercontent.com/105774046/169426589-c66156ee-dcde-4fff-9e04-79ba2d53408f.png)

**Comment by HibiKier** [comment]
不是，是你发送识别的图片

**Comment by TreesFeather** [comment]
欸？刚才去试了一下突然能用了(
![image](https://user-images.githubusercontent.com/105774046/169426831-c52ad255-4651-4691-9f9c-abceccc72a09.png)
![Screenshot_20220520_084920_com tencent tim](https://user-images.githubusercontent.com/105774046/169426884-859008fe-fa25-4263-a9a2-1cf7c1728b6e.jpg)
打扰您了orz

**Comment by TreesFeather** [comment]
我发现好像是某些图片会导致这个情况（没反应）

**Comment by HibiKier** [comment]
可能是没搜索到时没判断没做好吧，周末看看

**Comment by Su-Dream** [comment]
> 可能是没搜索到时没判断没做好吧，周末看看

有真寻交流群或者discord频道吗，qq群好像关闭了申群
