### ISSUE TITLE
戳一戳发送图片显示图片缺失

### ISSUE THREAD

**Issue by chara1051** [HibiKier/zhenxun_bot#401]
![捕获](https://user-images.githubusercontent.com/105768555/169443664-0f1b771a-8148-42a8-aaed-99cd77304a34.PNG)

**Comment by HibiKier** [comment]
你放图片了吗

**Comment by chara1051** [comment]
> 你放图片了吗
放了，要配置其他什么吗
![捕获](https://user-images.githubusercontent.com/105768555/169444330-3397e5f0-f8ac-4608-8588-6271b07e436e.PNG)
吗

**Comment by HibiKier** [comment]
呃，发送 萝莉 命令也是一样的错误吗

**Comment by chara1051** [comment]
> 呃，发送 萝莉 命令也是一样的错误吗

抱歉，是我的问题，已经解决
