### ISSUE TITLE
这是为什么

### ISSUE THREAD

**Issue by Bai3396** [HibiKier/zhenxun_bot#406]
![image](https://user-images.githubusercontent.com/93367792/169447913-3d65a305-6fd5-44c5-b626-0f3d3e867b3a.png)
这个cqhttp登录不上，我的真寻运行py文件一直提示数据库连接错误

**Comment by MingxuanGame** [comment]
see #212

**Comment by Bai3396** [comment]
![image](https://user-images.githubusercontent.com/93367792/169448270-333153c6-4845-42fc-bf0f-36c2f47c4eff.png)
这是报错信息

**Comment by Bai3396** [comment]
> see #212

See？

**Comment by MingxuanGame** [comment]
> > see #212
> 
> See？

参考的意思

**Comment by Bai3396** [comment]
> > > see #212
> > 
> > See？
> 
> 参考的意思

但是我是ios 我该如何寻找token文件

**Comment by MingxuanGame** [comment]
> > > > see #212
> > > 
> > > See？
> > 
> > 参考的意思
> 
> 但是我是ios 我该如何寻找token文件

你在你的电脑运行 gocqhttp 并登录后，将生成的 device.json 和 session.token 上传到服务器

**Comment by MingxuanGame** [comment]
数据库问题参考 https://github.com/HibiKier/zhenxun_bot/issues/194#issuecomment-1128982588

**Comment by Bai3396** [comment]
谢谢我已经大致明白

**Comment by Bai3396** [comment]
![image](https://user-images.githubusercontent.com/93367792/169449950-8cdbd13d-6fb4-4d4b-b7c6-97e572c01484.png)
遇到新的问题

**Comment by MingxuanGame** [comment]
> ![image](https://user-images.githubusercontent.com/93367792/169449950-8cdbd13d-6fb4-4d4b-b7c6-97e572c01484.png) 遇到新的问题

你运行 `python bot.py` 了吗

**Comment by HibiKier** [comment]
> ![image](https://user-images.githubusercontent.com/93367792/169448270-333153c6-4845-42fc-bf0f-36c2f47c4eff.png) 这是报错信息

按照按照数据库部分输入命令

**Comment by Bai3396** [comment]
已经创建好了一个名为testdb的库

**Comment by HibiKier** [comment]
你写的密码正确的吗

**Comment by Bai3396** [comment]
> 你写的密码正确的吗
正在尝试使用新的数据库名

**Comment by Bai3396** [comment]
真寻bot.py运行正常，但是cqhttp依旧提示错误，

**Comment by Bai3396** [comment]
> 你写的密码正确的吗

![image](https://user-images.githubusercontent.com/93367792/169459638-0ba29571-60f0-4b0c-828f-78c2d7fb0220.png)

**Comment by Bai3396** [comment]
![image](https://user-images.githubusercontent.com/93367792/169459750-4603a95f-635a-4a29-85c6-1b2d99bdcd01.jpeg)![image](https://user-images.githubusercontent.com/93367792/169459751-b71dd0a1-2316-4de6-b4b6-83dd4c1e55ec.jpeg)
真寻可以cqhttp一直提示报错

**Comment by HibiKier** [comment]
警告可以不管

**Comment by Bai3396** [comment]
谢谢我已经运行真寻，感谢作者
