### ISSUE TITLE
重启一次服务器后出现了插件全部无法导入

### ISSUE THREAD

**Issue by ChenPiTang-Hui** [HibiKier/zhenxun_bot#407]
[error_2022-05-20.log](https://github.com/HibiKier/zhenxun_bot/files/8735896/error_2022-05-20.log)

**Comment by HibiKier** [comment]
把data/configs/plugin2config删了

**Comment by ChenPiTang-Hui** [comment]
> 把data/configs/plugin2config删了

感谢 已解决
