### ISSUE TITLE
私聊敏感词屏蔽删除之后，重启b真寻后敏感词判断未生效

### ISSUE THREAD

**Issue by AngelBeats401** [HibiKier/zhenxun_bot#408]
![M8}F@3KPXPP`Q_4N@VV8%`M](https://user-images.githubusercontent.com/65359943/169451437-012d5e20-ce4e-4d8a-8e66-61244cef7b65.png)
![0QF71VFAL9GYCVZ59%%$_$Q](https://user-images.githubusercontent.com/65359943/169451751-7735ebf3-cf0b-4cac-bad7-3a1f2b22bb8a.png)

**Comment by HibiKier** [comment]
因为是存在配置文件里的，进data里找找

**Comment by AngelBeats401** [comment]
> 因为是存在配置文件里的，进data里找找
找到了，请问一下好感度降低处罚怎么关闭 或者是调整降低值

**Comment by HibiKier** [comment]
what？哪有好感度降低处罚
