### ISSUE TITLE
mockingbird问题

### ISSUE THREAD

**Issue by eachbol2333** [HibiKier/zhenxun_bot#409]
我使用教程的两个命令都不行pip install mockingbirdonlyforuse和pip install -r requirements.txt，都会报一下两个错误
![image](https://user-images.githubusercontent.com/105063888/169452617-f74fa0f4-584e-40df-b7e4-34ec0e8f5d41.png)
![image](https://user-images.githubusercontent.com/105063888/169452646-208e88ae-888b-49ad-b588-b64573eb4cc6.png)
q请问有没有解决办法

**Comment by AkashiCoin** [comment]
你issue怎么提这来了，mockingbirdonlyforuse是为了一些依赖装一次即可，require里的依赖是为了适配真寻的一些一些插件而修改了版本，正常装上使用即可，报错可以不用管

**Comment by eachbol2333** [comment]
好的，谢谢大佬，我再试试

**Comment by dick0841** [comment]
请问一下，我也在装mockingbird插件，我尝试放在新文件夹extra_plugins文件夹中
![image](https://user-images.githubusercontent.com/50237543/169701163-76a36047-7e7b-4cc3-a736-1c188c5e9cba.png)，
![image](https://user-images.githubusercontent.com/50237543/169701186-790e2cdc-2acf-417a-b13f-3b58f4571372.png)
我在根目录下有pip install mockingbirdforuse与在mockingbirdforuse文件中pip install -r requirements.txt --ignore-installed了，但是真寻好像不对指令反应
![image](https://user-images.githubusercontent.com/50237543/169701287-80935a99-de10-424a-a4ae-bb34df1b3816.png)
请问该如何解决？感谢大佬QwQ

**Comment by eachbol2333** [comment]
我现在卡在了安装mockingbirdforuse了，一直提示出错
![image](https://user-images.githubusercontent.com/105063888/169702060-23d4e232-679e-43fb-894c-45f8a663dad7.png)
请问您是怎么安装的

**Comment by dick0841** [comment]
我记得我是在mockingbirdforuse文件夹下pip install 的

**Comment by eachbol2333** [comment]
对，然后出现了这个
![image](https://user-images.githubusercontent.com/105063888/169702606-583d61a8-b020-4da4-a628-998e4248f1f7.png)
一直说缺少c++14.0
