### ISSUE TITLE
(已解决)centos7.9 运行playwright install-deps chromium  显示未找到命令

### ISSUE THREAD

**Issue by Smile-Luck** [HibiKier/zhenxun_bot#411]
`(zhenxun-bot-WueIPpGC-py3.9) [root@VM-4-10-centos zhenxun_bot-main]# playwright install-deps chromium
Installing Ubuntu dependencies...
sh: apt-get: 未找到命令
(zhenxun-bot-WueIPpGC-py3.9) [root@VM-4-10-centos zhenxun_bot-main]# 
`

前边指令playwright install chromium运行好了
但是在执行playwright install-deps chromium的时候提示apt-get 未找到

**Comment by MingxuanGame** [comment]
非 Ubuntu/Debian 系统可以不输入 `playwright install-deps chromium`

**Comment by zhability** [comment]
> 非 Ubuntu/Debian 系统可以不输入 `playwright install-deps chromium`

可是大佬，centos7下运行会提示：
`[WARNING] utils | 启动chromium发生错误 <class 'playwright._impl._api_types.Error'>：
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     playwright install-deps                                ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝`
有什么好的解决办法么

**Comment by Smile-Luck** [comment]
> > 非 Ubuntu/Debian 系统可以不输入 `playwright install-deps chromium`
> 
> 可是大佬，centos7下运行会提示： 有什么好的解决办法么`[WARNING] utils | 启动chromium发生错误 <class 'playwright._impl._api_types.Error'>： ╔════════════════════════════════════════════════════════════╗ ║ Host system is missing a few dependencies to run browsers. ║ ║ Please install them with the following command: ║ ║ ║ ║ playwright install-deps ║ ║ ║ ║ <3 Playwright Team ║ ╚════════════════════════════════════════════════════════════╝`

你这个是缺少依赖,给你提示让你安装了  执行playwright install-deps这个命令,翻译是这样说的

**Comment by Smile-Luck** [comment]
主要原因centos和ubuntu命令不一样,如果是centos服务器执行playwright install-deps chromium个命令时,尝试使用yum chromium
