### ISSUE TITLE
识别图片出现Saucenao 缺失API_KEY！

### ISSUE THREAD

**Issue by hotwu0** [HibiKier/zhenxun_bot#413]
![(_7QWVSD)CS}25FNFN3PC(T](https://user-images.githubusercontent.com/105857571/169455812-1a7edc60-1e5d-4645-9c92-f0303ee305af.png)
大佬们这什么情况

**Comment by HibiKier** [comment]
[#269](https://github.com/HibiKier/zhenxun_bot/issues/269)
