### ISSUE TITLE
群权限问题

### ISSUE THREAD

**Issue by y839757743** [HibiKier/zhenxun_bot#416]
纯小白发问
为什么我按照  修改群权限 群号 等级  的格式修改群权限机器人回复的一直是扑朔迷离然后一直修改不成功
![PK96QNU_QCHK6HUXB(AY37R](https://user-images.githubusercontent.com/105906537/169466637-64f1f2c4-a45d-4d6e-b03e-576674abee16.png)
![SY_U3TY T0RED2_{E96@B(J](https://user-images.githubusercontent.com/105906537/169466644-c01d1f1f-0f49-4505-bced-475435348ec8.png)

**Comment by HibiKier** [comment]
[393](https://github.com/HibiKier/zhenxun_bot/issues/393)

**Comment by y839757743** [comment]
> [393](https://github.com/HibiKier/zhenxun_bot/issues/393)

我添加过了超级用户了，然后群权限也是按照教程说的@机器人然后 群号 等级
![3XHRHU~P30M AY U7E{RAS](https://user-images.githubusercontent.com/105906537/169467431-c1156a1d-c148-4d92-83d1-ee7a6581ba50.png)

**Comment by SmartRTE** [comment]
涩图功能需要群权限等级9🌚

**Comment by MingxuanGame** [comment]
> > [393](https://github.com/HibiKier/zhenxun_bot/issues/393)
> 
> 我添加过了超级用户了，然后群权限也是按照教程说的@机器人然后 群号 等级 ![3XHRHU~P30M AY U7E{RAS](https://user-images.githubusercontent.com/105906537/169467431-c1156a1d-c148-4d92-83d1-ee7a6581ba50.png)

一个用户是一个字符串。。。

```
SUPERUSERS=["839757743", "3420310070"]
```

**Comment by y839757743** [comment]
> 

我看他们都能添加多个，但是问题不是这个我已经解决了，还是感谢dalao的回复

**Comment by Unicatcode** [comment]
> > 
> 
> 我看他们都能添加多个，但是问题不是这个我已经解决了，还是感谢dalao的回复

您好，请问这个问题是怎么解决的呢，我也遇到了这个问题

**Comment by y839757743** [comment]
> > > 
> > 
> > 
> > 我看他们都能添加多个，但是问题不是这个我已经解决了，还是感谢dalao的回复
> 
> 您好，请问这个问题是怎么解决的呢，我也遇到了这个问题

我在启动命令前面加了斜杆我@机器人的时候没加
