### ISSUE TITLE
P搜 显示KeyError: 'illust'

### ISSUE THREAD

**Issue by qwerdvd** [HibiKier/zhenxun_bot#417]
P搜在挂上全局梯子后一些图片已经可以搜索到
但是有一些图片会显示这样的报错
![image](https://user-images.githubusercontent.com/105906879/169467089-ca63f552-b61f-4084-8954-bbbe3e541639.png)

**Comment by HibiKier** [comment]
可能是bug，可以提供一下下搜索的pid吗

**Comment by qwerdvd** [comment]
> 可能是bug，可以提供一下下搜索的pid吗

之前的pid找不到了，随便又找了一个
在 p搜91224213 时显示的是
![X8R@4~N1MJOXEDJ~G~I~%XR](https://user-images.githubusercontent.com/105906879/169523267-a460fcf7-1357-4e21-99a7-a10edb422cf3.png)

现在显示KeyError: 'illust'时，我去p站看了一下，应该是 该作品已被删除，或作品ID不存在 的问题

**Comment by HibiKier** [comment]
本地已修复，等更新即可
