### ISSUE TITLE
p站搜图问题

### ISSUE THREAD

**Issue by 1033022842** [HibiKier/zhenxun_bot#418]
![image](https://user-images.githubusercontent.com/42911080/169467803-198cb464-ae37-4a25-9fc7-bcc2e954898d.png)

1. 把判断是否为群聊的判断删掉之后 ，能下载图片了 ，最后发送的时候报错

**Comment by MingxuanGame** [comment]
请查看 go-cqhttp 的输出

**Comment by MingxuanGame** [comment]
> 看了日志说被风控了 换了个号也是如此....

风控很玄学，试着多挂几天吧
