### ISSUE TITLE
p搜的时候无回复

### ISSUE THREAD

**Issue by Einck0** [HibiKier/zhenxun_bot#421]
![image](https://user-images.githubusercontent.com/91471683/169472533-b3e8090b-5e2f-4831-96e8-dabc96ef88cc.png)
显示这样的报错
挂上梯子后回复下载失败
![$710Q1_T~I0(TQ)_BGTI9J](https://user-images.githubusercontent.com/91471683/169491035-7e45acb4-afbb-4ae7-81be-30d207ee00e5.png)

**Comment by HibiKier** [comment]
可能是bug，该issues保留，可以提供一下使用的pid吗

**Comment by Einck0** [comment]
> 可能是bug，该issues保留，可以提供一下使用的pid吗

所有pid都不行
现在没有上一条报错了只有第二个下载失败的问题
可以提个建议吗，将pix -r设置为群友可用吗

**Comment by HibiKier** [comment]
本地已修复，等更新即可

**Comment by HibiKier** [comment]
pix -r群友可用可以提供一个配置项

**Comment by HibiKier** [comment]
已修
