### ISSUE TITLE
添加商品的时候显示失败

### ISSUE THREAD

**Issue by 80546033** [HibiKier/zhenxun_bot#422]
![image](https://user-images.githubusercontent.com/67412155/169473677-2862e939-e67a-4cd0-90eb-5d322aa35970.png)

**Comment by MingxuanGame** [comment]
看一下 log 检查一下是否有报错

**Comment by 80546033** [comment]
> 查看一下日志查看一下是否有报错
![image](https://user-images.githubusercontent.com/67412155/169484967-eab3d185-3d38-4e9c-8fe6-e43105890e90.png)
有

**Comment by 80546033** [comment]
> 查看一下日志查看一下是否有报错

![image](https://user-images.githubusercontent.com/67412155/169485664-6cd1144c-e669-4b4b-b1aa-3fb5efa3f75d.png)

**Comment by MingxuanGame** [comment]
似乎是数据库已经存在了此商品

**Comment by 80546033** [comment]
> 好像是数据库已经存在了这个商品

我添加了别的也显示失败，有没有数据库文件可以直接添加的

**Comment by MingxuanGame** [comment]
> > 好像是数据库已经存在了这个商品
> 
> 我添加了别的也显示失败，有没有数据库文件可以直接添加的

你可以使用 `pgadmin` 查看一下数据库情况

**Comment by 80546033** [comment]
> > > 商品好像是数据库已经存在了
> > 
> > 
> > 我添加了另外的也显示失败，没有数据库文件可以直接添加
> 
> 你可以使用`pgadmin`查看一下数据库情况

是有goods表的，但是里面没有东西，我试试能不能直接在表里添加

**Comment by MingxuanGame** [comment]
> 是有goods表的，但是里面没有东西，我试试能不能直接在表里添加

怪，可能是数据库查询出问题了

**Comment by 80546033** [comment]
> > 是有货表的，里面但是没有东西，我不能直接在表里添加
> 
> 怪，可能是数据库查询出问题了

好像是的，我直接在表里添加商品后报错了

**Comment by 80546033** [comment]
> > 是有货表的，里面没有但是东西，我不能直接在表里添加
> 
> 怪，可能是数据库查询出问题了

Traceback (most recent call last):

  File "bot.py", line 20, in <module>
    nonebot.run()
    │       └ <function run at 0x000000000388C4C0>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-azjZwigI-py3.8\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x0000000002592E50>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x0000000004C429D0>
    └ <module 'uvicorn' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-azjZwigI-py3.8\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x0000000004C42B80>
    └ <uvicorn.server.Server object at 0x000000001164C5B0>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x0000000004C42C10>
           │       │   └ <uvicorn.server.Server object at 0x000000001164C5B0>
           │       └ <function run at 0x0000000003329F70>
           └ <module 'asyncio' from 'c:\\users\\administrator\\appdata\\local\\programs\\python\\python38\\lib\\asyncio\\__init__.py'>

  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x0000000011621540>
           │    └ <function BaseEventLoop.run_until_complete at 0x0000000003327280>
           └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x00000000033271F0>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000000003329D30>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000000032D80D0>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000000012C1E070>(<Future finished result=None>)>

  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x0000000012C1E070>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x0000000012C1E070>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000000012C1E070>(<Future finished result=None>)>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\nonebot\message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x00000000038FD940>: <Task finished name='Task-882888' coro=<_command() done, defined at C:\Users\Admi...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x0000000011897130>
          │            │        │    │      └ {'_prefix': {'command': ('商店',), 'raw_command': '商店', 'command_arg': []}}
          │            │        │    └ PrivateMessageEvent(time=1653035518, self_id=475946486, post_type='message', sub_type='friend', user_id=80546033, message_typ...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x000000001314E520>
          │            └ <Matcher from basic_plugins.shop.shop_handle, type=message, priority=5, temp=False>
          └ <function _run_matcher at 0x0000000003A9B790>

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\nonebot\message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x00000000038FD940>: <Task finished name='Task-882888' coro=<_command() done, defined at C:\Users\Admi...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x0000000011897130>
          │       │   │    │      └ {'_prefix': {'command': ('商店',), 'raw_command': '商店', 'command_arg': []}}
          │       │   │    └ PrivateMessageEvent(time=1653035518, self_id=475946486, post_type='message', sub_type='friend', user_id=80546033, message_typ...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x000000001314E520>
          │       └ <function Matcher.run at 0x00000000038FD4C0>
          └ <Matcher from basic_plugins.shop.shop_handle, type=message, priority=5, temp=False>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x00000000038FD940>: <Task finished name='Task-882888' coro=<_command() done, defined at C:\Users\Admi...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x0000000011897130>
          │    │          │    │      └ {'_prefix': {'command': ('商店',), 'raw_command': '商店', 'command_arg': []}}
          │    │          │    └ PrivateMessageEvent(time=1653035518, self_id=475946486, post_type='message', sub_type='friend', user_id=80546033, message_typ...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x000000001314E520>
          │    └ <function Matcher.simple_run at 0x00000000038FD430>
          └ <Matcher from basic_plugins.shop.shop_handle, type=message, priority=5, temp=False>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x00000000097BE940>, params=[], parameterless=[]>

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-azjZwigI-py3.8\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {}
                 │    └ <function _ at 0x00000000097BE940>
                 └ <Dependent call=<function _ at 0x00000000097BE940>, params=[], parameterless=[]>

  File "D:\bot\basic_plugins\shop\shop_handle\__init__.py", line 71, in _
    await shop_help.send(image(b64=await create_shop_help()))
          │         │    │               └ <function create_shop_help at 0x00000000098E35E0>
          │         │    └ <function image at 0x0000000006D3FB80>
          │         └ <classmethod object at 0x00000000038F6730>
          └ <Matcher from basic_plugins.shop.shop_handle, type=message, priority=5, temp=False>

  File "D:\bot\basic_plugins\shop\shop_handle\data_source.py", line 59, in create_shop_help
    if goods.goods_limit_time == 0 or time.time() < goods.goods_limit_time:
       │     │                        │    │        │     └ <gino.declarative.ColumnAttribute object at 0x00000000098A7E20>
       │     │                        │    │        └ <models.goods_info.GoodsInfo object at 0x0000000012B6B700>
       │     │                        │    └ <built-in function time>
       │     │                        └ <module 'time' (built-in)>
       │     └ <gino.declarative.ColumnAttribute object at 0x00000000098A7E20>
       └ <models.goods_info.GoodsInfo object at 0x0000000012B6B700>

TypeError: '<' not supported between instances of 'float' and 'NoneType'日志

**Comment by HibiKier** [comment]
真寻版本多少？
