### ISSUE TITLE
关于出现apikey格式不合法

### ISSUE THREAD

**Issue by Leiserx** [HibiKier/zhenxun_bot#423]
请问下这个情况怎么解决，除了输入命令随便输入的信息都会出现apikey不合法
![Uploading Screenshot_2022-05-20-15-27-44-61_9d26c6446fd7bb8e41d99b6262b17def.jpg…]()

**Comment by Leiserx** [comment]
![Screenshot_2022-05-20-15-27-44-61_9d26c6446fd7bb8e41d99b6262b17def](https://user-images.githubusercontent.com/53103860/169476287-c0542fe9-05fe-422f-ad02-b5facee3006f.jpg)

**Comment by MingxuanGame** [comment]
你截图没发上来

可能和 #270 一样

**Comment by Leiserx** [comment]
> 
感谢

**Comment by MingxuanGame** [comment]
please close this issue
![image](https://user-images.githubusercontent.com/68982190/169479218-634e7796-b3ef-4c94-9da5-1a816a1fa692.png)
