### ISSUE TITLE
为什么识图功能加上APIkey后启动bot就报错

### ISSUE THREAD

**Issue by yoshino2333** [HibiKier/zhenxun_bot#424]
![image](https://user-images.githubusercontent.com/105909793/169476526-9f3ad750-d971-4690-a2cc-5b643891601b.png)
![image](https://user-images.githubusercontent.com/105909793/169476596-8023661f-acd4-474a-b11b-7d396d3f8aa2.png)
为什么识图功能加上APIkey后启动bot就报错

**Comment by yoshino2333** [comment]
大佬救救

**Comment by MingxuanGame** [comment]
API_KEY 冒号后面有空格

**Comment by yoshino2333** [comment]
> API_KEY 冒号后面有空格才行

草，刚自己发现了，谢谢大佬的回复
