### ISSUE TITLE
我有一个疑问

### ISSUE THREAD

**Issue by Bai3396** [HibiKier/zhenxun_bot#425]
我查找了教程但是没有，请问为什么关闭ssh窗口，真寻就停止了，我该如何让他一直启动是要写一个脚本，还是修改文件参数？

**Comment by MingxuanGame** [comment]
[see ](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/start_.html)

**Comment by Bai3396** [comment]
> [Linux 持久化运行](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/start_.html)
这个已经部署好了，但是并没用，每当我关闭shell窗口，她就停止了运行，我需要重新打开shell并运行才可以，不是很理解

**Comment by Bai3396** [comment]
> [Linux 持久化运行](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/start_.html)
我是一个云服务器

**Comment by MingxuanGame** [comment]
你是怎么挂到后台的

**Comment by Bai3396** [comment]
> 你是怎么挂到后台的

我部署在云服务器上，我只是在我的电脑上关闭了ssh连接，但是我的真寻停止了，不是很明白为什么。

**Comment by MingxuanGame** [comment]
> > 你是怎么挂到后台的
> 
> 我部署在云服务器上，我只是在我的电脑上关闭了ssh连接，但是我的真寻停止了，不是很明白为什么。

你要在 screen 启动后才能退出

**Comment by Bai3396** [comment]
> > > 你是怎么挂到后台的
> 
> > 
> 
> > 我部署在云服务器上，我只是在我的电脑上关闭了ssh连接，但是我的真寻停止了，不是很明白为什么。
> 
> 
> 
> 你要在 screen 启动后才能退出

Cqhttp也要sceen吗？真寻好像运行着，cqhttp停止了

**Comment by MingxuanGame** [comment]
> Cqhttp也要sceen吗？真寻好像运行着，cqhttp停止了

都要的

**Comment by Bai3396** [comment]
> > Cqhttp也要sceen吗？真寻好像运行着，cqhttp停止了
> 
> 
> 
> 都要的
非常感谢，问题解决了，安装文档上就写了screen ，zhenxun，第一次使用这个项目，麻烦贡献者了
