### ISSUE TITLE
原神玩家查询  返回Please login 

### ISSUE THREAD

**Issue by SuLiuming** [HibiKier/zhenxun_bot#428]
您好，
向云服务器（Linux）上的真寻bot发送 原神玩家查询 xxxx（uid） 返回Please login。

Regards

**Comment by MingxuanGame** [comment]
你的 cookie 过期了，重新登录并绑定

**Comment by SuLiuming** [comment]
@MingxuanGame  
Hi
 请问了下cookie 绑定指的是修改配置文件还指的是通过原神插件指令 ？

Best Regards

**Comment by HibiKier** [comment]
原神插件指令
