### ISSUE TITLE
导入omega图库后pix命令报错

### ISSUE THREAD

**Issue by VictoriqueNeko** [HibiKier/zhenxun_bot#429]
![image](https://user-images.githubusercontent.com/105913583/169488973-aec4ec8f-eebb-4607-9290-a6ff8b57a8ff.png)

**Comment by Fengshou-Xu** [comment]
乐 果然是这个问题
你要去真寻bot的配置文件里面手动修改对应混合搜索的比例的参数 
默认参数是带两个单引号''
这样Python读取配置就认为是字符 而字符是无法做算术运算的
你得把发图片相关功能的比例都改一遍 
去掉两个单引号就行了 要记得和前面的杠- 之前有空格

**Comment by HibiKier** [comment]
？默认生成没有单引号啊

**Comment by VictoriqueNeko** [comment]
> 乐 果然是这个问题 你要去真寻bot的配置文件里面手动修改对应混合搜索的比例的参数 默认参数是带两个单引号'' 这样Python读取配置就认为是字符 而字符是无法做算术运算的 你得把发图片相关功能的比例都改一遍 去掉两个单引号就行了 要记得和前面的杠- 之前有空格
搞定了，感谢
