### ISSUE TITLE
改图功能报错

### ISSUE THREAD

**Issue by chara1051** [HibiKier/zhenxun_bot#430]
![QQ图片20220520164135](https://user-images.githubusercontent.com/105768555/169493100-9132a851-e561-4af5-a6ad-12ccad9a5b1c.jpg)
![QQ图片20220520164148](https://user-images.githubusercontent.com/105768555/169493106-c5012ee1-8bc2-44e0-a63e-702de0ffc5b2.jpg)

**Comment by HibiKier** [comment]
如何复现？

**Comment by chara1051** [comment]
> 如何复现？

好像并不是网络问题，有些图片改不了，底色替换好像没有一次成功，有些会成功改图回复，有些后台直接报错没有任何回应

**Comment by chara1051** [comment]
> 如何复现？

好像是图片格式问题，改底色需要特殊的文件格式吗？

**Comment by HibiKier** [comment]
不需要，你发送的所有图片会被统一下载成jpg或png

**Comment by chara1051** [comment]
> 不需要，你发送的所有图片会被统一下载成jpg或png

底色替换没成功过，不知道怎么回事
![捕获](https://user-images.githubusercontent.com/105768555/169543652-fe199d7e-c4ce-4a29-b0d0-73b1af6ea38e.PNG)
