### ISSUE TITLE
程序启动失败 退出

### ISSUE THREAD

**Issue by ChenPiTang-Hui** [HibiKier/zhenxun_bot#431]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/69108232/169493211-752196fc-8b94-4c16-b67f-ac66fd0d3619.png">

**Comment by ChenPiTang-Hui** [comment]
已暂时解决 原因为添加了[真寻 成分姬插件](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/tree/master/ddcheck) 现删除插件后可以使用 
[一个似乎是插件冲突的问题](https://github.com/noneplugin/nonebot-plugin-boardgame/issues/7)

**Comment by HibiKier** [comment]
成分姬是有用到Playwright吧，这方面win上还没解决
