### ISSUE TITLE
wehui 只显示一个QQ的信息

### ISSUE THREAD

**Issue by mmmjie** [HibiKier/zhenxun_bot#432]
背景：
因为有时候内鬼举报会冻结真寻QQ，为了防止牵连其他群，我基本一个群配一个真寻QQ，如果被举报冻结就冻结本群的真寻，不会影响到其他群。

连接：
是一个真寻进程与多个go-cqhttp进程连接，共用一个端口

问题：
wehui上的Q群列表和好友邀请，在连接多个gocq的情况下，是随机显示其中一个真寻Q的群组和邀请，即便点击刷新也不会更换。

期望：
能否优化成显示所有真寻QQ账户的群组和好友邀请信息？

**Comment by HibiKier** [comment]
根据端口号来得，理论上你也可以根据端口开很多个webui

**Comment by HibiKier** [comment]
如果你是多个gocq配1个nonebot的话，现在并没有适配这方面的代码，可以作为一个需求issues
