### ISSUE TITLE
没有自动生成config.yaml

### ISSUE THREAD

**Issue by a930389426** [HibiKier/zhenxun_bot#433]
我程序跑成功了，bot也能成功接收到QQ群的消息，但是我没有自动生成config.yaml,对bot喊话也没有回应，已经不知道后面怎么搞了

**Comment by a930389426** [comment]
05-20 17:01:42 [SUCCESS] nonebot | NoneBot is initializing...
05-20 17:01:42 [INFO] nonebot | Current Env: prod
05-20 17:01:43 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
05-20 17:01:43 [SUCCESS] nonebot | Running NoneBot...
05-20 17:01:43 [INFO] uvicorn | Started server process [7448]
05-20 17:01:43 [INFO] uvicorn | Waiting for application startup.
05-20 17:01:43 [INFO] services | Database loaded successfully!
05-20 17:01:45 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-20 17:01:45 [INFO] uvicorn | Application startup complete.
05-20 17:01:45 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
05-20 17:02:13 [INFO] uvicorn | ('127.0.0.1', 63534) - "WebSocket /onebot/v11/ws/" [accepted]
05-20 17:02:13 [INFO] nonebot | OneBot V11 | Bot 2678283772 connected
05-20 17:02:13 [INFO] websockets | connection open

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169501804-378e860f-e006-426e-b80f-ebbcdb61d0fd.png)
你这不是什么插件都没加载吗，你basic_plugin和plugins文件夹下面有东西吗

**Comment by AF5656** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169501804-378e860f-e006-426e-b80f-ebbcdb61d0fd.png) 你这不是什么插件都没加载吗，你basic_plugin和plugins文件夹下面有东西吗

我也遇到了这个问题，两个文件夹下的插件都加载有了
但还是报上面的错
