### ISSUE TITLE
poetry如何新增依赖

### ISSUE THREAD

**Issue by TiAmoJIA** [HibiKier/zhenxun_bot#435]
想添加新的插件，但是缺少依赖，没看懂poetry虚拟环境如何增加新的依赖，比如我需要requests

**Comment by TiAmoJIA** [comment]
![image](https://user-images.githubusercontent.com/91871280/169501010-a44948a6-2204-4302-9267-f99ac7336ed5.png)
按照文档意思是用poetry add requests这样子，但是它为什么这么慢

**Comment by HibiKier** [comment]
他确实这么慢
