### ISSUE TITLE
bot.py启动后报错

### ISSUE THREAD

**Issue by PokiAcg** [HibiKier/zhenxun_bot#436]
![O6_J6C75OMK`C@6@{LXB~EO](https://user-images.githubusercontent.com/105905387/169502392-b5231b89-450c-4f35-be7f-4b05a999ee80.jpg)

**Comment by HibiKier** [comment]
你配置文件改坏了，config.yaml删了重启

**Comment by PokiAcg** [comment]
> 
谢谢大佬解决了


> 你的配置文件改坏了，config.yaml删了重启
