### ISSUE TITLE
识图问题

### ISSUE THREAD

**Issue by kyi-wuc** [HibiKier/zhenxun_bot#437]
![图片](https://user-images.githubusercontent.com/105788280/169507915-cffa4017-f96c-4be4-911c-f023e0ecfcc7.png)
![图片](https://user-images.githubusercontent.com/105788280/169508022-912cbaaf-c833-41a6-b9d4-f17894af809a.png)
![图片](https://user-images.githubusercontent.com/105788280/169508066-e987bf0d-ef77-49cf-838e-fc469492aa05.png)
前面能识图，后面识图就没反应了，这是API引用上限了么

**Comment by Slinet6056** [comment]
应该是网络问题，我一开始有这问题，挂上代理就没事了

**Comment by HibiKier** [comment]
是网络问题

**Comment by kyi-wuc** [comment]
好的，了解，多谢
