### ISSUE TITLE
插件安装错误

### ISSUE THREAD

**Issue by sxc2588** [HibiKier/zhenxun_bot#438]
已经按照各插件的要求装好了相关依赖，但仍会读取失败
![image](https://user-images.githubusercontent.com/105810286/169510122-5b900f57-a0cb-4f7c-9dc6-ff550777994e.png)
![image](https://user-images.githubusercontent.com/105810286/169510172-d76d4cf0-d23c-44dc-b06d-71baff820c66.png)
![image](https://user-images.githubusercontent.com/105810286/169510219-c9c04925-0636-416e-af3d-95d499cb6485.png)

**Comment by yajiwa** [comment]
依赖没有安装完成，有没有进虚拟环境安装呢

**Comment by IrisMiko** [comment]
![image](https://user-images.githubusercontent.com/60808770/169519563-56b26f17-be59-4963-b08a-f17bb30fd28e.png)
缺少这个插件

**Comment by sxc2588** [comment]
逐个检查安装完成了依赖，但启动后又报错了
![image](https://user-images.githubusercontent.com/105810286/169565833-613c6192-9a00-40fc-bc90-ebbfbc036137.png)
![image](https://user-images.githubusercontent.com/105810286/169565918-72dc45d7-32b1-43e2-b7c6-8fd8652e3d35.png)

**Comment by MingxuanGame** [comment]
> 逐个检查安装完成了依赖，但启动后又报错了

请问是否在 `.env.dev` 中开启了 `FASTAPI_RELOAD` 呢？

**Comment by sxc2588** [comment]
> > 逐个检查安装完成了依赖，但启动后又报错了
> 
> 请问是否在 `.env.dev` 中开启了 `FASTAPI_RELOAD` 呢
是这个env.dev吗，里面似乎没有这项
![image](https://user-images.githubusercontent.com/105810286/169590584-2c3f6f9b-8687-43f1-ba06-2239c25c7790.png)
![image](https://user-images.githubusercontent.com/105810286/169590693-29464333-1774-4103-8813-8fbc847ed01d.png)

**Comment by HibiKier** [comment]
> 逐个检查安装完成了依赖，但启动后又报错了 ![image](https://user-images.githubusercontent.com/105810286/169565833-613c6192-9a00-40fc-bc90-ebbfbc036137.png) ![image](https://user-images.githubusercontent.com/105810286/169565918-72dc45d7-32b1-43e2-b7c6-8fd8652e3d35.png)

playwrigh在win的限制已修，更新即可
