### ISSUE TITLE
启动失败 退出

### ISSUE THREAD

**Issue by wwcxin** [HibiKier/zhenxun_bot#439]
RuntimeError: There is no current event loop in thread 'wainThread '.
RuntimeError：线程‘wainThread’中没有当前事件循环。
各项信息填写正确，数据库测试可使用，但：
![image](https://user-images.githubusercontent.com/85999717/169511327-52f9d1eb-3ee9-4db5-b0c3-fdffc8579824.png)

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169517278-8eefe722-76ed-4fa7-8328-b15eca0a8ca8.png)
很清楚了啊
