### ISSUE TITLE
建议：添加MySQL数据库支持？

### ISSUE THREAD

**Issue by lakwsh** [HibiKier/zhenxun_bot#44]
其实主要是我没用过PostgreSQL，服务器大部分业务都是跑在MySQL上的（而且装多个数据库感觉有点麻烦...）

简略翻了一下代码，bot的数据库通讯好像用的Gino，Gino项目那边也看到几个issues是关于支持MySQL的建议
然后好像有人提到有个aiomysql项目能实现类似的功能，所以想问一下bot有没有这个打算添加一下MySQL的支持？

**Comment by HibiKier** [comment]
我研究一下，可以支持

**Comment by HibiKier** [comment]
gino文档中显示1.1b2已经有了aiomysql模块，不过目前pipy上最新版本是1.0.1
