### ISSUE TITLE
[WARNING] utils | 启动chromium发生错误 contos8

### ISSUE THREAD

**Issue by Edwbailey** [HibiKier/zhenxun_bot#440]
05-20 19:49:21 [WARNING] utils | 启动chromium发生错误 <class 'playwright._impl._api_types.Error'>：Executable doesn't exist at /root/.cache/ms-playwright/chromium-956323/chrome-linux/chrome
╔════════════════════════════════════════════════════════════════════════                                                                          ═╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     playwright install                                                  ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚════════════════════════════════════════════════════════════════════════                                                                          ═╝

安装时好像是安装了一个高版本的chromium导致无法调用

[root@bailey-FMVD04003 zhenxun_bot]# playwright install chromium
BEWARE: your OS is not officially supported by Playwright; downloading Ubuntu build as a fallback.
Downloading Chromium 102.0.5005.40 (playwright build v1005) - 129.7 Mb [====================] 100% 0.0s
(node:108243) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Chromium 102.0.5005.40 (playwright build v1005) downloaded to /root/.cache/ms-playwright/chromium-1005
BEWARE: your OS is not officially supported by Playwright; downloading Ubuntu build as a fallback.

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169517206-c1796acb-06e3-42e5-a515-324ca3a6aa37.png)
已经提示你了

**Comment by Edwbailey** [comment]
> 
playwright install chromium执行过

Chromium 102.0.5005.40 (playwright build v1005) downloaded to /root/.cache/ms-playwright/chromium-1005

playwright cr 也可以正常开启浏览器窗口

**Comment by Edwbailey** [comment]
用一种很奇妙的方式解决了。。。 
mv chromium-1005/ chromium-956323/
重命名就可以了
