### ISSUE TITLE
启动bot.py时报错Import "services.db_context" could not be resolved

### ISSUE THREAD

**Issue by fairyst** [HibiKier/zhenxun_bot#442]
![8@PUVDDX9QAQ57HD9)%JXYY](https://user-images.githubusercontent.com/105923016/169522949-009a97e1-96bd-4d29-a5d7-04e11a7c74f1.png)
![2ZQR7SBC2E{5IAU3T205O9I](https://user-images.githubusercontent.com/105923016/169523079-1f6e6fe2-3cc2-455f-b9e4-e7f98348c932.png)
![5}7`~2IFLWG4FLN%TIR6DXO](https://user-images.githubusercontent.com/105923016/169523133-731083fc-d99f-41bd-9abb-883601274e86.png)
![$1XCOBMZT2S12_$I77I ZHP](https://user-images.githubusercontent.com/105923016/169523178-e9b86b0d-d3ad-4910-9c7c-a927f01bcee6.png)

**Comment by MingxuanGame** [comment]
检查你运行 bot.py 的地址

要在 bot.py 所在目录

**Comment by fairyst** [comment]
> ###
![$F9MX3%4_U VX_YJD`8BT2](https://user-images.githubusercontent.com/105923016/169529741-086bd3a6-85f0-4b8c-8782-f0a0108667f7.png)
还是这样

**Comment by MingxuanGame** [comment]
打印一下当前目录文件列表

```
dir
```

**Comment by fairyst** [comment]
![GH84NXHEMJ%IK))CDS102ZQ](https://user-images.githubusercontent.com/105923016/169530512-c127b6c9-600f-4cc9-895c-a1298d196191.png)

**Comment by MingxuanGame** [comment]
你似乎没有解压全

试着重新解压看看

**Comment by fairyst** [comment]
谢谢大佬们 已经搞好了
