### ISSUE TITLE
ubuntu16 启动进程结束

### ISSUE THREAD

**Issue by Misakami** [HibiKier/zhenxun_bot#443]
![image](https://user-images.githubusercontent.com/22981008/169524136-0a707543-3dbc-40ee-9c5d-f0df12a55e24.png)

**Comment by HibiKier** [comment]
大概率是原神下地图拼接的时候内存炸了，可以暂时把原神资源插件删掉，plugins/genshin/query_resource_...

**Comment by Misakami** [comment]
> 大概率是原神下地图拼接的时候内存炸了，可以暂时把原神资源插件删掉，plugins/genshin/query_resource_...

好的我试试
