### ISSUE TITLE
念诗与网易云热评功能出现问题

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#444]
![image](https://user-images.githubusercontent.com/50237543/169524804-c97a53c4-ec71-4346-864b-e616ba0d6c86.png)
如图所示，一开始好好的，某次重启后就这样了

**Comment by Sakuracio** [comment]
ALAPI  报错 104 来源或者ip不在白名单 尝试添加你的IP到ALAPI白名单

**Comment by dick0841** [comment]
已经解决，非常感谢ヽ(✿ﾟ▽ﾟ)ノ
