### ISSUE TITLE
添加订阅主播失败<class'AttributeError'>

### ISSUE THREAD

**Issue by Umon7275** [HibiKier/zhenxun_bot#446]
在最开始运行bot.py时，bilibili_sub插件加载错误。之后用pip3手动安装了插件，加载成功。
添加订阅时，出现错误：
![image](https://user-images.githubusercontent.com/74399075/169526117-d22658b1-f3cd-4e04-acd4-07c09a8843ea.png)

**Comment by MingxuanGame** [comment]
可能是 bug（#320）

**Comment by HibiKier** [comment]
直播间id 555？

**Comment by HibiKier** [comment]
是直接clone的吗，需要等待更新

**Comment by Umon7275** [comment]
是直接git下来的。

**Comment by Umon7275** [comment]
嗯......忍不住看了下对应部分代码，发现并不是真寻的问题。
我测试了其他主播的直播间id，结果是订阅成功的。

然后我去看了下B站UZI的直播间地址，发现URL传的参数比其他直播间多了个 `is_room_feed=1`，说明直播间id `555` 并不是真实的。

![image](https://user-images.githubusercontent.com/74399075/170233387-32b5b902-728f-42b3-ab03-8f8cb143e942.png)

而UZI直播间真正的id可以在主页的直播间URL中看到其实是 `25059330` 。订阅这个id就不会出错。

![image](https://user-images.githubusercontent.com/74399075/170233227-012e9d7e-6cf8-4a69-9712-05e64bb889bd.png)

叔叔真的是！搞这些花里胡哨的干什么？
笑死。
