### ISSUE TITLE
BUFF查询皮肤功能报错

### ISSUE THREAD

**Issue by DeparturesNeko** [HibiKier/zhenxun_bot#447]
已经设置了cookie，proxy保持null，尝试查询ak47二西莫夫，出现如下图报错
![图片](https://user-images.githubusercontent.com/96569888/169532326-4900c686-84fd-4e8b-957f-cf1c6c5e7a0a.png)

**Comment by Einck0** [comment]
![image](https://user-images.githubusercontent.com/91471683/169550316-1d78d97b-9b00-417a-bf5e-abb10e4fc9e0.png)
proxy后面保持空白就行
