### ISSUE TITLE
小白 超级用户没有用

### ISSUE THREAD

**Issue by PJYasuna** [HibiKier/zhenxun_bot#448]
下载的压缩包里没有env 和env.dev 于是我自己又特地下了这两个放进了文件夹（不知道这样可不可以）。我按照教程把超级用户设置成了自己的qq，但是使用时确提示我没有权限。比如我发“开启色图”，提示“你的权限不足喔，该功能需要的权限等级：2”

**Comment by MingxuanGame** [comment]
发一下你的 .env.dev

**Comment by PJYasuna** [comment]
<img width="515" alt="截屏2022-05-20 下午9 19 25" src="https://user-images.githubusercontent.com/87230886/169536964-c5e47774-4119-484b-bae6-1c0bc930163e.png">

**Comment by MingxuanGame** [comment]
怪

确保设置对并重启了吗

**Comment by PJYasuna** [comment]
确保设置对有点泛不好保证 电脑也重启过了 我还测试了一下别的 比如我把config.yaml的默认群权限改成9 询问后还是5... 
就好像改动都没成功一样

**Comment by MingxuanGame** [comment]
> 确保设置对有点泛不好保证 电脑也重启过了 我还测试了一下别的 比如我把config.yaml的默认群权限改成9 询问后还是5... 就好像改动都没成功一样

你 bot.py 开启时的 log 发一下

**Comment by HibiKier** [comment]
config.yaml只对你之后加的群生效

**Comment by PJYasuna** [comment]
<img width="869" alt="截屏2022-05-20 下午9 33 13" src="https://user-images.githubusercontent.com/87230886/169539044-af51018e-9873-48a8-ad52-20376cfd651a.png">

**Comment by mmmjie** [comment]
1543149076 是你机器人的QQ，还是你自己常用的使用QQ？

这里是填哪个QQ，就哪个QQ有超级用户权限，是否填错成机器人QQ呢？

**Comment by PJYasuna** [comment]
1543149076是我的qq

**Comment by mmmjie** [comment]
目前有时候好像有BUG，进群后超级 用户和管理员没有相应的权限，要第二天才会刷新 （不确定）

你可以尝试私聊机器人QQ，发送 
添加权限 1543149076 （这里填Q群号 去掉括号）9
然后再试试

**Comment by PJYasuna** [comment]
<img width="1253" alt="截屏2022-05-20 下午9 38 12" src="https://user-images.githubusercontent.com/87230886/169540007-192a057e-deaf-4caa-911d-2a70d2b0b36d.png">
env.dev放的是这个位置

**Comment by PJYasuna** [comment]
<img width="707" alt="截屏2022-05-20 下午9 42 08" src="https://user-images.githubusercontent.com/87230886/169540728-f9b5c6de-cc5e-45f5-9d8e-1c2adb2c1b96.png">
好像行不通

**Comment by mmmjie** [comment]
抱歉,mac环境我不大了解，无能为力

**Comment by PJYasuna** [comment]
大佬们 请问识图报错说没有API key该怎么解决

**Comment by MingxuanGame** [comment]
> 大佬们 请问识图报错说没有API key该怎么解决

see #269

**Comment by PJYasuna** [comment]
> > 大佬们 请问识图报错说没有API key该怎么解决
> 
> see #269

感谢
