### ISSUE TITLE
啊呀……真寻酱好像没有写出来config.yaml的样子……

### ISSUE THREAD

**Issue by Noob-in-computers** [HibiKier/zhenxun_bot#449]
![image](https://user-images.githubusercontent.com/105729522/169534363-0f5a218f-a1df-4c9a-a062-9c1d5f5709fb.png)
![image](https://user-images.githubusercontent.com/105729522/169534433-8e118f10-b941-430e-bc32-10b930faf8c2.png)
如图，真寻bot成功部署，但是好像缺了一点配置文件……？
请问各位大佬有什么办法吗？谢谢各位力……

======
![image](https://user-images.githubusercontent.com/105729522/169535914-0e6be1ec-f8c5-4933-bad3-6c0ba7d05bd6.png)
![image](https://user-images.githubusercontent.com/105729522/169535955-9d68d5ee-f829-45b8-89f9-2e7c4e9ec45b.png)
basic_plugin和plugins文件夹下面都有东西，不应该出现这样的错误啊（沉思）

**Comment by Noob-in-computers** [comment]
备注，这是新买的云服务器，所以不存在什么环境冲突的东西，缺组件倒是可能

**Comment by Noob-in-computers** [comment]
> 插件加载过程中有报错吗
[新建文本文档.txt](https://github.com/HibiKier/zhenxun_bot/files/8747210/default.txt)

报错了，但是我按照报错中提示补全了py包

**Comment by HibiKier** [comment]
？你不是poetry install 都没输入吗
