### ISSUE TITLE
涩图功能有问题

### ISSUE THREAD

**Issue by jimodeniuren** [HibiKier/zhenxun_bot#45]
在线搜索好多之前能搜的关键字都搜不到了，就算是能搜到的，同一个关键字返回的也是同一张图片

**Comment by HibiKier** [comment]
比如哪一些关键字呢？我复现试试

**Comment by jimodeniuren** [comment]
比如【八重】就搜不到，但是【八重神子】就能搜到，感觉后者应该是包含于前者的？

**Comment by HibiKier** [comment]
因为现在色图是采用tag搜索，可以命令 “色图 萝莉 白丝”，“色图 萝莉|少女 白丝” 这样多tag搜索，模糊查询keyword是无法使用“色图 萝莉 白丝”这种，如果你希望使用keyword搜索，可以自行修改 plugins/send_setu/data_source.py第33行
```python
    tags = "".join(tags)
    params = {
        "r18": r18,  # 添加r18参数 0为否，1为是，2为混合
        "keyword": tags,  # 若指定tag
        "num": 100,  # 一次返回的结果数量
        "size": ["original"],
    }
```

**Comment by jimodeniuren** [comment]
好的，感谢
