### ISSUE TITLE
picsearcher启用失败

### ISSUE THREAD

**Issue by nertcy** [HibiKier/zhenxun_bot#451]
安装路径
![image](https://user-images.githubusercontent.com/94539226/169547410-c073fef0-4f9c-459c-953e-d087838cd543.png)
配置
![image](https://user-images.githubusercontent.com/94539226/169547520-773c830b-b01b-4aec-9f7f-96080bcc41d0.png)
![image](https://user-images.githubusercontent.com/94539226/169547584-2250a2f0-18fc-41bd-a84a-f9bdc254e1e7.png)
logs：
![image](https://user-images.githubusercontent.com/94539226/169547733-ab2e7949-5a34-496e-bd45-eecb52fd8d7d.png)
环境：win11  py3.8.10

**Comment by MingxuanGame** [comment]
这是你自己加载错了

[文档](https://v2.nonebot.dev/docs/tutorial/plugin/load-plugin)

**Comment by Sakuracio** [comment]
nonebot.load_plugins("my_pluhins/picsearcher")

**Comment by nertcy** [comment]
> nonebot.load_plugins（“my_pluhins/图片搜索者”）

![image](https://user-images.githubusercontent.com/94539226/169550565-3952c421-6b5d-4930-ba21-68abace5004f.png)

**Comment by MingxuanGame** [comment]
`load_plugins` 不是 `load_plugin`
