### ISSUE TITLE
启动时nonebot报错，且python bot.py也报错

### ISSUE THREAD

**Issue by sdfsddftd** [HibiKier/zhenxun_bot#452]
启动时提示如下错误![image](https://user-images.githubusercontent.com/69803371/169548470-378b1de2-44c0-4203-82f5-d698234b0077.png)
卸载重装后问题依旧，按照其他issue结局方法输入python bot.py则出现以下错误
![image](https://user-images.githubusercontent.com/69803371/169548690-0a25f55e-3600-4969-81f3-7ff24311c4d2.png)
依赖如虚拟环境等已经全部安装
![image](https://user-images.githubusercontent.com/69803371/169549145-85d1421a-f507-473f-996e-f355fd33c73e.png)

**Comment by sdfsddftd** [comment]
可能是我之前一不小心装了多个nonebot又卸载导致？搜了好久都没解决这个问题。。。

**Comment by MingxuanGame** [comment]
我 tm 彻底无语了

你都没进机器人目录

**Comment by sdfsddftd** [comment]
> 我 tm 彻底无语了
> 
> 你都没进机器人目录

![image](https://user-images.githubusercontent.com/69803371/169553004-ab205458-a89c-416a-8c26-5c14019caf6d.png)
是这样吗。。。刚接触unbuntu没多久不太熟悉😣

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169577809-a1c6dfa2-bbd3-40af-a250-504afe9224fc.png)

**Comment by sdfsddftd** [comment]
谢谢大佬！我在bot的文件夹下重新执行上述指令再
`python bot.py`
已经正常，如下图
![image](https://user-images.githubusercontent.com/69803371/169631513-910c6403-b8f2-40bf-8ed5-35919fdc3caa.png)
但是当我尝试用一键部署脚本启动bot时还是有如下报错
![image](https://user-images.githubusercontent.com/69803371/169631356-a4b8b08e-a26d-4994-b00c-194ba01bfddf.png)

**Comment by sdfsddftd** [comment]
感谢各位，经过设置之后机器人已经可以正常使用
所以只剩下一个小问题，那就是一键部署脚本用不了。。。
