### ISSUE TITLE
提一个建议开放群r18功能

### ISSUE THREAD

**Issue by Einck0** [HibiKier/zhenxun_bot#453]
机器人应该是服务群友的，建议开放群r18功能，可以默认关闭或者需要群权限9

**Comment by Sakuracio** [comment]
可以自己配置，自行查阅文档。

**Comment by wzlwzl1021** [comment]
在群里发送 修改群权限 群号 9

**Comment by Einck0** [comment]
> 在群里发送 修改群权限 群号 9

不行我说的是pix -r指令

**Comment by Umon7275** [comment]
see #296

**Comment by yanluoli** [comment]
可以在send_setu里修改

**Comment by Einck0** [comment]
发送色图已解决，pix -r将判断语句注释可以发送色图了但仍然会说不能看
![image](https://user-images.githubusercontent.com/91471683/169637582-22d0cae7-3e93-432e-a5f1-74f9c5a47460.png)
