### ISSUE TITLE
启动时报错Failed to import "word_clouds"（并未影响使用）

### ISSUE THREAD

**Issue by Einck0** [HibiKier/zhenxun_bot#454]
如题
![image](https://user-images.githubusercontent.com/91471683/169549811-b2362b80-7f74-44a0-8e99-14e7ab260f9e.png)

**Comment by MingxuanGame** [comment]
你的 emoji 没有安装

```bash
pip install emoji
```

**Comment by Einck0** [comment]
> 你的 emoji 没有安装
> 
> ```shell
> pip install emoji
> ```

已解决感谢
