### ISSUE TITLE
用同样的cookie，查询皮肤可以查价格，但开箱无法查询价格

### ISSUE THREAD

**Issue by Einck0** [HibiKier/zhenxun_bot#455]
查询
![image](https://user-images.githubusercontent.com/91471683/169551199-a5541bf8-9d56-42a8-9409-b1c7b1fc982a.png)
开箱
![image](https://user-images.githubusercontent.com/91471683/169551380-d94052b0-45c7-4d03-b6fa-a155b753c83d.png)

**Comment by MingxuanGame** [comment]
第二张图

日志放全一点

**Comment by Einck0** [comment]
> 第二张图
> 
![image](https://user-images.githubusercontent.com/91471683/169637782-3213dfde-aa46-4ab5-972c-365d0fdb1c2c.png)

> 日志放全一点

**Comment by Einck0** [comment]
已有其他同样issue
