### ISSUE TITLE
关于识图出的问题

### ISSUE THREAD

**Issue by NGPhoenixair** [HibiKier/zhenxun_bot#458]
![@KWAE M6BUQ6PM7UK$3F6{Q](https://user-images.githubusercontent.com/105866695/169560348-ee6a6d8e-beaa-4bc1-9fe9-003ad985911e.png)
![0N604CFPJ5W@HOC$8A{L96](https://user-images.githubusercontent.com/105866695/169560362-48deccbb-badf-4683-9b4f-eddca539cea4.png)
![ZQ1PL1PNH2X F7XNLL89L%5](https://user-images.githubusercontent.com/105866695/169560396-87ed93b0-4c62-4723-805c-8ca993bdf1c2.png)
这是我网络问题还是其他问题，还是说两种都有（

**Comment by MingxuanGame** [comment]
超时了，网络问题
