### ISSUE TITLE
发图的时候有时候会提示图片被小怪兽恰掉了

### ISSUE THREAD

**Issue by Natsumelan** [HibiKier/zhenxun_bot#459]
还有这个报错
![image](https://user-images.githubusercontent.com/105765802/169562654-30a751fe-1c53-46e6-b574-01adfea82e30.png)

**Comment by MingxuanGame** [comment]
麻烦日志放全一点

方便寻找问题

**Comment by wzlwzl1021** [comment]
data_resource.py用新的，原来的有问题

**Comment by Natsumelan** [comment]
> 麻烦日志放全一点
> 
> 方便寻找问题

![image](https://user-images.githubusercontent.com/105765802/169571381-882e7977-56ed-47dc-b267-cef654b6f9a9.png)
应该是网络问题

**Comment by Natsumelan** [comment]
> 麻烦日志放全一点
> 
> 方便寻找问题

还有这个
![image](https://user-images.githubusercontent.com/105765802/169571714-7072eb74-cf44-4b03-bc65-4be7a58dbca1.png)

**Comment by Natsumelan** [comment]
![image](https://user-images.githubusercontent.com/105765802/169572170-7957a405-4a3e-4b04-b2e4-71e4d91ca9bd.png)

**Comment by MingxuanGame** [comment]
windows 下不可用中文路径

**Comment by MingxuanGame** [comment]
windows 下可用中文路径

**Comment by Natsumelan** [comment]
> windows 下不可用中文路径

把文件夹名字改了之后程序就运行不了了
![image](https://user-images.githubusercontent.com/105765802/169630591-c6bb15cb-ecee-4d0f-b199-7762a8743623.png)

**Comment by MingxuanGame** [comment]
你的路径改了

环境也需要重新装

**Comment by Natsumelan** [comment]
> 

![image](https://user-images.githubusercontent.com/105765802/169633463-cca66fd0-8662-4083-80a6-cf8d321aaa2c.png)
然后就报错了

**Comment by Natsumelan** [comment]
> 你的路径改了
> 
> 环境也需要重新装

![image](https://user-images.githubusercontent.com/105765802/169633482-e9b73510-f166-46fc-9f24-d726e3f801bf.png)
报错了

**Comment by MingxuanGame** [comment]
把 `poetry.lock` 删了重试

**Comment by MingxuanGame** [comment]
把 `poetry.lock` 删了重试

**Comment by Natsumelan** [comment]
> 删`poetry.lock`了重试

![image](https://user-images.githubusercontent.com/105765802/169639526-5ddc9962-99fb-4b53-b42d-4c3efe7bb481.png)
全是报错

**Comment by MingxuanGame** [comment]
> > 删`poetry.lock`了重试
> 
> ![image](https://user-images.githubusercontent.com/105765802/169639526-5ddc9962-99fb-4b53-b42d-4c3efe7bb481.png) 全是报错

see #244
