### ISSUE TITLE
添加词条是图片读取不了

### ISSUE THREAD

**Issue by nertcy** [HibiKier/zhenxun_bot#463]
![image](https://user-images.githubusercontent.com/94539226/169571837-6669b2b0-d5cd-4e28-9a5b-1cdeece7ef0e.png)

![image](https://user-images.githubusercontent.com/94539226/169571569-f3ce6e8e-860e-4d7d-b104-41d78a9b5c86.png)

**Comment by HibiKier** [comment]
发一下你
![图片](https://user-images.githubusercontent.com/45528451/169582613-a08f637b-8cbc-4c85-9ac8-423bb4b2d142.png)
这个命令的完整日志

**Comment by nertcy** [comment]
> 发一下你 ![图片](https://user-images.githubusercontent.com/45528451/169582613-a08f637b-8cbc-4c85-9ac8-423bb4b2d142.png) 这个命令的完整日志

![image](https://user-images.githubusercontent.com/94539226/169641922-fb0fcd22-0a4b-478e-af17-4593079ef1c7.png)
昨天的日志找不到了，这是今天刚刚测试的，请确认
