### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Arturia169** [HibiKier/zhenxun_bot#464]
![image](https://user-images.githubusercontent.com/69199123/169573955-81382703-2e4d-4d54-81d0-a3d5f5944c71.png)

**Comment by MingxuanGame** [comment]
修改配置后重启即可

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/169577455-f4d94d25-aa4d-44df-9859-3c75081a0ca2.png)
现在跑起来了但是这个一直连接超时 导致机器人无法正常运行

**Comment by Arturia169** [comment]
已解决
