### ISSUE TITLE
更新cookie后，查询Buff武器价格报错

### ISSUE THREAD

**Issue by A1oneR** [HibiKier/zhenxun_bot#465]
![}T%J3EVYXORN YCPMZO79TJ](https://user-images.githubusercontent.com/70164765/169582485-5181329b-b73b-4ec4-af22-b0bdfb727b9c.png)
![B~)_(M`~HI MECRN{8LE1`7](https://user-images.githubusercontent.com/70164765/169582501-558b6d87-5934-4691-b905-21601f8f384b.png)

**Comment by MingxuanGame** [comment]
检查下你的 cookie，是否存在汉字等

**Comment by A1oneR** [comment]
不存在汉字

**Comment by A1oneR** [comment]
![M1JGHJ6CLJ@B}(X$W5WQPYM](https://user-images.githubusercontent.com/70164765/169583765-7e77b993-d8e7-4ab7-9c59-557efc1f7f75.png)

**Comment by A1oneR** [comment]
再次检查完毕，发现是data/configs/plugins2config.yaml内cookie value数值出现中文所导致的，现已完成修改，感谢开发人员对我不过脑的问题进行回复。
