### ISSUE TITLE
P站排行 R18发不出图片 显示网络不好

### ISSUE THREAD

**Issue by nefarians** [HibiKier/zhenxun_bot#466]
P站排行指令1-5都可以 6-8指令BOT永远都回复 “网络不太好？没有该页数？也许过一会就好了...”
BOT显示
05-20 19:39:04 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
05-20 19:39:04 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
05-20 19:39:04 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
05-20 19:39:04 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
05-20 19:39:04 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
05-20 19:39:04 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
05-20 19:39:04 [INFO] nonebot | Event will be handled by <Matcher from plugins.pixiv_rank_search, type=message, priority=5, temp=False>
05-20 19:39:05 [INFO] nonebot | Matcher <Matcher from plugins.pixiv_rank_search, type=message, priority=5, temp=False> running complete

**Comment by MingxuanGame** [comment]
请发送显示网络不好时的机器人日志，如果可以，也请提供当时的 gocqhttp 日志

**Comment by nefarians** [comment]
> 请发送显示网络不好时的机器人日志，如果可以，也请提供当时的 gocqhttp 日志
![BOT日志](https://user-images.githubusercontent.com/25260709/169629403-a1829609-67c7-4733-904c-bd2e5482bc7f.jpg)
![gocqhttp日志](https://user-images.githubusercontent.com/25260709/169629404-adf2b9ce-d3b8-4f03-baad-6cd81d7e7b6b.jpg)
![回复](https://user-images.githubusercontent.com/25260709/169629405-8fb020bd-fb6c-461c-8ccb-ccefe11fa9ee.jpg)

**Comment by milkasir** [comment]
相同问题，我是除了p站排行1和2以外都是该回复

**Comment by milkasir** [comment]
> 相同问题，我是除了p站排行1和2以外都是该回复

补充，都试了一遍我的8也能用，也就是周级别的可以查看，感觉是网络问题？

**Comment by HibiKier** [comment]
确实是网络问题或hibiapi那边没有数据
