### ISSUE TITLE
定时任务管理

### ISSUE THREAD

**Issue by ExcitedEven** [HibiKier/zhenxun_bot#467]
请问一下, 定时任务有没有统一的管理文件.
比如 epic插件 写了每天中午自动发送的命令. 我想让他每周只发送一次, 是要去 epic插件 的文件里面直接改 `cron` 代码, 还是有个文件可以直接管理
![image](https://user-images.githubusercontent.com/23137266/169626896-f686bd23-53a3-4a8d-a589-f177cacd5afb.png)

**Comment by HibiKier** [comment]
目前需要改源码

**Comment by ExcitedEven** [comment]
> 目前需要改源码

好的,谢谢
