### ISSUE TITLE
数据库连接失败力

### ISSUE THREAD

**Issue by TDuckQWQ** [HibiKier/zhenxun_bot#468]
![image](https://user-images.githubusercontent.com/62102282/169631067-6dc65b65-51b3-485e-838c-991be82cb3ac.png)
![image](https://user-images.githubusercontent.com/62102282/169631089-ddca29da-8d7e-4b3e-8576-472eb8d091f1.png)
是因为什么问题哇....

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169631164-6fbcb73f-e1cb-4532-9af5-95a086a8303f.png)
啊还有个这个

**Comment by MingxuanGame** [comment]
图一：填到引号里

图二：

```
pip install emoji
```

**Comment by TDuckQWQ** [comment]
唔唔，我再试试

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169631410-c011cdfe-9342-4934-81c4-bf2637363cb4.png)
![image](https://user-images.githubusercontent.com/62102282/169631427-9b78a4a2-0b7e-4a0a-a195-06d9dc1b9f0f.png)
啊嘞......

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169631518-06e9bd11-ff61-487f-839a-3fda0838af97.png)
唔？

**Comment by MingxuanGame** [comment]
> ![image](https://user-images.githubusercontent.com/62102282/169631518-06e9bd11-ff61-487f-839a-3fda0838af97.png) 唔？

```bash
pip install wordcloud
```

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169631630-466278da-6799-4f7d-b196-f947fef52946.png)

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169631655-ddf41593-e2b1-4feb-ad59-54cae15ec788.png)

**Comment by TDuckQWQ** [comment]
> ![image](https://user-images.githubusercontent.com/62102282/169631410-c011cdfe-9342-4934-81c4-bf2637363cb4.png) ![image](https://user-images.githubusercontent.com/62102282/169631427-9b78a4a2-0b7e-4a0a-a195-06d9dc1b9f0f.png) 啊嘞......

话说这个数据库是怎么回事哇

**Comment by MingxuanGame** [comment]
你的数据库开启了吗

**Comment by TDuckQWQ** [comment]
> 你的数据库开启了吗

![image](https://user-images.githubusercontent.com/62102282/169632616-74f8f293-5bab-47b2-ac65-4ba56afa5757.png)
是这样子的吗

**Comment by MingxuanGame** [comment]
> ![image](https://user-images.githubusercontent.com/62102282/169631655-ddf41593-e2b1-4feb-ad59-54cae15ec788.png)

https://download.visualstudio.microsoft.com/download/pr/d06b357b-3d84-49ac-acc4-68ed90dc799f/ca1d6619a5414c67c290daf248dafbd402e5bf33cd92ecf0e3d94252fad4da20/vs_BuildTools.exe

下载 vs 生成工具安装

![image](https://user-images.githubusercontent.com/68982190/169632670-28f0e00d-bba5-4920-95cd-c7740d6fbab7.png)

**Comment by MingxuanGame** [comment]
> > 你的数据库开启了吗
> 
> ![image](https://user-images.githubusercontent.com/62102282/169632616-74f8f293-5bab-47b2-ac65-4ba56afa5757.png) 是这样子的吗

开允许访问了吗

postgresql.conf：

> 找到 listen_addresses: '*' 取消前面的 # 注释，保存退出

pg_hba.conf：

> 在最下添加或修改后，保存退出

```
# 允许任意用户从任意机器上以密码方式访问数据库
host    all             all             0.0.0.0/0               md5
```

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169633509-54eede02-05f1-49ee-97f8-0b121d4e1a27.png)
咕噜咕噜

**Comment by TDuckQWQ** [comment]
> > ![image](https://user-images.githubusercontent.com/62102282/169631655-ddf41593-e2b1-4feb-ad59-54cae15ec788.png)
> 
> https://download.visualstudio.microsoft.com/download/pr/d06b357b-3d84-49ac-acc4-68ed90dc799f/ca1d6619a5414c67c290daf248dafbd402e5bf33cd92ecf0e3d94252fad4da20/vs_BuildTools.exe
> 
> 下载 vs 生成工具安装
> 
> ![image](https://user-images.githubusercontent.com/68982190/169632670-28f0e00d-bba5-4920-95cd-c7740d6fbab7.png)

![image](https://user-images.githubusercontent.com/62102282/169633575-4bc11c29-441c-4a48-b26f-f4e5bf022241.png)
唔？ 我装了vs

**Comment by MingxuanGame** [comment]
> > > ![image](https://user-images.githubusercontent.com/62102282/169631655-ddf41593-e2b1-4feb-ad59-54cae15ec788.png)
> > 
> > 
> > https://download.visualstudio.microsoft.com/download/pr/d06b357b-3d84-49ac-acc4-68ed90dc799f/ca1d6619a5414c67c290daf248dafbd402e5bf33cd92ecf0e3d94252fad4da20/vs_BuildTools.exe
> > 下载 vs 生成工具安装
> > ![image](https://user-images.githubusercontent.com/68982190/169632670-28f0e00d-bba5-4920-95cd-c7740d6fbab7.png)
> 
> ![image](https://user-images.githubusercontent.com/62102282/169633575-4bc11c29-441c-4a48-b26f-f4e5bf022241.png) 唔？ 我装了vs

你这是之前装了又删了吗？重装一下看看

**Comment by TDuckQWQ** [comment]
数据库应该是开了允许访问的，是不是我哪里填错了？

**Comment by MingxuanGame** [comment]
可能和 #194 一样

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169633782-70d246be-7f78-416c-a9e7-5156e7eca234.png)
应该没有吧，我vs也在的说

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169633782-70d246be-7f78-416c-a9e7-5156e7eca234.png)
应该没有吧，我vs也在的说

> 可能和 #194 一样

那我看看

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169634010-1ca5cdbd-e903-4921-8b7d-6bb7e4e7f99f.png)
！！算是连上了吧

**Comment by TDuckQWQ** [comment]
就是这个wordcloud还是error诶....

**Comment by MingxuanGame** [comment]
连上了

**Comment by TDuckQWQ** [comment]
> 就是这个wordcloud还是error诶....

![image](https://user-images.githubusercontent.com/62102282/169634043-b0c08a89-7108-4990-b30a-12687929443a.png)

**Comment by MingxuanGame** [comment]
> 就是这个wordcloud还是error诶....

试着删除 VS 和生成工具重装，并重启吧

没找到 python 3.9 的 windows wheel 包

**Comment by TDuckQWQ** [comment]
唔唔
![image](https://user-images.githubusercontent.com/62102282/169634208-39163b14-bf36-4347-a1b1-e2f2dd2c933e.png)
诶这个...

**Comment by MingxuanGame** [comment]
> 唔唔 ![image](https://user-images.githubusercontent.com/62102282/169634208-39163b14-bf36-4347-a1b1-e2f2dd2c933e.png) 诶这个...

你在 gocqhttp 运行的时候同时运行 `bot.py` 了吗（`bot.py` 需要加载全部插件，启动慢是正常，等待一会即可）

**Comment by TDuckQWQ** [comment]
> > 唔唔 ![image](https://user-images.githubusercontent.com/62102282/169634208-39163b14-bf36-4347-a1b1-e2f2dd2c933e.png) 诶这个...
> 
> 你在 gocqhttp 运行的时候同时运行 `bot.py` 了吗（`bot.py` 需要加载全部插件，启动慢是正常，等待一会即可）

好了好了  谢谢！！

**Comment by TDuckQWQ** [comment]
话说
![image](https://user-images.githubusercontent.com/62102282/169635118-c457aba0-b5cc-41ef-9a4d-f31440d74e3e.png)
这些指令是要怎么管理来着

**Comment by TDuckQWQ** [comment]
数据库又又又寄了
![image](https://user-images.githubusercontent.com/62102282/183566021-470c958f-c646-445c-b300-dd38b0860c0d.png)

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/183566748-0350dfc6-c161-4172-a5bf-d6804b83c5f1.png)
