### ISSUE TITLE
一键安装脚本的zhenxun数据库密码是多少啊=。=

### ISSUE THREAD

**Issue by Misakami** [HibiKier/zhenxun_bot#469]
![image](https://user-images.githubusercontent.com/22981008/169633645-1648f487-3686-47a0-a10f-dbd4e3c54fae.png)
jiemi解密不出来 想远程链接。。。

**Comment by MingxuanGame** [comment]
https://github.com/zhenxun-org/zhenxun_bot-deploy/blob/9501e63528ad2da5ddc1d4a16b378fcf53201a61/install.sh#L246

用户名：zhenxun

密码：zxpassword

**Comment by milkasir** [comment]
> https://github.com/zhenxun-org/zhenxun_bot-deploy/blob/9501e63528ad2da5ddc1d4a16b378fcf53201a61/install.sh#L246
> 
> 用户名：zhenxun
> 
> 密码：zxpassword

（虽然真寻已经在正常运行还是想了解和请教一下）
一键脚本有设置初始用户postgres的密码吗，我在root用户用sudo su - postgres之后好像是转到系统的postgres用户上，然后不管是psq1还是其他操作它都要我输入密码但既不是我的系统密码也不是zxpassword也不是空白
相对的，该按什么顺序和指令来进入数据库的zhenxun用户和数据库呢
以下是日志（基本没有基础所以可能是是很浅显的问题抱歉）
root@VM-12-8-ubuntu:~# sudo su zhenxun
su: user zhenxun does not exist
root@VM-12-8-ubuntu:~# sudo su - postgres
postgres@VM-12-8-ubuntu:~$ psq1

Command 'psq1' not found, did you mean:

  command 'psql' from deb postgresql-client-common (214ubuntu0.1)

Try: apt install <deb name>

postgres@VM-12-8-ubuntu:~$ su - postgres
Password: （这里ctrl c了）
postgres@VM-12-8-ubuntu:~$ su - zhenxun
su: user zhenxun does not exist
