### ISSUE TITLE
关于昵称

### ISSUE THREAD

**Issue by JMFANS** [HibiKier/zhenxun_bot#47]
env文件的nickname和config的nickname有什么区别呢

**Comment by HibiKier** [comment]
.env的nickname相当于喊["真寻", "小真寻", "绪山真寻", "小寻子"]等于艾特真寻，config中的nickname主要是用于在某些回复输出bot的名称，因为使用list(bot.config.nickname)[0]的话是.env中nickname每次重启随机的，所以在config中添加nickname来固定某些插件输出的机器人名称，示例：f"你为啥不查火星的天气呢？{NICKNAME}只支持国内天气查询!!"

**Comment by JMFANS** [comment]
好的，谢谢
