### ISSUE TITLE
运行bot.py时提示没有找到名为nonebot.adapters.onebot的模块

### ISSUE THREAD

**Issue by Snigellin** [HibiKier/zhenxun_bot#472]
如图
![O_ S@VD%01HQQM})ENNGHNW](https://user-images.githubusercontent.com/92661777/169635191-59b679f4-cdc9-484d-82d3-8e88d5d5e164.png)

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169636532-3f3d6029-8d05-44f1-b9bb-69321c91eb6b.png)

**Comment by Snigellin** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169636532-3f3d6029-8d05-44f1-b9bb-69321c91eb6b.png)

装过了

**Comment by Snigellin** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169636532-3f3d6029-8d05-44f1-b9bb-69321c91eb6b.png)
![FDMLQ%P%J5V S46 V



> ![图片](https://user-images.githubusercontent.com/45528451/169636532-3f3d6029-8d05-44f1-b9bb-69321c91eb6b.png)
XIBH](https://user-images.githubusercontent.com/92661777/169637165-5d4ab79f-32be-49f5-8c06-fe4afbe7b67f.png)
![LIP1GQF%HL4FMTXYLH6L22J](https://user-images.githubusercontent.com/92661777/169637172-875c6477-58ee-4605-8d6a-837f346acfd5.png)

**Comment by MingxuanGame** [comment]
使用 python 3.8 或 3.9

**Comment by HibiKier** [comment]
确实，没注意看版本，需要py3.8 3.9

**Comment by Snigellin** [comment]
> 确实，没注意看版本，需要py3.8 3.9

版本更换为3.9后poetry命令无法被识别是怎么回事
![1AWQX K_1K5 SVE{JH~UFIN](https://user-images.githubusercontent.com/92661777/169640391-0dae7359-c070-40eb-9e98-050a61822e71.png)

**Comment by MingxuanGame** [comment]
> > 确实，没注意看版本，需要py3.8 3.9
> 
> 版本更换为3.9后poetry命令无法被识别是怎么回事 ![1AWQX K_1K5 SVE{JH~UFIN](https://user-images.githubusercontent.com/92661777/169640391-0dae7359-c070-40eb-9e98-050a61822e71.png)

python -m poetry

**Comment by Snigellin** [comment]
> > > 确实，没注意看版本，需要py3.8 3.9
> > 
> > 
> > 版本更换为3.9后poetry命令无法被识别是怎么回事 ![1AWQX K_1K5 SVE{JH~UFIN](https://user-images.githubusercontent.com/92661777/169640391-0dae7359-c070-40eb-9e98-050a61822e71.png)
> 
> python -m poetry

pip3 install poetry和poetry install重新运行了一遍，进poetry shell后提示没有nonebo
![W{S5K%}L%S_4{DP$JSN9RY](https://user-images.githubusercontent.com/92661777/169641052-d1dbb516-c66c-434a-8936-71d697a13d21.png)
t

**Comment by Snigellin** [comment]
> 使用 python 3.8 或 3.9

pip3 install poetry和poetry install重新运行了一遍，进poetry shell后提示没有nonebot
![W{S5K%}L%S_4{DP$JSN9RY](https://user-images.githubusercontent.com/92661777/169641989-2b63fdbd-5072-4528-bfee-c5c20b29409a.png)

**Comment by Snigellin** [comment]
> 确实，没注意看版本，需要py3.8 3.9

大佬，其他的弄好了，回到了最开始的问题
No module named 'nonebot.adapters.onebot'
![RW~}(_)Z{)Z$C}2$8UD6%SN](https://user-images.githubusercontent.com/92661777/169644208-73a4fd24-b4c5-45bf-b6c2-5649981a9bac.png)

**Comment by Snigellin** [comment]
> > > 确实，没注意看版本，需要py3.8 3.9
> > 
> > 
> > 版本更换为3.9后poetry命令无法被识别是怎么回事 ![1AWQX K_1K5 SVE{JH~UFIN](https://user-images.githubusercontent.com/92661777/169640391-0dae7359-c070-40eb-9e98-050a61822e71.png)
> 
> python -m poetry

No module named 'nonebot.adapters.onebot'
![RW~}(_)Z{)Z$C}2$8UD6%SN](https://user-images.githubusercontent.com/92661777/169644274-b0af4396-bfa8-4018-aea1-c80b840d1b5a.png)

**Comment by WWWA7** [comment]
> > > > 确实，没注意看版本，需要py3.8 3.9
> > > 
> > > 
> > > 版本更换为3.9后poetry命令无法被识别是怎么回事 ![1AWQX K_1K5 SVE{JH~UFIN](https://user-images.githubusercontent.com/92661777/169640391-0dae7359-c070-40eb-9e98-050a61822e71.png)
> > 
> > 
> > python -m poetry
> 
> No module named 'nonebot.adapters.onebot' ![RW~}(_)Z{)Z$C}2$8UD6%SN](https://user-images.githubusercontent.com/92661777/169644274-b0af4396-bfa8-4018-aea1-c80b840d1b5a.png)

你这个不是No module named 'nonebot.adapters.onebot'的问题，是上边的No module named 'python'的问题
盲猜环境变量没配

**Comment by Snigellin** [comment]
> 

好的，将环境变量配置好后依旧提示缺失
![BRS~XMG`(JW~BEYUO5Z%D)1](https://user-images.githubusercontent.com/92661777/169689486-c285952a-0dc6-4921-93c7-00d509af4c5b.png)

**Comment by Snigellin** [comment]
> > > > > 确实，没注意看版本，需要py3.8 3.9
> > > > 
> > > > 
> > > > 版本更换为3.9后poetry命令无法被识别是怎么回事 ![1AWQX K_1K5 SVE{JH~UFIN](https://user-images.githubusercontent.com/92661777/169640391-0dae7359-c070-40eb-9e98-050a61822e71.png)
> > > 
> > > 
> > > python -m poetry
> > 
> > 
> > No module named 'nonebot.adapters.onebot' ![RW~}(_)Z{)Z$C}2$8UD6%SN](https://user-images.githubusercontent.com/92661777/169644274-b0af4396-bfa8-4018-aea1-c80b840d1b5a.png)
> 
> 你这个不是No module named 'nonebot.adapters.onebot'的问题，是上边的No module named 'python'的问题 盲猜环境变量没配

将环境变量配置好后依旧提示缺失，请问是什么问题
![BRS~XMG`(JW~BEYUO5Z%D)1](https://user-images.githubusercontent.com/92661777/169689527-25d382a5-56e9-4cac-a2b9-ce2eefac2fba.png)

**Comment by WWWA7** [comment]
> > 
> 
> 好的，将环境变量配置好后依旧提示缺失 ![BRSXMG`(JWBEYUO5Z%D)1](https://user-images.githubusercontent.com/92661777/169689486-c285952a-0dc6-4921-93c7-00d509af4c5b.png)

接下来 pip install nonebot.adapters.onebot 试试

**Comment by Snigellin** [comment]
> 



> > > 
> > 
> > 
> > 好的，将环境变量配置好后依旧提示缺失 ![BRSXMG`(JWBEYUO5Z%D)1](https://user-images.githubusercontent.com/92661777/169689486-c285952a-0dc6-4921-93c7-00d509af4c5b.png)
> 
> 接下来 pip install nonebot.adapters.onebot 试试
是需要更新版本吗
![`0@~M Q} DCB99AN4A E@2Y](https://user-images.githubusercontent.com/92661777/169689863-5fe3795f-11fc-4b73-bdcc-ed83722dd95e.png)

**Comment by WWWA7** [comment]
> > 
> 
> > > > 
> > > 
> > > 
> > > 好的，将环境变量配置好后依旧提示缺失 ![BRSXMG`(JWBEYUO5Z%D)1](https://user-images.githubusercontent.com/92661777/169689486-c285952a-0dc6-4921-93c7-00d509af4c5b.png)
> > 
> > 
> > 接下来 pip install nonebot.adapters.onebot 试试
> > 是需要更新版本吗
> > ![`0@~M Q} DCB99AN4A E@2Y](https://user-images.githubusercontent.com/92661777/169689863-5fe3795f-11fc-4b73-bdcc-ed83722dd95e.png)

百度一下Could not find a version that satisfies the requirement，看看别人怎么解决的，试试能不能解决

**Comment by Snigellin** [comment]
> > > 
> > 
> > 
> > > > > 
> > > > 
> > > > 
> > > > 好的，将环境变量配置好后依旧提示缺失 ![BRSXMG`(JWBEYUO5Z%D)1](https://user-images.githubusercontent.com/92661777/169689486-c285952a-0dc6-4921-93c7-00d509af4c5b.png)
> > > 
> > > 
> > > 接下来 pip install nonebot.adapters.onebot 试试
> > > 是需要更新版本吗
> > > ![`0@~M Q} DCB99AN4A E@2Y](https://user-images.githubusercontent.com/92661777/169689863-5fe3795f-11fc-4b73-bdcc-ed83722dd95e.png)
> 
> 百度一下Could not find a version that satisfies the requirement，看看别人怎么解决的，试试能不能解决

好的，谢谢

**Comment by endlessberial** [comment]
![image](https://user-images.githubusercontent.com/104594865/190631472-120b3c2e-f110-43c3-8590-3a5ecf2eeebc.png)
lz解决了吗，我也遇到这个问题了，前面的楼层我也都看完了但还是没解决，dd

**Comment by M946i** [comment]
> > > > 
> > > 
> > > 
> > > > > > 
> > > > > 
> > > > > 
> > > > > 好的，将环境变量配置好后依旧提示缺失 ![BRSXMG`(JWBEYUO5Z%D)1](https://user-images.githubusercontent.com/92661777/169689486-c285952a-0dc6-4921-93c7-00d509af4c5b.png)
> > > > 
> > > > 
> > > > 接下来 pip install nonebot.adapters.onebot 试试
> > > > 是需要更新版本吗
> > > > ![`0@~M Q} DCB99AN4A E@2Y](https://user-images.githubusercontent.com/92661777/169689863-5fe3795f-11fc-4b73-bdcc-ed83722dd95e.png)
> > 
> > 
> > 百度一下Could not find a version that satisfies the requirement，看看别人怎么解决的，试试能不能解决
> 
> 好的，谢谢

poetry shell之后pip install nonebot-adapter-onebot
