### ISSUE TITLE
搜番出现以下错误

### ISSUE THREAD

**Issue by SPLUS-VABLE** [HibiKier/zhenxun_bot#473]
![image](https://user-images.githubusercontent.com/42440354/169637051-ad493f1f-ddbf-4d90-a6f2-278f7e728b5d.png)
是网络问题？

**Comment by HibiKier** [comment]
是的

**Comment by SPLUS-VABLE** [comment]
好的，感谢大佬解答！

**Comment by Judp28** [comment]
怎么解决的

**Comment by SPLUS-VABLE** [comment]
没有解决，可能需要加速器。
