### ISSUE TITLE
报错 ModuleNotFoundError: No module named 'jinja2'

### ISSUE THREAD

**Issue by Renouer** [HibiKier/zhenxun_bot#479]
![QQ_kGlcPB8Nhz](https://user-images.githubusercontent.com/95909116/169639766-1b230c8f-6dbc-4330-a31c-7f054b20edc3.png)
已经用pip装上了Jinja2了，但是还是找不到，请问是什么问题吗？

**Comment by Su-Dream** [comment]
> ![QQ_kGlcPB8Nhz](https://user-images.githubusercontent.com/95909116/169639766-1b230c8f-6dbc-4330-a31c-7f054b20edc3.png) 已经用pip装上了Jinja2了，但是还是找不到，请问是什么问题吗？

poetry add Jinja2

**Comment by Renouer** [comment]
> > ![QQ_kGlcPB8Nhz](https://user-images.githubusercontent.com/95909116/169639766-1b230c8f-6dbc-4330-a31c-7f054b20edc3.png) 已经用pip装上了Jinja2了，但是还是找不到，请问是什么问题吗？
> 
> poetry add Jinja2
![mstsc_9KK8Ku8YYE](https://user-images.githubusercontent.com/95909116/169641229-67af1946-48d8-43ba-a4b7-e7addcaa5ef5.png)
添加后是SSLError 这是网络问题吗？

**Comment by MingxuanGame** [comment]
> > > ![QQ_kGlcPB8Nhz](https://user-images.githubusercontent.com/95909116/169639766-1b230c8f-6dbc-4330-a31c-7f054b20edc3.png) 已经用pip装上了Jinja2了，但是还是找不到，请问是什么问题吗？
> > 
> > 
> > poetry add Jinja2
> > ![mstsc_9KK8Ku8YYE](https://user-images.githubusercontent.com/95909116/169641229-67af1946-48d8-43ba-a4b7-e7addcaa5ef5.png)
> > 添加后是SSLError 这是网络问题吗？

你是使用了代理吗？如果是请关闭

**Comment by Renouer** [comment]
感谢，已解决！
