### ISSUE TITLE
[Bug] CSGO开箱模拟 接受负数

### ISSUE THREAD

**Issue by Fjaxzhy** [HibiKier/zhenxun_bot#48]
具体见图
![Bug复现](https://user-images.githubusercontent.com/33241583/133021161-68514fa8-b6bf-40c4-884a-19cc004b20d7.png)

**Comment by Fjaxzhy** [comment]
离离原上谱 #滑稽

**Comment by Fjaxzhy** [comment]
复现
![图片](https://user-images.githubusercontent.com/33241583/133021826-3d3eed91-9517-4e93-97e4-412bdaa22f92.png)

**Comment by Fjaxzhy** [comment]
在每日次数用尽后不能使用bug
![图片](https://user-images.githubusercontent.com/33241583/133022009-36a959ed-c095-49d7-8a1e-d8ea8e3d9cd2.png)

**Comment by yusana213214** [comment]
草，离谱

**Comment by yusana213214** [comment]
话说显示图片需要挂代理吗，，，还是啥

**Comment by HibiKier** [comment]
本地有图片资源就行

**Comment by yusana213214** [comment]
> 本地有图片资源就行

那么如何获取呢（×）

**Comment by HibiKier** [comment]
仓库里
