### ISSUE TITLE
我想要指定群聊关闭coser以及色图功能

### ISSUE THREAD

**Issue by Su-Dream** [HibiKier/zhenxun_bot#480]
我该怎么做，貌似没有这方面的issues

**Comment by IrisMiko** [comment]
可以去/data/managergroup_manager.json这个文件里面找到不想打开的群把"level"改成-1然后重启；或者在不想打开的群里发送关闭coser，关闭色图

**Comment by Su-Dream** [comment]
> 可以去/data/managergroup_manager.json这个文件里面找到不想打开的群把"level"改成-1然后重启；或者在不想打开的群里发送关闭coser，关闭色图

感谢
