### ISSUE TITLE
epic功能配图异常

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#483]
![image](https://user-images.githubusercontent.com/50237543/169641009-cf8ab31b-bcf0-4fa4-a1f1-a6ba341bed7b.png)

**Comment by MingxuanGame** [comment]
https://github.com/HibiKier/zhenxun_bot/blob/f03876304179a79adc3bc250363da5da92300978/plugins/epic/data_source.py#L103-L105

`game_thumbnail = None`

**Comment by HibiKier** [comment]
92e60ba141313f5b28f89afdfe813b29f13468c1
