### ISSUE TITLE
运行bot后全是报错

### ISSUE THREAD

**Issue by Natsumelan** [HibiKier/zhenxun_bot#485]
![%~V6ECZQC4@KZ42PT7PSBOP](https://user-images.githubusercontent.com/105765802/169641355-4651d11b-25db-44a3-9880-90f7d17d30d9.png)
![Uploading 1Y_4BTQXJ7X7$QQ@TLN2Y0E.png…]()
![Uploading EF{{EMOXAAY[]87XGHGI)2V.png…]()
![Uploading }{SD$G3_SF0{HSZHZ8~SX15.png…]()
😭

**Comment by whoismygrandson** [comment]
依赖没装完全

**Comment by MingxuanGame** [comment]
Duplicate of https://github.com/HibiKier/zhenxun_bot/issues/459#issuecomment-1133549048

**Comment by Natsumelan** [comment]
> Duplicate of [#459 (comment)](https://github.com/HibiKier/zhenxun_bot/issues/459#issuecomment-1133549048)

好了好了，多谢
