### ISSUE TITLE
自定义插件logo安装失败，提示 No module named 'jinja2'

### ISSUE THREAD

**Issue by SpideyUU** [HibiKier/zhenxun_bot#486]
安装自定义插件[logo](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/tree/master/logo)之后无法正常装载
（已经在bot.py中添加新代码）
![image](https://user-images.githubusercontent.com/34191381/169641892-30643eb8-a77d-4fd1-ad77-dae5199bd596.png)
启动后出现以下报错
![image](https://user-images.githubusercontent.com/34191381/169641813-458e21aa-f7e3-4147-bdbb-0fee29a9c365.png)
按照错误代码检查jinja2模块发现安装正常，求助如何解决。
![image](https://user-images.githubusercontent.com/34191381/169641836-b8ca2f7f-b208-487a-a3e6-f0b3866f1d68.png)

**Comment by HibiKier** [comment]
poetry add jinjia2

**Comment by SpideyUU** [comment]
> poetry add jinjia2

重新执行
pip3 install poetry
poetry install
后出现如下错误，且poetry add jinjia2后控制台无回应（开启全局代理也无效）
![image](https://user-images.githubusercontent.com/34191381/169642693-dd15678b-13fb-4837-bd6a-af40c76d9d54.png)

**Comment by SpideyUU** [comment]
> poetry add jinjia2

![image](https://user-images.githubusercontent.com/34191381/169642892-ea4194cc-cdfb-4278-9f07-fad0976c5fe9.png)
成功执行poetry add jinjia2得到的结果

**Comment by SpideyUU** [comment]
> > poetry add jinjia2
> 
> ![image](https://user-images.githubusercontent.com/34191381/169642892-ea4194cc-cdfb-4278-9f07-fad0976c5fe9.png) 成功执行poetry add jinjia2得到的结果

刚才是错误拼写，改正后一直处于此状态，目前钱已经等待20分钟
![image](https://user-images.githubusercontent.com/34191381/169643762-6d6f4277-6055-42dd-a288-ddcec0576b61.png)

**Comment by SpideyUU** [comment]
单纯网络问题，case closed。
