### ISSUE TITLE
emm好像不太会搭web ui的样子

### ISSUE THREAD

**Issue by TDuckQWQ** [HibiKier/zhenxun_bot#487]
![image](https://user-images.githubusercontent.com/62102282/169641919-ffd12286-4c41-42aa-a8f5-99f9bc477e70.png)

**Comment by MingxuanGame** [comment]
超时了

试试挂代理或者国内镜像

**Comment by TDuckQWQ** [comment]
> 超时了
> 
> 试试挂代理或者国内镜像

![image](https://user-images.githubusercontent.com/62102282/169642661-ab0c3b85-aac1-4730-9487-65133d936a27.png)
好慢.....都不知道是在下还是卡了...

**Comment by TDuckQWQ** [comment]
唔
![image](https://user-images.githubusercontent.com/62102282/169643641-2f2be309-ca96-44f6-8901-eae68058fc47.png)
是我找错地方了嘛
在哪打开呀....

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169643974-d79f53af-6956-4d43-af5a-1888cbcd3473.png)
呜呜呜

**Comment by Sakuracio** [comment]
如果没有 NodeJS 基础你可以不安装 WebUI，这并不影响你的 Bot 运行。

**Comment by TDuckQWQ** [comment]
但还是想整上可视化后台...呜呜

**Comment by TDuckQWQ** [comment]
那后台怎么用..来着

**Comment by Su-Dream** [comment]
> 唔 ![image](https://user-images.githubusercontent.com/62102282/169643641-2f2be309-ca96-44f6-8901-eae68058fc47.png) 是我找错地方了嘛 在哪打开呀....

在这一步
输入npm install yarn -g
然后输入yarn
最后输入yarn serve

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169655782-dfc28c1a-0965-4c8a-afdd-cf0faa63cc31.png)
啊嘞？

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169655829-e8266a5a-4527-4cc3-8d5a-7431ef8bdee1.png)
啊嘞....？

**Comment by Su-Dream** [comment]
> ![image](https://user-images.githubusercontent.com/62102282/169655829-e8266a5a-4527-4cc3-8d5a-7431ef8bdee1.png) 啊嘞....？

npm install -g @vue/cli
yarn serve

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169656026-99796ab8-fdc7-4d1c-9b8b-08f1ecaad5fc.png)
咕噜咕噜咕噜

**Comment by Su-Dream** [comment]
> ![image](https://user-images.githubusercontent.com/62102282/169656026-99796ab8-fdc7-4d1c-9b8b-08f1ecaad5fc.png) 咕噜咕噜咕噜

yarn global add @vue/cli-service-global
然后yarn serve

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169656166-45225ef6-58d0-45be-8f87-97bd60f71276.png)
还是不行诶.....好像还是同一个error

**Comment by Su-Dream** [comment]
> ![image](https://user-images.githubusercontent.com/62102282/169656166-45225ef6-58d0-45be-8f87-97bd60f71276.png) 还是不行诶.....好像还是同一个error

那就不知道了，等大佬解答，这个应该是你环境变量问题(

**Comment by TDuckQWQ** [comment]
> > ![image](https://user-images.githubusercontent.com/62102282/169656166-45225ef6-58d0-45be-8f87-97bd60f71276.png) 还是不行诶.....好像还是同一个error
> 
> 那就不知道了，等大佬解答，这个应该是你环境变量问题(

那真寻的控制台在哪里哇...

**Comment by WWWA7** [comment]
> 

可以在本地修改代码，基本上可以更改的都有中文注释，可以去找找你需要改的东西，configs和plugins这两个文件夹里能找到你可能想要修改的大部分内容

**Comment by TDuckQWQ** [comment]
> > 
> 
> 可以在本地修改代码，基本上可以更改的都有中文注释，可以去找找你需要改的东西，configs和plugins这两个文件夹里能找到你可能想要修改的大部分内容

唔唔！

**Comment by h265642327** [comment]
先看看node，vue-cli等所需要的工具的version，判断是否安装成功
