### ISSUE TITLE
Failed to import "word_clouds"

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#488]
![QQ图片20220521142653](https://user-images.githubusercontent.com/105090141/169642527-ffa00b18-6783-458b-b769-f486ee6bdb65.png)

**Comment by MingxuanGame** [comment]
`pip install emoji`

**Comment by wlz-remake** [comment]
真寻版本：0.1.5.3
Python 3.9.13
![QQ截图20220521161653](https://user-images.githubusercontent.com/105090141/169642743-0b3615fe-aac2-42f2-8c9e-8ca6fb27d7f4.png)
![QQ截图20220521161706](https://user-images.githubusercontent.com/105090141/169642746-7cca5e6a-d291-463d-8249-70a5c6c52acd.png)

**Comment by wlz-remake** [comment]
> `pip install emoji`

十分感谢，已解决
