### ISSUE TITLE
安装环境时提示没有名为playwright的模块

### ISSUE THREAD

**Issue by Snigellin** [HibiKier/zhenxun_bot#489]

**Comment by Snigellin** [comment]
![8J8_}9LB0ROC$V45)L1GKMO](https://user-images.githubusercontent.com/92661777/169643208-a6db7715-b37b-47e8-be8a-06d350407d09.png)

**Comment by HibiKier** [comment]
poetry insatll输过了吗

**Comment by Snigellin** [comment]
> poetry insatll输过了吗

是我理解错误，我是windows系统
## playwright 需要安装额外的系统环境，在命令行输入以下
playwright install chromium

# 该命令在win下无需输入
playwright install-deps chromium
我以为只有下面这个不用
