### ISSUE TITLE
playwright问题

### ISSUE THREAD

**Issue by yusana213214** [HibiKier/zhenxun_bot#49]
记得以前处理过类似的问题，但是现在忘了，干脆发个issue问问

**Comment by yusana213214** [comment]
![-7fbf193d7c1fc822](https://user-images.githubusercontent.com/35253755/133027162-850bc51c-13a9-43c1-88b1-449054fc5599.png)

**Comment by HibiKier** [comment]
python -m playwright install-deps chromium
