### ISSUE TITLE
添加词条是图片读取不了

### ISSUE THREAD

**Issue by nertcy** [HibiKier/zhenxun_bot#492]
![image](https://user-images.githubusercontent.com/94539226/169645047-b20cae3c-f284-4b83-89c4-a103f362f9c6.png)
![image](https://user-images.githubusercontent.com/94539226/169645054-1cac66d6-4113-4d24-a7dd-c25acdf7837e.png)

**Comment by Su-Dream** [comment]
添加词条 模糊/关键字 问xxxxx答图片

**Comment by WWWA7** [comment]
先查看词条，看看有没有添加成功：查看词条xxx

**Comment by nertcy** [comment]
> 添加词条 模糊/关键字 问xxxxx答图片

请问是具体是哪个文件哪个目录的呢，有点小白。

**Comment by Su-Dream** [comment]
> > 添加词条 模糊/关键字 问xxxxx答图片
> 
> 请问是具体是哪个文件哪个目录的呢，有点小白。

直接对着你的bot输出就行

**Comment by nertcy** [comment]
> 

![image](https://user-images.githubusercontent.com/94539226/169659521-7ebe49bd-b9b5-48a6-a3e6-d724cf49e64c.png)
![image](https://user-images.githubusercontent.com/94539226/169659551-8422caf4-56c6-46cf-85c3-8c415efe3b07.png)
这样吗？

**Comment by WWWA7** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/94539226/169659521-7ebe49bd-b9b5-48a6-a3e6-d724cf49e64c.png) ![image](https://user-images.githubusercontent.com/94539226/169659551-8422caf4-56c6-46cf-85c3-8c415efe3b07.png) 这样吗？

直接在群里发  添加词条问123答111    添加成功的话他会给你反馈，提示你成功添加词条。添加后的词条可以通过：查看词条123   这个指令来查看你添加的词条，这里的123换成你添加的词条，111换成回答的内容

**Comment by Su-Dream** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/94539226/169659521-7ebe49bd-b9b5-48a6-a3e6-d724cf49e64c.png) ![image](https://user-images.githubusercontent.com/94539226/169659551-8422caf4-56c6-46cf-85c3-8c415efe3b07.png) 这样吗？
> 
> 直接在群里发 添加词条问123答111 添加成功的话他会给你反馈，提示你成功添加词条。添加后的词条可以通过：查看词条123 这个指令来查看你添加的词条，这里的123换成你添加的词条，111换成回答的内容

是的

**Comment by WWWA7** [comment]
![QQ截图20220522001049](https://user-images.githubusercontent.com/84784330/169660195-ee1323c8-3caa-42b0-8a27-5cf1796ac63f.png)

**Comment by Su-Dream** [comment]
> ![QQ截图20220522001049](https://user-images.githubusercontent.com/84784330/169660195-ee1323c8-3caa-42b0-8a27-5cf1796ac63f.png)

查看词条 111

**Comment by nertcy** [comment]
> ![QQ截图20220522001049](https://user-images.githubusercontent.com/84784330/169660195-ee1323c8-3caa-42b0-8a27-5cf1796ac63f.png)

这里做统一回复了，感谢两位大佬的指导，我安装了picsearcher这个插件，导致原本能够模糊问123答图或者文字的功能变成只能回答文字不能识别图了，就不知道是怎么回事，自己也在想办法解决。看来是自己熊掌和鱼肉不可兼得了。
![image](https://user-images.githubusercontent.com/94539226/169660375-71673230-828f-4308-9a19-8c413866b47e.png)

**Comment by HibiKier** [comment]
picsearcher插件有个matcher把所有图片都拦截了，你得改源码

**Comment by nertcy** [comment]
> 

请问能具体说一下是哪一个吗，（本人小白，也就只能通过备注和百度了）拜托了，太需要这个插件了

**Comment by nertcy** [comment]
> picsearcher插件有个matcher把所有图片都拦截了，你得改源码

请问能具体说一下是哪一个吗，（本人小白，也就只能通过备注和百度了）拜托了，太需要这个插件了

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169661738-2502104e-fa3e-48c3-b125-9fac34896485.png)
他最新的已经改过了捏

**Comment by nertcy** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169661738-2502104e-fa3e-48c3-b125-9fac34896485.png) 他最新的已经改过了捏

谢谢大佬，词条问题解决了，但是发现这个插件是不是还会干扰到真寻帮助呢？
![image](https://user-images.githubusercontent.com/94539226/169674433-70c689ed-3cc6-4e55-9457-6851f238a62d.png)

**Comment by HibiKier** [comment]
clone最新的代码
