### ISSUE TITLE
大佬，安装依赖时遇到这个报错信息怎么解决，请赐教

### ISSUE THREAD

**Issue by freesugar9** [HibiKier/zhenxun_bot#493]
PS C:\Users\Administrator\Desktop\zhenxun_bot> poetry install
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting
cies. Run update to update them.

  SolverProblemError

  Because zhenxun-bot depends on bilibili-api (^9.1.0) which doesn't match any versions, version solvi

  at ~\AppData\Local\Programs\Python\Python38\lib\site-packages\poetry\puzzle\solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

**Comment by Sakuracio** [comment]
重新 clone 代码，poetry install

**Comment by freesugar9** [comment]
> 重新 clone 代码，poetry install

Updating dependencies
Resolving dependencies... (2835.9s)

Writing lock file
这样算是成功了么

**Comment by HibiKier** [comment]
等着

**Comment by freesugar9** [comment]
> 等着

Administrator@genshin MINGW64 ~/Desktop/zhenxun_bot/zhenxun_bot (main)
$ poetry install

Updating dependencies
Resolving dependencies... (2835.9s)

Writing lock file


Administrator@genshin MINGW64 ~/Desktop/zhenxun_bot/zhenxun_bot (main)
$

Administrator@genshin MINGW64 ~/Desktop/zhenxun_bot/zhenxun_bot (main)
$


大佬，等了一晚上还是这样

**Comment by Sakuracio** [comment]
新版已修复 请重新下载文件

**Comment by freesugar9** [comment]
> 新版已修复 请重新下载文件

Administrator@genshin MINGW64 ~/Desktop
$ poetry install

  RuntimeError

  Poetry could not find a pyproject.toml file in C:\Users\Administrator\Desktop or its parents

  at ~\AppData\Local\Programs\Python\Python38\lib\site-packages\poetry\core\factory.py:369 in locate
      365▒▒             if poetry_file.exists():
      366▒▒                 return poetry_file
      367▒▒
      368▒▒         else:
    ▒▒ 369▒▒             raise RuntimeError(
      370▒▒                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371▒▒                     cwd
      372▒▒                 )
      373▒▒             )

Administrator@genshin MINGW64 ~/Desktop


额，大佬，现在变这个了，重新git clone后还是这样

**Comment by HibiKier** [comment]
进目录在运行命令
