### ISSUE TITLE
进入虚拟环境时提示环境变量错误

### ISSUE THREAD

**Issue by Snigellin** [HibiKier/zhenxun_bot#495]
![X$5GY`X0)SIE4F9F94J_HK](https://user-images.githubusercontent.com/92661777/169646999-d35522ad-4758-4d52-ae3a-cadff4517f6e.png)

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169678589-5834455a-be60-4cb1-a652-d11d374d9009.png)
试试把这个文件夹删了重新poetry install？
