### ISSUE TITLE
大佬们这是怎么回事啊，计算机小白求助

### ISSUE THREAD

**Issue by edc0127** [HibiKier/zhenxun_bot#496]
PS D:\zhenxun_bot-main> python .\bot.py
ujson module not found, using json
Traceback (most recent call last):
  File "D:\zhenxun_bot-main\bot.py", line 2, in <module>
    from nonebot.adapters.onebot.v11 import Adapter
ModuleNotFoundError: No module named 'nonebot.adapters'

我是在进行安装bot那一步，前面几步做完，运行bot.py时候就出现这些代码，运行不成功

**Comment by 9biechongfeng** [comment]
pip install nonebot-adapter-onebot

**Comment by VanadiumT** [comment]
进虚拟环境了吗

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169657625-347c841e-36d3-41f0-8b34-d5b35cfe23da.png)
