### ISSUE TITLE
关于web_ui和pix的问题

### ISSUE THREAD

**Issue by 9biechongfeng** [HibiKier/zhenxun_bot#497]
大佬请问下plugins里的web_ui和zhenxun_bot_webui有什么区别，会冲突吗？
启动bot之后总会报这个错误
![微信图片_20220521175626](https://user-images.githubusercontent.com/68093556/169647056-2b183afc-7a2b-4748-b15f-45cb94f37546.png)
pix -r 4的时候会报这样的错误
<img width="811" alt="微信图片_20220521175618" src="https://user-images.githubusercontent.com/68093556/169647106-e0f2161e-8bd9-4982-bca8-93ccb1423c17.png">
感谢大佬解答下~

**Comment by HibiKier** [comment]
#267

**Comment by HibiKier** [comment]
pix因为你数据库里没东西吧
