### ISSUE TITLE
python bot.py最后错误退出

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#498]
![终](https://user-images.githubusercontent.com/105090141/169647115-ea6e5786-7370-480c-b0b6-13c3e5f34e20.png)
心态炸了，刚把几个插件问题解决，捣鼓一天了最后给我整个这个

真寻版本v0.1.5.3
Python 3.9.13

在[真寻 bot 的插件库](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot)安装了
随机唐可可
幻影坦克
历史上的今天
抽象化/火星文
彩云小梦AI续写
人生重开模拟器
Atri语音包
每日60秒看世界

poetry shell   # 进入虚拟环境后 pip install emoji、pip install wordcloud、pip install nonebot_plugin_htmlrender、pip install requests

**Comment by HibiKier** [comment]
截全

**Comment by wlz-remake** [comment]
因其他原因重装了系统并重新部署了bot，问题暂时无法复现
