### ISSUE TITLE
识番 图片格式

### ISSUE THREAD

**Issue by akademeia** [HibiKier/zhenxun_bot#499]
更新最新的代码测试了一下
1.发送 识番+图片 的情况下能够正常获取到img_url=https://gchat.qpic.cn/gchatpic_new/......
2.先发送“识番”，bot返回“虚空识番？来图来图GKD”，再发送图片的情况下，获取到的img_url是[CQ:Image]格式，需要做字符串处理提取出CQ:Image里的url值

**Comment by HibiKier** [comment]
已修复
