### ISSUE TITLE
不能获取到原神每日素材

### ISSUE THREAD

**Issue by jimodeniuren** [HibiKier/zhenxun_bot#5]
机器人显示是更新成功了，但发出来的消息没有图，对应的存放图片的文件夹里面也并没有图
![a](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//6565646576.jpg)

**Comment by HibiKier** [comment]
你运行bot的操作系统是？

**Comment by jimodeniuren** [comment]
是CentOS8

**Comment by HibiKier** [comment]
可以给一下调用 更新原神今日素材 后台的日志嘛

**Comment by jimodeniuren** [comment]
![a](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//QQ%E6%88%AA%E5%9B%BE20210711143156.jpg)
看了一下，是因为这个playwright的问题吗，但我的环境已经是linux的环境了啊

**Comment by HibiKier** [comment]
应该不是版本问题？你重新替换一下plugins/genshin/material_remind/__init__.py，仓库里新的这份会显示具体的报错

**Comment by HibiKier** [comment]
应该不是版本问题？你重新替换一下plugins/genshin/material_remind/__init__.py，仓库里新的这份会显示具体的报错

**Comment by jimodeniuren** [comment]
![c](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//QQ%E6%88%AA%E5%9B%BE20210711145348.jpg)

**Comment by HibiKier** [comment]
奇怪了，你把update_image.py里的try和except去掉呢？

**Comment by HibiKier** [comment]
艹，打错了，是把init.py里的update_image方法里的try和except去掉

**Comment by jimodeniuren** [comment]
去掉后在启动的时候就直接报错。。
![d](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//QQ%E6%88%AA%E5%9B%BE20210711150625.jpg)
![e](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//QQ%E6%88%AA%E5%9B%BE20210711150700.jpg)

**Comment by HibiKier** [comment]
替换一下plugins/genshin/material_remind/init.py和utils/browser.py，应该可以了

**Comment by jimodeniuren** [comment]
还是不行
![f](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//QQ%E6%88%AA%E5%9B%BE20210711152757.jpg)
![g](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//QQ%E6%88%AA%E5%9B%BE20210711152811.jpg)

**Comment by HibiKier** [comment]
这个是环境问题吧？尝试安装 libnss3.so

**Comment by jimodeniuren** [comment]
确实是环境问题，现在好了

**Comment by HibiKier** [comment]
ok

**Comment by Raysamatoken** [comment]
> 这个是环境问题吧？尝试安装 libnss3.so

晕了 同样的问题 arch Linux硬是找不到 libnss3.so相关包

**Comment by HibiKier** [comment]
> 
> 
> > 这个是环境问题吧？尝试安装 libnss3.so
> 
> 晕了 同样的问题 arch Linux硬是找不到 libnss3.so相关包

试试apt install libnss3-dev？

**Comment by Raysamatoken** [comment]
> > > 这个是环境问题吧？尝试安装 libnss3.so
> > 
> > 
> > 晕了 同样的问题 arch Linux硬是找不到 libnss3.so相关包
> 
> 试试apt install libnss3-dev？

Arch用的是Pacman 算了，明天装CentOS8去

**Comment by Raysamatoken** [comment]
> > > > 这个是环境问题吧？尝试安装 libnss3.so
> > > 
> > > 
> > > 晕了 同样的问题 arch Linux硬是找不到 libnss3.so相关包
> > 
> > 
> > 试试apt install libnss3-dev？
> 
> Arch用的是Pacman 算了，明天装CentOS8去

搞定，最后依赖直接 yum install chromium 一把梭装完
