### ISSUE TITLE
求问，修改文本后没有变化

### ISSUE THREAD

**Issue by TreesFeather** [HibiKier/zhenxun_bot#500]
改了商店的文本和概率，但重启后没有任何变化，求大佬救助！
![image](https://user-images.githubusercontent.com/105774046/169648292-19431a5f-a36b-4be7-b437-5d12278f080e.png)

**Comment by HibiKier** [comment]
1.在数据库修改
或者
2.使用命令修改

**Comment by TreesFeather** [comment]
使用一键安装脚本的话怎么找数据库？还是只能用命令修改了？QAQ

**Comment by HibiKier** [comment]
推荐命令修改

**Comment by TreesFeather** [comment]
如果修改功能的权限需求和其它一些文本的话，用命令无法实现吧，刚才去查怎么通过数据库修改，没有学会。。。有没有推荐的教程之类的😰🙏

**Comment by HibiKier** [comment]
> 如果修改功能的权限需求和其它一些文本的话，用命令无法实现吧，刚才去查怎么通过数据库修改，没有学会。。。有没有推荐的教程之类的😰🙏

看开发文档

**Comment by TreesFeather** [comment]
> > 如果修改功能的权限需求和其它一些文本的话，用命令无法实现吧，刚才去查怎么通过数据库修改，没有学会。。。有没有推荐的教程之类的😰🙏
> 
> 看开发文档

谢谢你！
