### ISSUE TITLE
如何吧插件删除干净和呼叫真寻帮助没反应

### ISSUE THREAD

**Issue by nertcy** [HibiKier/zhenxun_bot#505]
问题1、我在plugins吧bilibili_sub和read_60s删除了，但是还在提示我启动失败问题
![image](https://user-images.githubusercontent.com/94539226/169651008-a98a3879-04cc-4d12-bd32-e4ebe890da06.png)
2、正常启动呼叫真寻帮助、管理员帮助、都没反应
![Q WT`ULUWSCUQ5QR@@9MIC2](https://user-images.githubusercontent.com/94539226/169651031-d20e3b5a-7353-4ccd-be61-24d8bd9d8dd5.png)
![image](https://user-images.githubusercontent.com/94539226/169651338-204f2a81-0626-477d-8355-3b8d28583350.png)

**Comment by HibiKier** [comment]
虽然不明白发生了什么，但是你可以先更新代码，可以避免出现帮助错误

**Comment by nertcy** [comment]
> 虽然不明白发生了什么，但是你可以先更新代码，可以避免出现帮助错误

虽然不是很会，但是请问大佬在哪里进行更新呢？能可具体说一下嘛，谢谢

**Comment by HibiKier** [comment]
main分支

**Comment by nertcy** [comment]
> main分支

直接覆盖原文件吗请问。还是重新部署真寻bot呢

**Comment by HibiKier** [comment]
覆盖代码就行了
