### ISSUE TITLE
send_setu 网络错误

### ISSUE THREAD

**Issue by KuLiPoi** [HibiKier/zhenxun_bot#506]
send_setu 插件提示网络错误
控制台提示  send_setu 访问页面错误 <class 'httpx.ConnectTimeout'>：

我这边是路由器梯子，基本不会是被墙的原因。

我看了一下 pixiv.cat 好像是证书掉了 不知道是不是这个问题，
看别的issue说群里发了一个新的data_resource.py，我也没找到。

**Comment by Slinet6056** [comment]
会不会是梯子的规则列表里没有让 `pixiv.re` 走代理

**Comment by KuLiPoi** [comment]
我尝试把 i.pixiv.cat 和 pixiv.re 都加进强制代理列表了 但是还是不行 我用同一个网络内的另一个电脑可以正常访问两个域名，
另一台电脑只是Ubuntu，我自认为应该没有差别...
[![OvsH4s.md.png](https://s1.ax1x.com/2022/05/21/OvsH4s.md.png)](https://imgtu.com/i/OvsH4s)
[![OvsqCn.md.png](https://s1.ax1x.com/2022/05/21/OvsqCn.md.png)](https://imgtu.com/i/OvsqCn)

**Comment by KuLiPoi** [comment]
解决方法恰恰相反，要把 ```  *.pixiv.cat / *.pixiv.re / *.lolicon.app ``` 放进强制不走代理的列表里，虽然不知道原因为何，但是不走代理一切正常了。
