### ISSUE TITLE
小白求助：看不见postgresql里的表

### ISSUE THREAD

**Issue by RShock** [HibiKier/zhenxun_bot#507]
我的机器人已经正常工作了，但是我想要修改群友的积分。
我成功用dbeaver连上了数据库，但是数据库里一张表也看不见。然后我尝试在部署端用指令访问，也看不见表
个人在部署环境下的尝试如下：
```
sudo su - postgres 
psql
select * from pg_tables where tablename not like 'pg%' and tablename not like 'sql_%';
```

结果
```
 schemaname | tablename | tableowner | tablespace | hasindexes | hasrules | hastriggers | rowsecurity
------------+-----------+------------+------------+------------+----------+-------------+-------------
(0 rows)
```

**Comment by WWWA7** [comment]
可以直接发命令给真寻修改内容

好感度：
exec UPDATE "sign_group_users" SET impression=(好感度) WHERE user_qq=(qq号) AND group_id=(群号)
金币:
exec UPDATE "bag_users" SET gold=(金币) WHERE user_qq=(qq号) AND group_id=(群号)

**Comment by RShock** [comment]
已解决，连错了数据库，应该连zhenxun库
