### ISSUE TITLE
yarn run serve时候 弹出来note....

### ISSUE THREAD

**Issue by NekoInValkyr** [HibiKier/zhenxun_bot#508]
![image](https://user-images.githubusercontent.com/95226187/169655469-51601931-14b4-4d81-b9b9-69c8280d9568.png)

**Comment by Su-Dream** [comment]
> ![image](https://user-images.githubusercontent.com/95226187/169655469-51601931-14b4-4d81-b9b9-69c8280d9568.png)

访问上面local地址，关闭issue

**Comment by WWWA7** [comment]
建议打开浏览器，在地址栏里输入http://localhost:8081/

**Comment by NekoInValkyr** [comment]
> > ![image](https://user-images.githubusercontent.com/95226187/169655469-51601931-14b4-4d81-b9b9-69c8280d9568.png)
> 
> 访问上面local地址，关闭issue

![image](https://user-images.githubusercontent.com/95226187/169655767-2968b982-e6ef-413a-b5d3-2269331b3581.png)
![image](https://user-images.githubusercontent.com/95226187/169655774-592c2b58-7a00-4f97-b1c3-43fbeff4bdf6.png)

**Comment by Su-Dream** [comment]
> > > ![image](https://user-images.githubusercontent.com/95226187/169655469-51601931-14b4-4d81-b9b9-69c8280d9568.png)
> > 
> > 
> > 访问上面local地址，关闭issue
> 
> ![image](https://user-images.githubusercontent.com/95226187/169655767-2968b982-e6ef-413a-b5d3-2269331b3581.png) ![image](https://user-images.githubusercontent.com/95226187/169655774-592c2b58-7a00-4f97-b1c3-43fbeff4bdf6.png)

关闭防火墙，重启真寻

**Comment by NekoInValkyr** [comment]
谢谢大佬们
