### ISSUE TITLE
词云加载报错

### ISSUE THREAD

**Issue by LoliconXX** [HibiKier/zhenxun_bot#509]
![QQ图片20220521222354](https://user-images.githubusercontent.com/35798517/169656161-0bfca761-1dbe-4067-beb7-543a103cadfe.png)
已pip install wordcloud

**Comment by LoliconXX** [comment]
已pip install wordcloud

**Comment by WWWA7** [comment]
接下来 pip install emoji

**Comment by LoliconXX** [comment]
谢谢，可以了
