### ISSUE TITLE
原神资源查询地图显示错误

### ISSUE THREAD

**Issue by meng-luo** [HibiKier/zhenxun_bot#51]
位置偏了好多，都到到地图外了
![1631537868682](https://user-images.githubusercontent.com/79274361/133087894-8e482e96-c76f-4156-ae7f-fcf6949968aa.png)

**Comment by HibiKier** [comment]
删除地图重新更新

**Comment by meng-luo** [comment]
下载错误
![image](https://user-images.githubusercontent.com/79274361/133094369-4f95a942-c0e8-4e5a-9ac9-33af87b377de.png)

**Comment by HibiKier** [comment]
下载超时了
