### ISSUE TITLE
涩图自动撤回没反应

### ISSUE THREAD

**Issue by dishuii** [HibiKier/zhenxun_bot#510]
设置了自动撤回，然而并没有反应，无报错
请问是我的参数问题吗
![Snipaste_2022-05-21_22-23-42](https://user-images.githubusercontent.com/33979662/169656344-d1bd1327-32d1-4193-9bad-03f6873ea7ef.jpg)
![Snipaste_2022-05-21_22-31-45](https://user-images.githubusercontent.com/33979662/169656351-81cc9e25-e6ce-4e4e-b09c-f02d77d55e6e.jpg)

**Comment by HibiKier** [comment]
不要单引号，webui改这些还有点问题

**Comment by dishuii** [comment]
> 不要单引号，webui改这些还有点问题

OK 谢谢
