### ISSUE TITLE
关于poetry修改python版本问题

### ISSUE THREAD

**Issue by Su-Dream** [HibiKier/zhenxun_bot#511]
![image](https://user-images.githubusercontent.com/81561787/169656960-ba502b8d-cd48-4da2-8710-8376e53a05f7.png)
我想要把poetry支配的python版本修改成3.9，但是弹给了我一个错误
![image](https://user-images.githubusercontent.com/81561787/169656994-60b9e793-44e5-45cc-a57c-e9dba423a669.png)

**Comment by HibiKier** [comment]
可以试试先卸载poetry，然后用3.9的pip安装poetry？

**Comment by Su-Dream** [comment]
> 可以试试先卸载poetry，然后用3.9的pip安装poetry？

晚点应该会尝试，因为我现在已经把bot弄坏了QAQ
![image](https://user-images.githubusercontent.com/81561787/169659142-341a34fb-cd7e-45c5-b4d9-7b1cca4b1a6e.png)
