### ISSUE TITLE
buff更新价格失败

### ISSUE THREAD

**Issue by 1411484730** [HibiKier/zhenxun_bot#512]
填写了代理和cookie
执行命令后报错，bot前台无回复
![QQ图片20220521230647](https://user-images.githubusercontent.com/69163070/169657527-6bd0074b-99cd-4419-8e9a-93b99990efee.png)

**Comment by HibiKier** [comment]
你代理怎么填的

**Comment by 1411484730** [comment]
![image](https://user-images.githubusercontent.com/69163070/170827358-43cb9bf6-cc2f-4013-b3f4-4ee3b511ecea.png)
![image](https://user-images.githubusercontent.com/69163070/170827374-3a70f223-24e4-412c-bcdb-c748edec70ab.png)
直接复制buff上的session填了进去

**Comment by 1411484730** [comment]
猪鼻把代理跟cookie填反了，去掉单引号反过来填就正常了
