### ISSUE TITLE
是否能够关闭一些图片本地缓存或者真寻的文件备份来减少服务器硬盘的使用量？

### ISSUE THREAD

**Issue by Saukurs** [HibiKier/zhenxun_bot#513]
部署后因为瑟图被缓存的问题bot没几天就因为数据库炸了启动不起来了(悲

**Comment by 740333480** [comment]
configs目录中的config.yaml文件中278行 DOWNLOAD_SETU 改成false的话应该可以关闭部分色图的本地缓存

**Comment by Saukurs** [comment]
> configs目录中的config.yaml文件中278行 DOWNLOAD_SETU 改成false的话应该可以关闭部分色图的本地缓存

已经看见此行，更改后看一下占用会不会有所改善，谢谢！

**Comment by Saukurs** [comment]
> configs目录中的config.yaml文件中278行 DOWNLOAD_SETU 改成false的话应该可以关闭部分色图的本地缓存

我看了下关了还是会报瑟图缓存的日志条目
![Uploading 捕获.PNG…]()

**Comment by Saukurs** [comment]
最后写了个shell来自动清理真寻文件夹下面的色图缓存，但是不知道还有无其他缓存

**Comment by HibiKier** [comment]
修改后重启或者 重载配置 了吗，看不到图片，重新发一下日志，并且如果要清理某个文件夹缓存的不需要写shell，已经提供方法
```python
from utils.manager import resources_manager

# 将目标文件夹路径列为临时文件文件夹，每天自动清理
resources_manager.add_temp_dir(TEMP_PATH)
```

**Comment by Saukurs** [comment]
> 修改后重启或者 重载配置 了吗，看不到图片，重新发一下日志，并且如果要清理某个文件夹缓存的不需要写shell，已经提供方法
> 
> ```python
> from utils.manager import resources_manager
> 
> # 将目标文件夹路径列为临时文件文件夹，每天自动清理
> resources_manager.add_temp_dir(TEMP_PATH)
> ```

![捕获](https://user-images.githubusercontent.com/105751058/169678609-850a23f7-8842-4585-a6f3-cf09d065cc78.PNG)
已重启BOT
请问上述条目应该写在哪里？
再次感谢

**Comment by HibiKier** [comment]
你可以写在任意地方，只要能被导入，比如插件里等等

**Comment by Saukurs** [comment]
> 你可以写在任意地方，只要能被导入，比如插件里等等

好的感谢
