### ISSUE TITLE
已经使用pg_store导入omega图库并设置比例，但还是无法正常使用omega图库

### ISSUE THREAD

**Issue by sdfsddftd** [HibiKier/zhenxun_bot#514]
已经用如下的指令导入了图库到数据库（使用的用户是postgres）
` pg_restore -d zhenxun /home/zhenxun_bot/xx.sql`
![image](https://user-images.githubusercontent.com/69803371/169660980-140fec76-ad5e-4b99-b269-08866f408775.png)

也已经修改了config
![image](https://user-images.githubusercontent.com/69803371/169661007-34555949-9fab-49ea-a073-d53800990ef5.png)
但是给机器人发送“检测omega图库”无反应，查看后台也没有显示检测到数据库

对postgreSQL和ubuntu不是很熟悉。。。

**Comment by LoliconXX** [comment]
是把sql文件放入bot文件夹根目录，然后给机器人发送“检测omega图库”自动导入

**Comment by sdfsddftd** [comment]
![image](https://user-images.githubusercontent.com/69803371/169677051-1b9bcb38-3e9f-4000-b684-8a24e87b958a.png)
已经放在根目录了。。。但是好像并没有什么用
xx.sql来自 #39

**Comment by HibiKier** [comment]
要不你打开数据库看看你导入成功了没？

**Comment by sdfsddftd** [comment]
![G5S5R@{8U])Y1~}GZ)2@`55.png](https://user-images.githubusercontent.com/69803371/169684729-a6fa59fe-9b17-4540-a7a5-d8b64cbc5d39.png)
我是用pgadmin查看的，表已经导入到zhenxun这个数据库了

**Comment by sdfsddftd** [comment]
> 要不你打开数据库看看你导入成功了没？

已经解决 是因为更新omega图库需要超级用户权限 而我超级用户的qq错填成了bot的qq，现在已经可以正常使用
