### ISSUE TITLE
升级Python3.9后所有之前已有模块无法调用如何解决

### ISSUE THREAD

**Issue by XKaguya** [HibiKier/zhenxun_bot#518]
如题
我随后退回了3.8版本，问题解决了
但是升级3.9或者任意版本的话，如何确保这些模块仍旧可以被调用？
比如60秒看世界的插件，必须要PY3.9 而我是3.8，因为安装时不知道有这个问题

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169678134-388134d7-54f5-4383-87b9-68148fc14d0d.png)
在py3.9的环境再走一遍

**Comment by sdfsddftd** [comment]
> 如题 我随后退回了3.8版本，问题解决了 但是升级3.9或者任意版本的话，如何确保这些模块仍旧可以被调用？ 比如60秒看世界的插件，必须要PY3.9 而我是3.8，因为安装时不知道有这个问题

我也遇到了同样的问题，在py3.8的虚拟环境下一切正常，但是进入了py3.9的虚拟环境后用python bot.py启动bot产生大量重复报错
ModuleNotFoundError: No module named 'cv2'
ModuleNotFoundError: No module named 'pytz'
ModuleNotFoundError: No module named 'ujson'

**Comment by XKaguya** [comment]
按照这个方法试过了，
fallsnow@ubuntu:~/Desktop/zhenxun$ cd /home/zhenxun_bot/
fallsnow@ubuntu:/home/zhenxun_bot$ ls
backup         docs_image  plugins         resources         __version__
basic_plugins  LICENSE     poetry.lock     restart.sh        zhenxun_bot.log
bot.py         log         __pycache__     services
configs        logo.png    pyproject.toml  update_info.json
data           models      README.md       utils
fallsnow@ubuntu:/home/zhenxun_bot$ poetry shell
Spawning shell within /home/fallsnow/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8
. /home/fallsnow/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/bin/activate
fallsnow@ubuntu:/home/zhenxun_bot$ . /home/fallsnow/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/bin/activate
(zhenxun-bot-UH4sDRIh-py3.8) fallsnow@ubuntu:/home/zhenxun_bot$ python3.9 bot.py
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 1, in <module>
    import nonebot
ModuleNotFoundError: No module named 'nonebot'
(zhenxun-bot-UH4sDRIh-py3.8) fallsnow@ubuntu:/home/zhenxun_bot$ 

还是提示没有nonebot模块，我试过自行安装，提示是已经有了
我也试过一键部署脚本的开启，一样报这个错

**Comment by XKaguya** [comment]
> > 如题 我随后退回了3.8版本，问题解决了 但是升级3.9或者任意版本的话，如何确保这些模块仍旧可以被调用？ 比如60秒看世界的插件，必须要PY3.9 而我是3.8，因为安装时不知道有这个问题
> 
> 我也遇到了同样的问题，在py3.8的虚拟环境下一切正常，但是进入了py3.9的虚拟环境后用python bot.py启动bot产生大量重复报错 ModuleNotFoundError: No module named 'cv2' ModuleNotFoundError: No module named 'pytz' ModuleNotFoundError: No module named 'ujson'

对，我也是这样的 3.8的环境一切正常，3.9就不正常。
据说是版本升级换了地方，3.9认为没安装但是pip安装的目录认为你安装了

**Comment by XKaguya** [comment]
解决了，从重新安装虚拟机开始到结束。
我自行参考了https://www.jb51.net/article/221437.htm
有兴趣的可以根据这篇文章尝试一下，但是有个问题就是只能在文件夹内打开终端，除非切换Python版本到3.8
