### ISSUE TITLE
（已解决）pix指令IndexError: list index out of range

### ISSUE THREAD

**Issue by melulu578** [HibiKier/zhenxun_bot#519]
![image](https://user-images.githubusercontent.com/105999492/169674894-ed389b7a-8c1d-48bf-ba26-fc7735b7a51d.png)

![image](https://user-images.githubusercontent.com/105999492/169674810-04325b04-7450-42b4-be00-155e9f8a8d8f.png)
omega图库已经安装 pix图库里面也有图

**Comment by HibiKier** [comment]
你配置文件pix比例那一块怎么改的？

**Comment by melulu578** [comment]
（已解决）根据大大提醒修改了config.yaml 参考了原备份 确实是用可视化修改时造成的格式问题
