### ISSUE TITLE
抽卡模块的一个小问题

### ISSUE THREAD

**Issue by sakuno214** [HibiKier/zhenxun_bot#52]
抽pcr卡池怎么国服台服混在一起的，，，而且游戏里你是抽不到初始御三家的，抽卡结果输出里还能抽到，明显不合理

建议加一个pcr卡池重载，顺便，能不能加个pcr日服卡池啊呜呜呜

**Comment by HibiKier** [comment]
PCR_TAI = True  # pcr是否开启台服卡池，config里有这个配置的，pcr数据主要是爬取的bwiki，bwiki中没有角色限定的说明，目前pcr抽卡只区分了节日限定，关于日服卡池，找得到wiki什么之类的肯定加了

**Comment by yusana213214** [comment]
> PCR_TAI = True # pcr是否开启台服卡池，config里有这个配置的，pcr数据主要是爬取的bwiki，bwiki中没有角色限定的说明，目前pcr抽卡只区分了节日限定，关于日服卡池，找得到wiki什么之类的肯定加了

https://redive.estertion.win/

**Comment by HibiKier** [comment]
okk

**Comment by yusana213214** [comment]
> okk

里面还有音游谢谢奇怪的东西，有空也可以加上（滑稽）
