### ISSUE TITLE
关于群权限的几个疑问

### ISSUE THREAD

**Issue by railannad** [HibiKier/zhenxun_bot#520]
![image](https://user-images.githubusercontent.com/36919867/169676333-a5648a4f-9a93-47ef-bfe8-cc1a43bc0678.png)
![image](https://user-images.githubusercontent.com/36919867/169676347-bb056d8f-2cf6-483b-a62b-5bbfc255b05c.png)
![image](https://user-images.githubusercontent.com/36919867/169676368-3e8c8585-0c4b-4e42-a4d9-03ba46366aaa.png)
![image](https://user-images.githubusercontent.com/36919867/169676437-db2c2290-ce65-49ba-abc3-36230fd49f8c.png)
![image](https://user-images.githubusercontent.com/36919867/169676441-d97a2136-528d-4d60-9fd9-aacaa25e402e.png)

1.  为什么群权限会反复横跳？  从5改到9，查询之后又变成4。 再次查询之后又变成9
2.  为什么web ui里查询到的群权限和命令查询到的结果不一致？
3. 在`data/configs/plugin2settings.yaml`里修改`send_setu`的`level`值为5，期望的情况是权限5即可发色图，实际上还是不能使用色图。要如何操作？
4.  联动问题1，修改权限为9，实际上会在5和9之间反复横跳， 导致色图功能有时候能用，有时候提示权限不足。

简单查了一下，话说psql也是个关系型数据库吧，为什么源码里看不到sql语句（

**Comment by WWWA7** [comment]
色图是可以在群聊发的，色图r的话可以私聊看不能在群聊里看，想在群里发色图r的话需要去插件里改代码，但是因为色图r是r18的露点的，所以为了真寻的安全和群的安全着想，不建议开启

**Comment by railannad** [comment]
> 色图是可以在群聊发的，色图r的话可以私聊看不能在群聊里看，想在群里发色图r的话需要去插件里改代码，但是因为色图r是r18的露点的，所以为了真寻的安全和群的安全着想，不建议开启

大佬看一下我描述的四个问题，根本没有提到R18。   主要是对群权限反复横跳很懵逼。
因为默认的色图权限要9，我修改配置文件之后期望它只需要5就可以发，然而实际并没有达到我的期望。

**Comment by HibiKier** [comment]
1.并没有遇到群权限反复横跳的问题
2.webui处于测试阶段，有bug可以在对应仓库发送issues
3.你修改后重启过了吗，或者 重载配置 过了吗，我这里测试并无问题
4.以上
5.因为数据库框架使用的ORM框架

**Comment by railannad** [comment]
> 1.并没有遇到群权限反复横跳的问题 2.webui处于测试阶段，有bug可以在对应仓库发送issues 3.你修改后重启过了吗，或者 重载配置 过了吗，我这里测试并无问题 4.以上 5.因为数据库框架使用的ORM框架

emmm，打扰大佬了。今天才发现我之前测试环境并没有登出bot，也就是说我这几天一直都是两台vps在互相顶号。这样的话配置文件会反复横跳，24点的晚安/开箱重置提醒也会重复两次（#300）也就说得通了。
关掉测试环境之后发现上述问题已解决，感谢大佬。
