### ISSUE TITLE
明日方舟素材查询和干员材料插件可以有吗

### ISSUE THREAD

**Issue by LSGLSH** [HibiKier/zhenxun_bot#521]
发现机器人只有原神的查询是齐全的，平时玩明日方舟时间多一些，反而原神的插件作用不是很大

**Comment by NumberSir** [comment]
> 发现机器人只有原神的查询是齐全的，平时玩明日方舟时间多一些，反而原神的插件作用不是很大

能具体一点吗，比如查素材是像企鹅物流那样列出关卡掉落率、期望理智之类的吗？干员材料是像prts那样列出精英化 / 技能专精 / 解锁模组之类的吗？

**Comment by LSGLSH** [comment]
差不多很大佬你说的一样，这队友当前比较流行的明日方舟游戏的玩家，这些功能非常重要和实用，玩家不必要详细去翻角色看材料，就可以知道在哪打和缺什么。

**Comment by LSGLSH** [comment]
> 

差不多很大佬你说的一样，这队友当前比较流行的明日方舟游戏的玩家，这些功能非常重要和实用，玩家不必要详细去翻角色看材料，就可以知道在哪打和缺什么。

**Comment by LSGLSH** [comment]
> 差不多很大佬你说的一样，这队友当前比较流行的明日方舟游戏的玩家，这些功能非常重要和实用，玩家不必要详细去翻角色看材料，就可以知道在哪打和缺什么。

**Comment by LSGLSH** [comment]
> > 发现机器人只有原神的查询是齐全的，平时玩明日方舟时间多一些，反而原神的插件作用不是很大
> 
> 能具体一点吗，比如查素材是像企鹅物流那样列出关卡掉落率、期望理智之类的吗？干员材料是像prts那样列出精英化 / 技能专精 / 解锁模组之类的吗？

差不多很大佬你说的一样，这队友当前比较流行的明日方舟游戏的玩家，这些功能非常重要和实用，玩家不必要详细去翻角色看材料，就可以知道在哪打和缺什么。

**Comment by NumberSir** [comment]
> > > 发现机器人只有原神的查询是齐全的，平时玩明日方舟时间多一些，反而原神的插件作用不是很大
> > 
> > 
> > 能具体一点吗，比如查素材是像企鹅物流那样列出关卡掉落率、期望理智之类的吗？干员材料是像prts那样列出精英化 / 技能专精 / 解锁模组之类的吗？
> 
> 差不多很大佬你说的一样，这队友当前比较流行的明日方舟游戏的玩家，这些功能非常重要和实用，玩家不必要详细去翻角色看材料，就可以知道在哪打和缺什么。

[zhenxun_arktools](https://github.com/NumberSir/zhenxun_arktools)
