### ISSUE TITLE
唔，真寻的语音包？

### ISSUE THREAD

**Issue by TDuckQWQ** [HibiKier/zhenxun_bot#522]
![image](https://user-images.githubusercontent.com/62102282/169678776-ec04ee96-7d19-4bd3-8e9f-0c95a82f3308.png)
这些是怎么用的...qwq

**Comment by Umon7275** [comment]
在群里@她 + 骂我，或者直接私聊她“骂我”

**Comment by TDuckQWQ** [comment]
> 

![image](https://user-images.githubusercontent.com/62102282/169679050-3be6f781-f8c5-4aa9-98be-c9c086af5906.png)
“骂我”没有回应，好像没装ffmpeg，怎么装的说

**Comment by Umon7275** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/62102282/169679050-3be6f781-f8c5-4aa9-98be-c9c086af5906.png) “骂我”没有回应，好像没装ffmpeg，怎么装的说

查看安装文档，最下面安装ffmpeg，
[https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_gocq.html](url)

**Comment by TDuckQWQ** [comment]
> > > 
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/62102282/169679050-3be6f781-f8c5-4aa9-98be-c9c086af5906.png)“骂我”没有回应，好像没装ffmpeg，怎么装的说
> 
> 查看安装文档，最下面安装ffmpeg， https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_gocq.html

嗯嗯

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/169680904-7da217cd-4d7b-4e2c-98ac-015749825f04.png)
嗯？这是为什么

**Comment by Umon7275** [comment]
> ![image](https://user-images.githubusercontent.com/62102282/169680904-7da217cd-4d7b-4e2c-98ac-015749825f04.png) 嗯？这是为什么

不知道你的ffmpeg安装成功没有。
查看
https://docs.go-cqhttp.org/guide/quick_start.html#%E5%AE%89%E8%A3%85-ffmpeg
进行安装

**Comment by TDuckQWQ** [comment]
> > ![image](https://user-images.githubusercontent.com/62102282/169680904-7da217cd-4d7b-4e2c-98ac-015749825f04.png) 嗯？这是为什么
> 
> 不知道你的ffmpeg安装成功没有。 查看 https://docs.go-cqhttp.org/guide/quick_start.html#%E5%AE%89%E8%A3%85-ffmpeg 进行安装

![image](https://user-images.githubusercontent.com/62102282/169681594-bab62b3a-3bb3-44df-807c-ec4e426485fa.png)
呐

**Comment by Umon7275** [comment]
看这个
https://github.com/Mrs4s/go-cqhttp/issues/973
试试重启电脑。

**Comment by WWWA7** [comment]
安装好了记得重启插件或者重启真寻

**Comment by WWWA7** [comment]
是不是因为没重启，安装好了记得重启一下真寻或者重加载插件

**Comment by h265642327** [comment]
麻烦再看看报错的日记，截全一点

**Comment by TDuckQWQ** [comment]
唔唔，我再看看吧…

**Comment by caizhuoyue77** [comment]
> https://docs.go-cqhttp.org/guide/quick_start.html#%E5%AE%89%E8%A3%85-ffmpeg

请问你成功了吗？我还是一直报错
