### ISSUE TITLE
原神图片错误..已删除，等待下次更新     word_hanlde 插件报错

### ISSUE THREAD

**Issue by william-wwh** [HibiKier/zhenxun_bot#523]
启动时报错
![1](https://user-images.githubusercontent.com/60587573/169679415-4312cf8a-8e48-4855-aa06-5a44468a3815.png)
word_hanlde报错信息
![原神](https://user-images.githubusercontent.com/60587573/169679424-63e6afd6-a2cc-4a54-91fc-ec20954552e4.png)
原神图片错误
可能是代理设置错误? 色图能下载所以代理应该是可用的
![image](https://user-images.githubusercontent.com/60587573/169679496-86fa4f8b-5933-4a72-ba37-11d17356606b.png)

**Comment by william-wwh** [comment]
已经更换端口尝试 原神图片还是下载失败
![image](https://user-images.githubusercontent.com/60587573/169680126-1115a0b1-0e58-432d-a004-7246fb9d3a28.png)


> 启动提示错误word_hanlde 报错信息 原神图片错误 可能是代理设置错误？色图能下载所以代理应该是可用的 ![1](https://user-images.githubusercontent.com/60587573/169679415-4312cf8a-8e48-4855-aa06-5a44468a3815.png) ![原神](https://user-images.githubusercontent.com/60587573/169679424-63e6afd6-a2cc-4a54-91fc-ec20954552e4.png) ![图片](https://user-images.githubusercontent.com/60587573/169679496-86fa4f8b-5933-4a72-ba37-11d17356606b.png)

**Comment by HibiKier** [comment]
92e60ba141313f5b28f89afdfe813b29f13468c1

**Comment by HibiKier** [comment]
把代码更新一下

**Comment by william-wwh** [comment]
谢谢大佬
