### ISSUE TITLE
自行添加了bison插件之后bot运行报错

### ISSUE THREAD

**Issue by 534019023** [HibiKier/zhenxun_bot#524]
想为群友加点微博订阅之类的功能，于是在nonebot商店找到了这个叫bison的插件，按真寻作者文档里增添新插件的步骤新建了个新的文件夹放这个插件，并且在bot.py里面也写上了load plugin，但是运行的时候就报错了， 查询issue时参考过 #139 ，我这确实也提示了插件控制未加载，但是插件是否加载成功似乎不影响bot启动，而我的bot却会报错
这是报错代码：
![image](https://user-images.githubusercontent.com/95991937/169682399-f6c64569-fc2c-404b-ad1c-938a8cf92465.png)
还有根据#139 插件需要更改priority的值，但是这个插件的_init_文件里没有priority相关内容，对照其他插件的文件似乎是要自己添加priority的语句吗？如果要自己添加的话是要怎么添加呢，是否还要import些什么
这是插件的_init_文件
![image](https://user-images.githubusercontent.com/95991937/169682349-1b6a59eb-5d9a-4e91-ad03-c440fda9db47.png)
本人不太擅长写代码，希望有人可以提示我如何解决这个问题，谢谢

**Comment by MingxuanGame** [comment]
bison 使用了 [htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender)，此工具在 Windows 平台会有一定情况下报错

参考 https://github.com/kexue-z/nonebot-plugin-htmlrender/issues/15
