### ISSUE TITLE
原神图片错误..已删除，等待下次更新...

### ISSUE THREAD

**Issue by LoliconXX** [HibiKier/zhenxun_bot#525]
![QQ截图20220522160031](https://user-images.githubusercontent.com/35798517/169685034-78a32d79-2572-4720-8621-727a6cb2e2a6.png)
![QQ截图20220522160524](https://user-images.githubusercontent.com/35798517/169685092-655ce6a6-d8e3-41aa-98a1-337f59126c0f.png)
文件夹下也没有下载的文件

**Comment by HibiKier** [comment]
已修 d2fe95cc055086780b1ab7936b8f276ad50160f3
