### ISSUE TITLE
插件导入无法执行命令

### ISSUE THREAD

**Issue by zhong946555** [HibiKier/zhenxun_bot#526]
想增加这个头像表情包功能
https://github.com/noneplugin/nonebot-plugin-petpet
然后按照nonebot的文档导入了插件和资源，真寻也成功import运行了，但是无法执行命令功能
![image](https://user-images.githubusercontent.com/61000018/169685182-658ffcd2-10bd-459e-b0f9-a14f341c3f01.png)

**Comment by HibiKier** [comment]
https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot
