### ISSUE TITLE
已经更新最新版本，bilibli_sub、word_clouds启动失败，寻求大佬帮助。py代码全靠百度

### ISSUE THREAD

**Issue by nertcy** [HibiKier/zhenxun_bot#527]
已经更新最新版本，bilibli_sub、word_clouds启动失败不知道是不是要在哪里进行配置，原神黄历也是加载错误
系统环境腾讯云、win serverR2 Py3.8.10
![image](https://user-images.githubusercontent.com/94539226/169687683-15d60d77-b5da-4a93-93bd-7f6aad840aa9.png)
![image](https://user-images.githubusercontent.com/94539226/169687693-3451c069-c289-4147-8e29-c052709e3e48.png)
![image](https://user-images.githubusercontent.com/94539226/169687718-f5e6777a-e4b2-4f93-a87f-61c1b90d6365.png)
![image](https://user-images.githubusercontent.com/94539226/169687738-25051f9a-1899-4c12-9a0d-4ef187768f4e.png)
![image](https://user-images.githubusercontent.com/94539226/169687757-c719de45-7bf5-4b99-9170-8805263bc16d.png)

**Comment by WWWA7** [comment]
前两张图片，依赖没装全，看到你图片最后的no module了吗，说明缺的就是这些依赖
win环境下和playwright有关的好像还不能用，[看这里](https://v2.nonebot.dev/docs/tutorial/choose-driver#fastapi%E9%BB%98%E8%AE%A4)

**Comment by nertcy** [comment]
> 前两张图片，依赖没装全，看到你图片最后的no module了吗，说明缺的就是这些依赖 win环境下和playwright有关的好像还不能用，[看这里](https://v2.nonebot.dev/docs/tutorial/choose-driver#fastapi%E9%BB%98%E8%AE%A4)

因为是下载main最新版本进行覆盖的，仍然是用这几个依赖吗？
![image](https://user-images.githubusercontent.com/94539226/169689116-675d12d1-5f83-4a6c-b094-167e5e4553da.png)

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169689284-135d0b48-867c-4ded-8dd7-47cec143faff.png)
用最新的这俩

**Comment by nertcy** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/169689284-135d0b48-867c-4ded-8dd7-47cec143faff.png) 用最新的这俩

已经放在真寻bot目录下了，我改如何运行呢是pip3 install -r oietrt.lock和pip3 install -r pyproject.toml这样吗？

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/169690766-61226055-f358-40e1-8746-962ddd736637.png)
