### ISSUE TITLE
求助大佬识图问题

### ISSUE THREAD

**Issue by edc0127** [HibiKier/zhenxun_bot#528]
识图倒腾半天还是不行。。。现在是这样的!![image](https://user-images.githubusercontent.com/105971738/169689181-26733237-8b5f-4a04-adde-1fc7046d4903.png)[image](https://user-images.githubusercontent.com/105971738/169689174-2dde3283-9d59-4e1f-a7e2-6592f06bddbb.png)

**Comment by WWWA7** [comment]
可能是API_KEY配置错误，看configs里的config.yaml里的API_KEY配置是否正确

**Comment by HibiKier** [comment]
gocq有发送东西吗
