### ISSUE TITLE
黑白草图插件无法使用

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#529]
![黑白草图](https://user-images.githubusercontent.com/105090141/169689785-eaf86d0c-9e43-44b9-96a9-b741a786c62c.png)
![黑白草图2](https://user-images.githubusercontent.com/105090141/169689789-fef0e9e2-5937-4c0c-b0ff-20484bd94d73.png)
如图，bot无反应

**Comment by HibiKier** [comment]
因为你没风控了
