### ISSUE TITLE
更新群信息指令报错

### ISSUE THREAD

**Issue by LoliconXX** [HibiKier/zhenxun_bot#530]
![QQ截图20220522183323](https://user-images.githubusercontent.com/35798517/169691118-3c97850e-26bf-49e7-9f58-037267b9bf31.png)
![QQ截图20220522183334](https://user-images.githubusercontent.com/35798517/169691123-67d84ac4-80b6-4dde-9eb4-0647e8df275f.png)

**Comment by HibiKier** [comment]
已修
