### ISSUE TITLE
无法使用第三方插件

### ISSUE THREAD

**Issue by iven13465** [HibiKier/zhenxun_bot#532]
![image](https://user-images.githubusercontent.com/95957360/169695473-5bb9a67e-b171-4304-9ca8-50edb062fb8e.png)
能成功导入，但输入相关指令是没有反应
![image](https://user-images.githubusercontent.com/95957360/169695503-93e6347f-dbd3-45fb-8ff7-3d036b73f8fc.png)

**Comment by HibiKier** [comment]
你这命令都没触发到petpet，指令正确的吗？
