### ISSUE TITLE
我有一个疑问

### ISSUE THREAD

**Issue by yoshino2333** [HibiKier/zhenxun_bot#533]
我想改一下真寻回复的文本内容，请问在哪个文件修改啊，我找不到，大佬救救

**Comment by yoshino2333** [comment]
![image](https://user-images.githubusercontent.com/105909793/169697417-bf5c591e-f839-4876-8be4-e917214f4824.png)
比如改这个文本的内容，我该去哪改

**Comment by HibiKier** [comment]
plugins/nbnhhsh

**Comment by yoshino2333** [comment]
> plugins/nbnhhsh

![image](https://user-images.githubusercontent.com/105909793/169700034-6643acf2-a220-485c-8412-a5a163a0acc8.png)
谢谢大佬，那这种没配置文件的自动回复呢（也许是我没找到？）

**Comment by Sakuracio** [comment]
@yoshino2333 这是来自API的AI回复 没得改 你可以关了
