### ISSUE TITLE
关于词云新功能的报错

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#534]
关于运行bot.py后的报错，感觉跟大佬新添的词云功能有关，我以emoji功能开始尝试pip install emoji，显示安装成功，但是再运行bot仍然显示一下报错，感谢大佬捞捞QwQ
![1](https://user-images.githubusercontent.com/50237543/169696200-65cb6a68-b7bc-4ec2-8b8f-ccbd8b01a438.png)
![2](https://user-images.githubusercontent.com/50237543/169696203-1a5edd05-188d-478c-86b3-3ffd69346456.png)
![3](https://user-images.githubusercontent.com/50237543/169696214-02ad869f-a854-482e-9f5b-fde94b2db6d9.png)
![image](https://user-images.githubusercontent.com/50237543/169696215-4a910b97-38db-4ba7-adea-6f3c1c7731b2.png)

**Comment by HibiKier** [comment]
更新代码，然后Poetry install

**Comment by wlz-remake** [comment]
> Poetry install

请问是在poetry shell后pip3 install [相应模块]吗，我更新代码后直接pip3 install [相应模块]再poetry shell后python bot.py仍然报相同错误

**Comment by HibiKier** [comment]
在poetry shell后pip3 install [相应模块] 也可以

**Comment by dick0841** [comment]
QwQ请问更新代码是pip install 相应模块吗
![image](https://user-images.githubusercontent.com/50237543/169701459-96ef1703-d566-456c-8e55-529c51c42f0b.png)
好像找不到相应模块除了emoji

**Comment by wlz-remake** [comment]
> QwQ请问更新代码是pip install 相应模块吗 ![image](https://user-images.githubusercontent.com/50237543/169701459-96ef1703-d566-456c-8e55-529c51c42f0b.png) 好像找不到相应模块除了emoji

应该是的，不过我一直用的是powershell（管理员），其他的没试过，先poetry shell再pip3 install [相应模块]

**Comment by dick0841** [comment]
QwQ先poetry shell再pip3 install 还是一样找不到啊
![image](https://user-images.githubusercontent.com/50237543/169701707-de796584-6518-4d48-8b43-a586a1092c43.png)
我cd到插件所在文件夹pip install 插件也是不行
![image](https://user-images.githubusercontent.com/50237543/169701770-02976117-206a-4251-ba0a-5ac71d012442.png)
，非常感谢大佬帮助

**Comment by chara1051** [comment]
怎么更新吖，我也是缺失“emoji'

**Comment by dick0841** [comment]
我也还在看

**Comment by Excalibur5100** [comment]
我之前也报错，poetry shell下pip3 install emoji和pip3 install wordcloud再重启bot就加载词云成功了

**Comment by dick0841** [comment]
我按你的方法pip install wordcloud了一下，结果报错炸了
![image](https://user-images.githubusercontent.com/50237543/169932015-b9d8982a-211e-4499-bf71-dce24912bea7.png)
![image](https://user-images.githubusercontent.com/50237543/169932080-9b29635e-0765-48ca-a93e-941e4348f06d.png)
QwQ

**Comment by Excalibur5100** [comment]
> 我按你的方法pip install wordcloud了一下，结果报错炸了 ![image](https://user-images.githubusercontent.com/50237543/169932015-b9d8982a-211e-4499-bf71-dce24912bea7.png) ![image](https://user-images.githubusercontent.com/50237543/169932080-9b29635e-0765-48ca-a93e-941e4348f06d.png) QwQ

emm，我是centos7系统，poetry shell虚拟环境下cd到真寻bot目录下执行的，你这个是windows吧，我不太清楚
![image](https://user-images.githubusercontent.com/105792144/169932403-943c582e-6b20-4be2-bf88-0d39f5342cc8.png)

**Comment by dick0841** [comment]
QwQ好的谢谢，我按报错正在下载VS了
