### ISSUE TITLE
真寻自动获取版本失败

### ISSUE THREAD

**Issue by nertcy** [HibiKier/zhenxun_bot#536]
呼叫检查更新说自动获取版本失败
![image](https://user-images.githubusercontent.com/94539226/169697340-28f64a23-270b-40ce-9c7f-ad530c143e17.png)
![image](https://user-images.githubusercontent.com/94539226/169697367-6dc1f311-5cc9-4deb-83c0-0a3fdc5c6297.png)
今天已经在main分支手动更新了

**Comment by HibiKier** [comment]
网络问题

**Comment by nertcy** [comment]
> 网络问题

![image](https://user-images.githubusercontent.com/94539226/169699319-3ac746f9-ab03-4c26-ba71-f2635cc12dcf.png)
下载好了，死在安装了无语

**Comment by HibiKier** [comment]
你权限问题

**Comment by nertcy** [comment]
> 你权限问题

这个是真寻的权限问题（我在config没看见更新设置了权限的呀）还是这个win的权限问题了，

**Comment by HibiKier** [comment]
win的

**Comment by nertcy** [comment]
> win的

修改权限后更新成功，但是很多插件炸了，poetry install依赖也对不上，人傻了

**Comment by Lightning627** [comment]
![image](https://user-images.githubusercontent.com/23275257/169767969-6e0106d0-06ce-4b03-83ad-f66b2fe06807.png)
那我发送指令直接这样是怎么回事

**Comment by HibiKier** [comment]
> ![image](https://user-images.githubusercontent.com/23275257/169767969-6e0106d0-06ce-4b03-83ad-f66b2fe06807.png) 那我发送指令直接这样是怎么回事

没有图灵key不要填
