### ISSUE TITLE
执行bot.py报错

### ISSUE THREAD

**Issue by sola614** [HibiKier/zhenxun_bot#54]
![3V5OCL2W)GZRUUXLXH8@MND](https://user-images.githubusercontent.com/36149249/135308797-ab4f1de1-e579-404b-804a-7d2de33e4328.png)

PS：机器部署在国内，python版本3.9.2，系统Centos8，把碧蓝航线抽卡选项设为False后可以执行

**Comment by sola614** [comment]
还有`coser`这个命令也报错`发生了预料之外的错误..请稍后再试或联系管理员修复...`了，看信息是被`api520.ltd`拒绝访问了，我网页用代理访问也会报`禁止访问 Error 403`
![6{NUUQ`P7L8G__9WB{}3Z8C](https://user-images.githubusercontent.com/36149249/135371853-ebba30fa-fe92-4315-a9f2-af0e8410b8b5.png)

**Comment by sola614** [comment]
在一个群发过一次节日红包，再发的时候会报错，重启之后就可以正常发出，也就是说发第二次的时候会报错
![{QRZ0P1J7D(_8TN6DBIUQ K](https://user-images.githubusercontent.com/36149249/135444197-803cc232-3756-497c-89c3-6d2d6fb4cf66.png)

**Comment by HibiKier** [comment]
嗯，下个版本已经全部修复了
