### ISSUE TITLE
最新版本安装依赖报错

### ISSUE THREAD

**Issue by nertcy** [HibiKier/zhenxun_bot#542]
![image](https://user-images.githubusercontent.com/94539226/169707295-80f7e85b-1995-4d4c-83b4-23ed046b1f95.png)
winserver  py3.9.10

**Comment by housiyang-ufo** [comment]
用py3.8.x的版本吧，就没有这个问题了

**Comment by MingxuanGame** [comment]
可以选择使用 python 3.8，已经进行了预构建

如果选择使用 python 3.9，需要前往 log 中的地址安装 vs 生成工具
