### ISSUE TITLE
关于WEBUI安装的问题

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#543]
请问nodejs要放在bot根目录下吗，我放在不同的地方nodejs就会出现这个
![image](https://user-images.githubusercontent.com/50237543/169707521-e650d4a4-7ae3-4ccb-8a04-d750b1f4cb5f.png)
![image](https://user-images.githubusercontent.com/50237543/169707527-44158118-0a48-49ca-9d99-f18ee940c194.png)
结果是这个界面，没有别人搞出来会有一个"真寻的后台"界面啊QAQ
（有设置账号密码了

**Comment by jk6589jk** [comment]
要在下载下来的web-ui文件夹里使用yarn run serve

**Comment by dick0841** [comment]
登进去了，非常感谢QwQ
