### ISSUE TITLE
关于色图问题

### ISSUE THREAD

**Issue by eachbol2333** [HibiKier/zhenxun_bot#544]
求大佬告知怎么改send_setu文件才能在群里发r18，几个人的群，问题不大，谢谢各位大佬

**Comment by Fengshou-Xu** [comment]
你需要修改 `*bot所在路径*\plugin\send_setu\send_setu\` 下的 '__init__.py' 文件的 152 ~ 154行
将原有部分注释或者删除 然后复制粘贴149 ~ 150 行就行 记得调整num的值 默认是10 也就是连着发10张
例如
![image](https://user-images.githubusercontent.com/90647051/169709989-6363f710-2d15-436b-91de-74e882987e75.png)

**Comment by eachbol2333** [comment]
我靠，我刚刚就是在这里疯狂改没改对，妈的原来那么简单，谢谢带佬
