### ISSUE TITLE
原神查询相关功能出错

### ISSUE THREAD

**Issue by chara1051** [HibiKier/zhenxun_bot#549]
输入“今日素材”指令后，后台没有反应真寻没有任何回复,也没有报错，于是我反复尝试，在第四次发出指令后，发出以下报错，QQ中真寻没有任何回复
![捕获](https://user-images.githubusercontent.com/105768555/169739303-374e0cbf-5da0-4dd6-a771-24df31aa0e50.PNG)
![捕获](https://user-images.githubusercontent.com/105768555/169739319-9fad88f7-89cc-41df-aa05-cf99154aa8f6.PNG)
后来我又试了几次，发现黄历功能也有类似情况，没有成功回复过，但有时会发出报错信息，有时仅仅这样没有下文
![捕获](https://user-images.githubusercontent.com/105768555/169740442-1d6057a1-6e95-4db2-aa10-840de58f7bdd.PNG)不知道为什么
查材料地点正常但是会一直发出已下警告
![Uploading 捕获.PNG…]()

**Comment by chara1051** [comment]
警告是这样
![捕获](https://user-images.githubusercontent.com/105768555/169740502-5e89f1c3-4f14-4cc0-b044-99c1dd45e987.PNG)
的

**Comment by chara1051** [comment]
警告是这样
![捕获](https://user-images.githubusercontent.com/105768555/169740582-793c8b0c-b0c7-4d2b-8d0a-b4f55a26e5d4.PNG)
的

**Comment by chara1051** [comment]
![捕获(8)](https://user-images.githubusercontent.com/105768555/169740713-97407e41-8082-4f46-a897-ac1efe32b05e.PNG)发错了，警告是这个

**Comment by HibiKier** [comment]
这个问题需要去nonebot群问
