### ISSUE TITLE
真寻早晚安无法发送，提示被禁言

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#554]
![禁言1](https://user-images.githubusercontent.com/105090141/169753329-9d1d3f3c-de0f-4e5b-812c-64e14e0ecd55.png)
![禁言2](https://user-images.githubusercontent.com/105090141/169753333-8c6fe85e-42d2-42ab-a9af-911a174fa455.png)
但我向所有群聊发送的广播都能正常发送，登上真寻的QQ也没有哪个群被禁言了
![广播](https://user-images.githubusercontent.com/105090141/169753476-18b1d59a-6ff2-419f-bfb5-4050208b224d.png)
还需要哪里的截图吗？

**Comment by wlz-remake** [comment]
![启动1](https://user-images.githubusercontent.com/105090141/169754473-1083d411-43f7-40ff-b0e8-39aca4819cb4.png)
![启动2](https://user-images.githubusercontent.com/105090141/169754482-eda31493-e1d7-45f7-aed7-4642c3db5418.png)
![启动3](https://user-images.githubusercontent.com/105090141/169754491-a60dfcea-b893-4350-8078-928ab08a7709.png)

**Comment by GKCommander** [comment]
可能是go-cqhttp那边的问题？去看看那边呗

**Comment by HibiKier** [comment]
风控或禁言，反正是无法发送消息了

**Comment by wlz-remake** [comment]
go-cqhttp那边：[2022-05-23 17:12:22] [WARNING]: 群消息发送失败: 账号可能被风控.
