### ISSUE TITLE
真寻检查更新时当前版本号错误

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#555]
![版本号](https://user-images.githubusercontent.com/105090141/169755429-c7ff9511-055f-44c5-99a5-3bf02c9f0ce7.png)
![检查更新2](https://user-images.githubusercontent.com/105090141/169755439-9b5446ab-ca99-4a15-88e0-baf1b57e1c1d.png)
今早已经手动更新至v0.1.5.5，但检查更新时仍显示版本号为v0.1.5.4

**Comment by Misakami** [comment]
因为version文件里还是1.5.4 但是tag打了俩打到1.5.5了

**Comment by HibiKier** [comment]
小问题，等下次发版就行了
