### ISSUE TITLE
订阅b站动态错误

### ISSUE THREAD

**Issue by Misakami** [HibiKier/zhenxun_bot#556]
![image](https://user-images.githubusercontent.com/22981008/169757952-8e3d80cc-cc96-4a73-85de-00ad56aef7b8.png)
上海的云服务器，按理说不该出现超时

**Comment by Misakami** [comment]
代码手动用git pull了最新代码

**Comment by GKCommander** [comment]
我看过源码了，是没有实现动态有置顶时去置顶的功能，我改了一晚上，勉强修复了（就是方法比较蠢）
去/plugins/bilibili_sub/data_source.py中进行修改
`
329                 # 删除置顶
330                 await page.evaluate(
331                     """
332                     xs = document.getElementsByClassName('bili-dyn-item__tag');
333                     for (x of xs) {
334                       x.parentNode.remove();
335                     }
336                 """
337                 )
338                 await page.locator("//div[@class='bili-dyn-list__item'][1]/../*[2]").screenshot(
339                     path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg",
340                 )
341                 logger.info(f"默认有置顶")
342                 await page.locator("//div[@class='bili-dyn-list__item'][1]").screenshot(
343                     path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg",
344                 )
345                 logger.info(f"无置顶")
346             except Exception as e:
347                 logger.error(f"B站订阅：获取用户动态 发送错误 {type(e)}：{e}")
`

**Comment by Misakami** [comment]
> 我看过源码了，是没有实现动态有置顶时去置顶的功能，我改了一晚上，勉强修复了（就是方法比较蠢） 去/plugins/bilibili_sub/data_source.py中进行修改 `# 删除置顶 await page.evaluate( """ xs = document.getElementsByClassName('bili-dyn-item__tag'); for (x of xs) { x.parentNode.remove(); } """ ) await page.locator("//div[@class='bili-dyn-list__item'][1]/../*[2]").screenshot( path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg", ) logger.info(f"默认有置顶") await page.locator("//div[@class='bili-dyn-list__item'][1]").screenshot( path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg", ) logger.info(f"无置顶") except Exception as e: logger.error(f"B站订阅：获取用户动态 发送错误 {type(e)}：{e}")`

我换成你这个代码还是提示超时。难道真的是我网络问题？

**Comment by GKCommander** [comment]
> > 我看过源码了，是没有实现动态有置顶时去置顶的功能，我改了一晚上，勉强修复了（就是方法比较蠢） 去/plugins/bilibili_sub/data_source.py中进行修改 `# 删除置顶 await page.evaluate( """ xs = document.getElementsByClassName('bili-dyn-item__tag'); for (x of xs) { x.parentNode.remove(); } """ ) await page.locator("//div[@class='bili-dyn-list__item'][1]/../*[2]").screenshot( path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg", ) logger.info(f"默认有置顶") await page.locator("//div[@class='bili-dyn-list__item'][1]").screenshot( path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg", ) logger.info(f"无置顶") except Exception as e: logger.error(f"B站订阅：获取用户动态 发送错误 {type(e)}：{e}")`
> 
> 我换成你这个代码还是提示超时。难道真的是我网络问题？

bot重启了吗？以及有置顶动态的情况下虽然会报错，但功能是正常的

**Comment by Misakami** [comment]
> > > 我看过源码了，是没有实现动态有置顶时去置顶的功能，我改了一晚上，勉强修复了（就是方法比较蠢） 去/plugins/bilibili_sub/data_source.py中进行修改 `# 删除置顶 await page.evaluate( """ xs = document.getElementsByClassName('bili-dyn-item__tag'); for (x of xs) { x.parentNode.remove(); } """ ) await page.locator("//div[@class='bili-dyn-list__item'][1]/../*[2]").screenshot( path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg", ) logger.info(f"默认有置顶") await page.locator("//div[@class='bili-dyn-list__item'][1]").screenshot( path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg", ) logger.info(f"无置顶") except Exception as e: logger.error(f"B站订阅：获取用户动态 发送错误 {type(e)}：{e}")`
> > 
> > 
> > 我换成你这个代码还是提示超时。难道真的是我网络问题？
> 
> bot重启了吗？以及有置顶动态的情况下虽然会报错，但功能是正常的

![image](https://user-images.githubusercontent.com/22981008/169766990-4953a39e-5f12-4689-930e-185039c8581e.png)

**Comment by Misakami** [comment]
> > > 我看过源码了，是没有实现动态有置顶时去置顶的功能，我改了一晚上，勉强修复了（就是方法比较蠢） 去/plugins/bilibili_sub/data_source.py中进行修改 `# 删除置顶 await page.evaluate( """ xs = document.getElementsByClassName('bili-dyn-item__tag'); for (x of xs) { x.parentNode.remove(); } """ ) await page.locator("//div[@class='bili-dyn-list__item'][1]/../*[2]").screenshot( path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg", ) logger.info(f"默认有置顶") await page.locator("//div[@class='bili-dyn-list__item'][1]").screenshot( path=dynamic_path / f"{local_user.sub_id}_{dynamic_upload_time}.jpg", ) logger.info(f"无置顶") except Exception as e: logger.error(f"B站订阅：获取用户动态 发送错误 {type(e)}：{e}")`
> > 
> > 
> > 我换成你这个代码还是提示超时。难道真的是我网络问题？
> 
> bot重启了吗？以及有置顶动态的情况下虽然会报错，但功能是正常的

嗯 的确是有报错但是动态在更新了
