### ISSUE TITLE
重启后一直SSL报错

### ISSUE THREAD

**Issue by zhability** [HibiKier/zhenxun_bot#557]
服务器系统是centos7，前面重启了下服务器结果现在各种SSLCert报错。无论是卡池加载，还是B站订阅推送，还是原神今日素材之类的都是报错
`03-06 15:16:30 [WARNING] plugins | 阴阳师 更新数据错误：<class 'aiohttp.client_exceptions.ClientConnectorCertificateError'>：Cannot connect to host yys.res.netease.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1129)')]
03-06 15:17:33 [ERROR] plugins | B站订阅推送发生错误 sub_id： <class 'ssl.SSLCertVerificationError'>：[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1129)
03-06 15:18:03 [ERROR] plugins | B站订阅推送发生错误 sub_id： <class 'ssl.SSLCertVerificationError'>：[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1129)
03-06 15:18:34 [ERROR] plugins | B站订阅推送发生错误 sub_id： <class 'ssl.SSLCertVerificationError'>：[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1129)

`

**Comment by HibiKier** [comment]
虽然不知道发生了什么，但我建议是换Ubuntu

**Comment by zhability** [comment]
> 虽然不知道发生了什么，但我建议是换Ubuntu

centos上这一波也是不知道发生了什么，更新了系统的证书，py的证书都不行

现在已经换到win server上了。目前一切正常
