### ISSUE TITLE
更新pix关键词报错显示搜索图片失败

### ISSUE THREAD

**Issue by Einck0** [HibiKier/zhenxun_bot#559]
![image](https://user-images.githubusercontent.com/91471683/169772505-98c954d0-4d3f-45f9-a642-f36f0f3007ae.png)挂代理也是这样

**Comment by HibiKier** [comment]
啥版本？

**Comment by Einck0** [comment]
之前是1.5.3后来更新成1.5.5也是这样。一开始是可以的后来不知道干了什么就这样了
请问数据库的目录在哪我看看重装一下行不行

**Comment by Einck0** [comment]
重装也不能解决

**Comment by Einck0** [comment]
已解决
