### ISSUE TITLE
更新真寻后想尝试加入插件仓库的插件，显示目录不存在

### ISSUE THREAD

**Issue by ayachimako** [HibiKier/zhenxun_bot#560]
![图片](https://user-images.githubusercontent.com/105858150/169774972-170d1dd3-45e5-4085-86e4-ba032bd6cf30.png)
如图，路径应该是没错的吧...

**Comment by yajiwa** [comment]
这样是装不了插件的，需要手动下载插件放到插件目录
![image](https://user-images.githubusercontent.com/58063798/169797492-233f78c0-8a90-45bb-9948-ee2e67c87692.png)
![image](https://user-images.githubusercontent.com/58063798/169797546-5b6770a7-a6fa-4f0a-ab9c-9ac99039409b.png)
![image](https://user-images.githubusercontent.com/58063798/169797557-1226847e-3396-4181-bd59-0fd495b9e289.png)

**Comment by ayachimako** [comment]
> 这样是装不了插件的，需要手动下载插件放到插件目录 ![image](https://user-images.githubusercontent.com/58063798/169797492-233f78c0-8a90-45bb-9948-ee2e67c87692.png) ![image](https://user-images.githubusercontent.com/58063798/169797546-5b6770a7-a6fa-4f0a-ab9c-9ac99039409b.png) ![image](https://user-images.githubusercontent.com/58063798/169797557-1226847e-3396-4181-bd59-0fd495b9e289.png)

谢谢大佬，但为什么我下载完了之后只有一个文件夹啊，里面也没有插件
![TGD6K_F ~J)@`0(5T8T`FR8](https://user-images.githubusercontent.com/105858150/169805487-d4e231b4-1d63-4c7b-a137-27fc3c24427a.jpg)
![图片](https://user-images.githubusercontent.com/105858150/169805530-b98cb2dc-1478-4d65-8a9a-ded2282505fe.png)

**Comment by ayachimako** [comment]
已经解决了，直接下载了插件仓库的zip包解压出来就有了，谢谢
