### ISSUE TITLE
pid搜图报错

### ISSUE THREAD

**Issue by Natsumelan** [HibiKier/zhenxun_bot#565]
![image](https://user-images.githubusercontent.com/105765802/169799550-1e602822-3ef8-449f-ae08-7b02e124dd0c.png)

**Comment by Natsumelan** [comment]
程序没有报错
![image](https://user-images.githubusercontent.com/105765802/169799648-098e1f11-c15c-4ab2-8884-b241f1b17936.png)

**Comment by HibiKier** [comment]
更新代码

**Comment by Natsumelan** [comment]
> 更新代码

具体怎么更新呢，不太会

**Comment by Einck0** [comment]
> > 更新代码
> 
> 具体怎么更新呢，不太会

私聊检查更新真寻

**Comment by Natsumelan** [comment]
> > > 更新代码
> > 
> > 
> > 具体怎么更新呢，不太会
> 
> 私聊检查更新真寻

这个就是更新后出现的问题

**Comment by Natsumelan** [comment]
> > > 更新代码
> > 
> > 
> > 具体怎么更新呢，不太会
> 
> 私聊检查更新真寻

重启了一下就好了，不过还是谢谢了
