### ISSUE TITLE
删除已经删除的插件的配置

### ISSUE THREAD

**Issue by TiAmoJIA** [HibiKier/zhenxun_bot#566]
删除了一些不太好用的插件但是配置还在config.yaml里也没有自己添加的插件的配置，在哪能找到它们呢
![image](https://user-images.githubusercontent.com/91871280/169801584-a20a383b-be2c-457b-9e34-356d1e887a10.png)

**Comment by TiAmoJIA** [comment]
issue开了就问一下别的，之前私聊都会随机回复，突然不回复了只对指令回复可能是什么原因

**Comment by yajiwa** [comment]
看看今天的更新，更新后加载五次失败会删除对应的插件配置，可以手动替换这两个文件basic_plugins/init_plugin_config/init_none_plugin_count_manager.py
utils/manager/none_plugin_count_manager.py
自动回复是ai插件，可以看看日志

**Comment by TiAmoJIA** [comment]
> 

谢谢大佬
