### ISSUE TITLE
se图不会自动撤回

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#569]
![色图配置](https://user-images.githubusercontent.com/105090141/169822157-a81b0300-e60a-414a-b29c-da259bf14d8b.png)
![色图配置2](https://user-images.githubusercontent.com/105090141/169822165-becdff76-3be3-439c-b7f4-f159b77ed4a2.png)
![色图3](https://user-images.githubusercontent.com/105090141/169822174-367f6556-0979-477f-b954-c29e4178ff02.png)
10秒后没有撤回

**Comment by wlz-remake** [comment]
![QQ截图20220523205111](https://user-images.githubusercontent.com/105090141/169823585-9d2aa735-6512-45d7-902f-a88e9e003081.png)

go-cqhttp内除了正常的收发消息无其他信息

**Comment by HibiKier** [comment]
暂时不要使用webui修改配置，
![图片](https://user-images.githubusercontent.com/45528451/169829391-c58d5fbb-519f-4a0b-9306-b82c6d6e8e53.png)
将单引号去掉

**Comment by wlz-remake** [comment]
> 暂时不要使用webui修改配置， ![图片](https://user-images.githubusercontent.com/45528451/169829391-c58d5fbb-519f-4a0b-9306-b82c6d6e8e53.png) 将单引号去掉

oh！好的，没注意看
