### ISSUE TITLE
希望se图功能能追加反和谐处理

### ISSUE THREAD

**Issue by icegodSora** [HibiKier/zhenxun_bot#574]
就好像这个插件一样，能在图片上追加随机像素点，但是这个插件处理的不是很好，是用base64直接输出的，会直接导致图片大概率被压成渣渣，现在风控太恐怖了，不是很lu的se图都被gank

https://github.com/pcrbot/setu_renew

**Comment by HibiKier** [comment]
830103b9d53d87150c950ea0df0560fdf604994d
