### ISSUE TITLE
色图配置问题

### ISSUE THREAD

**Issue by eachbol2333** [HibiKier/zhenxun_bot#575]
这次更新后的群聊色图开启文件配置后不管用，还是发不出色图
![image](https://user-images.githubusercontent.com/105063888/169866481-a91cbf6b-e0ae-48fb-8693-814d44b30a51.png)
![image](https://user-images.githubusercontent.com/105063888/169866514-37c507e3-2f73-4f78-a7f0-4a7320ec2a49.png)
![image](https://user-images.githubusercontent.com/105063888/169866547-50a1d303-ee74-450e-a805-4a1478b2862d.png)
难道还有哪里没改对吗，谢谢大佬

**Comment by nertcy** [comment]
问题1群的权限要9级，问题2你自己的好感度不够，这里不是提醒你了吗！！！！快速修改好感度在sql中表名：sign_group_users。sql语句的话百度会帮助你的
![image](https://user-images.githubusercontent.com/94539226/169871527-615a77d3-d703-4ebf-974e-7679b2dc4570.png)
