### ISSUE TITLE
好感度总排行报错

### ISSUE THREAD

**Issue by nertcy** [HibiKier/zhenxun_bot#578]
1.5.6版本
![image](https://user-images.githubusercontent.com/94539226/169879271-34719a6c-0a3e-4511-b820-bcf9f12d3d0b.png)
![QQ截图20220524015547](https://user-images.githubusercontent.com/94539226/169879330-76c09c51-a919-4874-bc5e-2d5d51bd6e1e.jpg)

**Comment by HibiKier** [comment]
每次都有？

**Comment by nertcy** [comment]
> 每次都有？

是的今天早上也试过一次还是这样，我开始认为是缺少依赖，还重新在cmd跑了一次。

**Comment by HibiKier** [comment]
py版本多少？
