### ISSUE TITLE
B站订阅问题

### ISSUE THREAD

**Issue by Da2ns** [HibiKier/zhenxun_bot#580]
有up的动态有置顶，检测到动态更新后只会截图到置顶的动态

**Comment by wlz-remake** [comment]
一个解决办法#556

**Comment by wlz-remake** [comment]
![Screenshot_2022-05-24-10-42-40-084_com microsoft emmx](https://user-images.githubusercontent.com/105090141/169937943-1774ba7b-6723-4e2d-a5cd-0ba722b95a94.jpg)
已更新
