### ISSUE TITLE
添加商品出错

### ISSUE THREAD

**Issue by KuLiPoi** [HibiKier/zhenxun_bot#582]
添加商品 name:可疑的药Test price:5 des:效果未知
添加商品 name:可疑的药Test price:5 des:效果未知 失败了...

控制台没有报错 数据库的话goods_info表是空的 没有示例的那个神秘药的商品，我尝试手动加入商品也会报错

机器人版本是0.1.5.6

情况和 #422 一样

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/170046010-c5184877-83a0-4868-baae-01db06ed2e15.png)
无法复现？

**Comment by KuLiPoi** [comment]
自己的问题，已处理，谢谢。
