### ISSUE TITLE
go-cqhttp握手失败

### ISSUE THREAD

**Issue by smolensk-1375** [HibiKier/zhenxun_bot#583]
![Screenshot_2022-05-24-07-49-45-813_com oray sunlogin](https://user-images.githubusercontent.com/74787161/169934406-e5153f1a-fb7a-4099-bb12-805849d7b3af.jpg)
![Screenshot_2022-05-24-07-50-55-720_com oray sunlogin](https://user-images.githubusercontent.com/74787161/169934415-51c54dbb-9bfb-4b67-9e7c-3499172214cf.jpg)
基本上都按文档来做了，但是不明白为什么会握手失败，请问有大佬知道吗？

**Comment by HibiKier** [comment]
v11不是v1

**Comment by smolensk-1375** [comment]
感谢
