### ISSUE TITLE
应该是与词云功能相关的报错

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#584]
![image](https://user-images.githubusercontent.com/50237543/169936369-01421cf3-29ac-43fa-b676-7054bcba9a45.png)
![image](https://user-images.githubusercontent.com/50237543/169936408-08b5363a-6358-4be5-bcbd-ff32f6232583.png)
看着像是与词云功能相关的报错，请教下该如何解决，非常感谢！！QwQ

**Comment by WWWA7** [comment]
更新过版本了吗？没有的话更新下版本试试，新版本修复了很多东西
