### ISSUE TITLE
CSGO开箱次数变负且仍可开箱

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#585]
![IMG_20220524_110357](https://user-images.githubusercontent.com/105090141/169940403-1b553d9d-f5fb-41a5-ac96-bbfef0dd5c3c.png)
如图，开箱次数我设置为了3次，在开箱失败的情况下真寻仍然扣除了次数且剩余次数变为了负数，且此情况下单次开箱仍然可用。
此外，希望其他游戏抽卡也能添加次数限制

**Comment by HibiKier** [comment]
?真寻版本是？

**Comment by wlz-remake** [comment]
> ?真寻版本是？

0.1.5.5

**Comment by wlz-remake** [comment]
> ?真寻版本是？

结束，更新之后无问题了
