### ISSUE TITLE
搜番功能报错，已挂代理

### ISSUE THREAD

**Issue by Judp28** [HibiKier/zhenxun_bot#586]
![49OAH`R~Q9$0%}KQY)CB1ZJ](https://user-images.githubusercontent.com/105803689/169944213-de401b46-2099-40ac-bc34-1513439e34f7.png)

**Comment by Judp28** [comment]
![SXHUT3XF2CIPX `9$U%@@5B](https://user-images.githubusercontent.com/105803689/169944237-83c37e78-c073-4c92-b79e-415f51829e58.png)

**Comment by SPLUS-VABLE** [comment]
大佬想问一下怎么挂代理

**Comment by Judp28** [comment]
> 大佬想问一下怎么挂代理

我用的clash

**Comment by HibiKier** [comment]
config.py中是否已经写了代理地址？

**Comment by Judp28** [comment]
> config.py中是否已经写了代理地址？

已解决
