### ISSUE TITLE
自己写的插件，运行webui访问普通插件时报错

### ISSUE THREAD

**Issue by yixue99** [HibiKier/zhenxun_bot#588]
05-24 13:54:01 [ERROR] plugins | WEB_UI GET /webui/plugins model：check_word 发生错误 <class 'pydantic.error_wrappers.ValidationError'>：1 validation error for CountLimit
limit_type
  value could not be parsed to a boolean (type=type_error.bool)

**Comment by HibiKier** [comment]
你这个插件的次数限制在plugin2limit中是怎么写的呢

**Comment by yixue99** [comment]
> 你这个插件的次数限制在plugin2limit中是怎么写的呢
![image](https://user-images.githubusercontent.com/50444999/170032341-ccef9526-e93e-4931-8090-5b4425cfa0d3.png)
![image](https://user-images.githubusercontent.com/50444999/170032775-db7e536f-146f-4d3a-a4ec-326cc42bb43e.png)

**Comment by HibiKier** [comment]
是我countlimit中limit type类型写错了，已修复
