### ISSUE TITLE
安装依赖出现问题，弄了好久也不知道咋办

### ISSUE THREAD

**Issue by LDAOYU** [HibiKier/zhenxun_bot#589]
![屏幕截图 2022-05-24 143907](https://user-images.githubusercontent.com/106139669/169965028-28d755f5-3175-446c-9810-b5800743d555.png)

**Comment by LDAOYU** [comment]
Installing dependencies from lock file

No dependencies to install or update

**Comment by LDAOYU** [comment]
![屏幕截图 2022-05-24 154027](https://user-images.githubusercontent.com/106139669/169976177-768e1948-29c7-4e38-8b21-0e3c2b0c41ad.png)

**Comment by wlz-remake** [comment]
看看数据库连接配置
![QQ截图20220524161411](https://user-images.githubusercontent.com/105090141/169983216-6a262207-07b1-4a6a-b9e7-f2be3f50e5c4.png)

**Comment by wlz-remake** [comment]
请仔细、耐心、认真地看安装文档
