### ISSUE TITLE
win中原神黄历字体问题

### ISSUE THREAD

**Issue by ChenPiTang-Hui** [HibiKier/zhenxun_bot#591]
![-784cde164dc2df72](https://user-images.githubusercontent.com/69108232/169977751-259a9cce-76ed-4466-bbcf-36094ff48c43.png)
查看了Issues并无win修改的方法

**Comment by wlz-remake** [comment]
该问题是数据来源的问题，和真寻无关：https://genshin.pub/

**Comment by HibiKier** [comment]
你浏览器打开就是这样的，真寻只是帮你截了 个图

**Comment by ChenPiTang-Hui** [comment]
已解决这个问题可能是win分辨率的问题 当用高分辨率启动远程连接后 字体正常了
![QQ图片20220527171249](https://user-images.githubusercontent.com/69108232/170669594-8132b972-92e8-412e-8cd3-30c0873bd77b.png)
