### ISSUE TITLE
csgo开箱就只有五个箱子能开吗，可以自己添加箱子吗

### ISSUE THREAD

**Issue by SPLUS-VABLE** [HibiKier/zhenxun_bot#592]

**Comment by wlz-remake** [comment]
[csgo开箱](https://hibikier.github.io/zhenxun_bot/docs/help_doc/public_plugins/draw_card_plugins/draw_card_plugins.html#csgo%E5%BC%80%E7%AE%B1)

**Comment by SPLUS-VABLE** [comment]
> https://hibikier.github.io/zhenxun_bot/docs/help_doc/public_plugins/draw_card_plugins/draw_card_plugins.html#csgo%E5%BC%80%E7%AE%B1

能添加古堡等其他箱子吗

**Comment by HibiKier** [comment]
buff小号被封了，我加不了，你自己要加的话直接在plugins/open_cases/config中按照格式加你相加的箱子就行了

**Comment by xuebiya** [comment]
> buff小号被封了，我加不了，你自己要加的话直接在plugins/open_cases/config中按照格式加你相加的箱子就行了

有爬图片的脚本吗 图片直链不是明文的
