### ISSUE TITLE
无法运行bot.py！！求助

### ISSUE THREAD

**Issue by dongbao666666** [HibiKier/zhenxun_bot#593]
C:\Users\Administrator\zhenxun>poetry shell
Spawning shell within C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-O2FezPUB-py3.9
Microsoft Windows [版本 10.0.17763.1879]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\Administrator\zhenxun>C:\Users\Administrator\zhenxun\zhenxun_bot\bot.py
Traceback (most recent call last):
  File "C:\Users\Administrator\zhenxun\zhenxun_bot\bot.py", line 1, in <module>
    import nonebot
ModuleNotFoundError: No module named 'nonebot'

**Comment by yixue99** [comment]
库没装全

**Comment by wlz-remake** [comment]
![image](https://user-images.githubusercontent.com/105090141/169985599-60e0d9d1-9b97-4ab9-85b1-6c43ef825247.png)

**Comment by dongbao666666** [comment]
感谢 ！应该是在真寻文件夹里安装依赖！已解决
