### ISSUE TITLE
真寻文档错误和修改建议

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#594]
![image](https://user-images.githubusercontent.com/105090141/169987199-e9e9cea3-05e3-43dc-8fa3-a33f336c5324.png)
[原神相关](https://hibikier.github.io/zhenxun_bot/docs/help_doc/public_plugins/genshin_plugins/genshin_plugins.html)
此处出现了两个原神签到，第二个应为【原神树脂提醒】吧

![image](https://user-images.githubusercontent.com/105090141/169988118-588537c8-1df3-41ab-9add-56f7edc20591.png)
[安装绪山真寻bot](https://hibikier.github.io/zhenxun_bot/docs/installation_doc/install_zhenxun.html)
虽然但是建议说明“与教程一模一样的命令代码”指的是Linux部分，不少在win端安装的小白会踩坑

**Comment by HibiKier** [comment]
文档已更新
