### ISSUE TITLE
如何在pixiv_rank_search模块中启用群聊R18功能？

### ISSUE THREAD

**Issue by SpideyUU** [HibiKier/zhenxun_bot#595]
更新了0156版本后，感谢将send_setu模块和pix模块开启r18功能

当本人尝试将

await send_image(info_list, pixiv_keyword, bot, event)

加在
if event.message_type == "group":
和
if "r18" in msg.lower():下

再次在群聊内@机器人 并使用r18关键词后
得到如下报错，不知如何解决，请问有什么解决方案吗？
![image](https://user-images.githubusercontent.com/34191381/169991178-8a681165-0469-439c-9c99-41376c02ac72.png)

**Comment by wlz-remake** [comment]
学过其他语言没学过python，尝试着这样改了代码
![image](https://user-images.githubusercontent.com/105090141/170007567-61b83534-4772-4987-a40f-13831d5e93bf.png)
![image](https://user-images.githubusercontent.com/105090141/170007622-5a968a75-c0fe-43af-a134-362802b7a789.png)
这应该是判断句吧，我直接把判断注释掉了
能成功运行并执行
![image](https://user-images.githubusercontent.com/105090141/170009529-36c8e83e-5a1a-46fc-90d1-372a462af94a.png)
不过我这边日志里说被风控了，图发不出来
不懂能不能帮到你

**Comment by SpideyUU** [comment]
> 学过其他语言没学过python，尝试着这样改了代码 ![image](https://user-images.githubusercontent.com/105090141/170007567-61b83534-4772-4987-a40f-13831d5e93bf.png) ![image](https://user-images.githubusercontent.com/105090141/170007622-5a968a75-c0fe-43af-a134-362802b7a789.png) 这应该是判断句吧，我直接把判断注释掉了 能成功运行并执行 ![image](https://user-images.githubusercontent.com/105090141/170009529-36c8e83e-5a1a-46fc-90d1-372a462af94a.png) 不过我这边日志里说被风控了，图发不出来 不懂能不能帮到你

感谢回复，我的思路也是对修改句进行修改，改为了正常情况的判断，我现在就试试把这段注掉看看能不能发送。

**Comment by HibiKier** [comment]
a7d61b1f2b248c9b2df7d26e155d8e6ba5c205f7 搜图在群聊中提供r18配置
