### ISSUE TITLE
运行bot.py出错

### ISSUE THREAD

**Issue by yingshihang** [HibiKier/zhenxun_bot#596]
![`F120}QA0VE7_@8{OC`CFLU(1).png](https://user-images.githubusercontent.com/89337308/170041226-5ccd57c5-34f6-4167-b882-269ee973f985.png)

**Comment by wlz-remake** [comment]
进虚拟环境了吗
如果进了请看#593
一模一样的问题

**Comment by HibiKier** [comment]
报错日志发全，不缺流量
