### ISSUE TITLE
求助，目前只能管理英文名插件，中文名插件无法被管理

### ISSUE THREAD

**Issue by yuan488** [HibiKier/zhenxun_bot#598]
![-4d3ce28f806a71e5](https://user-images.githubusercontent.com/69119229/170023347-a9c340bb-be10-4b5f-b718-45a5201171b6.jpg)
如图，仅能开关ai插件，其他中文名插件无法打开与关闭

**Comment by yuan488** [comment]
![Screenshot_2022-05-24-19-02-51-931_com sonelli juicessh](https://user-images.githubusercontent.com/69119229/170024815-b4888571-6e8b-459d-a122-c083db58df2d.jpg)
![Screenshot_2022-05-24-19-01-20-128_com sonelli juicessh](https://user-images.githubusercontent.com/69119229/170024828-2c69b76d-c136-4df1-94cd-418a93a8e141.jpg)
log似乎没有报错，中文插件被当成ai问答处理了

**Comment by yuan488** [comment]
已经添加了，开启ai是可以触发的，重启命令也能使用

**Comment by MingxuanGame** [comment]
能开一下 `debug` 模式重启再试吗
 
在 `.env.dev` 修改
```
LOG_LEVEL=INFO
```

为

```
LOG_LEVEL=DEBUG
```

**Comment by HibiKier** [comment]
用过webui了吧，把plugin2setting删了重新生成试试

**Comment by yuan488** [comment]
感谢大佬，已解决。确实是webui的bug
