### ISSUE TITLE
今天更新1.5.6版本后，bot聊天报错

### ISSUE THREAD

**Issue by Excalibur5100** [HibiKier/zhenxun_bot#599]
![image](https://user-images.githubusercontent.com/105792144/170024805-ba0c4ee4-a89e-470c-8a93-3d99f8f179ad.png)
如图，今天更新后才会这样，更新前如果没触发任何插件的指令的话，无论怎样哪怕驴唇不对马嘴都会回一句，现在只会说格式不合法；之前是一直都没有在配置中写入过图灵key的但能正常回复

然后根据运行日志的提示去看了下对应插件代码，按道理来说就算没有图灵ai聊天回复，也应该是这代码里写对应情况的回复吧（你好，自我介绍这些能够回复对应内容），而不应该是报格式错误
![image](https://user-images.githubusercontent.com/105792144/170025183-ea29ab55-9413-4928-857f-8fa29ac59cfc.png)
![image](https://user-images.githubusercontent.com/105792144/170027859-256b9703-3184-47be-aab7-66187fbd9b58.png)
![image](https://user-images.githubusercontent.com/105792144/170027895-7b935e39-7fcb-4a68-a5f8-d8779fdb2dd7.png)

顺便问一下，如果是非要图灵key的话，是哪个图灵apikey？另外，另一个插件alapi和这个ai插件配置里的ALAPI_AI_CHECK一项是什么关系

**Comment by HibiKier** [comment]
也没说非要，有图灵优先图灵，没有就青云客，因为青云客有些话非常zz，所以需要通过alapi的检测来对回复进行检测后发送，也不可以不开启检测

**Comment by Excalibur5100** [comment]
那之前也没有用图灵api，也能回复一些内容；现在如果没有图灵且发送内容不是指令的话bot直接说格式不合法，也没找到是哪里判定后回复“格式不合法的”，就算只有之前的憨憨样子可行呐，现在这样真·智障了/捂脸

**Comment by Excalibur5100** [comment]
![image](https://user-images.githubusercontent.com/105792144/170039080-ddbb7bbf-2dd7-4462-bc5a-f74963c473eb.png)
我卸载并重新安装后不会回复格式不合法了，但日志出现了这样的报错，请问什么原因咋解决呢
