### ISSUE TITLE
部署后在QQ使用指令没有反应

### ISSUE THREAD

**Issue by THNEden** [HibiKier/zhenxun_bot#604]
![9IFUL}(Y`L$T{YSAWZ7` P2](https://user-images.githubusercontent.com/87106832/170075327-f5ef537b-92cc-40e5-aa89-de6c2667141d.png)
![Z 0@1~DZBUBI69`0243D(J](https://user-images.githubusercontent.com/87106832/170075409-ebb8d18f-f292-4223-b942-dea8db63302a.png)
0基础入门，倒在最后一步了，能部署下来说明前面的步骤没有做错才是，请教一下具体如何使用bot

**Comment by XKaguya** [comment]
go-cphttp开了吗

**Comment by XKaguya** [comment]
没显示加载了XX跳超级用户和connected 就是没连上go-cqhttp

**Comment by XKaguya** [comment]
![image](https://user-images.githubusercontent.com/96401952/170077322-f983a24a-b2d4-4c1a-81b1-8b2e84329ad5.png)

**Comment by THNEden** [comment]
好的 已经可以使用了 非常感谢

**Comment by wlz-remake** [comment]
自己把问题关了吧。。。
