### ISSUE TITLE
求助，安装依赖时出现问题

### ISSUE THREAD

**Issue by pamss** [HibiKier/zhenxun_bot#605]
C:\Users\Lenovo\Desktop\zhenxun_bot-main>poetry install
Installing dependencies from lock file

Package operations: 25 installs, 0 updates, 0 removals

  • Installing scipy (1.6.1)

  EnvCommandError

  Command C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ix95yl7x-py3.10\Scripts\pip.exe install --no-deps file:///C:/Users/Lenovo/AppData/Local/pypoetry/Cache/artifacts/5a/ee/20/36676d9298f4330ba6bdbfb04bef679b543140a69b095e294e76a5bee9/scipy-1.6.1.tar.gz errored with the following return code 1, and output:
  Processing c:\users\lenovo\appdata\local\pypoetry\cache\artifacts\5a\ee\20\36676d9298f4330ba6bdbfb04bef679b543140a69b095e294e76a5bee9\scipy-1.6.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error

    Preparing metadata (pyproject.toml) did not run successfully.
    exit code: 1

    [126 lines of output]
    setup.py:461: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\Lenovo\AppData\Local\Temp\pip-modern-metadata-xxhdalyy'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from SciPy source directory.
    INFO: lapack_opt_info:
    INFO: lapack_armpl_info:
    INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    INFO: customize MSVCCompiler
    INFO:   libraries armpl_lp64_mp not found in ['C:\\Users\\Lenovo\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-ix95yl7x-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    INFO: lapack_mkl_info:
    INFO:   libraries mkl_rt not found in ['C:\\Users\\Lenovo\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-ix95yl7x-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    INFO: openblas_lapack_info:
    INFO:   libraries openblas not found in ['C:\\Users\\Lenovo\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-ix95yl7x-py3.10\\lib', 'C:\\']
    INFO: get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    INFO: customize GnuFCompiler
    WARN: Could not locate executable g77
    WARN: Could not locate executable f77
    INFO: customize IntelVisualFCompiler
    WARN: Could not locate executable ifort
    WARN: Could not locate executable ifl
    INFO: customize AbsoftFCompiler
    WARN: Could not locate executable f90
    INFO: customize CompaqVisualFCompiler
    WARN: Could not locate executable DF
    INFO: customize IntelItaniumVisualFCompiler
    WARN: Could not locate executable efl
    INFO: customize Gnu95FCompiler
    WARN: Could not locate executable gfortran
    WARN: Could not locate executable f95
    INFO: customize G95FCompiler
    WARN: Could not locate executable g95
    INFO: customize IntelEM64VisualFCompiler
    INFO: customize IntelEM64TFCompiler
    WARN: Could not locate executable efort
    WARN: Could not locate executable efc
    INFO: customize PGroupFlangCompiler
    WARN: Could not locate executable flang
    WARN: don't know how to compile Fortran code on platform 'nt'
    INFO:   NOT AVAILABLE
    INFO:
    INFO: openblas_clapack_info:
    INFO:   libraries openblas,lapack not found in ['C:\\Users\\Lenovo\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-ix95yl7x-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    INFO: flame_info:
    INFO:   libraries flame not found in ['C:\\Users\\Lenovo\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-ix95yl7x-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    INFO: accelerate_info:
    INFO:   NOT AVAILABLE
    INFO:
    INFO: atlas_3_10_threads_info:
    INFO: Setting PTATLAS=ATLAS
    INFO:   libraries tatlas,tatlas not found in C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ix95yl7x-py3.10\lib
    INFO:   libraries tatlas,tatlas not found in C:\
    INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    INFO:   NOT AVAILABLE
    INFO:
    INFO: atlas_3_10_info:
    INFO:   libraries satlas,satlas not found in C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ix95yl7x-py3.10\lib
    INFO:   libraries satlas,satlas not found in C:\
    INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
    INFO:   NOT AVAILABLE
    INFO:
    INFO: atlas_threads_info:
    INFO: Setting PTATLAS=ATLAS
    INFO:   libraries ptf77blas,ptcblas,atlas not found in C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ix95yl7x-py3.10\lib
    INFO:   libraries ptf77blas,ptcblas,atlas not found in C:\
    INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
    INFO:   NOT AVAILABLE
    INFO:
    INFO: atlas_info:
    INFO:   libraries f77blas,cblas,atlas not found in C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ix95yl7x-py3.10\lib
    INFO:   libraries f77blas,cblas,atlas not found in C:\
    INFO: <class 'numpy.distutils.system_info.atlas_info'>
    INFO:   NOT AVAILABLE
    INFO:
    INFO: lapack_info:
    INFO:   libraries lapack not found in ['C:\\Users\\Lenovo\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-ix95yl7x-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-o6gig_kc\overlay\Lib\site-packages\numpy\distutils\system_info.py:1902: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    INFO: lapack_src_info:
    INFO:   NOT AVAILABLE
    INFO:
    C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-o6gig_kc\overlay\Lib\site-packages\numpy\distutils\system_info.py:1902: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    INFO:   NOT AVAILABLE
    INFO:
    Traceback (most recent call last):
      File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ix95yl7x-py3.10\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
        main()
      File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ix95yl7x-py3.10\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ix95yl7x-py3.10\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-o6gig_kc\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-o6gig_kc\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-o6gig_kc\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 588, in <module>
        setup_package()
      File "setup.py", line 584, in setup_package
        setup(**metadata)
      File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-o6gig_kc\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 499, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
    To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
    See site.cfg.example in the Scipy source directory and
    https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed

  Encountered error while generating package metadata.

  See above for output.

  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.
  WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
  You should consider upgrading via the 'C:\Users\Lenovo\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ix95yl7x-py3.10\Scripts\python.exe -m pip install --upgrade pip' command.

  at ~\AppData\Local\Programs\Python\Python310\lib\site-packages\poetry\utils\env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

**Comment by Nova-Noir** [comment]
根据搜索，好像都是`python3.10`的问题，可以尝试降级`python`再次安装。
相关：[Error while installing pytq5 with pip: Preparing metadata (pyproject.toml) did not run successfully](https://stackoverflow.com/questions/70961915/error-while-installing-pytq5-with-pip-preparing-metadata-pyproject-toml-did-n)

**Comment by HibiKier** [comment]
py降级
