### ISSUE TITLE
pip install wordcloud 出现错误

### ISSUE THREAD

**Issue by xi888888** [HibiKier/zhenxun_bot#609]
C:\zhenxun_bot-0.1.5.3>pip install wordcloud
Collecting wordcloud
  Using cached wordcloud-1.8.1.tar.gz (220 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.6.1 in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from wordcloud) (1.22.2)
Requirement already satisfied: pillow in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from wordcloud) (9.0.1)
Requirement already satisfied: matplotlib in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from wordcloud) (3.5.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from matplotlib->wordcloud) (3.0.7)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from matplotlib->wordcloud) (4.29.1)
Requirement already satisfied: packaging>=20.0 in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from matplotlib->wordcloud) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from matplotlib->wordcloud) (1.3.2)
Requirement already satisfied: six>=1.5 in c:\users\administrator\appdata\local\pypoetry\cache\virtualenvs\zhenxun-bot-sog-iuzd-py3.9\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\color_from_image.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\tokenization.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\wordcloud.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\_version.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\__init__.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\__main__.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\stopwords -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-cpython-39\wordcloud
      UPDATING build\lib.win-amd64-cpython-39\wordcloud/_version.py
      set build\lib.win-amd64-cpython-39\wordcloud/_version.py to '1.8.1'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\wordcloud
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-sOg-iuzD-py3.9\include -IC:\python\include -IC:\python\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" /Tcwordcloud/query_integral_image.c /Fobuild\temp.win-amd64-cpython-39\Release\wordcloud/query_integral_image.obj
      query_integral_image.c
      C:\python\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wordcloud did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running install
      C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-sOg-iuzD-py3.9\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\color_from_image.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\tokenization.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\wordcloud.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\_version.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\__init__.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\__main__.py -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\stopwords -> build\lib.win-amd64-cpython-39\wordcloud
      copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-cpython-39\wordcloud
      UPDATING build\lib.win-amd64-cpython-39\wordcloud/_version.py
      set build\lib.win-amd64-cpython-39\wordcloud/_version.py to '1.8.1'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\wordcloud
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-sOg-iuzD-py3.9\include -IC:\python\include -IC:\python\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" /Tcwordcloud/query_integral_image.c /Fobuild\temp.win-amd64-cpython-39\Release\wordcloud/query_integral_image.obj
      query_integral_image.c
      C:\python\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wordcloud

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Nova-Noir** [comment]
查看环境变量中是否包含`INCLUDE`项。检查Visual Studio是否安装C++/CLI支持。
相关： [Cannot open include file: 'io.h': No such file or directory](https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory)

**Comment by yangmagua** [comment]
pip 失败时应该先考虑使用代理，使用代理再失败应该去下载whl文件pip，再失败就提issues
