### ISSUE TITLE
超级用户设置不生效

### ISSUE THREAD

**Issue by BestRailgun** [HibiKier/zhenxun_bot#61]
ENV.DEV文件已经填写了SUPERUSERS，私聊还是无权限
![屏幕截图 2021-10-04 172431](https://user-images.githubusercontent.com/53421615/135826765-2dfac51c-754a-44e2-a396-5cf80128c390.png)

**Comment by HibiKier** [comment]
重启过了吗

**Comment by BestRailgun** [comment]
log显示自动更新权限就好了，多谢作者。
第一次部署，之前看没权限就重启了几次。
