### ISSUE TITLE
退出卡死

### ISSUE THREAD

**Issue by dishuii** [HibiKier/zhenxun_bot#611]
screen里 每次按Ctrl+C退出 就一直卡死在这了，Waiting for application shutdown 什么命令都没反应，只能Ctrl+A+D退出后结束这个窗口，要用再重新创建
![Snipaste_2022-05-25_07-07-11](https://user-images.githubusercontent.com/33979662/170151946-4e4e5836-a322-4ac1-96a8-d3c4916606f9.jpg)

**Comment by Nova-Noir** [comment]
使用ctrl+z可以强制结束

**Comment by dishuii** [comment]
> 

有效，感谢
