### ISSUE TITLE
数据库连接错误

### ISSUE THREAD

**Issue by xdaqda** [HibiKier/zhenxun_bot#612]
运行bot.py后数据库连接错误
![QQ图片20220525090454](https://user-images.githubusercontent.com/106209173/170157086-20ae5dbc-91de-47ab-9dbb-7fcc3ae7adf6.png)
![QQ图片20220525090515](https://user-images.githubusercontent.com/106209173/170157088-2fabcce9-84a7-4164-a1b2-a06e15e3569e.png)

**Comment by HibiKier** [comment]
检查数据库配置填写是否正确

**Comment by xdaqda** [comment]
> 
安装时用的代码和安装文档一直，所以我直接复制了文档的代码，我改动配置之后好像还是连接错误
