### ISSUE TITLE
真寻休息后戳一戳仍有反应

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#615]
系统版本：Windows 10 家庭版 21H2
真寻版本：0.1.5.6
错误截图
![-2e7523b5b9298e53](https://user-images.githubusercontent.com/105090141/170174762-c3f46c31-6c5e-4d73-a139-c72d507767c9.jpg)
![-925c9f089bf0ba](https://user-images.githubusercontent.com/105090141/170174927-3a43b9d5-c34d-4c65-bf5e-dca0c45acb19.jpg)

错误说明
如图

**Comment by HibiKier** [comment]
无法复现？
![图片](https://user-images.githubusercontent.com/45528451/170816238-ae55c093-4587-42bd-b671-f488cb7b32b2.png)

**Comment by HibiKier** [comment]
724541d69128b6875b719b1b0c31848b5fba3158 已修复
