### ISSUE TITLE
骂我功能报错

### ISSUE THREAD

**Issue by qclf** [HibiKier/zhenxun_bot#616]
gocq提示
![QQ截图20220525105654](https://user-images.githubusercontent.com/97816993/170175019-857a5fcf-7534-4d85-a02d-cd25ac190b88.png)
zhenxun提示
![QQ截图20220525105927](https://user-images.githubusercontent.com/97816993/170175022-5a65701f-d005-422f-a815-cc6a271ef277.png)

**Comment by wlz-remake** [comment]
ffmpeg装了吗

**Comment by HiDolen** [comment]
需要安装ffmpeg，Ubuntu 指令 `sudo apt install -y ffmpeg`

**Comment by qclf** [comment]
解决了，感谢
