### ISSUE TITLE
建议增加一个启动异常反馈

### ISSUE THREAD

**Issue by yusana213214** [HibiKier/zhenxun_bot#62]
能不能加上一个使用重启命令，或者手动ctrlc结束进程再次运行的时候，遇到插件加载失败但是不影响基本功能的前提下，向超级用户推送模块报错日志（或者是提示"xx加载异常，请查看错误日志"提示）因为有时候并不是随时都在服务器上，而且有时候更新完成重启以后部分功能挂壁了不知道

或者在功能状态指令里面，对无法调用的插件用红色字体标出error

感觉理论上是可以做到的，不知道这玩意儿有没有实际用处，提了再说

**Comment by HibiKier** [comment]
可以加
