### ISSUE TITLE
群功能和私聊功能不统一

### ISSUE THREAD

**Issue by DeparturesNeko** [HibiKier/zhenxun_bot#621]
config文件使用默认配置的情况下，“骂我”功能和“bt搜索”功能仅私聊可触发，群聊时无法触发
下图中，第一个success标签后为群聊，第二个success标签后为私聊
![图片](https://user-images.githubusercontent.com/96569888/170205462-928d6c5c-29c8-4b4f-b315-1c18fed00962.png)

**Comment by DeparturesNeko** [comment]
> 默认配置“骂我”是可以群聊触发的 ![image](https://user-images.githubusercontent.com/105090141/170208251-61410eb8-8f82-4d5e-b533-246b3ce87425.png)

@真寻之后可以触发，了解了，但是bt功能还是只能私聊

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/170211025-cea4d37e-6712-4fbe-9223-8a52e4041650.png)
有没有可能这个不是bug并且文档已经写了呢？
