### ISSUE TITLE
首次启动时插件无法启动以及数据库连接错误

### ISSUE THREAD

**Issue by GuanGuan502L** [HibiKier/zhenxun_bot#627]
### 错误截图

![Screenshot_20220525_170540_com aidlux_edit_90557028094514](https://user-images.githubusercontent.com/92279074/170226090-eefcf834-d4e8-48b4-a3e8-22d65ef21fa3.jpg)
![Screenshot_20220525_170540_com aidlux_edit_90557028094514](https://user-images.githubusercontent.com/92279074/170226161-fec2c356-3f4e-48ab-9391-3a907afc5852.jpg)
![Screenshot_20220525_170551_com aidlux_edit_90569348402325](https://user-images.githubusercontent.com/92279074/170226168-7441c7f0-4674-46e4-8b40-84074795fe22.jpg)
![Screenshot_20220525_170604_com aidlux_edit_90592025254925](https://user-images.githubusercontent.com/92279074/170226171-7cdd0653-3b50-456f-8fbf-0c2896bf8079.jpg)
![Screenshot_20220525_170609_com aidlux_edit_90610424866902](https://user-images.githubusercontent.com/92279074/170226174-50a30df3-4fcf-4e8f-8c93-ea8c0ca943ea.jpg)

### 日志截图

![Screenshot_20220525_171858_cn wps moffice_eng](https://user-images.githubusercontent.com/92279074/170228890-f3395623-2d47-41a3-b2d1-55b35d0fb179.jpg)
![Screenshot_20220525_172042_cn wps moffice_eng](https://user-images.githubusercontent.com/92279074/170228900-b262aff8-2a0b-4e36-b5b3-f6e6cf46ca66.jpg)
![Screenshot_20220525_172100_cn wps moffice_eng](https://user-images.githubusercontent.com/92279074/170228902-a2026a01-18f7-4f62-a9ff-d0625349f794.jpg)

### 错误说明
按照教程配置数据库，poetry安装依赖无误，首次启动bot.py时报错，部分截图如上，看起来好像是无法启动插件以及数据库连接错误。猜测可能与系统环境有关。另:启动shell时有如下提示，不知道是否有关系
![Screenshot_20220525_172748](https://user-images.githubusercontent.com/92279074/170230198-ab5ea784-50fa-4341-b514-fa04e9aea812.jpg)

**Comment by HibiKier** [comment]
发一下第一个插件报错的截图日志，还有看日志事你数据库没有安装

**Comment by GuanGuan502L** [comment]
![Screenshot_20220525_201915_cn wps moffice_eng](https://user-images.githubusercontent.com/92279074/170260393-c5752690-5114-4114-bf80-8ae9213783b7.jpg)
数据库的话我装了，不过当时安装教程没装成功后来从官网装的，版本和教程不一样，我再重新装一下数据库试试

**Comment by GuanGuan502L** [comment]
> 发一下第一个插件报错的截图日志，还有看日志事你数据库没有安装



> 发一下第一个插件报错的截图日志，还有看日志事你数据库没有安装

数据库的话我装了，不过当时安装教程没装成功后来从官网装的，版本和教程不一样，我再重新装一下数据库试试，下面这个是错误日志第一页的截图
![Screenshot_20220525_201915_cn wps moffice_eng](https://user-images.githubusercontent.com/92279074/170408895-b4e1fbf6-b1a8-4760-aa57-46a1f8e8a8be.jpg)

**Comment by GuanGuan502L** [comment]
> 

数据库的话我装了，不过当时安装教程没装成功后来从官网装的，版本和教程不一样，我再重新装一下数据库试试，下面这个是错误日志第一页的截图
![Screenshot_20220525_201915_cn wps moffice_eng](https://user-images.githubusercontent.com/92279074/170409360-7334ed83-20b3-4352-b5c9-ba8c93415157.jpg)

**Comment by HibiKier** [comment]
没截全，第一个插件都加载失败的话可能是日期原因

**Comment by GuanGuan502L** [comment]
> 

不好意思之前没有用过错误日志不太会看，这次多截了一些，还有把时间同步至北京时间后问题未能解决，应该和时间没有关系
![Screenshot_20220529_173340](https://user-images.githubusercontent.com/92279074/170861584-3084c011-7b20-4f4d-950c-49fa7225b260.jpg)

**Comment by GuanGuan502L** [comment]
不好意思之前没有用过错误日志不太会看，这次多截了一些，还有把时间同步至北京时间后问题未能解决，应该和时间没有关系
![Screenshot_20220529_173310_cn wps moffice_eng](https://user-images.githubusercontent.com/92279074/170861648-8db0b5c3-8e14-4758-80b6-e64b33b618e6.jpg)

**Comment by HibiKier** [comment]
没有见过，尝试百度
![图片](https://user-images.githubusercontent.com/45528451/172012817-6cf7023c-684d-4aec-96cc-4d6e20ff81eb.png)
