### ISSUE TITLE
draw_card模块无法正确加载

### ISSUE THREAD

**Issue by qwerdvd** [HibiKier/zhenxun_bot#628]
### 错误截图

![G79F2OL_)JOM4MD41{9DJ L](https://user-images.githubusercontent.com/105906879/170239319-bf0fb092-0684-4069-813b-1efc3237cbba.png)

### 日志截图

![YFGDTG$A WV_Y0Q@@N_X9{2](https://user-images.githubusercontent.com/105906879/170239811-3da50abd-99de-4620-965d-08e224bc3d65.png)

![9GFO(}X9ORP6}WSMU5NQMVP](https://user-images.githubusercontent.com/105906879/170239837-613cdec4-67aa-4128-8921-ebc9d0fde6f2.png)

### 错误说明

draw_card模块无法正确加载

**Comment by demonrain** [comment]
ImportError: cannot import name 'hdrs' from partially initialized module 'aiohttp' (most likely due to a circular import)

**Comment by HibiKier** [comment]
替换draw_card

**Comment by qwerdvd** [comment]
已解决，谢谢
