### ISSUE TITLE
关于账号被风控

### ISSUE THREAD

**Issue by ardsgfcrtjhj** [HibiKier/zhenxun_bot#629]
### 错误截图

![image](https://user-images.githubusercontent.com/33345867/170241222-40d4ce5f-b374-4c65-8a00-81a11fbc7844.png)

### 日志截图

[img]

### 错误说明

大佬救命！在群里发色图显示账号被风控，可是我又单独建了一个只有我和bot的群做测试，却能发出色图。难道风控是指定群来风控的吗？在别的提问中看到，说是bot多挂几天就好了，这样能行吗。。。

**Comment by ardsgfcrtjhj** [comment]
而且不是色图r的问题，我已经在1.5.6中打开了群r18的开关

**Comment by HibiKier** [comment]
风控管不了，你只能祈求腾讯，建议多挂几天

**Comment by ardsgfcrtjhj** [comment]
> 风控管不了，你只能祈求腾讯，建议多挂几天

好的多谢大佬
