### ISSUE TITLE
更新开箱图片出现错误

### ISSUE THREAD

**Issue by yuan488** [HibiKier/zhenxun_bot#630]
### 错误截图

![Screenshot_2022-05-25-18-41-28-402_com sonelli juicessh](https://user-images.githubusercontent.com/69119229/170244408-5ed68e00-9ef4-4ffa-adce-1852a4c553e0.jpg)

### 错误说明

使用 '更新开箱图片' 命令时出现错误

**Comment by HibiKier** [comment]
你要指定武器箱

**Comment by yuan488** [comment]
感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月28日(周六) 下午3:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HibiKier/zhenxun_bot] 更新开箱图片出现错误 (Issue #630)




 
你要指定武器箱
