### ISSUE TITLE
黑白图命令报错

### ISSUE THREAD

**Issue by StrawberryCake-Fish** [HibiKier/zhenxun_bot#631]
### 错误截图 && 日志截图
![image](https://user-images.githubusercontent.com/60875311/170245561-8ccaaada-71b7-42be-b524-b5111a68ede5.png)

### 错误说明
发送命令 黑白图 后报错

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/170254413-f79311f1-b2fe-46a8-bddb-e9ce39999b00.png)
