### ISSUE TITLE
请问我可以发布windows下真寻保姆级安装教程吗

### ISSUE THREAD

**Issue by borntree** [HibiKier/zhenxun_bot#632]
如题，可以解决很多人大部分问题
作者大大如果觉得不合适的话我就不发了=.=
@HibiKier

**Comment by qinglingyo** [comment]
非常需要

**Comment by borntree** [comment]
> 非常需要

得看看作者的意愿

**Comment by HibiKier** [comment]
可以，求之不得，但是尽量不要发在b站

**Comment by qinglingyo** [comment]
跪求，谢谢

**Comment by borntree** [comment]
> 可以，求之不得，但是尽量不要发在b站

好的，我这两天闲下来就制作一个，不会发到b站，跟风小鬼和举报小鬼太多了

**Comment by KudouShinnyan** [comment]
> 可以，求之不得，但是尽量不要发在b站

(仅仅是不要发到陈某那里吗? 刚刚在陈某家收到私信后把AC和基安发的都删了)

**Comment by sheepig1** [comment]
请问有发在哪个平台吗，非常需要QAQ

**Comment by sheepig1** [comment]
请问有发在哪个平台吗，非常需要QAQ

**Comment by sheepig1** [comment]
感谢

> > 请问有发在哪个平台吗，非常需要QAQ
> 
> #680

感谢感谢
