### ISSUE TITLE
原神玩家查询失败

### ISSUE THREAD

**Issue by Umon7275** [HibiKier/zhenxun_bot#633]
### 错误截图

_没有错误日志_ XD

### 日志截图

![image](https://user-images.githubusercontent.com/74399075/170256346-ee00c53e-5ea9-411d-b6de-a6f143a85128.png)

### 错误说明

向真寻发送 “原神玩家查询” ，真寻回复 “查询失败..”。

访问 https://api-takumi-record.mihoyo.com/game_record/app/genshin/api/character
返回 Method Not Allowed

**Comment by HibiKier** [comment]
添加cookie了吗？

**Comment by Umon7275** [comment]
> 添加cookie了吗？

已设置cookie。
在未设置cookie时，真寻回复“查询失败”；
在设置了错误的cookie时，真寻回复“please login”
在设置了正确的cookie（ _从控制台通过`document.cookie`获得的全部内容_ ）时，真寻回复“查询失败”

在保存了米游社cookie的浏览器上直接访问接口时，返回 _Method Not Allowed_
清除cookie后再访问，依然返回 _Method Not Allowed_

没有返回 _OK_ ，不知道是不是api的问题 Xp

**Comment by MingxuanGame** [comment]
可否将 log 放全一点？

**Comment by Umon7275** [comment]
> 可否将 log 放全一点？

没有更多相关的日志了


![image](https://user-images.githubusercontent.com/74399075/170286078-4d0ff528-edb2-4fa5-814f-9af64b1c5145.png)

**Comment by HibiKier** [comment]
我这里似乎并没有这样的错误？每次都无法成功吗

**Comment by HibiKier** [comment]
我这里似乎并没有这样的错误？每次都无法成功吗

**Comment by Umon7275** [comment]
拿其他人的号测试了，可以使用。
