### ISSUE TITLE
关于bot自称在哪更改

### ISSUE THREAD

**Issue by Excalibur5100** [HibiKier/zhenxun_bot#635]
![image](https://user-images.githubusercontent.com/105792144/170280844-98e5fdb8-5c77-4c03-af08-d58f159804b8.png)
在和真寻bot聊天互动时，bot有时会自称“真寻”“小真寻”啥的，在ai代码中看了下这个名称似乎是可以通过{NICKNAME}更改的，请问这应该在哪里配置呢

**Comment by ayachimako** [comment]
> ![image](https://user-images.githubusercontent.com/105792144/170280844-98e5fdb8-5c77-4c03-af08-d58f159804b8.png) 在和真寻bot聊天互动时，bot有时会自称“真寻”“小真寻”啥的，在ai代码中看了下这个名称似乎是可以通过{NICKNAME}更改的，请问这应该在哪里配置呢

安装文档里面有提到哦，在真寻目录里的.env.dev里更改

**Comment by Umon7275** [comment]
~~Big胆！居然想让真寻不再是真寻！~~

改了 _.env.dev_ 文件似乎没有用。
不过可以从最上面的 `import` 语句看到， `NICKNAME` 是从 _/configs/config.py_ 导入的。
再来看看 _configs/config.py_ 里面是怎么写的：`NICKNAME: str = "小真寻"`
是的没错！`NICKNAME` 是已经写死的！而且就算修改了 _.env.dev_ 文件再重启bot，_config.py_ 里面一个字都不会变（笑）
所以实际需要改的是config.py里的 `NICKNAME` 。

注意，修改了自称之后，有的指令并不会改变：

1. 自动更新
自动更新是在 _/plugins/check_zhenxun_update/\_\_init\_\_.py_ 中写死了 ：
`update_zhenxun = on_command("检查更新真寻", permission=SUPERUSER, priority=1, block=True)`
2. 自我介绍
自我介绍则是在 _/plugins/aconfig/\_\_init\_\_.py_ 中：
`if NICKNAME.find('真寻') != -1:`

再次注意！如果修改了1或2中的代码，下次自动更新将会重置这些代码。
之前我把俄罗斯转盘7发子弹改成通常的6发了，更新的时候忘了备份了，然后就被重置了hhh

**Comment by Excalibur5100** [comment]
感谢两位，很有帮助！另外顺便提一下，我之后在#47中看到了关于.env.dev和config里NICKNAME具体区别的解释
