### ISSUE TITLE
启动失败 疑似缺少plugins2config.yaml ？求助

### ISSUE THREAD

**Issue by wuqiufengfensi** [HibiKier/zhenxun_bot#636]
### 错误说明
\zhenxun_bot-0.1.5.6\data\configs里确实没有plugins2config.yaml
疑似缺少plugins2config.yaml ？
但是我有config.yaml

### 报错部分
[ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\if\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ddOllhLb-py3.9\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\if\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ddOllhLb-py3.9\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\if\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ddOllhLb-py3.9\lib\site-packages\starlette\routing.py", line 614, in startup
    handler()
  File "D:\zhenxubot\zhenxun_bot-0.1.5.6\basic_plugins\init_plugin_config\__init__.py", line 45, in _
    init_plugins_config(DATA_PATH)
  File "D:\zhenxubot\zhenxun_bot-0.1.5.6\basic_plugins\init_plugin_config\init_plugins_config.py", line 73, in init_plugins_config
    _data = round_trip_load(open(plugins2config_file, encoding="utf8"))
FileNotFoundError: [Errno 2] No such file or directory: 'data\\configs\\plugins2config.yaml'

05-25 21:22:11 [ERROR] uvicorn | Application startup failed. Exiting.

### 完整输出
   >D:\zhenxubot\zhenxun_bot-0.1.5.6>python bot.py
D:\zhenxubot\zhenxun_bot-0.1.5.6>python bot.py
05-25 21:21:49 [SUCCESS] nonebot | NoneBot is initializing...
05-25 21:21:49 [INFO] nonebot | Current Env: dev
05-25 21:21:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
05-25 21:21:50 [SUCCESS] nonebot | Succeeded to import "nickname"
05-25 21:21:53 [SUCCESS] nonebot | Succeeded to import "help"
05-25 21:21:53 [SUCCESS] nonebot | Succeeded to import "chat_message"
05-25 21:21:53 [SUCCESS] nonebot | Succeeded to import "chat_message_handle"
05-25 21:21:53 [SUCCESS] nonebot | Succeeded to import "chat_history"
05-25 21:21:53 [SUCCESS] nonebot | Succeeded to import "clear_data"
05-25 21:21:53 [SUCCESS] nonebot | Succeeded to import "set_admin_permissions"
05-25 21:21:53 [SUCCESS] nonebot | Succeeded to import "exec_sql"
05-25 21:21:53 [SUCCESS] nonebot | Succeeded to import "reload_setting"
05-25 21:21:54 [SUCCESS] nonebot | Succeeded to import "manager_group"
05-25 21:21:54 [SUCCESS] nonebot | Succeeded to import "update_friend_group_info"
05-25 21:21:54 [SUCCESS] nonebot | Succeeded to import "bot_friend_group"
05-25 21:21:54 [SUCCESS] nonebot | Succeeded to import "super_task_switch"
05-25 21:21:54 [SUCCESS] nonebot | Succeeded to import "super_cmd"
05-25 21:21:54 [SUCCESS] nonebot | Succeeded to import "use"
05-25 21:21:54 [SUCCESS] nonebot | Succeeded to import "shop_handle"
05-25 21:21:54 [SUCCESS] nonebot | Succeeded to import "shop_handle"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "my_props"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "buy"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "use"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "gold"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "reset_today_gold"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "shop"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "broadcast"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "super_help"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "switch_rule"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "rule"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "timing_task"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "admin_config"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "update_group_member_info"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "custom_welcome_message"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "admin_bot_manage"
05-25 21:21:55 [SUCCESS] nonebot | Succeeded to import "admin_help"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "invite_manager"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "hooks"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "apscheduler"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "scripts"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "ban"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "update_info"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "group_handle"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "init_plugin_config"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "statistics_hook"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "statistics_handle"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "statistics"
05-25 21:21:56 [SUCCESS] nonebot | Succeeded to import "update_gocqhttp"
05-25 21:21:59 [SUCCESS] nonebot | Succeeded to import "draw_card"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "send_setu"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "update_setu"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "send_setu_"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "coser"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "sign_in"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "mute"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "dialogue"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "roll"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "fudu"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "check"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "group_welcome_msg"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "nbnhhsh"
05-25 21:22:00 [SUCCESS] nonebot | Succeeded to import "poke"
05-25 21:22:01 [SUCCESS] nonebot | Succeeded to import "search_buff_skin_price"
05-25 21:22:01 [SUCCESS] nonebot | Succeeded to import "white2black_image"
05-25 21:22:01 [SUCCESS] nonebot | Succeeded to import "check_zhenxun_update"
05-25 21:22:01 [SUCCESS] nonebot | Succeeded to import "pix_update"
05-25 21:22:01 [SUCCESS] nonebot | Succeeded to import "pix_show_info"
05-25 21:22:01 [SUCCESS] nonebot | Succeeded to import "pix"
05-25 21:22:02 [SUCCESS] nonebot | Succeeded to import "pix_add_keyword"
05-25 21:22:02 [SUCCESS] nonebot | Succeeded to import "pix_pass_del_keyword"
05-25 21:22:02 [SUCCESS] nonebot | Succeeded to import "pix_gallery"
05-25 21:22:02 [SUCCESS] nonebot | Succeeded to import "parse_bilibili_json"
05-25 21:22:02 [SUCCESS] nonebot | Succeeded to import "fake_msg"
05-25 21:22:02 [SUCCESS] nonebot | Succeeded to import "gold_redbag"
05-25 21:22:02 [SUCCESS] nonebot | Succeeded to import "ai"
05-25 21:22:02 [SUCCESS] nonebot | Succeeded to import "translate"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "word_hanlde"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "message_handle"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "model"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "word_bank"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "update_picture"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "what_anime"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "pid_search"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "one_friend"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "music"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "upload_image"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "send_image"
05-25 21:22:03 [SUCCESS] nonebot | Succeeded to import "delete_image"
05-25 21:22:04 [SUCCESS] nonebot | Succeeded to import "move_image"
05-25 21:22:04 [SUCCESS] nonebot | Succeeded to import "image_management"
05-25 21:22:04 [SUCCESS] nonebot | Succeeded to import "yiqing"
05-25 21:22:04 [SUCCESS] nonebot | Succeeded to import "pixiv_rank_search"
05-25 21:22:04 [SUCCESS] nonebot | Succeeded to import "quotations"
05-25 21:22:04 [SUCCESS] nonebot | Succeeded to import "web_ui"
05-25 21:22:04 [SUCCESS] nonebot | Succeeded to import "open_cases"
05-25 21:22:04 [SUCCESS] nonebot | Succeeded to import "aconfig"
05-25 21:22:05 [SUCCESS] nonebot | Succeeded to import "russian"
05-25 21:22:05 [SUCCESS] nonebot | Succeeded to import "epic"
05-25 21:22:05 [SUCCESS] nonebot | Succeeded to import "black_word"
05-25 21:22:05 [SUCCESS] nonebot | Succeeded to import "wbtop"
05-25 21:22:05 [SUCCESS] nonebot | Succeeded to import "jitang"
05-25 21:22:05 [SUCCESS] nonebot | Succeeded to import "cover"
05-25 21:22:05 [SUCCESS] nonebot | Succeeded to import "comments_163"
05-25 21:22:05 [SUCCESS] nonebot | Succeeded to import "poetry"
05-25 21:22:05 [SUCCESS] nonebot | Succeeded to import "alapi"
05-25 21:22:06 [SUCCESS] nonebot | Succeeded to import "word_clouds"
05-25 21:22:06 [SUCCESS] nonebot | Succeeded to import "search_image"
05-25 21:22:07 [SUCCESS] nonebot | Succeeded to import "query_resource_points"
05-25 21:22:07 [SUCCESS] nonebot | Succeeded to import "almanac"
05-25 21:22:07 [SUCCESS] nonebot | Succeeded to import "material_remind"
05-25 21:22:07 [SUCCESS] nonebot | Succeeded to import "reset_today_query_user_data"
05-25 21:22:07 [SUCCESS] nonebot | Succeeded to import "genshin_sign"
05-25 21:22:07 [SUCCESS] nonebot | Succeeded to import "query_memo"
05-25 21:22:07 [SUCCESS] nonebot | Succeeded to import "resin_remind"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "bind"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "query_memo"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "query_role"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "query_user"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "genshin"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "my_info"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "send_dinggong_voice"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "weather"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "bt"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "bilibili_sub"
05-25 21:22:08 [SUCCESS] nonebot | Succeeded to import "search_anime"
05-25 21:22:09 [SUCCESS] nonebot | Succeeded to import "luxun"
05-25 21:22:09 [SUCCESS] nonebot | Succeeded to import "withdraw"
05-25 21:22:09 [SUCCESS] nonebot | Succeeded to import "about"
05-25 21:22:09 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
05-25 21:22:09 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
05-25 21:22:09 [SUCCESS] nonebot | Succeeded to import "auth_hook"
05-25 21:22:09 [SUCCESS] nonebot | Succeeded to import "ban_hook"
05-25 21:22:09 [SUCCESS] nonebot | Succeeded to import "task_hook"
05-25 21:22:09 [SUCCESS] nonebot | Succeeded to import "other_hook"
05-25 21:22:09 [SUCCESS] nonebot | Running NoneBot...
05-25 21:22:09 [INFO] uvicorn | Started server process [17916]
05-25 21:22:09 [INFO] uvicorn | Waiting for application startup.
05-25 21:22:11 [INFO] services | Database loaded successfully!
C:\Users\if\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ddOllhLb-py3.9\lib\site-packages\apscheduler\util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
05-25 21:22:11 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-25 21:22:11 [INFO] basic_plugins | 已成功加载 60 个非限制插件.
05-25 21:22:11 [INFO] utils | 已成功加载 5 个Cd限制.
05-25 21:22:11 [INFO] utils | 已成功加载 12 个Block限制.
05-25 21:22:11 [INFO] utils | 已成功加载 1 个Count限制.
05-25 21:22:11 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\if\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ddOllhLb-py3.9\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\if\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ddOllhLb-py3.9\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\if\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ddOllhLb-py3.9\lib\site-packages\starlette\routing.py", line 614, in startup
    handler()
  File "D:\zhenxubot\zhenxun_bot-0.1.5.6\basic_plugins\init_plugin_config\__init__.py", line 45, in _
    init_plugins_config(DATA_PATH)
  File "D:\zhenxubot\zhenxun_bot-0.1.5.6\basic_plugins\init_plugin_config\init_plugins_config.py", line 73, in init_plugins_config
    _data = round_trip_load(open(plugins2config_file, encoding="utf8"))
FileNotFoundError: [Errno 2] No such file or directory: 'data\\\configs\\\plugins2config.yaml'

05-25 21:22:11 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by HibiKier** [comment]
将你config.yaml改个名在启动试试

**Comment by wuqiufengfensi** [comment]
仍然不行，在zhenxun_bot-0.1.5.6\data\configs\plugins目录下重新生成了新的config.yaml但是\data\configs\plugins中仍然没有\data\configs\plugins，报错相同
我曾尝试过删除整个configs，结果仍然不变。
![image](https://user-images.githubusercontent.com/81866991/170392828-65ac073e-075b-4bd5-8c78-4c45f5fe4809.png)

**Comment by HibiKier** [comment]
插件是全部加载成功的吗？有什么报错吗？

**Comment by HibiKier** [comment]
插件是全部加载成功的吗？有什么报错吗？

**Comment by HibiKier** [comment]
插件是全部加载成功的吗？有什么报错吗？

**Comment by wuqiufengfensi** [comment]
![image](https://user-images.githubusercontent.com/81866991/170401292-d8c2bf08-2d45-4b45-bf06-0e5f1aa68c3f.png)
您好！因为一直没有产生所需yaml，所以我比对原压缩包以后，发现数据库配置(config.py)最下面的生成文件代码因不知原因被修改！所以我把压缩包里的代码复制了进去，解决了这个问题。感谢您的帮助😁
