### ISSUE TITLE
运行bot出现以下错误。。

### ISSUE THREAD

**Issue by hangbulang** [HibiKier/zhenxun_bot#639]
PS D:\实验\zhenxun_bot-main> poetry shell
Spawning shell within C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-JTb6ZFMm-py3.9
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS D:\实验\zhenxun_bot-main> python bot.py
Traceback (most recent call last):
  File "D:\实验\zhenxun_bot-main\bot.py", line 3, in <module>
    from services.db_context import init, disconnect
ModuleNotFoundError: No module named 'services'

**Comment by Umon7275** [comment]
模块缺失。通常可以通过 `pip install module_name` 来解决。
这里则应该是 `pip install services`

**Comment by hangbulang** [comment]
PS D:\实验\zhenxun_bot-main>  pip install module_name
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting module_name
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/38/2b/d1aa59346de1dbfe187341bf1893bd6585092d63f8338b56902c8d59497b/module_name-0.5.1.tar.gz (3.1 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for module_name, since package 'wheel' is not installed.
Installing collected packages: module_name
  Running setup.py install for module_name ... done
Successfully installed module_name-0.5.1
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'C:\Users\86150\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
PS D:\实验\zhenxun_bot-main> pip install services
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting services
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a5/07/742d5ee1d40edd462ec1e4fb8aec250ac4ebaa5fc20c7f496a9eeb57a251/services-0.1.1-py2.py3-none-any.whl (3.9 kB)
Collecting Click>=6.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl (96 kB)
     ---------------------------------------- 96.6/96.6 KB 1.4 MB/s eta 0:00:00
Collecting colorama
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Installing collected packages: colorama, Click, services
Successfully installed Click-8.1.3 colorama-0.4.4 services-0.1.1
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'C:\Users\86150\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
PS D:\实验\zhenxun_bot-main> poetry shell
Spawning shell within C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-JTb6ZFMm-py3.9
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS D:\实验\zhenxun_bot-main> python bot.py
Traceback (most recent call last):
  File "D:\实验\zhenxun_bot-main\bot.py", line 3, in <module>
    from services.db_context import init, disconnect
ModuleNotFoundError: No module named '

**Comment by hangbulang** [comment]
PS D:\实验\zhenxun_bot-main>  pip install module_name
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting module_name
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/38/2b/d1aa59346de1dbfe187341bf1893bd6585092d63f8338b56902c8d59497b/module_name-0.5.1.tar.gz (3.1 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for module_name, since package 'wheel' is not installed.
Installing collected packages: module_name
  Running setup.py install for module_name ... done
Successfully installed module_name-0.5.1
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'C:\Users\86150\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
PS D:\实验\zhenxun_bot-main> pip install services
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting services
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a5/07/742d5ee1d40edd462ec1e4fb8aec250ac4ebaa5fc20c7f496a9eeb57a251/services-0.1.1-py2.py3-none-any.whl (3.9 kB)
Collecting Click>=6.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl (96 kB)
     ---------------------------------------- 96.6/96.6 KB 1.4 MB/s eta 0:00:00
Collecting colorama
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Installing collected packages: colorama, Click, services
Successfully installed Click-8.1.3 colorama-0.4.4 services-0.1.1
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'C:\Users\86150\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
PS D:\实验\zhenxun_bot-main> poetry shell
Spawning shell within C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-JTb6ZFMm-py3.9
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS D:\实验\zhenxun_bot-main> python bot.py
Traceback (most recent call last):
  File "D:\实验\zhenxun_bot-main\bot.py", line 3, in <module>
    from services.db_context import init, disconnect
ModuleNotFoundError: No module named 'services'

**Comment by hangbulang** [comment]
我猜有可能我的文件下载时损坏了。。。

**Comment by hangbulang** [comment]
> 模块缺失。通常可以通过 `pip install module_name` 来解决。 这里则应该是 `pip install services`

PS D:\实验\zhenxun_bot-main> pip install module_name
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting module_name
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/38/2b/d1aa59346de1dbfe187341bf1893bd6585092d63f8338b56902c8d59497b/module_name-0.5.1.tar.gz (3.1 kB)
Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for module_name, since package 'wheel' is not installed.
Installing collected packages: module_name
Running setup.py install for module_name ... done
Successfully installed module_name-0.5.1
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'C:\Users\86150\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
PS D:\实验\zhenxun_bot-main> pip install services
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting services
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a5/07/742d5ee1d40edd462ec1e4fb8aec250ac4ebaa5fc20c7f496a9eeb57a251/services-0.1.1-py2.py3-none-any.whl (3.9 kB)
Collecting Click>=6.0
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl (96 kB)
---------------------------------------- 96.6/96.6 KB 1.4 MB/s eta 0:00:00
Collecting colorama
Downloading https://pypi.tuna.tsinghua.edu.cn/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Installing collected packages: colorama, Click, services
Successfully installed Click-8.1.3 colorama-0.4.4 services-0.1.1
WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
You should consider upgrading via the 'C:\Users\86150\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
PS D:\实验\zhenxun_bot-main> poetry shell
Spawning shell within C:\Users\86150\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-JTb6ZFMm-py3.9
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS D:\实验\zhenxun_bot-main> python bot.py
Traceback (most recent call last):
File "D:\实验\zhenxun_bot-main\bot.py", line 3, in
from services.db_context import init, disconnect
ModuleNotFoundError: No module named 'services'

**Comment by Umon7275** [comment]
你使用的pip对应的Python版本是多少，用 `pip -V` 查看版本。
也许是中文路径影响了环境配置的路径，也许也不会影响到。不过建议一般对于程序相关的，尽量不使用中文。
其他的我也不知道了，我不是很懂Python。

**Comment by HibiKier** [comment]
services是项目中的，可能事文件无了

**Comment by hangbulang** [comment]
下载的时候文件损坏了
