### ISSUE TITLE
小真寻0.1.5.6版的B站转发解析为什么被移除了？

### ISSUE THREAD

**Issue by Umon7275** [HibiKier/zhenxun_bot#640]
### 真寻版本：0.1.5.6

我注意到了小真寻不再解析群友转发到群里的视频。
查看parse_bilibili_json.py后，发现全被注释掉了。
请问这个功能是会影响到其他功能的运行嘛？

**Comment by HibiKier** [comment]
影响到playwright运行了 ，权衡利弊之后暂时注释等后续新的解决办法
