### ISSUE TITLE
服务器延迟测试失败（小白不是很看的懂）

### ISSUE THREAD

**Issue by A-joke** [HibiKier/zhenxun_bot#641]
![%9171U@X(~_YL771SELI9J6](https://user-images.githubusercontent.com/80505888/170349222-0d8606b4-29bf-48ad-ba69-0b2c5694a620.png)

**Comment by HibiKier** [comment]
把你bot开启来

**Comment by A-joke** [comment]
![image](https://user-images.githubusercontent.com/80505888/170425490-a76c55fd-7f93-4698-b2bb-a62b8e7bbd88.png)

**Comment by A-joke** [comment]
一打开就说我代码出错

**Comment by HibiKier** [comment]
因为你用的py2
