### ISSUE TITLE
建议，在群里和真寻聊天一直需要@很难受aaa

### ISSUE THREAD

**Issue by 52llc** [HibiKier/zhenxun_bot#644]
下面是我的一个想法：
能不能给真寻那个ai改成不用@，通过机器人名字唤出，然后机器人获取群成员的qq，进行免@ai回复，十秒无回复，需要重新唤出。

**Comment by SinKy-Yan** [comment]
这是由插件自己设置需不需要at机器人来触发的，跟bot没关系
https://hibikier.github.io/zhenxun_bot/docs/development_doc/plugins.html#plugin-cd-limit

**Comment by 52llc** [comment]
> 这是由插件自己设置需不需要at机器人来触发的，跟bot没关系 https://hibikier.github.io/zhenxun_bot/docs/development_doc/plugins.html#plugin-cd-limit
具体怎样设置啊，那个源码我看不懂

**Comment by SuLiuming** [comment]
通过机器人名字唤出 默认我记得是开启的 关键字你可以在.env.dev文件中的NICKNAME就是  免at回复暂时没注意在哪设置
