### ISSUE TITLE
昵称系统修改昵称的功能无法使用

### ISSUE THREAD

**Issue by Fordzd** [HibiKier/zhenxun_bot#645]
### 错误截图

![image](https://user-images.githubusercontent.com/63229644/170410869-de4dfa4f-da87-459e-8478-fe33536a3bdb.png)

### 日志截图

![image](https://user-images.githubusercontent.com/63229644/170410982-25b507a6-9181-4493-a745-dfba15770129.png)

### 错误说明

根据日志我框选的部分看到已经触发了指令，但是昵称并没有更改，修改昵称的指令真寻都没有回应，但是其他昵称系统中的指令都正常。

**Comment by HibiKier** [comment]
at他，如果有些功能不能触发，你就at她再试试

**Comment by Fordzd** [comment]
目前已经通过修改数据库的形式改变了昵称，机器人就我一个人用，影响不是很大。
![Snipaste_2022-05-26_13-02-35](https://user-images.githubusercontent.com/63229644/170419770-662b02a7-ae70-4934-bada-6ecb81bb28af.png)
![Snipaste_2022-05-26_13-02-49](https://user-images.githubusercontent.com/63229644/170419798-8e98e02d-7ccd-4115-87bf-de52e0df2310.png)


还是希望有大佬帮忙看看问题出在哪里。
