### ISSUE TITLE
群内使用B站订阅功能没有任何反应

### ISSUE THREAD

**Issue by zhao-xp** [HibiKier/zhenxun_bot#646]
### 日志截图
![日志](https://user-images.githubusercontent.com/58055920/170410975-ff4ab53c-7b39-4f3f-bcc7-bfd193756e95.png)

### 错误说明
在群内使用B站订阅功能没有任何反应,群权限是9,看日志好像是没触发订阅插件?不懂Python,是我哪里设置有问题吗?求解答

**Comment by HibiKier** [comment]
B站订阅只是插件名字，具体看帮助
