### ISSUE TITLE
救命！

### ISSUE THREAD

**Issue by yangshiling** [HibiKier/zhenxun_bot#648]
114514

**Comment by kitUIN** [comment]
救命!

**Comment by MingxuanGame** [comment]
![65P{)T`GEM(RQR$B%97_$V7](https://user-images.githubusercontent.com/68982190/170416112-8ebe77eb-6dba-42c4-a7b8-e4e6e261d898.jpg)
先把钱交了

**Comment by Copaan** [comment]
这个是哪里出问题了呢[拍屏]

**Comment by yangshiling** [comment]
114514
