### ISSUE TITLE
新增plugins2count.yaml配置导致webUI错误

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#651]
### 系统版本：
![image](https://user-images.githubusercontent.com/105090141/170415727-53df7f82-2e1f-4aa0-aafd-e8a3b09f82f6.png)

### 错误截图
![image](https://user-images.githubusercontent.com/105090141/170415830-4fc6275f-ec88-454d-bfbb-5f334e03a882.png)

### 日志截图
![image](https://user-images.githubusercontent.com/105090141/170415895-e90773ce-d201-495d-9456-eddc5982db05.png)

### 配置截图
![image](https://user-images.githubusercontent.com/105090141/170415984-e2158ce4-3eb6-4fc7-b5c1-0f0d7c611ec2.png)

### 错误说明
在plugins2count.yaml里新增插件配置后webUI插件列表-普通插件无法读取，删除plugins2count.yaml里的所有配置后能恢复正常，图中的3个插件都单独试过均会引起错误

**Comment by HibiKier** [comment]
更新一下
