### ISSUE TITLE
关于开关群功能的问题

### ISSUE THREAD

**Issue by winseven2018** [HibiKier/zhenxun_bot#652]
### 错误截图

![image](https://user-images.githubusercontent.com/52370126/170417091-db14dfd5-ddcf-4806-8b21-4c0155b2e730.png)
![image](https://user-images.githubusercontent.com/52370126/170417244-82612049-abec-4f68-834d-933726387804.png)

### 日志截图

![image](https://user-images.githubusercontent.com/52370126/170417506-c9f4e9b2-078a-4716-970c-ee80a2a54ead.png)

### 错误说明

我在Plugin2Settings.yaml文件中将epic项的default_status设置为了false，但依旧没有关闭该功能？请问正确关闭功能的方法？
还有如何取消掉每天早上自动发送的原神黄历消息以及epic免费消息，我在config.yaml文件中的task项中设置对应值为false后好像也没能正常关闭？

**Comment by HibiKier** [comment]
default_status和config.yaml只影响之后加的群，管理员帮助 都已经告诉你命令了，另外不要把cmd修改成 关闭xxx 开启xxx
