### ISSUE TITLE
打开bot时出错求大佬解答

### ISSUE THREAD

**Issue by A-joke** [HibiKier/zhenxun_bot#654]
![image](https://user-images.githubusercontent.com/80505888/170430932-2953acb3-a48b-403d-93ff-a8b7598cc66d.png)

**Comment by misakamikoto2019** [comment]
您好，我在学习您们的代码中，在使用pycharm编译器（编译器提示我用poerty.yaml创建虚拟环境，但创建失败了）尝试新增一个模块后，重启后报错nomodelfound，如下图，（之前真寻是正常的）猜测是poetry出现问题，但又不知如何解决，希望大佬给一些指点
![image](https://user-images.githubusercontent.com/103396762/170664077-7b460ded-cd98-4ae6-a283-9f6a63b20c52.png)

![image](https://user-images.githubusercontent.com/103396762/170663548-c2a9b117-b2e5-4182-a9f8-05df5ac2718e.png)

**Comment by MingxuanGame** [comment]
> 您好，我在学习您们的代码中，在使用pycharm编译器（编译器提示我用poerty.yaml创建虚拟环境，但创建失败了）尝试新增一个模块后，重启后报错nomodelfound，如下图，（之前真寻是正常的）猜测是poetry出现问题，但又不知如何解决，希望大佬给一些指点 ![image](https://user-images.githubusercontent.com/103396762/170664077-7b460ded-cd98-4ae6-a283-9f6a63b20c52.png)
> 
> ![image](https://user-images.githubusercontent.com/103396762/170663548-c2a9b117-b2e5-4182-a9f8-05df5ac2718e.png)

不建议使用 pycharm 的安装，请打开 pycharm 的终端输入文档里面的命令安装

**Comment by HibiKier** [comment]
在powershell中
poetry install 
poetry shell

**Comment by misakamikoto2019** [comment]
感谢大佬回复，已解决，原因是pycharm里环境是Python3.10，修改成3.9后运行Poetry就一切恢复正常了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月28日(周六) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HibiKier/zhenxun_bot] 打开bot时出错求大佬解答 (Issue #654)




 
在powershell中
 poetry install
 poetry shell

**Comment by misakamikoto2019** [comment]
已收到，感谢大佬回复！我在去尝试一下！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 下午4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 打开bot时出错求大佬解答 (Issue #654)





  
您好，我在学习您们的代码中，在使用pycharm编译器（编译器提示我用poerty.yaml创建虚拟环境，但创建失败了）尝试新增一个模块后，重启后报错nomodelfound，如下图，（之前真寻是正常的）猜测是poetry出现问题，但又不知如何解决，希望大佬给一些指点 
 

  
不建议使用 pycharm 的安装，请打开 pycharm 的终端输入文档里面的命令安装
