### ISSUE TITLE
戳一戳回复图片时尝试读取不存在的图片

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#655]
### 系统版本：
![image](https://user-images.githubusercontent.com/105090141/170415727-53df7f82-2e1f-4aa0-aafd-e8a3b09f82f6.png)

### 错误截图
![尝试读取4jpg](https://user-images.githubusercontent.com/105090141/170431283-bf10b97c-9a38-4c10-b835-0e2a7971ea31.png)

### 错误说明
![image](https://user-images.githubusercontent.com/105090141/170431697-3c724370-2581-46f4-b0b3-90ab7b2e2193.png)
如图，文件夹内有4张图片但没有4.jpg

**Comment by HibiKier** [comment]
7ab185f7d787c4e1792f73d685e6daf704b4335e 图库没空时略过发图转为下继续判断

**Comment by HibiKier** [comment]
24d9ec2b759cdf722d32474d6e855d581fd9ddb6
