### ISSUE TITLE
请问black_word插件的敏感词可以自行添加吗

### ISSUE THREAD

**Issue by DTR3912** [HibiKier/zhenxun_bot#656]
### 真寻版本：0.1.5.4

我在此处添加后重启bot后@真寻，输入含有新添敏感词的内容，真寻没有检测到并记录。
![屏幕截图 2022-05-26 145232](https://user-images.githubusercontent.com/79055835/170435242-c5d2a512-d96e-4ec1-88aa-ab16243b2db3.jpg)
![屏幕截图 2022-05-26 145032](https://user-images.githubusercontent.com/79055835/170435353-f2d6525b-6779-49e6-9adf-202a340cd417.jpg)

**Comment by HibiKier** [comment]
新的敏感词请在data/black_word目录下的文件中添加

**Comment by DTR3912** [comment]
谢谢
