### ISSUE TITLE
linux 执行 playwright install-deps chromium 报错

### ISSUE THREAD

**Issue by qiangzaiqaq** [HibiKier/zhenxun_bot#659]
### 错误截图

![image](https://user-images.githubusercontent.com/69947042/170460357-e2d86185-d62e-45e5-bf1f-99805b8c69ba.png)

### 错误说明
Installing Ubuntu dependencies...
sh: apt-get: command not found

**Comment by HibiKier** [comment]
centos要自己安装依赖吧

**Comment by HiDolen** [comment]
centos 默认没有 apt-get，要装一个 apt-get

**Comment by gentleman6663** [comment]
centos用的是yum，ubuntu用的是apt-get，我用的centos8这步也报错，但是我没管，暂时没发现会影响使用

**Comment by qiangzaiqaq** [comment]
> centos用的是yum，ubuntu用的是apt-get，我用的centos8这步也报错，但是我没管，暂时没发现会影响使用

但是我不管这一步，往后python3 bot 不会生成配置文件 咋回事 还有这import的报错 看报错就是没有那些配置

**Comment by HibiKier** [comment]
为什么不发日志呢

**Comment by HibiKier** [comment]
> > centos用的是yum，ubuntu用的是apt-get，我用的centos8这步也报错，但是我没管，暂时没发现会影响使用
> 
> 但是我不管这一步，往后python3 bot 不会生成配置文件 咋回事 还有这import的报错 看报错就是没有那些配置

日志

**Comment by qiangzaiqaq** [comment]
> > > centos用的是yum，ubuntu用的是apt-get，我用的centos8这步也报错，但是我没管，暂时没发现会影响使用
> > 
> > 
> > 但是我不管这一步，往后python3 bot 不会生成配置文件 咋回事 还有这import的报错 看报错就是没有那些配置
> 
> 日志

![image](https://user-images.githubusercontent.com/69947042/172312624-62e94302-7e63-4e8e-a230-1ee533a0cd80.png)
