### ISSUE TITLE
启动chromium发生错误

### ISSUE THREAD

**Issue by zhao-xp** [HibiKier/zhenxun_bot#662]
### 错误截图

![报错信息](https://user-images.githubusercontent.com/58055920/170467377-786560cd-3da1-4ce5-af44-3eb538f2806b.png)

### 日志截图

![错误](https://user-images.githubusercontent.com/58055920/170467404-8b1232ba-3feb-4ca7-a5fa-19bae3bf5345.png)

### 错误说明

今天执行poetry install更新依赖,成功启动但使用时出现上图报错信息,再次执行playwright install chromium却提示不支持,但是前几天初次安装时却没有这个提示,请问有什么解决办法吗,还是只能把服务器镜像换成Ubuntu,目前使用的是CentOS 7.9

**Comment by HibiKier** [comment]
centos要自己安装依赖吧
