### ISSUE TITLE
关于【磁力搜索(bt)】插件，请及时更新

### ISSUE THREAD

**Issue by AreCie** [HibiKier/zhenxun_bot#663]
关于【磁力搜索(bt)】插件，经测试，原接口地址【http://www.eclzz.mobi/】已被弃用，新地址为【http://www.eclzz.win/】，请及时更新插件的接口地址

![image](https://user-images.githubusercontent.com/41849402/170472334-a5a5c14a-6165-4ebc-a138-0668388691e0.png)
![image](https://user-images.githubusercontent.com/41849402/170472415-b3f5039b-f748-4285-ac6a-ffabd466854c.png)
![image](https://user-images.githubusercontent.com/41849402/170472509-de593a58-ed0d-4395-aec6-b757dd622783.png)
【http://www.eclzz.mobi/】被重定向到【http://www.eclzz.win/】

**Comment by HibiKier** [comment]
https://github.com/HibiKier/zhenxun_bot/pull/668
