### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#665]
### 系统版本：
版本	Windows 10 家庭版
版本号	21H2
安装日期	‎2022/‎5/‎22
操作系统内部版本	19044.1706
体验	Windows Feature Experience Pack 120.2212.4170.0
### 错误截图
![寄了](https://user-images.githubusercontent.com/105090141/170474158-8ed7341d-b299-466f-92c8-176bbc217efc.png)

### 日志截图
![日志](https://user-images.githubusercontent.com/105090141/170474189-8699db2c-0ea2-47a9-9d2a-b6408a245d70.png)

### 错误说明
一页下来全是这样的报错，按照[MockingBird 语音](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/tree/master/mockingbird)里的食用方法安装好后就成这样了

**Comment by HibiKier** [comment]
plugin2config.yaml估计被清空了
