### ISSUE TITLE
签到之后后台报错，没有图片消息发出来。

### ISSUE THREAD

**Issue by saber20200** [HibiKier/zhenxun_bot#666]
### 错误截图
![image](https://user-images.githubusercontent.com/76509197/170481559-3ee76335-4f29-499b-9ba7-e36738726a66.png)
![image](https://user-images.githubusercontent.com/76509197/170481599-2e0073c7-cda5-46cd-b9d5-e527b32f7549.png)

### 错误说明
在群里面发送签到之后在后台提示这些报错，是因为python版本过高吗？我的python版本是3.9.13.

**Comment by saber20200** [comment]
> ### 系统版本：Ubuntu 20.04
> ### 真寻版本：0.1.5.6
> ### 错误截图
> ![image](https://user-images.githubusercontent.com/76509197/170481559-3ee76335-4f29-499b-9ba7-e36738726a66.png) ![image](https://user-images.githubusercontent.com/76509197/170481599-2e0073c7-cda5-46cd-b9d5-e527b32f7549.png)
> 
> ### 错误说明
> 在群里面发送签到之后在后台提示这些报错，是因为python版本过高吗？我的python版本是3.9.13.
在go-cqhttp里面显示[2022-05-26 20:05:37] [WARNING]: 监听反向WS Universal时出现错误: websocket: close 1006 (abnormal closure): unexpected EOF 这个错误

**Comment by HibiKier** [comment]
3.9.13是新的吧，没遇到过这种问题，试试降低版本
