### ISSUE TITLE
web ui错误

### ISSUE THREAD

**Issue by 52llc** [HibiKier/zhenxun_bot#674]
### 错误截图
![image](https://user-images.githubusercontent.com/95897275/170504744-6153642b-703f-4975-acf1-b065eb445ccc.png)

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by SinGone949** [comment]
#267 
可能和这个是一个问题？

**Comment by 52llc** [comment]
> #267 可能和这个是一个问题？

![image](https://user-images.githubusercontent.com/95897275/170515974-fe46059f-cd22-42a2-8a10-96bdc8909e9c.png)
试了一下报错了

**Comment by SinGone949** [comment]
应该是网络问题，建议扶墙或者改用国内镜像
