### ISSUE TITLE
poetry依赖安装失败以及插件加载失败

### ISSUE THREAD

**Issue by Akihiiiiii** [HibiKier/zhenxun_bot#675]
### 错误截图

![poetry](https://user-images.githubusercontent.com/106335240/170526165-43707fec-ed3c-4d1d-b7f7-e7591b000ff0.png)
![插件1](https://user-images.githubusercontent.com/106335240/170526176-d0dd569d-5e5f-4be6-bbd3-1cd1773e3998.png)

![插件2](https://user-images.githubusercontent.com/106335240/170526182-f35d730d-8564-446b-b18e-6813becb7725.png)

### 日志截图

![日志](https://user-images.githubusercontent.com/106335240/170526562-9ab597f3-3641-46f6-8a71-4a9576f0b23c.png)

### 错误说明

插件基本都是failed to import
第一次接触python和nonebot 不是很懂 麻烦大佬教下

**Comment by Akihiiiiii** [comment]
> 

系统版本是windows2012 server

**Comment by HibiKier** [comment]
你看看config.py代码是否完整

**Comment by Akihiiiiii** [comment]
谢谢 确实是这个的问题 我替换了下文件就好了 麻烦了

**Comment by Akihiiiiii** [comment]
> 你看看config.py代码是否完整
![QQ图片20220527095524](https://user-images.githubusercontent.com/106335240/170613097-3daedca5-066a-4797-bf07-679a0006c965.png)
这个报错是网络问题吗 麻烦请教下怎么解决

**Comment by Sakuracio** [comment]
出国
