### ISSUE TITLE
微博热搜问题

### ISSUE THREAD

**Issue by SSRanh** [HibiKier/zhenxun_bot#676]
微博热搜提示TypeError: argument of type 'int' is not iterable
错误提示
![image](https://user-images.githubusercontent.com/106005353/170527647-1a4f3082-0f1c-4aae-b22c-163259fb482f.png)
05-27 00:03:17 [ERROR] nonebot | Running matcher <Matcher from plugins.alapi.wbtop, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):

  File "bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7f0199cad310>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f019b4bedc0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7f0198765af0>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f0198765ca0>
    └ <uvicorn.server.Server object at 0x7f017b56fd00>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f0198765d30>
           │       │   └ <uvicorn.server.Server object at 0x7f017b56fd00>
           │       └ <function run at 0x7f019ad87670>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f017ac75840>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _event_to_me at 0x7f0199c4f670>: <Task finished name='Task-42114' coro=<_event_to_me() done, defined at /root/.cac...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f017575c3a0>
          │       │   │    │      └ {'_prefix': {'command': ('微博热搜',), 'raw_command': '微博热搜', 'command_arg': []}}
          │       │   │    └ PrivateMessageEvent(time=1653580997, self_id=2737435598, post_type='message', sub_type='friend', user_id=1410221813, message_...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f0175627670>
          │       └ <function Matcher.run at 0x7f0199c4f310>
          └ <Matcher from plugins.alapi.wbtop, type=message, priority=5, temp=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _event_to_me at 0x7f0199c4f670>: <Task finished name='Task-42114' coro=<_event_to_me() done, defined at /root/.cac...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f017575c3a0>
          │    │          │    │      └ {'_prefix': {'command': ('微博热搜',), 'raw_command': '微博热搜', 'command_arg': []}}
          │    │          │    └ PrivateMessageEvent(time=1653580997, self_id=2737435598, post_type='message', sub_type='friend', user_id=1410221813, message_...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f0175627670>
          │    └ <function Matcher.simple_run at 0x7f0199c4f280>
          └ <Matcher from plugins.alapi.wbtop, type=message, priority=5, temp=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7f017fd14310>, params=[ModelField(name='event', type=MessageEvent, required=True), ModelFiel...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'event': PrivateMessageEvent(time=1653580997, self_id=2737435598, post_type='message', sub_type='friend', user_id=1410221813...
                 │    └ <function _ at 0x7f017fd14310>
                 └ <Dependent call=<function _ at 0x7f017fd14310>, params=[ModelField(name='event', type=MessageEvent, required=True), ModelFiel...

  File "/home/ubuntu/zhenxun_bot-main/plugins/alapi/wbtop.py", line 49, in _
    img = await asyncio.get_event_loop().run_in_executor(
                │       └ <built-in function get_event_loop>
                └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>

  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None

  File "/home/ubuntu/zhenxun_bot-main/plugins/alapi/_data_source.py", line 48, in gen_wbtop_pic
    bk.paste(text_bk, (0, 280))
    │  │     └ <utils.image_utils.BuildImage object at 0x7f01758742e0>
    │  └ <function BuildImage.paste at 0x7f0185d07820>
    └ <utils.image_utils.BuildImage object at 0x7f01758749d0>

  File "/home/ubuntu/zhenxun_bot-main/utils/image_utils.py", line 418, in text
    self.draw.text(pos, text, fill=fill, font=self.font)
    │    │    │    │    │          │          │    └ <PIL.ImageFont.FreeTypeFont object at 0x7f0175877820>
    │    │    │    │    │          │          └ <utils.image_utils.BuildImage object at 0x7f0175877be0>
    │    │    │    │    │          └ (0, 0, 0)
    │    │    │    │    └ 2887139
    │    │    │    └ (580, 4)
    │    │    └ <function ImageDraw.text at 0x7f0185d09ca0>
    │    └ <PIL.ImageDraw.ImageDraw object at 0x7f017587ad00>
    └ <utils.image_utils.BuildImage object at 0x7f0175877be0>

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/PIL/ImageDraw.py", line 393, in text
    if self._multiline_check(text):
       │    │                └ 2887139
       │    └ <function ImageDraw._multiline_check at 0x7f0185d09b80>
       └ <PIL.ImageDraw.ImageDraw object at 0x7f017587ad00>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-TQHA6eKj-py3.8/lib/python3.8/site-packages/PIL/ImageDraw.py", line 368, in _multiline_check
    return split_character in text
           │                  └ 2887139
           └ b'\n'

TypeError: argument of type 'int' is not iterable

**Comment by HibiKier** [comment]
更新代码

**Comment by McElaga** [comment]
我也遇到了,在\plugins\alapi\_data_source.py 48行左右,把hot这个对象变成str就行:比如hot=str(.....)

**Comment by XKaguya** [comment]
> hot=str(.....)

能细说一下是怎么改的吗？我也有这个问题

**Comment by McElaga** [comment]
> 

![image](https://user-images.githubusercontent.com/105900675/170627571-e2ba3829-994d-4277-b73a-c67cc8bf21f2.png)
改为:
![image](https://user-images.githubusercontent.com/105900675/170627669-10212a9d-e1ef-4a02-bf49-cf374df8dd16.png)

**Comment by XKaguya** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/105900675/170627571-e2ba3829-994d-4277-b73a-c67cc8bf21f2.png) 改为: ![image](https://user-images.githubusercontent.com/105900675/170627669-10212a9d-e1ef-4a02-bf49-cf374df8dd16.png)

解决了，谢谢回复

**Comment by SSRanh** [comment]
解决了，谢谢大佬们
