### ISSUE TITLE
关于使用docker部署后，真寻回复消息是图片时会报错，能正常回复文字

### ISSUE THREAD

**Issue by JHDZ33** [HibiKier/zhenxun_bot#677]
### 错误截图
![微信图片_20220526235610](https://user-images.githubusercontent.com/78144612/170526453-1719d9c2-6add-426d-a324-e60f1f29ef7b.png)
go-cqhttp：
![图片](https://user-images.githubusercontent.com/78144612/170526554-c1ed3c4f-5961-439d-95dd-8849b8abaf0f.png)

### 日志截图
![图片](https://user-images.githubusercontent.com/78144612/170529214-7747c345-19c2-4c29-b6de-5641323a5e82.png)

### 错误说明
使用docker安装好之后真寻可以回复纯文字的信息，但是带图片的回复就会报如上错误orz

**Comment by HibiKier** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/326

**Comment by Sakuracio** [comment]
duplicate of #165
see https://github.com/HibiKier/zhenxun_bot/issues/165#issuecomment-1129577477

**Comment by JHDZ33** [comment]
> duplicate of #165 see [#165 (comment)](https://github.com/HibiKier/zhenxun_bot/issues/165#issuecomment-1129577477)

感谢orz，已解决！
