### ISSUE TITLE
提一个有趣的功能需求，希望能实现

### ISSUE THREAD

**Issue by jiaokele** [HibiKier/zhenxun_bot#679]
就是    盲盒  功能
群里发送   ‘盲盒’ ‘来个盲盒’ ‘开盲盒’  等
真寻就发送  ‘鸡汤’ ‘热搜’ ‘热评’ ‘色图’ ‘bt种子’ ‘xxx’ 等目前有的功能或者别的  ，色图等这些可以根据现有的群权限去判定，群权限不够就发送别的内容

**Comment by jiaokele** [comment]
就像戳一戳一样  可以合并？ 戳一戳发送盲盒  生活要带点随机性~

**Comment by Sakuracio** [comment]
建议你实现它 然后发送一个 PR
