### ISSUE TITLE
go-cqhttp出错

### ISSUE THREAD

**Issue by Natsumelan** [HibiKier/zhenxun_bot#681]
![image](https://user-images.githubusercontent.com/105765802/170658369-50045d42-e323-4aa5-95ee-e6bf50d0a43c.png)
扫码登陆后是这个界面

**Comment by Natsumelan** [comment]
昨天因为色图发太多，账号被冻结了，可能是这个原因？

**Comment by Sakuracio** [comment]
那么你为什么不去 [Mrs4s/go-cqhttp](https://github.com/Mrs4s/go-cqhttp) 问呢？

**Comment by MingxuanGame** [comment]
这是一个老 bug 了

重试几次就好了
