### ISSUE TITLE
关于安装portry

### ISSUE THREAD

**Issue by Mrmurong** [HibiKier/zhenxun_bot#684]
### 错误截图
![image](https://user-images.githubusercontent.com/26669224/170769161-a2fc8ae7-d7a5-4e99-9532-19787089597a.png)

### 错误说明

发生了警告，无法将poetry安装成功

**Comment by HibiKier** [comment]
？你不是安装成功了吗

**Comment by Sakuracio** [comment]
如果有不认识的英文，可以翻译一下！
