### ISSUE TITLE
私聊色图r只会发送固定两张图片

### ISSUE THREAD

**Issue by Alkaid114514** [HibiKier/zhenxun_bot#689]
### 错误截图
无报错

### 日志截图
![setu](https://user-images.githubusercontent.com/66519160/170809629-8623b1ef-b88f-4b5c-be12-0a7ab368eadb.png)

### 错误说明
私聊色图r只会发送固定两张图片，没有报错
配置文件里没有开仅发送本地图片
在resources中删除两张图片后依然会下载回来
真寻提示：“坏了，已经没图了，被榨干了！”

**Comment by Alkaid114514** [comment]
补充一下，非r18色图可以正常使用

**Comment by HibiKier** [comment]
色图r 带上tag试过吗，比如 色图r 原神

**Comment by Alkaid114514** [comment]
试了一下，色图r加tag是可以用的，那就没问题啦，随机色图也不怎么用，谢谢
