### ISSUE TITLE
真寻bot不接收消息

### ISSUE THREAD

**Issue by Neptinium** [HibiKier/zhenxun_bot#690]
### 日志截图
bot日志
![log](https://user-images.githubusercontent.com/65025626/170817673-c6f6e2bd-ba1e-4305-bd03-c0fd0b649822.png)
go—cqhttp
![% G_Y L EMN_R`}9LQPWFJ6](https://user-images.githubusercontent.com/65025626/170817753-9950f0cb-4aa3-4f50-9702-f16f1332fdb7.png)

### 错误说明

真寻不接收QQ消息，也无法正常处理回复。go_cqhttp能正常接收信息

**Comment by HibiKier** [comment]
看着是gocq没连上bot？

**Comment by Neptinium** [comment]
解决了谢谢，仔细检查了一下应该是配置没弄好。删除config.yml重新过一遍配置就行了。
