### ISSUE TITLE
数据库连接失败

### ISSUE THREAD

**Issue by Risekato** [HibiKier/zhenxun_bot#691]
### 错误截图
![Q_ BH11 2E892}ZT)2QM BP](https://user-images.githubusercontent.com/102220780/170818943-fbf99a29-ce42-4055-b090-0c7c836e698b.png)

![M3WOIW35L1H1P8UCHBO`QHS](https://user-images.githubusercontent.com/102220780/170818915-900413c8-7d90-40cf-94e7-60360a9491e6.png)

![_C%KDA$%HTR@O5M~4XW5W@Q](https://user-images.githubusercontent.com/102220780/170818753-3380eb7b-8e80-4168-91c8-06f5f555b7d7.png)

![N)`1CVX {HDK@JOE(VE4@22](https://user-images.githubusercontent.com/102220780/170818793-60796623-1a72-4a65-9f99-749076126036.png)

### 日志截图

[img]

### 错误说明
数据库一直连接不上，不确定前面哪里出问题了QAQ

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/170819523-5c31848b-d3b2-4fa1-a1e1-7f5498a484cf.png)
你数据库没建
