### ISSUE TITLE
ai插件出错

### ISSUE THREAD

**Issue by yoshino2333** [HibiKier/zhenxun_bot#693]
![image](https://user-images.githubusercontent.com/105909793/170820517-02cf141d-5d0d-4495-9d53-efd486401869.png)
修改了anime.json里面的文本内容，重启后能收到消息，但bot不理我了，截图是日志，是anime.json不能修改数据吗？

**Comment by HibiKier** [comment]
日志不全，可以修改，但你修改可能不规范

**Comment by yoshino2333** [comment]
> 日志不全，可以修改，但你修改可能不规范

![image](https://user-images.githubusercontent.com/105909793/170820912-b9d21905-15b8-412a-ae31-c2286ad1831f.png)
![image](https://user-images.githubusercontent.com/105909793/170820938-0ac2a6b8-d504-490b-acc0-b32ab8c1538c.png)
大佬请看
![BXP~(NMX(FBMST()RXTIE)P](https://user-images.githubusercontent.com/105909793/170820941-89dc2250-5b08-4729-8f99-f542cacfb3e3.png)

**Comment by HibiKier** [comment]
估计是你改的时候不规范

**Comment by yoshino2333** [comment]
不好意思，是我少了个符号
