### ISSUE TITLE
您好，请教一下无法响应指令的问题

### ISSUE THREAD

**Issue by heixiaoou** [HibiKier/zhenxun_bot#695]
### 错误截图

![image](https://user-images.githubusercontent.com/106435645/170831395-8f18ef92-f2dd-4e0a-8a31-edc23daa88e8.png)
![image](https://user-images.githubusercontent.com/106435645/170831542-ee4e04d0-37ec-467f-9e5a-2d952750b36d.png)
![image](https://user-images.githubusercontent.com/106435645/170831584-348ca497-55ab-47fa-9aba-08bd208abd92.png)

### 日志截图

![image](https://user-images.githubusercontent.com/106435645/170831438-ddfbe122-0d06-4264-9fd4-0d812c67c7c6.png)

### 错误说明

发生了无法反应签到，骂我的指令

**Comment by HibiKier** [comment]
网络问题捏

**Comment by heixiaoou** [comment]
我目前使用的是校园网，是只能用家里的网那种类型的吗？

**Comment by heixiaoou** [comment]
先谢谢大佬了
