### ISSUE TITLE
连接反向服务器出现错误

### ISSUE THREAD

**Issue by HouraisanHoshi** [HibiKier/zhenxun_bot#696]
### 错误截图

![@X75H3MJ DQ83KC$19Q%(BI](https://user-images.githubusercontent.com/59908591/170851353-e76ffc8d-3cd3-4099-bbe9-4ec9f84c862e.png)

### 日志截图

![@X75H3MJ DQ83KC$19Q%(BI](https://user-images.githubusercontent.com/59908591/170851362-dbc47302-9f38-4d40-ab55-0dcdefa96bca.png)

### 错误说明

应该怎么处理，求大大指导

**Comment by HibiKier** [comment]
把你bot开起来

**Comment by HouraisanHoshi** [comment]
现在又有新问题了，我zhenxun_bot解压的文件夹里没有env.dev,设置不了超级用户
![image](https://user-images.githubusercontent.com/59908591/170854510-fcf2bd80-621d-429c-923a-0b9380b6b3f9.png)

**Comment by HouraisanHoshi** [comment]
上面问题解决了，原来是文件隐藏了，现在又有新问题了。。。
![}KXWSTH90_0CHU30PUEM ZA](https://user-images.githubusercontent.com/59908591/170855437-9827ee28-e0f2-4507-8a4b-8ec93dbee841.png)
这个killed怎么处理

**Comment by MingxuanGame** [comment]
> 上面问题解决了，原来是文件隐藏了，现在又有新问题了。。。 ![}KXWSTH90_0CHU30PUEM ZA](https://user-images.githubusercontent.com/59908591/170855437-9827ee28-e0f2-4507-8a4b-8ec93dbee841.png) 这个killed怎么处理

https://github.com/HibiKier/zhenxun_bot/issues/234
