### ISSUE TITLE
找不到指定模块

### ISSUE THREAD

**Issue by xdaqda** [HibiKier/zhenxun_bot#698]
家里的台式机bot可以完美跑起来
但是换了笔记本之后就报错，找不到指定模块，这要咋办
![QQ图片20220529155941](https://user-images.githubusercontent.com/106209173/170858388-b5480578-87a2-4057-bfa8-d747bf6a8c43.png)

**Comment by MingxuanGame** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/373#issuecomment-1131638639

**Comment by xdaqda** [comment]
> [#373 （评论）](https://github.com/HibiKier/zhenxun_bot/issues/373#issuecomment-1131638639)

成功解决，十分感谢
