### ISSUE TITLE
webui 登录未知错误

### ISSUE THREAD

**Issue by Heartcoolman** [HibiKier/zhenxun_bot#699]
### 错误截图
![image](https://user-images.githubusercontent.com/60339402/170858611-7515d5c6-6716-40ba-b957-01bca16a44f0.png)

### 日志截图

![image](https://user-images.githubusercontent.com/60339402/170858665-0f8b5ef0-9b0d-41fe-8065-92db67abb43d.png)
### 错误说明

按正常流程走的，bot可以正常运行，但是web ui 能访问网页但一直错误

**Comment by HanakoLuna** [comment]
检查zhenxun_bot(机器人目录)下的.env.dev文件，页底的Port是否为8080。

**Comment by Heartcoolman** [comment]
好，解决了，谢谢

> 检查zhenxun_bot(机器人目录)下的.env.dev文件，页底的Port是否为8080。

**Comment by Heartcoolman** [comment]
> ### 系统版本：Ubuntu 20.04
> ### 真寻版本：0.1.5.3
> ### 错误截图
> ![图片](https://user-images.githubusercontent.com/60339402/170858611-7515d5c6-6716-40ba-b957-01bca16a44f0.png)
> 
> ### 日志截图
> ![图片](https://user-images.githubusercontent.com/60339402/170858665-0f8b5ef0-9b0d-41fe-8065-92db67abb43d.png)
> 
> ### 错误说明
> 按正常流程走的，bot可以正常运行，但是web ui 可以访问网页但一直报错
