### ISSUE TITLE
可莉特调每天四点才切换到下一天

### ISSUE THREAD

**Issue by jimodeniuren** [HibiKier/zhenxun_bot#7]
这两天发现每日素材都是刚好晚一天，后来发现可莉特调零点的时候并没有切到下一天而是四点的时候才切换，自动更新应该设置成四点之后

**Comment by HibiKier** [comment]
好的，已修改，感谢

**Comment by Jerry-FaGe** [comment]
稻妻图开了之后，可莉特调每日素材的那个框放不下了，加了滚动条，截图只截那个框的稻妻武器那部分会届不到

**Comment by HibiKier** [comment]
> 
> 
> 稻妻图开了之后，可莉特调每日素材的那个框放不下了，加了滚动条，截图只截那个框的稻妻武器那部分会届不到

已修复
![C3@@~OPJ200GI 1R1 V2%%O](https://user-images.githubusercontent.com/45528451/126995196-5f5cd30a-de0b-4e5c-894f-2725146fbf86.PNG)

**Comment by jimodeniuren** [comment]
今天比昨天又长了一行，又塞不下了
![1](https://cdn.jsdelivr.net/gh/jimodeniuren/tuchuang//3463991930-4065669968-0AE2CEC5324A337F8475A4E9DE1FD77C.png)

**Comment by Raysamatoken** [comment]
请问下最新版的调用的字体是啥，更新完后直接乱码了
![QQ图片20210727095125](https://user-images.githubusercontent.com/26264287/127082279-0844f4de-7ed5-43d6-9781-14b49128b07b.png)

**Comment by Jerry-FaGe** [comment]
> 今天比昨天又长了一行，又塞不下了

https://github.com/HibiKier/zhenxun_bot/blob/0dfca7e23d4c9e28d1d1ec8bec16d3c32aad08a7/plugins/genshin/material_remind/__init__.py#L54-L62
暂时改成这样吧，我在上班没有时间研究更智能的方法了
```python
        await page.set_viewport_size({"width": 2560, "height": 2560})


        await page.evaluate("""
            document.getElementsByClassName('GSTitleBar_gs_titlebar__2IJqy')[0].remove();
            document.getElementsByClassName('GSToday_gs_today__S-nol')[0].remove();
            e = document.getElementsByClassName('GSContainer_gs_container__2FbUz')[0];
            e.setAttribute("style", "height:1080px");
        """)


        await page.click("button")
```

**Comment by Jerry-FaGe** [comment]
> 请问下最新版的调用的字体是啥，更新完后直接乱码了

Linux 安装中文字体，百度一下照做就行了

**Comment by HibiKier** [comment]
我改成单个截图+拼图了，这样以后开新图也不用一直在这方面更新
![3238573864-1747216220-A0F0E03DC709739750CB53BECECBF886](https://user-images.githubusercontent.com/45528451/127131069-d17ba408-0df5-46ca-beb4-43afc6344108.png)
