### ISSUE TITLE
签到系统未知错误

### ISSUE THREAD

**Issue by neal240** [HibiKier/zhenxun_bot#703]
### 错误截图

[img]
![IMG_3856](https://user-images.githubusercontent.com/106437969/170866022-abc6b5c1-c176-4724-88a2-8df73453bf23.PNG)

### 日志截图

[img]

### 错误说明

签到时真寻没有反应，后台显示上图

**Comment by HibiKier** [comment]
每次签到都有？

**Comment by ShiinaRinne** [comment]
> 每次签到都有？

我今天早上签到失败，看日志是和这个一样的情况，重启过几次之后就没这个错误了，群员现在可以正常签到。
附两个上午的私聊截图，看了下日志，签到好像有时候会被ai插件捕获：

- 小真寻生病了不能签到
- 本次签到成功

![image](https://user-images.githubusercontent.com/45081750/170919335-f8d471be-40d5-4bda-b364-1c8c3a688b4c.png)
![image](https://user-images.githubusercontent.com/45081750/170919480-4b1eefb0-444e-4c30-9dde-4d72ad3e7ce5.png)

**Comment by cqash** [comment]
我也是不能签到，但是群里其他人可以签到，不知道把超级用户改掉会不会能签到

**Comment by HibiKier** [comment]
> > 每次签到都有？
> 
> 我今天早上签到失败，看日志是和这个一样的情况，重启过几次之后就没这个错误了，群员现在可以正常签到。 附两个上午的私聊截图，看了下日志，签到好像有时候会被ai插件捕获：
> 
>     * 小真寻生病了不能签到
> 
>     * 本次签到成功
> 
> 
> ![image](https://user-images.githubusercontent.com/45081750/170919335-f8d471be-40d5-4bda-b364-1c8c3a688b4c.png) ![image](https://user-images.githubusercontent.com/45081750/170919480-4b1eefb0-444e-4c30-9dde-4d72ad3e7ce5.png)

你私聊签到什么

**Comment by HibiKier** [comment]
> 我也是不能签到，但是群里其他人可以签到，不知道把超级用户改掉会不会能签到

日志

**Comment by cqash** [comment]
> 

问题确认了，是我那时候设置了透明头像导致的作图的程序报错导致的
