### ISSUE TITLE
无法检查更新真寻，显示为SSL证书问题

### ISSUE THREAD

**Issue by THNEden** [HibiKier/zhenxun_bot#704]
### 错误截图
![F7RP(EY122A` QHZD QFZ4](https://user-images.githubusercontent.com/87106832/170866393-046b8e84-6269-42bc-8b20-979015449227.png)

### 日志截图

![DN 1QAHMHXDAQXLZH19CGO0](https://user-images.githubusercontent.com/87106832/170866409-7653aad2-f8c2-424b-aaca-af8f3fbd08ea.png)

### 错误说明
如题

**Comment by HibiKier** [comment]
试试在get请求上加verify=False
