### ISSUE TITLE
版本：v0.1.5.6升级版本：v0.1.5.8后 无法启动bot，提示插件冲突 截了最后一小段打印信息

### ISSUE THREAD

**Issue by cqash** [HibiKier/zhenxun_bot#708]
1:00:57 [WARNING] basic_plugins | 配置文件 模块：pixiv_rank_search 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：send_setu 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：weather 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：nbnhhsh 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：white2black_image 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：pid_search 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：bt 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：music 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：what_anime 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：search_anime 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：pix 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：bilibili_sub 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：translate 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：quotations 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：poetry 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：wbtop 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：jitang 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：cover 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：comments_163 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：search_image 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：update_picture 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [WARNING] basic_plugins | 配置文件 模块：ai 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
05-30 01:00:57 [INFO] basic_plugins | 已成功加载 59 个非限制插件.
05-30 01:00:57 [INFO] utils | 已成功加载 5 个Cd限制.
05-30 01:00:57 [INFO] utils | 已成功加载 12 个Block限制.
05-30 01:00:57 [INFO] utils | 已成功加载 1 个Count限制.
05-30 01:00:57 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/cqash/zhenxun_bot-main/basic_plugins/init_plugin_config/init_plugins_config.py", line 86, in init_plugins_config
    admin_manager.set_admin_level(k, v)
  File "/home/cqash/zhenxun_bot-main/utils/manager/admin_manager.py", line 31, in set_admin_level
    self._data[plugin]["level"] = level
KeyError: 'custom_welcome_message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cqash/.cache/pypoetry/virtualenvs/zhenxun-bot-MURHfYdM-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/home/cqash/.cache/pypoetry/virtualenvs/zhenxun-bot-MURHfYdM-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/home/cqash/.cache/pypoetry/virtualenvs/zhenxun-bot-MURHfYdM-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 600, in startup
    handler()
  File "/home/cqash/zhenxun_bot-main/basic_plugins/init_plugin_config/__init__.py", line 45, in _
    init_plugins_config(DATA_PATH)
  File "/home/cqash/zhenxun_bot-main/basic_plugins/init_plugin_config/init_plugins_config.py", line 88, in init_plugins_config
    raise KeyError(f"{e} ****** 请检查是否有插件加载失败 ******")
KeyError: "'custom_welcome_message' ****** 请检查是否有插件加载失败 ******"

05-30 01:00:57 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by GKCommander** [comment]
我是这样解决的，退出poetry后输入poetry install重新安装一些项目后就能正常启动了

**Comment by MarmotSun** [comment]
我也是。。

**Comment by MarmotSun** [comment]
建议按[https://github.com/HibiKier/zhenxun_bot/issues/661](url)重新更新一遍，基本就能解决了

**Comment by Judp28** [comment]
> 建议按[https://github.com/HibiKier/zhenxun_bot/issues/661](url)重新更新一遍，基本就能解决了

这个链接点进去是空的。。

**Comment by blingblinghydrogen** [comment]
> 我是这样解决的，退出poetry后输入poetry install重新安装一些项目后就能正常启动了

非常感谢，这样做之后能运行了。
