### ISSUE TITLE
更新后启动出现问题

### ISSUE THREAD

**Issue by qclf** [HibiKier/zhenxun_bot#710]
### 错误截图

![QQ截图20220530104938](https://user-images.githubusercontent.com/97816993/170909156-1f9bc4fa-3030-4d2b-a4e3-a9636281ae9f.png)
![QQ截图20220530105012](https://user-images.githubusercontent.com/97816993/170909159-92782d62-7a9b-449f-804a-bad3b970b1f8.png)

**Comment by HibiKier** [comment]
文件夹请替换而不是覆盖

**Comment by milkasir** [comment]
> 文件夹请替换而不是覆盖

大佬我按照这个把原文件夹删除然后再把下载的源码上传还是会报这个错怎么办orz
![image](https://user-images.githubusercontent.com/92635464/170920138-f2fe7595-bfd7-4391-a23e-e96b16d2ab35.png)

**Comment by qclf** [comment]
> > 文件夹请替换而不是覆盖
> 
> 大佬我按照这个把原文件夹删除然后再把下载的源码上传还是会报这个错怎么办orz ![image](https://user-images.githubusercontent.com/92635464/170920138-f2fe7595-bfd7-4391-a23e-e96b16d2ab35.png)

我把除了data和resources以外的文件全部删掉然后把新版的放进去重启搞好了

**Comment by HibiKier** [comment]
新版本wbtop移到alapi外边了，你不把文件删了就报这个重复的错了
