### ISSUE TITLE
（bug？）显示词条显示不全

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#713]
### 系统版本：
版本	Windows Server 2022 Datacenter
版本号	21H2
安装日期	‎2022/‎5/‎29
操作系统内部版本	20348.643

### 错误截图
![1V37T%WFCT5}I2N} BZIBTD](https://user-images.githubusercontent.com/105090141/170920987-bd73b2c0-419c-4c23-b3f7-de988cb50062.PNG)

### 错误说明
显示词条时图片长度不够，如图第17个词条显示不出来（能看到一丁点）

**Comment by HibiKier** [comment]
501e47c6ec0d8f958c560ba0f01f5eee3fe84ac5
