### ISSUE TITLE
bot无法发送图片

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#714]
### 系统版本：
版本 Windows Server 2022 Datacenter
版本号 21H2
安装日期 ‎2022/‎5/‎29
操作系统内部版本 20348.643

### 错误截图
![go-cqhttp](https://user-images.githubusercontent.com/105090141/170927855-82991916-cb5c-4a3e-8093-a867d37589b6.png)
![合并](https://user-images.githubusercontent.com/105090141/170927872-689a7498-dd6a-4f0b-a58a-f5f931af43a2.png)

### 错误说明
![发送](https://user-images.githubusercontent.com/105090141/170927987-b2874d51-5d5b-4936-ae1f-afc662ef73f7.png)
![接收](https://user-images.githubusercontent.com/105090141/170927997-dc8ee510-d471-493c-8698-38a46fcf3fb8.png)
经测试只有【用户A→bot→用户/群聊B】形式的图片发不出，如广播、联系管理员等功能的图片就会报上面的错误，并且只有文字发出来了。（但是词条功能正常）
识图、色图、帮助功能也仍然正常

**Comment by HibiKier** [comment]
因为这个是直接发送的url，发不出去了大概率是网络问题
