### ISSUE TITLE
nonebot商店里的一个插件导入后报错

### ISSUE THREAD

**Issue by 52llc** [HibiKier/zhenxun_bot#716]
### 错误截图
![image](https://user-images.githubusercontent.com/95897275/170936106-0b49efdc-1b10-4433-991e-9969818b9270.png)

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by HibiKier** [comment]
虽然这是网络问题，但是你不应该去对应插件仓库提issues吗？
