### ISSUE TITLE
PIX图库无法使用

### ISSUE THREAD

**Issue by HanakoLuna** [HibiKier/zhenxun_bot#718]
### 错误截图

![2](https://user-images.githubusercontent.com/26741937/170968979-2b16d073-a705-4c11-ae74-18ced5944c66.png)

### 错误说明

PIX图库无法使用，任何有关Pix的命令皆返回相似错误

“ TypeError: unsupported operand type(s) for /: 'str' and 'str' ”

希望获得解决方法，谢谢。

**Comment by HibiKier** [comment]
配置文件中pix那边比例部分把单引号去掉

**Comment by HanakoLuna** [comment]
非常感谢，已解决。
