### ISSUE TITLE
自带cos插件API更新了

### ISSUE THREAD

**Issue by Nikki-520** [HibiKier/zhenxun_bot#719]
请教一下，目前cos插件接口是直接返回的图片
但是有的api接口更新成返回json了，图片url在json里
这里要怎么改啊
![image](https://user-images.githubusercontent.com/36581300/170973510-ee733e46-2f55-4e3d-b4b5-c241e17537cf.png)
![image](https://user-images.githubusercontent.com/36581300/170973581-1eb651ec-2d79-4192-915d-bb873bc794f6.png)

**Comment by HibiKier** [comment]
获取后自己把url取出来再发送
