### ISSUE TITLE
关于真寻的主人

### ISSUE THREAD

**Issue by KONOHADA** [HibiKier/zhenxun_bot#723]
每次问bot“你的主人是谁”，都会出现一堆不认识的人名。问“你的男主人呢”会出现一个不知道是谁的qq号，这是啥情况
![Uploading B91974A48312F2B525FE5DFAF645D1C0.jpg…]()
![Uploading QQ截图20220530232528.png…]()

**Comment by HiDolen** [comment]
![OS5BLAS$1} }GXXX@6)6N0I](https://user-images.githubusercontent.com/87627379/171072658-e013246b-9e93-40f9-ade2-dfa85e2d7cc0.png)
确实会发生这些情况

**Comment by HibiKier** [comment]
青云客的回复
