### ISSUE TITLE
非管理员也能使用撤回权限？

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#724]
### 系统版本：
版本 Windows Server 2022 Datacenter
版本号 21H2
安装日期 ‎2022/‎5/‎29
操作系统内部版本 20348.643

### 错误截图
![-23c65359123dbf6a](https://user-images.githubusercontent.com/105090141/171028585-341e3b45-e60a-4725-8f4d-f6abee37dfa9.png)
![-e67b1758f76526f](https://user-images.githubusercontent.com/105090141/171028640-3ef25939-7210-4715-930c-e49a4fcb1574.png)
![-6af831deb885fa45](https://user-images.githubusercontent.com/105090141/171028683-dc364451-bf0c-4707-b282-79188e2e6740.png)

### 错误说明
看文档里撤回属于管理员插件，确认了群友没有管理员权限后发现仍能使用撤回功能

**Comment by HibiKier** [comment]
因为配置文件中这个level默认为0
