### ISSUE TITLE
真寻更新后启动出现问题

### ISSUE THREAD

**Issue by wjiajian** [HibiKier/zhenxun_bot#727]
### 错误截图

![image](https://user-images.githubusercontent.com/71640797/171076031-402d7508-e026-4019-a447-a15e941fb73a.png)

### 错误说明
替换更新文件后无法正常启动

**Comment by WWWA7** [comment]
看看上边是不是有报错No module named 'rich'
pip3 install rich安装rich然后重启就行了

**Comment by wjiajian** [comment]
> 

感谢，问题已经解决了
