### ISSUE TITLE
在python 3.10 环境下 使用pip install scipy==1.6.1 安装scipy依赖库报错，这个有办法解决吗

### ISSUE THREAD

**Issue by Zenithsk** [HibiKier/zhenxun_bot#728]
D:\onbotDeploy\botdir\zhenxun_bot>pip install scipy==1.6.1
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting scipy==1.6.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/26/68/84dbe18583e79e56e4cee8d00232a8dd7d4ae33bc3acf3be1c347991848f/scipy-1.6.1.tar.gz (27.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [130 lines of output]
      setup.py:461: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\DELL\AppData\Local\Temp\pip-modern-metadata-3iek0n9u'), proceeding with generating Cython sources and expanding templates
        warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
      Running from SciPy source directory.
      INFO: lapack_opt_info:
      INFO: lapack_armpl_info:
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO:   libraries armpl_lp64_mp not found in ['D:\\Program Files\\Python310\\lib', 'C:\\', 'D:\\Program Files\\Python310\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_mkl_info:
      INFO:   libraries mkl_rt not found in ['D:\\Program Files\\Python310\\lib', 'C:\\', 'D:\\Program Files\\Python310\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_lapack_info:
      INFO:   libraries openblas not found in ['D:\\Program Files\\Python310\\lib', 'C:\\', 'D:\\Program Files\\Python310\\libs']
      INFO: get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      INFO: customize GnuFCompiler
      WARN: Could not locate executable g77
      WARN: Could not locate executable f77
      INFO: customize IntelVisualFCompiler
      WARN: Could not locate executable ifort
      WARN: Could not locate executable ifl
      INFO: customize AbsoftFCompiler
      WARN: Could not locate executable f90
      INFO: customize CompaqVisualFCompiler
      WARN: Could not locate executable DF
      INFO: customize IntelItaniumVisualFCompiler
      WARN: Could not locate executable efl
      INFO: customize Gnu95FCompiler
      WARN: Could not locate executable gfortran
      WARN: Could not locate executable f95
      INFO: customize G95FCompiler
      WARN: Could not locate executable g95
      INFO: customize IntelEM64VisualFCompiler
      INFO: customize IntelEM64TFCompiler
      WARN: Could not locate executable efort
      WARN: Could not locate executable efc
      INFO: customize PGroupFlangCompiler
      WARN: Could not locate executable flang
      WARN: don't know how to compile Fortran code on platform 'nt'
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_clapack_info:
      INFO:   libraries openblas,lapack not found in ['D:\\Program Files\\Python310\\lib', 'C:\\', 'D:\\Program Files\\Python310\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: flame_info:
      INFO:   libraries flame not found in ['D:\\Program Files\\Python310\\lib', 'C:\\', 'D:\\Program Files\\Python310\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: accelerate_info:
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas,tatlas not found in D:\Program Files\Python310\lib
      INFO:   libraries tatlas,tatlas not found in C:\
      INFO:   libraries tatlas,tatlas not found in D:\Program Files\Python310\libs
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_info:
      INFO:   libraries satlas,satlas not found in D:\Program Files\Python310\lib
      INFO:   libraries satlas,satlas not found in C:\
      INFO:   libraries satlas,satlas not found in D:\Program Files\Python310\libs
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in D:\Program Files\Python310\lib
      INFO:   libraries ptf77blas,ptcblas,atlas not found in C:\
      INFO:   libraries ptf77blas,ptcblas,atlas not found in D:\Program Files\Python310\libs
      INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_info:
      INFO:   libraries f77blas,cblas,atlas not found in D:\Program Files\Python310\lib
      INFO:   libraries f77blas,cblas,atlas not found in C:\
      INFO:   libraries f77blas,cblas,atlas not found in D:\Program Files\Python310\libs
      INFO: <class 'numpy.distutils.system_info.atlas_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_info:
      INFO:   libraries lapack not found in ['D:\\Program Files\\Python310\\lib', 'C:\\', 'D:\\Program Files\\Python310\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      C:\Users\DELL\AppData\Local\Temp\pip-build-env-0wptyl5l\overlay\Lib\site-packages\numpy\distutils\system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO: lapack_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      C:\Users\DELL\AppData\Local\Temp\pip-build-env-0wptyl5l\overlay\Lib\site-packages\numpy\distutils\system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO:   NOT AVAILABLE
      INFO:
      Traceback (most recent call last):
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Program Files\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-0wptyl5l\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-0wptyl5l\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-0wptyl5l\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 588, in <module>
          setup_package()
        File "setup.py", line 584, in setup_package
          setup(**metadata)
        File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-0wptyl5l\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
          config = configuration()
        File "setup.py", line 499, in configuration
          raise NotFoundError(msg)
      numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
      To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
      See site.cfg.example in the Scipy source directory and
      https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Zenithsk** [comment]
在进行安装依赖时，在3.10.1的python环境会提示安装 scipy 1.6.1 失败，项目里有用到 scipy1.6.1库吗

**Comment by pamss** [comment]
试试python3.8 或 python3.9，我之前用 python3.10也报错了

**Comment by Zenithsk** [comment]
> 试试python3.8 或 python3.9，我之前用 python3.10也报错了

嗯嗯，蟹蟹~
