### ISSUE TITLE
请问怎么开启自动同意进群功能，自定义问答功能

### ISSUE THREAD

**Issue by qijidaren** [HibiKier/zhenxun_bot#73]
请问怎么开启自动同意进群功能，自定义问答功能

**Comment by HibiKier** [comment]
自动进群？超级用户拉bot的话是会自动同意的，自定义问答可以安装nbstore中的nonebot-plugin-wordbank

**Comment by qijidaren** [comment]
自动同意其他人进群 不是机器人进群

**Comment by HibiKier** [comment]
同意被人进群，目前没有
