### ISSUE TITLE
更新后启动加载插件报错

### ISSUE THREAD

**Issue by Excalibur5100** [HibiKier/zhenxun_bot#732]
### 错误截图
![image](https://user-images.githubusercontent.com/105792144/171207286-47264154-9273-4875-bde6-3c540b0458dd.png)

### 日志截图

![image](https://user-images.githubusercontent.com/105792144/171207186-a57d066d-553e-4090-9981-85592f42ebbd.png)

### 错误说明

更新后重启bot时一开始很多个插件加载时都提示ModuleNotFoundError: No module named 'rich'，如上图，然后一堆插件都没加载，最后启动失败

**Comment by jk6589jk** [comment]
去插件文件夹里看看是不是插件被删掉了😳，我上上次更新也遇到过

**Comment by HibiKier** [comment]
poetry install

**Comment by Excalibur5100** [comment]
感谢
