### ISSUE TITLE
原神抽卡卡池还是神里绫华

### ISSUE THREAD

**Issue by ayakasuki** [HibiKier/zhenxun_bot#733]
### 错误截图
![image](https://user-images.githubusercontent.com/20859971/171218183-dba9329f-a8f2-4083-bae6-30731f2f68e4.png)

[img]

### 日志截图

[img]

### 错误说明

无发生错误，但是卡池还是旧卡池。已重载卡池和信息

**Comment by Frenqy** [comment]
![image](https://user-images.githubusercontent.com/28777951/171318541-c708a45a-ba47-461e-a9fe-6f2df7734cb0.png)
看了下日志 后台是有报错的 但是看不到堆栈，也没办法排查

**Comment by ayakasuki** [comment]
![image](https://user-images.githubusercontent.com/20859971/171374278-40ab2011-669e-46ad-b838-a41a934aa04d.png)
我看到了，重载卡池信息是有报错的

**Comment by HiDolen** [comment]
b wiki已经跟新了。可能是代码缺陷

等一个大佬的pr

**Comment by Frenqy** [comment]
看了下bwiki和源码，估计是因为bwiki上还没有人上传卡池图片的原因
等一个好哥哥上传卡池图片

**Comment by ayakasuki** [comment]
> 看了下bwiki和源码，估计是因为bwiki上还没有人上传卡池图片的原因 等一个好哥哥上传卡池图片

BWIKI已经更新，重载卡池依然是出错

**Comment by ayakasuki** [comment]
> 看了下bwiki和源码，估计是因为bwiki上还没有人上传卡池图片的原因 等一个好哥哥上传卡池图片

没事了，Bwiki图片确实没上传

**Comment by ayakasuki** [comment]
> 看了下bwiki和源码，估计是因为bwiki上还没有人上传卡池图片的原因 等一个好哥哥上传卡
现在可以了

**Comment by Lightning627** [comment]
现在是双UP池，BOT只能抽一个UP池子
