### ISSUE TITLE
petpet 头像表情包 发送头像表情包真寻返回只有序号的功能说明图

### ISSUE THREAD

**Issue by SSRanh** [HibiKier/zhenxun_bot#735]
### 错误截图
![QQ图片20220601014019](https://user-images.githubusercontent.com/106005353/171245866-596950d3-db5d-4700-bd76-5a4b12922a47.jpg)

### 日志截图
日志尚未报错

**Comment by HibiKier** [comment]
你不该去对应仓库下面提issues？

**Comment by McElaga** [comment]
有人提出解决了,是字体缺失.解决方法:apt install fonts-noto

**Comment by SSRanh** [comment]
谢谢大大们，已经解决了，安装字体就行了
