### ISSUE TITLE
 原神玩家查询失败

### ISSUE THREAD

**Issue by LSGLSH** [HibiKier/zhenxun_bot#736]
原神玩家查询失败显示真寻版本1.2.8所以小更新我都更新了

**Comment by HibiKier** [comment]
更到最新的

**Comment by LSGLSH** [comment]
> 



> 更到最新的

已经是最新版本了但依旧查询失败

**Comment by HibiKier** [comment]
仓库最新的，不是release

**Comment by LSGLSH** [comment]
> 仓库最新的，不是release

就是在仓库拉取的，大概率查询失败，或者有部分查询了，回复回来的图片极慢，而且数据不完全

**Comment by ayakasuki** [comment]
> 

win_rate那行的#前面不要空格，之前改的人带空格了，亲测可行

**Comment by 52llc** [comment]
> > 
> 
> win_rate那行的#前面不要空格，之前改的人带空格了，亲测可行
我去试试

**Comment by HiDolen** [comment]
绑定cookie才能查询
