### ISSUE TITLE
[建议]更简单粗暴的防图片被夹方式

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#739]
从别的群bot那里得来的灵感
![-46ce9e2083914996](https://user-images.githubusercontent.com/105090141/171383045-19502f6f-e242-4f16-8070-ca76e03afa86.png)
没错就是直接旋转图片90°
然后我想起图片简易操作功能中是有一个旋转图片的功能
![-30149c24cfbfdcd0](https://user-images.githubusercontent.com/105090141/171383489-f01e93a5-131e-4b59-a7ef-9e6b0316f9a2.png)
所以理论上只需要复制一下这个功能添加到setu这边来就可以了吧（？

**Comment by HibiKier** [comment]
6effbacb28f80b5c5d9f1b6751d76e9b6faa77b8 修改了图片的md5
