### ISSUE TITLE
查看插件仓库超时

### ISSUE THREAD

**Issue by Kanase** [HibiKier/zhenxun_bot#744]
### 错误截图

![image](https://user-images.githubusercontent.com/34505849/171530276-c75f0c2b-513e-4a2c-83c0-9865ccca8a8d.png)

### 错误说明

查看插件仓库发生错误：http.readtimeout

**Comment by HanakoLuna** [comment]
可以考虑挂个梯子。

**Comment by HibiKier** [comment]
可以考虑挂个梯子。
