### ISSUE TITLE
No module named 'nonebot' 我已安装了 还是这样

### ISSUE THREAD

**Issue by fjf199907** [HibiKier/zhenxun_bot#746]
### 错误截图
![P B3 F6N}MVP1C@WMV4~KQ2](https://user-images.githubusercontent.com/49164645/171540777-5da580d3-2855-4f16-b1be-5efc17c6fc63.png)

[img]

### 日志截图
空的

### 错误说明
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 1, in <module>
    import nonebot
ModuleNotFoundError: No module named 'nonebot'

**Comment by mxk736850509** [comment]
我也是这样 刚好也想问
我的是win10
运行
poetry shell
python bot.py
（用Python3没任何输出）
就和你的一模一样了

**Comment by HanakoLuna** [comment]
使用一键脚本安装，到输入bot qq号的时候不可打断进程，（可以随便输入一串数字，跳过设置阶段，后续会进入pip安装依赖阶段。

**Comment by fjf199907** [comment]
是pip安装依赖阶段。可能出问题了么？ 我重新安装一下

**Comment by mxk736850509** [comment]
> 使用一键脚本安装 直到出现“输入bot qq”时，不可使用ctrl+c 打断进程 （可以随便输入一串数字，跳过设置阶段) 后续会进入pip安装依赖阶段。 理论上可以解决这个错误。

大佬求教
我pip安装依赖都安装上了
就是启动不了

**Comment by HibiKier** [comment]
难道没有 poetry install阶段的？？

**Comment by fjf199907** [comment]
poetry install阶段一键部署自动安装了
