### ISSUE TITLE
安装依赖出现问题

### ISSUE THREAD

**Issue by NekoInValkyr** [HibiKier/zhenxun_bot#748]
### 错误截图

![image](https://user-images.githubusercontent.com/95226187/171555801-66fbd8b6-3ca1-489d-8483-f181e8db1e5d.png)

### 日志截图

如上

### 错误说明

安装依赖出现问题

**Comment by fjf199907** [comment]
安装依赖 不成功是py版本不对 必须要3.8或者3.9的

**Comment by fjf199907** [comment]
多余版本卸载

**Comment by NekoInValkyr** [comment]
python是3.8.x的，版本是对的

> 安装依赖 不成功是py版本不对 必须要3.8或者3.9的

**Comment by WWWA7** [comment]
试试先安装依赖torch
![image](https://user-images.githubusercontent.com/84784330/171571526-4c28537f-2c20-44bf-9446-1a1b1351cd16.png)

**Comment by NekoInValkyr** [comment]
> 试试先安装依赖torch ![image](https://user-images.githubusercontent.com/84784330/171571526-4c28537f-2c20-44bf-9446-1a1b1351cd16.png)

好，晚上试试😊
