### ISSUE TITLE
如何禁用私聊功能，并且限制在部分群聊使用真寻bot

### ISSUE THREAD

**Issue by K0zero** [HibiKier/zhenxun_bot#749]
### 真寻版本：0.1.5.3

bot能正常使用，但是如何禁用私聊自动回复功能以及将bot功能限制在仅在部分群聊中使用。
而且在文档中好像没有提到
以及超级用户、管理员分别是什么身份，看了文档，感觉无法区分
求大佬指导，感谢！

**Comment by HibiKier** [comment]
文档中都提到了，看 插件开关部分
