### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by BalconyJH** [HibiKier/zhenxun_bot#75]
添加类似于黄历/塔罗/星座/幸运值等玄学功能（
支持以特殊符号或其他形式为间隔的同时关闭/开启/多群聊启用/禁用功能

**Comment by BalconyJH** [comment]
昵称系统可以选择全局通用或者区分私聊/群聊

**Comment by BalconyJH** [comment]
好感度系统全局通用

**Comment by BalconyJH** [comment]
![image](https://user-images.githubusercontent.com/73932916/140857221-0de7d7da-7eff-44bd-a304-1cec0c92eef6.png)
@HibiKier 宝这里的星星是不是太多了（ @HibiKier

**Comment by HibiKier** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/73932916/140857221-0de7d7da-7eff-44bd-a304-1cec0c92eef6.png) @HibiKier 宝这里的星星是不是太多了（ @HibiKier

这事青云客的

**Comment by sun0225SUN** [comment]
这个很简单做的，找个万年历API就可以自己写插件了，数据都不用自己爬 :smile:

**Comment by BalconyJH** [comment]
朋友说支持emoji

**Comment by BalconyJH** [comment]
权限管理系统支持未收录插件接入

**Comment by HibiKier** [comment]
支持未收录的插件只需要符合真寻的插件标准就行了，就添加一些__plugin_xxx__，具体查看文档，另外且要求插件matcher的优先级不是1或9（优先级方面超级用户插件除外

**Comment by evlic** [comment]
> 朋友说（鲁迅说）支持emoji ![Screenshot_20211118-134934_QQ.jpg](https://user-images.githubusercontent.com/73932916/142359584-1e1de4e3-35b7-4ab9-bd05-3860057b37bf.jpg)

对 emjio 的问题我有一点点研究，首先插件源码中是封装的图片处理 Util，目前只看到用过 ttf 格式的字体，关于彩色 emjio 有好几家字体标准，首先这需要确保该 Util 支持加入多种字体（和 Css font-family 类似的处理，差字自动选补），以及该 图片处理功能库本身要支持 emjio 才行。
