### ISSUE TITLE
发红包功能疑似bug

### ISSUE THREAD

**Issue by RShock** [HibiKier/zhenxun_bot#750]
### 错误截图

![Screenshot_2022-06-02-17-51-20-739_com tencent mobileqq](https://user-images.githubusercontent.com/11630758/171604756-e3466035-7f94-4f5b-9b46-c53c731ef2ea.png)

### 日志截图

暂无

### 错误说明

疑似在A发红包结束后，B发送“发红包退回”会将红包剩余数额返回给B

**Comment by RShock** [comment]
其他人有这个问题吗？感觉总是把金币退还给下一个发红包的人。群主已经被气跑了群解散了:(

**Comment by RShock** [comment]
好像是line127直接取了event用户作为退还对象导致的

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/172047103-432acaea-c380-44b2-8948-86ee721fecec.png)
？别人退回难道没有这个？

**Comment by RShock** [comment]
退回那边有是否是本人退回的校验，但是塞红包没有，会直接覆盖发送红包人

**Comment by HibiKier** [comment]
已接收pr
