### ISSUE TITLE
真寻帮助昵称 提示“没有此功能的帮助信息...”

### ISSUE THREAD

**Issue by mmmjie** [HibiKier/zhenxun_bot#752]
### 真寻版本：0.1.5.8

后台无报错，自己想不到哪的问题，所以求助！！！

![QQ截图20220602205311](https://user-images.githubusercontent.com/45615222/171634264-cd9179fb-f461-41a5-8e2d-9dc7fad00e9b.png)

**Comment by Umon7275** [comment]
直接看使用文档吧
https://hibikier.github.io/zhenxun_bot/docs/help_doc/basic_plugins/common_plugins.html#%E6%98%B5%E7%A7%B0

**Comment by HibiKier** [comment]
363acf37bc64cd69164ebc3f7ad6bfb2fcd9c4ca
