### ISSUE TITLE
真寻报错No module named ’nonebot.adapters.onebot.v11.exception’

### ISSUE THREAD

**Issue by wjiajian** [HibiKier/zhenxun_bot#755]
### 错误截图

![image](https://user-images.githubusercontent.com/71640797/171786180-e69bbfab-6b8f-4d37-a23a-807fa3b6e165.png)

### 错误说明

使用poetry update后无法正常启动bot，删除所有依赖重新安装依赖后依旧报错

**Comment by wjiajian** [comment]
> ### 系统版本：Ubuntu 20.04
> ### 真寻版本：0.1.5.8
> ### 错误截图
> ![image](https://user-images.githubusercontent.com/71640797/171786180-e69bbfab-6b8f-4d37-a23a-807fa3b6e165.png)
> 
> ### 错误说明
> 使用poetry update后无法正常启动bot，删除所有依赖重新安装依赖后依旧报错

使用命令poetry env remove python3删除虚拟环境后，替换poetry.lock后重新portry install解决问题

**Comment by tyx3** [comment]
大佬，怎么替换poetry.lock啊？
