### ISSUE TITLE
如何把数据转移到服务器上

### ISSUE THREAD

**Issue by zlsSGuang** [HibiKier/zhenxun_bot#759]
我是一开始用自己的电脑来搞的机器人，现在已经把服务器的小真寻搞完了，但是数据没有同步，请问数据是在哪个文件的？

**Comment by Umon7275** [comment]
当然都在数据库里啦。
你可以在自己的电脑上下一个pgadmin4，可视化操作数据库捏。

**Comment by zlsSGuang** [comment]
> 据库里啦。
> 你可以在自

在数据库的data文件夹吗？
