### ISSUE TITLE
B站订阅无法获取动态

### ISSUE THREAD

**Issue by Izumi096** [HibiKier/zhenxun_bot#76]
订阅的用户发了动态之后后台没有反应

**Comment by HibiKier** [comment]
操作系统是windows?

**Comment by Izumi096** [comment]
是的

**Comment by HibiKier** [comment]
windows下面暂时不能使用playwright方面的功能，用户动态是采用的playwright

**Comment by Izumi096** [comment]
另外my_info里貌似因为没有__plugin_settings__ 查看帮助的时候会提示没有此功能的帮助信息...

**Comment by HibiKier** [comment]
噢对，因为里面没有__plugin_settings__，你可以自己先照着加上
