### ISSUE TITLE
数据库连接异常

### ISSUE THREAD

**Issue by zlsSGuang** [HibiKier/zhenxun_bot#760]
![image](https://user-images.githubusercontent.com/105781964/171886929-1dfe98b7-d068-4284-a95f-9dd9b6f39055.png)
一直提示这个，因为我想要备份我这个电脑里的数据到新买的服务器里，而备份到postgres一直提示错误，我就新建了一个数据库，新建数据库→还原到...→备份文件→提示成功→把真寻config数据库名称改成新的→尝试登录→提示连接数据库异常

**Comment by zlsSGuang** [comment]
![image](https://user-images.githubusercontent.com/105781964/171896197-4eb92540-3947-4b84-bb61-e4de68d8dcc6.png)

**Comment by HibiKier** [comment]
你改了sql_name？

**Comment by zlsSGuang** [comment]
![image](https://user-images.githubusercontent.com/105781964/171898463-b519808e-62a1-4453-9a0f-6a597ca64687.png)
![image](https://user-images.githubusercontent.com/105781964/171899278-9561fa56-ef0e-45aa-92ab-f3d1b4f293ab.png)

**Comment by MingxuanGame** [comment]
sql_name 为 postgresql 不能大写

**Comment by zlsSGuang** [comment]
> sql_name 为 postgresql 不能大写
大写小写都试过了，一直报错

**Comment by zlsSGuang** [comment]
对了，如果是用默认的postgres是可以连接的，但是是新的数据……我想要备份数据

**Comment by zlsSGuang** [comment]
> 对了，如果是用默认的postgres是可以连接的，但是是新的数据......我想要备份数据

如果不行的话就只能用默认的了
