### ISSUE TITLE
关于pix指令同时存在tag和图片数量时的冲突

### ISSUE THREAD

**Issue by river-1** [HibiKier/zhenxun_bot#762]
系统版本：Ubuntu 20.04
真寻版本：0.1.5.8

错误截图

![DFB13118-30BE-431A-9C8C-E982F45BD226](https://user-images.githubusercontent.com/58901462/171974760-9b6ca2fa-4297-45a4-96ff-e5668fd708bb.png)

日志截图

略

错误说明

当发送pix指令同时包括tag和数量时，疑似会把“tag+数字”整体看作tag的字符串。举例如发送“pix 白丝 2”，收获了一张22娘的白丝图。
当前问题复现的条件为加载了omega图库，并将图库比例设置为0:10，即完全依赖omega图库

**Comment by river-1** [comment]
补充：希望能给tag增加单独的标识符，如tag前加“#”。刚刚把pix开放给群友用，收到的第一条指令是“pix 02”（国家队你坏事做尽）
Ps：来酒吧的客人点了一份炒面

**Comment by HibiKier** [comment]
785179e4a7d28c271b5ad8a06f878480ffffade6
