### ISSUE TITLE
好感度系统建议：增大获取倍率、增加获取途径

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#765]
![image](https://user-images.githubusercontent.com/105090141/171988454-9f616026-1a64-4596-8d10-040c7add1445.png)
看了签到好感度的代码，觉得原来的倍率实在太低，即使每天都能触发好感度×2，从零开始签到直至到达恋人等级也需要400/(0.5×2)=400天（数学期望），改倍率×10之后就好很多

群友提到只能通过签到获得好感度不符合设定，我参考了下其他bot：
1、每日和bot互动也可获得好感度，每次互动可得少量好感，通过该途径获取好感度有每日次数上限
2、“好感度双倍加持卡”改为“XX礼物”，通过“使用/赠送”指令使用，使用效果为“立即增加好感度/提高当日途径1的次数上限/下次签到好感度倍率提升”

**Comment by HibiKier** [comment]
你可以通过添加商品的方式来实现，给真寻送礼物之类的，详细见开发文档

**Comment by luoxiyun** [comment]
想问一下修改好感度倍率是在哪个地方，具体是怎么改呢，好感度太难加了。望大佬不吝赐教

**Comment by nekopaer** [comment]
直接改数据库多简单，直接手动好感度9999999

**Comment by luoxiyun** [comment]
> > 想问一下修改好感度倍率是在哪个地方，具体是怎么改呢，好感度太难加了。 望大佬不吝赐教
> 
> 我是在\plugins\sign_in\group_user_checkin.py的第66行改的

好耶，成功了把100改成10 好感度加的快多了。谢谢大佬
