### ISSUE TITLE
更新后启动插件加载失败，web登录未知错误，后台报错404

### ISSUE THREAD

**Issue by Bai3396** [HibiKier/zhenxun_bot#770]
![image](https://user-images.githubusercontent.com/93367792/172069556-326c550f-2ec7-4cd9-ba10-6d4c876313d4.jpeg)

**Comment by MingxuanGame** [comment]
pip install rich

**Comment by nekopaer** [comment]
我这升级之后也发现一些插件用不了，然后查了下，升级之后，一些插件目录被干掉了，重新安装下就好了

**Comment by Bai3396** [comment]
> pip install rich

你好，安装库之后启动依旧报错，插件加载失败

**Comment by Bai3396** [comment]
多次安装库已解决，但是新版的web前端有反应，登录不上，后端也不报东西

**Comment by Bai3396** [comment]
已解决
