### ISSUE TITLE
原神角色X连命令只会抽取第一个池子

### ISSUE THREAD

**Issue by Narmaya-gbf** [HibiKier/zhenxun_bot#771]
### 错误截图

[img]

### 日志截图

[img]

### 错误说明

当原神同时两个池子时，原神角色X连命令只会抽取第一个池子

**Comment by McElaga** [comment]
需要更换池子

**Comment by HiDolen** [comment]
代码缺陷，没考虑到双角色池的情况。等一个大佬的pr

**Comment by ayakasuki** [comment]
可以参考sagiri_bot那边的切换卡池

**Comment by HibiKier** [comment]
b25b9ca928597e38d4aabd6f5227991a80caf0d0
