### ISSUE TITLE
关于插件管理相关指令在哪

### ISSUE THREAD

**Issue by Excalibur5100** [HibiKier/zhenxun_bot#773]
![image](https://user-images.githubusercontent.com/105792144/172150772-69806af2-7d47-415a-b93a-b2c99f656c92.png)
看更新日志的时候提到增加了插件相关的指令，请问这个指令有使用帮助或文档吗，或者在代码哪里看

**Comment by HibiKier** [comment]
超级用户帮助

**Comment by chengfsrc** [comment]
超级用户帮助没有相关指令

**Comment by HibiKier** [comment]
363acf37bc64cd69164ebc3f7ad6bfb2fcd9c4ca
