### ISSUE TITLE
真寻机器人更新不了怎么办？

### ISSUE THREAD

**Issue by waq527** [HibiKier/zhenxun_bot#780]
![3e0fa84b90559b74](https://user-images.githubusercontent.com/106297247/172405762-fa4bb9a6-b13a-400b-967c-27c3d6cb3a24.jpg)
![4da850dc196fd6e](https://user-images.githubusercontent.com/106297247/172405774-853e5eea-b702-4ef7-ac76-1546b54869c4.png)

**Comment by MingxuanGame** [comment]
请查看 gocqhttp 的输出

大概率为风控

**Comment by waq527** [comment]
![2ab430305d66863b](https://user-images.githubusercontent.com/106297247/172523656-5b38c90a-a889-4c68-8e95-4f54310909ec.png)
好像不是风控，这个是这么回事啊？

**Comment by MingxuanGame** [comment]
请更新 go-cqhttp 版本为 1.0.0-rc2

**Comment by waq527** [comment]
![-467f463509e625af](https://user-images.githubusercontent.com/106297247/172525926-58b628f3-0a29-46a5-b0aa-6c8305d01d77.jpg)
![7cd25aad90bda22f](https://user-images.githubusercontent.com/106297247/172525931-6f9636f0-b788-4e2b-9b86-96e16b43b6b4.jpg)
更新了但是好像还是报错

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/174427135-8d0abb0e-b932-40e4-9170-e449f89a3dfa.png)
