### ISSUE TITLE
签到插件Bug

### ISSUE THREAD

**Issue by XKaguya** [HibiKier/zhenxun_bot#781]
### 错误截图
无

### 日志截图
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 1743, in putalpha
    self.im.setmode(mode)
    │    │  │       └ 'LA'
    │    │  └ <method 'setmode' of 'ImagingCore' objects>
    │    └ <ImagingCore object at 0x7f928edc84f0>
    └ <PIL.Image.Image image mode=1 size=102x102 at 0x7F928FA4ACD0>

ValueError: image has wrong mode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7f92b4246160>
    └ <module 'nonebot' from '/usr/local/lib/python3.9/dist-packages/nonebot/__init__.py'>

  File "/usr/local/lib/python3.9/dist-packages/nonebot/__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f92b5b11ca0>

  File "/usr/local/lib/python3.9/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
    │       └ <function run at 0x7f92b2ffab80>
    └ <module 'uvicorn' from '/usr/local/lib/python3.9/dist-packages/uvicorn/__init__.py'>

  File "/usr/local/lib/python3.9/dist-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f92b2ffa670>
    └ <uvicorn.server.Server object at 0x7f9294fcd4c0>

  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f92b2ffa700>
           │       │   └ <uvicorn.server.Server object at 0x7f9294fcd4c0>
           │       └ <function run at 0x7f92b53d0f70>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>

  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f9294fdf5c0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>

  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f92b4261b80>: <Task finished name='Task-192657' coro=<_command() done, defined at /usr/local/lib/py...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f928ed6b880>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '签到', '_matched_g...
          │            │        │    └ GroupMessageEvent(time=1654590084, self_id=3134562597, post_type='message', sub_type='normal', user_id=1254229822, message_ty...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f928fc18760>
          │            └ <Matcher from plugins.sign_in, type=message, priority=5, temp=False>
          └ <function _run_matcher at 0x7f92b40d3f70>

> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f92b4261b80>: <Task finished name='Task-192657' coro=<_command() done, defined at /usr/local/lib/py...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f928ed6b880>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '签到', '_matched_g...
          │       │   │    └ GroupMessageEvent(time=1654590084, self_id=3134562597, post_type='message', sub_type='normal', user_id=1254229822, message_ty...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f928fc18760>
          │       └ <function Matcher.run at 0x7f92b42615e0>
          └ <Matcher from plugins.sign_in, type=message, priority=5, temp=False>

  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f92b4261b80>: <Task finished name='Task-192657' coro=<_command() done, defined at /usr/local/lib/py...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f928ed6b880>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '签到', '_matched_g...
          │    │          │    └ GroupMessageEvent(time=1654590084, self_id=3134562597, post_type='message', sub_type='normal', user_id=1254229822, message_ty...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f928fc18760>
          │    └ <function Matcher.simple_run at 0x7f92b4261550>
          └ <Matcher from plugins.sign_in, type=message, priority=5, temp=False>

  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7f929b556af0>, params=[ModelField(name='event', type=GroupMessageEvent, required=True), Mode...

  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'event': GroupMessageEvent(time=1654590084, self_id=3134562597, post_type='message', sub_type='normal', user_id=1254229822, ...
                 │    └ <function _ at 0x7f929b556af0>
                 └ <Dependent call=<function _ at 0x7f929b556af0>, params=[ModelField(name='event', type=GroupMessageEvent, required=True), Mode...

  File "/home/zhenxun_bot/plugins/sign_in/__init__.py", line 93, in _
    await group_user_check_in(nickname, event.user_id, event.group_id),
          │                   │         │     │        │     └ 831196839
          │                   │         │     │        └ GroupMessageEvent(time=1654590084, self_id=3134562597, post_type='message', sub_type='normal', user_id=1254229822, message_ty...
          │                   │         │     └ 1254229822
          │                   │         └ GroupMessageEvent(time=1654590084, self_id=3134562597, post_type='message', sub_type='normal', user_id=1254229822, message_ty...
          │                   └ '神奇的辞西兰'
          └ <function group_user_check_in at 0x7f929b533040>

  File "/home/zhenxun_bot/plugins/sign_in/group_user_checkin.py", line 39, in group_user_check_in
    return await _handle_check_in(nickname, user_qq, group, present)  # ok
                 │                │         │        │      └ datetime.datetime(2022, 6, 7, 16, 21, 24, 447158)
                 │                │         │        └ 831196839
                 │                │         └ 1254229822
                 │                └ '神奇的辞西兰'
                 └ <function _handle_check_in at 0x7f929b556430>

  File "/home/zhenxun_bot/plugins/sign_in/group_user_checkin.py", line 97, in _handle_check_in
    return await get_card(user, nickname, impression_added, gold, gift)
                 │        │     │         │                 │     └ '额外金币 + 1'
                 │        │     │         │                 └ 19
                 │        │     │         └ 0.44
                 │        │     └ '神奇的辞西兰'
                 │        └ <models.sign_group_user.SignGroupUser object at 0x7f928f1d0e50>
                 └ <function get_card at 0x7f929b556040>

  File "/home/zhenxun_bot/plugins/sign_in/utils.py", line 83, in get_card
    return await asyncio.get_event_loop().run_in_executor(
                 │       └ <built-in function get_event_loop>
                 └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>

  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None

  File "/home/zhenxun_bot/plugins/sign_in/utils.py", line 120, in _generate_card
    ava.circle()
    │   └ <function BuildImage.circle at 0x7f929dcdb280>
    └ <utils.image_utils.BuildImage object at 0x7f928edbcf10>

  File "/home/zhenxun_bot/utils/image_utils.py", line 684, in circle
    self.markImg.putalpha(mask)
    │    │       │        └ <PIL.Image.Image image mode=L size=102x102 at 0x7F928FA4A880>
    │    │       └ <function Image.putalpha at 0x7f929f9400d0>
    │    └ <PIL.Image.Image image mode=1 size=102x102 at 0x7F928FA4ACD0>
    └ <utils.image_utils.BuildImage object at 0x7f928edbcf10>

  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 1746, in putalpha
    im = self.im.convert(mode)
         │    │  │       └ 'LA'
         │    │  └ <method 'convert' of 'ImagingCore' objects>
         │    └ <ImagingCore object at 0x7f928edc84f0>
         └ <PIL.Image.Image image mode=1 size=102x102 at 0x7F928FA4ACD0>

ValueError: conversion from 1 to LA not supported
[img]

### 错误说明

无

当透明头像时，真寻无任何报错在QQ里显示 更换头像即可解决

**Comment by HibiKier** [comment]
363acf37bc64cd69164ebc3f7ad6bfb2fcd9c4ca
