### ISSUE TITLE
关于插件库中几个插件的报错

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#782]
### 真寻版本：0.1.5.3
插件库地址：https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot
### 错误截图

原神角色卡片
![image](https://user-images.githubusercontent.com/50237543/172450936-b9b204a2-b1c6-4d5f-b7af-423933bbf914.png)

彩云AI续写（已填写API
![image](https://user-images.githubusercontent.com/50237543/172451005-202e93a2-058b-4a52-a452-9ff2f59f2d52.png)

合成字符画插件
![image](https://user-images.githubusercontent.com/50237543/172451105-42037431-e112-4c0d-8993-eb8dd5031b1f.png)

多风格loge生成器
![image](https://user-images.githubusercontent.com/50237543/172451185-a6ede91a-778b-4dff-894a-8bc1ca1cd76b.png)

猜成语
![image](https://user-images.githubusercontent.com/50237543/172451287-d9a38bcb-edd7-410b-a546-e29892cd685a.png)

win下查成分
![image](https://user-images.githubusercontent.com/50237543/172451377-0164b777-601f-4ff2-8598-72cc300ebeb5.png)

好像不是插件（?)我另创的插件文件夹里没这个名字的插件
![image](https://user-images.githubusercontent.com/50237543/172451451-813375d4-192a-4ab9-824b-f04e79ddf50e.png)

头像表情包插件
![image](https://user-images.githubusercontent.com/50237543/172452189-91c90b8f-cf41-4755-abe7-e91610047185.png)

### 日志截图

[img]

### 错误说明

帮助里没有显示以上插件，功能也使用不了。我cmd把上面说缺的插件在插件文件夹中都Pip install 了，其中头像制作插件中nonebot_plugin_imageutils、猜成语插件中enchant、原神角色卡片插件_中curses查无插件安装不了，其他均安装完后重启后还是显示这个图，应该还是无法import，不知道该怎么办QAQ。感谢大佬捞捞

**Comment by Unicorn369** [comment]
头像表情包需要的[nonebot_plugin_imageutils]，实测高于0.1.4版本就不能用，你可以指定版本`pip install nonebot_plugin_imageutils==0.1.3.1`
至于其他的安装了也显示不能用，你也可以换个版本看的

**Comment by dick0841** [comment]
我换了您说的版本在新的插件文件夹里安装后，仍出现如上报错QAQ，感觉好像是别的问题

**Comment by Unicorn369** [comment]
> 我换了你说你在新出现的插件里安装后的版本，仍然如上报错QAQ，感觉好像是其他问题

实在不行只能加个好友，我帮你看看了。你这如果的的确确安装了，但是还是显示没有，大概率应该是某个依赖版本太高，还有你要先执行`pip uninstall [模块名称]`卸载后再重新安装模块才行。

**Comment by McElaga** [comment]
> 我换了您说的版本在新的插件文件夹里安装后，仍出现如上报错QAQ，感觉好像是别的问题

在虚拟环境下安装
