### ISSUE TITLE
linux部署时扫码登录会提示异地登录不给扫码

### ISSUE THREAD

**Issue by splinte** [HibiKier/zhenxun_bot#784]
在其他issue中可以看到有大佬说上传本地的token和session，具体操作流程是什么样的，可以详细说下嘛

**Comment by Lu-Qi-777** [comment]
这边建议扫码的手机换个服务器所在地的ip后重新扫码登录
Mrs4s
/
go-cqhttp#1469

**Comment by McElaga** [comment]
> 在其他issue中可以看到有大佬说上传本地的token和session，具体操作流程是什么样的，可以详细说下嘛

首先在自己设备上使用go-cqhttp扫码登录,把go-cqhttp目录里生成的`device.json`和`session.token`替换掉服务器的`device.json`和`session.token`

**Comment by splinte** [comment]
> 
试过了 也上传了 配置文件里面改了登录方式为口令 还是让我扫码

**Comment by splinte** [comment]
贴一下错误日志吧
06-11 21:06:50 [INFO] uvicorn | Started server process [1313]
06-11 21:06:50 [INFO] uvicorn | Waiting for application startup.
06-11 21:06:51 [ERROR] uvicorn | Traceback (most recent call last):
  File "/home/zhenxun_bot/services/db_context.py", line 19, in init
    await db.set_bind(i_bind)
  File "/usr/local/lib/python3.9/site-packages/gino/api.py", line 417, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/gino/strategies.py", line 55, in create
    pool = await dialect.init_pool(u, loop, pool_class=pool_class)
  File "/usr/local/lib/python3.9/site-packages/gino/dialects/asyncpg.py", line 465, in init_pool
    return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs)
  File "/usr/local/lib/python3.9/site-packages/gino/dialects/asyncpg.py", line 218, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 413, in _async__init__
    await self._initialize()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 441, in _initialize
    await first_ch.connect()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 133, in connect
    self._con = await self._pool._get_new_connection()
  File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 511, in _get_new_connection
    con = await connection.connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2085, in connect
    return await connect_utils._connect(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect
    return await _connect_addr(
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 781, in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 831, in __connect_addr
    await compat.wait_for(connected, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 66, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "zhenxun"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/home/zhenxun_bot/services/db_context.py", line 23, in init
    raise Exception(f'数据库连接错误.... {type(e)}: {e}')
Exception: 数据库连接错误.... <class 'asyncpg.exceptions.InvalidPasswordError'>: password authentication failed for user "zhenxun"

06-11 21:06:51 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by McElaga** [comment]
> 贴一下错误日志吧 06-11 21:06:50 [INFO] uvicorn | Started server process [1313] 06-11 21:06:50 [INFO] uvicorn | Waiting for application startup. 06-11 21:06:51 [ERROR] uvicorn | Traceback (most recent call last): File "/home/zhenxun_bot/services/db_context.py", line 19, in init await db.set_bind(i_bind) File "/usr/local/lib/python3.9/site-packages/gino/api.py", line 417, in set_bind bind = await create_engine(bind, loop=loop, **kwargs) File "/usr/local/lib/python3.9/site-packages/gino/strategies.py", line 55, in create pool = await dialect.init_pool(u, loop, pool_class=pool_class) File "/usr/local/lib/python3.9/site-packages/gino/dialects/asyncpg.py", line 465, in init_pool return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs) File "/usr/local/lib/python3.9/site-packages/gino/dialects/asyncpg.py", line 218, in _init self._pool = await asyncpg.create_pool(**args) File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 413, in _async__init__ await self._initialize() File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 441, in _initialize await first_ch.connect() File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 133, in connect self._con = await self._pool._get_new_connection() File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 511, in _get_new_connection con = await connection.connect( File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2085, in connect return await connect_utils._connect( File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect return await _connect_addr( File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 781, in _connect_addr return await __connect_addr(params, timeout, True, *args) File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 831, in __connect_addr await compat.wait_for(connected, timeout=timeout) File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 66, in wait_for return await asyncio.wait_for(fut, timeout) File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for return fut.result() asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "zhenxun"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan async with self.lifespan_context(app): File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 530, in **aenter** await self._router.startup() File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup await handler() File "/home/zhenxun_bot/services/db_context.py", line 23, in init raise Exception(f'数据库连接错误.... {type(e)}: {e}') Exception: 数据库连接错误.... <class 'asyncpg.exceptions.InvalidPasswordError'>: password authentication failed for user "zhenxun"
> 
> 06-11 21:06:51 [ERROR] uvicorn | Application startup failed. Exiting.

你这也不是gocq的错误,数据库密码错了

**Comment by splinte** [comment]
> > 贴一下错误日志吧 06-11 21:06:50 [INFO] uvicorn | Started server process [1313] 06-11 21:06:50 [INFO] uvicorn | Waiting for application startup. 06-11 21:06:51 [ERROR] uvicorn | Traceback (most recent call last): File "/home/zhenxun_bot/services/db_context.py", line 19, in init await db.set_bind(i_bind) File "/usr/local/lib/python3.9/site-packages/gino/api.py", line 417, in set_bind bind = await create_engine(bind, loop=loop, **kwargs) File "/usr/local/lib/python3.9/site-packages/gino/strategies.py", line 55, in create pool = await dialect.init_pool(u, loop, pool_class=pool_class) File "/usr/local/lib/python3.9/site-packages/gino/dialects/asyncpg.py", line 465, in init_pool return await pool_class(url, loop, init=self.on_connect(), **self._pool_kwargs) File "/usr/local/lib/python3.9/site-packages/gino/dialects/asyncpg.py", line 218, in _init self._pool = await asyncpg.create_pool(**args) File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 413, in _async__init__ await self._initialize() File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 441, in _initialize await first_ch.connect() File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 133, in connect self._con = await self._pool._get_new_connection() File "/usr/local/lib/python3.9/site-packages/asyncpg/pool.py", line 511, in _get_new_connection con = await connection.connect( File "/usr/local/lib/python3.9/site-packages/asyncpg/connection.py", line 2085, in connect return await connect_utils._connect( File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 881, in _connect return await _connect_addr( File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 781, in _connect_addr return await __connect_addr(params, timeout, True, *args) File "/usr/local/lib/python3.9/site-packages/asyncpg/connect_utils.py", line 831, in __connect_addr await compat.wait_for(connected, timeout=timeout) File "/usr/local/lib/python3.9/site-packages/asyncpg/compat.py", line 66, in wait_for return await asyncio.wait_for(fut, timeout) File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for return fut.result() asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "zhenxun"
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan async with self.lifespan_context(app): File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 530, in **aenter** await self._router.startup() File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup await handler() File "/home/zhenxun_bot/services/db_context.py", line 23, in init raise Exception(f'数据库连接错误.... {type(e)}: {e}') Exception: 数据库连接错误.... <class 'asyncpg.exceptions.InvalidPasswordError'>: password authentication failed for user "zhenxun"
> > 06-11 21:06:51 [ERROR] uvicorn | Application startup failed. Exiting.
> 
> 你这也不是gocq的错误,数据库密码错了

我用的一键部署 他自动的 我也不知道正确的数据库密码是多少

**Comment by McElaga** [comment]
> 我用的一键部署 他自动的 我也不知道正确的数据库密码是多少

那么数据库算是另一个错误;这里解决gocq的:先确保你的本地gocq可以登录并且可以启动成功.然后在你的服务器重新按照安装文档配置gocq,注意不要改变登录方式,首次运行扫码登录后出现异地登陆提示,关闭gocq,再将两个本地文件替换
