### ISSUE TITLE
[微博热搜插件数据时效性问题]

### ISSUE THREAD

**Issue by Lu-Qi-777** [HibiKier/zhenxun_bot#785]
当用户只想获取第一条热搜时，会尝试发送“微博热搜 1”
如果是bot第一次运行插件，则没有问题
但是一段时间后如果用户想获得第n条热搜，由于wbtop_data的内容还是第一次运行{微博热搜 n}/上一次运行{微博热搜}的内容，此时获取到的热搜内容与实际热搜顺序不符

建议获取第n条热搜详细信息时也检查一下当前wbtop_data["time"]与实际时间的差值←_←

**Comment by HibiKier** [comment]
833e266a1f95ae91034795b8835a17675fab5eb7

**Comment by Lu-Qi-777** [comment]
收到收到收到~
