### ISSUE TITLE
关于pix图库和omega图库怎么删除

### ISSUE THREAD

**Issue by Zhuazizizi** [HibiKier/zhenxun_bot#787]
我导入了omega图库，然后发觉自己硬盘内存不是很足，现在想删掉的话应该咋整，
还有PIX图库能批量删除图片吗，我删除了关键词后似乎图片并没有一起删除。

**Comment by McElaga** [comment]
pix图库只导入相关的信息,不会导入图片
如果想删除信息的话,在数据库中pix和omega表中删除

**Comment by Zhuazizizi** [comment]
> pix图库只导入相关的信息,不会导入图片 如果想删除信息的话,在数据库中pix和omega表中删除

谢谢！找到了！
原来导入的只是信息吗，那可能感觉内存少了是我的错觉把。
