### ISSUE TITLE
真寻的基础功能出了些问题

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#788]
![image](https://user-images.githubusercontent.com/50237543/172692283-61896968-df11-4e1a-9197-7f46951f529b.png)
![image](https://user-images.githubusercontent.com/50237543/172692333-03bdaba8-3c30-4dd4-9278-dd9015ac1178.png)
![image](https://user-images.githubusercontent.com/50237543/172692378-72fae41a-daaa-4662-8fe1-70e6fdcef2cc.png)
几个核心功能好像显示同一个问题呃呃，帮助用不了，商店用不了QWQ求捞捞

**Comment by dick0841** [comment]
![image](https://user-images.githubusercontent.com/50237543/172698991-4b452e5a-96b4-4674-86d7-e0b31a3f3fcc.png)
什么都没做自己冒出来的报错，看着像是插件的问题，但不知道是不是基础功能导致的

**Comment by HibiKier** [comment]
> ![image](https://user-images.githubusercontent.com/50237543/172692283-61896968-df11-4e1a-9197-7f46951f529b.png) ![image](https://user-images.githubusercontent.com/50237543/172692333-03bdaba8-3c30-4dd4-9278-dd9015ac1178.png) ![image](https://user-images.githubusercontent.com/50237543/172692378-72fae41a-daaa-4662-8fe1-70e6fdcef2cc.png) 几个核心功能好像显示同一个问题呃呃，帮助用不了，商店用不了QWQ求捞捞

你这不都是ai的报错？你把配置文件ai的某个配置项删了？

**Comment by dick0841** [comment]
呃呃，有可能是  出现这个问题可能跟我程序还在运行就给它关了有关系   但是我后面重新下了最新版的真寻把数据重新填了  额外的插件重新放了    还是出现这个问题    请问该如何解决QWQ

**Comment by HibiKier** [comment]
plugin2config.yaml删了

**Comment by dick0841** [comment]
已解决，肥肠感谢QAQ
