### ISSUE TITLE
原神插件 玩家查询报错

### ISSUE THREAD

**Issue by BECKONXD** [HibiKier/zhenxun_bot#789]
### 错误截图

[img]
![QQ截图20220609022806](https://user-images.githubusercontent.com/100980706/172698919-9223037a-4ca3-4c10-b0dc-2309854423d4.png)

### 日志截图
[error_2022-06-09.log](https://github.com/HibiKier/zhenxun_bot/files/8864462/error_2022-06-09.log)

### 错误说明

原神绑定了uid，米游社和cookie，输入 ys [UID]后没反应，后台报错。

**Comment by MaMaMayoyi** [comment]
我这边使用原神角色查询时也出错
![image](https://user-images.githubusercontent.com/86137185/172752036-108748c1-72b3-452f-8914-143c3479c996.png)

**Comment by HibiKier** [comment]
363acf37bc64cd69164ebc3f7ad6bfb2fcd9c4ca
