### ISSUE TITLE
运行ai报错

### ISSUE THREAD

**Issue by WindFlarer** [HibiKier/zhenxun_bot#79]
提示 gino.exceptions.UninitializedError: Gino engine is not initialized.

**Comment by HibiKier** [comment]
Gino未初始化，你咋运行的

**Comment by WindFlarer** [comment]
就是因为未初始化报的错，所以来寻求大佬帮助，因为不知道怎么初始化gino



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 晚上9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 运行ai报错 (Issue #79)





 
Gino未初始化，你咋运行的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HibiKier** [comment]
??你正常启动 python bot.py 就会初始化啊

**Comment by advancejar** [comment]
raise Exception(f'数据库连接错误.... e: {e}')
Exception: 数据库连接错误.... e: invalid literal for int() with base 10: ''
我也报这错

**Comment by HibiKier** [comment]
查看数据库配置
