### ISSUE TITLE
金币红包开的时候报错

### ISSUE THREAD

**Issue by qclf** [HibiKier/zhenxun_bot#792]
### 错误截图

![QQ截图20220610103625](https://user-images.githubusercontent.com/97816993/172979648-f6d9dda7-96cb-4351-883a-007a4f9793c6.png)

### 错误说明

发送开之后机器人不回消息，再次发开之后会提示已经开启过红包

**Comment by qclf** [comment]
![QQ图片20220610110908](https://user-images.githubusercontent.com/97816993/172984874-534d9507-4e30-4345-a49c-8958ee3233d1.png)
发现会提示第二种报错

**Comment by McElaga** [comment]
第二种错是因为缺少文件.
解决办法:下载release中的压缩包,将`resources/image/prts`文件夹里的内容全部替换
