### ISSUE TITLE
Poetry install时出现错误

### ISSUE THREAD

**Issue by cglzxb** [HibiKier/zhenxun_bot#793]
### 错误截图

![QQ图片20220611091251](https://user-images.githubusercontent.com/107266036/173166955-2ec8f589-9d79-49f4-83cf-1e3ac4d502bd.png)

### 日志截图

[img]

### 错误说明
Poetry install时出现了错误，搞了好久还是不懂˃ʍ˂

**Comment by mxk736850509** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/468#issuecomment-1133516066
这几天跟你一样，我是这样解决的

**Comment by cglzxb** [comment]
谢谢！删除 VS 和生成工具重装后就好了。
