### ISSUE TITLE
关于真寻自我更新功能报错

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#796]
![image](https://user-images.githubusercontent.com/50237543/173195418-6b036bf1-3a1b-45bd-a9c0-79b482de5846.png)
版本为0.1.5.6，尝试让真寻自我更新但是失败，求大佬捞捞QwQ

**Comment by dick0841** [comment]
win10

**Comment by nekopaer** [comment]
你这文件别丢c盘了，c盘装软件有时候就会有这种权限问题

**Comment by dick0841** [comment]
感谢提醒，我转手扔D盘了，
![image](https://user-images.githubusercontent.com/50237543/173225015-fad5bda1-253e-404e-9cff-bf94ac1595f3.png)，pip install nonebot后
![image](https://user-images.githubusercontent.com/50237543/173225031-2980a164-8170-4a60-9145-3f7459264cb7.png)
，好像pip有问题，请问这样该怎么办

**Comment by unknown10777** [comment]
在机器人目录执行
```
python -m poetry update
python -m poetry install
python -m poetry shell
python bot.py
```

**Comment by unknown10777** [comment]
切记要python3.9或以下环境，python3.10会报poetry install组件错
切记要一直用你poetry install成功那个环境，不同环境会报错

**Comment by dick0841** [comment]
解决了，十分感谢
