### ISSUE TITLE
[建议]修改ban插件

### ISSUE THREAD

**Issue by Da2ns** [HibiKier/zhenxun_bot#797]
在把账号ban掉后，真寻会一直回复并at被ban账号
![Screenshot_20220612-104130_QQ](https://user-images.githubusercontent.com/19469933/173212047-0de9fe63-5968-4758-9774-0b89723834c1.png)
建议改成被ban后不再响应账号的任何消息(目前是会回复)

**Comment by HibiKier** [comment]
你可以选择 b了 命令
