### ISSUE TITLE
能否提供关闭图灵API的选项

### ISSUE THREAD

**Issue by alphagocc** [HibiKier/zhenxun_bot#8]
就做做关键词匹配好了（
主要是那个API要钱

**Comment by HibiKier** [comment]
确实，图灵每日白嫖只有140，不过是有备用的聊天接口的(免费)，当图灵次数用完就会使用备用接口，大部分功能都是有开关的，关闭AI聊天的话输入 ‘’关闭ai‘’ 就行了

**Comment by alphagocc** [comment]
好的，thx
