### ISSUE TITLE
开箱时皮肤价格查询问题

### ISSUE THREAD

**Issue by RMSCA** [HibiKier/zhenxun_bot#801]
### 错误截图

<img width="409" alt="Screen Shot 2022-06-12 at 9 32 14 PM" src="https://user-images.githubusercontent.com/72942610/173280256-e3171baa-cb23-431e-844c-ca53aa35855d.png">
<img width="395" alt="Screen Shot 2022-06-12 at 9 32 21 PM" src="https://user-images.githubusercontent.com/72942610/173280263-e31a40dd-9a45-4310-b58c-6c403f47af22.png">

### 日志截图

gocq日志：
<img width="925" alt="Screen Shot 2022-06-12 at 7 28 36 PM" src="https://user-images.githubusercontent.com/72942610/173279982-3cb297f1-b57c-4c94-afdd-0e21da8653f1.png">
真寻bot日志：
<img width="1056" alt="Screen Shot 2022-06-12 at 7 29 29 PM" src="https://user-images.githubusercontent.com/72942610/173279916-03caf9e1-c5a4-48bb-bde4-f8b663cf4f00.png">
配置文件：
<img width="476" alt="Screen Shot 2022-06-12 at 7 29 55 PM" src="https://user-images.githubusercontent.com/72942610/173279945-a61dd27d-bdff-4cd2-9574-0800f869d4fd.png">
<img width="470" alt="Screen Shot 2022-06-12 at 7 30 04 PM" src="https://user-images.githubusercontent.com/72942610/173279959-bca2f145-7902-4b87-a4f9-c9f148397a7a.png">

### 错误说明

配置文件里填写的cookie是正确的，但是在开箱的时候无法查询到价格
单独使用查询皮肤时是可以正常工作的
感谢帮助！

**Comment by HibiKier** [comment]
开箱是从数据库里查的

**Comment by RMSCA** [comment]
请问我应该做什么配置吗，不是很懂这一块。。

**Comment by HibiKier** [comment]
用buff小号更新价格，图片之类的，或者直接导群里的数据库文件，更新价格图片很容易被封号
