### ISSUE TITLE
识图功能报错KeyError: 'ext_urls'

### ISSUE THREAD

**Issue by qwerdvd** [HibiKier/zhenxun_bot#802]
### 错误截图

![64`I(3 SIUB$O~9T 6AG 0P](https://user-images.githubusercontent.com/105906879/173282275-63159904-15d3-4768-a1be-9d76cda822e3.png)

识别的图是

![91$JDMSA%{M{)O8LV)$L}GH](https://user-images.githubusercontent.com/105906879/173282396-67b93cbd-ced9-41ba-9d8d-67c474becb15.jpg)

### 日志截图

[log.txt](https://github.com/HibiKier/zhenxun_bot/files/8887997/log.txt)

### 错误说明

识图功能报错，显示KeyError: 'ext_urls'
但是在试其他图片时，没有问题

**Comment by HibiKier** [comment]
0736533389f0d773ecaf08c3ec4fc099b5a02597

**Comment by qwerdvd** [comment]
感谢修复
