### ISSUE TITLE
搜番错误

### ISSUE THREAD

**Issue by GHSSeBi** [HibiKier/zhenxun_bot#803]
### 错误截图

![Uploading 2EC0657F-C6B1-4B0C-B533-76F9B32B0266.png…]()

### 日志截图

![AA627E38-51AA-4FF9-89CD-C203A9F8F73E](https://user-images.githubusercontent.com/67882684/173291918-ccc2aca7-2814-4e70-9191-86399b1eaa58.jpeg)

### 错误说明

无法搜番

**Comment by HibiKier** [comment]
挂代理
