### ISSUE TITLE
关于真寻插件安装方面的问题

### ISSUE THREAD

**Issue by wangyousama** [HibiKier/zhenxun_bot#805]
win端
从https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/blob/index/README.md下载的插件
下载后放入plugin文件夹，启动真寻不加载，通过真寻自带插件商店安装插件后，插件位于\extensive_plugin文件夹
重启真寻后依旧不加载，放入plugin后
![XOCJ{5S8 LF1$TUU 3HM)~S](https://user-images.githubusercontent.com/107395159/173309400-1131723b-f3ae-4efa-9bb9-ad5f56346dfc.png)提示如下，bot.py文件没动。
如何才能在真寻bot安装新插件

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/173469444-705b5ea7-5bf6-4374-ac85-eabc06e0f553.png)

**Comment by wangyousama** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/173469444-705b5ea7-5bf6-4374-ac85-eabc06e0f553.png)

就是弹这个错误，依赖也装了

**Comment by HibiKier** [comment]
你看看你是不是重复装了
