### ISSUE TITLE
群词条问答有图片和表情的时候真寻会发表情的代码

### ISSUE THREAD

**Issue by Heartcoolman** [HibiKier/zhenxun_bot#808]
### 错误截图

![image](https://user-images.githubusercontent.com/60339402/173381599-8039d0a2-b4fd-42d2-bd60-fa15b2304017.png)
![image](https://user-images.githubusercontent.com/60339402/173381733-6c486c79-bbf6-4ee3-91e8-50413e8f4a33.png)

这有办法解决嘛

**Comment by dick0841** [comment]
路人弱弱问下这个功能在哪，查看帮助好像没有啊

**Comment by sheep-black** [comment]
拉取请求有一个已经解决该问题by LambdaYH

**Comment by HibiKier** [comment]
0e8d7537d4e47a0b12d5836163bc9ee1678513f4
