### ISSUE TITLE
发送“管理员帮助”无回应

### ISSUE THREAD

**Issue by unknown10777** [HibiKier/zhenxun_bot#814]
###系统版本：Linux KaliNas 5.16.0-kali7-amd64 https://github.com/HibiKier/zhenxun_bot/pull/1 SMP PREEMPT Debian 5.16.18-1kali1 (2022-04-01) x86_64 GNU/Linux

###真寻版本：0.1.5.9

### 错误截图

![image](https://user-images.githubusercontent.com/83267603/173643995-24e3b1b6-3015-4d44-8f01-9a505223f796.png)

### 日志截图

![image](https://user-images.githubusercontent.com/83267603/173643052-c546e2cd-83ab-4e72-9fce-ad6d04835a9c.png)

### 错误说明

”管理员帮助“无回应，其他指令一切正常

**Comment by HibiKier** [comment]
群里发
