### ISSUE TITLE
使用昵称系统的时候报错

### ISSUE THREAD

**Issue by Pumpkin-N** [HibiKier/zhenxun_bot#815]
### 错误截图

[img]

![图片](https://user-images.githubusercontent.com/77291104/173751322-77449bab-c11a-4fe0-a5ff-d358d1ea1607.png)

[img]

### 错误说明

使用“叫我xx”指令报错
”我是“指令没有问题

**Comment by HibiKier** [comment]
呃，大概是BLACK WORD配置项的值为空造成的

**Comment by HibiKier** [comment]
c37901290a3274794cadf5dfbc5279684ddb79d6
