### ISSUE TITLE
在使用"查看插件仓库"时提示"文件下载或解压失败"

### ISSUE THREAD

**Issue by SEVEN-6174** [HibiKier/zhenxun_bot#817]
![Quicker_20220615_173735](https://user-images.githubusercontent.com/107546075/173796362-49010a2e-e159-4a8c-8eed-001bd8a9612a.png)

**Comment by SEVEN-6174** [comment]
> 访问github问题

感谢
但是我挂了加速器
Watt Toolkit（原名steam++，我启用了github加速）

**Comment by HibiKier** [comment]
试试给AsyncHttpx.get加上verify=False
