### ISSUE TITLE
git pull 这个Update browser.py更新后，真寻重启命令出错

### ISSUE THREAD

**Issue by qwerdvd** [HibiKier/zhenxun_bot#818]
### 错误截图

![M9A{6 2TP_DR{P6ZR{%%9IY](https://user-images.githubusercontent.com/105906879/173812833-83afe496-0b4b-44df-923f-e746b31870ae.png)

### 日志截图

无日志

### 错误说明

Update browser.py更新后，真寻重启命令出错
尝试了重装等办法，都无效
回退这次更新就可以使用了

**Comment by HibiKier** [comment]
5172fa69e59e7167dfc59ccf040137cd9fef25d6
