### ISSUE TITLE
小白，装了插件之后报错了，怎么回事？

### ISSUE THREAD

**Issue by waq527** [HibiKier/zhenxun_bot#819]
![720aa481d8e2c60e](https://user-images.githubusercontent.com/106297247/173840077-6987018f-16cf-4441-b9f1-436d4e9e7b0d.png)
小白，想请教一下插件怎么装啊？

**Comment by HanakoLuna** [comment]
引用于 “`https://github.com/yajiwa/zhenxun_plugin_memes`”

进入插件目录，安装相关依赖   `pip3 install -r requirements.txt`

**Comment by waq527** [comment]
解决了
