### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Amoslzh** [HibiKier/zhenxun_bot#82]
12-03 00:56:44 [WARNING] apscheduler | Run time of job "_ (trigger: interval[0:00:30], next run at: 2021-12-03 00:56:57 CST)" was missed by 0:00:16.635029
12-03 00:56:44 [WARNING] init_plugin_config | 插件 <module 'nonebot.plugin.manager._internal.f25597a7430c9babbf0de34fc109f478.apscheduler' from 'basic_plugins\\apscheduler\\__init__.py'> 加载失败...，插件控制未加载.
12-03 00:56:44 [WARNING] init_plugin_config | 插件 <module 'nonebot.plugin.manager._internal.f25597a7430c9babbf0de34fc109f478.invite_manager' from 'basic_plugins\\invite_manager\\__init__.py'> 加载失败...，插件控制未加载.
12-03 00:56:44 [WARNING] init_plugin_config | 插件 <module 'nonebot.plugin.manager._internal.65635d6d2ceffdd946551617f8ed16c7.fudu' from 'plugins\\fudu.py'> 加载失败...，插件控制未加载.
12-03 00:56:44 [WARNING] init_plugin_config | 插件 <module 'nonebot.plugin.manager._internal.f25597a7430c9babbf0de34fc109f478.group_handle' from 'basic_plugins\\group_handle\\__init__.py'> 加载失败...，插件控制未加载.
12-03 00:56:44 [WARNING] init_plugin_config | 插件 <module 'nonebot.plugin.manager._internal.f25597a7430c9babbf0de34fc109f478.group_handle' from 'basic_plugins\\group_handle\\__init__.py'> 加载失败...，插件控制未加载.
12-03 00:56:44 [WARNING] init_plugin_config | 插件 <module 'nonebot.plugin.manager._internal.f25597a7430c9babbf0de34fc109f478.group_handle' from 'basic_plugins\\group_handle\\__init__.py'> 加载失败...，插件控制未加载.
12-03 00:56:44 [WARNING] init_plugin_config | 插件 <module 'nonebot.plugin.manager._internal.f25597a7430c9babbf0de34fc109f478.broadcast' from 'basic_plugins\\broadcast\\__init__.py'> 加载失败...，插件控制未加载.
12-03 00:56:44 [WARNING] init_plugin_config | 插件 <module 'nonebot.plugin.manager._internal.f25597a7430c9babbf0de34fc109f478.help' from 'basic_plugins\\help\\__init__.py'> 加载失败...，插件控制未加载.
12-03 00:56:44 [WARNING] init_plugin_config | 插件 <module 'nonebot.plugin.manager._internal.f25597a7430c9babbf0de34fc109f478.help' from 'basic_plugins\\help\\__init__.py'> 加载失败...，插件控制未加载.
....
....一堆warning

12-03 00:56:44 [INFO] init_plugin_config | 已成功加载 0 个非限制插件.
12-03 00:56:44 [INFO] utils | 已成功加载 1 个Cd限制.
12-03 00:56:44 [INFO] utils | 已成功加载 1 个Block限制.
12-03 00:56:44 [INFO] utils | 已成功加载 1 个Count限制.
12-03 00:56:44 [ERROR] uvicorn | Traceback (most recent call last):
  File "T:\anaconda3\lib\site-packages\starlette\routing.py", line 540, in lifespan
    async for item in self.lifespan_context(app):
  File "T:\anaconda3\lib\site-packages\starlette\routing.py", line 481, in default_lifespan
    await self.startup()
  File "T:\anaconda3\lib\site-packages\starlette\routing.py", line 518, in startup
    handler()
  File "basic_plugins\init_plugin_config\__init__.py", line 45, in _
    init_plugins_data(DATA_PATH)
  File "basic_plugins\init_plugin_config\init_plugins_data.py", line 82, in init_plugins_data
    plugins_manager.save()
  File "T:\pypj\zhenxun_bot-main\utils\manager\data_class.py", line 54, in save
    json.dump(self._data, f, ensure_ascii=False, indent=4)
TypeError: <module 'nonebot.plugin.manager._internal.65635d6d2ceffdd946551617f8ed16c7.ai' from 'plugins\\ai\\__init__.py'> is not JSON serializable

12-03 00:56:44 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by Amoslzh** [comment]
这次后报错之后，然后再次运行后之前能成功加载的模块就有好多变成加载失败了

**Comment by HibiKier** [comment]
新依赖retrying有用pip装了吗

**Comment by Amoslzh** [comment]
![image](https://user-images.githubusercontent.com/93984484/144539358-068cfb85-5c29-4ed0-babc-5035383d291d.png)
安装了的,retrying 1.3.3
第一运行失败没生成配置文件，后续运行都是一样的错误
  File "T:\pypj\zhenxun_bot-main\utils\manager\data_class.py", line 22, in __init__
    self._data: dict = json.load(f)
ValueError: Expected object or value
![image](https://user-images.githubusercontent.com/93984484/144539881-e5d7de5f-3d94-4476-93e4-bcbef3cb3305.png)

**Comment by HibiKier** [comment]
第一次运行吗？如果是第一次运行先将配置data/configs和data/manager配置文件里的东西都删除，如果是修改过文件，根据日志是data/manager/group_manager.json改坏了

**Comment by Amoslzh** [comment]
删除后就回到了第一次运行失败的报错
![image](https://user-images.githubusercontent.com/93984484/144540972-f6ba3614-d5ec-4438-b51b-332fe515ae55.png)
![image](https://user-images.githubusercontent.com/93984484/144541007-833b0885-51f4-4374-8036-557cc2f4156c.png)

**Comment by HibiKier** [comment]
你nonebot2版本多少，插件插件有没有报错

**Comment by HibiKier** [comment]
插件加载有没有报错

**Comment by Amoslzh** [comment]
![image](https://user-images.githubusercontent.com/93984484/144541873-331cfb9b-d601-4c20-85f8-a6ea3a7ca6dc.png)
![image](https://user-images.githubusercontent.com/93984484/144541899-5586d6e2-cf63-4cbd-bf8f-514b4551a1ad.png)
插件都成成功导入了，就各别有些警告
nonebot2 是2.0.0a16
![image](https://user-images.githubusercontent.com/93984484/144542013-006ff1cd-0e38-4ec2-8a1d-989157a59349.png)

**Comment by HibiKier** [comment]
请根据requirements.txt来安装依赖

**Comment by Amoslzh** [comment]
噢噢好的解决了谢谢大佬。。。另外想问下我把群默认等级设为9了，普通成员为啥还提示权限不足
![image](https://user-images.githubusercontent.com/93984484/144555338-2729195a-a55a-4f07-b23b-f1d74de12f1f.png)
![image](https://user-images.githubusercontent.com/93984484/144555420-81ed2147-7688-49a5-a45c-602eefc16aee.png)

**Comment by HibiKier** [comment]
默认群权限只针对新加入的群
