### ISSUE TITLE
插件import成功但是无法使用

### ISSUE THREAD

**Issue by dick0841** [HibiKier/zhenxun_bot#822]
如题，找了一些可疑的日志
![image](https://user-images.githubusercontent.com/50237543/174078998-dc44e967-76a4-4a74-b358-cf7170d8bec2.png)
![image](https://user-images.githubusercontent.com/50237543/174079242-c49ff73a-da8a-48eb-9663-4280d3d66dcf.png)
，感觉无法识别命令了的样子

**Comment by dick0841** [comment]
win10系统，版本0.1.5.9真寻，并且下载了最新的真寻并重新配置（config.yaml、mockingbird模型、dev.dev、config.py）仍如图故障

**Comment by SEVEN-6174** [comment]
感觉你关了似的，试试发“醒来”之后尝试
（不行的话我也无能为力）

**Comment by SEVEN-6174** [comment]
> 如题，找了一些可疑的日志 ![图像](https://user-images.githubusercontent.com/50237543/174078998-dc44e967-76a4-4a74-b358-cf7170d8bec2.png) ![图像](https://user-images.githubusercontent.com/50237543/174079242-c49ff73a-da8a-48eb-9663-4280d3d66dcf.png) ，感觉无法识别命令了的样子

感觉你关了似的，试试发"醒来"之后尝试
（不行的话我也无能为力）

**Comment by dick0841** [comment]
QWQ感谢提供解决思路，按宁方法尝试解决似乎不太行，我再试试（同时再求路过大佬救救

**Comment by SEVEN-6174** [comment]
> QWQ感谢提供解决思路，按宁方法尝试解决似乎不太行，我再试试（同时再求路过大佬救救

这种情况我在使用“休息吧”的指令时遇见过，也就是关闭整个群里的开关，再使用就会切换到这种状态，这个只针对某一个群
如果使用我之前说的那种方法不行的话，可以试试直接重新下载最新的代码，然后把配置重新填一下
