### ISSUE TITLE
使用p站排行提示有一点点小错误

### ISSUE THREAD

**Issue by SEVEN-6174** [HibiKier/zhenxun_bot#823]
![Quicker_20220617_001018](https://user-images.githubusercontent.com/107546075/174117177-3fb689b2-642e-4cfc-bfe7-c75dbc715535.png)

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/174284606-db4ac7b7-e729-45a6-9b8e-e8ccdfb0abe2.png)
网络问题
