### ISSUE TITLE
请问一下，我是第一次用这个bot，我搭建好了之后私聊所有功能都能用，但我拉入群的时候为什么部分功能说权限不足？

### ISSUE THREAD

**Issue by 1293885868** [HibiKier/zhenxun_bot#824]
是要在zhenxun_bot\configs里的configs.yaml里修改群权限等级还是去zhenxun_bot\data\configs里的plugins2settings.yaml里修改？

**Comment by SEVEN-6174** [comment]
> 

如果是超级用户可以直接使用
管理员则是通过
添加权限@xxx 等级，详见文档https://hibikier.github.io/zhenxun_bot/docs/help_doc/basic_plugins/superuser_plugins.html#%E7%AE%A1%E7%90%86%E5%91%98%E6%9D%83%E9%99%90%E6%93%8D%E4%BD%9C
（具体功能等级要求里面也有）

**Comment by SEVEN-6174** [comment]
> 是要在zhenxun_bot\configs里的configs.yaml里修改群权限等级还是去zhenxun_bot\data\configs里的plugins2settings.yaml里修改？
如果是超级用户可以直接使用
管理员则是通过
添加权限@xxx 等级，详见文档 https://hibikier.github.io/zhenxun_bot/docs/help_doc/basic_plugins/superuser_plugins.html#%E7%AE%A1%E7%90%86%E5%91%98%E6%9D%83%E9%99%90%E6%93%8D%E4%BD%9C
管理员权限操作一项
（具体功能等级要求里面也有）

**Comment by SEVEN-6174** [comment]
> 是要在zhenxun_bot\configs里的configs.yaml里修改群权限等级还是去zhenxun_bot\data\configs里的plugins2settings.yaml里修改？

如果是超级用户可以直接使用
管理员则是通过
添加权限@xxx 等级，详见文档 https://hibikier.github.io/zhenxun_bot/docs/help_doc/basic_plugins/superuser_plugins.html#%E7%AE%A1%E7%90%86%E5%91%98%E6%9D%83%E9%99%90%E6%93%8D%E4%BD%9C
管理员权限操作一项
（具体功能等级要求里面也有）

**Comment by 1293885868** [comment]
> > 是要在zhenxun_bot\configs里的configs.yaml里修改群权限等级还是去zhenxun_bot\data\configs里的plugins2settings.yaml里修改？
> 
> 如果是超级用户可以直接使用 管理员则是通过 添加权限@xxx 等级，详见文档 https://hibikier.github.io/zhenxun_bot/docs/help_doc/basic_plugins/superuser_plugins.html#%E7%AE%A1%E7%90%86%E5%91%98%E6%9D%83%E9%99%90%E6%93%8D%E4%BD%9C 管理员权限操作一项 （具体功能等级要求里面也有）

好的，这个问题解决了，但我现在遇到了使用bt来搜索磁力链接却报错
![9%)TYMPV59H(%YLWB_IZTPH](https://user-images.githubusercontent.com/106426137/174395899-1ffa319c-77c5-443e-abb9-188ac3c06a1b.png)

**Comment by 1293885868** [comment]
> > 是要在zhenxun_bot\configs里的configs.yaml里修改群权限等级还是去zhenxun_bot\data\configs里的plugins2settings.yaml里修改？
> 
> 如果是超级用户可以直接使用 管理员则是通过 添加权限@xxx 等级，详见文档 https://hibikier.github.io/zhenxun_bot/docs/help_doc/basic_plugins/superuser_plugins.html#%E7%AE%A1%E7%90%86%E5%91%98%E6%9D%83%E9%99%90%E6%93%8D%E4%BD%9C 管理员权限操作一项 （具体功能等级要求里面也有）

关于web-ui，后台网页设置密码之后登录显示未知错误又该怎么解决？因为我是第一次用bot，不是很了解这些，感谢您的解答

**Comment by unknown10777** [comment]
你可以close这个issue了，这是第二个issue了

**Comment by 1293885868** [comment]
> issue
