### ISSUE TITLE
金币红包问题

### ISSUE THREAD

**Issue by SSRanh** [HibiKier/zhenxun_bot#826]
### 错误截图
![image](https://user-images.githubusercontent.com/106005353/174308609-a6573995-e335-4659-aca1-673c71146307.png)

### 日志截图
06-17 21:31:25 [ERROR] nonebot | Running matcher <Matcher from plugins.gold_redbag, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):

  File "bot.py", line 22, in <module>
    nonebot.run()
    │       └ <function run at 0x7f9e13944160>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 259, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f9e15162dc0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
    │       └ <function run at 0x7f9e124035e0>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f9e12403790>
    └ <uvicorn.server.Server object at 0x7f9df5c452e0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f9e12403820>
           │       │   └ <uvicorn.server.Server object at 0x7f9df5c452e0>
           │       └ <function run at 0x7f9e14a47040>
           └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f9df5cc0cc0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f9e138e4670>: <Task finished name='Task-7419' coro=<_command() done, defined at /root/.cache/pypoet..
.
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f9df4fdb8e0>
          │       │   │    │      └ {'_prefix': {'command': ('开',), 'raw_command': '开', 'command_arg': [], 'command_start': ''}}
          │       │   │    └ GroupMessageEvent(time=1655472685, self_id=2737435598, post_type='message', sub_type='normal', user_id=1410221813, message_ty...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f9df01b0dc0>
          │       └ <function Matcher.run at 0x7f9e138e41f0>
          └ <Matcher from plugins.gold_redbag, type=message, priority=5, temp=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f9e138e4670>: <Task finished name='Task-7419' coro=<_command() done, defined at /root/.cache/pypo
et...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f9df4fdb8e0>
          │    │          │    │      └ {'_prefix': {'command': ('开',), 'raw_command': '开', 'command_arg': [], 'command_start': ''}}
          │    │          │    └ GroupMessageEvent(time=1655472685, self_id=2737435598, post_type='message', sub_type='normal', user_id=1410221813, message_ty...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f9df01b0dc0>
          │    └ <function Matcher.simple_run at 0x7f9e138e4160>
          └ <Matcher from plugins.gold_redbag, type=message, priority=5, temp=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7f9dfafeaaf0>, params=[ModelField(name='event', type=GroupMessageEvent, required=True), Mode...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-Cff2XHJC-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'event': GroupMessageEvent(time=1655472685, self_id=2737435598, post_type='message', sub_type='normal', user_id=1410221813, ...
                 │    └ <function _ at 0x7f9dfafeaaf0>
                 └ <Dependent call=<function _ at 0x7f9dfafeaaf0>, params=[ModelField(name='event', type=GroupMessageEvent, required=True), Mode...

  File "/home/shiran/zhenxun_bot/plugins/gold_redbag/__init__.py", line 219, in _
    image(b64=await get_redbag_img(event.user_id, event.group_id)),
    │               │              │     │        │     └ 574464716
    │               │              │     │        └ GroupMessageEvent(time=1655472685, self_id=2737435598, post_type='message', sub_type='normal', user_id=1410221813, message_ty
...
    │               │              │     └ 1410221813
    │               │              └ GroupMessageEvent(time=1655472685, self_id=2737435598, post_type='message', sub_type='normal', user_id=1410221813, message_ty...
    │               └ <function get_redbag_img at 0x7f9dfafeadc0>
    └ <function image at 0x7f9e11c0e0d0>

  File "/home/shiran/zhenxun_bot/plugins/gold_redbag/__init__.py", line 410, in get_redbag_img
    b64 = await generate_open_redbag_pic(
                └ <function generate_open_redbag_pic at 0x7f9dfafea280>

  File "/home/shiran/zhenxun_bot/plugins/gold_redbag/data_source.py", line 57, in generate_open_redbag_pic
    return await asyncio.create_task(_generate_open_redbag_pic(user_id, send_user_nickname, amount, text))
                 │       │           │                         │        │                   │       └ '已领取1/5个，共8/100金币'
                 │       │           │                         │        │                   └ 8
                 │       │           │                         │        └ '\xa0'
                 │       │           │                         └ 1410221813
                 │       │           └ <function _generate_open_redbag_pic at 0x7f9dfafea310>
                 │       └ <function create_task at 0x7f9e145a7a60>
                 └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>

  File "/home/shiran/zhenxun_bot/plugins/gold_redbag/data_source.py", line 69, in _generate_open_redbag_pic
    ava = BuildImage(66, 66, is_alpha=True, background=BytesIO(await get_user_avatar(user_id)))
          │                                            │             │               └ 1410221813
          │                                            │             └ <function get_user_avatar at 0x7f9e11c9fd30>
          │                                            └ <class '_io.BytesIO'>
          └ <class 'utils.image_utils.BuildImage'>

  File "/home/shiran/zhenxun_bot/utils/image_utils.py", line 216, in __init__
    is_edit = sum([1 for x in pos[0:3] if x > 240]) == 3
                              └ 204

TypeError: 'int' object is not subscriptable
### 错误说明

TypeError: 'int' object is not subscriptable

**Comment by HibiKier** [comment]
903b5b88a734de5ecdfba0293320820aec9e75bb

**Comment by SSRanh** [comment]
谢谢大佬
