### ISSUE TITLE
log文件的编码方式是什么？有部分乱码

### ISSUE THREAD

**Issue by anonymous-gy** [HibiKier/zhenxun_bot#829]
### 真寻版本：0.1.5.8

###错误截图 and 
### 日志截图

![image](https://user-images.githubusercontent.com/23382652/174424443-7d386975-d22f-4da8-8c21-1eb489ce89d7.png)

### 错误说明

如图，就是log乱码，设置了utf8和gb系列都有乱码，想知道具体用哪个编码。 
使用中出了点小问题，准备自己看日志修复
没有在issue和帮助中找到相关的说明

**Comment by anonymous-gy** [comment]
gbk能正常显示中文，但还是存在类似于 [33m 这样的乱码

**Comment by HibiKier** [comment]
utf8？并没有遇到乱码
