### ISSUE TITLE
额外添加插件的问题

### ISSUE THREAD

**Issue by VoplsX** [HibiKier/zhenxun_bot#83]
作者你好，我在额外添加插件之后，添加了一个Genshin_Impact_bot 和GenshinUID，前一个并无报错但是输入指令无反馈，后一个提示获取插件 GenshinUID __zx_plugin_name__ 失败...,插件控制未加载.。个人猜想是除Bot.py还有一个总控插件的文件吗？希望作者能帮忙解答
谢谢！

**Comment by HibiKier** [comment]
Genshin_Impact_bot部分插件与真寻有重复的，具体问题查看日志，另外，所有nonebot2插件都是可以正常在真寻内使用的，如果你希望插件可以获得 帮助，权限控制等，就按照真寻开发文档添加__plugin_xxx__，如果仅仅是使用，不需要其他控制等，就不用管 zx_plugin_name 失败...,插件控制未加载

**Comment by VoplsX** [comment]
感谢答疑！今天努力一天终于在各种奇怪的错误中在Linux部署成功了（主要是postgresql上费了好大劲），impact放弃了，主要是这个插件的抽卡可以分池子 之前还挺想要的，然后是GenshinUID的问题，我添加了__plugin_xxx__（对不起没有好好研读开发文档），在昨天的windows部署的查询角色树脂功能无法绑定cookies，今天换了Linux以及添加了__plugin_xxx__之后就莫名的好了，十分感谢作者们为真寻插件的努力与付出 感谢！
