### ISSUE TITLE
p站排行除日榜其他都发不出

### ISSUE THREAD

**Issue by 1294266616** [HibiKier/zhenxun_bot#831]
### 错误截图

![image](https://user-images.githubusercontent.com/52421598/174425599-bf3e43b7-00b5-4b08-bf80-8174d5a8c881.png)

### 日志截图

![image](https://user-images.githubusercontent.com/52421598/174425558-9c9ef489-7bb0-4929-8360-f5d8b29de5e7.png)
![image](https://user-images.githubusercontent.com/52421598/174425577-88238b32-42a6-4765-ba46-bddb89bf7138.png)

### 错误说明

网络没有问题就是只能看日榜换了其他api也是如此，请问是哪出了问题

**Comment by HibiKier** [comment]
服务器是腾讯云的？

**Comment by 1294266616** [comment]
> 服务器是腾讯云的？

自己的nas挂代理了

**Comment by lin686** [comment]
日本甲骨文服务器也是这样

**Comment by lin686** [comment]
![image](https://user-images.githubusercontent.com/45395335/174432452-55ceeebc-88a8-4cfd-b5cb-ff14601c9c25.png)
提示网不太好

**Comment by 1294266616** [comment]
应该不是日榜能看，代理也能正常访问网站

**Comment by 1294266616** [comment]
> 我本地无法复现，服务器上能访问hibiapi那边的接口吗
接口可以访问，现在是偶尔其他排行榜可以出来图片但过会就不行了😂

**Comment by HibiKier** [comment]
建议自建hibiapi试试

**Comment by 1294266616** [comment]
> 建议自建hibiapi试试

很奇怪之前有自建个不能用，现在又能用了最近也就更新下bot不过能用就好了，谢谢
