### ISSUE TITLE
修改图片md5似乎没有生效

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#833]
### 系统版本：
![系统](https://user-images.githubusercontent.com/105090141/174449332-36ced40c-667b-429b-b0b1-dad9406a49c8.png)

### 真寻版本：0.1.5.9
https://github.com/HibiKier/zhenxun_bot/commit/3b8d52bcb5f7a224c4f3bdbcfce854ba82ca4359

### 错误说明
向真寻发送了几次色图r指令，其中有两张图片被夹：
![色图被夹](https://user-images.githubusercontent.com/105090141/174450000-138d87d2-1b0d-401e-807c-1f3bfd06d91d.png)

指定图片id（就是被夹的这两张图的id）即可正常发送：
![色图1](https://user-images.githubusercontent.com/105090141/174450150-af6a689e-1b9c-4643-8bae-06199e8b3e4f.png)
![色图2](https://user-images.githubusercontent.com/105090141/174450172-7a6dce60-0bca-480c-bf3c-aabacea5b668.png)

**Comment by ZZZ-zero** [comment]
我最近也遇到这个问题，问题可能出在我最近将色图图库手动清空，而没有清空数据库内的色图数据，导致只发出数据而没有图片，但是现在也不敢动数据库，问题暂时搁置。
