### ISSUE TITLE
升级go-cqhttp v1.0.0-rc2后，群词条添加图片还是有点问题

### ISSUE THREAD

**Issue by saferabbit** [HibiKier/zhenxun_bot#841]
### 真寻版本：0.1.6.0

![{086DK)(X%H83MC{R$}90CS](https://user-images.githubusercontent.com/44218328/174720408-a77bf3b5-cdba-4df5-bc10-c7c051767530.png)

### 错误说明

群词条匹配还是有点问题，有大佬查看下吗？看了lssue，也修改过了还是出现，估计是升级go-cqhttp v1.0.0-rc2？

**Comment by HibiKier** [comment]
56ea3964a738eb6d6c472b1b7642d11222f297a2 现在还有吗？

**Comment by saferabbit** [comment]
现在没有了，感谢大佬回答
