### ISSUE TITLE
安装依赖时遇到问题

### ISSUE THREAD

**Issue by yuyezhige** [HibiKier/zhenxun_bot#843]
### 日志截图

![image](https://user-images.githubusercontent.com/53608949/174785201-50d75f9b-bd47-466c-b003-d147cd2a0859.png)

请问该如何解决这个问题

**Comment by FiresonZ** [comment]
先安装poetry吧...
pip install poetry

**Comment by yuyezhige** [comment]
第一步已经做过了，现在再弄是这样
![image](https://user-images.githubusercontent.com/53608949/174827007-da45eaf5-b828-4412-aa5e-d67398ed0b15.png)

**Comment by FiresonZ** [comment]
这不是好了吗

**Comment by yuyezhige** [comment]
可能是与python有关，我重装了python后没有遇到任何问题
