### ISSUE TITLE
更新0.1.6.0之后 pix num指令还是在报错

### ISSUE THREAD

**Issue by Narmaya-gbf** [HibiKier/zhenxun_bot#844]
### 日志截图

![1OVXFN~TI)07@)3 NGU7ISN](https://user-images.githubusercontent.com/66237606/174922272-27008b61-84d6-4ab9-8a39-8f24a78c73fc.png)

### 错误说明
在按照要求替换以下目录
![5S~XUXWI1X_~~5ZR_ILX YR](https://user-images.githubusercontent.com/66237606/174922384-b205de74-2ff5-4b4c-a838-60242511cdc2.PNG)
文件升级后，使用 pix  -s  num 指令还是在报错

**Comment by HibiKier** [comment]
你pix数据库里有东西吗
