### ISSUE TITLE
关于原神每日素材更新失败以及BILIBILI推送延迟过高发生错误，貌似和playwright有关

### ISSUE THREAD

**Issue by VoplsX** [HibiKier/zhenxun_bot#85]
![B}G~8RT1G22CJ_4 S0%~(OV](https://user-images.githubusercontent.com/23568231/145282206-d5f2c873-f9da-4f66-b0b3-ebed64840110.png)
![GM`%N_LVQS~W{F`{7${6THR](https://user-images.githubusercontent.com/23568231/145282259-fad03968-9124-4fa7-9edb-59c67db355bb.png)

如图，用的是阿里云，开启了反代，其他功能（包括pix）都正常 就这俩。。是网络问题么？

**Comment by VoplsX** [comment]
![NJ}Y5IB4EX$3SI%7X_J40W6](https://user-images.githubusercontent.com/23568231/145282678-8b443452-e25d-4e19-ac15-b313d5360e4e.png)
刚看到一个这个错误，不知是否有关
以及avator的一个错误
![C}WI{ 66}W2$@34G3Z}CR%M](https://user-images.githubusercontent.com/23568231/145282860-b0e643d0-4523-4784-9810-208de10c3eaa.png)
，非常抱歉问题这么多，希望作者大大能解答xD

**Comment by HibiKier** [comment]
Timeout是网络问题，pip install imageio

**Comment by VoplsX** [comment]
好的，非常感谢!
