### ISSUE TITLE
B站动态转发和直播通知无效

### ISSUE THREAD

**Issue by SHDocter** [HibiKier/zhenxun_bot#850]
没有报错的log
在最开始有置顶动态的时候报过一下错，之后就没有任何错误log了

[ERROR] plugins | B站订阅：获取用户动态 发送错误 <class 'playwright._impl._api_types.TimeoutError'>：Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".bili-dyn-list__item >> nth=0" to be visib

**Comment by HibiKier** [comment]
超时了

**Comment by SHDocter** [comment]
那有什么办法能解决吗

**Comment by HibiKier** [comment]
提供一下订阅id？

**Comment by SHDocter** [comment]
31842
