### ISSUE TITLE
epic在群里面使用，插件报错

### ISSUE THREAD

**Issue by 1294266616** [HibiKier/zhenxun_bot#853]
### 错误日志
[error_2022-06-25.log](https://github.com/HibiKier/zhenxun_bot/files/8984532/error_2022-06-25.log)

### 日志截图

![bug](https://user-images.githubusercontent.com/52421598/175770334-89f2ffc9-ef1b-4091-82ae-e7d8001b499b.png)

### 错误说明

好友聊天里面可以正常获取，群里面发就报错请问是哪出问题了

**Comment by HibiKier** [comment]
大概率风控

**Comment by 1294266616** [comment]
> 大概率风控

从21号搭建到现在26号群一直发不出去的，还要继续等吗？

**Comment by HibiKier** [comment]
可以
