### ISSUE TITLE
为啥go-cqhttp获取Ticket 时出现错误啊

### ISSUE THREAD

**Issue by Cintser** [HibiKier/zhenxun_bot#854]
### 错误截图
![image](https://user-images.githubusercontent.com/98868806/175777202-93f89772-d216-4981-8add-4f957f8dcdca.png)

![E2`MMQ4$~M0FJ`%3%XI22MC](https://user-images.githubusercontent.com/98868806/175777258-6ef5906e-893d-42c9-97b7-490b9bcb58cd.png)

[img]

### 日志截图

[img]

### 错误说明
我扫二维码登录qq时出现这玩意，不太懂
（我不太会用github，而且是英文，谷歌翻译功能不见了，请见谅）
（请问群什么时候能公开啊）

**Comment by MingxuanGame** [comment]
试试使用滑条登录

**Comment by Cintser** [comment]
本来第一张图是滑条登录出问题的cmd截图




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月25日(星期六) 晚上10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 为啥go-cqhttp获取Ticket 时出现错误啊 (Issue #854)





 试试使用滑条登录

**Comment by Cintser** [comment]
啊这好像




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月25日(星期六) 晚上10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 为啥go-cqhttp获取Ticket 时出现错误啊 (Issue #854)





 试试使用滑条登录

**Comment by Cintser** [comment]
阿西吧xdm发错图了怎么办



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月25日(星期六) 晚上10:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 为啥go-cqhttp获取Ticket 时出现错误啊 (Issue #854)





 试试使用滑条登录

**Comment by HibiKier** [comment]
去gocq issues里提
