### ISSUE TITLE
使用添加商品指令后报错

### ISSUE THREAD

**Issue by Kairinsama** [HibiKier/zhenxun_bot#855]
### 错误截图

![错误截图](https://user-images.githubusercontent.com/80304836/175803669-8d7e8069-22ad-4446-8049-df653365e84c.png)

### 错误说明

使用添加商品指令后报错
![图片1](https://user-images.githubusercontent.com/80304836/175803830-d3542cc9-5fa1-4764-9869-23c76ae9d62f.png)

**Comment by HibiKier** [comment]
你代码没更新全，用最新的

**Comment by Kairinsama** [comment]
> 你代码没更新全，用最新的

这个机器人是我刚刚部署的，直接用的最新的代码。第一次安装好后也是报这个错误，然后我把整个文件夹删了重新安装后还是这样。

**Comment by HibiKier** [comment]
40da48e685d76fed480beea001df4a9bece4cd5a

**Comment by Kairinsama** [comment]
问题已解决
