### ISSUE TITLE
赛马插件报错

### ISSUE THREAD

**Issue by Tamakoy** [HibiKier/zhenxun_bot#856]
### 日志截图
![QQ截图20220626161944](https://user-images.githubusercontent.com/108110130/175806267-4038200e-2b71-4b8c-a6d6-38c2b4b311f2.png)

### 错误说明
安装好赛马插件后前部分功能都能使用，在玩家加入比赛后说 赛马开始 后就如上图一样报错了，希望得到解决方法

**Comment by HibiKier** [comment]
第三方插件别在这发issues
