### ISSUE TITLE
昵称插件无效

### ISSUE THREAD

**Issue by Amoslzh** [HibiKier/zhenxun_bot#86]
![image](https://user-images.githubusercontent.com/93984484/145659152-b2c5b781-ffb9-478b-a095-65ae86989e3c.png)
![image](https://user-images.githubusercontent.com/93984484/145659159-e5217fbf-dc68-4e4b-9de3-5c0eb306a189.png)
版本为0.0.66
![image](https://user-images.githubusercontent.com/93984484/145659297-b3224e51-763d-4418-ba6a-b4aa743fb49a.png)

**Comment by HibiKier** [comment]
艾特她
