### ISSUE TITLE
更新最新文件后bilibili插件加载报错

### ISSUE THREAD

**Issue by Excalibur5100** [HibiKier/zhenxun_bot#862]
### 错误截图
![image](https://user-images.githubusercontent.com/105792144/175953698-83cce1d7-10fe-4eba-9baf-fdb0436ebd47.png)

### 错误说明

如题如图

**Comment by HiDolen** [comment]
我也是一样的错误

**Comment by HibiKier** [comment]
poetry update

**Comment by Excalibur5100** [comment]
> poetry update

感谢，解决了
