### ISSUE TITLE
无法更新omega图库

### ISSUE THREAD

**Issue by 283Gawin** [HibiKier/zhenxun_bot#863]
### 错误截图

![image](https://user-images.githubusercontent.com/69577009/175973330-d31c19d1-575e-416b-b84b-82f3999e09fe.png)

[img]

### 日志截图
![image](https://user-images.githubusercontent.com/69577009/175972810-3ae65153-6ac0-4f34-a9ff-c59b79bb33d6.png)
![image](https://user-images.githubusercontent.com/69577009/175972993-9502a7bd-5aaa-4e77-a11e-455848660b64.png)

[img]

### 错误说明

omega图库无法更新，sql已放置于根目录

**Comment by HibiKier** [comment]
把数据库文件名称改成omega_pixiv_illusts

**Comment by 283Gawin** [comment]
已解决
