### ISSUE TITLE
色图num默认参数太高

### ISSUE THREAD

**Issue by swearl** [HibiKier/zhenxun_bot#864]
### 真寻版本：0.1.6.0

好像从昨天开始, num最大值只能20, 现在默认100, 返回空data
```json
{
  "error": "",
  "data": [
  ]
}
```

**Comment by chengfsrc** [comment]
lolicon图库修改了api调用，现在加参数都无法进行搜索了，好像也限制了一次最多返回20

**Comment by HibiKier** [comment]
27b89b333a0b5f3da0c09ef4001125eac2093cdd
