### ISSUE TITLE
web_ui报错

### ISSUE THREAD

**Issue by bbyyds** [HibiKier/zhenxun_bot#867]
### 错误截图
![image](https://user-images.githubusercontent.com/59153565/176180478-76a7692a-2f8a-49af-af31-cca409ae0182.png)

### 日志截图
![image](https://user-images.githubusercontent.com/59153565/176180618-ea1e527d-5860-41dc-8836-07106a726319.png)

### 错误说明

自动更新出错打不开了，然后重装了一下，就这个报错了

**Comment by HibiKier** [comment]
issues里有，你翻翻

**Comment by bbyyds** [comment]
> issues里有，你翻翻

我用的就是最新的代码

**Comment by HibiKier** [comment]
和代码没关系，你装的包的问题

**Comment by bbyyds** [comment]
> 和代码没关系，你装的包的问题

我没有在issues里找到其他的相关问题，可以在说一下嘛？麻烦你了

**Comment by bbyyds** [comment]
> 和代码没关系，你装的包的问题

我把issues都翻了一遍，没找到

**Comment by HibiKier** [comment]
https://github.com/HibiKier/zhenxun_bot/issues/267
