### ISSUE TITLE
朋友说功能建议加上触发条件

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#869]
![image](https://user-images.githubusercontent.com/105090141/176349657-e357cfe7-03b3-47fc-9a52-5cbc8022cb34.png)
经常突然冒出来=_=

**Comment by XKaguya** [comment]
![image](https://user-images.githubusercontent.com/96401952/176407490-4da07bd4-d975-48ca-a14b-b86b07c1121e.png)

**Comment by XKaguya** [comment]
不过貌似有的插件不支持 不太清楚

**Comment by XKaguya** [comment]
哦抱歉 我审题不仔细 可能没用
