### ISSUE TITLE
原神黄历显示问题

### ISSUE THREAD

**Issue by a970703218** [HibiKier/zhenxun_bot#87]
![4b09d8fb07588926](https://user-images.githubusercontent.com/48351858/145661352-f6ffe84f-89f1-4462-b035-9c63e1835bf6.png)
大佬大佬，显示成这样了，昨天还好好的。

**Comment by HibiKier** [comment]
查看文档FQA

**Comment by a970703218** [comment]
> 查看文档FQA

好的，感谢大佬
