### ISSUE TITLE
超级管理员私聊图片上传错误

### ISSUE THREAD

**Issue by ChthollyWn** [HibiKier/zhenxun_bot#870]
### 错误截图

![image](https://user-images.githubusercontent.com/85938618/176355371-31fd1cf8-3684-43c0-8aab-516a4888e963.png)

### 日志截图

![@1`XW60V{Z%USE5 G021_2E](https://user-images.githubusercontent.com/85938618/176355752-c42301d2-f473-46d6-904e-41b0e98ea473.png)

bot日志中没有报错

### 错误说明

当超级管理员在对bot私聊时，bot发送图片会失败，文本消息正常输出，gocq后台有para error错误，bot后台没有报错信息，
在群聊消息中图片发送正常，好友私聊时也正常，目前只发现超级管理员私聊图片发送失败

**Comment by HibiKier** [comment]
尝试换gocq版本
