### ISSUE TITLE
看到转发解析有人修复了激动的pull了代码然后

### ISSUE THREAD

**Issue by Misakami** [HibiKier/zhenxun_bot#872]
### 错误截图
![image](https://user-images.githubusercontent.com/22981008/176405879-3d798c75-473b-41b1-9303-831abcba3289.png)

### 日志截图

[img]

### 错误说明

尝试使用了pip install bilireq并没有成功。求助。。。

**Comment by HibiKier** [comment]
poetry update

**Comment by xipesoy** [comment]
> 诗歌更新

逮住了！我的阿咪老婆
