### ISSUE TITLE
商店折扣功能不显示折扣后价格

### ISSUE THREAD

**Issue by RShock** [HibiKier/zhenxun_bot#873]
### 错误截图
![EOFFP%8~EGRY{`K9XMM DHM](https://user-images.githubusercontent.com/11630758/176435950-e61e3f6c-dccf-4114-86b3-d09ae1b41fb3.PNG)

### 错误说明

实际上商品是有折扣的，但是UI看不出来

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/177015938-d6d5aae6-b497-4d63-aa13-9fc5bcc9d69e.png)
e5c036cee81dfddae3b9fef91f2e4b5ae7302176
