### ISSUE TITLE
请教一下，“检查更新真寻”和“查看插件仓库”指令报错，提示“自动获取真寻版本失败....”和“文件下载失败或解压失败..”

### ISSUE THREAD

**Issue by TwoWenV587** [HibiKier/zhenxun_bot#874]
### 错误截图

![image](https://user-images.githubusercontent.com/108177273/176613849-b684201f-cfa2-4649-af3a-ef4f94c39050.png)

### 日志截图

![image](https://user-images.githubusercontent.com/108177273/176613905-94f69bd1-78fe-4f87-9b40-f782ad3b50c0.png)

### 错误说明
持续了好几天的问题，一直无法查看插件仓库和检查更新真寻，检索了issues之后发现了类似的问题
#817 #704 
挂了梯子，可以正常访问github，根据指示在AsyncHttpx.get后加上了verify=False，依然报错（和上述日志截图相同）
![image](https://user-images.githubusercontent.com/108177273/176615777-628413a9-aa5b-4a56-a6d0-a718af33edcd.png)
![image](https://user-images.githubusercontent.com/108177273/176615925-b865e03c-6db2-4e35-92d3-455a0dd162bd.png)
![image](https://user-images.githubusercontent.com/108177273/176615355-2810241c-6e11-4f39-9d13-9c7395e581ac.png)
还是说我加的不对T T
恳请帮助！谢谢！

**Comment by Unicorn369** [comment]
或者你在`https://github.com/`前面加上`https://ghproxy.com/`或`https://mirror.ghproxy.com/`
再试试行不行。挂了梯子记得关掉。还有是在前面加，别改错了。

**Comment by xipesoy** [comment]
不行就手动覆盖更新的文件（

**Comment by HibiKier** [comment]
这个文件里有AsyncHttp.get的你都给他加上

**Comment by borntree** [comment]
> 或者你在`https://github.com/`前面加上`https://ghproxy.com/`或`https://mirror.ghproxy.com/` 再试试行不行。挂了梯子记得关掉。还有是在前面加，别改错了。

老哥，这个具体是怎么改呢？我看plugins/check_zhenxun_update/data_source.py的url地址是https://api.github.com/repos/HibiKier/zhenxun_bot/releases/latest，并未找到https://github.com/
还是说另有其他文件
