### ISSUE TITLE
B站订阅动态后，发的动态图中文字全是方格

### ISSUE THREAD

**Issue by qq351959684** [HibiKier/zhenxun_bot#875]
平台是阿里云CentOS7 版本是v0.1.6.0

![8`I9P ($WR8N175Y(`XFA~H](https://user-images.githubusercontent.com/61103131/176657982-c9de524a-32ba-475c-bec3-7d42919c60fb.PNG)

**Comment by xipesoy** [comment]
服务器安装中文字体
