### ISSUE TITLE
B站订阅的动态图片中文字体全是方格

### ISSUE THREAD

**Issue by qq351959684** [HibiKier/zhenxun_bot#876]
服务器是阿里云centos7  真寻版本v0.1.6.0

![8`I9P ($WR8N175Y(`XFA~H](https://user-images.githubusercontent.com/61103131/176658207-fa4ed89f-dec2-4feb-90cc-e705f16029ba.PNG)

**Comment by yajiwa** [comment]
服务器安装中文字体
