### ISSUE TITLE
安装依赖出现的问题，python版本为3.8.10,看描述应该是pyproject.toml的问题？ 不知道如何解决

### ISSUE THREAD

**Issue by VanLewis2003** [HibiKier/zhenxun_bot#877]
root@orangepi3-lts:/home/orangepi/Desktop/bot/zhenxun_bot-main# poetry install
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

Package operations: 89 installs, 0 updates, 0 removals

  • Installing backports.zoneinfo (0.2.1): Failed

  EnvCommandError

  Command ['/root/.cache/pypoetry/virtualenvs/zhenxun-bot-s5IZ9irC-py3.8/bin/pip', 'install', '--no-deps', 'file:///root/.cache/pypoetry/artifacts/42/81/3c/a835fa124d7abf15eefd37c8d68980f2b7df7070002f071b1c16dcb291/backports.zoneinfo-0.2.1.tar.gz'] errored with the following return code 1, and output: 
  Processing /root/.cache/pypoetry/artifacts/42/81/3c/a835fa124d7abf15eefd37c8d68980f2b7df7070002f071b1c16dcb291/backports.zoneinfo-0.2.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: backports.zoneinfo
    Building wheel for backports.zoneinfo (pyproject.toml): started
    Building wheel for backports.zoneinfo (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    × Building wheel for backports.zoneinfo (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [41 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.linux-aarch64-cpython-38
        creating build/lib.linux-aarch64-cpython-38/backports
        copying src/backports/__init__.py -> build/lib.linux-aarch64-cpython-38/backports
        creating build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/_zoneinfo.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/_version.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/_tzpath.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/_common.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/__init__.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        running egg_info
        writing src/backports.zoneinfo.egg-info/PKG-INFO
        writing dependency_links to src/backports.zoneinfo.egg-info/dependency_links.txt
        writing requirements to src/backports.zoneinfo.egg-info/requires.txt
        writing top-level names to src/backports.zoneinfo.egg-info/top_level.txt
        reading manifest file 'src/backports.zoneinfo.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        /tmp/pip-build-env-7pd3avlv/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
          warnings.warn(msg, warning_class)
        warning: no files found matching '*.png' under directory 'docs'
        warning: no files found matching '*.svg' under directory 'docs'
        no previously-included directories found matching 'docs/_build'
        no previously-included directories found matching 'docs/_output'
        adding license file 'LICENSE'
        adding license file 'licenses/LICENSE_APACHE'
        writing manifest file 'src/backports.zoneinfo.egg-info/SOURCES.txt'
        copying src/backports/zoneinfo/__init__.pyi -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        copying src/backports/zoneinfo/py.typed -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
        running build_ext
        building 'backports.zoneinfo._czoneinfo' extension
        creating build/temp.linux-aarch64-cpython-38
        creating build/temp.linux-aarch64-cpython-38/lib
        aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/root/.cache/pypoetry/virtualenvs/zhenxun-bot-s5IZ9irC-py3.8/include -I/usr/include/python3.8 -c lib/zoneinfo_module.c -o build/temp.linux-aarch64-cpython-38/lib/zoneinfo_module.o -std=c99
        lib/zoneinfo_module.c:1:10: fatal error: Python.h: No such file or directory
            1 | #include "Python.h"
              |          ^~~~~~~~~~
        compilation terminated.
        error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for backports.zoneinfo
  Failed to build backports.zoneinfo
  ERROR: Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects
  

  at /usr/local/lib/python3.8/dist-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│ 
      1197│         return decode(output)
      1198│ 
      1199│     def execute(self, bin, *args, **kwargs):

**Comment by VanLewis2003** [comment]
这是使用pip安装后的报错
root@orangepi3-lts:/home/orangepi/Desktop/bot/zhenxun_bot-main# pip3 install  backports.zoneinfo
Collecting backports.zoneinfo
  Downloading backports.zoneinfo-0.2.1.tar.gz (74 kB)
     |████████████████████████████████| 74 kB 8.9 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: backports.zoneinfo
  Building wheel for backports.zoneinfo (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpx0qvw8w6 build_wheel /tmp/tmpsgt11f3s
       cwd: /tmp/pip-install-zr2yz1k1/backports.zoneinfo
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-cpython-38
  creating build/lib.linux-aarch64-cpython-38/backports
  copying src/backports/__init__.py -> build/lib.linux-aarch64-cpython-38/backports
  creating build/lib.linux-aarch64-cpython-38/backports/zoneinfo
  copying src/backports/zoneinfo/_zoneinfo.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
  copying src/backports/zoneinfo/_version.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
  copying src/backports/zoneinfo/_tzpath.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
  copying src/backports/zoneinfo/_common.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
  copying src/backports/zoneinfo/__init__.py -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
  running egg_info
  writing src/backports.zoneinfo.egg-info/PKG-INFO
  writing dependency_links to src/backports.zoneinfo.egg-info/dependency_links.txt
  writing requirements to src/backports.zoneinfo.egg-info/requires.txt
  writing top-level names to src/backports.zoneinfo.egg-info/top_level.txt
  reading manifest file 'src/backports.zoneinfo.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  /tmp/pip-build-env-lcouh8zi/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  warning: no files found matching '*.png' under directory 'docs'
  warning: no files found matching '*.svg' under directory 'docs'
  no previously-included directories found matching 'docs/_build'
  no previously-included directories found matching 'docs/_output'
  adding license file 'LICENSE'
  adding license file 'licenses/LICENSE_APACHE'
  writing manifest file 'src/backports.zoneinfo.egg-info/SOURCES.txt'
  copying src/backports/zoneinfo/__init__.pyi -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
  copying src/backports/zoneinfo/py.typed -> build/lib.linux-aarch64-cpython-38/backports/zoneinfo
  running build_ext
  building 'backports.zoneinfo._czoneinfo' extension
  creating build/temp.linux-aarch64-cpython-38
  creating build/temp.linux-aarch64-cpython-38/lib
  aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.8 -c lib/zoneinfo_module.c -o build/temp.linux-aarch64-cpython-38/lib/zoneinfo_module.o -std=c99
  lib/zoneinfo_module.c:1:10: fatal error: Python.h: No such file or directory
      1 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for backports.zoneinfo
Failed to build backports.zoneinfo
ERROR: Could not build wheels for backports.zoneinfo which use PEP 517 and cannot be installed directly

**Comment by Unicorn369** [comment]
你的python3 是源安装的，还是编译安装的，"Python.h"显示找不到，建议你卸载后重新安装或者重新编译安装。另外你的好像是香橙派，arm架构可能跑不了，我之前有用过，依赖环境全装好，最后运行全是报错。以为是系统问题，换Ubuntu，Debian，archlinux也不行。

**Comment by ZHANGYOU705** [comment]
You can try three commands to solve this problem：
seq1:
export C_INCLUDE_PATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/Headers
seq2:
pip install backports.zoneinfo
seq3:
python3 -m pip install Django
