### ISSUE TITLE
poetry安装依赖发生错误

### ISSUE THREAD

**Issue by AdminVivy** [HibiKier/zhenxun_bot#878]
### 错误截图
/usr/local/python3.8/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
can't set attribute
![image](https://user-images.githubusercontent.com/90098435/176879732-c9f5d611-5f9e-4660-8262-20006c3de66d.png)

### 错误说明
安装依赖发生报错...

**Comment by xipesoy** [comment]
python3 -m poetry shell

python3 -m poetry install
去试试这两个

**Comment by HibiKier** [comment]
你可以把poetry.lock删除重新poetry install

**Comment by xipesoy** [comment]
> 你可以把poetry.lock删除重新poetry install

逮住阿咪老婆惹！

**Comment by AdminVivy** [comment]
> python3 -m poetry shell
> 
> python3 -m poetry install 去试试这两个

谢谢，解决了
先进入虚拟环境就可以安装依赖，直接安装依赖就那样报错
