### ISSUE TITLE
b站订阅报错

### ISSUE THREAD

**Issue by ChthollyWn** [HibiKier/zhenxun_bot#881]
### 日志截图

![6cfca9ecc08601c1b568fc09e1bfa33](https://user-images.githubusercontent.com/85938618/177009742-4d24ee2f-f310-4b4a-9984-2bbfb006fe52.png)
![552f70bc0d486ac9a0d789c6756bbdd](https://user-images.githubusercontent.com/85938618/177009745-b88cfc62-c194-4c60-8124-8197f4f92eb2.png)

### 错误说明

playwright浏览器重新安装后也没用，请问这样有什么影响吗，如何解决呢
b站订阅一直出错，无从下手

**Comment by HibiKier** [comment]
可能你内存不够浏览器被干掉了
