### ISSUE TITLE
图片功能用不了，后台也没报错

### ISSUE THREAD

**Issue by 80546033** [HibiKier/zhenxun_bot#883]
### 错误截图
![Q%13(`K0B45FJCXNP DZB D](https://user-images.githubusercontent.com/67412155/177038037-dd22f317-b740-46ff-ad58-735705411b47.png)

[img]

### 日志截图
![image](https://user-images.githubusercontent.com/67412155/177038101-5f579957-8e4e-4fe0-a283-f69b0240d7aa.png)

[img]

### 错误说明

发生了xx错误...

**Comment by HibiKier** [comment]
更新代码

**Comment by 80546033** [comment]
> 更新代码

好像是说没导入sql文件，问一下怎么导入

**Comment by HibiKier** [comment]
和sql无关

**Comment by 80546033** [comment]
> 和sql



> 



> 和sql无关

可以了，感谢
