### ISSUE TITLE
B站订阅发送失败

### ISSUE THREAD

**Issue by nicewsc** [HibiKier/zhenxun_bot#884]
### 错误截图

![image](https://user-images.githubusercontent.com/59506907/177105233-a6e17c63-9ebd-48c5-bbc4-6d149a32e55b.png)

### 日志截图

![image](https://user-images.githubusercontent.com/59506907/177105552-cdee7d2b-600a-430f-8ff9-fb74898d8cd6.png)

### 错误说明

1.6.1更新了以后bilireq出了问题，更新了之后B站订阅出现问题，无法发送

以下是bilireq更新之前的错误信息
![image](https://user-images.githubusercontent.com/59506907/177105942-48f403b5-7c15-400f-a5ab-cfc97634fcbd.png)

**Comment by xiaorui158** [comment]
先改用老插件吧，在真寻的backup文件夹里有备份，等更新这个
