### ISSUE TITLE
更新后大量报错，无法找到错误原因

### ISSUE THREAD

**Issue by AlanMULI** [HibiKier/zhenxun_bot#888]
今天早上更新了昨天的最新版，然后重启时大量报错，无法启动机器人：（
log文件和error文件附在下面。
[2022-07-05.log](https://github.com/HibiKier/zhenxun_bot/files/9042496/2022-07-05.log)
[error_2022-07-05.log](https://github.com/HibiKier/zhenxun_bot/files/9042497/error_2022-07-05.log)

**Comment by yajiwa** [comment]
如果是虚拟环境运行的真寻，请在真寻目录运行poetry install

**Comment by xh22805** [comment]
更新后购买道具次数限制为零，请问怎么修改

**Comment by yajiwa** [comment]
> 更新后购买道具次数限制为零，请问怎么修改
ac57c01更新代码

**Comment by yajiwa** [comment]
> 更新后购买道具次数限制为零，请问怎么修改
[ac57c01](https://github.com/HibiKier/zhenxun_bot/commit/ac57c016a62b8bdcccd80e1e2e6a97a797a8a9fb)更新代码

**Comment by yajiwa** [comment]
> 更新后购买道具次数限制为零，请问怎么修改

[ac57c01](https://github.com/HibiKier/zhenxun_bot/commit/ac57c016a62b8bdcccd80e1e2e6a97a797a8a9fb)更新代码

**Comment by yajiwa** [comment]
> 更新后购买道具次数限制为零，请问怎么修改

[b6b569f](https://github.com/HibiKier/zhenxun_bot/commit/b6b569fff91de96488808921561354329c839248) 更新代码

**Comment by AlanMULI** [comment]
> 如果是虚拟环境运行的真寻，请在真寻目录运行poetry install

但是我没有用poetry运行真寻诶

**Comment by xh22805** [comment]
有可能onebot出问题了，重装吧

**Comment by yajiwa** [comment]
> > 如果是虚拟环境运行的真寻，请在真寻目录运行poetry install
> 
> 但是我没有用poetry运行真寻诶

缺啥安啥，pip install rich
