### ISSUE TITLE
 Saucenao识图失败..status：3

### ISSUE THREAD

**Issue by nicewsc** [HibiKier/zhenxun_bot#889]
### 错误截图
无error日志
### 日志截图
![image](https://user-images.githubusercontent.com/59506907/177262934-f5d60da7-471c-4287-b27b-0f2dc3d293f1.png)

### 错误说明

如图，这个问题貌似没有errorr日志记录
![29LU)3UNFIHUZE((ZCDR(@W](https://user-images.githubusercontent.com/59506907/177262990-5d7456d0-f803-4f2a-9f8d-cc36003dd61c.png)

**Comment by inkbloom** [comment]
+1 我的还出现了status：-1

**Comment by Otakusprpr** [comment]
+1
