### ISSUE TITLE
色图自动撤回功能

### ISSUE THREAD

**Issue by XKaguya** [HibiKier/zhenxun_bot#890]
### 错误截图
没发现
### 错误说明
![image](https://user-images.githubusercontent.com/96401952/177343009-bd8c9c5a-5430-45a5-bb7e-3d5ce9c29c16.png)
如图配置，如果有配置错误请指出 谢谢
真寻不会自动撤回，即使是单张单张，不是合并消息也不会撤回

**Comment by inkbloom** [comment]
好像没有单引号
