### ISSUE TITLE
开箱建议：通过金币购买箱子

### ISSUE THREAD

**Issue by Darphas** [HibiKier/zhenxun_bot#892]
主要解决刷屏问题，每天群内基本都是开箱灌水很无趣，建议按照箱子原价定价金币价格，顺便起到回收金币的作用

**Comment by Darphas** [comment]
怎么设置，我好像没有看到

**Comment by OrphanFaker** [comment]
data/configs/plugins2settings.yaml下面有cost_gold，默认的是0
