### ISSUE TITLE
B站订阅推送错误

### ISSUE THREAD

**Issue by yuyezhige** [HibiKier/zhenxun_bot#896]
### 错误截图

![image](https://user-images.githubusercontent.com/53608949/177693952-50488abf-9851-4008-a22e-16bb512c1066.png)
![image](https://user-images.githubusercontent.com/53608949/177694021-ac73473d-20f2-416b-b8f4-f51d955b6dd2.png)

**Comment by HibiKier** [comment]
poetry update,
![图片](https://user-images.githubusercontent.com/45528451/177710670-d0bbf826-b3d2-40b9-b2d2-072c875bab89.png)
网络超时

**Comment by yuyezhige** [comment]
感谢解答，已解决
