### ISSUE TITLE
send_setu随机本地发送失败

### ISSUE THREAD

**Issue by ZZZ-zero** [HibiKier/zhenxun_bot#898]
### 错误截图

[
![image](https://user-images.githubusercontent.com/30883525/177812064-0f0b2576-fb57-4bc5-a514-62c3216efb40.png)

### 日志截图

[img]

### 错误说明
'>=' not supported between instances of 'int' and 'str' 
字符对比错误，导致发送“色图”返回本地色图失败报错

**Comment by HibiKier** [comment]
暂时别用webui修改配置，你把config.yaml里setu的
![图片](https://user-images.githubusercontent.com/45528451/177904472-c1fe2498-ba33-4445-970b-663cd98261e9.png)
删了就行了
