### ISSUE TITLE
运行报错，换环境也会这样

### ISSUE THREAD

**Issue by Adsicmes** [HibiKier/zhenxun_bot#9]
![image](https://user-images.githubusercontent.com/79645438/125965622-a1f7fb15-6d1d-46df-be33-8a752f88656d.png)

**Comment by HibiKier** [comment]
windows系统的问题，建议使用linux系统或删除该功能

**Comment by Adsicmes** [comment]
这个是哪部分的功能，怎么删（

**Comment by HibiKier** [comment]
先在configs/config.py中删除
```Python
    'material_remind': {
        'level': 5,
        'cmd': ['今日素材', '天赋材料']
    },
```
后删除文件夹
plugins/genshin/material_remind.py 和 utils/browser.py文件，

**Comment by Adsicmes** [comment]
感谢，他没有问题了
