### ISSUE TITLE
请问如何关闭或者移除某些插件呢？

### ISSUE THREAD

**Issue by ID114514** [HibiKier/zhenxun_bot#90]
plugins2settings.yaml
default_status: false
貌似不起作用，还是能照常使用

**Comment by HibiKier** [comment]
这个只是入群后插件的默认开关状态，关于开关插件问题请直接查看文档内置插件使用部分

**Comment by ID114514** [comment]
> 这个只是入群后插件的默认开关状态，关于开关插件问题请直接查看文档内置插件使用部分

OK，那命令是在这改cmd 还是在插件里面改呢？

**Comment by HibiKier** [comment]
给bot发送命令就行了

**Comment by ID114514** [comment]
> 给bot发送命令就行了

呃 指的是修改命令，菜单一类的，使它更简洁

**Comment by HibiKier** [comment]
插件里改

**Comment by ID114514** [comment]
> 插件里改

ok多谢大佬指导

**Comment by ID114514** [comment]
> 插件里改

还要麻烦问下大佬，这个文字版的菜单是哪个插件的...

小真寻内置多种功能，通过发送命令可执行特殊操作
★★ 示例 ★★
　查询天气预报信息，示例：天气 深圳
    XXXXXX

**Comment by HibiKier** [comment]
是青云客的，和真寻无关

**Comment by ID114514** [comment]
> 是青云客的，和真寻无关

那么这个菜单的指令能不能修改掉，想把它给隐藏了

**Comment by HibiKier** [comment]
自己在ai插件里if else

**Comment by ID114514** [comment]
> 自己在ai插件里if else

是这个目录的插件吗  plugins/ai   貌似没找到相关命令内容...

**Comment by HibiKier** [comment]
没有命令，这是代码实现部分

**Comment by ID114514** [comment]
> 没有命令，这是代码实现部分

所以不能更改或者隐藏吗，，

**Comment by HibiKier** [comment]
可以，自己要修改代码

**Comment by ID114514** [comment]
> 可以，自己要修改代码

大佬能不能指条明路，只是想把命令改掉

**Comment by HibiKier** [comment]
这个是ai插件的回复，和 帮助 插件 不是一个东西
