### ISSUE TITLE
停了一次之后就启动不了了，说是无法导入包

### ISSUE THREAD

**Issue by Syozhi-1** [HibiKier/zhenxun_bot#901]
### 错误截图
![image](https://user-images.githubusercontent.com/58074198/177955543-9b96fb18-b0a4-449b-b3c2-ffcc019c24f0.png)

### 错误说明
报错信息：ImportError: cannot import name 'overrides' from 'nonebot.typing'
不知道什么原因，本想停掉真寻重启一次，删除了真寻的screen后再次重启就这样了，试了在虚拟环境中pip3 install nonebot，不行nonebot2也不行，更新nonebot2也不行，很烦，找不到问题原因

**Comment by Syozhi-1** [comment]
> 要不试试把 nonebot.typing 模块卸了重新装一下？

这个我试了，没找到模组，估计是我的命令有问题， pip3 install nonebot.typing
然后我把~/.cache整个目录都删掉了，把nonebot2依赖包也删完了
然后更换了pip源，从腾讯云的源换成了阿里云
重新poetry shell后提示没有nonebot模组，pip安装nonebot后成功启动了！
耶！！！
但是，我现在得跟着插件一个个报错去安装依赖包，**非常的折磨**

**Comment by Kurehava** [comment]
一般pip3这样用命令在环境中有多个python环境的情况下容易报错

可以试试找到bot调用的python的目录

python3.x -m pip uninstall nonebot.typing

python3.x -m pip install nonebot.typing
