### ISSUE TITLE
无法正常推送B站订阅

### ISSUE THREAD

**Issue by Kurehava** [HibiKier/zhenxun_bot#902]
### 日志截图

<img width="1022" alt="スクリーンショット 2022-07-08 18 57 18" src="https://user-images.githubusercontent.com/78236470/177969229-e028a926-9aad-40e4-8612-124e536411c4.png">

### 错误说明

无法正常推送B站订阅
显示超时

**Comment by HibiKier** [comment]
更新到最新代码

**Comment by Kurehava** [comment]
感谢回复！

部署的真寻已经使用的是最新版本，
服务器环境和更新版本一样无变化，
更新之前能正常推送，更新之后报错如上图

现在已经从 /backup 目录中提取上一版本bilibili_sub 替换新版本bilibili_sub，
老版本bilibili_sub能够正常推送

**Comment by Kurehava** [comment]
好的！麻烦了！我去更新下试试！
辛苦了！！
