### ISSUE TITLE
请求色图提示权限不足

### ISSUE THREAD

**Issue by barryblueice** [HibiKier/zhenxun_bot#903]
### 错误截图

权限不足

### 日志截图

07-08 19:06:08 [SUCCESS] nonebot | ONEBOT V11 2650167109 | [message.group.normal]: Message -1728874481 from 963215834@[群:1022831576] "@群机器人 色图"
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False>
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False> running complete
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False>
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from plugins.fudu, type=message, priority=999, temp=False>
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from plugins.fudu, type=message, priority=999, temp=False> running complete
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False>
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False> running complete
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False>
07-08 19:06:08 [INFO] nonebot | Event will be handled by <Matcher from plugins.fudu, type=message, priority=999, temp=False>
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from plugins.fudu, type=message, priority=999, temp=False> running complete
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False> running complete
07-08 19:06:08 [INFO] nonebot | Matcher <Matcher from basic_plugins.invite_manager, type=message, priority=999, temp=False> running complete

### 错误说明

发生了xx错误...

**Comment by barryblueice** [comment]
> > 我请求没问题，其他人请求就有权限问题😂……
> 
> 如果你把自己设置成为超级用户的话，你的权限默认为9级，群管理员默认5级，涩图权限要求为9级，可以在插件索引里面找到文档改一下。

好的谢谢大佬，那具体是哪一个文件

**Comment by luoxiyun** [comment]
在zhenxun_bot\data\configs\plugins2settings.yaml下搜索send_setu修改leve
![IF0{Q(U~) LG0QHMCM$DG_7](https://user-images.githubusercontent.com/106081898/178082372-9d11cd6d-28b9-49f6-a140-a3f94fadd318.png)
l

**Comment by luoxiyun** [comment]
未生效的话删除zhenxun_bot\data\manager下的group_manager.json重启小真寻即可

**Comment by luoxiyun** [comment]
还可以使用 重载配置 命令
