### ISSUE TITLE
签到功能在人数多的群风控

### ISSUE THREAD

**Issue by q56535** [HibiKier/zhenxun_bot#908]
### 错误截图
![MN CF8B(JPUHUB 8UGNZ3JE](https://user-images.githubusercontent.com/26663837/178086490-abf01d97-f1af-46bc-a7b8-489289bfb89d.png)

### 日志截图

太长了直接贴
https://pastebin.ubuntu.com/p/HRYkMQHs49/

### 错误说明

签到的时候只有群人数较多的群显示账号风控，人数少的群就不风控，且其他功能能正常使用，不显示账号风控

**Comment by xh22805** [comment]
我的人数少的和多的都会

**Comment by HibiKier** [comment]
风控我也管不了

**Comment by q56535** [comment]
只有签到是风控，其他的都没有问题

**Comment by yajiwa** [comment]
替换签到背景图片(resources\image\sign\sign_res\background\background_01.jpg)

**Comment by xh22805** [comment]
图片也不涩阿，怎么会提示风控捏

**Comment by q56535** [comment]
那可以尝试一下更改md5值

**Comment by fuyang0811** [comment]
我这边一样的问题，我这边所有群都风控了，包括只有几个人的小群。换了qq号还是被风控。

**Comment by qq351959684** [comment]
楼主解决了吗

**Comment by q56535** [comment]
目前可以肯定的是，签到是已经签上了，但是签到之后生成的图片发不出去

**Comment by q56535** [comment]
可以试着找到zhenxun_bot-main\resources\image\sign\today_card把图片删了然后再试一次

**Comment by fuyang0811** [comment]
我这边解决了，综合yajiwa和q5635的回复：
1.更换签到背景图片(resources\image\sign\sign_res\background\background_01.jpg)。
2.找到zhenxun_bot-main\resources\image\sign\today_card把图片删了，这样重新生成图片就可以发出去了。
其实第一步已经可以了，但是真寻会默认发之前存的文件，所以要第二步把缓存删掉。

**Comment by qq351959684** [comment]
谢谢fuyang 有效解决！

**Comment by Am2333** [comment]
> 我这边解决了，综合yajiwa和q5635的回复： 1.更换签到背景图片(resources\image\sign\sign_res\background\background_01.jpg)。 2.找到zhenxun_bot-main\resources\image\sign\today_card把图片删了，这样重新生成图片就可以发出去了。 其实第一步已经可以了，但是真寻会默认发之前存的文件，所以要第二步把缓存删掉。

谢谢，有效，已解决
