### ISSUE TITLE
初始化成功后输出Killed

### ISSUE THREAD

**Issue by kain-hao** [HibiKier/zhenxun_bot#91]
![](https://s2.loli.net/2021/12/11/IkboKBS2uaDQ3vx.png)
大概就是这样...内存明明只用了400多M
有没有办法能优化一下呢:(

**Comment by HibiKier** [comment]
大概率是原神地图下载合成的问题，这个米游社api返回的地图就是十几兆，先把genshin/query_resource_points关了吧

**Comment by kain-hao** [comment]
大佬这个要怎么关掉啊...是在data/configs/plugins2settings.yaml里吗

**Comment by HibiKier** [comment]
不是，最简单的就是删掉文件夹

**Comment by kain-hao** [comment]
哦哦哦谢谢大佬
