### ISSUE TITLE
如何在群晖中安装bot

### ISSUE THREAD

**Issue by tianshubenshu** [HibiKier/zhenxun_bot#914]
### 系统版本：DSM 7.1
现在使用群晖中docker安装，但是群晖没有vim，无法编辑congif

**Comment by wearshoes** [comment]
你可以ssh连上后 把文件download到本地 修改完后上传回去

**Comment by tianshubenshu** [comment]
群晖什么都没有，shell里并不能找到sz命令，甚至他没有apt-get和vim编辑



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 中午1:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
你可以ssh连上后 把文件download到本地 修改完后上传回去

**Comment by wearshoes** [comment]
![image](https://user-images.githubusercontent.com/30278479/178194032-4701ab37-1fcd-4d27-bf39-b652f5db8283.png)
一般工具都带这种文件处理的功能 下载后修改再上传

**Comment by tianshubenshu** [comment]
我在winscp中并不能查看那个目录后的文件，因为我是直接使用的docker容器，点击进去文件夹是空的





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 中午1:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 

 一般工具都带这种文件处理的功能 下载后修改再上传

**Comment by wearshoes** [comment]
你要是docker的话 直接把挂载目录挂到共享文件夹下直接就能在群晖里修改
![image](https://user-images.githubusercontent.com/30278479/178195390-5e071edc-6479-4492-a8c7-32c71da4dda2.png)

**Comment by tianshubenshu** [comment]
每一个文件夹都要挂载吗，我只挂载了一个，启动容器就强行停止了，能否方便截图下挂载存储空间那里是如何设置的呢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 中午1:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
你要是docker的话 直接把挂载目录挂到共享文件夹下直接就能在群晖里修改

**Comment by wearshoes** [comment]
![image](https://user-images.githubusercontent.com/30278479/178196142-3c8dbf6f-b733-418a-bf56-21adb8d65a6d.png)

**Comment by tianshubenshu** [comment]
我目前是这样设置，不会产生任何文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 中午1:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)

**Comment by wearshoes** [comment]
这不应该啊 你下载完镜像 配置好docker之后 开启 应该就会在这个挂载的目录里生成了文件才对。。是不是有什么报错

**Comment by tianshubenshu** [comment]
这样子配置好像会导致容器读不到任何文件然后强行停止



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午2:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
这不应该啊 你下载完镜像 配置好docker之后 开启 应该就会在这个挂载的目录里生成了文件才对。。是不是有什么报错

**Comment by wearshoes** [comment]
那应该是你那边配置错了 我的这个docker文件夹是通过filestation新建共享文件夹弄出来的
![image](https://user-images.githubusercontent.com/30278479/178199554-6d7cf724-d3e1-4cdb-b8cf-26094cdea489.png)

**Comment by tianshubenshu** [comment]
没问题啊，docker文件夹是共享文件夹，然后在里面新建zhenxun_bot文件夹，然后https://github.com/SinKy-Yan/zhenxunbot-docker页面中快速开始那条命令shh输入后就没有然后了（不排除我不太会使用那个命令）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午2:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
那应该是你那边配置错了 我的这个docker文件夹是通过filestation新建共享文件夹弄出来的

**Comment by wearshoes** [comment]
不需要命令 直接开启就行了

**Comment by tianshubenshu** [comment]
另外的，我看容器内终端的日志没有任何报错，但实际上qq中没有反应，是还需要其他什么步骤吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午2:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
那应该是你那边配置错了 我的这个docker文件夹是通过filestation新建共享文件夹弄出来的

**Comment by tianshubenshu** [comment]
我觉得出现问题大概率是我的无经验和无知导致的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午2:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
不需要命令 直接开启就行了

**Comment by wearshoes** [comment]
他这边其实还需要自己手动安装运行 go-cqhttp还有要在dokcer里启动一个progresql

**Comment by tianshubenshu** [comment]
jyishit/zhenxun_bot也需要吗？我看他写的内置了，go-cqhttp以及docker的progresql都已经按照文档完成配置了，因为群=群晖中没法进行构建环境那一步，就搜到那个写内置一切的了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午2:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
他这边其实还需要自己手动安装运行 go-cqhttp还有要在dokcer里启动一个progresql

**Comment by wearshoes** [comment]
我怎么没搜到这个项目。。。我是跟着本项目docker走的 确实写的不详细 基本都是自己摸出来的

**Comment by tianshubenshu** [comment]
这一个，现在正在龟速下载本项目的dockers镜像






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午2:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
我怎么没搜到这个项目。。。我是跟着本项目docker走的 确实写的不详细 基本都是自己摸出来的

**Comment by tianshubenshu** [comment]
y


原谅我的无知，该如何配置呢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
我怎么没搜到这个项目。。。我是跟着本项目docker走的 确实写的不详细 基本都是自己摸出来的

**Comment by wearshoes** [comment]
下完别启动 
先下一个progressql的docker

**Comment by tianshubenshu** [comment]
progressql的docker以及下好，但我不确定我的配置是否正确





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
下完别启动
 先下一个progressql的docker

**Comment by wearshoes** [comment]
那你配置好zhenxun的docker就启动看报错吧

**Comment by tianshubenshu** [comment]
是这个吗？好像下的不对







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午2:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
那你配置好zhenxun的docker就启动看报错吧

**Comment by tianshubenshu** [comment]
目前是报错这个






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午2:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
那你配置好zhenxun的docker就启动看报错吧

**Comment by wearshoes** [comment]
？没看到图

**Comment by tianshubenshu** [comment]
现在能否看到（莫不是之前的图都没发出去QAQ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
？没看到图

**Comment by wearshoes** [comment]
嗯 看不到图 也没看到你之前有图

**Comment by tianshubenshu** [comment]
bad




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
嗯 看不到图 也没看到你之前有图

**Comment by tianshubenshu** [comment]
小声问一句，能否给予更为方便的即时通讯方式，QQ、微信、tg


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HibiKier/zhenxun_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)





 
嗯 看不到图 也没看到你之前有图

**Comment by wearshoes** [comment]
394383401

**Comment by tianshubenshu** [comment]
我使用的是jyisht/zhenxun_bot这个镜像，貌似有些许不同，装载路径按您图片中的填写/bot，什么都不会生成，填写按他发行页中的文件结构填写/home就会停止运行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 中午1:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/zhenxun_bot] 如何在群晖中安装bot (Issue #914)
