### ISSUE TITLE
如何更改代码让bt在群聊中也能使用？

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#915]
看了 https://github.com/HibiKier/zhenxun_bot/issues/296 说是要改代码，但是我把PrivateMessageEvent改成GroupMessageEvent之后bt私聊群聊都没反应了
小白不会弄请教一下各位大佬怎么改
![image](https://user-images.githubusercontent.com/105090141/178205876-8c6730c2-5738-4775-8498-f2d9c3704556.png)
![image](https://user-images.githubusercontent.com/105090141/178205899-336cbbef-f07b-4c46-8e7d-f7eaa52ebc47.png)

**Comment by soulrewrite** [comment]
![image](https://user-images.githubusercontent.com/105762209/178260185-44b987d6-9a40-4b7f-9000-3b8e4bc81b3f.png)
只是开R18在配置里修改就行
pix是这2个
![image](https://user-images.githubusercontent.com/105762209/178260312-98d83cec-ba6a-47ca-90d8-b07f57b353f5.png)

我猜原贴改代码是说默认是打开状态

**Comment by HibiKier** [comment]
删了![图片](https://user-images.githubusercontent.com/45528451/178514473-924794b4-fe08-48e7-a869-5e344c161f4b.png)
