### ISSUE TITLE
安装poetry出错

### ISSUE THREAD

**Issue by TDuckQWQ** [HibiKier/zhenxun_bot#918]
python是3.9.13
安装依赖的时候error
![image](https://user-images.githubusercontent.com/62102282/178431171-0016e38e-4f9b-4063-a81f-2ebc09b15e2d.png)

**Comment by qq2867199593** [comment]
![image](https://user-images.githubusercontent.com/56507208/178465348-db8fb734-5063-492d-a8b5-4fc3ae2763bb.png)
我也报错

**Comment by HibiKier** [comment]
> python是3.9.13 安装依赖的时候error ![image](https://user-images.githubusercontent.com/62102282/178431171-0016e38e-4f9b-4063-a81f-2ebc09b15e2d.png)

把poetry.lock删了试试

**Comment by TDuckQWQ** [comment]
> > python是3.9.13 安装依赖的时候error ![image](https://user-images.githubusercontent.com/62102282/178431171-0016e38e-4f9b-4063-a81f-2ebc09b15e2d.png)
> 
> 把poetry.lock删了试试
![image](https://user-images.githubusercontent.com/62102282/178539961-25ed15ff-a15d-4da0-83d4-e5a84aae012b.png)
可以了！
