### ISSUE TITLE
b站转发解析无反应

### ISSUE THREAD

**Issue by 1294266616** [HibiKier/zhenxun_bot#919]
### 错误截图

![image](https://user-images.githubusercontent.com/52421598/178521203-d4e09f28-e4c3-4e31-a093-0ec4928f8f72.png)

### 日志截图

![image](https://user-images.githubusercontent.com/52421598/178521054-0e0c24be-b29c-489b-bc49-3722a37948b3.png)

### 错误说明
群转发b站链接过去无反应，多次尝试也是如此，无报错插件也正常加载，请问是那方面的问题

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/180619236-1d62b695-2faa-4655-a65d-8b47e7c2da6f.png)
你这分享是怎么操作的。如何复现

**Comment by 1294266616** [comment]
奇怪有时候突然出来了，正尝试还会复现不

**Comment by 1294266616** [comment]
结果出来了qq辅助模块把小程序的改了应该就是这个导致识别不出
