### ISSUE TITLE
新手请教pix模块导入omega图库应该怎么操作

### ISSUE THREAD

**Issue by bjl101501** [HibiKier/zhenxun_bot#92]
![image](https://user-images.githubusercontent.com/82082262/145701275-5e71b504-d774-4897-8f5c-b44c21c57094.png)
按照教程放置数据库，发送检测omega图库后，直接死机了，不知道是不是我的轻量配置太垃圾的事，试了几次后都是如此
`12-11 17:23:33 [INFO] nonebot | 检测到OmegaPixivIllusts数据库，准备开始更新....`
每次发送检测omega图库后日志最后一条就是这个，不重启就一点反应都没有，最后这一次没管，一直到早上五点多自己重启了才正常

**Comment by HibiKier** [comment]
一般配置的轻量都会爆炸的，这里给两条建议
1.使用本地pgadmin导入
2.在某条issues中找到psql版本的数据库（是有的，问题差不多，但忘了是哪个）
