### ISSUE TITLE
poetry安装时候出错

### ISSUE THREAD

**Issue by MisakaMikoto2233** [HibiKier/zhenxun_bot#920]
![image](https://user-images.githubusercontent.com/108781155/178522960-4903bab4-62cc-4680-9315-9038d27137f3.png)
一到这里就出错，pip换源也试过，删了重来也试了，每次都是安装这俩时候error了（哭）

**Comment by MisakaMikoto2233** [comment]
如果把poetry.lock删了之后会卡在这
![image](https://user-images.githubusercontent.com/108781155/178526635-51f8cb8a-037e-4dc1-80d1-9df2500d4596.png)

**Comment by TDuckQWQ** [comment]
> 如果把poetry.lock删了之后会卡在这 ![image](https://user-images.githubusercontent.com/108781155/178526635-51f8cb8a-037e-4dc1-80d1-9df2500d4596.png)

干等就完事了，刚刚才发过issue

**Comment by MisakaMikoto2233** [comment]
> 



> > 如果把poetry.lock删了之后会卡在这 ![image](https://user-images.githubusercontent.com/108781155/178526635-51f8cb8a-037e-4dc1-80d1-9df2500d4596.png)
> 
> 干等就完事了，刚刚才发过issue

我删了之后等了十分钟，然后开始安装了，然后又跟第一张图一样error，，，

**Comment by HibiKier** [comment]
你py3.10？

**Comment by Snaessssss** [comment]
我也遇到同样的问题，作者解决了吗？

**Comment by MisakaMikoto2233** [comment]
> 我也遇到同样的问题，作者解决了吗？

我是往下找别人遇到的问题然后找到一个视频教学，重新跟着那人视频一步一步做了一遍然后就成功了，没再遇到这个问题了
