### ISSUE TITLE
真寻的插件__plugin_count_limit__在max_count修改之后还是会使用之前的数值

### ISSUE THREAD

**Issue by YH1345246294** [HibiKier/zhenxun_bot#922]
### 错误截图

![2V27N%ZOQE2PGG Y BRQOUS](https://user-images.githubusercontent.com/22020116/178702140-98482e15-1c7b-4e2e-b1a7-e93b09ebe70c.png)

### 日志截图

[img]

### 错误说明

我自己去修改了福利金插件的__plugin_count_limit__的max_count配置，但是真寻还是会使用之前的数值，无论干脆删掉__plugin_count_limit__配置还是设置status为False都没有用，重启也无法解决

**Comment by YH1345246294** [comment]
07-13 17:25:07 [SUCCESS] nonebot | ONEBOT V11 642094420 | [message.group.normal]: Message -1050303663 from 765647303@[群:232923827] "行行好给点钱"
07-13 17:25:07 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
07-13 17:25:07 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
07-13 17:25:07 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
07-13 17:25:07 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
07-13 17:25:07 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
07-13 17:25:08 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
07-13 17:25:08 [INFO] nonebot | Event will be handled by <Matcher from plugin.TZfulijin, type=message, priority=5, temp=False>
07-13 17:25:08 [INFO] nonebot | Matcher <Matcher from plugin.TZfulijin, type=message, priority=5, temp=False> running is cancelled
07-13 17:25:08 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False>
07-13 17:25:08 [INFO] nonebot | Matcher <Matcher from basic_plugins.apscheduler, type=message, priority=9, temp=False> running complete
07-13 17:25:08 [INFO] nonebot | Event will be handled by <Matcher from plugins.ai, type=message, priority=998, temp=False>
07-13 17:25:08 [INFO] nonebot | Matcher <Matcher from plugins.ai, type=message, priority=998, temp=False> running is cancelled
补个日志

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/178860833-f54420d3-1566-46a9-956b-37c5a78641be.png)

**Comment by YH1345246294** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/178860833-f54420d3-1566-46a9-956b-37c5a78641be.png)

非常感谢
