### ISSUE TITLE
模块错误集合

### ISSUE THREAD

**Issue by Lost-in-Tianyi** [HibiKier/zhenxun_bot#923]
个人安装的时候出现的问题，仅供参考，欢迎大家来补充，直接CTRL+F搜索即可。
win7真特么操蛋。用的an装的python，只能一个个测出问题来，，
前六个有的是模块，有的是不可抗力的问题，
1. no module named [cv2](https://blog.csdn.net/weixin_39450145/article/details/104801730)
2. no module named [PIL](https://blog.csdn.net/weixin_44037416/article/details/96842058)
3. [no module named nonebot.adapters](https://blog.csdn.net/weixin_44037416/article/details/96842058)
4. [ModuleNotFoundError: No module named ‘ruamel‘](https://blog.csdn.net/hhhhhhhhhhwwwwwwwwww/article/details/118719980)
5. [playwright 打包程序 无法定位程序输入点gethostname于动态链接库ws2_32.dll上](https://www.cnblogs.com/carl-/p/16017737.html)
6. [no module named 'pytz'](https://blog.csdn.net/hellokandy/article/details/91542680)
大多都是库问题：
cn2an
scripts
lxml
bilireq
matplotlib
retry
retrying
rich
nonebot-plugin-apscheduler
aiohttp
jose
jieba
feedparser
bs4
emoji
dateparser
psutil
wordcloud
也可以依照上面写一个requirement。

**Comment by HibiKier** [comment]
。除了5不都是依赖没装上吗。。不是已经提供pyproject.toml吗
