### ISSUE TITLE
这个机器人是不是已经阵亡了

### ISSUE THREAD

**Issue by weltck** [HibiKier/zhenxun_bot#925]
我这个是不是机器人已经阵亡了啊
在群里怎么交互都没用，甚至是gocq和bot的都要ctrl+c刷新一下才出来最新的消息
![U0UD2@IFX5OI 92H5 Y `C](https://user-images.githubusercontent.com/106135805/179336762-a3039740-3dd7-4267-b5db-8f444a0259b1.png)

**Comment by lalalavard** [comment]
我也一样   在某个群发不出信息, 别的群可以  是QQ的问题, 换个账号 或者解除风控

**Comment by weltck** [comment]
好吧

**Comment by Am2333** [comment]
是的，尤其是签到功能，有人能用有人不能用
已经尝试了修改devices.json，删除session.json，更换账号，设备锁，都无法解决该问题

**Comment by lalalavard** [comment]
> > 我也一样 在某个群发不出信息, 别的群可以 是QQ的问题, 换个账号 或者解除风控
> 
> 如何解除风控，麻烦告知，我更换账号还是遇到风控问题

我的话是尝试了一下大概方法.  能够解除风控, 但有时还是会封控 , 但是重启zhenxun 也会自己好
1.  给QQ加上设备锁,
2. 加上设备锁后, 修改 config.yml 的 password 为 空, 使其 登录为扫码登录
3. 重新扫码登录, 期间显示 需要在同一wifi下登录 ,  也就是我本地网络地址 和我 云服务器商ip地址不在同一地区 , 我的话是 在本地电脑 登录 ./go-cqhttp ,然后将 生成的 device.json 和 session.token 拷贝的服务器网络, 重新输入密码后正常登录
4.  如果还不行, 可以尝试 修改 qq密码 或者 将 device.json 的 protocal 修改为 1 走安卓协议( 默认为5 ipad协议)

**Comment by Am2333** [comment]
> * **若只是签到功能异常的话，其它功能正常使用的话**，可以进入**真寻根目录下的resources/image/sign/sign_res/background**，重新找一张图片，把**background_01.jpg**覆盖替换掉。
>   ![image](https://user-images.githubusercontent.com/101381538/179481075-091668a3-32e3-403a-aa75-662b9ccd0190.png)
> * **PS：替换后的图片仍需保持名称为background_01.jpg**不变，分辨率目前看来没有太大的要求，大于原图片的分辨率也可以，**图片格式为jpg**

已经替换，但是在go-cqhttp的log界面还是显示账号风控。
刚刚尝试了三个群，但是只在一个群签到成功，有图片发出，其他两个均提示风控

**Comment by Am2333** [comment]
> 
1 2 3 4 都尝试了，现在的情况仍然没有变化
目前看来只有签到受到影响，而且极其不稳定，在三个群之间，完全随机风控

**Comment by q56535** [comment]
一般风控发不出来的都是图片问题

**Comment by Am2333** [comment]
> 一般风控发不出来的都是图片问题

谢谢，尝试有效，问题已解决
