### ISSUE TITLE
真寻不回复也不处理群友请求的问题

### ISSUE THREAD

**Issue by qq351959684** [HibiKier/zhenxun_bot#927]
### 错误截图

群A的群友发送签到和签到排行，真寻没有回复，到服务器查看也没有群友的签到图，好感度没有上升。但是我作为超管，在群A发送签到和签到排行可以正常被回复。
![image](https://user-images.githubusercontent.com/61103131/179367884-4ca6c219-4c5c-444a-8e9c-30c47c35183f.png)

![image](https://user-images.githubusercontent.com/61103131/179367917-b8f04556-1343-4b22-a355-47f3c244383c.png)

于是我把我的小号和真寻拉了个群B，小号在群B发送签到和签到排行，真寻正常处理。

### 日志截图
cq后台无风控提示。
![image](https://user-images.githubusercontent.com/61103131/179367957-40ac3c3a-a465-44d7-887f-9981c28ed61e.png)

请问怎么解决呢？

**Comment by qq351959684** [comment]
![image](https://user-images.githubusercontent.com/61103131/179368269-3b1eee59-64dd-4e70-b640-6b423cbd6f57.png)

**Comment by Par1y** [comment]
咱也是这个问题，除了一个群其他都能回复，超级用户必须@机器人才会回复

**Comment by qq351959684** [comment]
好多模块都cancelled了

**Comment by qq351959684** [comment]
已经解决，原来是休眠了，发送xx醒了即可
