### ISSUE TITLE
服务器内存一直增加直到服务器崩溃

### ISSUE THREAD

**Issue by rcoplo** [HibiKier/zhenxun_bot#93]
系统：CentOS 8.2
程序:0.0.6.6
Postgresql 11.0
服务器配置2-4
一运行机器人，内存就一直在缓慢增加，没几个小时服务器就崩了，只能重启
QAQ

**Comment by HibiKier** [comment]
请使用top查看内存占用情况，虽然长时间运行会增加一定内存，但基本不会奔溃

**Comment by rcoplo** [comment]
目前解决了,不知道是什么原因
