### ISSUE TITLE
关于签到和搜图的问题

### ISSUE THREAD

**Issue by Qian033** [HibiKier/zhenxun_bot#931]
### 真寻版本：0.1.5.3

签到显示群内被风控
![SZE0@HMTB(}ZEP2)6J4S)_Y](https://user-images.githubusercontent.com/96489171/179693540-b7ea2ea3-e5cc-4b00-b12d-2558c5b34499.png)

搜图时显示网络不太好/没有该页数但gocq上没有风控
![image](https://user-images.githubusercontent.com/96489171/179693170-dba003fc-7904-4e7c-b6a2-cb802aac01ba.png)

**Comment by HibiKier** [comment]
签到可以尝试替换签到默认背景图，搜图要看hibiapi返回和网络
