### ISSUE TITLE
当日开箱后修改开箱次数，次数会变成负的并且可以无限开箱

### ISSUE THREAD

**Issue by Frankcsc** [HibiKier/zhenxun_bot#933]
### 错误截图

![FA69JXI1 GT~3896@6PF{HM](https://user-images.githubusercontent.com/45666537/179777607-5228c1cf-562e-4b12-b008-29a7282b6215.jpg)

### 错误说明

初始开箱次数为20，当日开箱若干次后，修改配置文件将每日开箱次数改为5，群友再次开箱，当日开箱次数会变为负值且不限制其继续开箱。开箱统计同样受此影响。

**Comment by HibiKier** [comment]
1f01ba1d10b5900b74aecbd5435440862100f10d
