### ISSUE TITLE
签到系统未知错误

### ISSUE THREAD

**Issue by SEANPNEX** [HibiKier/zhenxun_bot#935]
### 错误截图
![Screenshot from 2022-07-19 18-23-31](https://user-images.githubusercontent.com/40521013/179883984-e6035337-b3a7-4b56-8cd2-243be357a9d7.png)

### 日志截图

Traceback (most recent call last):

  File "/home/sean/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7f3b626329d0>
    └ <module 'nonebot' from '/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/nonebot...

  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f3b63d76310>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
    │       └ <function run at 0x7f3b60bc4ca0>
    └ <module 'uvicorn' from '/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/uvicorn...
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7f3b60bc4e50>
    └ <uvicorn.server.Server object at 0x7f3b21a37b20>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f3b60bc4ee0>
           │       │   └ <uvicorn.server.Server object at 0x7f3b21a37b20>
           │       └ <function run at 0x7f3b634b33a0>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f3b219f13c0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7f3b623c4310>: <Task finished name='Task-18852' coro=<_command() done, defined at /home/sean/.cache/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7f3b1c45ff40>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '签到', '_matched_g...
          │            │        │    └ GroupMessageEvent(time=1658276990, self_id=2470007981, post_type='message', sub_type='normal', user_id=2677620881, message_ty...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f3b0f701a60>
          │            └ <Matcher from plugins.sign_in, type=message, priority=5, temp=False>
          └ <function _run_matcher at 0x7f3b62240c10>
> File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7f3b623c4310>: <Task finished name='Task-18852' coro=<_command() done, defined at /home/sean/.cache/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7f3b1c45ff40>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '签到', '_matched_g...
          │       │   │    └ GroupMessageEvent(time=1658276990, self_id=2470007981, post_type='message', sub_type='normal', user_id=2677620881, message_ty...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f3b0f701a60>
          │       └ <function Matcher.run at 0x7f3b623bbe50>
          └ <Matcher from plugins.sign_in, type=message, priority=5, temp=False>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7f3b623c4310>: <Task finished name='Task-18852' coro=<_command() done, defined at /home/sean/.cache/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7f3b1c45ff40>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}, '_matched': '签到', '_matched_g...
          │    │          │    └ GroupMessageEvent(time=1658276990, self_id=2470007981, post_type='message', sub_type='normal', user_id=2677620881, message_ty...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7f3b0f701a60>
          │    └ <function Matcher.simple_run at 0x7f3b623bbdc0>
          └ <Matcher from plugins.sign_in, type=message, priority=5, temp=False>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _ at 0x7f3b28895040>, params=[ModelField(name='event', type=GroupMessageEvent, required=True), Mode...
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'event': GroupMessageEvent(time=1658276990, self_id=2470007981, post_type='message', sub_type='normal', user_id=2677620881, ...
                 │    └ <function _ at 0x7f3b28895040>
                 └ <Dependent call=<function _ at 0x7f3b28895040>, params=[ModelField(name='event', type=GroupMessageEvent, required=True), Mode...

  File "/home/sean/zhenxun_bot/plugins/sign_in/__init__.py", line 93, in _
    await group_user_check_in(nickname, event.user_id, event.group_id),
          │                   │         │     │        │     └ 829931014
          │                   │         │     │        └ GroupMessageEvent(time=1658276990, self_id=2470007981, post_type='message', sub_type='normal', user_id=2677620881, message_ty...
          │                   │         │     └ 2677620881
          │                   │         └ GroupMessageEvent(time=1658276990, self_id=2470007981, post_type='message', sub_type='normal', user_id=2677620881, message_ty...
          │                   └ '?Username?'
          └ <function group_user_check_in at 0x7f3b288e8e50>

  File "/home/sean/zhenxun_bot/plugins/sign_in/group_user_checkin.py", line 39, in group_user_check_in
    return await _handle_check_in(nickname, user_qq, group, present)  # ok
                 │                │         │        │      └ datetime.datetime(2022, 7, 20, 8, 29, 51, 78828)
                 │                │         │        └ 829931014
                 │                │         └ 2677620881
                 │                └ '?Username?'
                 └ <function _handle_check_in at 0x7f3b28936f70>

  File "/home/sean/zhenxun_bot/plugins/sign_in/group_user_checkin.py", line 97, in _handle_check_in
    return await get_card(user, nickname, impression_added, gold, gift)
                 │        │     │         │                 │     └ '好感度双倍加持卡Ⅰ + 1'
                 │        │     │         │                 └ 41
                 │        │     │         └ 0.94
                 │        │     └ '?Username?'
                 │        └ <models.sign_group_user.SignGroupUser object at 0x7f3b0f70a2e0>
                 └ <function get_card at 0x7f3b288e88b0>

  File "/home/sean/zhenxun_bot/plugins/sign_in/utils.py", line 76, in get_card
    ava = BytesIO(await get_user_avatar(user_id))
          │             │               └ 2677620881
          │             └ <function get_user_avatar at 0x7f3b29c67f70>
          └ <class '_io.BytesIO'>

  File "/home/sean/zhenxun_bot/utils/utils.py", line 342, in get_user_avatar
    return (await client.get(url)).content
                  │      │   └ 'http://q1.qlogo.cn/g?b=qq&nk=2677620881&s=160'
                  │      └ <function AsyncClient.get at 0x7f3b2b4d15e0>
                  └ <httpx.AsyncClient object at 0x7f3b1c5f06d0>

  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
                 │    └ <function AsyncClient.request at 0x7f3b2b4d11f0>
                 └ <httpx.AsyncClient object at 0x7f3b1c5f06d0>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x7f3b2bac1b20>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x7f3b2bac1b20>
                 │    │    └ <Request('GET', 'http://q1.qlogo.cn/g?b=qq&nk=2677620881&s=160')>
                 │    └ <function AsyncClient.send at 0x7f3b2b4d13a0>
                 └ <httpx.AsyncClient object at 0x7f3b1c5f06d0>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x7f3b2b4d1430>
                     └ <httpx.AsyncClient object at 0x7f3b1c5f06d0>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x7f3b2b4d14c0>
                     └ <httpx.AsyncClient object at 0x7f3b1c5f06d0>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('GET', 'http://q1.qlogo.cn/g?b=qq&nk=2677620881&s=160')>
                     │    └ <function AsyncClient._send_single_request at 0x7f3b2b4d1550>
                     └ <httpx.AsyncClient object at 0x7f3b1c5f06d0>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('GET', 'http://q1.qlogo.cn/g?b=qq&nk=2677620881&s=160')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x7f3b2b4ca940>
                     └ <httpx.AsyncHTTPTransport object at 0x7f3b1c5f25b0>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'GET']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x7f3b2b536af0>
                 │    └ <httpcore.AsyncHTTPProxy object at 0x7f3b1c5f2850>
                 └ <httpx.AsyncHTTPTransport object at 0x7f3b1c5f25b0>
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7f3b0f77b800>
    │    │   │     │    └ ConnectError(gaierror(-3, 'Temporary failure in name resolution'))
    │    │   │     └ <class 'httpcore.ConnectError'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_httpcore_exceptions at 0x7f3b1c6f42e0>
    └ <contextlib._GeneratorContextManager object at 0x7f3b0f720070>
  File "/home/sean/.cache/pypoetry/virtualenvs/zhenxun-bot-mA25EF5r-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ '[Errno -3] Temporary failure in name resolution'
          └ <class 'httpx.ConnectError'>

httpx.ConnectError: [Errno -3] Temporary failure in name resolution

### 错误说明

突然不能签到了，之前运行正常，看日志像是网络问题，但是go-cqhttp并没有报错，发送其他图片也都正常

**Comment by Frankcsc** [comment]
我昨天部署的，也有签到的问题，然后看了下源码，有的群友艾特真寻发送“显示我”就好了，有的群友发送了也不行
![2 KOZL2O__IM%V(H4I8 P00](https://user-images.githubusercontent.com/45666537/179891929-fc60bea4-05bb-4831-a245-04751e117c7b.png)

**Comment by HibiKier** [comment]
下载群友头像的时候网络问题
