### ISSUE TITLE
球球版本的docker安装脚本出现未知错误

### ISSUE THREAD

**Issue by shanjiayi** [HibiKier/zhenxun_bot#936]
### 错误截图

[img]
![Screenshot_20220718_225823](https://user-images.githubusercontent.com/98953455/179908870-b90b80d1-cd3c-4ec7-91dd-9401716e9a81.jpg)

![0X(C_O8ZKAIAC}Y_}U5_X3R](https://user-images.githubusercontent.com/98953455/179909013-def2212e-3a93-481c-8d17-c21e7cda6f10.png)

### 日志截图

[img]

### 错误说明
安装脚本时无法正常运行，按方向键会出现未知字符。按enter键无法跳到下一步
发生了xx错误...

**Comment by Pumilk** [comment]
可以把项目里的SetUP.sh手动放在服务器中然后运行
然后你发现这个脚本可以正常操作了
但是似乎后面还有深渊一般的存在…（指似乎镜像下不下来
我的建议是直接使用快速开始中的
docker run -itd --restart=on-failure:3 \
-e bot_qq='BOT的QQ号' \
-e bot_qq_key='BOT的QQ密码' \
-e admin_qq='管理员QQ号' \
-e api_key='识图API-KEY' \
-e webui_user='WebUI用户名' \
-e webui_passwd='WebUI密码' \
-p 8081:8081 \
-v ~/my_plugins:/home/zhenxun_bot/my_plugins \
--name=zhenxun_bot \
jyishit/zhenxun_bot
