### ISSUE TITLE
修改了比例配置但pix插件好像没有调用Omega图库里的数据

### ISSUE THREAD

**Issue by TDuckQWQ** [HibiKier/zhenxun_bot#937]
![image](https://user-images.githubusercontent.com/62102282/179985905-2962457e-7be2-4783-816e-0538e0fa560a.png)
![image](https://user-images.githubusercontent.com/62102282/179986104-0a8dca1a-eeee-4025-aa19-7559b94414da.png)

**Comment by HibiKier** [comment]
你甚至连日志都不愿意给

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/180339286-d4e6fef6-8d92-4138-9db6-8d3d4260989d.png)
啊，抱歉

**Comment by HibiKier** [comment]
用pix指定搜一下omega里的图pid或画师uid

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/180650399-6a615a40-aede-4fba-9532-162e3b4ca5f8.png)

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/180650852-2f16c974-8af4-42bf-af0b-a046ab2923d1.png)

(

**Comment by TDuckQWQ** [comment]
只能搜指定添加的pid和uid？，关键词添加的图也搜不出来诶

**Comment by HibiKier** [comment]
改成0 10 搜得到吗

**Comment by TDuckQWQ** [comment]
搜不到，感觉改了和不改的情况一样，搜出来和搜不出来的图都一样

**Comment by TDuckQWQ** [comment]
改成0 10了还是调用pix插件数据库里的图片

**Comment by TDuckQWQ** [comment]
![image](https://user-images.githubusercontent.com/62102282/180690234-8e0012f4-3c1e-4fd3-802c-d7902d887e8c.png)
并搜不到，这是0,10的情况

**Comment by HibiKier** [comment]
可能最新的sql文件有东西变了

**Comment by TDuckQWQ** [comment]
更新0.1.6.3后管用了，感谢
