### ISSUE TITLE
如何让真寻运行在site package的库

### ISSUE THREAD

**Issue by cyberaltoria** [HibiKier/zhenxun_bot#940]
### 错误截图

[img]

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by cyberaltoria** [comment]
总而言之就是无法从site packages目录加载通过pip安装的Python模块

**Comment by THNEden** [comment]
我也是这个问题 试试手动扯到plugins里

**Comment by HibiKier** [comment]
看nb文档
