### ISSUE TITLE
请问为什么在最新的commit中删除了词库问答？

### ISSUE THREAD

**Issue by LambdaYH** [HibiKier/zhenxun_bot#943]
刚刚pull下来最新版本，发现词库问答在https://github.com/HibiKier/zhenxun_bot/commit/1f01ba1d10b5900b74aecbd5435440862100f10d 中被删了，可以知道下原因吗。

**Comment by HibiKier** [comment]
注释忘记打开了，直接打开就行了

**Comment by LambdaYH** [comment]
:joy:
