### ISSUE TITLE
[运行报错]ValueError: Event has no context

### ISSUE THREAD

**Issue by zeyi1688** [HibiKier/zhenxun_bot#944]
系统：win10 x64 
真寻版本：0.1.6.1
![PicsArt_07-24-03 52 17](https://user-images.githubusercontent.com/82829699/180637826-29ba488e-1797-4219-8a0d-d7a056de1751.jpg)

好像是检测到违禁词之后开始报错，一直重复

**Comment by zeyi1688** [comment]
百度和谷歌过，但没能得到解答qaq，大佬求解

**Comment by zeyi1688** [comment]
小白看不懂日志qnq，拍照可能也找不到重点，我直接发log了。
链接：
https://lianlian1314.lanzouj.com/iy89m08fy0ud
多有麻烦，感谢大佬

**Comment by HibiKier** [comment]
下不了，截图报错的最后一部分

**Comment by zeyi1688** [comment]
![Screenshot_2022-07-27-09-57-25-525_bin mt plus](https://user-images.githubusercontent.com/82829699/181144214-932822a3-d40f-4acb-a1b6-caac33edd539.jpg)
![Screenshot_2022-07-27-09-57-43-983_bin mt plus](https://user-images.githubusercontent.com/82829699/181144273-c17888bb-d304-419c-8c14-9058a8023278.jpg)
![Screenshot_2022-07-27-09-57-33-995_bin mt plus](https://user-images.githubusercontent.com/82829699/181144314-4586c091-3cbd-43b4-872c-1ca074b1e09f.jpg)
这些够吗

**Comment by HibiKier** [comment]
是积压消息太多然后一次性调用爆了？
