### ISSUE TITLE
原神角色查询问题

### ISSUE THREAD

**Issue by Rememem** [HibiKier/zhenxun_bot#945]
### 错误截图

![image](https://user-images.githubusercontent.com/58849545/180681961-ed52f2cb-abd2-42c0-acdd-1644c510ad7e.png)

### 日志截图

![image](https://user-images.githubusercontent.com/58849545/180682128-f339fef6-957f-410b-a793-66b0f4a1c11c.png)

### 错误说明

原神角色查询出现查询失败..

**Comment by HibiKier** [comment]
至少需要一个cookie
