### ISSUE TITLE
pix指定数量报错

### ISSUE THREAD

**Issue by GHSSeBi** [HibiKier/zhenxun_bot#948]
### 错误截图

![1](https://user-images.githubusercontent.com/67882684/181038920-b55b7ee6-63de-446f-9297-91f6d0ea2255.png)
![2](https://user-images.githubusercontent.com/67882684/181038950-b3feb6eb-823a-4624-bb39-6e4e69e46ced.png)

### 日志截图

![3](https://user-images.githubusercontent.com/67882684/181038988-9fd02fc2-b2d7-4313-b0f8-c1fc52b82b3f.png)
![4](https://user-images.githubusercontent.com/67882684/181039003-8548271b-cd87-42c1-a4a7-5eafe050c4d6.png)

只要指定了数量就会报错，不指定就不会报错

**Comment by HibiKier** [comment]
aa35a166107b846f535f091bde5eff8335680ff8
