### ISSUE TITLE
coser功能使用的api跑路了

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#949]
![IMG_20220727_005928](https://user-images.githubusercontent.com/105090141/181066476-38d2d30f-8a25-4d89-a304-b6781c0fea35.jpg)

顺便一说上次更新coser连发功能后单发一个“cos”就没有反应了
还有可以像setu一样加个**提供配置项群聊中单次发送图片数量达到指定时使用合并转发**嘛~(￣▽￣)~*

**Comment by xihuantudi** [comment]
> 

谢谢提供源

**Comment by DuXinyu0722** [comment]
你在coser的init离把coser=那块的代码改成这样
coser = on_regex(r"^(\d)连?(cos|COS|coser|括丝)|^(cos|COS)$", priority=5, block=True)
就可以用cos单张了。
最好备份一下，我也是小白，可能会出现bug。

**Comment by HibiKier** [comment]
5794c82a2d0854bd7e742789cb5f551bda6d2ec4
