### ISSUE TITLE
真寻一直发退群提示

### ISSUE THREAD

**Issue by VCE1** [HibiKier/zhenxun_bot#95]
从几天前开始只要发一张图片，真寻就会发相同的退群提示，只有个别群出现这个问题。

**Comment by VCE1** [comment]
群号708967328，在qq群里艾特过你啦，但是好像不在线

**Comment by VCE1** [comment]
![Uploading Screenshot_20211218_130336_com.tencent.mobileqq.jpg…]()

**Comment by VCE1** [comment]
https://user-images.githubusercontent.com/79588027/146630007-8c84fa32-88e1-4f98-ab6e-552f4dd30f33.jpg

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/146630650-4ff661a5-0877-49ac-8c05-efd2dc314251.png)，
![图片](https://user-images.githubusercontent.com/45528451/146631186-f6e4ea42-9c8e-404a-8569-1774aa98a3fb.png)
你群词条，某些用户使用空格来作为问题导致只要是消息就会被回复，目前已修复空格问题，另外，我并不会经常上bot号，有问题可以通过 滴滴滴- 联系管理员，另外真寻已经在群内几乎有着所有功能开关，详细查看文档

**Comment by HibiKier** [comment]
已经删了你群空格词条
