### ISSUE TITLE
Ubuntu arm64 22.04 安装postgresql后不能正常使用如何解决

### ISSUE THREAD

**Issue by KudouShinnyan** [HibiKier/zhenxun_bot#950]
![Screenshot_20220727-044225_Termux](https://user-images.githubusercontent.com/68854981/181108357-06153422-46b5-4162-a893-91fba8c3c961.png)

**Comment by Unicorn369** [comment]
termux使用psql请参考这https://www.jinjun.top/412.html

另外arm架构建议使用Docker或者使用proot装x64架构的linux

**Comment by KudouShinnyan** [comment]
apt装完postgresql和postgresql-contrib后参考链接那里, 在执行建文件夹命令之前文件夹就存在的了, 然后下一行… initdb: command not found…

至于Ubuntu x64, 貌似报错更多了…
![Screenshot_20220727-140528_Termux](https://user-images.githubusercontent.com/68854981/181173453-4e7a6e24-c92a-4d3b-bd81-580d4d2e42e7.png)

**Comment by KudouShinnyan** [comment]
> termux使用psql请参考这https://www.jinjun.top/412.html
> 
> 另外arm架构建议使用Docker或者使用proot装x64架构的linux

apt装完postgresql和postgresql-contrib后参考链接那里, 在执行建文件夹命令之前文件夹已经是存在的了, 然后下一行… initdb: command not found…

至于Ubuntu x64, 貌似报错更多了…
![Screenshot_20220727-140528_Termux](https://user-images.githubusercontent.com/68854981/181174334-45a1e86c-aa46-4934-8525-d22b8f92faaf.png)
