### ISSUE TITLE
B站转发解析无反应

### ISSUE THREAD

**Issue by ChthollyWn** [HibiKier/zhenxun_bot#954]
### 错误截图

![image](https://user-images.githubusercontent.com/85938618/181905101-ba0d8e21-0cb1-406a-bbd8-66b18e629ece.png)

### 日志截图

bot日志无错误
![image](https://user-images.githubusercontent.com/85938618/181905112-db5ca531-aacf-40fb-a35c-57737ebb5a5d.png)

go-cq日志也无错误
![image](https://user-images.githubusercontent.com/85938618/181905139-78598ce4-d9c4-4d10-84a2-19fc52439bfd.png)

### 错误说明

B站的转发解析无反应，没有报错，求救！

**Comment by LambdaYH** [comment]
转发解析只有群聊才有效

**Comment by ChthollyWn** [comment]
> 转发解析只有群聊才有效

![image](https://user-images.githubusercontent.com/85938618/182028130-26693309-2754-45d9-9840-98e7d0ef0d36.png)
![image](https://user-images.githubusercontent.com/85938618/182028142-cda70ed9-eeb1-422f-a285-4bd3e76bff92.png)
在群聊中转发后显示失败，gocq显示被风控，但是其他消息是可以正常发送的，只有解析不能使用

**Comment by HibiKier** [comment]
收购腾讯？
