### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by xingluo233** [HibiKier/zhenxun_bot#955]
### 错误截图

![Screenshot_2022-07-30-18-07-45-980_com.microsoft.rdc.androidx.jpg](https://user-images.githubusercontent.com/54618947/181906875-84efdd68-e6ba-4713-afdb-399f867db3fd.jpg)

### 日志截图

![Screenshot_2022-07-30-18-41-43-291_com.microsoft.rdc.androidx.jpg](https://user-images.githubusercontent.com/54618947/181906881-734afc12-d661-4379-943c-271e60ae6ad7.jpg)

### 错误说明

运行后，刚开始没什么事，加载完插件后就一直报错，都不带停的，放了一会后日志文件直接到了200m

**Comment by HibiKier** [comment]
看报错最后一行

**Comment by xingluo233** [comment]
> 看报错最后一行

![Screenshot_2022-07-31-18-02-49-622_com.microsoft.rdc.androidx.jpg](https://user-images.githubusercontent.com/54618947/182021181-1c38c044-8dcc-4545-b3a6-4f11ff9c55dc.jpg)

**Comment by HibiKier** [comment]
积压太多消息一次性处理了吧

**Comment by xingluo233** [comment]
> 积压太多消息一次性处理了吧

那咋办啊，我是第一次部署
