### ISSUE TITLE
B站订阅查看订阅指令消息风控

### ISSUE THREAD

**Issue by 1411484730** [HibiKier/zhenxun_bot#956]
### 错误截图
聊天记录内bot无回复，cqhttp内错误提示消息风控
![image](https://user-images.githubusercontent.com/69163070/181918480-e31f8961-9bda-4b59-80f1-b25e00003ba8.png)

### 日志截图

![image](https://user-images.githubusercontent.com/69163070/181918526-9ba30517-7403-4bc9-a866-d777e496b317.png)

### 错误说明

消息时好时坏的，建议把订阅列表做成图片发送避免文字信息被风控

**Comment by HibiKier** [comment]
c089388323a32985d32265ad7c7f63703ea2406a
