### ISSUE TITLE
帮助指令异常

### ISSUE THREAD

**Issue by ChthollyWn** [HibiKier/zhenxun_bot#959]
### 错误截图

![image](https://user-images.githubusercontent.com/85938618/182062816-cf2632e0-deeb-440c-94b7-3df14fe7376c.png)

### 日志截图

![image](https://user-images.githubusercontent.com/85938618/182062779-431b4d52-bb7c-4b31-8098-67ab108bf0a4.png)

### 错误说明

发送帮助指令返回的是青云客的帮助

**Comment by HibiKier** [comment]
你帮助插件加载报错了吗
