### ISSUE TITLE
单个用户无法正常使用双倍加持卡

### ISSUE THREAD

**Issue by SinGone949** [HibiKier/zhenxun_bot#965]
### 错误截图

![QQ图片20220803203637](https://user-images.githubusercontent.com/34976274/182609480-ff9ee341-4981-4a03-9733-2becae6a3ac5.png)

### 日志截图

![屏幕截图 2022-08-03 202935](https://user-images.githubusercontent.com/34976274/182609652-6fd95068-a01e-4b12-ba8a-96ae5800bf33.png)

### 错误说明

真寻一直正常运行，今天突然有群友表示无法使用双倍加持卡，但其他群友使用双倍卡均正常，只有该群友使用时报日志中错误，前几天把真寻从0.1.6.0升级为了0.1.6.2，但该群友表示出现这一问题已经很长时间，应该和更新没有关系。
报错要求参考gocqhttp的保存，但那边只有“[WARNING]: 群消息发送失败: 账号可能被风控.”的提示，我也不贴出来了。（但我觉得风控没有只针对一个人的吧，真寻对其他人的任何回复，还有对该群友除了使用双倍卡的所有回复都正常）没有什么头绪，求各位大佬指点。

**Comment by HibiKier** [comment]
这个也只是发送消息风控，实际上道具已经生效了

**Comment by ru8lq0005** [comment]
风控的话 可以手动登陆一下手机qq，应该能解除，不行就删了session文件和device.json 重新登录试试

**Comment by SinGone949** [comment]
原来就是风控的问题嘛，我之前一直觉得这个针对特定的人发特定的话才发不出来的情况不像风控诶
