### ISSUE TITLE
链接数据库失败

### ISSUE THREAD

**Issue by lookmycat** [HibiKier/zhenxun_bot#967]
### 错误截图

![image](https://user-images.githubusercontent.com/60572850/182752971-15fcf9f0-bc43-4c8f-b64a-2490b3af4cc8.png)
![image](https://user-images.githubusercontent.com/60572850/182753042-63358dc5-4bda-4355-8692-d04237eb7d28.png)

数据库链接配置
![image](https://user-images.githubusercontent.com/60572850/182753346-8abf608b-831d-4355-9551-cb34cb18f299.png)

数据库页面
![image](https://user-images.githubusercontent.com/60572850/182753835-2a8d127f-2ce7-47ea-831c-ae75a3928746.png)

### 错误说明
链接在操作过程中关闭

**Comment by lookmycat** [comment]
已经自行解决了

**Comment by KnightKilito** [comment]
求教如何解决的
