### ISSUE TITLE
部分图片无法发送

### ISSUE THREAD

**Issue by Awavy7** [HibiKier/zhenxun_bot#970]
### 错误截图

![IX}YBJZETWE6}1VXNLP{(WE](https://user-images.githubusercontent.com/110511426/183088991-8867ac8e-ff7f-4f2f-90f0-06aa49a6e565.png)

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by HibiKier** [comment]
= = 问腾讯

**Comment by HibiKier** [comment]
= = 问腾讯

**Comment by HibiKier** [comment]
= = 问腾讯
