### ISSUE TITLE
米游社无法签到

### ISSUE THREAD

**Issue by Narmaya-gbf** [HibiKier/zhenxun_bot#976]
### 错误截图

![image](https://user-images.githubusercontent.com/66237606/183379477-70999889-0e72-451f-9031-44b5920a74c4.png)

### 日志截图

![image](https://user-images.githubusercontent.com/66237606/183379566-5f02f831-b728-4dc8-874e-802822564212.png)

### 错误说明

更新了0.1.6.2版本之后，米游社签到还是 invalid request 尝试重新绑定米游社之后也还是不行，无法查看已绑定的cookie，请教一下大佬该如何解决

**Comment by MisakaMikoto2333** [comment]
同样我也遇到了这个问题

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/183819578-60832caf-88c8-4c36-9067-710782645b26.png)

**Comment by Narmaya-gbf** [comment]
> ![图片](https://user-images.githubusercontent.com/45528451/183819578-60832caf-88c8-4c36-9067-710782645b26.png)

已经更新了改pr

**Comment by HDU-Nbsp** [comment]
> > ![图片](https://user-images.githubusercontent.com/45528451/183819578-60832caf-88c8-4c36-9067-710782645b26.png)
> 
> 已经更新了改pr，这个是更新后报的错，还是感谢大佬百忙之中回复

因为还没有正式更新，需要手动git pull后替换文件或者等0.1.6.3。

另外偶尔会出现签不上道的情况是因为有时候会需要进行验证，暂时没有比较好的解决方案，可以尝试过一段时间通过`原神我硬签`指令尝试重新签到或自己登陆米游社进行签到。
