### ISSUE TITLE
大佬们真寻最新的commit号是啥啊,我都不知道这个玩意在哪?

### ISSUE THREAD

**Issue by NoelleDLL** [HibiKier/zhenxun_bot#977]
### 错误截图

[img]

### 日志截图

[img]

### 错误说明

发生了xx错误...

**Comment by NoelleDLL** [comment]
本人第一次用github，很多东西都还在学习中，想加群但是不知道commit号在哪...

**Comment by shinianj** [comment]
你

> 本人第一次用github，很多东西都还在学习中，想加群但是不知道commit号在哪...

你再仔细看看code页面

**Comment by NoelleDLL** [comment]
> 你
> 
> > 本人第一次用github，很多东西都还在学习中，想加群但是不知道commit号在哪...
> 
> 你再仔细看看code页面

你是说那一堆sha吗？然后呢大佬

**Comment by NoelleDLL** [comment]
> 你
> 
> > 本人第一次用github，很多东西都还在学习中，想加群但是不知道commit号在哪...
> 
> 你再仔细看看code页面

ca78e32？是这个吗

**Comment by shinianj** [comment]
> > 你
> > > 本人第一次用github，很多东西都还在学习中，想加群但是不知道commit号在哪...
> > 
> > 
> > 你再仔细看看code页面
> 
> [ca78e32](https://github.com/HibiKier/zhenxun_bot/commit/ca78e32d97b6fccedd8692a7a30d910a91e9d169)？是这个吗

你觉得是就是啦（我不好说啊，真的不好说）

**Comment by IrisMiko** [comment]
如果不知道我建议是善用搜索工具而不是直接发issues，像现在你发了，在没更新前所有人都可以在你这找到commit号，那设置这个问题还有什么意义呢？

**Comment by NoelleDLL** [comment]
> 如果不知道我建议是善用搜索工具而不是直接发issues，像现在你发了，在没更新前所有人都可以在你这找到commit号，那设置这个问题还有什么意义呢？

已经知道啦!
