### ISSUE TITLE
数据库连接失败

### ISSUE THREAD

**Issue by TDuckQWQ** [HibiKier/zhenxun_bot#978]
### 错误截图
![183566748-0350dfc6-c161-4172-a5bf-d6804b83c5f1](https://user-images.githubusercontent.com/62102282/183665462-14c94588-a97f-4ce8-9aed-ed91ced4c359.png)

### 日志截图
![183566021-470c958f-c646-445c-b300-dd38b0860c0d](https://user-images.githubusercontent.com/62102282/183665452-2af7fb57-46b8-426d-9c89-1dc2548ab56a.png)

### 错误说明
真寻已经开过一段时间了，最近经常出现无法连接数据库的问题
数据库的软件重装过一次，使用过了一段时间又会出现连接不上的问题

**Comment by TDuckQWQ** [comment]
![E8$}O $RASNYQ4$%1SDF{51](https://user-images.githubusercontent.com/62102282/184277965-1f8352d5-1c00-4c6b-9c99-f617a4651e5f.jpg)

**Comment by HibiKier** [comment]
配置文件写多了吗，数据库创建了吗

**Comment by TDuckQWQ** [comment]
就是单纯的连不上数据库，可能被什么软件代理顶掉了，我自行检查一下先
