### ISSUE TITLE
反向WebSocket Universal服务器连接失败

### ISSUE THREAD

**Issue by Star-Sum** [HibiKier/zhenxun_bot#979]
### 错误截图

[img]

### 日志截图

[img]

### 错误说明

No connection could be made because the target machine actively refused it.

**Comment by han15179** [comment]
这个问题我也遇到了不知道为什么，如果有任何进展请告诉我

**Comment by WASDECXZQ** [comment]
1你真寻没打开,只开一个gocq肯定是这样
