### ISSUE TITLE
“检查更新真寻”求助

### ISSUE THREAD

**Issue by borntree** [HibiKier/zhenxun_bot#980]
### 系统版本：	
Windows Server 2012 R2 DataCenter 64bit CN
### 错误截图

![image](https://user-images.githubusercontent.com/82987943/183815401-a3d8ce3b-54d7-465e-980d-497ce6784b86.png)

### 日志截图

![image](https://user-images.githubusercontent.com/82987943/183815366-b56375d3-d825-4fb5-a977-0b181c388a9b.png)

### 错误说明

梯子挂了，下载速度平均1M/s，但是就是更新失败，两处verify也改为了false，特来求助
![image](https://user-images.githubusercontent.com/82987943/183815616-b2aacaeb-9ec2-476e-8e61-ffec1e0ddb9f.png)
![image](https://user-images.githubusercontent.com/82987943/183815694-7e21163d-2c5b-48f3-a07e-6df88d4fb8f1.png)

有无真寻最新安装包的镜像站，想试试修改这个后![image](https://user-images.githubusercontent.com/82987943/183815954-b375a494-fddb-4635-a6b6-8bf193b3798a.png)不挂梯子能否更新

**Comment by foreveruand** [comment]
可以加一下https://ghproxy.com前缀

**Comment by borntree** [comment]
> 可以加一下https://ghproxy.com前缀

![IMG_20220812_101716.jpg](https://user-images.githubusercontent.com/82987943/184272777-fd0bd0ce-c885-4346-b585-2cf262aa6920.jpg)
可是这个地址没有任何东西呀

**Comment by foreveruand** [comment]
> > 可以加一下[https://ghproxy.com前缀](https://ghproxy.com%E5%89%8D%E7%BC%80)
> 
> ![IMG_20220812_101716.jpg](https://user-images.githubusercontent.com/82987943/184272777-fd0bd0ce-c885-4346-b585-2cf262aa6920.jpg) 可是这个地址没有任何东西呀

![图片](https://user-images.githubusercontent.com/43624948/184273374-f454ffa3-3ab4-40b5-8cb9-7e629bd6b9b3.png)
像这样直接加上试一下

**Comment by borntree** [comment]
> > > 可以加一下[https://ghproxy.com前缀](https://ghproxy.com%E5%89%8D%E7%BC%80)
> > 
> > ![IMG_20220812_101716.jpg](https://user-images.githubusercontent.com/82987943/184272777-fd0bd0ce-c885-4346-b585-2cf262aa6920.jpg) 可是这个地址没有任何东西呀
> 
> ![图片](https://user-images.githubusercontent.com/43624948/184273374-f454ffa3-3ab4-40b5-8cb9-7e629bd6b9b3.png)
> 像这样直接加上试一下

直接无法获取了![Screenshot_20220812_103031.jpg](https://user-images.githubusercontent.com/82987943/184274118-b8f98266-733e-4cdb-a190-cc7bbfa891cd.jpg)![IMG_20220812_103114_edit_153564152730212.jpg](https://user-images.githubusercontent.com/82987943/184274189-c520a6e3-3917-4d9e-b114-6450f3dfe763.jpg)

**Comment by HibiKier** [comment]
。。
![图片](https://user-images.githubusercontent.com/45528451/184537951-7ee66c34-dcf2-4f0e-ab8c-8316d5defdbf.png)
？

**Comment by borntree** [comment]
我下载了最新版，然后把除了配置的文件全部覆盖了一遍，已解决。（手动安装）
