### ISSUE TITLE
远程主机强迫关闭了一个现有的连接且数据库连接错误....怎么解决

### ISSUE THREAD

**Issue by superdobo** [HibiKier/zhenxun_bot#982]
### 错误截图
![屏幕截图 2022-08-12 233451](https://user-images.githubusercontent.com/83578139/184390473-0fb402cd-7f67-4272-a0b2-76289c1d2dd2.png)
![屏幕截图 2022-08-12 233516](https://user-images.githubusercontent.com/83578139/184390663-162d1bec-e19b-45a8-9c65-29441cdddc1c.png)

### 日志截图

![屏幕截图 2022-08-12 233819](https://user-images.githubusercontent.com/83578139/184390895-9c16ddc5-0542-4c4d-9332-501f1fd25431.png)

### 

详细问题
远程主机强迫关闭了一个现有的连接且.数据库连接错误....端口号一致，pgAdmin的Group Roles也配置了，求解决

**Comment by HibiKier** [comment]
数据库创建了吗，配置写的对吗
