### ISSUE TITLE
签到无法生效

### ISSUE THREAD

**Issue by Misakami** [HibiKier/zhenxun_bot#983]
### 错误截图
![image](https://user-images.githubusercontent.com/22981008/184405170-527e3d00-0d7c-4f3b-a6a7-c3a4d86025e8.png)

[img]

### 错误说明

签到错误，代码为最新。
![image](https://user-images.githubusercontent.com/22981008/184405240-b11d050a-21e6-45b6-945a-8f55c0a57d1b.png)

**Comment by HDU-Nbsp** [comment]
偶尔会出现签不上道的情况是因为有时候会需要进行验证，暂时没有比较好的解决方案，可以尝试过一段时间通过**原神我硬签**指令尝试重新签到或自己登陆米游社进行签到。
![image](https://user-images.githubusercontent.com/83355040/184498727-4878f04d-9ba2-43ef-803f-e84d3a4ced8e.png)
（图片来源于其他issue）

**Comment by HibiKier** [comment]
确实
