### ISSUE TITLE
配置文件无法生成

### ISSUE THREAD

**Issue by gscsdnegy** [HibiKier/zhenxun_bot#984]
操作系统：Windows10
真寻版本：0.15.4

启动真寻后成功连接，但是第六步的config.yaml没有生成。

**Comment by HibiKier** [comment]
我 __猜__ 你插件加载报错了

**Comment by gscsdnegy** [comment]
所以我应该怎么做？

**Comment by Linsy-Linnnnnn** [comment]
遇到同样问题了；；

**Comment by HibiKier** [comment]
你应该发日志让我看看你是什么错

**Comment by xuhanlia** [comment]
连接反向时出错
![QQ截图20220821151006](https://user-images.githubusercontent.com/111414305/185780004-9839a093-2640-408f-a9e9-3146e0dd4e9d.png)

**Comment by HibiKier** [comment]
你把bot开起来

**Comment by xuhanlia** [comment]
我的bot一直在线啊，还是说我理解错了bot账号
![QQ截图20220821151744](https://user-images.githubusercontent.com/111414305/185780198-0c64066e-8f7c-45bb-96da-24f5eaccb6af.png)

**Comment by HibiKier** [comment]
这步是对的，你继续看文档往下做就行了

**Comment by xuhanlia** [comment]
![image](https://user-images.githubusercontent.com/111414305/188271361-2ac34780-f1b6-4401-bd28-40536a1330fc.png)
数据库无法安装

**Comment by xuhanlia** [comment]
破案了，版本问题，该怎么建立链接
![image](https://user-images.githubusercontent.com/111414305/188271859-c26003a0-a71c-4a0c-b683-b1f088eba986.png)
