### ISSUE TITLE
pix的功能好像都用不了

### ISSUE THREAD

**Issue by WASDECXZQ** [HibiKier/zhenxun_bot#986]
### 错误截图
![image](https://user-images.githubusercontent.com/77792390/184498234-da22f35a-3e63-4f86-a0b1-f3a4887b5653.png)
![image](https://user-images.githubusercontent.com/77792390/184498248-b724bc73-86f3-4be7-8484-8a43f1f6f130.png)

### 日志截图
日志没有error

### 错误说明
不知道是哪里设置出现了问题,图库也是有的,但是pix就是加载不出任何图,总显示"未在图库中找到与 xx 相关Tag/UID/PID的图片...
"
刚开始接触这方面,也是第一次在issues问问题要是什么基础性小错误还请下嘴轻点)

**Comment by HibiKier** [comment]
omega新的数据库文件改结构了，等我修

**Comment by WASDECXZQ** [comment]
> omega新的数据库文件改结构了，等我修

那pix图库怎么用不了,omega图库没了pix也是能用的吧

**Comment by HibiKier** [comment]
不清楚，这个查询是根据tag搜的，你可以去数据库里看一下有无这个tag？

**Comment by modeilan** [comment]
> 不清楚，这个查询是根据tag搜的，你可以去数据库里看一下有无这个tag？

大佬想问下为啥私聊pix -r不行，怎么样单独打开私聊的关闭群聊的-r，涩图倒是可以

**Comment by HibiKier** [comment]
发日志
