### ISSUE TITLE
在安装poetry install出现报错

### ISSUE THREAD

**Issue by beiyaohhhc** [HibiKier/zhenxun_bot#987]
### 错误截图
`  EnvCommandError

  Command C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Yp7V4K4D-py3.10\Scripts\pip.exe install --no-deps file:///C:/Users/Administrator/AppData/Local/pypoetry/Cache/artifacts/5a/ee/20/36676d9298f4330ba6bdbfb04bef679b543140a69b095e294e76a5bee9/scipy-1.6.1.tar.gz errored with the following return code 1, and output:
  Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
  Processing c:\users\administrator\appdata\local\pypoetry\cache\artifacts\5a\ee\20\36676d9298f4330ba6bdbfb04bef679b543140a69b095e294e76a5bee9\scipy-1.6.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error

    Preparing metadata (pyproject.toml) did not run successfully.
    exit code: 1

    [137 lines of output]
    setup.py:461: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\Administrator\AppData\Local\Temp\2\pip-modern-metadata-4riwhe3g'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    setup.py:563: DeprecationWarning:

      `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
      of the deprecation of `distutils` itself. It will be removed for
      Python >= 3.12. For older Python versions it will remain present.
      It is recommended to use `setuptools < 60.0` for those Python versions.
      For more details, see:
        https://numpy.org/devdocs/reference/distutils_status_migration.html

      from numpy.distutils.core import setup
    Running from SciPy source directory.
    INFO: lapack_opt_info:
    INFO: lapack_armpl_info:
    INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    INFO: customize MSVCCompiler
    INFO:   libraries armpl_lp64_mp not found in ['C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-Yp7V4K4D-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    INFO: lapack_mkl_info:
    INFO:   libraries mkl_rt not found in ['C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-Yp7V4K4D-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    INFO: openblas_lapack_info:
    INFO:   libraries openblas not found in ['C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-Yp7V4K4D-py3.10\\lib', 'C:\\']
    INFO: get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    INFO: customize GnuFCompiler
    WARN: Could not locate executable g77
    WARN: Could not locate executable f77
    INFO: customize IntelVisualFCompiler
    WARN: Could not locate executable ifort
    WARN: Could not locate executable ifl
    INFO: customize AbsoftFCompiler
    WARN: Could not locate executable f90
    INFO: customize CompaqVisualFCompiler
    WARN: Could not locate executable DF
    INFO: customize IntelItaniumVisualFCompiler
    WARN: Could not locate executable efl
    INFO: customize Gnu95FCompiler
    WARN: Could not locate executable gfortran
    WARN: Could not locate executable f95
    INFO: customize G95FCompiler
    WARN: Could not locate executable g95
    INFO: customize IntelEM64VisualFCompiler
    INFO: customize IntelEM64TFCompiler
    WARN: Could not locate executable efort
    WARN: Could not locate executable efc
    INFO: customize PGroupFlangCompiler
    WARN: Could not locate executable flang
    WARN: don't know how to compile Fortran code on platform 'nt'
    INFO:   NOT AVAILABLE
    INFO:
    INFO: openblas_clapack_info:
    INFO:   libraries openblas,lapack not found in ['C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-Yp7V4K4D-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    INFO: flame_info:
    INFO:   libraries flame not found in ['C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-Yp7V4K4D-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    INFO: accelerate_info:
    INFO:   NOT AVAILABLE
    INFO:
    INFO: atlas_3_10_threads_info:
    INFO: Setting PTATLAS=ATLAS
    INFO:   libraries tatlas,tatlas not found in C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Yp7V4K4D-py3.10\lib
    INFO:   libraries tatlas,tatlas not found in C:\
    INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    INFO:   NOT AVAILABLE
    INFO:
    INFO: atlas_3_10_info:
    INFO:   libraries satlas,satlas not found in C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Yp7V4K4D-py3.10\lib
    INFO:   libraries satlas,satlas not found in C:\
    INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
    INFO:   NOT AVAILABLE
    INFO:
    INFO: atlas_threads_info:
    INFO: Setting PTATLAS=ATLAS
    INFO:   libraries ptf77blas,ptcblas,atlas not found in C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Yp7V4K4D-py3.10\lib
    INFO:   libraries ptf77blas,ptcblas,atlas not found in C:\
    INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
    INFO:   NOT AVAILABLE
    INFO:
    INFO: atlas_info:
    INFO:   libraries f77blas,cblas,atlas not found in C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Yp7V4K4D-py3.10\lib
    INFO:   libraries f77blas,cblas,atlas not found in C:\
    INFO: <class 'numpy.distutils.system_info.atlas_info'>
    INFO:   NOT AVAILABLE
    INFO:
    INFO: lapack_info:
    INFO:   libraries lapack not found in ['C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-Yp7V4K4D-py3.10\\lib', 'C:\\']
    INFO:   NOT AVAILABLE
    INFO:
    C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-ass5vh3d\overlay\Lib\site-packages\numpy\distutils\system_info.py:1902: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    INFO: lapack_src_info:
    INFO:   NOT AVAILABLE
    INFO:
    C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-ass5vh3d\overlay\Lib\site-packages\numpy\distutils\system_info.py:1902: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    INFO:   NOT AVAILABLE
    INFO:
    Traceback (most recent call last):
      File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Yp7V4K4D-py3.10\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
        main()
      File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Yp7V4K4D-py3.10\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-Yp7V4K4D-py3.10\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-ass5vh3d\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-ass5vh3d\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-ass5vh3d\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 588, in <module>
        setup_package()
      File "setup.py", line 584, in setup_package
        setup(**metadata)
      File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-ass5vh3d\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 499, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
    To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
    See site.cfg.example in the Scipy source directory and
    https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed

  Encountered error while generating package metadata.

  See above for output.

  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.

  at ~\AppData\Local\Programs\Python\Python310\lib\site-packages\poetry\utils\env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):`
[img]

### 日志截图
无
[img]

**Comment by beiyaohhhc** [comment]
>

**Comment by beiyaohhhc** [comment]
看到之前的issue说删掉poetry.lock删掉可以会像下图卡住
![image](https://user-images.githubusercontent.com/98569420/184533854-83b7aa96-fbb7-4c39-9b37-784af7b4b3a3.png)
python版本是3.10

**Comment by HibiKier** [comment]
换3.9

**Comment by beiyaohhhc** [comment]
换3.9.13后安装依然有报错 而且poetry.lock删掉依然卡住

**Comment by beiyaohhhc** [comment]
是在• Installing scipy (1.6.1)这步会出现报错

**Comment by 276562578** [comment]
这个问题解决了吗

**Comment by beiyaohhhc** [comment]
> 这个问题解决了吗

没有

**Comment by 276562578** [comment]
我通过删除poetry.lock重新安装解决了

**Comment by beiyaohhhc** [comment]
删过 但是会卡住

**Comment by beiyaohhhc** [comment]
![image](https://user-images.githubusercontent.com/98569420/184584029-b9ab0ee9-a194-4853-aff5-4eb2777f12ae.png)

**Comment by beiyaohhhc** [comment]
![image](https://user-images.githubusercontent.com/98569420/184584081-741e2b88-7a1a-482e-9c3c-ca0237223060.png)

**Comment by 276562578** [comment]
挂梯子，他只是很慢

**Comment by beiyaohhhc** [comment]
可以了 在安装了 谢谢

**Comment by beiyaohhhc** [comment]
好吧 又有新报错....  • Installing wordcloud (1.8.2.2)

  RuntimeError

  Invalid hashes (sha256:965a2ebcf12541ca0798ce14554c69fc963340be1743ced5097c7c2e16c1bd52) for playwright (1.24.1) using archive playwright-1.24.1-py3-none-win_amd64.whl. Expected one of sha256:04575c6682098a2f5e851a3fb04bc0e3269af6e00732798103a02f63e4409dfb, sha256:279c8f150662292814499b61ccbc35917f5041592ede1853e2a46e59456500df, sha256:5ad16b26f4ae2d539c580273bd323907e24a125dbf0f38460466608d1cb39c83, sha256:7355d00cd2cb24265779b1cd9b18d9dcac17eea4a558d57ce20df650fc766f53, sha256:b3f2acda4c22e78c94a47eb5b6f77f20c0313ec76f8e19d77c09bee1c44631d9, sha256:e0821859b625ad3dd1c89c9359d5d10d48ce1af81dc99d702437721ab72cd150, sha256:f6add5cc97a8b3bca775c38ba3382fe73004d59adc9e404bf59f23f35442ede7.

  at ~\AppData\Local\Programs\Python\Python310\lib\site-packages\poetry\installation\executor.py:627 in _download_link

  RuntimeError

  Invalid hashes (sha256:a975e53cd4aa96132cc4fdc2e11ee04566f41c69bcbcbb0774583cb27ba48c09) for jieba (0.42.1) using archive jieba-0.42.1.tar.gz. Expected one of sha256:055ca12f62674fafed09427f176506079bc135638a14e23e25be909131928db2.

  at ~\AppData\Local\Programs\Python\Python310\lib\site-packages\poetry\installation\executor.py:627 in _download_link
