### ISSUE TITLE
不懂就问在代码的哪里可以更改签到图片白色部分的透明度

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#988]
![image](https://user-images.githubusercontent.com/105090141/184519719-860e9951-e8fd-485b-9ccf-1fac041f047e.png)

如题，觉得不够透想改一下，不懂该改哪里的代码，小白一个
（说起来刚发现签到背景图是能随机的23333）

**Comment by HibiKier** [comment]
![图片](https://user-images.githubusercontent.com/45528451/184539733-0d3a113a-d272-4180-a16f-cb78288c7e31.png)
![图片](https://user-images.githubusercontent.com/45528451/184539736-5c8a907f-e12a-467d-8a36-bd814b16319b.png)
