### ISSUE TITLE
超级用户私聊无法正常试用广播和色图功能

### ISSUE THREAD

**Issue by wlz-remake** [HibiKier/zhenxun_bot#989]
### 系统版本：
![image](https://user-images.githubusercontent.com/105090141/184520836-d3a89389-ebfd-420c-9bf0-588bacdcb96b.png)

### 错误截图
![image](https://user-images.githubusercontent.com/105090141/184520854-d8ddbac6-4c4b-4fe6-b3a8-c1e1a96d29b0.png)
私聊没有回应

### 日志截图
色图报错：
![image](https://user-images.githubusercontent.com/105090141/184520712-e502a7a5-7f75-418e-a07a-93389bf20e2c.png)
![image](https://user-images.githubusercontent.com/105090141/184520725-42e7a780-b696-45c9-a11e-a54954fce152.png)

广播报错：
![image](https://user-images.githubusercontent.com/105090141/184520774-fc295de7-d64c-40b9-a00c-02adde27e6e5.png)
![image](https://user-images.githubusercontent.com/105090141/184520790-8130ea25-cc3d-4bbb-adc0-306c6e9d37e3.png)

### 错误说明
如题，色图是完全没有反应，广播只能发送至两个群聊，其他群就没动静；
但在群聊中使用这两个功能时就能正常生效。

**Comment by HibiKier** [comment]
建议去nb群问
