### ISSUE TITLE
macOS 运行出现错误 ValueError: Cannot guess message type to reply!

### ISSUE THREAD

**Issue by sjtuli** [HibiKier/zhenxun_bot#992]
### 错误截图
<img width="732" alt="截屏2022-08-15 09 43 24" src="https://user-images.githubusercontent.com/75962592/184564183-bd07a88b-fa72-4b1a-9752-a80e52443366.png">

### 日志截图
ValueError: Cannot guess message type to reply!

### 错误说明
别的机器人是没问题的，真寻按照官方文档的配置来的。
有一个包，hash验证失败，按提示修改了poetry.lock的hash值

**Comment by sjtuli** [comment]
Python3.8、3.10都测试过，均存在问题

**Comment by sjtuli** [comment]
把返回值打印出来了
<img width="754" alt="截屏2022-08-15 10 34 54" src="https://user-images.githubusercontent.com/75962592/184568261-2dd6c6a3-393b-4350-9635-d3c756957b1a.png">

**Comment by HibiKier** [comment]
这个可以去nb群问一下

**Comment by sjtuli** [comment]
解决了，是因为之前都是私聊触发的
on_command的rule是to_me()
我一直以为是私聊，但是实际上应该是在群里 @机器人 触发
私聊返回的CQ码，格式应该是不同的
因而报错无法得知消息类型

**Comment by sjtuli** [comment]
是适配器的问题。。。后面测试发现正常应该私聊返回的数据仍然报错。
上nonebot的issue里查看了一下，发现：
<img width="1026" alt="截屏2022-08-23 20 46 17" src="https://user-images.githubusercontent.com/75962592/186162239-635c3194-ad77-4166-a3f4-4862e02f33cb.png">
所以更新适配器就好了
