### ISSUE TITLE
dinggong插件输入“骂我”指令没有返回消息

### ISSUE THREAD

**Issue by ChocolateSerein** [HibiKier/zhenxun_bot#994]
对着真寻输入骂我指令，没有一点的消息回复，连不调用插件dinggong的回复也没有，应该是调用了这个插件的，但是没有返回任何消息

**Comment by Umon7275** [comment]
这个功能需要@真寻

**Comment by ChocolateSerein** [comment]
> 这个功能需要@真寻

我@真寻了，而且私聊应该也能用，我私聊也没反应

**Comment by HibiKier** [comment]
日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志日志

**Comment by qingba** [comment]
你安装ffmpeg了没
环境变量也要设置
