### ISSUE TITLE
签到功能突然去世（非账号风控提醒）

### ISSUE THREAD

**Issue by SEVEN-6174** [HibiKier/zhenxun_bot#995]
![image](https://user-images.githubusercontent.com/107546075/184638394-8ff9b116-bb46-4553-bea6-045047f36c95.png)
如图
我翻了报错里面的几个文件，也没看出什么

**Comment by SEVEN-6174** [comment]
> 用户头像有问题吧

并不，所有用户都报错

**Comment by SEVEN-6174** [comment]
> 用户头像有问题吧

原因找到了,是所有的头像都获取失败，但是不知道原因

**Comment by VanadiumT** [comment]
遇到了相同的问题

**Comment by VanadiumT** [comment]
有解决方案的时候踢我下

**Comment by HibiKier** [comment]
没遇到过，可能是网络问题

**Comment by SEVEN-6174** [comment]
> 没遇到过，可能是网络问题

过了几天就好了
（触发的原因应该是切换go-cqhttp的账号选择清理缓存，然后头像就没了，过个几天就下载回来了）

**Comment by SEVEN-6174** [comment]
> 没遇到过，可能是网络问题

过了几天就好了
（触发的原因应该是切换go-cqhttp的账号选择清理缓存，然后头像就没了，过个几天就下载回来了）

**Comment by SEVEN-6174** [comment]
> 没遇到过，可能是网络问题

过了几天就好了
（触发的原因应该是切换go-cqhttp的账号选择清理缓存，然后头像就没了，过个几天就下载回来了）

**Comment by SEVEN-6174** [comment]
> 有解决方案的时候踢我下

等了几天就没事了XD
