### ISSUE TITLE
问问云服务器上后台持久化运行问题

### ISSUE THREAD

**Issue by Qian033** [HibiKier/zhenxun_bot#997]
机器人在云服务器上搭建成功了，但所有运行都得保证在命令行不关闭的情况下在前台才能运行

想问问有没有dalao成功过  不需要挂着远程连接云服务器的窗口就可以后台持久化运行的  或者有类似的解决方法？

大感谢！

**Comment by LambdaYH** [comment]
但凡看了文档都不会存在这个issue（

**Comment by ID114514** [comment]
......
