### ISSUE TITLE
使用poetry install安装 • Installing jieba (0.42.1)   • Installing playwright (1.24.1)时出现报错

### ISSUE THREAD

**Issue by beiyaohhhc** [HibiKier/zhenxun_bot#999]
### 错误截图
![image](https://user-images.githubusercontent.com/98569420/184813841-208ade9e-3c26-43d3-b78a-1fd17407fb1d.png)

[img]

### 日志截图

[img]

### 错误说明

发生了poetry instal安装 Installing jieba (0.42.1)   • Installing playwright (1.24.1)错误...

**Comment by beiyaohhhc** [comment]
已经试过删除poetry.lock 依然这样 python版本为3.9.13

**Comment by HibiKier** [comment]
别用py3.10
